Repository matomo-org/matomo, pull requests merged in 2018-06, with the labels that each got.

#13027 Fix some UI tests, including random failure + allow --piwik-domain use in tests:run-ui
  plugins/Feedback/templates/index.twig
  plugins/TestRunner/Commands/TestsRunUI.php
  plugins/TestRunner/Commands/TestsSetupFixture.php
  tests/PHPUnit/Fixtures/UITestFixture.php
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard3.png
  tests/UI/expected-screenshots/UIIntegrationTest_feedback_form.png
  tests/UI/specs/UIIntegration_spec.js
  tests/lib/screenshot-testing/support/test-environment.js
Labels: Regression, c: Tests & QA, not-in-changelog

#13032 Avoid too many DB connections error in tests
  tests/PHPUnit/Framework/TestCase/IntegrationTestCase.php
Labels: Needs Review

#12985 Show database update screen for non API calls to API module
  plugins/CoreUpdater/CoreUpdater.php
  plugins/CoreUpdater/tests/UI/expected-screenshots/CoreUpdaterDb_CoreUpdater.API.ErrorMessageCSV.txt
  plugins/CoreUpdater/tests/UI/expected-screenshots/CoreUpdaterDb_CoreUpdater.API.ErrorMessageJSON.txt
  plugins/CoreUpdater/tests/UI/expected-screenshots/CoreUpdaterDb_CoreUpdater.API.ErrorMessagePHP.txt
  plugins/CoreUpdater/tests/UI/expected-screenshots/CoreUpdaterDb_CoreUpdater.API.ErrorMessageTSV.txt
  plugins/CoreUpdater/tests/UI/expected-screenshots/CoreUpdaterDb_CoreUpdater.API.ErrorMessageXML.txt
Labels: Bug, Needs Review

#13049 Do not link empty action urls in real time widget
  plugins/Live/templates/getLastVisitsStart.twig
Labels: Needs Review, c: Usability

#12987 Adds option to format metrics in export overlay
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/angularjs/report-export/reportexport.directive.js
  plugins/CoreHome/angularjs/report-export/reportexport.popover.html
  plugins/CoreHome/angularjs/report-export/reportexport.popover.less
  plugins/CoreHome/lang/en.json
  tests/UI/expected-screenshots/ViewDataTableTest_export_options.png
  tests/UI/specs/ReportExporting_spec.js
Labels: Needs Review, not-in-changelog

#12885 Make some menus translatable
  CHANGELOG.md
  core/Plugin/Menu.php
  lang/en.json
  plugins/API/Menu.php
  plugins/CoreAdminHome/lang/en.json
  plugins/CustomVariables/Menu.php
  plugins/ExamplePlugin/Menu.php
  plugins/ExampleUI/Menu.php
  plugins/ExampleUI/lang/en.json
  plugins/Morpheus/Menu.php
  plugins/PrivacyManager/Menu.php
  plugins/PrivacyManager/lang/en.json
Labels: Needs Review, c: i18n

#13041 Fixxes a problem with preused variable name in graph generating via API
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_scheduled_report_in_html_tables_and_graph__ScheduledReports.generateReport_week.original.html
  plugins/ImageGraph/StaticGraph/HorizontalBar.php
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_scheduled_report_in_html_tables_and_graph__ScheduledReports.generateReport_month.original.html
Labels: Needs Review

#12698 Removed '-' when editing password in users manager
  plugins/UsersManager/angularjs/manage-users/manage-users.controller.js
  plugins/UsersManager/templates/index.twig
Labels: Needs Review

#13053 Hide GeoIP2 server module settings by default
  plugins/GeoIp2/SystemSettings.php
  plugins/GeoIp2/lang/en.json
  tests/PHPUnit/System/expected/test_ImportLogs__CorePluginsAdmin.getSystemSettings.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits__CorePluginsAdmin.getSystemSettings.xml
  tests/PHPUnit/System/expected/test_noVisit_PeriodIsLast__CorePluginsAdmin.getSystemSettings.xml
  tests/PHPUnit/System/expected/test_noVisit__CorePluginsAdmin.getSystemSettings.xml
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_settings_general.png
Labels: Needs Review

#12128 Allow to provide secondary sort column for reports
  core/API/DataTableGenericFilter.php
  core/DataTable/Filter/Sort.php
  core/Plugin/Report.php
  tests/PHPUnit/Unit/DataTable/Filter/SortTest.php
Labels: Enhancement, Needs Review, c: Platform

#12546 Remove usage of synchronous ajax requests
  CHANGELOG.md
  plugins/Annotations/javascripts/annotations.js
  plugins/CoreHome/javascripts/corehome.js
  plugins/CoreHome/javascripts/dataTable.js
  plugins/CoreHome/javascripts/dataTable_rowactions.js
  plugins/CoreHome/javascripts/popover.js
  plugins/DBStats/templates/index.twig
  plugins/Dashboard/javascripts/dashboard.js
  plugins/Dashboard/javascripts/dashboardObject.js
  plugins/Dashboard/javascripts/dashboardWidget.js
  plugins/Dashboard/javascripts/widgetMenu.js
  plugins/Dashboard/templates/embeddedIndex.twig
  plugins/Live/javascripts/SegmentedVisitorLog.js
  plugins/Live/javascripts/live.js
  plugins/Live/templates/index.twig
  plugins/Morpheus/javascripts/ajaxHelper.js
  plugins/Overlay/javascripts/Piwik_Overlay.js
  plugins/SEO/javascripts/rank.js
  plugins/SegmentEditor/javascripts/Segmentation.js
  plugins/Transitions/javascripts/transitions.js
  plugins/Widgetize/angularjs/widget-preview/widget-preview.directive.js
  tests/UI/specs/UIIntegration_spec.js
  tests/lib/screenshot-testing/support/page-renderer.js
Labels: Needs Review

#11885 Fix #11596: Compatibility of Piwik with MySQL Group Replication and MySQL InnoDB Cluster
  core/Db/Schema/Mysql.php
  core/Updates/3.6.0-b1.php
  core/Version.php
Labels: Needs Review, Pull Request WIP

#13063 Fix update for case where site_setting still has idsite AUTO_INCREMENT.
  core/Updates/3.6.0-b1.php
Labels: not-in-changelog

#13067 Fix undefined variable
  plugins/CoreAdminHome/OptOutManager.php
Labels: Bug

#12363 Deprecates the `historyService` along with `broadcast.init`, `broadcast.propagateAjax`, `broadcast.pageLoad`
  CHANGELOG.md
  plugins/CoreHome/angularjs/history/history.service.js
  plugins/CoreHome/javascripts/broadcast.js
  plugins/Dashboard/templates/_header.twig
  plugins/Overlay/javascripts/Piwik_Overlay.js
Labels: Needs Review

#13072 [automatic translation update] Updated 666 strings in 7 languages (da, de, fr, pl, pt, el, ja)
  lang/da.json
  lang/de.json
  lang/fr.json
  lang/pl.json
  plugins/API/lang/da.json
  plugins/API/lang/de.json
  plugins/API/lang/fr.json
  plugins/API/lang/pt.json
  plugins/Actions/lang/da.json
  plugins/Actions/lang/fr.json
  plugins/Contents/lang/pt.json
  plugins/CoreAdminHome/lang/da.json
  plugins/CoreAdminHome/lang/de.json
  plugins/CoreAdminHome/lang/el.json
  plugins/CoreAdminHome/lang/fr.json
  plugins/CoreAdminHome/lang/pl.json
  plugins/CoreHome/lang/da.json
  plugins/CoreHome/lang/de.json
  plugins/CoreHome/lang/fr.json
  plugins/CoreHome/lang/ja.json
  plugins/CoreHome/lang/pl.json
  plugins/CorePluginsAdmin/lang/pt.json
  plugins/CoreUpdater/lang/pt.json
  plugins/DevicePlugins/lang/pt.json
  plugins/DevicesDetection/lang/de.json
  plugins/DevicesDetection/lang/pt.json
  plugins/Ecommerce/lang/pt.json
  plugins/Events/lang/pt.json
  plugins/Feedback/lang/da.json
  plugins/Feedback/lang/pt.json
  plugins/GeoIp2/lang/de.json
  plugins/GeoIp2/lang/el.json
  plugins/GeoIp2/lang/fr.json
  plugins/GeoIp2/lang/ja.json
  plugins/Goals/lang/da.json
  plugins/Goals/lang/pt.json
  plugins/ImageGraph/lang/pt.json
  plugins/Insights/lang/pt.json
  plugins/Installation/lang/da.json
  plugins/LanguagesManager/lang/pt.json
  plugins/Live/lang/de.json
  plugins/Live/lang/el.json
  plugins/Live/lang/pl.json
  plugins/Live/lang/pt.json
  plugins/Login/lang/pt.json
  plugins/Marketplace/lang/da.json
  plugins/Marketplace/lang/pt.json
  plugins/MobileMessaging/lang/ja.json
  plugins/Overlay/lang/pt.json
  plugins/PrivacyManager/lang/da.json
  plugins/PrivacyManager/lang/de.json
  plugins/PrivacyManager/lang/fr.json
  plugins/PrivacyManager/lang/pl.json
  plugins/PrivacyManager/lang/pt.json
  plugins/Referrers/lang/da.json
  plugins/SitesManager/lang/de.json
  plugins/SitesManager/lang/fr.json
  plugins/SitesManager/lang/pl.json
  plugins/VisitorInterest/lang/fr.json
Labels: c: i18n

#12066 replace sparkline library with modern equivalent
  LEGALNOTICE
  composer.json
  composer.lock
  core/Visualization/Sparkline.php
  libs/sparkline/CHANGES
  libs/sparkline/DESIGN
  libs/sparkline/LICENSE-BSD.txt
  libs/sparkline/README
  libs/sparkline/gpl-2.0.txt
  libs/sparkline/lib/Sparkline.php
  libs/sparkline/lib/SparklineObject.php
  libs/sparkline/lib/Sparkline_Bar.php
  libs/sparkline/lib/Sparkline_Line.php
  plugins/CoreHome/DataTableRowAction/RowEvolution.php
  plugins/CoreHome/javascripts/sparkline.js
  plugins/CoreHome/stylesheets/sparklineColors.less
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_reset.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_rowevolution.png
  plugins/MultiSites/tests/UI/expected-screenshots/MultiSitesTest_all_websites.png
  plugins/MultiSites/tests/UI/expected-screenshots/MultiSitesTest_all_websites_changed_sort_order.png
  plugins/MultiSites/tests/UI/expected-screenshots/MultiSitesTest_all_websites_page_1.png
  plugins/MultiSites/tests/UI/expected-screenshots/MultiSitesTest_all_websites_search.png
  plugins/Overlay/tests/UI/expected-screenshots/Overlay_row_evolution.png
  tests/PHPUnit/Framework/TestingEnvironmentManipulator.php
  tests/UI/expected-screenshots/RowEvolution_multirow_evolution.png
  tests/UI/expected-screenshots/RowEvolution_multirow_evolution_other_metric.png
  tests/UI/expected-screenshots/RowEvolution_row_evolution.png
  tests/UI/expected-screenshots/RowEvolution_row_evolution_ecommerce_item.png
  tests/UI/expected-screenshots/RowEvolution_row_evolution_multiple_series.png
  tests/UI/expected-screenshots/RowEvolution_row_evolution_other_metric.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard2.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard4.png
  tests/UI/expected-screenshots/UIIntegrationTest_ecommerce_overview.png
  tests/UI/expected-screenshots/UIIntegrationTest_exampleui_sparklines.png
  tests/UI/expected-screenshots/UIIntegrationTest_goals_ecommerce.png
  tests/UI/expected-screenshots/UIIntegrationTest_goals_individual_goal.png
  tests/UI/expected-screenshots/UIIntegrationTest_goals_individual_goal_updated.png
  tests/UI/expected-screenshots/UIIntegrationTest_goals_individual_row_evolution.png
  tests/UI/expected-screenshots/UIIntegrationTest_goals_overview.png
  tests/UI/expected-screenshots/UIIntegrationTest_referrers_overview.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_engagement.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_locations_provider.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_overview.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_overview_reloaded.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_overview_segment.png
  tests/UI/expected-screenshots/UIIntegrationTest_widgetize_allwebsites.png
Labels: Needs Review

#12730 Prevent caching of tracker in proxies
  CHANGELOG.md
  core/Tracker/Response.php
  plugins/Installation/tests/System/APITest.php
  tests/PHPUnit/Framework/Constraint/HttpResponseText.php
  tests/PHPUnit/Framework/Constraint/ResponseCode.php
  tests/PHPUnit/Framework/TestCase/SystemTestCase.php
  tests/PHPUnit/System/TrackerResponseTest.php
Labels: Needs Review

#13077 Format metrics in row evolution popover correctly
  plugins/CoreHome/DataTableRowAction/RowEvolution.php
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_rowevolution.png
  plugins/Overlay/tests/UI/expected-screenshots/Overlay_row_evolution.png
  tests/UI/expected-screenshots/RowEvolution_row_evolution.png
  tests/UI/expected-screenshots/RowEvolution_row_evolution_ecommerce_item.png
  tests/UI/expected-screenshots/RowEvolution_row_evolution_multiple_series.png
  tests/UI/expected-screenshots/RowEvolution_row_evolution_other_metric.png
  tests/UI/expected-screenshots/UIIntegrationTest_goals_individual_row_evolution.png
Labels: Needs Review, not-in-changelog

#13083 minor sparkline improvement (line thickness)
  core/Visualization/Sparkline.php
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_reset.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_rowevolution.png
  plugins/MultiSites/tests/UI/expected-screenshots/MultiSitesTest_all_websites.png
  plugins/MultiSites/tests/UI/expected-screenshots/MultiSitesTest_all_websites_changed_sort_order.png
  plugins/MultiSites/tests/UI/expected-screenshots/MultiSitesTest_all_websites_page_1.png
  plugins/MultiSites/tests/UI/expected-screenshots/MultiSitesTest_all_websites_search.png
  plugins/Overlay/tests/UI/expected-screenshots/Overlay_row_evolution.png
  tests/UI/expected-screenshots/RowEvolution_multirow_evolution.png
  tests/UI/expected-screenshots/RowEvolution_multirow_evolution_other_metric.png
  tests/UI/expected-screenshots/RowEvolution_row_evolution.png
  tests/UI/expected-screenshots/RowEvolution_row_evolution_ecommerce_item.png
  tests/UI/expected-screenshots/RowEvolution_row_evolution_multiple_series.png
  tests/UI/expected-screenshots/RowEvolution_row_evolution_other_metric.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard2.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard4.png
  tests/UI/expected-screenshots/UIIntegrationTest_ecommerce_overview.png
  tests/UI/expected-screenshots/UIIntegrationTest_exampleui_sparklines.png
  tests/UI/expected-screenshots/UIIntegrationTest_goals_ecommerce.png
  tests/UI/expected-screenshots/UIIntegrationTest_goals_individual_goal.png
  tests/UI/expected-screenshots/UIIntegrationTest_goals_individual_goal_updated.png
  tests/UI/expected-screenshots/UIIntegrationTest_goals_individual_row_evolution.png
  tests/UI/expected-screenshots/UIIntegrationTest_goals_overview.png
  tests/UI/expected-screenshots/UIIntegrationTest_referrers_overview.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_engagement.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_locations_provider.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_overview.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_overview_reloaded.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_overview_segment.png
  tests/UI/expected-screenshots/UIIntegrationTest_widgetize_allwebsites.png
Labels: not-in-changelog

#13082 ignore custom svg files
  config/global.php
Labels: not-in-changelog

#13087 Adds missing default value for addEventListener
  js/piwik.js
  js/piwik.min.js
  piwik.js
Labels: Needs Review, not-in-changelog

#12902 Update widget title when switching to related report
  plugins/CoreHome/javascripts/dataTable.js
Labels: Needs Review, not-in-changelog

#13064 Validate premium feature license correctly when cancelled
  core/Plugin.php
  core/Plugin/Manager.php
  plugins/Marketplace/Controller.php
  plugins/Marketplace/Marketplace.php
  plugins/Marketplace/Plugins.php
  plugins/Marketplace/Plugins/InvalidLicenses.php
  plugins/Marketplace/lang/en.json
  plugins/Marketplace/tests/Integration/Plugins/InvalidLicensesTest.php
  plugins/Marketplace/tests/Integration/PluginsTest.php
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_notification_plugincheck_noLicense.png
  plugins/Marketplace/tests/resources/v2.0_plugins-purchase_type-paid-access_token-consumer1_paid2_custom1.json
  plugins/Marketplace/tests/resources/v2.0_plugins-purchase_type-paid-num_users-201-access_token-consumer1_paid2_custom1.json
  tests/PHPUnit/Integration/Plugin/ManagerTest.php
Labels: Needs Review

#13089 Clear up some confusing code
  core/Tracker/TableLogAction.php
Labels: Needs Review, not-in-changelog

#13075 Ignore IP Whitelist for Opt Out IFrame
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/LoginWhitelist.php
Labels: Needs Review, not-in-changelog

#13100 Use translation for console update success message
  plugins/CoreUpdater/Commands/Update.php
  plugins/CoreUpdater/lang/en.json
  plugins/CoreUpdater/tests/Integration/Commands/UpdateTest.php
Labels: Needs Review, not-in-changelog

#13088 Use saved ViewDataTable parameters mechanism for datatables displayed inside a widget container.
  core/ViewDataTable/Factory.php
  core/ViewDataTable/Manager.php
  plugins/CoreHome/Controller.php
  plugins/CoreHome/angularjs/widget/widget.directive.js
  plugins/CoreHome/javascripts/dataTable.js
Labels: Needs Review, not-in-changelog

#13102 ensure Updater::getComponentUpdates returns null if no update is available
  core/Updater.php
Labels: Needs Review, not-in-changelog

#13094 Update cacert.pem
  core/DataFiles/cacert.pem
Labels: Needs Review, c: Security
