Repository matomo-org/matomo, pull requests merged in 2018-05, with the labels that each got.

#12800 Automatically initialize title tooltips after loading a report
  plugins/CoreHome/angularjs/widget/widget.directive.js
  tests/UI/specs/UIIntegration_spec.js
Labels: Needs Review, not-in-changelog

#12787 Prevent tracking failures when invalid goal patterns are defined
  core/Tracker/GoalManager.php
Labels: Needs Review

#12786 Adds check for correct parameter type to prevent possible php error
  plugins/CoreHome/DataTableRowAction/RowEvolution.php
Labels: Needs Review, not-in-changelog

#12802 Add new embed icon
  LEGALNOTICE
  plugins/Morpheus/fonts/matomo.svg
  plugins/Morpheus/fonts/matomo.ttf
  plugins/Morpheus/fonts/matomo.woff
  plugins/Morpheus/fonts/selection.json
  plugins/Morpheus/stylesheets/base/icons.css
  plugins/Morpheus/templates/demo.twig
  plugins/Morpheus/tests/UI/expected-screenshots/Morpheus_load.png
Labels: Needs Review

#12796 Convert comma separated param values to arrays if needed
  core/Plugin/ViewDataTable.php
Labels: Needs Review, not-in-changelog

#12798 Show number of Goals created in the System summary widget
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_removed.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_loaded_token_auth.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_removed.png
  plugins/Goals/Goals.php
  plugins/Goals/Model.php
  plugins/Goals/lang/en.json
  tests/UI/expected-screenshots/EmptySite_emptySiteDashboard_ignored.png
  tests/UI/expected-screenshots/Theme_home.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_home.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard1.png
Labels: Needs Review, not-in-changelog

#12659 Improve realtime visitor log widget
  plugins/Live/Controller.php
  plugins/Live/javascripts/live.js
  plugins/Live/stylesheets/live.less
  plugins/Live/templates/getLastVisitsStart.twig
  plugins/Referrers/templates/_visitorDetails.twig
Labels: Needs Review, not-in-changelog

#12807 Added new setting field to configure multiple values
  CHANGELOG.md
  core/Db/Schema/Mysql.php
  core/Settings/FieldConfig.php
  core/Settings/FieldConfig/MultiPair.php
  core/Settings/Setting.php
  core/Settings/Storage/Backend/MeasurableSettingsTable.php
  core/Settings/Storage/Backend/PluginSettingsTable.php
  core/Updates/3.0.0-b1.php
  core/Updates/3.5.0-b4.php
  core/Version.php
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/angularjs/common/directives/attributes.js
  plugins/CoreHome/angularjs/multipairfield/multipairfield.controller.js
  plugins/CoreHome/angularjs/multipairfield/multipairfield.directive.html
  plugins/CoreHome/angularjs/multipairfield/multipairfield.directive.js
  plugins/CoreHome/angularjs/multipairfield/multipairfield.directive.less
  plugins/CorePluginsAdmin/angularjs/field/field.directive.js
  plugins/CorePluginsAdmin/angularjs/form-field/field-multituple.html
  plugins/Morpheus/templates/demo.twig
  plugins/Morpheus/tests/UI/expected-screenshots/Morpheus_load.png
  tests/PHPUnit/Integration/Settings/Storage/Backend/MeasurableSettingsTableTest.php
  tests/PHPUnit/Integration/Settings/Storage/Backend/PluginSettingsTableTest.php
Labels: Needs Review

#12534 Show city / country in visitor details
  plugins/Actions/tests/UI/expected-screenshots/ActionsDataTable_segmented_visitor_log.png
  plugins/Live/stylesheets/live.less
  plugins/Live/templates/_visitorDetails.twig
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_log.png
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_log_expand_actions.png
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_profile.png
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_profile_action_details.png
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_profile_actions_hidden.png
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_profile_visit_details.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_visits_showprofile.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard2.png
  tests/UI/expected-screenshots/UIIntegrationTest_ecommerce_log.png
  tests/UI/expected-screenshots/UIIntegrationTest_ecommerce_log_segmented.png
  tests/UI/expected-screenshots/UIIntegrationTest_segmented_visitorlog.png
  tests/UI/expected-screenshots/UIIntegrationTest_widgetize_ecommercelog.png
  tests/UI/expected-screenshots/UIIntegrationTest_widgetize_visitor_log.png
Labels: Needs Review

#12788 Validate goal pattern and type in API
  core/Tracker/GoalManager.php
  core/Validators/Regex.php
  lang/en.json
  plugins/Goals/API.php
  plugins/Goals/tests/Integration/APITest.php
Labels: Needs Review

#12790 Do not show 'all' limit selector option for VisitorLog & default to 25 if filter_limit=-1 used
  CHANGELOG.md
  core/ViewDataTable/Config.php
  plugins/Actions/tests/UI/expected-screenshots/ActionsDataTable_segmented_visitor_log.png
  plugins/CoreHome/javascripts/dataTable.js
  plugins/Live/Visualizations/VisitorLog.php
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_log.png
  tests/UI/expected-screenshots/UIIntegrationTest_segmented_visitorlog.png
  tests/UI/expected-screenshots/UIIntegrationTest_widgetize_ecommercelog.png
  tests/UI/expected-screenshots/UIIntegrationTest_widgetize_visitor_log.png
Labels: Needs Review, not-in-changelog

#12817 Adds "keyword not defined" tooltips
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_log.png
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_log_expand_actions.png
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_profile_action_details.png
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_profile_visit_details.png
  plugins/Referrers/templates/_visitorDetails.twig
Labels: Needs Review, not-in-changelog

#12821 Fixing some missing information in SEO Rankings widget
  plugins/SEO/Metric/DomainAge.php
  plugins/SEO/Metric/Google.php
Labels: Bug

#12831 updates php-di package
  composer.lock
Labels: Needs Review, Task, c: Performance

#12828 Show activity indicator only for plugin settings that is being updated
  plugins/CorePluginsAdmin/angularjs/plugin-settings/plugin-settings.controller.js
  plugins/CorePluginsAdmin/angularjs/plugin-settings/plugin-settings.directive.html
Labels: Needs Review

#12827 Fix always all plugin settings are saved in the backend
  plugins/CorePluginsAdmin/API.php
Labels: Needs Review

#12838 Correctly name and describe userid pseudonymization feature.
  plugins/PrivacyManager/lang/en.json
  plugins/PrivacyManager/templates/privacySettings.twig
Labels: Needs Review, c: Design / UI, not-in-changelog

#12833 fix typos and style issues in GDPR Overview
  plugins/PrivacyManager/templates/gdprOverview.twig
Labels: Needs Review, not-in-changelog

#12843 Fix icon alignment in realtime log
  plugins/Live/stylesheets/live.less
Labels: Regression, not-in-changelog

#12850 Added missing translation key
  plugins/CoreHome/CoreHome.php
Labels: Needs Review

#12854 Prevent possible view access error
  plugins/Live/Model.php
Labels: Needs Review

#12844 Use extra salt stored in database for userid anonymization
  core/Updates/3.5.0-rc2.php
  plugins/PrivacyManager/PrivacyManager.php
  plugins/PrivacyManager/Tracker/RequestProcessor.php
  plugins/PrivacyManager/tests/Integration/Dao/LogDataAnonymizerTest.php
  plugins/PrivacyManager/tests/Integration/Tracker/RequestProcessorTest.php
  plugins/PrivacyManager/tests/System/AnonymizationTest.php
  plugins/PrivacyManager/tests/System/expected/anonymizeVisitInformation_anonymizeUserId.json
  plugins/PrivacyManager/tests/System/expected/test_userIdAnonymized__Live.getLastVisitsDetails_year.xml
Labels: Needs Review

#12856 Tweak the text of both pseudo anonymize user id sections in the privacy page.
  plugins/PrivacyManager/angularjs/anonymize-log-data/anonymize-log-data.directive.html
  plugins/PrivacyManager/lang/en.json
Labels: not-in-changelog

#12890 Update Intl translations to CLDR 33
  plugins/Intl/lang/am.json
  plugins/Intl/lang/ar.json
  plugins/Intl/lang/be.json
  plugins/Intl/lang/bg.json
  plugins/Intl/lang/bn.json
  plugins/Intl/lang/bs.json
  plugins/Intl/lang/ca.json
  plugins/Intl/lang/cy.json
  plugins/Intl/lang/da.json
  plugins/Intl/lang/de.json
  plugins/Intl/lang/el.json
  plugins/Intl/lang/es.json
  plugins/Intl/lang/et.json
  plugins/Intl/lang/eu.json
  plugins/Intl/lang/fa.json
  plugins/Intl/lang/fi.json
  plugins/Intl/lang/fr.json
  plugins/Intl/lang/gl.json
  plugins/Intl/lang/he.json
  plugins/Intl/lang/hi.json
  plugins/Intl/lang/hr.json
  plugins/Intl/lang/hu.json
  plugins/Intl/lang/id.json
  plugins/Intl/lang/is.json
  plugins/Intl/lang/it.json
  plugins/Intl/lang/ja.json
  plugins/Intl/lang/ka.json
  plugins/Intl/lang/lv.json
  plugins/Intl/lang/nb.json
  plugins/Intl/lang/nl.json
  plugins/Intl/lang/nn.json
  plugins/Intl/lang/pl.json
  plugins/Intl/lang/pt-br.json
  plugins/Intl/lang/pt.json
  plugins/Intl/lang/ro.json
  plugins/Intl/lang/ru.json
  plugins/Intl/lang/sk.json
  plugins/Intl/lang/sl.json
  plugins/Intl/lang/sq.json
  plugins/Intl/lang/sr.json
  plugins/Intl/lang/sv.json
  plugins/Intl/lang/te.json
  plugins/Intl/lang/th.json
  plugins/Intl/lang/tl.json
  plugins/Intl/lang/tr.json
  plugins/Intl/lang/uk.json
  plugins/Intl/lang/vi.json
  plugins/Intl/lang/zh-cn.json
  plugins/Intl/lang/zh-tw.json
  tests/PHPUnit/Integration/NumberFormatterTest.php
Labels: c: i18n

#12912 [automatic translation update] Updated 273 strings in 13 languages (ar, da, de, fa, fr, hu, pl, pt-br, pt, sq, tr, zh-tw, el)
  lang/da.json
  lang/de.json
  lang/fa.json
  lang/fr.json
  lang/hu.json
  lang/pl.json
  lang/pt-br.json
  lang/pt.json
  lang/sq.json
  lang/tr.json
  lang/zh-tw.json
  plugins/API/lang/pt-br.json
  plugins/Actions/lang/da.json
  plugins/Actions/lang/pt-br.json
  plugins/Contents/lang/pt-br.json
  plugins/CoreAdminHome/lang/da.json
  plugins/CoreAdminHome/lang/de.json
  plugins/CoreAdminHome/lang/fr.json
  plugins/CoreAdminHome/lang/zh-tw.json
  plugins/CoreHome/lang/fr.json
  plugins/CorePluginsAdmin/lang/da.json
  plugins/CoreUpdater/lang/da.json
  plugins/Goals/lang/da.json
  plugins/Goals/lang/fr.json
  plugins/Goals/lang/sq.json
  plugins/Goals/lang/zh-tw.json
  plugins/ImageGraph/lang/ar.json
  plugins/Installation/lang/ar.json
  plugins/Installation/lang/da.json
  plugins/Installation/lang/de.json
  plugins/Installation/lang/fr.json
  plugins/LanguagesManager/lang/da.json
  plugins/Live/lang/pt-br.json
  plugins/Login/lang/da.json
  plugins/Overlay/lang/pt-br.json
  plugins/PrivacyManager/lang/da.json
  plugins/PrivacyManager/lang/de.json
  plugins/PrivacyManager/lang/el.json
  plugins/PrivacyManager/lang/fr.json
  plugins/PrivacyManager/lang/pl.json
  plugins/PrivacyManager/lang/sq.json
  plugins/PrivacyManager/lang/tr.json
  plugins/PrivacyManager/lang/zh-tw.json
  plugins/SEO/lang/da.json
  plugins/SitesManager/lang/da.json
  plugins/UserCountry/lang/de.json
  plugins/UserCountry/lang/el.json
  plugins/UserCountry/lang/fr.json
  plugins/UserCountry/lang/pl.json
  plugins/UserCountry/lang/sq.json
  plugins/UserCountry/lang/tr.json
  plugins/UserCountry/lang/zh-tw.json
  plugins/UsersManager/lang/da.json
  plugins/VisitFrequency/lang/pt-br.json
  plugins/VisitsSummary/lang/pt-br.json
Labels: c: i18n

#12913 Add new method to detect if root request is an API request
  CHANGELOG.md
  core/API/Request.php
  plugins/API/API.php
  plugins/PrivacyManager/templates/gdprOverview.twig
Labels: Needs Review

#12910 Prevent possible fatal when showing deleted goals in visitor profile
  plugins/Live/templates/_profileSummary.twig
Labels: Bug, Needs Review

#12898 Improve UI/UX of report help
  plugins/CoreHome/angularjs/enrichedheadline/enrichedheadline.directive.html
  plugins/CoreHome/angularjs/enrichedheadline/enrichedheadline.directive.less
Labels: Needs Review, c: Design / UI, not-in-changelog

#12882 Fix unique visitors not shown on city map
  lang/en.json
  plugins/UserCountryMap/Controller.php
  plugins/UserCountryMap/javascripts/visitor-map.js
Labels: Needs Review, not-in-changelog

#12931 Fix failing system test.
  tests/PHPUnit/System/TrackerResponseTest.php
Labels: c: Tests & QA, not-in-changelog

#12929 Better group by in actions archiver
  plugins/Actions/Archiver.php
Labels: Needs Review

#12911 Improve report documentation of search keywords report
  plugins/Referrers/Reports/GetKeywords.php
  plugins/Referrers/lang/en.json
Labels: Needs Review

#12941 Disallow change of GeoIp2 server variables if GeoLocation admin is disabled
  plugins/GeoIp2/SystemSettings.php
Labels: Needs Review

#12944 Fix DI is not used in tracker updater command
  plugins/CustomPiwikJs/Commands/UpdateTracker.php
Labels: Bug, Needs Review

#12945 Add possibility to trigger the archiving only for a specific plugin
  core/ArchiveProcessor/Parameters.php
  core/ArchiveProcessor/PluginsArchiver.php
Labels: Needs Review, c: Platform

#12947 Fixed undefined APIRequest in Visualization.php
  core/Plugin/Visualization.php
Labels: Bug

#12878 Adds message about data retention on gdpr overview
  config/global.ini.php
  core/Tracker/Model.php
  plugins/PrivacyManager/API.php
  plugins/PrivacyManager/Commands/AnonymizeRawData.php
  plugins/PrivacyManager/Controller.php
  plugins/PrivacyManager/PrivacyManager.php
  plugins/PrivacyManager/lang/en.json
  plugins/PrivacyManager/stylesheets/gdprOverview.less
  plugins/PrivacyManager/templates/gdprOverview.twig
  plugins/PrivacyManager/templates/privacySettings.twig
  plugins/PrivacyManager/tests/Integration/DataPurgingTest.php
  plugins/PrivacyManager/tests/UI/PrivacyManager_spec.js
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_anonymizelogdata_anonymizeip_and_visit_column_cancelled.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_anonymizelogdata_anonymizeip_and_visit_column_confirmed.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_anonymizelogdata_anonymizeip_and_visit_column_prefilled.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_anonymizelogdata_anonymizelocation_anduserid_and_action_column_confirmed.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_anonymizelogdata_anonymizelocation_anduserid_and_action_column_prefilled.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_anonymizelogdata_one_site_and_custom_date_confirmed.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_anonymizelogdata_one_site_and_custom_date_prefilled.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_overview.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_overview_no_retention.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_privacy_settings_default.png
  plugins/UserCountry/Commands/AttributeHistoricalDataWithLocations.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_settings_general.png
Labels: Needs Review, not-in-changelog

#12939 Ensure no tooltip is shown in opened limit selection
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/javascripts/dataTable.js
  plugins/CoreHome/templates/_dataTableFooter.twig
Labels: Needs Review, c: Design / UI, not-in-changelog

#12953 Allow numbers in css font family for opt out iframe
  plugins/CoreAdminHome/OptOutManager.php
Labels: Needs Review

#12952 Make sendContentAsDownload method reusable
  plugins/Morpheus/javascripts/piwikHelper.js
  plugins/PrivacyManager/angularjs/manage-gdpr/managegdpr.controller.js
Labels: Needs Review, not-in-changelog

#12897 Adds update script to remove GeoIP2 plugin from marketplace
  core/Updates/3.5.1-b1.php
  core/Version.php
  plugins/GeoIp2/tests/Integration/LocationProviderTest.php
  plugins/GeoIp2/tests/Integration/UpdateTest.php
Labels: Needs Review, not-in-changelog

#12967 Slightly faster location provider instance creation
  plugins/UserCountry/LocationProvider.php
Labels: Needs Review, c: Performance

#12950 Rename Actions category to Behavior + Referrers category to Acquisition
  core/Category/Category.php
  plugins/API/WidgetMetadata.php
  plugins/Actions/lang/en.json
  plugins/CoreHome/Categories/ActionsCategory.php
  plugins/Dashboard/tests/UI/Dashboard_spec.js
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_create_new.png
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_expanded.png
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_removed.png
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_widget_list_shown.png
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_widget_preview.png
  plugins/Referrers/Categories/ReferrersCategory.php
  plugins/Referrers/lang/en.json
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getReportPagesMetadata.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getWidgetMetadata.xml
  tests/PHPUnit/Unit/Category/CategoryTest.php
  tests/UI/expected-screenshots/EmptySite_emptySiteDashboard_ignored.png
  tests/UI/expected-screenshots/Menus_mainmenu_loaded.png
  tests/UI/expected-screenshots/Menus_mainmenu_lower_clicked.png
  tests/UI/expected-screenshots/Menus_mainmenu_upper_clicked.png
  tests/UI/expected-screenshots/QuickAccess_search_1.png
  tests/UI/expected-screenshots/QuickAccess_search_sites.png
  tests/UI/expected-screenshots/Theme_home.png
  tests/UI/expected-screenshots/UIIntegrationTest_period_select_date_range_click.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_overview_segment.png
  tests/UI/expected-screenshots/UIIntegrationTest_widgets_listing.png
Labels: Needs Review, not-in-changelog

#12984 Fix for non-test mode where test DI entry should not be available.
  plugins/Live/Model.php
Labels: not-in-changelog

#12884 Improves realtime widget
  plugins/Live/stylesheets/live.less
  plugins/Live/templates/_visitorDetails.twig
  plugins/Live/templates/_visitorLogIcons.twig
  plugins/Live/templates/getLastVisitsStart.twig
Labels: Needs Review

#12994 Replaces Piwik with Matomo in PRIVACY.md
  PRIVACY.md
Labels: Needs Review, Task

#12948 Allow segmented visitor log popup to launch visitor profile
  plugins/Actions/tests/UI/expected-screenshots/ActionsDataTable_segmented_visitor_log.png
  plugins/CoreHome/angularjs/popover-handler/popover-handler.directive.js
  plugins/CoreHome/javascripts/broadcast.js
  plugins/CoreHome/javascripts/dataTable_rowactions.js
  plugins/CoreHome/javascripts/popover.js
  plugins/Live/javascripts/SegmentedVisitorLog.js
  plugins/Live/javascripts/visitorLog.js
  plugins/Live/javascripts/visitorProfile.js
  plugins/Overlay/tests/UI/expected-screenshots/Overlay_row_evolution.png
  plugins/Overlay/tests/UI/expected-screenshots/Overlay_transitions.png
  tests/UI/expected-screenshots/RowEvolution_multirow_evolution_other_metric.png
  tests/UI/expected-screenshots/UIIntegrationTest_segmented_visitorlog.png
Labels: Enhancement, Needs Review, c: Design / UI, not-in-changelog

#12975 Show product name before product sku
  plugins/Ecommerce/Reports/GetItemsName.php
  plugins/Ecommerce/Reports/GetItemsSku.php
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_scheduled_report_in_csv__ScheduledReports.generateReport_week.original.csv
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_scheduled_report_in_html_tables_and_graph__ScheduledReports.generateReport_week.original.html
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_scheduled_report_in_html_tables_only__ScheduledReports.generateReport_week.original.html
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_scheduled_report_in_pdf_tables_only__ScheduledReports.generateReport_week.original.pdf
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getReportMetadata_day.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getReportPagesMetadata.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getWidgetMetadata.xml
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard3.png
  tests/UI/expected-screenshots/UIIntegrationTest_ecommerce_products.png
  tests/UI/expected-screenshots/UIIntegrationTest_email_reports_editor.png
Labels: Needs Review, not-in-changelog

#12996 Remove internal API example
  misc/others/api_internal_call.php
  tests/PHPUnit/System/ExternalScriptsTest.php
  tests/PHPUnit/proxy/include_single_file.php
Labels: Needs Review, c: Platform

#13001 Fix sales funnel row evolution
  plugins/API/API.php
Labels: Needs Review, not-in-changelog

#12958 Improved glossary and let plugins add items to it
  CHANGELOG.md
  plugins/API/Controller.php
  plugins/API/lang/en.json
  plugins/API/templates/glossary.twig
  plugins/API/templates/glossaryAdmin.twig
  plugins/API/templates/glossaryWidget.twig
  tests/UI/expected-screenshots/UIIntegrationTest_glossary.png
  tests/UI/expected-screenshots/UIIntegrationTest_glossary_widgetized.png
  tests/UI/specs/UIIntegration_spec.js
Labels: Enhancement, Needs Review

#13004 Added feature to optionally disable Schedule old data deletion feature
  config/global.ini.php
  plugins/PrivacyManager/PrivacyManager.php
  plugins/PrivacyManager/templates/privacySettings.twig
  plugins/PrivacyManager/tests/Integration/PrivacyManagerTest.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: Needs Review

#12997 Fix zen icon duplication after update check
  plugins/CoreHome/javascripts/corehome.js
Labels: Needs Review, not-in-changelog

#13012 Adds option to sync system test files command to directly copy files to expected directory
  plugins/CoreConsole/Commands/DevelopmentSyncProcessedSystemTests.php
Labels: c: Tests & QA, not-in-changelog

#13011 Add event to allow altering the request URL that CronArchive uses.
  core/CronArchive.php
Labels: Needs Review, not-in-changelog

#13009 Support both LFS pointers and full objects
  tests/PHPUnit/Integration/ReleaseCheckListTest.php
Labels: Needs Review

#13020 Fix typo "encountered"
  core/FrontController.php
Labels: not-in-changelog

#12727 Speed up package management on travis
  .travis.yml
Labels: Needs Review, c: Performance, c: Tests & QA
