Repository matomo-org/matomo, pull requests merged in 2018-02, with the labels that each got.

#12543 Possibility to login by email
  plugins/Login/Controller.php
  tests/UI/specs/Login_spec.js
Labels: Needs Review

#12556 Allow plugins to define custom action types
  CHANGELOG.md
  plugins/Actions/Actions.php
  plugins/Actions/Columns/ActionType.php
Labels: Needs Review

#12521 Add more date segments
  plugins/CoreHome/Columns/VisitLastActionDate.php
  plugins/CoreHome/Columns/VisitLastActionDayOfMonth.php
  plugins/CoreHome/Columns/VisitLastActionDayOfWeek.php
  plugins/CoreHome/Columns/VisitLastActionDayOfYear.php
  plugins/CoreHome/Columns/VisitLastActionMonth.php
  plugins/CoreHome/Columns/VisitLastActionQuarter.php
  plugins/CoreHome/Columns/VisitLastActionSecond.php
  plugins/CoreHome/Columns/VisitLastActionWeekOfYear.php
  plugins/CoreHome/Columns/VisitLastActionYear.php
  plugins/VisitTime/functions.php
  plugins/VisitTime/lang/en.json
  tests/PHPUnit/System/expected/test_AutoSuggestAPITest_visitEndServerDate__API.getSuggestedValuesForSegment.xml
  tests/PHPUnit/System/expected/test_AutoSuggestAPITest_visitEndServerDate__VisitsSummary.get_range.xml
  tests/PHPUnit/System/expected/test_AutoSuggestAPITest_visitEndServerDayOfMonth__API.getSuggestedValuesForSegment.xml
  tests/PHPUnit/System/expected/test_AutoSuggestAPITest_visitEndServerDayOfMonth__VisitsSummary.get_range.xml
  tests/PHPUnit/System/expected/test_AutoSuggestAPITest_visitEndServerDayOfWeek__API.getSuggestedValuesForSegment.xml
  tests/PHPUnit/System/expected/test_AutoSuggestAPITest_visitEndServerDayOfWeek__VisitsSummary.get_range.xml
  tests/PHPUnit/System/expected/test_AutoSuggestAPITest_visitEndServerDayOfYear__API.getSuggestedValuesForSegment.xml
  tests/PHPUnit/System/expected/test_AutoSuggestAPITest_visitEndServerDayOfYear__VisitsSummary.get_range.xml
  tests/PHPUnit/System/expected/test_AutoSuggestAPITest_visitEndServerMonth__API.getSuggestedValuesForSegment.xml
  tests/PHPUnit/System/expected/test_AutoSuggestAPITest_visitEndServerMonth__VisitsSummary.get_range.xml
  tests/PHPUnit/System/expected/test_AutoSuggestAPITest_visitEndServerQuarter__API.getSuggestedValuesForSegment.xml
  tests/PHPUnit/System/expected/test_AutoSuggestAPITest_visitEndServerQuarter__VisitsSummary.get_range.xml
  tests/PHPUnit/System/expected/test_AutoSuggestAPITest_visitEndServerSecond__API.getSuggestedValuesForSegment.xml
  tests/PHPUnit/System/expected/test_AutoSuggestAPITest_visitEndServerSecond__VisitsSummary.get_range.xml
  tests/PHPUnit/System/expected/test_AutoSuggestAPITest_visitEndServerWeekOfYear__API.getSuggestedValuesForSegment.xml
  tests/PHPUnit/System/expected/test_AutoSuggestAPITest_visitEndServerWeekOfYear__VisitsSummary.get_range.xml
  tests/PHPUnit/System/expected/test_AutoSuggestAPITest_visitEndServerYear__API.getSuggestedValuesForSegment.xml
  tests/PHPUnit/System/expected/test_AutoSuggestAPITest_visitEndServerYear__VisitsSummary.get_range.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getSegmentsMetadata.xml
Labels: Enhancement, Needs Review

#12561 Update error message in API/UI if date is before 1992 (#12559)
  core/Date.php
  lang/en.json
  tests/PHPUnit/Unit/PeriodTest.php
Labels: Needs Review

#12530 Fixes position of activity indicator
  plugins/CoreHome/angularjs/selector/selector.directive.less
Labels: c: Design / UI

#12570 DeviceDetection, display themed "refresh" button
  plugins/DevicesDetection/templates/detection.twig
Labels: c: Design / UI

#12406 Move methods away from Live controller
  plugins/Live/Controller.php
  plugins/Live/Live.php
  plugins/Live/ProfileSummaryProvider.php
  plugins/UserCountry/ProfileSummary/LocationSummary.php
Labels: Needs Review, not-in-changelog

#12545 JS Tracker: expected no warning in the console when addTracker multiple times
  js/piwik.js
  js/piwik.min.js
  piwik.js
Labels: Bug, Needs Review
