Repository matomo-org/matomo, pull requests merged in 2018-09, with the labels that each got.

#13342 Show confirm before changing a users password and show notification on save complete.
  plugins/UsersManager/UsersManager.php
  plugins/UsersManager/angularjs/user-edit-form/user-edit-form.component.html
  plugins/UsersManager/angularjs/user-edit-form/user-edit-form.component.js
  plugins/UsersManager/angularjs/user-edit-form/user-edit-form.component.less
  plugins/UsersManager/lang/en.json
Labels: Needs Review

#13312 Use font icon for visitorlog instead of images
  plugins/Ecommerce/templates/conversionOverview.twig
  plugins/Goals/templates/conversionOverview.twig
  plugins/Live/images/visitorlog-hover.png
  plugins/Live/images/visitorlog.png
  plugins/Live/stylesheets/live.less
  plugins/UserId/images/visitordetails-hover.png
  plugins/UserId/images/visitordetails.png
  plugins/UserId/javascripts/rowaction.js
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard2.png
  tests/UI/expected-screenshots/UIIntegrationTest_ecommerce_overview.png
  tests/UI/expected-screenshots/UIIntegrationTest_goals_ecommerce.png
  tests/UI/expected-screenshots/UIIntegrationTest_goals_individual_goal.png
  tests/UI/expected-screenshots/UIIntegrationTest_goals_individual_goal_updated.png
Labels: Needs Review, c: Design / UI, not-in-changelog

#13286 Stable sort for most frequent segment values
  plugins/API/API.php
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_actionUrl__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_browserCode__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_browserVersion__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_city__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_countryCode__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_customVariablePageName__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_customVariablePageValue2__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_customVariablePageValue5__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_customVariablePageValue__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_customVariableValue1__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_customVariableValue1__VisitsSummary.get_range.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_customVariableValue5__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_customVariableValue5__VisitsSummary.get_range.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_customVariableValue__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_customVariableValue__VisitsSummary.get_range.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_deviceBrand__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_deviceModel__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_downloadUrl__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_downloadUrl__VisitsSummary.get_range.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_eventAction__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_eventAction__VisitsSummary.get_range.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_eventCategory__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_eventCategory__VisitsSummary.get_range.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_eventName__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_eventName__VisitsSummary.get_range.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_eventValue__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_latitude__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_longitude__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_operatingSystemCode__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_operatingSystemVersion__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_outlinkUrl__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_outlinkUrl__VisitsSummary.get_range.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_regionCode__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_regionCode__VisitsSummary.get_range.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_visitIp__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_visitorId__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_visitorId__VisitsSummary.get_range.xml
  plugins/Actions/VisitorDetails.php
Labels: Needs Review, c: Tests & QA

#13335 Add [tests] config option to enable logging in tests.
  CHANGELOG.md
  config/environment/test.php
  config/global.ini.php
  plugins/Monolog/config/tracker.php
  plugins/Monolog/tests/Integration/LogTest.php
  plugins/Monolog/tests/System/TrackerLoggingTest.php
  plugins/TestRunner/Commands/TestsRun.php
  plugins/TestRunner/Commands/TestsRunUI.php
  plugins/TestRunner/Commands/TestsSetupFixture.php
  tests/PHPUnit/Framework/Fixture.php
  tests/PHPUnit/Framework/TestingEnvironmentManipulator.php
  tests/PHPUnit/Framework/TestingEnvironmentVariables.php
  tests/PHPUnit/Integration/ArchiveWebTest.php
  tests/PHPUnit/System/TrackerTest.php
  tests/lib/screenshot-testing/support/test-environment.js
Labels: Needs Review

#13319 Couple test related changes for tests that load multiple other plugins
  plugins/TestRunner/Commands/TestsSetupFixture.php
  tests/PHPUnit/Framework/Fixture.php
  tests/PHPUnit/Framework/TestingEnvironmentManipulator.php
Labels: Needs Review

#13390 Make sure UserTableFilter can filter by new roles/capabilities.
  plugins/UsersManager/Sql/UserTableFilter.php
  plugins/UsersManager/tests/Integration/APITest.php
Labels: Bug, Needs Review, not-in-changelog

#13391 Make sure user is not logged out when settings saved w/ no password change.
  plugins/UsersManager/API.php
  plugins/UsersManager/Controller.php
  plugins/UsersManager/Model.php
  plugins/UsersManager/tests/Integration/APITest.php
Labels: Needs Review, Regression

#13296 Make sure simple datatable metadata is serialized + some test case changes
  core/DataTable.php
  tests/PHPUnit/Framework/TestCase/SystemTestCase.php
  tests/PHPUnit/Unit/DataTable/SimpleTest.php
Labels: Needs Review

#13340 If serialize=1 in Original renderer, return serialized array w/ exception info instead of throwing.
  plugins/API/Renderer/Original.php
Labels: Needs Review

#13388 New events + some other misc changes
  CHANGELOG.md
  core/Access.php
  core/Site.php
  plugins/ScheduledReports/API.php
  plugins/ScheduledReports/tests/Integration/ApiTest.php
  plugins/SitesManager/API.php
  plugins/SitesManager/templates/siteWithoutData.twig
  plugins/UsersManager/Controller.php
Labels: Needs Review, c: Platform

#13304 Remove COLUMN_AGGREGATION_OPS_METADATA_NAME metadata before serializi…
  plugins/API/Renderer/Original.php
Labels: Needs Review

#13405 Fixes Ecommerce overview
  plugins/Ecommerce/Controller.php
Labels: Needs Review, Regression

#13269 Couple changes to aid debugging
  core/ArchiveProcessor.php
  core/DataAccess/ArchiveTableDao.php
  core/ErrorHandler.php
  plugins/Diagnostics/Commands/AnalyzeArchiveTable.php
  plugins/Diagnostics/tests/Integration/Commands/AnalyzeArchiveTableTest.php
  tests/PHPUnit/Integration/DataAccess/ArchiveTableDaoTest.php
  tests/PHPUnit/Integration/FrontControllerTest.php
  tests/resources/trigger-fatal.php
Labels: Needs Review

#13430 Allow session to be writable in CLI mode so tests can write values.
  core/Session/SessionNamespace.php
Labels: Needs Review, c: Tests & QA

#13425 Prevent error related report may not be defined
  core/Plugin/ViewDataTable.php
Labels: Needs Review

#13408 Fix parsing of RGB values.
  core/Mail/EmailStyles.php
  tests/PHPUnit/Unit/Mail/EmailStylesTest.php
Labels: Needs Review, not-in-changelog

#13415 When displaying unprocessed segment message, check for urlencoded segment.
  plugins/SegmentEditor/SegmentEditor.php
  plugins/SegmentEditor/tests/System/UnprocessedSegmentsTest.php
  plugins/SegmentEditor/tests/System/expected/test___VisitsSummary.get_autoArchiveSegmentUnprocessedEncoded.xml
Labels: Bug, Needs Review

#13428 Use Request::processRequest() so API events are triggered.
  plugins/UsersManager/Controller.php
Labels: Needs Review

#13436 [automatic translation update] Updated 303 strings in 8 languages (el, fa, fi, fr, sv, it, pt, tr)
  lang/el.json
  lang/fa.json
  lang/fi.json
  lang/fr.json
  plugins/API/lang/fa.json
  plugins/API/lang/fi.json
  plugins/API/lang/fr.json
  plugins/CoreAdminHome/lang/fi.json
  plugins/CoreAdminHome/lang/fr.json
  plugins/CoreAdminHome/lang/sv.json
  plugins/CoreHome/lang/fi.json
  plugins/CoreHome/lang/fr.json
  plugins/CorePluginsAdmin/lang/fi.json
  plugins/CorePluginsAdmin/lang/fr.json
  plugins/CoreUpdater/lang/fi.json
  plugins/CustomVariables/lang/sv.json
  plugins/DBStats/lang/fi.json
  plugins/Feedback/lang/fi.json
  plugins/Goals/lang/fr.json
  plugins/Installation/lang/fi.json
  plugins/LanguagesManager/lang/fi.json
  plugins/Marketplace/lang/fi.json
  plugins/MobileMessaging/lang/fi.json
  plugins/Overlay/lang/fi.json
  plugins/PrivacyManager/lang/fr.json
  plugins/Referrers/lang/fr.json
  plugins/ScheduledReports/lang/fi.json
  plugins/ScheduledReports/lang/fr.json
  plugins/SegmentEditor/lang/fr.json
  plugins/SegmentEditor/lang/sv.json
  plugins/SitesManager/lang/fi.json
  plugins/SitesManager/lang/fr.json
  plugins/Transitions/lang/fr.json
  plugins/UserCountry/lang/fi.json
  plugins/UserCountryMap/lang/fr.json
  plugins/UsersManager/lang/el.json
  plugins/UsersManager/lang/fi.json
  plugins/UsersManager/lang/fr.json
  plugins/UsersManager/lang/it.json
  plugins/UsersManager/lang/pt.json
  plugins/UsersManager/lang/sv.json
  plugins/UsersManager/lang/tr.json
  plugins/Widgetize/lang/fi.json
Labels: c: i18n

#13450 Set backtrace on error object and check Piwik_ShouldPrintBackTraceWithMessage()
  core/FrontController.php
  plugins/CorePluginsAdmin/Controller.php
  plugins/CorePluginsAdmin/templates/safemode.twig
  tests/PHPUnit/Integration/FrontControllerTest.php
  tests/UI/expected-screenshots/UIIntegrationTest_fatal_error_safemode.png
Labels: not-in-changelog

#13404 Ensure action details are sorted stable across PHP versions
  plugins/API/tests/System/expected/test_AutoSuggestAPITest__Live.getLastVisitsDetails_range.xml
  plugins/Actions/tests/UI/expected-screenshots/ActionsDataTable_segmented_visitor_log.png
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment_noOptions__Live.getLastVisitsDetails_day.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment_noOptions__Live.getLastVisitsDetails_year.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems__Live.getLastVisitsDetails_day.xml
  plugins/Live/Visitor.php
  tests/PHPUnit/System/expected/test_CustomEvents__Live.getLastVisitsDetails_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Live.getLastVisitsDetails_range.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_Live.getLastVisitsDetails_offsetAndLimit_1__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_Live.getLastVisitsDetails_offsetAndLimit_2__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_Live.getLastVisitsDetails_sortByIdVisit__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_Live.getLastVisitsDetails_sortDesc__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits_withCookieSupport__Live.getLastVisitsDetails_day.xml
  tests/UI/expected-screenshots/UIIntegrationTest_ecommerce_log.png
  tests/UI/expected-screenshots/UIIntegrationTest_segmented_visitorlog.png
  tests/UI/expected-screenshots/UIIntegrationTest_widgetize_ecommercelog.png
  tests/UI/expected-screenshots/UIIntegrationTest_widgetize_visitor_log.png
Labels: Needs Review, c: Tests & QA

#13092 Auto-detect timezone and currency in installer
  core/bootstrap.php
  plugins/Installation/FormFirstWebsiteSetup.php
Labels: Needs Review

#13363 Send email if no tracked data within N days.
  config/global.ini.php
  core/Email/ContentGenerator.php
  core/Mail.php
  core/Scheduler/Schedule/SpecificTime.php
  core/Scheduler/Timetable.php
  core/Site.php
  core/View/HtmlEmailFooterView.php
  core/View/HtmlReportEmailHeaderView.php
  plugins/CoreAdminHome/Emails/JsTrackingCodeMissingEmail.php
  plugins/CoreAdminHome/Tasks.php
  plugins/CoreAdminHome/lang/en.json
  plugins/CoreAdminHome/templates/_jsTrackingCodeMissingEmail.twig
  plugins/CoreAdminHome/tests/Integration/TasksTest.php
  plugins/CoreHome/templates/ReportRenderer/_htmlReportFooter.twig
  plugins/CoreHome/templates/ReportRenderer/_htmlReportHeader.twig
  plugins/CoreHome/templates/_htmlEmailFooter.twig
  plugins/CoreHome/templates/_htmlEmailHeader.twig
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_scheduled_report_in_html_row_evolution_graph__ScheduledReports.generateReport_week.original.html
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_scheduled_report_in_html_tables_and_graph__ScheduledReports.generateReport_week.original.html
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_scheduled_report_in_html_tables_only__ScheduledReports.generateReport_week.original.html
  plugins/SitesManager/SitesManager.php
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_scheduled_report_in_html_row_evolution_graph__ScheduledReports.generateReport_month.original.html
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_scheduled_report_in_html_tables_and_graph__ScheduledReports.generateReport_month.original.html
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_scheduled_report_in_html_tables_only__ScheduledReports.generateReport_month.original.html
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: Needs Review

#13469 Referrer name comparison should be case insensitive …
  plugins/Referrers/Columns/Base.php
  plugins/Referrers/tests/System/ApiTest.php
Labels: Bug, Needs Review

#13439 Fix fatal when multiple sites are requested in referrers API report
  plugins/Actions/API.php
  plugins/Annotations/API.php
  plugins/CustomVariables/API.php
  plugins/Goals/API.php
  plugins/Referrers/API.php
  plugins/Referrers/tests/System/ApiTest.php
  plugins/Referrers/tests/System/expected/test_allSites__Referrers.getAll_year.xml
  plugins/Referrers/tests/System/expected/test_allSites__Referrers.getReferrerType_year.xml
  plugins/VisitFrequency/API.php
Labels: Needs Review, not-in-changelog

#13470 Remove user-agent checking code in SessionAuth.
  core/Session/SessionAuth.php
  core/Session/SessionFingerprint.php
  tests/PHPUnit/Integration/Session/SessionAuthTest.php
  tests/PHPUnit/Unit/Session/SessionFingerprintTest.php
  tests/PHPUnit/Unit/Session/SessionInitializerTest.php
Labels: Needs Review

#13477 Stable sort for additional pivoted columns
  core/DataTable/Filter/PivotByDimension.php
  tests/PHPUnit/System/expected/test_PivotByQueryParamTest_test_PivotByParam_WorksWithCustomDimensionReport__CustomDimensions.getCustomDimension_week.xml
  tests/PHPUnit/System/expected/test_PivotByQueryParamTest_test_PivotByParam_WorksWithCustomDimension__UserCountry.getCountry_week.xml
  tests/PHPUnit/System/expected/test_PivotByQueryParamTest_test_PivotByParam_WorksWithReportWhoseSubtableIsSelf__Actions.getPageUrls_week.xml
  tests/PHPUnit/System/expected/test_PivotByQueryParamTest_test_PivotBySubtableDimension_CreatesCorrectPivotTable_WhenPeriodIsDateRange__Referrers.getKeywords_range.xml
  tests/PHPUnit/System/expected/test_PivotByQueryParamTest_test_PivotBySubtableDimension_CreatesCorrectPivotTable__Referrers.getKeywords_week.xml
  tests/PHPUnit/System/expected/test_PivotByQueryParamTest_test_PivotBySubtableDimension_WhenEntireHirearchyIsNotLoaded__Referrers.getKeywords_week.xml
  tests/UI/expected-screenshots/PivotByDimension_pivoted.png
  tests/UI/expected-screenshots/PivotByDimension_pivoted_columns_report.png
Labels: Needs Review, c: Tests & QA

#13437 Replace unsupported characters in all tracking request params
  core/Tracker/Request.php
  tests/PHPUnit/Fixtures/Utf8mb4.php
  tests/PHPUnit/System/Utf8mb4Test.php
  tests/PHPUnit/System/expected/test_Utf8mb4__Live.getLastVisitsDetails_year.xml
Labels: Needs Review

#13509 Use empty array as default value for cpchart colors
  plugins/ImageGraph/StaticGraph.php
Labels: Needs Review, not-in-changelog

#13511 Fix various notices caused by invalid parameter values
  core/Period/Factory.php
  plugins/API/API.php
  plugins/ExampleAPI/API.php
  plugins/ImageGraph/API.php
Labels: Needs Review, not-in-changelog

#13502 Ensure report title is escaped in export overlay
  plugins/CoreHome/angularjs/report-export/reportexport.directive.js
Labels: Needs Review, c: Security
