Repository matomo-org/matomo, pull requests merged in 2018-10, with the labels that each got.

#13512 Ensure segment param is used from url if no hash available
  plugins/Morpheus/javascripts/ajaxHelper.js
Labels: Needs Review, not-in-changelog

#13514 Ensure idSite param has correct type
  core/Plugin/Visualization.php
Labels: Needs Review, not-in-changelog

#13487 Fix incorrect sort order when scheduled report uses custom report
  core/API/Proxy.php
  core/API/Request.php
  core/Context.php
Labels: Bug, Needs Review

#13515 Improve parameter handling in UsersManager.getUsers
  plugins/UsersManager/API.php
Labels: Needs Review, not-in-changelog

#13504 Avoid creating any archive tables for future dates
  core/DataAccess/ArchiveSelector.php
  tests/PHPUnit/Integration/ArchiveTest.php
Labels: Needs Review

#13483 New feature: allow setting goal revenue to event value for event matching goals.
  core/Db/Schema/Mysql.php
  core/Tracker/GoalManager.php
  core/Updates/3.6.1-b3.php
  core/Version.php
  plugins/Events/Actions/ActionEvent.php
  plugins/Goals/API.php
  plugins/Goals/angularjs/manage-goals/manage-goals.controller.js
  plugins/Goals/lang/en.json
  plugins/Goals/templates/_formAddGoal.twig
  plugins/Goals/tests/Integration/APITest.php
  tests/PHPUnit/Fixtures/ThreeVisitsWithCustomEvents.php
  tests/PHPUnit/System/expected/test_CustomEvents_Events.getAction_flat__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_Events.getAction_lastN__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_Events.getCategory_flat__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_Events.getCategory_lastN__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_Events.getName_flat__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_Events.getName_lastN__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents__Actions.getPageUrls_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_CustomEvents__Events.getAction_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents__Events.getAction_month.xml
  tests/PHPUnit/System/expected/test_CustomEvents__Events.getCategory_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents__Events.getCategory_month.xml
  tests/PHPUnit/System/expected/test_CustomEvents__Events.getName_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents__Events.getName_month.xml
  tests/PHPUnit/System/expected/test_CustomEvents__Goals.get_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents__Live.getLastVisitsDetails_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_CustomEvents_secondaryDimensionIsEventAction__Events.getCategory_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_secondaryDimensionIsEventAction__Events.getCategory_month.xml
  tests/PHPUnit/System/expected/test_CustomEvents_secondaryDimensionIsEventAction__Events.getName_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_secondaryDimensionIsEventAction__Events.getName_month.xml
  tests/PHPUnit/System/expected/test_CustomEvents_secondaryDimensionIsEventCategory__Events.getAction_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_secondaryDimensionIsEventCategory__Events.getAction_month.xml
  tests/PHPUnit/System/expected/test_CustomEvents_secondaryDimensionIsEventCategory__Events.getName_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_secondaryDimensionIsEventCategory__Events.getName_month.xml
  tests/PHPUnit/System/expected/test_CustomEvents_secondaryDimensionIsEventName__Events.getAction_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_secondaryDimensionIsEventName__Events.getAction_month.xml
  tests/PHPUnit/System/expected/test_CustomEvents_secondaryDimensionIsEventName__Events.getCategory_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_secondaryDimensionIsEventName__Events.getCategory_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Goals.getGoals.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits__Goals.getGoals.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits_withCookieSupport__Goals.getGoals.xml
Labels: Needs Review, not-in-changelog

#13522 Put our current mission statement (as of Sept 2018) in the Readme
  README.md
Labels: Needs Review

#13445 Create periods with timezones in a couple places that are missing it.
  core/Period/Factory.php
  core/Period/Range.php
  plugins/CoreVisualizations/Visualizations/JqplotGraph/Evolution.php
Labels: Bug, Needs Review

#13526 Improve usage of requested site in plugin Controllers
  plugins/Annotations/Controller.php
  plugins/CoreAdminHome/Controller.php
  plugins/CoreHome/Controller.php
  plugins/CustomVariables/Controller.php
  plugins/Goals/Controller.php
  plugins/ImageGraph/Controller.php
  plugins/Insights/Controller.php
  plugins/Live/Controller.php
  plugins/Login/Controller.php
  plugins/Overlay/Controller.php
  plugins/SitesManager/Controller.php
  plugins/UserCountryMap/Controller.php
  plugins/UsersManager/Controller.php
  plugins/VisitsSummary/Controller.php
Labels: Needs Review, not-in-changelog

#13421 Use placeholder for unsubscribe link and place it near the normal email footer content.
  core/ReportRenderer/Html.php
  core/View/HtmlEmailFooterView.php
  plugins/CoreHome/templates/_htmlEmailFooter.twig
  plugins/ScheduledReports/ScheduledReports.php
Labels: Needs Review, not-in-changelog

#13530 Fixing build.
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_scheduled_report_in_html_row_evolution_graph__ScheduledReports.generateReport_week.original.html
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_scheduled_report_in_html_tables_and_graph__ScheduledReports.generateReport_week.original.html
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_scheduled_report_in_html_tables_only__ScheduledReports.generateReport_week.original.html
  tests/PHPUnit/Integration/ReleaseCheckListTest.php
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_scheduled_report_in_html_row_evolution_graph__ScheduledReports.generateReport_month.original.html
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_scheduled_report_in_html_tables_and_graph__ScheduledReports.generateReport_month.original.html
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_scheduled_report_in_html_tables_only__ScheduledReports.generateReport_month.original.html
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard2.png
Labels: not-in-changelog

#13545 Fix replace not defined JS error
  plugins/Morpheus/javascripts/piwikHelper.js
Labels: Needs Review, not-in-changelog

#13551 Scroll to content pane when editing a user
  plugins/UsersManager/angularjs/users-manager/users-manager.component.html
  plugins/UsersManager/angularjs/users-manager/users-manager.component.js
Labels: Needs Review

#13529 Quote db name in certain queries.
  core/Db/Schema/Mysql.php
  tests/PHPUnit/Integration/DbHelperTest.php
Labels: Needs Review

#13473 Add possibility to manage and view Intranet websites
  config/global.ini.php
  core/Tracker/Visit.php
  core/Tracker/VisitorRecognizer.php
  core/Updates/3.6.1-b2.php
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_removed.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_loaded_token_auth.png
  plugins/IntranetMeasurable/.gitignore
  plugins/IntranetMeasurable/IntranetMeasurable.php
  plugins/IntranetMeasurable/MeasurableSettings.php
  plugins/IntranetMeasurable/Tracker/RequestProcessor.php
  plugins/IntranetMeasurable/Type.php
  plugins/IntranetMeasurable/lang/en.json
  plugins/IntranetMeasurable/plugin.json
  plugins/IntranetMeasurable/tests/Fixtures/IntranetSitesWithVisits.php
  plugins/IntranetMeasurable/tests/System/TrackingTest.php
  plugins/IntranetMeasurable/tests/System/expected/test__intranet__API.get_day.xml
  plugins/IntranetMeasurable/tests/System/expected/test__notIntranet__API.get_day.xml
  plugins/IntranetMeasurable/tests/UI/.gitignore
  plugins/IntranetMeasurable/tests/UI/IntranetMeasurable_spec.js
  plugins/IntranetMeasurable/tests/UI/expected-screenshots/.gitkeep
  plugins/IntranetMeasurable/tests/UI/expected-screenshots/IntranetMeasurable_add_new_dialog.png
  plugins/IntranetMeasurable/tests/UI/expected-screenshots/IntranetMeasurable_intranet_create.png
  plugins/IntranetMeasurable/tests/UI/expected-screenshots/IntranetMeasurable_intranet_created.png
  plugins/IntranetMeasurable/tests/UI/expected-screenshots/IntranetMeasurable_intranet_reloaded.png
  plugins/SitesManager/SitesManager.php
  plugins/SitesManager/tests/UI/expected-screenshots/SitesManager_loaded.png
  plugins/SitesManager/tests/UI/expected-screenshots/SitesManager_page_1.png
  plugins/SitesManager/tests/UI/expected-screenshots/SitesManager_page_1_again.png
  plugins/SitesManager/tests/UI/expected-screenshots/SitesManager_page_2.png
  plugins/SitesManager/tests/UI/expected-screenshots/SitesManager_search.png
  plugins/SitesManager/tests/UI/expected-screenshots/SitesManager_search_no_result.png
  plugins/SitesManager/tests/UI/expected-screenshots/SitesManager_search_page_1.png
  tests/PHPUnit/Integration/JsProxyTest.php
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getAvailableMeasurableTypes.xml
  tests/UI/expected-screenshots/EmptySite_emptySiteDashboard_ignored.png
  tests/UI/expected-screenshots/MeasurableManager_add_new_dialog.png
  tests/UI/expected-screenshots/Theme_home.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_home.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_manage_websites.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_plugins.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_plugins_no_internet.png
Labels: Needs Review, not-in-changelog

#13569 Fix license information may not be shown correctly
  plugins/CorePluginsAdmin/Controller.php
Labels: Needs Review

#13538 Changed wording of YouAreOptedIn
  plugins/CoreAdminHome/lang/en.json
  plugins/CoreAdminHome/templates/optOut.twig
Labels: Needs Review, not-in-changelog

#13576 fix SEO bing count
  plugins/SEO/Metric/Bing.php
Labels: Needs Review

#13575 don't allow SEO plugin to make non-HTTPS requests
  plugins/SEO/Metric/Alexa.php
  plugins/SEO/Metric/Bing.php
  plugins/SEO/Metric/DomainAge.php
Labels: Needs Review, c: Privacy

#13561 Prevent possible error if goalId is not set
  plugins/Goals/VisitorDetails.php
Labels: Needs Review

#13573 Truncate referrer name & keyword in Base class so the value used there matches what is in the DB.
  plugins/Referrers/Columns/Base.php
  plugins/Referrers/Columns/Keyword.php
  plugins/Referrers/Columns/ReferrerName.php
  plugins/Referrers/tests/System/ApiTest.php
Labels: Needs Review

#13568 Support window.Matomo in JS Tracker
  js/piwik.js
  js/piwik.min.js
  piwik.js
  tests/javascript/index.php
Labels: Needs Review

#13285 Implements wrapper method for a more secure unserialize with PHP 7
  .travis.yml
  core/Common.php
  core/Concurrency/DistributedList.php
  core/CronArchive.php
  core/DataAccess/ArchiveSelector.php
  core/DataTable.php
  core/DataTable/Renderer/Php.php
  core/Scheduler/Timetable.php
  core/Tracker/Visit/ReferrerSpamFilter.php
  core/Updates/3.0.0-b1.php
  plugins/Annotations/AnnotationList.php
  plugins/Referrers/SearchEngine.php
  plugins/Referrers/Social.php
  plugins/UserCountryMap/Controller.php
  tests/PHPUnit/Unit/CommonTest.php
Labels: Pull Request WIP, c: Security

#13580 Fix single day archive check in ArchiveProcessor/Parameters.
  core/ArchiveProcessor/Parameters.php
  tests/PHPUnit/Integration/ArchiveProcessor/ParametersTest.php
Labels: Bug, Needs Review

#13500 Tweaks to escaping strategy in a couple places
  plugins/Annotations/templates/getEvolutionIcons.twig
  plugins/CoreAdminHome/angularjs/trackingcode/jstrackingcode.controller.js
  plugins/CoreHome/angularjs/quick-access/quick-access.directive.html
  plugins/CoreHome/angularjs/siteselector/siteselector-model.service.js
  plugins/CoreHome/angularjs/siteselector/siteselector.directive.html
  plugins/CoreHome/angularjs/siteselector/siteselector.directive.js
  plugins/CoreHome/templates/_dataTable.twig
  plugins/CustomVariables/templates/_actionTooltip.twig
  plugins/ExampleVisualization/templates/simpleTable.twig
  plugins/Live/templates/_dataTableViz_visitorLog.twig
  plugins/Live/templates/_visitorDetails.twig
  plugins/Live/templates/getVisitorProfilePopup.twig
  plugins/PrivacyManager/templates/privacySettings.twig
  plugins/ScheduledReports/SubscriptionModel.php
  plugins/ScheduledReports/templates/_addReport.twig
  plugins/ScheduledReports/templates/_listReports.twig
  plugins/ScheduledReports/templates/unsubscribe.twig
  plugins/UsersManager/templates/index.twig
  plugins/UsersManager/templates/userSettings.twig
Labels: Needs Review, not-in-changelog

#13583 Acquire an exclusive lock when writing config file
  core/Config.php
Labels: Needs Review

#13579 Encode html chars in integrity file list
  core/FileIntegrity.php
Labels: Needs Review

#13595 Update expected screenshots.
  tests/UI/expected-screenshots/OptOutForm_loaded.png
  tests/UI/expected-screenshots/OptOutForm_safari-loaded.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_privacy_optout_iframe.png
  tests/UI/expected-screenshots/UIIntegrationTest_opt_out.png
Labels: not-in-changelog

#13534 don't post travis results to IRC
  .travis.yml
Labels: not-in-changelog

#13523 Add tests for password resetter and tweak process a bit.
  plugins/Login/PasswordResetter.php
  plugins/Login/lang/en.json
  plugins/Login/tests/Integration/PasswordResetterTest.php
  tests/PHPUnit/Framework/TestCase/IntegrationTestCase.php
  tests/PHPUnit/Framework/TestingEnvironmentManipulator.php
  tests/PHPUnit/Framework/TestingEnvironmentVariablesDefinitionSource.php
Labels: Needs Review

#13593 Fix undefined variable on PHP 7.3
  plugins/API/API.php
Labels: Needs Review

#13601 Fix CliMultiTest on PHP7
  tests/PHPUnit/System/CliMultiTest.php
Labels: c: Tests & QA, not-in-changelog

#13603 Fix FrontControllerTest for PHP7
  tests/PHPUnit/Integration/FrontControllerTest.php
Labels: c: Tests & QA, not-in-changelog

#13621 Ensure sensitive data is sent as POST parameters in user management
  plugins/UsersManager/angularjs/user-edit-form/user-edit-form.component.js
  plugins/UsersManager/angularjs/user-permissions-edit/user-permissions-edit.component.js
  plugins/UsersManager/angularjs/users-manager/users-manager.component.js
Labels: Needs Review, c: Security

#13615 Let plugins modify the JS tracker
  CHANGELOG.md
  plugins/CustomPiwikJs/TrackingCode/PiwikJsManipulator.php
Labels: Needs Review

#13632 fix typo in LEGALNOTICE
  LEGALNOTICE
Labels: not-in-changelog

#13641 Fix possible notice if never scheduled report is triggered
  core/View/HtmlReportEmailHeaderView.php
Labels: Needs Review, not-in-changelog

#13549 Fix possible error in visitor profile when no visit found
  plugins/Live/VisitorProfile.php
Labels: Needs Review

#13591 Regenerate htaccess files after update
  core/Updater.php
  plugins/Installation/ServerFilesGenerator.php
Labels: Needs Review

#13434 Real-time widget border is slightly misplaced
  plugins/Live/stylesheets/live.less
Labels: Needs Review, not-in-changelog
