Repository matomo-org/matomo, pull requests merged in 2018-04, with the labels that each got.

#12692 Moves ArchiveWebTest to Integration tests
  tests/PHPUnit/Integration/ArchiveWebTest.php
  tests/PHPUnit/Integration/ReleaseCheckListTest.php
Labels: c: Tests & QA, not-in-changelog

#12688 Fix Overlay API not always working with token_auth
  plugins/Overlay/API.php
Labels: Needs Review, not-in-changelog

#10866 Mysql SSL connection support from pull request #8049
  config/global.ini.php
  core/Db/Adapter/Mysqli.php
  core/Db/Adapter/Pdo/Mysql.php
  libs/Zend/Db/Adapter/Mysqli.php
  plugins/Diagnostics/Diagnostic/DbOverSSLCheck.php
  plugins/Diagnostics/config/config.php
  plugins/Installation/lang/en.json
  tests/PHPUnit/Integration/DbSSLTest.php
Labels: Major, c: Security, not-in-changelog

#12550 Fixes #12400 - Option::set() INSERT ... ON DUPLICATE KEY can be slow
  core/Option.php
Labels: Needs Review

#12631 Update Tracker DB config to support SSL
  core/Tracker/Db/Mysqli.php
  core/Tracker/Db/Pdo/Mysql.php
Labels: Needs Review, not-in-changelog

#12672 Set Fixture::$persistFixtureData if PERSIST_FIXTURE_DATA env var is set
  tests/PHPUnit/Framework/Fixture.php
Labels: Needs Review, c: Tests & QA

#12704 [automatic translation update] Updated 126 strings in 8 languages (de, es, sl, el, pl, sq, tr, zh-tw)
  lang/de.json
  lang/es.json
  plugins/CoreAdminHome/lang/sl.json
  plugins/CoreHome/lang/de.json
  plugins/CoreHome/lang/el.json
  plugins/CoreHome/lang/pl.json
  plugins/CoreHome/lang/sq.json
  plugins/CoreHome/lang/tr.json
  plugins/CoreHome/lang/zh-tw.json
  plugins/CoreUpdater/lang/pl.json
  plugins/CustomVariables/lang/sq.json
  plugins/Goals/lang/sq.json
  plugins/Installation/lang/de.json
  plugins/Installation/lang/el.json
  plugins/Installation/lang/pl.json
  plugins/Installation/lang/sq.json
  plugins/Installation/lang/tr.json
  plugins/PrivacyManager/lang/sl.json
  plugins/UserCountry/lang/sq.json
  plugins/UsersManager/lang/sq.json
Labels: c: i18n

#12708 During core:archive when a day or period archiving fails for a website, abort the website archiving
  core/CronArchive.php
Labels: Needs Review

#12696 Redirect to a different site if deleting idSite in URL
  plugins/SitesManager/angularjs/sites-manager/sites-manager-site.controller.js
Labels: Needs Review, not-in-changelog

#12717 Log a job ID for cli commands
  plugins/Monolog/Processor/RequestIdProcessor.php
  plugins/Monolog/config/cli.php
  plugins/Monolog/tests/Integration/LogTest.php
Labels: Needs Review

#12720 Archive: mark the daily archive as successful, only after it was really successful
  core/CronArchive.php
Labels: Needs Review, not-in-changelog

#12719 Do not archive a period when a sub period is processing
  core/CliMulti.php
  core/CronArchive.php
Labels: Needs Review, not-in-changelog

#12729 When invalidating a websites report, allow plugins to invalidate additional sites automatically
  CHANGELOG.md
  core/Archive/ArchiveInvalidator.php
Labels: Needs Review

#12744 missing POST in password reset form
  plugins/Login/templates/login.twig
Labels: not-in-changelog

#12741 Aggregate 500 events in a sub-table instead of 100
  config/global.ini.php
Labels: Needs Review

#12705 Added new event to add stylesheets
  CHANGELOG.md
  core/AssetManager/UIAssetMerger/StylesheetUIAssetMerger.php
Labels: Needs Review

#12702 Do not run the same archive command twice
  core/CliMulti.php
  core/CronArchive.php
Labels: Needs Review

#12693 Modify IdSite dimension so it is visible in customreports UI for use w/ CustomReports.
  lang/en.json
  plugins/CoreHome/Columns/IdSite.php
Labels: Enhancement, Needs Review, not-in-changelog

#12748 Add Common::stripHeader()
  core/Common.php
  core/ProxyHttp.php
  core/View/OneClickDone.php
Labels: Needs Review

#12752 Faster Real Time Maps
  plugins/UserCountryMap/Controller.php
  plugins/UserCountryMap/javascripts/realtime-map.js
Labels: Needs Review

#12728 piwikUrl.getSearchParam() should not set an empty URL value
  plugins/CoreHome/angularjs/common/services/piwik-url.js
Labels: Needs Review

#12742 When setting or resetting User ID, do not update the Visitor ID in the first party cookie
  js/piwik.js
  js/piwik.min.js
  piwik.js
  tests/javascript/index.php
Labels: Bug, c: Platform

#12756 Improve performance for real time map
  plugins/UserCountryMap/Controller.php
Labels: Needs Review, not-in-changelog

#12759 Fix syntax vor 'SHOW COLUMNS FROM'
  core/Db/Schema/Mysql.php
Labels: Bug

#12757 Fix core:purge-old-archive-data failing in some cases
  plugins/CoreAdminHome/Commands/PurgeOldArchiveData.php
Labels: Needs Review, not-in-changelog

#12764 Skip CLIMulti check for already running commands in tests
  core/CliMulti.php
Labels: c: Tests & QA, not-in-changelog

#12378 Discard idGoal parameter for row evolution in goal visualizations
  plugins/CoreHome/javascripts/dataTable_rowactions.js
  tests/UI/expected-screenshots/UIIntegrationTest_goals_individual_row_evolution.png
  tests/UI/specs/UIIntegration_spec.js
Labels: Needs Review

#12755 3rd party cookie visitor ID value should not change over time
  core/Tracker/Request.php
  core/Tracker/Visit.php
Labels: Needs Review

#12771 Fixes regression: rowevolution not working in overlay mode
  plugins/CoreHome/javascripts/dataTable_rowactions.js
Labels: Regression

#12776 Add new icon rocket, upload and bug
  LEGALNOTICE
  plugins/Morpheus/fonts/matomo.svg
  plugins/Morpheus/fonts/matomo.ttf
  plugins/Morpheus/fonts/matomo.woff
  plugins/Morpheus/fonts/selection.json
  plugins/Morpheus/stylesheets/base/icons.css
  plugins/Morpheus/templates/demo.twig
  plugins/Morpheus/tests/UI/expected-screenshots/Morpheus_load.png
Labels: Needs Review

#12791 Add possibility to specify an icon and onclick handler for submenu items
  core/Menu/MenuAbstract.php
  plugins/CoreHome/templates/_menu.twig
Labels: Needs Review

#12792 Remove extra spacing for grouped duplicate actions in visitor profile
  plugins/Live/stylesheets/live.less
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_profile.png
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_profile_action_details.png
Labels: Needs Review, not-in-changelog

#12775 Use a higher precision for rates to show more accurate percentage values
  core/Plugin/ComputedMetric.php
Labels: Needs Review
