Repository matomo-org/matomo, pull requests merged in 2018-11, with the labels that each got.

#13494 Limit password length
  plugins/UsersManager/UsersManager.php
  plugins/UsersManager/lang/en.json
  plugins/UsersManager/tests/Integration/APITest.php
Labels: Needs Review, not-in-changelog

#13635 fix switch continue in CreatePull
  plugins/LanguagesManager/Commands/CreatePull.php
Labels: Needs Review

#13663 [automatic translation update] Updated 222 strings in 9 languages (ja, fi, uk, de, es, pt, it, cs, tr)
  lang/fi.json
  lang/ja.json
  lang/uk.json
  plugins/API/lang/ja.json
  plugins/Actions/lang/fi.json
  plugins/Actions/lang/ja.json
  plugins/Contents/lang/ja.json
  plugins/CoreAdminHome/lang/de.json
  plugins/CoreAdminHome/lang/es.json
  plugins/CoreAdminHome/lang/ja.json
  plugins/CoreAdminHome/lang/pt.json
  plugins/CoreHome/lang/fi.json
  plugins/CoreHome/lang/ja.json
  plugins/CorePluginsAdmin/lang/es.json
  plugins/CorePluginsAdmin/lang/it.json
  plugins/CorePluginsAdmin/lang/ja.json
  plugins/CoreUpdater/lang/ja.json
  plugins/CustomVariables/lang/es.json
  plugins/Feedback/lang/ja.json
  plugins/GeoIp2/lang/es.json
  plugins/Goals/lang/es.json
  plugins/Goals/lang/ja.json
  plugins/Goals/lang/pt.json
  plugins/Insights/lang/ja.json
  plugins/Installation/lang/ja.json
  plugins/IntranetMeasurable/lang/ja.json
  plugins/Live/lang/ja.json
  plugins/Login/lang/cs.json
  plugins/Login/lang/ja.json
  plugins/Login/lang/pt.json
  plugins/Login/lang/tr.json
  plugins/MobileMessaging/lang/ja.json
  plugins/PrivacyManager/lang/es.json
  plugins/PrivacyManager/lang/ja.json
  plugins/Provider/lang/ja.json
  plugins/Referrers/lang/ja.json
  plugins/Resolution/lang/ja.json
  plugins/ScheduledReports/lang/ja.json
  plugins/SegmentEditor/lang/ja.json
  plugins/SitesManager/lang/ja.json
  plugins/UserCountry/lang/ja.json
  plugins/UserCountryMap/lang/ja.json
  plugins/UsersManager/lang/ja.json
  plugins/VisitFrequency/lang/ja.json
  plugins/VisitorInterest/lang/ja.json
Labels: c: i18n

#13642 Remove outdated lib changes from README
  libs/README.md
Labels: Needs Review, not-in-changelog

#13658 Let plugins change content of JS Tracking Code Missing Email
  plugins/CoreAdminHome/Emails/JsTrackingCodeMissingEmail.php
  plugins/CoreAdminHome/Tasks.php
Labels: Needs Review

#13660 Show the CORS settings in the UI when enable_general_settings_admin=0
  config/global.ini.php
  plugins/CoreAdminHome/SystemSettings.php
Labels: Bug, Needs Review

#13574 fix domain age from archive.org
  plugins/SEO/Metric/DomainAge.php
  plugins/SEO/tests/Integration/SEOTest.php
Labels: Needs Review

#13584 Add more tests for format=original.
  core/Common.php
  tests/PHPUnit/Framework/TestCase/SystemTestCase.php
  tests/PHPUnit/Framework/TestRequest/ApiTestConfig.php
  tests/PHPUnit/Framework/TestRequest/Collection.php
  tests/PHPUnit/Framework/TestRequest/Response.php
  tests/PHPUnit/System/OneVisitorTwoVisitsTest.php
Labels: Needs Review, c: Tests & QA

#13537 Event tracking with trackEvent: a value of 0 (zero) is not recorded
  core/Tracker/Action.php
Labels: Needs Review, not-in-changelog

#13693 Fix wrong Site class is used which may not be available in build
  plugins/CoreAdminHome/Tasks.php
Labels: Needs Review

#13692 Do not remove viewdatatable params in test env during tracking or event...
  tests/PHPUnit/Framework/TestingEnvironmentManipulator.php
Labels: c: Tests & QA, not-in-changelog

#13695 Some translation in maps contains an unnecessary %s
  plugins/UserCountryMap/Controller.php
Labels: Needs Review, Regression

#13700 In API requests made by Insights, make sure existing query params do not affect requests.
  plugins/Insights/API.php
  plugins/Insights/Model.php
  plugins/Insights/tests/UI/expected-screenshots/Insights_initial.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: Needs Review

#13708 [automatic translation update] Updated 272 strings in 13 languages (da, et, pl, pt-br, ru, sq, es, de, el, it, pt, tr, cs)
  lang/da.json
  lang/et.json
  lang/pl.json
  lang/pt-br.json
  lang/ru.json
  lang/sq.json
  plugins/API/lang/ru.json
  plugins/API/lang/sq.json
  plugins/Contents/lang/es.json
  plugins/CoreAdminHome/lang/da.json
  plugins/CoreAdminHome/lang/de.json
  plugins/CoreAdminHome/lang/es.json
  plugins/CoreAdminHome/lang/ru.json
  plugins/CorePluginsAdmin/lang/el.json
  plugins/CorePluginsAdmin/lang/es.json
  plugins/CorePluginsAdmin/lang/it.json
  plugins/CorePluginsAdmin/lang/pt.json
  plugins/CorePluginsAdmin/lang/sq.json
  plugins/CorePluginsAdmin/lang/tr.json
  plugins/CustomPiwikJs/lang/ru.json
  plugins/Dashboard/lang/ru.json
  plugins/Goals/lang/de.json
  plugins/Goals/lang/ru.json
  plugins/Login/lang/de.json
  plugins/MobileMessaging/lang/es.json
  plugins/Overlay/lang/it.json
  plugins/PrivacyManager/lang/es.json
  plugins/PrivacyManager/lang/sq.json
  plugins/Referrers/lang/es.json
  plugins/ScheduledReports/lang/el.json
  plugins/ScheduledReports/lang/es.json
  plugins/ScheduledReports/lang/sq.json
  plugins/ScheduledReports/lang/tr.json
  plugins/SitesManager/lang/es.json
  plugins/UsersManager/lang/cs.json
  plugins/UsersManager/lang/de.json
  plugins/UsersManager/lang/el.json
  plugins/UsersManager/lang/it.json
  plugins/UsersManager/lang/pt.json
  plugins/UsersManager/lang/sq.json
  plugins/UsersManager/lang/tr.json
  plugins/VisitorInterest/lang/ru.json
Labels: c: i18n

#13720 Add request parameters to API.Request.intercept event.
  core/API/Proxy.php
Labels: Needs Review

#13724 Fix text of any non-first table action is not readable
  plugins/CoreHome/stylesheets/dataTable/_entityTable.less
Labels: Needs Review, not-in-changelog

#13722 Assume `javascript:void(0);` as safe link in tests
  plugins/Login/tests/UI/expected-screenshots/Login_password_reset_complete.png
  tests/UI/expected-screenshots/UIIntegrationTest_actions_page_titles.png
  tests/UI/expected-screenshots/UIIntegrationTest_actions_site_search.png
  tests/UI/expected-screenshots/UIIntegrationTest_ecommerce_products.png
  tests/lib/screenshot-testing/support/chai-extras.js
Labels: c: Tests & QA

#13735 Update app logos
  plugins/CoreHome/images/applePinnedTab.svg
  plugins/CoreHome/images/applogo_128.png
  plugins/CoreHome/images/applogo_144.png
  plugins/CoreHome/images/applogo_192.png
  plugins/CoreHome/images/applogo_256.png
  plugins/CoreHome/images/applogo_32.png
  plugins/CoreHome/images/applogo_72.png
  plugins/CoreHome/images/applogo_732.png
  plugins/CoreHome/images/favicon.ico
Labels: Needs Review

#13734 Update link to the cloud website
  plugins/CoreUpdater/templates/updateSuccess.twig
Labels: Needs Review

#13732 Prevent possible fatal during update
  core/Updates/3.7.0-b1.php
Labels: Needs Review

#13496 Flattened "entry page" and "exit page" take a long time to be generated
  plugins/Actions/API.php
Labels: Needs Review, not-in-changelog

#13652 Fix content actions are not tracked on search pages
  core/Tracker/Action.php
  plugins/Contents/tests/Fixtures/TwoVisitsWithContents.php
  plugins/Contents/tests/System/expected/test_Contents_Contents.getContentNames_lastN__API.getProcessedReport_day.xml
  plugins/Contents/tests/System/expected/test_Contents_Contents.getContentPieces_lastN__API.getProcessedReport_day.xml
  plugins/Contents/tests/System/expected/test_Contents__Contents.getContentNames_day.xml
  plugins/Contents/tests/System/expected/test_Contents__Contents.getContentNames_month.xml
  plugins/Contents/tests/System/expected/test_Contents__Contents.getContentPieces_day.xml
  plugins/Contents/tests/System/expected/test_Contents__Contents.getContentPieces_month.xml
  plugins/Contents/tests/System/expected/test_Contents__Live.getLastVisitsDetails_day.xml
  plugins/Contents/tests/System/expected/test_Contents__Live.getLastVisitsDetails_month.xml
  plugins/Contents/tests/System/expected/test_Contents_contentInteractionMatch__Live.getLastVisitsDetails_day.xml
  plugins/Contents/tests/System/expected/test_Contents_contentTargetMatch__Live.getLastVisitsDetails_day.xml
  plugins/Contents/tests/System/expected/test_ContentscontentNameOrPieceMatch__Live.getLastVisitsDetails_day.xml
Labels: Needs Review, not-in-changelog

#13715 Fix lbraces in widget names before setting widget titles.
  plugins/CoreHome/angularjs/widget-loader/widgetloader.directive.js
  plugins/Morpheus/javascripts/piwikHelper.js
Labels: Needs Review

#13442 Tooltips appear all over the place but shouldn't
  plugins/CoreHome/angularjs/widget/widget.directive.js
  plugins/Live/templates/_dataTableViz_visitorLog.twig
Labels: Needs Review, not-in-changelog

#13741 Fix build
  core/Updates/3.7.0-b1.php
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_scheduled_report_in_csv__ScheduledReports.generateReport_month.original.csv
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_scheduled_report_in_html_tables_and_graph__ScheduledReports.generateReport_month.original.html
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_scheduled_report_in_html_tables_only__ScheduledReports.generateReport_month.original.html
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_scheduled_report_in_pdf_tables_only__ScheduledReports.generateReport_month.original.pdf
  tests/UI/expected-screenshots/UIIntegrationTest_actions_content_name_piece.png
  tests/UI/expected-screenshots/UIIntegrationTest_actions_content_piece_name.png
  tests/UI/expected-screenshots/UIIntegrationTest_actions_pages_tooltip_help.png
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
  tests/UI/expected-screenshots/UIIntegrationTest_goals_overview.png
  tests/lib/screenshot-testing/support/chai-extras.js
Labels: not-in-changelog

#13728 Fix two issues causing new/returning visitor conversion rate to not appear
  core/DataAccess/ArchiveSelector.php
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_noOptions__Goals.get_month.xml
  plugins/Diagnostics/tests/Integration/Commands/AnalyzeArchiveTableTest.php
  plugins/Goals/Archiver.php
  plugins/PrivacyManager/tests/Integration/DataPurgingTest.php
  plugins/Referrers/tests/System/expected/test_phpSerialized__Referrers.getReferrerType_year.original
Labels: Needs Review

#13729 In LogAggregator, allow the use of a complex dimension w/ an already defined select as.
  core/DataAccess/LogAggregator.php
  core/DataTable/Map.php
  tests/PHPUnit/Integration/DataAccess/LogAggregatorTest.php
Labels: Needs Review

#13606 When token_auth is re-generated, remove wording that user will be logged out
  plugins/UsersManager/lang/en.json
  plugins/UsersManager/templates/userSettings.twig
Labels: Needs Review, not-in-changelog

#13608 Dashboard selector listing all widgets is hidden once the scroll bar is used
  plugins/CoreHome/angularjs/common/directives/focus-anywhere-but-here.js
  plugins/CoreHome/angularjs/selector/selector.directive.js
Labels: Needs Review, not-in-changelog

#13544 Use different icon for segmented visitor log
  LEGALNOTICE
  plugins/Actions/tests/UI/expected-screenshots/ActionsDataTable_pageview_percentages.png
  plugins/Actions/tests/UI/expected-screenshots/ActionsDataTable_segmented_visitor_log_hover.png
  plugins/Actions/tests/UI/expected-screenshots/ActionsDataTable_unique_pageview_percentages.png
  plugins/Live/javascripts/rowaction.js
  plugins/Morpheus/fonts/matomo.svg
  plugins/Morpheus/fonts/matomo.ttf
  plugins/Morpheus/fonts/matomo.woff
  plugins/Morpheus/fonts/matomo.woff2
  plugins/Morpheus/fonts/piwik.svg
  plugins/Morpheus/fonts/piwik.ttf
  plugins/Morpheus/fonts/piwik.woff
  plugins/Morpheus/fonts/piwik.woff2
  plugins/Morpheus/fonts/selection.json
  plugins/Morpheus/stylesheets/base/icons.css
  plugins/Morpheus/templates/demo.twig
  plugins/Morpheus/tests/UI/expected-screenshots/Morpheus_load.png
  tests/UI/expected-screenshots/Menus_mobile_top.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_user_settings.png
  tests/UI/expected-screenshots/ViewDataTableTest_14_visits_percent.png
Labels: Needs Review, not-in-changelog

#13675 Always fail during tracking when authentication is required but invalid token is used
  core/Tracker/Request.php
  plugins/UserCountry/Columns/Base.php
  tests/PHPUnit/Integration/Tracker/VisitTest.php
  tests/PHPUnit/Unit/Tracker/RequestTest.php
Labels: Needs Review, not-in-changelog

#13633 prefer Gzip to Deflate
  core/ProxyHttp.php
Labels: Needs Review

#13536 Cache cacheBuster generation when rendering a view
  core/View.php
Labels: Needs Review, c: Performance

#13748 don't allow chrome to translate Matomo pages
  plugins/CorePluginsAdmin/templates/safemode.twig
  plugins/CoreUpdater/templates/layout.twig
  plugins/Dashboard/templates/_header.twig
  plugins/Installation/templates/layout.twig
  plugins/Morpheus/templates/layout.twig
  plugins/Overlay/templates/showErrorWrongDomain.twig
  plugins/Widgetize/templates/iframe.twig
Labels: Needs Review, c: Privacy

#13689 Add possibility to switch period in evolution graph
  core/ViewDataTable/Config.php
  plugins/Actions/javascripts/actionsDataTable.js
  plugins/CoreHome/javascripts/dataTable.js
  plugins/CoreHome/lang/en.json
  plugins/CoreHome/templates/_dataTableActions.twig
  plugins/CoreVisualizations/Visualizations/JqplotGraph/Evolution.php
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_widget_preview.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_rowevolution.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_widget_maximise.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_widget_move.png
  plugins/Overlay/tests/UI/expected-screenshots/Overlay_row_evolution.png
  tests/UI/expected-screenshots/EvolutionGraph_annotation_delete.png
  tests/UI/expected-screenshots/EvolutionGraph_annotation_edit_form.png
  tests/UI/expected-screenshots/EvolutionGraph_annotation_edit_submit.png
  tests/UI/expected-screenshots/EvolutionGraph_annotation_starred.png
  tests/UI/expected-screenshots/EvolutionGraph_annotations_all.png
  tests/UI/expected-screenshots/EvolutionGraph_annotations_none.png
  tests/UI/expected-screenshots/EvolutionGraph_annotations_single_period.png
  tests/UI/expected-screenshots/EvolutionGraph_bounce_rate.png
  tests/UI/expected-screenshots/EvolutionGraph_initial.png
  tests/UI/expected-screenshots/EvolutionGraph_label_ticks_cutout.png
  tests/UI/expected-screenshots/EvolutionGraph_limit_changed.png
  tests/UI/expected-screenshots/EvolutionGraph_metric_picker_shown.png
  tests/UI/expected-screenshots/EvolutionGraph_new_annotation_form.png
  tests/UI/expected-screenshots/EvolutionGraph_new_annotation_submit.png
  tests/UI/expected-screenshots/EvolutionGraph_one_series.png
  tests/UI/expected-screenshots/EvolutionGraph_periods_list.png
  tests/UI/expected-screenshots/EvolutionGraph_periods_selected.png
  tests/UI/expected-screenshots/EvolutionGraph_table_actions.png
  tests/UI/expected-screenshots/EvolutionGraph_two_metrics.png
  tests/UI/expected-screenshots/RowEvolution_multirow_evolution.png
  tests/UI/expected-screenshots/RowEvolution_multirow_evolution_other_metric.png
  tests/UI/expected-screenshots/RowEvolution_row_evolution.png
  tests/UI/expected-screenshots/RowEvolution_row_evolution_ecommerce_item.png
  tests/UI/expected-screenshots/RowEvolution_row_evolution_multiple_series.png
  tests/UI/expected-screenshots/RowEvolution_row_evolution_other_metric.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard5_mobile.png
  tests/UI/expected-screenshots/UIIntegrationTest_goals_individual_row_evolution.png
  tests/UI/expected-screenshots/UIIntegrationTest_widgets_listing.png
  tests/UI/specs/EvolutionGraph_spec.js
Labels: Needs Review, not-in-changelog

#13687 Auto zoom real time and visitor map
  plugins/UserCountryMap/javascripts/realtime-map.js
  plugins/UserCountryMap/javascripts/visitor-map.js
Labels: Needs Review, not-in-changelog

#13764 In two UsersManager API methods, do not apply offset if limit is not also applied.
  plugins/UsersManager/Model.php
  plugins/UsersManager/tests/Integration/APITest.php
Labels: Needs Review, not-in-changelog

#13765 Make sure unsubscribe links shows in attached report emails.
  plugins/ScheduledReports/ReportEmailGenerator/AttachedFileReportEmailGenerator.php
Labels: Needs Review, not-in-changelog

#13768 add tagmanager containers to .gitignore
  .gitignore
Labels: not-in-changelog

#13767 Remove old link
  plugins/CoreAdminHome/lang/en.json
  plugins/CoreUpdater/SystemSettings.php
  tests/PHPUnit/System/expected/test_ImportLogs__CorePluginsAdmin.getSystemSettings.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits__CorePluginsAdmin.getSystemSettings.xml
  tests/PHPUnit/System/expected/test_noVisit_PeriodIsLast__CorePluginsAdmin.getSystemSettings.xml
  tests/PHPUnit/System/expected/test_noVisit__CorePluginsAdmin.getSystemSettings.xml
Labels: not-in-changelog

#13497 Add max_allowed_packet diagnostic check
  plugins/Diagnostics/Diagnostic/DbMaxPacket.php
  plugins/Diagnostics/config/config.php
  plugins/Diagnostics/lang/en.json
Labels: Needs Review, not-in-changelog

#13546 Add campaign url builder widget
  lang/en.json
  plugins/Referrers/Categories/CampaignUrlBuilderSubcategory.php
  plugins/Referrers/Referrers.php
  plugins/Referrers/Widgets/GetCampaignUrlBuilder.php
  plugins/Referrers/angularjs/campaign-builder/campaign-builder.controller.js
  plugins/Referrers/angularjs/campaign-builder/campaign-builder.directive.html
  plugins/Referrers/angularjs/campaign-builder/campaign-builder.directive.js
  plugins/Referrers/angularjs/campaign-builder/campaign-builder.directive.less
  plugins/Referrers/lang/en.json
  plugins/Referrers/templates/campaignBuilder.twig
  plugins/Referrers/tests/UI/.gitignore
  plugins/Referrers/tests/UI/CampaignBuilder_spec.js
  plugins/Referrers/tests/UI/expected-screenshots/.gitkeep
  plugins/Referrers/tests/UI/expected-screenshots/CampaignBuilder_generate_url_nokeyword.png
  plugins/Referrers/tests/UI/expected-screenshots/CampaignBuilder_generate_url_reset.png
  plugins/Referrers/tests/UI/expected-screenshots/CampaignBuilder_generate_url_withkeyword.png
  plugins/Referrers/tests/UI/expected-screenshots/CampaignBuilder_loaded.png
  plugins/Widgetize/tests/System/WidgetTest.php
  tests/PHPUnit/Integration/WidgetsListTest.php
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getReportPagesMetadata.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getWidgetMetadata.xml
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard3.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard4.png
Labels: Needs Review, not-in-changelog

#13758 Use new exception in PluginsArchiver & add previous exceptions to backtrace in fatal error report
  core/API/ResponseBuilder.php
  core/ArchiveProcessor/PluginsArchiver.php
  core/ArchiveProcessor/PluginsArchiverException.php
  core/FrontController.php
  tests/PHPUnit/Integration/ArchiveProcessor/PluginsArchiverTest.php
  tests/PHPUnit/Integration/FrontControllerTest.php
Labels: Needs Review

#13680 Support callback in JS tracker method trackGoal
  js/piwik.js
  js/piwik.min.js
  piwik.js
Labels: Needs Review, not-in-changelog

#13676 During installation allow to prefill DB form from environment variables
  plugins/Installation/FormDatabaseSetup.php
Labels: Needs Review, not-in-changelog

#13766 Small API changes needed for a translation plugin
  core/API/Request.php
  plugins/Dashboard/Dashboard.php
Labels: Needs Review

#13667 Support tideways xhprof profiler
  core/Profiler.php
Labels: Needs Review

#13605 allow admin user to copy dashboards
  plugins/Dashboard/API.php
  plugins/Dashboard/Controller.php
  plugins/Dashboard/DashboardManagerControl.php
  plugins/Dashboard/templates/embeddedIndex.twig
  plugins/Dashboard/tests/Integration/APITest.php
Labels: Needs Review, not-in-changelog

#13607 When creating HTML reports in tmp/assets/ include a random string in the filename
  CHANGELOG.md
  plugins/MobileMessaging/tests/Integration/MobileMessagingTest.php
  plugins/ScheduledReports/API.php
Labels: Needs Review, not-in-changelog

#13616 Add possibility to queue tracking requests so they are sent in bulk
  CHANGELOG.md
  js/piwik.js
  js/piwik.min.js
  piwik.js
  tests/javascript/index.php
Labels: Needs Review

#13683 When changing password or email address, require to type old password
  CHANGELOG.md
  core/Piwik.php
  plugins/Login/PasswordResetter.php
  plugins/PrivacyManager/PrivacyManager.php
  plugins/UsersManager/API.php
  plugins/UsersManager/Controller.php
  plugins/UsersManager/LastSeenTimeLogger.php
  plugins/UsersManager/UserUpdater.php
  plugins/UsersManager/UsersManager.php
  plugins/UsersManager/angularjs/personal-settings/personal-settings.controller.js
  plugins/UsersManager/angularjs/user-edit-form/user-edit-form.component.html
  plugins/UsersManager/angularjs/user-edit-form/user-edit-form.component.js
  plugins/UsersManager/lang/en.json
  plugins/UsersManager/stylesheets/usersManager.less
  plugins/UsersManager/templates/userSettings.twig
  plugins/UsersManager/tests/Integration/APITest.php
  plugins/UsersManager/tests/Integration/UsersManagerTest.php
  plugins/UsersManager/tests/UI/UsersManager_spec.js
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_edit_user_basic_asks_confirmation.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_edit_user_basic_confirmed_wrong_password.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_edit_user_form.png
  tests/PHPUnit/Integration/Session/SessionAuthTest.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_user_settings_asks_confirmation.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_user_settings_wrong_password_confirmed.png
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
  tests/UI/specs/UIIntegration_spec.js
Labels: Needs Review, not-in-changelog

#13498 "Loading data.." is not always displayed when changing dates in the dashboard
  plugins/CoreHome/angularjs/reporting-page/reportingpage.controller.js
  plugins/Dashboard/angularjs/dashboard/dashboard.directive.js
Labels: Needs Review, not-in-changelog
