Repository matomo-org/matomo, pull requests merged in 2019-05, with the labels that each got.

#14398 Fix build ecommerce order with items
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_html_tables_and_graph__ScheduledReports.generateReport_week.original.html
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_html_tables_only__ScheduledReports.generateReport_week.original.html
Labels: Needs Review, not-in-changelog

#14351 Submit report download link as a post request
  plugins/ScheduledReports/angularjs/manage-scheduled-report/manage-scheduled-report.controller.js
  plugins/ScheduledReports/templates/_listReports.twig
Labels: Needs Review

#14363 Allow limit selection contents to be customized by specific visualization.
  plugins/CoreHome/javascripts/dataTable.js
Labels: Needs Review

#14386 Make sure evolution parameters are initialized in Config so Controllers can override them.
  plugins/CoreVisualizations/Visualizations/JqplotGraph/Evolution.php
  plugins/CoreVisualizations/Visualizations/JqplotGraph/Evolution/Config.php
Labels: Needs Review

#14387 Require password confirmation before installing plugins
  plugins/CorePluginsAdmin/Controller.php
  plugins/Marketplace/Controller.php
  plugins/Marketplace/templates/uploadPluginDialog.twig
Labels: Needs Review

#14317 Task to purge archives for deleted websites and segments
  core/Archive/ArchivePurger.php
  core/DataAccess/Model.php
  core/Segment.php
  plugins/CoreAdminHome/Tasks.php
  plugins/CoreAdminHome/tests/Integration/TasksTest.php
  tests/PHPUnit/Fixtures/RawArchiveDataWithTempAndInvalidated.php
  tests/PHPUnit/Integration/Archive/ArchivePurgerTest.php
Labels: not-in-changelog

#14399 Invalidate archives when visits removed via GDPR tool
  plugins/PrivacyManager/Model/DataSubjects.php
  plugins/PrivacyManager/angularjs/manage-gdpr/managegdpr.directive.html
  plugins/PrivacyManager/tests/Fixtures/MultipleSitesMultipleVisitsFixture.php
  plugins/PrivacyManager/tests/Integration/Model/DataSubjectsTest.php
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_delete_visit_cancelled.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_delete_visit_cancelled_verified_no_data_deleted.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_delete_visit_confirmed.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_delete_visit_unconfirmed.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_enrich_segment_by_ip.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_uncheck_one_visit.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_visits_found.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_visits_showprofile.png
Labels: Needs Review

#14407 Fix build for failing integration test purger
  core/DataAccess/Model.php
Labels: Needs Review, not-in-changelog

#14405 Do not create request to validate license in tracker mode
  core/Plugin/Manager.php
Labels: Needs Review, not-in-changelog

#14419 Fix possible error occurring in charts
  plugins/CoreVisualizations/Visualizations/Graph/Config.php
Labels: Needs Review

#14415 Real-time report under Visitors does not refresh
  plugins/Live/Live.php
  plugins/Live/angularjs/live-widget-refresh/live-widget-refresh.directive.js
  plugins/Live/templates/index.twig
Labels: Needs Review, not-in-changelog

#14431 random failure UI test fix + update packages to get rid of github warning
  tests/UI/specs/Menus_spec.js
  tests/UI/specs/OptOutForm_spec.js
  tests/lib/screenshot-testing/package-lock.json
  tests/lib/screenshot-testing/package.json
Labels: not-in-changelog

#14372 Ensure segment definitions don't regress
  plugins/DevicesDetection/API.php
  plugins/DevicesDetection/Columns/BrowserName.php
  plugins/DevicesDetection/Columns/Os.php
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems__API.getProcessedReport_day.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems__UserCountry.getCountry_day.xml
  plugins/GeoIp2/tests/System/expected/test_ConvertRegionCodesToIsoTest_testExecute_ShouldConvertRegionCodes__UserCountry.getCountry_month.xml
  plugins/UserCountry/API.php
  plugins/UserCountry/Columns/Country.php
  plugins/UserCountry/tests/System/expected/test_AttributeHistoricalDataWithLocationsTest_testExecute_ShouldReturnLogAfterWorkingWithSomeData__UserCountry.getCountry_month.xml
  tests/PHPUnit/System/expected/test_BackwardsCompatibility1XTest__UserCountry.getCountry_day.xml
  tests/PHPUnit/System/expected/test_ImportLogs__DevicesDetection.getBrowserFamilies_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__DevicesDetection.getBrowsers_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__UserCountry.getCountry_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest__UserCountry.getCountry_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_getCountry_with_filter_excludelowpop__UserCountry.getCountry_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_segment_city__UserCountry.getCountry_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_segment_continent__UserCountry.getCountry_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_segment_lat_long__UserCountry.getCountry_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_segment_region__UserCountry.getCountry_month.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits__DevicesDetection.getBrowserFamilies_day.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits__DevicesDetection.getBrowsers_day.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits__UserCountry.getCountry_day.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits_withCookieSupport__DevicesDetection.getBrowserFamilies_day.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits_withCookieSupport__DevicesDetection.getBrowsers_day.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits_withCookieSupport__UserCountry.getCountry_day.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata_showRawMetrics__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_oneVisitor_oneWebsite_severalDays_DateRange__UserCountry.getCountry_range.xml
  tests/PHPUnit/System/expected/test_periodIsRange_dateIsLastN_MetadataAndNormalAPI__API.getProcessedReport_range.xml
  tests/PHPUnit/System/expected/test_periodIsRange_dateIsLastN_MetadataAndNormalAPI_pagesegment__API.getProcessedReport_range.xml
Labels: Needs Review

#14273 Overwrite direct entry referrer information if campaign referrer is found in later request.
  CHANGELOG.md
  plugins/Referrers/Columns/Base.php
  plugins/Referrers/Columns/Campaign.php
  plugins/Referrers/Columns/Keyword.php
  plugins/Referrers/Columns/ReferrerName.php
  plugins/Referrers/Columns/ReferrerType.php
  plugins/Referrers/Columns/ReferrerUrl.php
  plugins/Referrers/tests/Integration/Columns/ReferrerKeywordTest.php
  plugins/Referrers/tests/Integration/Columns/ReferrerNameTest.php
  plugins/Referrers/tests/Integration/Columns/ReferrerTypeTest.php
  plugins/SitesManager/SiteUrls.php
  tests/PHPUnit/Fixtures/SomeVisitsCustomVariablesCampaignsNotHeuristics.php
  tests/PHPUnit/System/TrackCustomVariablesAndCampaignsForceUsingVisitIdNotHeuristicsTest.php
  tests/PHPUnit/System/expected/test_PiwikTracker_trackForceUsingVisitId_insteadOfHeuristics_alsoTestsCampaignTracking__Live.getLastVisitsDetails_day.xml
  tests/PHPUnit/System/expected/test_PiwikTracker_trackForceUsingVisitId_insteadOfHeuristics_alsoTestsCampaignTracking__Referrers.getCampaigns_day.xml
  tests/PHPUnit/System/expected/test_PiwikTracker_trackForceUsingVisitId_insteadOfHeuristics_alsoTestsCampaignTracking__VisitsSummary.get_day.xml
  tests/UI/specs/UIIntegration_spec.js
Labels: Needs Review

#14439 Add missing 2fa test
  plugins/TwoFactorAuth/.gitignore
  plugins/TwoFactorAuth/tests/Fixtures/SimpleFixtureTrackFewVisits.php
  plugins/TwoFactorAuth/tests/System/TwoFactorAuthTest.php
Labels: not-in-changelog

#14443 Fixes various misspellings of Matomo (and Piwik)
  lang/cs.json
  lang/da.json
  lang/et.json
  lang/fa.json
  lang/sq.json
  plugins/API/lang/fa.json
  plugins/CoreAdminHome/lang/fa.json
  plugins/CoreAdminHome/lang/ja.json
  plugins/CoreAdminHome/lang/ru.json
  plugins/CoreAdminHome/lang/sv.json
  plugins/CoreHome/lang/fa.json
  plugins/CoreHome/lang/sv.json
  plugins/CoreUpdater/lang/de.json
  plugins/CustomVariables/lang/fr.json
  plugins/DevicesDetection/lang/de.json
  plugins/Installation/lang/de.json
  plugins/Installation/lang/fa.json
  plugins/Installation/lang/tl.json
  plugins/Installation/lang/zh-cn.json
  plugins/Marketplace/lang/de.json
  plugins/Overlay/lang/de.json
  plugins/PrivacyManager/lang/de.json
  plugins/PrivacyManager/lang/fr.json
  plugins/SitesManager/lang/sr.json
  plugins/UserCountry/lang/zh-cn.json
Labels: c: i18n, not-in-changelog

#14436 Group different writings of Instagram in reports
  plugins/Referrers/API.php
  plugins/Referrers/DataTable/Filter/GroupDifferentSocialWritings.php
  plugins/Referrers/tests/Unit/GroupDifferentSocialWritingsTest.php
Labels: Needs Review, not-in-changelog

#14414 Allow Metric instances to be stored in Report::$metrics.
  core/Plugin/Report.php
Labels: Needs Review, not-in-changelog

#14380 Copy geoip archive into temporary folder instead of in the geoip folder
  plugins/GeoIp2/GeoIP2AutoUpdater.php
  plugins/GeoIp2/LocationProvider/GeoIp2.php
Labels: Needs Review

#13832 Allow period used to generate scheduled report to be different from email schedule.
  core/Updates/3.10.0-b2.php
  core/Version.php
  plugins/ScheduledReports/API.php
  plugins/ScheduledReports/Controller.php
  plugins/ScheduledReports/Model.php
  plugins/ScheduledReports/angularjs/manage-scheduled-report/manage-scheduled-report.controller.js
  plugins/ScheduledReports/lang/en.json
  plugins/ScheduledReports/templates/_addReport.twig
  plugins/ScheduledReports/tests/Integration/ApiTest.php
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
  tests/UI/expected-screenshots/UIIntegrationTest_email_reports_editor.png
  tests/UI/specs/UIIntegration_spec.js
Labels: Needs Review

#14023 Allow throwing exceptions for HTTP error codes to better check query param input.
  core/API/ResponseBuilder.php
  core/ExceptionHandler.php
  core/Http/BadRequestException.php
  core/Http/HttpCodeException.php
  core/Plugin/Visualization.php
  core/ViewDataTable/RequestConfig.php
  plugins/CoreVisualizations/Visualizations/Cloud.php
  plugins/CoreVisualizations/Visualizations/HtmlTable.php
  plugins/CoreVisualizations/Visualizations/HtmlTable/AllColumns.php
  plugins/CoreVisualizations/Visualizations/JqplotGraph/Bar.php
  plugins/CoreVisualizations/Visualizations/JqplotGraph/Evolution.php
  plugins/CoreVisualizations/Visualizations/JqplotGraph/Pie.php
  plugins/ScheduledReports/API.php
  plugins/ScheduledReports/tests/Integration/ApiTest.php
Labels: Needs Review, not-in-changelog

#14049 One Click Install UI test
  plugins/CoreHome/tests/UI/SingleMetricView_spec.js
  plugins/CoreUpdater/Updater.php
  plugins/CoreUpdater/tests/UI/CoreUpdaterCode_spec.js
  plugins/CoreUpdater/tests/UI/expected-screenshots/CoreUpdaterCode_httpsUpdateFail.png
  plugins/CoreUpdater/tests/UI/expected-screenshots/CoreUpdaterCode_newVersion.png
  plugins/Dashboard/tests/UI/DashboardManager_spec.js
  plugins/Dashboard/tests/UI/Dashboard_spec.js
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_removed.png
  plugins/TestRunner/Commands/TestsRunUI.php
  plugins/TwoFactorAuth/tests/UI/TwoFactorAuth_spec.js
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuth_twofa_setup_step4.png
  tests/PHPUnit/Fixtures/LatestStableInstall.php
  tests/PHPUnit/Fixtures/LatestStableInstall/GitCommitReleaseChannel.php
  tests/UI/expected-screenshots/OneClickUpdate_latest_version_available.png
  tests/UI/expected-screenshots/OneClickUpdate_login.png
  tests/UI/expected-screenshots/OneClickUpdate_update_fail.png
  tests/UI/expected-screenshots/OneClickUpdate_update_screen.png
  tests/UI/expected-screenshots/OneClickUpdate_update_success.png
  tests/UI/specs/OneClickUpdate_spec.js
  tests/lib/screenshot-testing/run-tests.js
  tests/resources/install-matomo.php
  tests/resources/one-click-update-version.php
Labels: Needs Review, c: Tests & QA, not-in-changelog

#14453 Fix realtime map ui test
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuth_twofa_forced_step2.png
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuth_twofa_forced_step3.png
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuth_twofa_forced_step4.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_realtime_map.png
  tests/UI/specs/UIIntegration_spec.js
  tests/lib/screenshot-testing/support/app.js
Labels: not-in-changelog

#14422 Store matomo url only if host is valid
  core/SettingsPiwik.php
Labels: Needs Review, not-in-changelog

#14416 Replace internal API requests with processed ones
  plugins/Referrers/API.php
  plugins/Referrers/DataTable/Filter/SetGetReferrerTypeSubtables.php
  plugins/Referrers/tests/System/expected/test_phpSerialized__Referrers.getReferrerType_year.original
Labels: Needs Review, not-in-changelog

#14412 Don't tell people to run chmod -R 755 on their install if update fails
  core/Filechecks.php
Labels: Needs Review, not-in-changelog

#14309 Let controllers specify what type a view to be rendered is
  core/Plugin/Controller.php
  core/Plugin/ControllerAdmin.php
  core/Plugin/Menu.php
  plugins/SitesManager/Controller.php
Labels: Needs Review

#14356 Make sure to ignore filter limit in insights when "all" is selected
  plugins/Insights/DataTable/Filter/Limit.php
  plugins/Insights/Visualizations/Insight.php
  plugins/Insights/tests/Unit/FilterLimitTest.php
Labels: Needs Review, not-in-changelog

#14348 fix Unsupported pivot dimension when switching between related event reports
  plugins/Events/Reports/Base.php
Labels: Needs Review, not-in-changelog

#13884 Make sure to group the label in Referrer Websites report
  plugins/Referrers/DataTable/Filter/UrlsFromWebsiteId.php
Labels: Needs Review, not-in-changelog

#14467 New command to send test emails
  plugins/CoreConsole/Commands/TestEmail.php
Labels: Needs Review

#14423 Changed period in row evolution breaks graph/metric association
  plugins/CoreHome/templates/getMultiRowEvolutionPopover.twig
  plugins/CoreVisualizations/Visualizations/Graph.php
  plugins/CoreVisualizations/javascripts/jqplot.js
  tests/UI/specs/RowEvolution_spec.js
Labels: Needs Review, not-in-changelog

#14483 don't send Referer in E-Mail footer link
  plugins/CoreHome/templates/_htmlEmailFooter.twig
Labels: Needs Review, c: Privacy

#14486 Add extra processed metrics to list of available metrics in Graph if …
  plugins/CoreVisualizations/Visualizations/Graph.php
Labels: Bug

#14454 Update video content on Welcome widget
  plugins/CoreHome/images/promo_splash.png
  plugins/CoreHome/images/promo_video_splash.jpg
  plugins/CoreHome/stylesheets/promo.less
  plugins/CoreHome/templates/getPromoVideo.twig
  plugins/CorePluginsAdmin/tests/UI/expected-screenshots/TagManagerTeaser_admin_page_disable.png
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_removed.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_loaded_token_auth.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_removed.png
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuth_logme_verified.png
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuth_twofa_forced_step4.png
  tests/UI/expected-screenshots/EmptySite_emptySiteDashboard_ignored.png
  tests/UI/expected-screenshots/Theme_home.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard1.png
Labels: Needs Review

#14438 Maintenance mode, grey text on blue background
  plugins/Morpheus/stylesheets/simple_structure.css
  plugins/Morpheus/templates/maintenance.tpl
Labels: Needs Review, not-in-changelog

#14494 fix tracking code on "No data is recorded yet" screen does not reflect whitelabel setting
  plugins/SitesManager/Controller.php
Labels: Needs Review, not-in-changelog

#14497 Default to current ip in UserCountry.getLocationFromIp and add some tests.
  plugins/UserCountry/API.php
  plugins/UserCountry/tests/Integration/APITest.php
Labels: Needs Review
