Repository matomo-org/matomo, pull requests merged in 2019-11, with the labels that each got.

#15094 Fix double encoding in guest settings
  plugins/UsersManager/templates/anonymousSettings.twig
Labels: Needs Review, not-in-changelog

#15093 Fix reports by dimensions layout
  plugins/CoreHome/angularjs/widget-bydimension-container/widget-bydimension-container.directive.less
  tests/UI/expected-screenshots/PivotByDimension_pivoted.png
  tests/UI/expected-screenshots/UIIntegrationTest_ecommerce_sales.png
  tests/UI/expected-screenshots/UIIntegrationTest_events_overview.png
  tests/UI/expected-screenshots/UIIntegrationTest_goals_individual_goal.png
  tests/UI/expected-screenshots/UIIntegrationTest_goals_individual_goal_updated.png
  tests/UI/expected-screenshots/UIIntegrationTest_goals_overview.png
Labels: Needs Review, Regression

#15032 Some overlay improvements
  plugins/Overlay/javascripts/Piwik_Overlay.js
Labels: Needs Review

#15037 Prevent warning array to string conversion in console renderer
  core/DataTable/Renderer/Console.php
Labels: Needs Review

#15044 Slight performance improvement when rendering data table visualisations
  plugins/CoreHome/templates/_dataTable.twig
Labels: Needs Review, c: Performance

#15095 Fix zend session hides actual error when there are two or more errors…
  libs/Zend/Session/Exception.php
Labels: Needs Review

#15057 Prevent notice in tracker code generator
  core/Tracker/TrackerCodeGenerator.php
Labels: Needs Review

#15066 Avoid 'Trying to add two strings in DataTable\Row::sumRowArray' warning in SEO API
  plugins/SEO/API.php
Labels: Needs Review

#15048 Send queued requests slightly less often and have method to change interval
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  tests/javascript/index.php
Labels: Needs Review, not-in-changelog

#15075 Revert "Support alternative matomo bootstrap file"
  console
  index.php
  piwik.php
Labels: Needs Review, not-in-changelog

#15055 Updates device detector to 3.12.1
  composer.lock
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_browserName__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_deviceType__API.getSuggestedValuesForSegment.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_range_archive__DevicesDetection.getType_range.xml
  plugins/DevicesDetection/functions.php
  plugins/DevicesDetection/lang/en.json
  plugins/DevicesDetection/tests/System/expected/test___DevicesDetection.getType_day.xml
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_profile.png
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_profile_action_details.png
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_profile_actions_hidden.png
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_profile_limited.png
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_profile_visit_details.png
  tests/PHPUnit/System/expected/test_ImportLogs__DevicesDetection.getType_month.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits__DevicesDetection.getType_day.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits_withCookieSupport__DevicesDetection.getType_day.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getSegmentsMetadata.xml
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard2.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_devices.png
Labels: Needs Review

#15105 Fix possible notice in lineMessageFormatter when trace has less than 10 records
  plugins/Monolog/Formatter/LineMessageFormatter.php
Labels: Needs Review, not-in-changelog

#15106 tmp directory should use user path
  config/global.php
Labels: Needs Review, not-in-changelog

#15058 More efficient heart beat timer
  CHANGELOG.md
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  tests/javascript/index.php
Labels: Needs Review, not-in-changelog

#15107 Prevent test cookie from being created when cookies are disabled
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: Needs Review, not-in-changelog

#15103 Ensure insight reports uses the correct compare period number for periods other than day
  plugins/Insights/Visualizations/Insight.php
Labels: Bug, Needs Review

#15102 Fix Insight visualization layout
  plugins/Insights/javascripts/insightsDataTable.js
  plugins/Insights/stylesheets/insightVisualization.less
  plugins/Insights/templates/insightControls.twig
  plugins/Insights/templates/insightVisualization.twig
  plugins/Insights/templates/overviewWidget.twig
  plugins/Insights/tests/UI/expected-screenshots/Insights_initial.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard2.png
Labels: Needs Review, Regression

#15129 Don't freeze lefthand column of datatable on small screens
  plugins/CoreHome/stylesheets/dataTable/_dataTable.less
Labels: Needs Review

#15124 Update network componenent to fix iprange on PHP7
  composer.lock
Labels: Needs Review, not-in-changelog

#15116 Show the link to upload a new plugin when enable_plugin_upload=1
  plugins/CorePluginsAdmin/templates/plugins.twig
Labels: Needs Review

#15026 Use thousands separator in single metric view
  plugins/CoreVisualizations/templates/macros.twig
Labels: Needs Review

#15114 Better detection of a succesfull start of a session
  libs/Zend/Session.php
  libs/Zend/Session/Exception.php
Labels: Needs Review

#15131 accept numbers for setUserId, setEcommerceView, addEcommerceItem, removeEcommerceItem
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  tests/javascript/index.php
Labels: Needs Review, not-in-changelog

#15110 Fixes a couple segment handling regressions in the UI
  core/Segment.php
  plugins/CoreHome/javascripts/broadcast.js
  plugins/SegmentEditor/javascripts/Segmentation.js
  tests/PHPUnit/Integration/SegmentTest.php
Labels: Needs Review

#15030 Adds links to online guides in reports help
  core/Plugin/Report.php
  core/ViewDataTable/Config.php
  plugins/API/Glossary.php
  plugins/Actions/Reports/GetSiteSearchKeywords.php
  plugins/Actions/Reports/SiteSearchBase.php
  plugins/Actions/lang/en.json
  plugins/Contents/Reports/Base.php
  plugins/Contents/tests/System/expected/test_Contents_Contents.getContentNames_lastN__API.getProcessedReport_day.xml
  plugins/Contents/tests/System/expected/test_Contents_Contents.getContentPieces_lastN__API.getProcessedReport_day.xml
  plugins/CoreHome/angularjs/enrichedheadline/enrichedheadline.directive.less
  plugins/CoreHome/lang/en.json
  plugins/CoreHome/templates/_dataTable.twig
  plugins/CustomVariables/Reports/Base.php
  plugins/Ecommerce/Reports/Base.php
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_Metadata_Goals.Get_AbandonedCart__API.getProcessedReport_day.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_Metadata_Goals.Get_NormalGoal__API.getProcessedReport_day.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_Metadata_Goals.Get_Order__API.getProcessedReport_day.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_Metadata_ItemsCategory__API.getProcessedReport_day.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_Metadata_ItemsSku__API.getProcessedReport_day.xml
  plugins/Events/Reports/Base.php
  plugins/Goals/Reports/Base.php
  plugins/Referrers/Reports/GetCampaigns.php
  plugins/Referrers/lang/en.json
  tests/PHPUnit/System/expected/test_CustomEvents_Events.getAction_flat__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_Events.getAction_lastN__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_Events.getCategory_flat__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_Events.getCategory_lastN__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_Events.getName_flat__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_Events.getName_lastN__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_SiteSearch_Actions.getPageTitlesFollowingSiteSearch_firstSite_lastN__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_SiteSearch_Actions.getPageTitlesFollowingSiteSearch_firstSite_lastN__API.getProcessedReport_month.xml
  tests/PHPUnit/System/expected/test_SiteSearch_Actions.getPageUrlsFollowingSiteSearch_firstSite_lastN__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_SiteSearch_Actions.getPageUrlsFollowingSiteSearch_firstSite_lastN__API.getProcessedReport_month.xml
  tests/PHPUnit/System/expected/test_SiteSearch_Actions.getSiteSearchCategories_firstSite_lastN__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_SiteSearch_Actions.getSiteSearchCategories_firstSite_lastN__API.getProcessedReport_month.xml
  tests/PHPUnit/System/expected/test_SiteSearch_Actions.getSiteSearchKeywords_firstSite_lastN__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_SiteSearch_Actions.getSiteSearchKeywords_firstSite_lastN__API.getProcessedReport_month.xml
  tests/PHPUnit/System/expected/test_SiteSearch_Actions.getSiteSearchNoResultKeywords_firstSite_lastN__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_SiteSearch_Actions.getSiteSearchNoResultKeywords_firstSite_lastN__API.getProcessedReport_month.xml
  tests/PHPUnit/System/expected/test_SiteSearch_CustomVariables.getCustomVariables_firstSite_lastN__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_SiteSearch_CustomVariables.getCustomVariables_firstSite_lastN__API.getProcessedReport_month.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_Conversions_Goals.getDaysToConversion_firstSite_lastN__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getGlossaryReports.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getReportMetadata_day.xml
  tests/PHPUnit/System/expected/test_twoVisitsWithCustomVariables__subtable__API.getProcessedReport_day.xml
Labels: Enhancement, Major, Needs Review, c: Usability

#15056 Fix error core JS proxy couldn't be decoded when gzipped
  core/ProxyHttp.php
Labels: Needs Review, not-in-changelog

#14360 UserID no longer overwrites VisitorId
  CHANGELOG.md
  composer.lock
  core/Tracker/Request.php
  core/Tracker/Visit.php
  plugins/CoreHome/Tracker/VisitRequestProcessor.php
  tests/PHPUnit/Fixtures/FewVisitsWithSetVisitorId.php
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getEntryPageTitles_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getEntryPageTitles_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getEntryPageUrls_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getEntryPageUrls_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getExitPageTitles_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getExitPageTitles_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getExitPageUrls_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getExitPageUrls_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getPageTitles_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getPageTitles_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getPageUrls_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.get_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.get_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs__CustomVariables.getCustomVariables_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__DevicesDetection.getBrand_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__DevicesDetection.getBrowserEngines_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__DevicesDetection.getBrowserFamilies_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__DevicesDetection.getBrowserVersions_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__DevicesDetection.getBrowsers_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__DevicesDetection.getModel_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__DevicesDetection.getOsFamilies_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__DevicesDetection.getOsVersions_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__DevicesDetection.getType_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Live.getLastVisitsDetails_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Referrers.getAll_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Referrers.getReferrerType_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Referrers.getWebsites_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Resolution.getConfiguration_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Resolution.getResolution_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__UserCountry.getCity_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__UserCountry.getContinent_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__UserCountry.getCountry_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__UserCountry.getNumberOfDistinctCountries_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__UserCountry.getRegion_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__UserId.getUsers_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__UserLanguage.getLanguageCode_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__UserLanguage.getLanguage_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__VisitTime.getByDayOfWeek_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__VisitTime.getVisitInformationPerLocalTime_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__VisitTime.getVisitInformationPerServerTime_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__VisitorInterest.getNumberOfVisitsPerPage_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__VisitorInterest.getNumberOfVisitsPerPage_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs__VisitsSummary.getBounceCount_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__VisitsSummary.getSumVisitsLengthPretty_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__VisitsSummary.getSumVisitsLength_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__VisitsSummary.get_month.xml
  tests/PHPUnit/System/expected/test_UserId_VisitorId__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_UserId_VisitorId__VisitsSummary.get_day.xml
  tests/PHPUnit/System/expected/test_UserId_VisitorId__VisitsSummary.get_month.xml
  tests/PHPUnit/System/expected/test_UserId_VisitorId__VisitsSummary.get_week.xml
  tests/PHPUnit/System/expected/test_UserId_VisitorId__VisitsSummary.get_year.xml
  tests/PHPUnit/System/expected/test_UserId_VisitorId_segmentUserId__Goals.get_day.xml
  tests/PHPUnit/System/expected/test_UserId_VisitorId_segmentUserId__VisitsSummary.get_day.xml
Labels: Needs Review

#15088 Rename "Clicked URL" dimension to "Clicked Outlink"
  plugins/Actions/lang/en.json
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_loaded_token_auth.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_removed.png
  plugins/SegmentEditor/tests/UI/SegmentSelectorEditor_spec.js
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_add_new_and_condition.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_drag_and_condition.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_drag_or_condition.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_saved_details.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_updated_details.png
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_Actions.getOutlinks_firstSite_lastN__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getReportMetadata_day.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getSegmentsMetadata.xml
  tests/UI/expected-screenshots/Theme_home.png
  tests/UI/expected-screenshots/UIIntegrationTest_actions_outlinks.png
  tests/UI/expected-screenshots/enable_framed_pages_embed_whole_app.png
Labels: Needs Review

#15142 Fix "PHP Deprecated: strpos(): Non-string needles will be interprete…
  core/Access.php
Labels: Needs Review, not-in-changelog

#15147 Adds new event to define if lower metric values are better
  CHANGELOG.md
  core/Metrics.php
Labels: Needs Review

#15148 Ignore SSL errors in UI tests
  tests/lib/screenshot-testing/run-tests.js
Labels: Needs Review

#15152 Fix manual plugin upload process
  plugins/CorePluginsAdmin/PluginInstaller.php
Labels: Needs Review

#15158 String can be urlencoded when parsing range dates in client.
  plugins/CoreHome/angularjs/common/services/periods.js
Labels: Needs Review, not-in-changelog

#15153 Update composer dependencies
  composer.lock
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_in_pdf_tables_only__ScheduledReports.generateReport_week.original.pdf
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_in_pdf_tables_only__ScheduledReports.generateReport_month.original.pdf
Labels: Needs Review, not-in-changelog

#15166 Fix socket configuration not applied in MySQLi
  libs/Zend/Db/Adapter/Mysqli.php
Labels: Needs Review

#15162 Disable range select until overlay is fully loaded.
  plugins/Overlay/javascripts/Piwik_Overlay.js
  plugins/Overlay/templates/index.twig
Labels: Needs Review, not-in-changelog

#15154 Only add site to list of sites to reprocess if only date being processed is today.
  core/Archive/ArchiveInvalidator.php
  core/DataAccess/Model.php
  tests/PHPUnit/Fixtures/TwoSitesVisitsInPast.php
  tests/PHPUnit/Integration/DataAccess/ArchiveInvalidatorTest.php
  tests/PHPUnit/System/VisitsInPastInvalidateOldReportsTest.php
Labels: Needs Review, not-in-changelog

#15171 Proceed rate in Goal Funnel report and row evolution of funnel is mismatching
  core/API/Inconsistencies.php
Labels: Needs Review, not-in-changelog

#15180 Update lessphp to use branch for php 7.4 compatibility.
  composer.json
  composer.lock
Labels: Needs Review, not-in-changelog

#15178 API reference doc: fix some of the example links
  core/API/DocumentationGenerator.php
Labels: Needs Review

#15183 Update spyc to 0.6.X
  composer.json
  composer.lock
Labels: Needs Review

#15187 Fix broken dashboard when a new version available and when multi_server_environment = 1
  plugins/CoreHome/templates/_headerMessage.twig
Labels: Needs Review

#15189 Support CliMulti on OS X and print note about whether CliMulti is used in archive output
  core/CliMulti/Process.php
  core/CronArchive.php
  core/SettingsServer.php
  tests/PHPUnit/Integration/CronArchiveTest.php
Labels: Needs Review

#15195 [automatic translation update] Updated 160 strings in 6 languages (fr, it, ja, lt, pt-br, tr)
  lang/fr.json
  lang/it.json
  lang/ja.json
  plugins/Actions/lang/fr.json
  plugins/Actions/lang/it.json
  plugins/Actions/lang/ja.json
  plugins/Actions/lang/lt.json
  plugins/Actions/lang/pt-br.json
  plugins/Actions/lang/tr.json
  plugins/CoreAdminHome/lang/it.json
  plugins/CoreAdminHome/lang/ja.json
  plugins/CoreHome/lang/fr.json
  plugins/CoreHome/lang/it.json
  plugins/CoreHome/lang/ja.json
  plugins/CoreHome/lang/pt-br.json
  plugins/CoreHome/lang/tr.json
  plugins/DevicesDetection/lang/fr.json
  plugins/DevicesDetection/lang/ja.json
  plugins/DevicesDetection/lang/tr.json
  plugins/Feedback/lang/ja.json
  plugins/Live/lang/ja.json
  plugins/Marketplace/lang/ja.json
  plugins/Referrers/lang/fr.json
  plugins/Referrers/lang/it.json
  plugins/Referrers/lang/ja.json
  plugins/Referrers/lang/pt-br.json
  plugins/Referrers/lang/tr.json
  plugins/SegmentEditor/lang/it.json
  plugins/SegmentEditor/lang/ja.json
  plugins/SitesManager/lang/ja.json
  plugins/Tour/lang/fr.json
  plugins/Tour/lang/ja.json
Labels: c: i18n

#15089 Remove the SiteSpecificUserAgentExcludeEnabled setting
  CHANGELOG.md
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_widget_move.png
  plugins/SitesManager/API.php
  plugins/SitesManager/Controller.php
  plugins/SitesManager/SitesManager.php
  plugins/SitesManager/angularjs/sites-manager/sites-manager.controller.js
  plugins/SitesManager/lang/en.json
  plugins/SitesManager/templates/global-settings.html
  plugins/SitesManager/templates/sites-list/site-fields.html
  plugins/SitesManager/tests/UI/expected-screenshots/SitesManager_global_settings.png
  tests/PHPUnit/Fixtures/InvalidVisits.php
  tests/PHPUnit/Fixtures/OneVisitorTwoVisits.php
  tests/PHPUnit/Integration/Tracker/VisitTest.php
  tests/PHPUnit/System/DuplicateActionsTest.php
  tests/PHPUnit/System/OneVisitorTwoVisitsTest.php
  tests/PHPUnit/System/expected/test_BackwardsCompatibility1XTest__Tour.getChallenges.xml
  tests/PHPUnit/System/expected/test_BackwardsCompatibility1XTest__Tour.getLevel.xml
  tests/PHPUnit/System/expected/test_BackwardsCompatibility1XTest__VisitFrequency.get_range.xml
  tests/PHPUnit/System/expected/test_BackwardsCompatibility1XTest__VisitFrequency.get_year.xml
  tests/PHPUnit/System/expected/test_BackwardsCompatibility1XTest_multipleOldNew__VisitFrequency.get_month.xml
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
Labels: Needs Review

#15204 another PHP 7.3 fix
  libs/upgradephp/upgrade.php
Labels: Needs Review
