Repository matomo-org/matomo, pull requests merged in 2019-12, with the labels that each got.

#15213 Add method to detect if we are running within Matomo for WordPress
  CHANGELOG.md
  core/SettingsServer.php
Labels: Needs Review

#15222 Several PHP 7.4 fixes
  core/Tracker/Db/Mysqli.php
Labels: Needs Review

#15231 If not truncating response in CronArchive, do not replace newlines w/ spaces.
  core/CronArchive.php
Labels: Needs Review

#15219 fix PNG interlacing
  plugins/Installation/tests/UI/expected-screenshots/Installation_db_setup.png
  plugins/Installation/tests/UI/expected-screenshots/Installation_db_setup_fail.png
  plugins/Installation/tests/UI/expected-screenshots/Installation_start.png
  plugins/Installation/tests/UI/expected-screenshots/Installation_system_check.png
  plugins/Morpheus/images/logo-email.png
  plugins/Morpheus/images/logo-header.png
  plugins/Morpheus/images/logo.png
Labels: Needs Review, not-in-changelog

#15134 Fix header alignment for multi-dimension reports
  plugins/CoreHome/stylesheets/dataTable/_dataTable.less
  plugins/CoreHome/templates/_dataTableHead.twig
  plugins/CoreVisualizations/templates/_dataTableViz_htmlTable.twig
  tests/UI/expected-screenshots/Comparison_subtables_loaded.png
  tests/UI/expected-screenshots/ViewDataTableTest_dimension_columns.png
  tests/UI/expected-screenshots/ViewDataTableTest_dimension_search.png
Labels: Needs Review

#15228 Fix site selector shows undefined in custom dimensions
  core/Plugin/Controller.php
Labels: Needs Review, not-in-changelog

#15245 do not check licenses in development mode since it has no cache
  core/Plugin/ControllerAdmin.php
Labels: Needs Review

#15233 Fix Malformed URL in real-time-visitors module
  plugins/Actions/VisitorDetails.php
Labels: Needs Review, not-in-changelog

#15250 Prevent notice in installer enable_ssl not defined
  plugins/Installation/FormDatabaseSetup.php
Labels: Needs Review

#15218 remove unnecessary number format in visit summary
  plugins/CorePluginsAdmin/tests/UI/expected-screenshots/TagManagerTeaser_admin_page_disable.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/UnprocessedSegmentTest_custom_segment.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/UnprocessedSegmentTest_unprocessed_segment.png
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuth_logme_verified.png
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuth_twofa_forced_step4.png
  plugins/VisitsSummary/Reports/Get.php
Labels: Needs Review

#15252 Fix visitors overview ui test
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_overview_columns.png
  tests/UI/specs/UIIntegration_spec.js
Labels: Needs Review, c: Tests & QA

#15186 Use appropriate SameSite value for session cookie
  core/Session.php
  core/Session/SessionAuth.php
  lang/en.json
  libs/Zend/Session.php
Labels: Needs Review

#15255 Use PHP_BINDIR if other environment variables/constants are not present when looking for the PHP binary.
  core/CliMulti/CliPhp.php
Labels: Needs Review

#15225 Fix test cookie may be set multiple times
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: Needs Review, not-in-changelog

#15196 Add more debug info to archiving queries
  core/DataAccess/LogAggregator.php
Labels: Needs Review

#15224 PHP 7.4 warning in ColumnDelete
  core/DataTable/Filter/ColumnDelete.php
Labels: Needs Review

#15185 Use appropriate SameSite values for cookies
  core/Cookie.php
  core/Tracker/Request.php
  plugins/LanguagesManager/LanguagesManager.php
  tests/PHPUnit/System/CookieTest.php
Labels: Needs Review

#15271 Add method to get errors in Cron archive
  core/CronArchive.php
Labels: Needs Review

#15258 Trust cookie only when visitorId is set
  core/Tracker/VisitorRecognizer.php
Labels: Needs Review

#15260 Fix error message when not correct token is used in API
  core/Access.php
Labels: Bug

#15268 If fingers crossed handler is used make sure to print exception traces in CLI
  core/Console.php
Labels: Needs Review

#15276 Fix mysql table name too long while archiving a segment
  core/DataAccess/LogAggregator.php
  core/Db/Schema/Mysql.php
Labels: Needs Review

#15279 Couple tweaks to Environment class so current environment name can be easily queried.
  core/Application/Environment.php
Labels: Needs Review

#15282 Fix BC issues from #15128 PR
  plugins/Goals/API.php
  plugins/VisitFrequency/API.php
  tests/PHPUnit/System/expected/test_BackwardsCompatibility1XTest__VisitFrequency.get_day.xml
  tests/PHPUnit/System/expected/test_BackwardsCompatibility1XTest__VisitFrequency.get_month.xml
  tests/PHPUnit/System/expected/test_BackwardsCompatibility1XTest__VisitFrequency.get_range.xml
  tests/PHPUnit/System/expected/test_BackwardsCompatibility1XTest__VisitFrequency.get_week.xml
  tests/PHPUnit/System/expected/test_BackwardsCompatibility1XTest__VisitFrequency.get_year.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_invertCompare__VisitFrequency.get_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_noData_againsNoData__VisitFrequency.get_day.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_noData_againstWithData__VisitFrequency.get_day.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_periods__VisitFrequency.get_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_rangePeriodAgainstSingle__VisitFrequency.get_range.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_segmentsAndPeriods__VisitFrequency.get_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_segments__VisitFrequency.get_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_singleAgainstRange__VisitFrequency.get_day.xml
  tests/PHPUnit/System/expected/test_ImportLogs__VisitFrequency.get_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__VisitFrequency.get_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs_siteIdThree_TrackedUsingLogReplayWithFixedSiteId__VisitFrequency.get_range.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits__VisitFrequency.get_day.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits_withCookieSupport__VisitFrequency.get_day.xml
  tests/PHPUnit/System/expected/test_noVisit__VisitFrequency.get_day.xml
  tests/PHPUnit/System/expected/test_oneVisitor_oneWebsite_severalDays_DateRange__VisitFrequency.get_range.xml
Labels: Needs Review, not-in-changelog

#15297 Add tooltip to goal overview link.
  plugins/Goals/Goals.php
  plugins/Goals/angularjs/common/directives/goal-page-link.js
  plugins/Goals/lang/en.json
Labels: Needs Review

#15298 In EchoHandler print out formatted message, not just level and message.
  plugins/Monolog/Handler/EchoHandler.php
Labels: Needs Review

#15296 Make sure unprocessed segment notification is still shown and include notifications in UI test.
  core/Plugin/Visualization.php
  plugins/SegmentEditor/tests/UI/UnprocessedSegment_spec.js
Labels: Bug, Needs Review

#15303 Don't render goal when no goal name defined
  plugins/Live/VisitorDetails.php
Labels: Needs Review

#15285 Fix cli archiving might not work when using litespeed
  core/CliMulti/CliPhp.php
Labels: Needs Review

#15277 Remove output that can be ignored in climulti
  core/CliMulti/Output.php
  tests/PHPUnit/Integration/CliMulti/OutputTest.php
Labels: Needs Review

#15305 Disable pivot by if comparison is enabled.
  plugins/CoreHome/templates/_dataTableActions.twig
Labels: Needs Review

#15249 Prevent race conditions when updating plugin settings
  config/global.php
  core/Concurrency/Lock.php
  core/Db/Schema/Mysql.php
  core/Settings/Storage/Backend/BaseSettingsTable.php
  core/Settings/Storage/Backend/MeasurableSettingsTable.php
  core/Settings/Storage/Backend/PluginSettingsTable.php
  plugins/CorePluginsAdmin/Model/TagManagerTeaser.php
Labels: Needs Review

#15314 Updates device detector to 3.12.2
  composer.lock
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_browserEngine__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_browserName__API.getSuggestedValuesForSegment.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getSegmentsMetadata.xml
Labels: Needs Review, Task

#15309 Ignore disableCookie setting when giving consent / removing consent
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: Needs Review

#15265 ProxySite related changes to let comparisons work properly
  core/API/Request.php
  core/Plugin/Visualization.php
  plugins/Referrers/API.php
  plugins/Referrers/tests/System/expected/test_Referrers_getReferrerType__API.getProcessedReport_day.xml
  plugins/Referrers/tests/System/expected/test_phpSerialized__Referrers.getReferrerType_year.original
  plugins/ScheduledReports/Controller.php
  plugins/SegmentEditor/SegmentSelectorControl.php
  plugins/SegmentEditor/tests/UI/expected-screenshots/UnprocessedSegmentTest_unprocessed_segment.png
  tests/PHPUnit/System/expected/test_DataComparisonTest_invertCompare__Referrers.getAll_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_periods__Referrers.getAll_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_rangePeriodAgainstSingle__Referrers.getAll_range.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_segmentsAndPeriods__Referrers.getAll_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_segments__Referrers.getAll_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Referrers.getAll_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Referrers.getReferrerType_month.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits__Referrers.getAll_day.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits__Referrers.getReferrerType_day.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits_withCookieSupport__Referrers.getAll_day.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits_withCookieSupport__Referrers.getReferrerType_day.xml
  tests/PHPUnit/System/expected/test_reportLimiting__Referrers.getAll_day.xml
  tests/PHPUnit/System/expected/test_reportLimiting__Referrers.getReferrerType_day.xml
  tests/PHPUnit/System/expected/test_reportLimiting_flattened__Referrers.getAll_day.xml
  tests/PHPUnit/System/expected/test_reportLimiting_flattened__Referrers.getReferrerType_day.xml
  tests/PHPUnit/System/expected/test_reportLimiting_rankingQuery__Referrers.getAll_day.xml
  tests/PHPUnit/System/expected/test_reportLimiting_rankingQuery__Referrers.getReferrerType_day.xml
Labels: Needs Review

#15272 Lock when archiving and avoid invalidating sites that have archiving in progress
  config/global.php
  core/Archive/ArchiveInvalidator.php
  core/ArchiveProcessor/ArchivingStatus.php
  core/ArchiveProcessor/Loader.php
  core/ArchiveProcessor/Rules.php
  core/Concurrency/Lock.php
  core/Concurrency/LockBackend.php
  core/DataAccess/ArchiveSelector.php
  core/DataAccess/ArchivingDbAdapter.php
  core/DataAccess/LogAggregator.php
  core/DataAccess/Model.php
  tests/PHPUnit/Integration/ArchiveProcessor/ArchivingStatusTest.php
  tests/PHPUnit/Integration/ArchiveProcessor/LoaderTest.php
  tests/PHPUnit/Integration/DataAccess/ArchiveInvalidatorTest.php
  tests/PHPUnit/Integration/DataAccess/LogAggregatorTest.php
Labels: Needs Review, not-in-changelog

#15315 Fix more PHP 7.4 issues
  composer.json
  composer.lock
Labels: Needs Review, not-in-changelog

#15323 Add unit test missing from #15294
  plugins/API/tests/Unit/DataTable/MergeDataTablesTest.php
Labels: not-in-changelog

#15325 Revert prevent race condition in plugin settings #15249
  config/global.php
  core/Concurrency/Lock.php
  core/Db/Schema/Mysql.php
  core/Settings/Storage/Backend/BaseSettingsTable.php
  core/Settings/Storage/Backend/MeasurableSettingsTable.php
  core/Settings/Storage/Backend/PluginSettingsTable.php
  plugins/CorePluginsAdmin/Model/TagManagerTeaser.php
Labels: Pull Request WIP

#15312 Fix log tmp segment may be too long
  core/DataAccess/LogAggregator.php
  plugins/Login/Login.php
  plugins/TwoFactorAuth/Controller.php
  tests/PHPUnit/Integration/DataAccess/LogAggregatorTest.php
Labels: Needs Review, not-in-changelog

#15324 Remember consent given by default for 30 years
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: not-in-changelog

#15331 Fix some tests
  core/Tracker/Db/Mysqli.php
  tests/PHPUnit/Integration/Tracker/DbTest.php
Labels: not-in-changelog

#15184 Set a first-party cookie when user opts out of tracking
  core/Tracker/IgnoreCookie.php
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  plugins/CoreAdminHome/javascripts/optOut.js
  plugins/CoreAdminHome/lang/en.json
  plugins/CoreAdminHome/templates/optOut.twig
  tests/javascript/index.php
  tests/javascript/matomotest.js
Labels: Needs Review

#15333 fix tests broken since #15265
  tests/PHPUnit/System/expected/test_DataComparisonTest_invertCompare__Referrers.getAll_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_periods__Referrers.getAll_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_rangePeriodAgainstSingle__Referrers.getAll_range.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_segmentsAndPeriods__Referrers.getAll_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_segments__Referrers.getAll_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Referrers.getAll_month.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits__Referrers.getAll_day.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits_withCookieSupport__Referrers.getAll_day.xml
  tests/PHPUnit/System/expected/test_reportLimiting__Referrers.getAll_day.xml
  tests/PHPUnit/System/expected/test_reportLimiting_flattened__Referrers.getAll_day.xml
  tests/PHPUnit/System/expected/test_reportLimiting_rankingQuery__Referrers.getAll_day.xml
Labels: c: Tests & QA, not-in-changelog

#15329 If user is already super user, no need to set super user flag
  core/Access.php
Labels: Needs Review

#15330 Fix archiving when getmypid is disabled
  core/Archive/ArchiveInvalidator.php
  core/CliMulti/Process.php
  core/CronArchive.php
Labels: Needs Review

#15336 Prevent errors if limitVisits is <= 0.
  plugins/Live/API.php
Labels: Needs Review
