Repository matomo-org/matomo, pull requests merged in 2019-07, with the labels that each got.

#14596 Check $defaultLayout is an array when generating default dashboard
  plugins/Tour/Tour.php
Labels: not-in-changelog

#14598 Document possible BC break with Custom Dimension double encoding
  CHANGELOG.md
Labels: not-in-changelog

#14591 Improve segments tests
  plugins/API/tests/System/AutoSuggestAPITest.php
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_browserName__VisitsSummary.get_range.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_countryName__VisitsSummary.get_range.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_operatingSystemName__VisitsSummary.get_range.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_visitEndServerDate__VisitsSummary.get_range.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_visitEndServerDayOfMonth__VisitsSummary.get_range.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_visitEndServerYear__VisitsSummary.get_range.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_visitLocalMinute__VisitsSummary.get_range.xml
Labels: Needs Review, c: Tests & QA, not-in-changelog

#14562 Gracefully handle case when row evolution has no data
  plugins/API/RowEvolution.php
  plugins/API/tests/Integration/RowEvolutionTest.php
Labels: Needs Review

#14565 use same fontsize for links
  plugins/Feedback/angularjs/feedback-popup/feedback-popup.directive.less
Labels: Needs Review

#14581 Truncate very long useragents to prevent possible tracking slowdown
  core/DeviceDetectorFactory.php
Labels: Needs Review

#14620 Remove "open source web analytics" tooltip in app logo when a custom logo is uploaded
  plugins/CoreHome/templates/_logo.twig
Labels: Needs Review

#14616 If URL starts with // in sites manager, only prepend http: instead of… http://
  plugins/WebsiteMeasurable/Settings/Urls.php
Labels: Needs Review, not-in-changelog

#14618 Adds fbclid to excluded query parameters
  config/global.ini.php
Labels: Needs Review, not-in-changelog

#14627 Tweaks to Readme, updating links
  README.md
Labels: Needs Review

#14584 avoid using group by and select min for tracker actions query to avoid tmp tables refs #14535
  core/Tracker/Model.php
  tests/PHPUnit/Integration/Tracker/ModelTest.php
Labels: Needs Review, not-in-changelog

#14560 Hide date selector when viewing live visits (not as widget)
  plugins/CoreHome/angularjs/period-selector/period-selector.directive.js
  plugins/Live/javascripts/live.js
  plugins/UserCountryMap/javascripts/realtime-map.js
Labels: Needs Review, not-in-changelog

#14537 Copy downloaded plugin to all plugins directories
  core/Plugin/Manager.php
  plugins/CorePluginsAdmin/PluginInstaller.php
Labels: Needs Review

#14558 Fix padding in Visits in Real-time
  plugins/Live/stylesheets/live.less
  plugins/Morpheus/stylesheets/main.less
Labels: Needs Review, not-in-changelog

#14531 Fix GitHub links for 'About matomo'-Page (Footer)
  plugins/Feedback/templates/index.twig
Labels: Needs Review

#14600 Removes Zend_Cache
  libs/Zend/Cache.php
  libs/Zend/Cache/Backend.php
  libs/Zend/Cache/Backend/Apc.php
  libs/Zend/Cache/Backend/BlackHole.php
  libs/Zend/Cache/Backend/ExtendedInterface.php
  libs/Zend/Cache/Backend/File.php
  libs/Zend/Cache/Backend/Interface.php
  libs/Zend/Cache/Backend/Libmemcached.php
  libs/Zend/Cache/Backend/Memcached.php
  libs/Zend/Cache/Backend/Sqlite.php
  libs/Zend/Cache/Backend/Static.php
  libs/Zend/Cache/Backend/Test.php
  libs/Zend/Cache/Backend/TwoLevels.php
  libs/Zend/Cache/Backend/WinCache.php
  libs/Zend/Cache/Backend/Xcache.php
  libs/Zend/Cache/Backend/ZendPlatform.php
  libs/Zend/Cache/Backend/ZendServer.php
  libs/Zend/Cache/Backend/ZendServer/Disk.php
  libs/Zend/Cache/Backend/ZendServer/ShMem.php
  libs/Zend/Cache/Core.php
  libs/Zend/Cache/Exception.php
  libs/Zend/Cache/Frontend/Capture.php
  libs/Zend/Cache/Frontend/Class.php
  libs/Zend/Cache/Frontend/File.php
  libs/Zend/Cache/Frontend/Function.php
  libs/Zend/Cache/Frontend/Output.php
  libs/Zend/Cache/Frontend/Page.php
  libs/Zend/Cache/Manager.php
Labels: Task

#14448 allow to disable tracking failure notifications
  config/global.ini.php
  plugins/CoreAdminHome/Tasks.php
Labels: Needs Review

#14641 [automatic translation update] Updated 328 strings in 5 languages (pt-br, zh-cn, fr, ja, ro)
  lang/fr.json
  lang/ja.json
  lang/ro.json
  lang/zh-cn.json
  plugins/API/lang/fr.json
  plugins/Actions/lang/fr.json
  plugins/Annotations/lang/fr.json
  plugins/Annotations/lang/zh-cn.json
  plugins/CoreAdminHome/lang/fr.json
  plugins/CoreAdminHome/lang/zh-cn.json
  plugins/CoreHome/lang/fr.json
  plugins/CorePluginsAdmin/lang/fr.json
  plugins/CoreUpdater/lang/fr.json
  plugins/CustomPiwikJs/lang/pt-br.json
  plugins/CustomVariables/lang/fr.json
  plugins/CustomVariables/lang/pt-br.json
  plugins/Dashboard/lang/fr.json
  plugins/DevicePlugins/lang/fr.json
  plugins/Ecommerce/lang/fr.json
  plugins/Ecommerce/lang/ja.json
  plugins/Feedback/lang/fr.json
  plugins/GeoIp2/lang/fr.json
  plugins/Goals/lang/fr.json
  plugins/Goals/lang/zh-cn.json
  plugins/Installation/lang/fr.json
  plugins/IntranetMeasurable/lang/pt-br.json
  plugins/Live/lang/fr.json
  plugins/Marketplace/lang/fr.json
  plugins/MobileMessaging/lang/fr.json
  plugins/MobileMessaging/lang/pt-br.json
  plugins/Overlay/lang/fr.json
  plugins/PrivacyManager/lang/fr.json
  plugins/Referrers/lang/fr.json
  plugins/ScheduledReports/lang/fr.json
  plugins/SegmentEditor/lang/fr.json
  plugins/SitesManager/lang/fr.json
  plugins/SitesManager/lang/pt-br.json
  plugins/TwoFactorAuth/lang/fr.json
  plugins/TwoFactorAuth/lang/zh-cn.json
  plugins/UserCountry/lang/fr.json
  plugins/UserCountryMap/lang/fr.json
  plugins/UserCountryMap/lang/pt-br.json
  plugins/UsersManager/lang/fr.json
  plugins/UsersManager/lang/zh-cn.json
  plugins/VisitsSummary/lang/fr.json
Labels: c: i18n

#14576 Allow site selector dropdown to grow wider for websites with long names
  plugins/CoreHome/angularjs/siteselector/siteselector.directive.less
  tests/UI/expected-screenshots/SiteSelector_expanded.png
  tests/UI/expected-screenshots/SiteSelector_search_one_char.png
  tests/UI/expected-screenshots/SiteSelector_search_two_chars.png
Labels: Needs Review

#14640 Only permit scalar values for custom variables
  core/Tracker/Request.php
  tests/PHPUnit/Integration/Tracker/RequestTest.php
Labels: Needs Review

#14642 Split Integration tests into Core and Plugins
  .travis.yml
  tests/PHPUnit/phpunit.xml.dist
Labels: Needs Review, c: Tests & QA, not-in-changelog

#14643 Fix failing SEO test
  plugins/SEO/tests/Integration/SEOTest.php
Labels: Needs Review, c: Tests & QA, not-in-changelog

#14649 Fix span element self closing
  plugins/SegmentEditor/templates/_segmentSelector.twig
Labels: Needs Review, not-in-changelog

#14461 make opt-out iframe reload cacheless
  plugins/CoreAdminHome/javascripts/optOut.js
Labels: Needs Review

#14629 Long labels in left mobile menu may be shown on the next line
  plugins/CoreHome/angularjs/reporting-menu/reportingmenu.directive.html
Labels: Needs Review

#14624 various performance tweaks
  core/Option.php
  core/SettingsPiwik.php
  core/View.php
  plugins/CustomVariables/CustomVariables.php
Labels: Needs Review

#14476 use PHP filter to validate E-Mails
  config/global.php
  core/Piwik.php
  libs/Zend/Validate/EmailAddress.php
  tests/PHPUnit/Integration/EmailValidatorTest.php
Labels: Needs Review

#14482 send Referrer-Policy header
  core/View.php
Labels: Needs Review, c: Privacy

#14656 Migrate Tour plugin UI tests to headless Chrome...
  plugins/CoreUpdater/tests/UI/CoreUpdaterDb_spec.js
  plugins/Dashboard/tests/UI/DashboardManager_spec.js
  plugins/Dashboard/tests/UI/Dashboard_spec.js
  plugins/Feedback/tests/UI/FeedbackPopup_spec.js
  plugins/Tour/tests/UI/Tour_spec.js
  plugins/Tour/tests/UI/expected-screenshots/Tour_widget_all_completed.png
  plugins/Tour/tests/UI/expected-screenshots/Tour_widget_complete_some_challenges.png
  plugins/Tour/tests/UI/expected-screenshots/Tour_widget_complete_some_challenges_page_2.png
  plugins/Tour/tests/UI/expected-screenshots/Tour_widget_complete_some_challenges_page_3.png
  plugins/Tour/tests/UI/expected-screenshots/Tour_widget_initial.png
  plugins/Tour/tests/UI/expected-screenshots/Tour_widget_none_completed.png
  plugins/Tour/tests/UI/expected-screenshots/Tour_widget_skipped_goal.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_realtime_map.png
Labels: c: Tests & QA, not-in-changelog

#14655 Bump lodash from 4.17.11 to 4.17.14 in /tests/lib/screenshot-testing
  tests/lib/screenshot-testing/package-lock.json
Labels: c: Tests & QA

#14628 When installer is disabled and any module is requested, also show the not set up yet message
  core/Application/Kernel/EnvironmentValidator.php
Labels: Needs Review

#14449 Fix download issues via cURL with HTTP/2
  core/Http.php
  tests/PHPUnit/Integration/HttpTest.php
Labels: Needs Review

#14037 Update _updateCommunicationEmail.twig
  plugins/CoreUpdater/templates/_updateCommunicationEmail.twig
Labels: Needs Review

#14660 In JS tracker generator make sure to reuse same class when creating new file
  plugins/CustomPiwikJs/File.php
  plugins/CustomPiwikJs/TrackerUpdater.php
  plugins/CustomPiwikJs/tests/Integration/FileTest.php
Labels: Needs Review

#14657 Fix blocked XHR requests when widgetizing dashboard
  plugins/TwoFactorAuth/TwoFactorAuth.php
Labels: Needs Review

#14368 Fix missing 3rd party cookie when using POST requests
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  tests/javascript/index.php
Labels: Needs Review

#14661 Fix build
  core/Application/Kernel/EnvironmentValidator.php
  js/piwik-min.js
  js/piwik.js.orig
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: not-in-changelog

#13934 Implements a rate limit for password resets
  plugins/Login/PasswordResetter.php
  plugins/Login/lang/en.json
  plugins/Login/tests/Integration/PasswordResetterTest.php
Labels: Needs Review, not-in-changelog

#14672 fix environment validator test
  core/Application/Kernel/EnvironmentValidator.php
Labels: Needs Review, not-in-changelog

#14682 Fix Integration Test
  plugins/CoreUpdater/tests/Integration/UpdateCommunicationTest.php
Labels: not-in-changelog

#14683 Update cache component to 1.0.3
  composer.lock
Labels: Needs Review

#14684 [automatic translation update] Updated 269 strings in 7 languages (ja, uk, fr, el, es, tr, zh-cn)
  lang/ja.json
  plugins/Actions/lang/ja.json
  plugins/CoreAdminHome/lang/ja.json
  plugins/CoreHome/lang/ja.json
  plugins/CoreHome/lang/uk.json
  plugins/CorePluginsAdmin/lang/ja.json
  plugins/CoreUpdater/lang/ja.json
  plugins/CustomPiwikJs/lang/ja.json
  plugins/Dashboard/lang/ja.json
  plugins/DevicesDetection/lang/ja.json
  plugins/Diagnostics/lang/ja.json
  plugins/Ecommerce/lang/ja.json
  plugins/Events/lang/ja.json
  plugins/Feedback/lang/fr.json
  plugins/Feedback/lang/ja.json
  plugins/Goals/lang/el.json
  plugins/Goals/lang/es.json
  plugins/Goals/lang/ja.json
  plugins/Goals/lang/tr.json
  plugins/Goals/lang/zh-cn.json
  plugins/Insights/lang/ja.json
  plugins/Installation/lang/ja.json
  plugins/Live/lang/ja.json
  plugins/Login/lang/el.json
  plugins/Login/lang/es.json
  plugins/Login/lang/ja.json
  plugins/Login/lang/tr.json
  plugins/Marketplace/lang/ja.json
  plugins/MobileMessaging/lang/ja.json
  plugins/PrivacyManager/lang/ja.json
  plugins/ScheduledReports/lang/ja.json
  plugins/SegmentEditor/lang/ja.json
  plugins/SitesManager/lang/ja.json
  plugins/Transitions/lang/ja.json
  plugins/TwoFactorAuth/lang/ja.json
  plugins/UserCountry/lang/ja.json
  plugins/UsersManager/lang/ja.json
  plugins/UsersManager/lang/zh-cn.json
Labels: c: i18n

#14685 Updates Device Detector to 3.12.0
  composer.lock
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_browserName__API.getSuggestedValuesForSegment.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getSegmentsMetadata.xml
Labels: Task

#14681 Support configuration of a reader database
  config/global.ini.php
  core/Archive.php
  core/DataAccess/ArchiveSelector.php
  core/DataAccess/LogAggregator.php
  core/Db.php
  plugins/Actions/VisitorDetails.php
  plugins/Diagnostics/ConfigReader.php
  plugins/Diagnostics/Diagnostic/DbReaderCheck.php
  plugins/Diagnostics/config/config.php
  plugins/Diagnostics/lang/en.json
  plugins/Ecommerce/VisitorDetails.php
  plugins/Goals/VisitorDetails.php
  plugins/Live/Model.php
  plugins/Live/VisitorDetailsAbstract.php
  tests/PHPUnit/Framework/TestCase/SystemTestCase.php
  tests/PHPUnit/Integration/DbTest.php
Labels: Needs Review

#14676 Remove sponsors from the help page
  plugins/Feedback/templates/index.twig
Labels: Needs Review

#14666 fix 'secondaryDimension' isn't set in the Request when viewing row evolution in events
  plugins/Events/Reports/Base.php
Labels: Needs Review, not-in-changelog

#14687 Determine in file class if the file content is the same
  plugins/CustomPiwikJs/File.php
  plugins/CustomPiwikJs/TrackerUpdater.php
  plugins/CustomPiwikJs/tests/Integration/FileTest.php
Labels: Needs Review

#14692 Don't show feedback prompt when user does not exist
  plugins/Feedback/Feedback.php
Labels: Needs Review

#14696 Remove no longer needed require statement
  core/Plugin.php
Labels: Needs Review

#14424 Display error message after encountering ajax error in popover
  plugins/CoreHome/javascripts/popover.js
  plugins/Morpheus/javascripts/ajaxHelper.js
Labels: Needs Review, not-in-changelog

#14663 Add new property to store un-encoded site name for use in JS.
  core/Plugin/Controller.php
  plugins/Morpheus/templates/_jsGlobalVariables.twig
Labels: Needs Review

#14707 Fix missing translation key Goals_Patterns
  plugins/Goals/Goals.php
  plugins/Goals/angularjs/manage-goals/manage-goals.controller.js
Labels: Needs Review

#14671 Save DataTable metadata in records if added during archiving.
  core/DataTable.php
  tests/PHPUnit/Unit/DataTableTest.php
Labels: Needs Review, RFC

#14674 fix optUserOut cookie expires after session
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  plugins/Widgetize/Controller.php
Labels: Needs Review, not-in-changelog

#14712 Adds command to update iso region names
  plugins/API/tests/System/expected/test_AutoSuggestAPITest__Live.getLastVisitsDetails_range.xml
  plugins/GeoIp2/Commands/UpdateRegionCodes.php
  plugins/GeoIp2/data/isoRegionNames.php
  plugins/GeoIp2/tests/System/expected/test_ConvertRegionCodesToIsoTest_testExecute_ShouldConvertRegionCodes__UserCountry.getRegion_month.xml
  plugins/UserCountry/tests/System/expected/test_AttributeHistoricalDataWithLocationsTest_testExecute_ShouldReturnLogAfterWorkingWithSomeData__UserCountry.getCity_month.xml
  plugins/UserCountry/tests/System/expected/test_AttributeHistoricalDataWithLocationsTest_testExecute_ShouldReturnLogAfterWorkingWithSomeData__UserCountry.getRegion_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest__UserCountry.getCity_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest__UserCountry.getRegion_month.xml
Labels: Needs Review, c: i18n
