Repository matomo-org/matomo, pull requests merged in 2019-02, with the labels that each got.

#14068 Optimize all archive tables only monthly
  plugins/CoreAdminHome/Tasks.php
Labels: Needs Review

#14073 Don't access config setting directly
  core/Mail.php
Labels: Needs Review, not-in-changelog

#14003 Include non-sql migrations in update dry run output.
  core/Config.php
  core/Updater.php
  core/Updater/Migration/Plugin/Activate.php
  core/Updater/Migration/Plugin/Deactivate.php
  plugins/CoreUpdater/Controller.php
  plugins/CoreUpdater/javascripts/updateLayout.js
  plugins/CoreUpdater/lang/en.json
  plugins/CoreUpdater/templates/runUpdaterAndExit_welcome.twig
  plugins/CoreUpdater/tests/UI/expected-screenshots/CoreUpdaterDb_main.png
  plugins/CoreUpdater/tests/UI/expected-screenshots/CoreUpdaterDb_main_instance.png
  tests/PHPUnit/Integration/Updater/Migration/Plugin/FactoryTest.php
Labels: Needs Review, not-in-changelog

#14084 Remove old unused files
  tests/lib/java/mysql-connector-java-5.1.7.jar
  tests/lib/java/schemaSpy_5.0.0.jar
  tests/lib/screenshot-testing/node_modules/jambalaya/package.json
  tests/lib/screenshot-testing/npm-debug.log
Labels: Needs Review, not-in-changelog

#14081 POST to login plugin in login form
  plugins/Login/Controller.php
  plugins/Login/FormLogin.php
  plugins/Login/javascripts/login.js
  plugins/Login/templates/login.twig
Labels: Needs Review, not-in-changelog

#14089 rename composer dependency to avoid deprecation warning
  composer.json
  composer.lock
Labels: not-in-changelog

#14079 Make segmented visitor log in sales page only display visits with orders.
  core/ViewDataTable/Config.php
  core/Widget/WidgetsList.php
  plugins/API/ProcessedReport.php
  plugins/CoreHome/angularjs/widget-bydimension-container/widget-bydimension-container.directive.js
  plugins/Goals/Pages.php
  plugins/Live/javascripts/rowaction.js
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getReportPagesMetadata.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getWidgetMetadata.xml
Labels: Needs Review, not-in-changelog

#14098 Let plugins change the report type in sendReport event
  plugins/ScheduledReports/API.php
Labels: Needs Review, c: Platform

#14050 Add spans to realtime visitor log tooltips.
  plugins/Live/templates/getLastVisitsStart.twig
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_log.png
  tests/UI/expected-screenshots/UIIntegrationTest_ecommerce_log.png
Labels: Needs Review, not-in-changelog

#13923 Enable fingers crossed handler via INI config and show backtrace in logs/archive api output
  CHANGELOG.md
  core/API/Proxy.php
  core/API/Request.php
  core/API/ResponseBuilder.php
  core/ArchiveProcessor/PluginsArchiver.php
  core/CliMulti.php
  core/Development.php
  core/ErrorHandler.php
  core/ExceptionHandler.php
  core/FrontController.php
  core/Plugin/ViewDataTable.php
  core/Plugin/Visualization.php
  core/Session.php
  core/testMinimumPhpVersion.php
  plugins/CoreConsole/Commands/ClearCaches.php
  plugins/CustomVariables/Model.php
  plugins/Monolog/Handler/LogCaptureHandler.php
  plugins/Monolog/Handler/WebNotificationHandler.php
  plugins/Monolog/Processor/ExceptionToTextProcessor.php
  plugins/Monolog/config/config.php
  plugins/ScheduledReports/tests/Integration/ApiTest.php
  plugins/UserCountry/GeoIPAutoUpdater.php
  tests/PHPUnit/Fixtures/UITestFixture.php
  tests/PHPUnit/Framework/XssTesting.php
  tests/PHPUnit/Integration/DataTable/Filter/PivotByDimensionTest.php
  tests/PHPUnit/Integration/FrontControllerTest.php
  tests/PHPUnit/Integration/ReportTest.php
  tests/UI/specs/UIIntegration_spec.js
Labels: Needs Review

#14114 update cacert.pem
  core/DataFiles/cacert.pem
Labels: Task, not-in-changelog

#14116 Add better error message for unsupported operand error.
  core/DataTable/Row.php
  tests/PHPUnit/Unit/DataTable/RowTest.php
Labels: Needs Review

#14115 Realtime Log UI improvements/fixes
  plugins/Live/javascripts/live.js
  plugins/Live/stylesheets/live.less
Labels: Needs Review, Regression

#13978 Improve site search detection in fragment query
  plugins/Actions/Actions/ActionSiteSearch.php
  plugins/Actions/tests/Integration/ActionSiteSearchTest.php
Labels: Needs Review, not-in-changelog

#14092 In segmented visitor log, allow opening segment editor in new tab w/ segment used.
  core/ViewDataTable/Config.php
  plugins/CoreHome/templates/_dataTableActions.twig
  plugins/Live/Visualizations/VisitorLog.php
  plugins/Live/javascripts/SegmentedVisitorLog.js
  plugins/Live/javascripts/visitorLog.js
  plugins/SegmentEditor/javascripts/Segmentation.js
  plugins/SegmentEditor/lang/en.json
Labels: Needs Review, not-in-changelog

#14107 Tweak default tracker text that explains Matomo
  core/Tracker/Response.php
  tests/PHPUnit/Integration/TrackerTest.php
  tests/PHPUnit/System/TrackerResponseTest.php
  tests/PHPUnit/Unit/Tracker/ResponseTest.php
Labels: Needs Review, not-in-changelog

#14121 Noindex, nofollow for login page and tracker default output
  core/Tracker/Response.php
  plugins/Actions/tests/UI/expected-screenshots/ActionsDataTable_segmented_visitor_log.png
  plugins/Login/templates/loginLayout.twig
  tests/PHPUnit/Integration/TrackerTest.php
  tests/PHPUnit/System/TrackerResponseTest.php
  tests/PHPUnit/Unit/Tracker/ResponseTest.php
  tests/UI/expected-screenshots/UIIntegrationTest_segmented_visitorlog.png
Labels: Needs Review, not-in-changelog

#14078 Make access level filter in user permissions edit default to showing all websites.
  plugins/UsersManager/angularjs/user-permissions-edit/user-permissions-edit.component.js
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_admin_view_admin_edit_permissions.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_permissions_edit.png
Labels: Needs Review, not-in-changelog

#14077 Hide View Detailed Visitor Log link when realtime visits widget is embedded.
  plugins/Dashboard/javascripts/widgetMenu.js
  plugins/Live/stylesheets/live.less
Labels: Needs Review, not-in-changelog

#14016 Do not render until form is initialized
  plugins/ScheduledReports/angularjs/manage-scheduled-report/manage-scheduled-report.controller.js
  plugins/ScheduledReports/templates/_addReport.twig
  tests/UI/expected-screenshots/UIIntegrationTest_email_reports_editor.png
Labels: Needs Review

#14134 [automatic translation update] Updated 455 strings in 8 languages (ru, fr, he, lv, sv, it, el, sq)
  lang/fr.json
  lang/he.json
  lang/lv.json
  lang/ru.json
  plugins/CoreAdminHome/lang/fr.json
  plugins/CoreAdminHome/lang/sv.json
  plugins/CoreHome/lang/fr.json
  plugins/CoreHome/lang/sv.json
  plugins/CorePluginsAdmin/lang/fr.json
  plugins/CoreUpdater/lang/fr.json
  plugins/CoreUpdater/lang/it.json
  plugins/CoreUpdater/lang/ru.json
  plugins/CustomPiwikJs/lang/fr.json
  plugins/CustomPiwikJs/lang/it.json
  plugins/CustomPiwikJs/lang/ru.json
  plugins/CustomVariables/lang/fr.json
  plugins/Diagnostics/lang/fr.json
  plugins/Diagnostics/lang/ru.json
  plugins/Events/lang/fr.json
  plugins/GeoIp2/lang/ru.json
  plugins/Goals/lang/fr.json
  plugins/Installation/lang/fr.json
  plugins/Installation/lang/it.json
  plugins/Installation/lang/sv.json
  plugins/IntranetMeasurable/lang/ru.json
  plugins/Live/lang/fr.json
  plugins/Live/lang/ru.json
  plugins/Login/lang/fr.json
  plugins/Login/lang/ru.json
  plugins/MultiSites/lang/ru.json
  plugins/PrivacyManager/lang/fr.json
  plugins/Referrers/lang/fr.json
  plugins/Referrers/lang/ru.json
  plugins/Referrers/lang/sv.json
  plugins/ScheduledReports/lang/fr.json
  plugins/ScheduledReports/lang/ru.json
  plugins/SegmentEditor/lang/el.json
  plugins/SegmentEditor/lang/it.json
  plugins/SegmentEditor/lang/sq.json
  plugins/SitesManager/lang/ru.json
  plugins/Transitions/lang/fr.json
  plugins/TwoFactorAuth/lang/fr.json
  plugins/UsersManager/lang/fr.json
  plugins/UsersManager/lang/sv.json
  plugins/VisitTime/lang/ru.json
Labels: c: i18n

#14111 If more than one yaxis in a jqplot graph, make sure there is space on right for it.
  plugins/CoreVisualizations/javascripts/jqplot.js
  tests/UI/expected-screenshots/EvolutionGraph_bounce_rate.png
Labels: Needs Review, not-in-changelog

#13961 Show next link in visitor log only if more records are available
  plugins/Live/Visualizations/VisitorLog.php
Labels: Needs Review, not-in-changelog

#14142 Fix undefined error in segmentation.js
  plugins/SegmentEditor/javascripts/Segmentation.js
Labels: not-in-changelog

#14144 Fix build
  core/API/DocumentationGenerator.php
  plugins/Actions/tests/UI/expected-screenshots/ActionsDataTable_segmented_visitor_log.png
  plugins/CoreAdminHome/angularjs/trackingcode/jstrackingcode.controller.js
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_reset.png
  tests/PHPUnit/System/expected/test_OneVisitor_NoKeywordSpecified__Live.getLastVisitsDetails_day.xml
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
  tests/UI/expected-screenshots/UIIntegrationTest_ecommerce_log.png
  tests/UI/expected-screenshots/UIIntegrationTest_ecommerce_log_segmented.png
  tests/UI/expected-screenshots/UIIntegrationTest_ecommerce_sales.png
  tests/UI/expected-screenshots/UIIntegrationTest_widgets_listing.png
  tests/UI/specs/UIIntegration_spec.js
Labels: not-in-changelog

#14093 remove getKeywordsForPageUrl widget
  CHANGELOG.md
  plugins/Referrers/API.php
  plugins/Referrers/Controller.php
  plugins/Referrers/Widgets/GetKeywordsForPage.php
  plugins/Widgetize/tests/System/WidgetTest.php
  tests/PHPUnit/Fixtures/UITestFixture.php
  tests/PHPUnit/Integration/WidgetsListTest.php
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getWidgetMetadata.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getWidgetMetadata_day.xml
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
Labels: Needs Review
