Repository matomo-org/matomo, pull requests merged in 2020-06, with the labels that each got.

#15997 Fix min archive time not correctly respected
  core/DataAccess/ArchiveSelector.php
Labels: Needs Review

#16010 Optional userLogin in getUserPreference API
  CHANGELOG.md
  plugins/UsersManager/API.php
  plugins/UsersManager/tests/System/ApiTest.php
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
Labels: Needs Review

#15994 SQL type FLOAT should not be used for economical data
  core/Columns/Updater.php
  core/Db/Schema/Mysql.php
  core/Updates/4.0.0-b1.php
  plugins/Ecommerce/Columns/RevenueDiscount.php
  plugins/Ecommerce/Columns/RevenueShipping.php
  plugins/Ecommerce/Columns/RevenueSubtotal.php
  plugins/Ecommerce/Columns/RevenueTax.php
  tests/PHPUnit/Integration/Columns/UpdaterTest.php
Labels: Needs Review, not-in-changelog

#15996 Fix today archive is not being archived
  core/DataAccess/ArchiveSelector.php
Labels: Needs Review, not-in-changelog

#15991 Archiving job prioritization and safety precautions
  core/CliMulti.php
  core/CliMulti/RequestParser.php
  core/CronArchive.php
  core/DataAccess/ArchiveSelector.php
  core/DataAccess/Model.php
  core/Period.php
  tests/PHPUnit/Framework/Mock/FakeCliMulti.php
  tests/PHPUnit/Integration/CronArchiveTest.php
  tests/PHPUnit/Integration/DataAccess/ModelTest.php
  tests/PHPUnit/Unit/CliMulti/RequestParserTest.php
  tests/PHPUnit/Unit/PeriodTest.php
Labels: Needs Review, not-in-changelog

#16003 fix #16002
  plugins/CoreUpdater/Tasks.php
Labels: Needs Review, not-in-changelog

#16016 Fix details overlay for links in overlay mode
  plugins/Overlay/client/translations.js
Labels: Needs Review, Regression, not-in-changelog

#16017 Do not generate crossdomain link when cookies are disabled
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: Needs Review

#16029 Keep JSON2 format in Matomo 4
  CHANGELOG.md
  core/API/ApiRenderer.php
  tests/PHPUnit/Unit/API/ApiRendererTest.php
Labels: Needs Review, not-in-changelog

#16038 Use latest version of iframeresizer
  package-lock.json
  package.json
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/javascripts/iframeResizer.contentWindow.min.js
  plugins/CoreHome/javascripts/iframeResizer.min.js
Labels: Needs Review, not-in-changelog

#16023 Remove StaticContainer usage from Live plugin controller
  plugins/Live/Controller.php
Labels: Needs Review, not-in-changelog

#16039 apply timezone just before querying the log tables in Loader optimization
  core/ArchiveProcessor/Loader.php
  core/CronArchive.php
  core/Period.php
  tests/PHPUnit/Unit/PeriodTest.php
Labels: Needs Review, not-in-changelog

#16045 Fix saving of personal settings
  plugins/UsersManager/angularjs/personal-settings/personal-settings.controller.js
Labels: Needs Review, Regression, not-in-changelog

#16042 Expose setVisitorId JS tracker method
  CHANGELOG.md
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  tests/javascript/index.php
Labels: Needs Review

#16046 Fix metric format for page performance sparklines
  plugins/PagePerformance/Reports/Get.php
Labels: Needs Review, Regression, not-in-changelog

#16041 Document breaking change in bulk request API
  CHANGELOG.md
  tests/PHPUnit/System/OneVisitorTwoVisitsTest.php
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits_bulk_json__API.getBulkRequest.json
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits_bulk_xml__API.getBulkRequest.xml
Labels: Needs Review, not-in-changelog

#15998 Date factory test when date object is passed
  core/Date.php
  core/Scheduler/Schedule/Schedule.php
  plugins/Contents/tests/Fixtures/TwoVisitsWithContents.php
  plugins/Contents/tests/System/expected/test_Contents__Live.getLastVisitsDetails_day.xml
  plugins/Contents/tests/System/expected/test_Contents__Live.getLastVisitsDetails_month.xml
  plugins/Contents/tests/System/expected/test_Contents_contentInteractionMatch__Live.getLastVisitsDetails_day.xml
  plugins/Contents/tests/System/expected/test_Contents_contentTargetMatch__Live.getLastVisitsDetails_day.xml
  plugins/Contents/tests/System/expected/test_ContentscontentNameOrPieceMatch__Live.getLastVisitsDetails_day.xml
  tests/PHPUnit/Fixtures/ThreeVisitsWithCustomEvents.php
  tests/PHPUnit/System/expected/test_CustomEvents__Live.getLastVisitsDetails_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents__Live.getLastVisitsDetails_month.xml
Labels: Needs Review

#16054 Rename PHP Events that contain Piwik to Matomo
  CHANGELOG.md
  core/Tracker/TrackerCodeGenerator.php
  tests/PHPUnit/Integration/Tracker/TrackerCodeGeneratorTest.php
Labels: Needs Review

#16053 Rename Piwik -> Matomo in cookies
  PRIVACY.md
  config/global.ini.php
  core/Session.php
  core/Session/SessionFingerprint.php
  core/Updates/4.0.0-b2.php
  plugins/Login/tests/Integration/SessionInitializerTest.php
Labels: Needs Review

#16052 Rename Piwik -> Matomo in JS tracker where possible
  CHANGELOG.md
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  plugins/Overlay/client/client.js
  plugins/Overlay/client/followingpages.js
  plugins/Overlay/client/translations.js
  tests/javascript/content-fixtures/contentUtilities.html
  tests/javascript/content-fixtures/findContentNodesTest.html
  tests/javascript/index.php
  tests/javascript/matomotest.js
Labels: Needs Review

#16061 Document which APIs break in particular for JSON response
  CHANGELOG.md
Labels: Needs Review, not-in-changelog

#16064 do not prefix url if it is about:blank in ui tests
  tests/lib/screenshot-testing/support/page-renderer.js
Labels: not-in-changelog

#16012 Improve newsletter privacy note in installation
  plugins/Installation/lang/en.json
  plugins/Installation/tests/UI/expected-screenshots/Installation_superuser.png
  plugins/Installation/tests/UI/expected-screenshots/Installation_superuser_fail.png
Labels: Needs Review, not-in-changelog

#16075 Ensure dialogs can be moved smoothly
  plugins/Morpheus/stylesheets/ui/_popups.less
Labels: Needs Review, Regression, not-in-changelog

#16070 Add legacy autoloader for 2.x-dev for smoother upgrades
  LegacyAutoloader.php
  composer.json
  core/Plugin/ControllerAdmin.php
  core/Version.php
Labels: Needs Review

#16068 Mention users should not share their token with anyone
  plugins/UsersManager/lang/en.json
  plugins/UsersManager/templates/addNewTokenSuccess.twig
  plugins/UsersManager/tests/UI/expected-screenshots/UserSettings_add_token_success.png
Labels: Needs Review, not-in-changelog

#16069 Add legacy autoloader to support Matomo namespaces in 3.X
  LegacyAutoloader.php
  composer.json
Labels: Needs Review

#16080 Fix materializecss modal options
  plugins/CoreHome/angularjs/common/directives/dialog.js
  plugins/Morpheus/javascripts/piwikHelper.js
Labels: Needs Review, not-in-changelog

#16077 Organise Changelog better
  CHANGELOG.md
Labels: Needs Review, not-in-changelog

#16084 Document StaticContainer considered no longer API
  CHANGELOG.md
Labels: not-in-changelog

#16085 Mention few more tracker changes in changelog
  CHANGELOG.md
Labels: Needs Review, not-in-changelog

#16088 Try to fix randomly failing UI test
  plugins/PagePerformance/tests/UI/PagePerformance_spec.js
Labels: c: Tests & QA, not-in-changelog

#16066 Makes report export overlay compatible with app specific tokens
  core/Access.php
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/angularjs/report-export/reportexport.directive.js
  plugins/CoreHome/angularjs/report-export/reportexport.popover.html
  plugins/CoreHome/lang/en.json
Labels: Needs Review, not-in-changelog

#16092 Allow configuration of a shorter lock wait time in tracker mode
  config/global.ini.php
  core/Tracker/Db.php
  core/Tracker/Db/Pdo/Mysql.php
  plugins/BulkTracking/Tracker/Handler.php
  tests/PHPUnit/Integration/Tracker/DbTest.php
Labels: Needs Review

#16091 Delete segments when a site is deleted
  plugins/SegmentEditor/SegmentEditor.php
Labels: Needs Review

#16100 also support python 3.8
  CHANGELOG.md
Labels: not-in-changelog

#16087 Critical: Fixed wrong escaping of cookie path
  core/Cookie.php
Labels: Needs Review, Regression

#16106 Fix wrong escaping of cookie path
  core/Cookie.php
Labels: Needs Review

#16089 Remove custom variables requirement hint for site search categories
  plugins/Goals/VisitorDetails.php
  plugins/SitesManager/angularjs/sites-manager/sites-manager-site.controller.js
  plugins/SitesManager/angularjs/sites-manager/sites-manager.controller.js
  plugins/SitesManager/templates/global-settings.html
  plugins/SitesManager/templates/sites-list/site-search-field.html
  plugins/SitesManager/tests/System/expected/test_SitesManager__SitesManager.getSiteSettings.xml
  plugins/WebsiteMeasurable/MeasurableSettings.php
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getAvailableMeasurableTypes.xml
Labels: Needs Review, not-in-changelog

#16108 Fix failing test for mysqli
  tests/PHPUnit/Integration/Tracker/DbTest.php
Labels: Needs Review, c: Tests & QA, not-in-changelog

#16006 Removing piwik composer deprecations
  composer.json
  composer.lock
Labels: Needs Review

#16110 Fix tests in 3.x
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_in_pdf_tables_only__ScheduledReports.generateReport_week.original.pdf
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_in_pdf_tables_only__ScheduledReports.generateReport_month.original.pdf
  tests/PHPUnit/Unit/NonceTest.php
Labels: not-in-changelog

#16111 Fix nonce tests in 3.x
  core/Nonce.php
Labels: not-in-changelog

#16117 Use correct color for text fields
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_invalid_token_auth.png
  plugins/Login/tests/UI/expected-screenshots/Login_forgot_password.png
  plugins/Login/tests/UI/expected-screenshots/Login_password_reset_complete.png
  plugins/Morpheus/stylesheets/general/_forms.less
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuth_logme_not_verified.png
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuth_logme_not_verified_wrong_code.png
  tests/UI/expected-screenshots/SiteSelector_expanded.png
  tests/UI/expected-screenshots/SiteSelector_search_no_results.png
  tests/UI/expected-screenshots/SiteSelector_search_one_char.png
  tests/UI/expected-screenshots/SiteSelector_search_two_chars.png
  tests/UI/expected-screenshots/UIIntegrationTest_invalid_idsite.png
  tests/UI/expected-screenshots/UIIntegrationTest_not_logged_in.png
Labels: Needs Review, not-in-changelog

#16105 Rename referrer spam list
  CHANGELOG.md
  core/Tracker/VisitExcluded.php
  plugins/CoreAdminHome/Tasks.php
  plugins/CoreAdminHome/tests/Integration/TasksTest.php
Labels: Needs Review

#16115 Configure device detector cache through DI
  config/global.php
  core/DeviceDetector/DeviceDetectorFactory.php
  plugins/API/Menu.php
Labels: Needs Review

#15973 add missing link to consent help page
  plugins/PrivacyManager/lang/en.json
  plugins/PrivacyManager/templates/askingForConsent.twig
Labels: Needs Review, c: i18n

#16130 Fix UI test in privacy manager
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_consent_default.png
Labels: not-in-changelog

#13109 Fix 3rd party cookie / global visitorid race condition
  core/Tracker/Request.php
  js/tracker.php
Labels: Needs Review

#15887 Improve performance/memory of archive selection
  core/DataAccess/ArchiveSelector.php
  core/DataAccess/Model.php
  tests/PHPUnit/Integration/DataAccess/ArchiveSelectorTest.php
Labels: Pull Request WIP

#15979 no cut-off icons in DataTables
  plugins/CoreHome/stylesheets/dataTable/_dataTable.less
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_removed.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_loaded_token_auth.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_removed.png
  plugins/MultiSites/tests/UI/expected-screenshots/MultiSitesTest_all_websites.png
  plugins/MultiSites/tests/UI/expected-screenshots/MultiSitesTest_all_websites_changed_sort_order.png
  plugins/MultiSites/tests/UI/expected-screenshots/MultiSitesTest_all_websites_page_1.png
  plugins/MultiSites/tests/UI/expected-screenshots/MultiSitesTest_all_websites_range.png
  plugins/MultiSites/tests/UI/expected-screenshots/MultiSitesTest_all_websites_search.png
  tests/UI/expected-screenshots/Comparison_normal_table.png
  tests/UI/expected-screenshots/Comparison_normal_table_no_periods.png
  tests/UI/expected-screenshots/Comparison_normal_table_no_segments.png
  tests/UI/expected-screenshots/Comparison_subtables_loaded.png
  tests/UI/expected-screenshots/Comparison_subtables_paginate.png
  tests/UI/expected-screenshots/Theme_home.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard1.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard2.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard3.png
  tests/UI/expected-screenshots/UIIntegrationTest_referrers_search_engines_keywords.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_devices.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_software.png
  tests/UI/expected-screenshots/UIIntegrationTest_widgetize_allwebsites.png
  tests/UI/expected-screenshots/ViewDataTableTest_11_flattened.png
  tests/UI/expected-screenshots/ViewDataTableTest_12_aggregate_shown.png
  tests/UI/expected-screenshots/ViewDataTableTest_dimension_columns.png
  tests/UI/expected-screenshots/ViewDataTableTest_dimension_search.png
  tests/UI/expected-screenshots/ViewDataTableTest_flatten_search.png
  tests/UI/expected-screenshots/ViewDataTableTest_related_report_click.png
  tests/UI/expected-screenshots/ViewDataTableTest_subtables_loaded.png
Labels: Needs Review, c: Design / UI

#16122 Try to avoid ui test failures due to CSS loading failures
  core/ProxyHttp.php
  plugins/Installation/tests/UI/expected-screenshots/Installation_superuser_de.png
  tests/lib/screenshot-testing/support/page-renderer.js
Labels: Needs Review, c: Tests & QA, not-in-changelog

#16101 Better detection for cookies for browser plugins report for hybrid consent
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: Needs Review, not-in-changelog

#15955 Do not check if any archive is running when a segment is forced
  core/CronArchive.php
Labels: Needs Review

#16132 Fix names of viewed product category dimensions
  plugins/Ecommerce/Columns/ProductViewCategory.php
Labels: Needs Review, not-in-changelog

#16131 Show different message in password confirmation email to reduce confusion
  plugins/UsersManager/lang/en.json
  plugins/UsersManager/templates/_userInfoChangedEmail.twig
Labels: Needs Review, not-in-changelog

#13301 IgnoreCookie: added support for cookie_domain and ignore cookie signature
  core/Cookie.php
  core/Tracker/IgnoreCookie.php
Labels: Needs Review

#16163 Make geolocation provider work with isp database only
  plugins/GeoIp2/LocationProvider/GeoIp2/Php.php
Labels: Needs Review
