Repository matomo-org/matomo, pull requests merged in 2020-07, with the labels that each got.

#16170 Clarify developer changelog as it's not clear that we would keep BC for these
  CHANGELOG.md
Labels: not-in-changelog

#16113 Add method to enable cookies in JS
  core/Option.php
  core/Tracker/Settings.php
  core/Tracker/Visit.php
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  plugins/API/tests/System/expected/test_AutoSuggestAPITest__Live.getLastVisitsDetails_range.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_fingerprint__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_fingerprint__VisitsSummary.get_range.xml
  plugins/DevicesDetection/tests/System/expected/test___DevicesDetection.getBrand_day.xml
  plugins/DevicesDetection/tests/System/expected/test___DevicesDetection.getModel_day.xml
  plugins/DevicesDetection/tests/System/expected/test___DevicesDetection.getType_day.xml
  plugins/ExampleLogTables/tests/System/expected/test_ExampleLogTables_admin__UserId.getUsers_month.xml
  plugins/ExampleLogTables/tests/System/expected/test_ExampleLogTables_admin__VisitsSummary.get_month.xml
  plugins/ExampleLogTables/tests/System/expected/test_ExampleLogTables_all__UserId.getUsers_month.xml
  plugins/ExampleLogTables/tests/System/expected/test_ExampleLogTables_all__VisitsSummary.get_month.xml
  plugins/ExampleLogTables/tests/System/expected/test_ExampleLogTables_men__UserId.getUsers_month.xml
  plugins/ExampleLogTables/tests/System/expected/test_ExampleLogTables_men__VisitsSummary.get_month.xml
  plugins/ExampleLogTables/tests/System/expected/test_ExampleLogTables_women__UserId.getUsers_month.xml
  plugins/ExampleLogTables/tests/System/expected/test_ExampleLogTables_women__VisitsSummary.get_month.xml
  plugins/UserId/tests/System/expected/test___UserId.getUsers_range.xml
  plugins/UserId/tests/System/expected/test_ascSortOrder__UserId.getUsers_range.xml
  plugins/UserId/tests/System/expected/test_limit__UserId.getUsers_range.xml
  plugins/UserId/tests/System/expected/test_searchByUserId__UserId.getUsers_range.xml
  tests/PHPUnit/Integration/OptionTest.php
  tests/PHPUnit/System/expected/test_Archive_InvalidationWebsite2_NewDataShouldAppear__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs_siteIdThree_TrackedUsingLogReplayWithFixedSiteId__Live.getLastVisitsDetails_range.xml
  tests/PHPUnit/System/expected/test_UserId_VisitorId__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_UserId_VisitorId__VisitsSummary.get_month.xml
  tests/javascript/index.php
Labels: Needs Review, not-in-changelog

#16073 Removes double escaping in siteselector tooltip
  plugins/CoreHome/angularjs/siteselector/siteselector.directive.html
Labels: Needs Review, not-in-changelog

#16169 Improve host validation
  CHANGELOG.md
  core/Plugin/Controller.php
  core/Profiler.php
  core/Url.php
  plugins/ScheduledReports/config/tcpdf_config.php
  tests/PHPUnit/Integration/Config/CacheTest.php
  tests/PHPUnit/Unit/NonceTest.php
  tests/PHPUnit/Unit/UrlTest.php
  tests/PHPUnit/bootstrap.php
  tests/resources/install-matomo.php
Labels: Needs Review, c: Security

#16174 Set longer ignore cookie expiry time
  core/Tracker/IgnoreCookie.php
Labels: Needs Review, not-in-changelog

#16173 Don't set any cookies when no consent is given
  js/piwik.js
  tests/javascript/index.php
Labels: Needs Review, not-in-changelog

#16182 don't specify optional parameters before required parameters
  core/Http.php
Labels: Needs Review

#16181 don't use create_function() anywhere
  libs/HTML/QuickForm2/Element/Date.php
  plugins/Diagnostics/Diagnostic/PhpFunctionsCheck.php
  plugins/Installation/lang/en.json
Labels: Needs Review

#16178 Implement cookie consent
  CHANGELOG.md
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  tests/javascript/index.php
Labels: Needs Review

#16185 don't specify optional parameters before required parameters
  plugins/CoreHome/Controller.php
  plugins/SegmentEditor/SegmentSelectorControl.php
  plugins/UsersManager/API.php
  plugins/UsersManager/Controller.php
  plugins/UsersManager/UserPreferences.php
  plugins/UsersManager/tests/Integration/APITest.php
  plugins/UsersManager/tests/Integration/UsersManagerTest.php
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
Labels: Needs Review, not-in-changelog

#16187 Make Matomo more compatible with jQuery 3
  plugins/CoreHome/angularjs/reporting-page/reportingpage.directive.html
  plugins/CoreHome/angularjs/widget-loader/widgetloader.directive.html
Labels: Needs Review, not-in-changelog

#16188 Link to tracking consent guide to not have duplicate content
  plugins/PrivacyManager/lang/en.json
  plugins/PrivacyManager/templates/askingForConsent.twig
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_consent_default.png
Labels: Needs Review, not-in-changelog

#16194 Styling tweak for multituple labels.
  plugins/CorePluginsAdmin/CorePluginsAdmin.php
  plugins/CorePluginsAdmin/angularjs/form-field/field-multituple.html
  plugins/CorePluginsAdmin/angularjs/form-field/field-multituple.less
  plugins/Diagnostics/tests/UI/expected-screenshots/Diagnostics_page.png
  plugins/Installation/tests/UI/expected-screenshots/Installation_system_check.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_settings_general.png
  tests/UI/expected-screenshots/UIIntegrationTest_widgetize_ecommercelog.png
Labels: not-in-changelog

#16190 Generated tracking code should init window._paq and only use async
  plugins/Morpheus/templates/javascriptCode.twig
  plugins/SitesManager/tests/System/expected/test_SitesManager_after3_7_0__SitesManager.getJavascriptTag.xml
  plugins/SitesManager/tests/System/expected/test_SitesManager_prior3_7_0__SitesManager.getJavascriptTag.xml
  plugins/SitesManager/tests/System/expected/test_SitesManager_prior3_7_0_but_forced__SitesManager.getJavascriptTag.xml
  tests/PHPUnit/Integration/Tracker/TrackerCodeGeneratorTest.php
  tests/PHPUnit/System/expected/test_apiGetReportMetadata_year__SitesManager.getJavascriptTag.xml
  tests/UI/expected-screenshots/EmptySite_emptySiteDashboard.png
  tests/UI/expected-screenshots/OneClickUpdate_login.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_manage_tracking_code.png
Labels: Needs Review, not-in-changelog

#16195 Backport support for matomo_ignore class
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: not-in-changelog

#16201 Follow up change only triggering error when no start and end date is set
  core/Segment.php
Labels: Needs Review, not-in-changelog

#16206 Add new user preference
  plugins/UsersManager/API.php
Labels: Needs Review, not-in-changelog

#16213 Fix version number in developer changelog
  CHANGELOG.md
Labels: not-in-changelog

#16197 Make it possible to detect other clients than Browsers
  plugins/CoreUpdater/tests/UI/expected-screenshots/CoreUpdaterDb_main.png
  plugins/CoreUpdater/tests/UI/expected-screenshots/CoreUpdaterDb_main_instance.png
  plugins/DevicesDetection/API.php
  plugins/DevicesDetection/Columns/BrowserName.php
  plugins/DevicesDetection/Columns/ClientType.php
  plugins/DevicesDetection/VisitorDetails.php
  plugins/DevicesDetection/functions.php
  plugins/DevicesDetection/lang/en.json
  plugins/PrivacyManager/tests/Integration/Dao/LogDataAnonymizerTest.php
  plugins/PrivacyManager/tests/System/expected/anonymizeVisitInformation_allSitesAllDates.json
  plugins/PrivacyManager/tests/System/expected/anonymizeVisitInformation_anonymizeUserId.json
  plugins/PrivacyManager/tests/System/expected/anonymizeVisitInformation_restrictDate.json
  plugins/PrivacyManager/tests/System/expected/anonymizeVisitInformation_restrictSites.json
  plugins/PrivacyManager/tests/System/expected/exportDataSubject_allVisits.json
  plugins/PrivacyManager/tests/System/expected/exportDataSubject_oneVisitGiven.json
  plugins/PrivacyManager/tests/System/expected/test___PrivacyManager.getAvailableVisitColumnsToAnonymize.xml
  tests/PHPUnit/System/expected/test_ImportLogs__DevicesDetection.getBrowserVersions_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__DevicesDetection.getBrowsers_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Live.getLastVisitsDetails_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs__PrivacyManager.getAvailableVisitColumnsToAnonymize.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Resolution.getConfiguration_month.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits__PrivacyManager.getAvailableVisitColumnsToAnonymize.xml
  tests/PHPUnit/System/expected/test_noVisit_PeriodIsLast__PrivacyManager.getAvailableVisitColumnsToAnonymize.xml
  tests/PHPUnit/System/expected/test_noVisit__PrivacyManager.getAvailableVisitColumnsToAnonymize.xml
Labels: Needs Review

#16214 Fix download of scheduled reports
  plugins/ScheduledReports/templates/_listReports.twig
  tests/UI/expected-screenshots/UIIntegrationTest_email_reports_download.png
  tests/UI/specs/UIIntegration_spec.js
Labels: Needs Review, Regression, not-in-changelog

#16216 Delete remembered archived only for one specific site when a site is deleted
  core/Archive/ArchiveInvalidator.php
Labels: Needs Review

#16212 Fix language selector in mobile menu is not visible
  plugins/CoreHome/stylesheets/layout.less
Labels: Needs Review

#16221 Fix start/end time for given period it can skip this archive
  core/DataAccess/RawLogDao.php
  core/Period.php
  tests/PHPUnit/System/RawLogDaoTest.php
  tests/PHPUnit/Unit/PeriodTest.php
Labels: Needs Review, not-in-changelog

#16228 fix select for new materialize
  plugins/CoreVisualizations/angularjs/series-picker/series-picker.component.html
Labels: not-in-changelog

#16232 Fix escaping in site selection for anonymous user configuration
  plugins/UsersManager/Controller.php
Labels: Needs Review

#16227 Fix include path of PiwikTracker.php
  libs/PiwikTracker/PiwikTracker.php
Labels: Needs Review, not-in-changelog

#16226 Backport userId to overwrite visitorId feature
  config/global.ini.php
  core/Tracker/Request.php
  core/Tracker/Visit.php
  plugins/CoreHome/Tracker/VisitRequestProcessor.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: Needs Review, not-in-changelog

#16236 Fix focus color of select fields
  plugins/Morpheus/stylesheets/general/_forms.less
Labels: Regression, c: Design / UI, not-in-changelog

#16235 Avoid API error if invalid idSubtable is given
  plugins/Referrers/API.php
Labels: Needs Review

#16234 Adds missing rel attribute for external link
  plugins/Live/templates/getLastVisitsStart.twig
Labels: Needs Review, not-in-changelog

#16237 Set referrer policy on default img tracking code
  plugins/SitesManager/API.php
  plugins/SitesManager/tests/System/expected/test_SitesManager_after3_7_0__SitesManager.getImageTrackingCode.xml
  plugins/SitesManager/tests/System/expected/test_SitesManager_prior3_7_0__SitesManager.getImageTrackingCode.xml
  plugins/SitesManager/tests/System/expected/test_SitesManager_prior3_7_0_but_forced__SitesManager.getImageTrackingCode.xml
  tests/UI/expected-screenshots/UIIntegrationTest_admin_manage_tracking_code.png
Labels: Needs Review, not-in-changelog

#16241 sort custom dimensions alphabetically in menu
  plugins/CustomDimensions/CustomDimensions.php
Labels: Needs Review, not-in-changelog

#16217 Add new dimension profilable
  core/Updates/4.0.0-b1.php
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_profilable__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_profilable__VisitsSummary.get_range.xml
  plugins/CoreHome/Columns/Profilable.php
  plugins/CoreHome/lang/en.json
  plugins/CoreUpdater/tests/UI/expected-screenshots/CoreUpdaterDb_main.png
  plugins/CoreUpdater/tests/UI/expected-screenshots/CoreUpdaterDb_main_instance.png
  plugins/CustomDimensions/tests/System/expected/test___API.getSegmentsMetadata.xml
  plugins/PrivacyManager/tests/Integration/Dao/LogDataAnonymizerTest.php
  plugins/PrivacyManager/tests/System/expected/anonymizeVisitInformation_allSitesAllDates.json
  plugins/PrivacyManager/tests/System/expected/anonymizeVisitInformation_anonymizeUserId.json
  plugins/PrivacyManager/tests/System/expected/anonymizeVisitInformation_restrictDate.json
  plugins/PrivacyManager/tests/System/expected/anonymizeVisitInformation_restrictSites.json
  plugins/PrivacyManager/tests/System/expected/exportDataSubject_allVisits.json
  plugins/PrivacyManager/tests/System/expected/exportDataSubject_oneVisitGiven.json
  plugins/PrivacyManager/tests/System/expected/test___PrivacyManager.getAvailableVisitColumnsToAnonymize.xml
  tests/PHPUnit/System/expected/test_ImportLogs__PrivacyManager.getAvailableVisitColumnsToAnonymize.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits__PrivacyManager.getAvailableVisitColumnsToAnonymize.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getSegmentsMetadata.xml
  tests/PHPUnit/System/expected/test_noVisit_PeriodIsLast__PrivacyManager.getAvailableVisitColumnsToAnonymize.xml
  tests/PHPUnit/System/expected/test_noVisit__PrivacyManager.getAvailableVisitColumnsToAnonymize.xml
Labels: Needs Review, not-in-changelog

#16240 Improve visitor profile styles, so nothing collapses when zooming in/out
  plugins/Live/stylesheets/visitor_profile.less
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_profile.png
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_profile_action_details.png
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_profile_actions_hidden.png
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_profile_limited.png
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_profile_more_visits.png
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_profile_visit_details.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_visits_showprofile.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitor_profile_not_segmented.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitor_profile_popup.png
Labels: Needs Review, not-in-changelog

#16244 Remove update script for new profilable dimension
  core/Updates/4.0.0-b1.php
Labels: not-in-changelog

#16242 Use category display name for segment metadata
  plugins/API/SegmentMetadata.php
  plugins/CustomDimensions/tests/System/expected/test___API.getSegmentsMetadata.xml
  plugins/SegmentEditor/tests/UI/SegmentSelectorEditor_spec.js
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getSegmentsMetadata.xml
Labels: Needs Review

#16245 Use new tracker mehtod to set a custom dimension
  composer.lock
  plugins/CustomDimensions/angularjs/manage/edit.directive.html
  plugins/CustomDimensions/docs/faq.md
  plugins/CustomDimensions/tests/Fixtures/TrackVisitsWithCustomDimensionsFixture.php
  plugins/Live/tests/Fixtures/VisitsWithAllActionsAndDevices.php
  tests/LocalTracker.php
  tests/PHPUnit/Fixtures/ManySitesImportedLogsWithXssAttempts.php
  tests/PHPUnit/Fixtures/ManyVisitsWithMockLocationProvider.php
  tests/PHPUnit/System/TrackerResponseTest.php
Labels: Needs Review, not-in-changelog

#16251 Add additional test for fingerprint salt date string generator
  tests/PHPUnit/Integration/Tracker/FingerprintSaltTest.php
Labels: not-in-changelog

#16253 Remove no longer needed/used heartbeat code
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  plugins/Overlay/templates/startOverlaySession.twig
Labels: Needs Review, not-in-changelog

#16250 Truncate userId to prevent error data too long
  plugins/CoreHome/Columns/UserId.php
Labels: Needs Review, not-in-changelog
