Repository matomo-org/matomo, pull requests merged in 2020-11, with the labels that each got.

#16631 Update link to demo
  README.md
Labels: Needs Review, not-in-changelog

#16641 read from the task timetable option more often when executing tasks...
  core/Scheduler/Scheduler.php
  core/Scheduler/Timetable.php
Labels: Needs Review

#16649 Updates composer dependencies
  composer.lock
Labels: Needs Review, not-in-changelog

#16654 use original jshrink
  composer.json
  composer.lock
Labels: Task, not-in-changelog

#16652 reactivate some tests that were disabled till first release
  plugins/Marketplace/tests/System/Api/ClientTest.php
  tests/PHPUnit/Unit/DeprecatedMethodsTest.php
Labels: Needs Review, c: Tests & QA, not-in-changelog

#14444 simplified cookies
  CHANGELOG.md
  core/Cookie.php
  core/Tracker/IgnoreCookie.php
  plugins/ExampleSettingsPlugin/SystemSettings.php
  tests/PHPUnit/Unit/CookieTest.php
Labels: Needs Review

#16651 Updates node modules
  node_modules/angular-animate/angular-animate.js
  node_modules/angular-animate/angular-animate.min.js
  node_modules/angular-animate/bower.json
  node_modules/angular-animate/package.json
  node_modules/angular-cookies/angular-cookies.js
  node_modules/angular-cookies/angular-cookies.min.js
  node_modules/angular-cookies/bower.json
  node_modules/angular-cookies/package.json
  node_modules/angular-mocks/angular-mocks.js
  node_modules/angular-mocks/bower.json
  node_modules/angular-mocks/package.json
  node_modules/angular-sanitize/angular-sanitize.js
  node_modules/angular-sanitize/angular-sanitize.min.js
  node_modules/angular-sanitize/angular-sanitize.min.js.map
  node_modules/angular-sanitize/bower.json
  node_modules/angular-sanitize/package.json
  node_modules/angular/angular.js
  node_modules/angular/angular.min.js
  node_modules/angular/angular.min.js.map
  node_modules/angular/bower.json
  node_modules/angular/package.json
  package-lock.json
  package.json
Labels: Needs Review, not-in-changelog

#16653 don't install unneeded polyfills with composer
  composer.json
Labels: Task, not-in-changelog

#16645 Add PR template
  .github/pull_request_template.md
Labels: RFC

#16658 Fix build
  core/Cookie.php
  plugins/Login/tests/Integration/SessionInitializerTest.php
  tests/PHPUnit/Unit/CookieTest.php
Labels: Needs Review, not-in-changelog

#16665 make sure date2 is always defined in ArchiveInvalidator::reArchiveReport
  core/Archive/ArchiveInvalidator.php
  tests/PHPUnit/Integration/DataAccess/ArchiveInvalidatorTest.php
Labels: not-in-changelog

#16660 Add timezone version to php informational system check output
  plugins/Diagnostics/Diagnostic/PhpInformational.php
  plugins/Diagnostics/tests/UI/expected-screenshots/Diagnostics_page.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_updates_superuser.png
Labels: Needs Review

#16663 Fix plugin might not be loaded when installing the plugin
  core/AssetManager.php
  plugins/Diagnostics/tests/UI/expected-screenshots/Diagnostics_page.png
  tests/PHPUnit/Unit/AssetManager/PluginManagerMock.php
Labels: Needs Review, not-in-changelog

#16676 Fix UnprocessedSegment UI tests
  plugins/SegmentEditor/tests/UI/UnprocessedSegment_spec.js
Labels: c: Tests & QA, not-in-changelog

#16675 Fix siteSearchCategory segment
  plugins/Actions/API.php
  plugins/Actions/Columns/SearchCategory.php
  plugins/CustomDimensions/tests/System/expected/test___API.getSegmentsMetadata.xml
  tests/PHPUnit/System/expected/test_SiteSearch_Actions.getSiteSearchCategories_firstSite_lastN__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_SiteSearch_Actions.getSiteSearchCategories_firstSite_lastN__API.getProcessedReport_month.xml
  tests/PHPUnit/System/expected/test_SiteSearch_AllSites__Actions.getSiteSearchCategories_day.xml
  tests/PHPUnit/System/expected/test_SiteSearch_AllSites__Actions.getSiteSearchCategories_month.xml
  tests/PHPUnit/System/expected/test_SiteSearch_NotLastNPeriods__Actions.getSiteSearchCategories_day.xml
  tests/PHPUnit/System/expected/test_SiteSearch_NotLastNPeriods__Actions.getSiteSearchCategories_month.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getSegmentsMetadata.xml
Labels: Needs Review, not-in-changelog

#16668 Always set consent removed cookie even when cookies are disabled
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: Needs Review

#16686 Adds nonce to one click update form
  plugins/CoreUpdater/Controller.php
  plugins/CoreUpdater/templates/newVersionAvailable.twig
  plugins/CoreUpdater/templates/updateHttpsError.twig
Labels: Needs Review, not-in-changelog

#16687 Added whitespace to the bottom of email template
  plugins/CoreHome/templates/_htmlEmailHeader.twig
Labels: Needs Review

#16692 use Matomo in user agent
  core/Http.php
  tests/PHPUnit/Integration/HttpTest.php
Labels: Needs Review

#16691 update cacert.pem
  core/DataFiles/cacert.pem
Labels: Needs Review

#16690 Show invalidation information in system check
  plugins/Diagnostics/Diagnostic/ReportInformational.php
  plugins/Diagnostics/tests/UI/expected-screenshots/Diagnostics_page.png
Labels: Needs Review

#16696 Add hash equals method
  CHANGELOG.md
  core/Common.php
  tests/PHPUnit/Unit/CommonTest.php
Labels: Needs Review

#16699 Fix HTTP events tests
  tests/PHPUnit/Integration/HttpTest.php
Labels: not-in-changelog

#16697 Better anonymising of data
  core/Twig.php
Labels: Needs Review, not-in-changelog

#16701 Better detect failed archiving jobs.
  core/CronArchive.php
  core/DataAccess/Model.php
  core/Db/Schema/Mysql.php
  core/Updates/4.0.0-rc3.php
  core/Version.php
  tests/PHPUnit/Integration/DataAccess/ModelTest.php
Labels: Needs Review, not-in-changelog

#16705 Fix methods to get plugin de-/activation time.
  core/Plugin.php
Labels: Needs Review, not-in-changelog

#16702 Delayed rearchiving
  core/Archive/ArchiveInvalidator.php
  core/CronArchive.php
  core/CronArchive/ReArchiveList.php
  tests/PHPUnit/Integration/CronArchiveTest.php
  tests/PHPUnit/Integration/DataAccess/ArchiveInvalidatorTest.php
Labels: Needs Review, not-in-changelog

#16711 Fix removal of rearchiving records
  core/Archive/ArchiveInvalidator.php
Labels: Needs Review, not-in-changelog

#16710 Workaround shell_exec being disabled
  core/CliMulti/CliPhp.php
Labels: Needs Review, not-in-changelog

#16716 Fix ecommerce and goal tracking may not work
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  tests/javascript/index.php
Labels: not-in-changelog

#16718 Make it clear that tracking ISP data requires Provider plugin
  plugins/GeoIp2/LocationProvider/GeoIp2/Php.php
  plugins/GeoIp2/lang/en.json
  plugins/GeoIp2/templates/_updaterManage.twig
  plugins/UserCountry/stylesheets/userCountry.less
  plugins/UserCountry/tests/UI/UserCountry_spec.js
  plugins/UserCountry/tests/UI/expected-screenshots/UserCountry_admin_geoip2_no_provider.png
Labels: Needs Review

#16709 backport confirm password fix for loginldap on 3.x
  plugins/Login/Controller.php
  plugins/Login/PasswordVerifier.php
  plugins/Login/templates/confirmPassword.twig
Labels: Needs Review

#16717 typo in deleting blob archive data
  core/DataAccess/Model.php
  core/Updates/4.0.0-rc4.php
  core/Version.php
Labels: Needs Review, not-in-changelog

#16720 Make sure to disable example theme on matomo4 upgrade
  core/Updates/4.0.0-rc4.php
Labels: Needs Review, not-in-changelog

#16723 Updates iso region mapping
  plugins/GeoIp2/Commands/UpdateRegionCodes.php
  plugins/GeoIp2/data/isoRegionNames.php
Labels: Needs Review

#16721 require laster master commit of tedivm/JShrink to fix PHP8 issue
  composer.json
  composer.lock
Labels: Needs Review, not-in-changelog

#16725 When token is anonymous do not append force api session
  core/API/DocumentationGenerator.php
Labels: Needs Review, not-in-changelog

#16680 Update en.json
  lang/en.json
Labels: Needs Review

#16731 Improve newly added dimensions/metrics
  plugins/DevicePlugins/Columns/DevicePluginColumn.php
  plugins/UserCountry/Columns/Provider.php
  plugins/UserCountry/lang/en.json
Labels: Needs Review, not-in-changelog

#16730 Remove unneeded metric format in Goal overview
  plugins/Goals/Reports/Get.php
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard2.png
  tests/UI/expected-screenshots/UIIntegrationTest_goals_overview.png
Labels: Needs Review, not-in-changelog

#16713 DB-IP URL is automatically updated in the options
  plugins/GeoIp2/GeoIP2AutoUpdater.php
Labels: Needs Review

#16728 take into account broken archive invalidations when resetting failed jobs
  core/DataAccess/Model.php
Labels: Needs Review, not-in-changelog

#16733 SameSite cookie attribute can be configured for JS tracker
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  tests/javascript/index.php
Labels: not-in-changelog

#16727 Add convenience method for rescheduling archiving for a single plugin.
  core/Plugin.php
  tests/PHPUnit/Integration/PluginTest.php
Labels: Needs Review

#16734 Do not allow uninstalling custom variables and provider for a while
  core/Plugin/Manager.php
  tests/PHPUnit/Integration/ReleaseCheckListTest.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_plugins.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_plugins_no_internet.png
  tests/UI/expected-screenshots/UIIntegrationTest_fatal_error_safemode.png
Labels: Needs Review, not-in-changelog

#16736 Bump version to Matomo 4 RC5
  core/Version.php
Labels: not-in-changelog

#16735 Only assume important log encountered when log level is >= WARN
  plugins/Monolog/Handler/FailureLogMessageDetector.php
Labels: Needs Review, not-in-changelog

#16737 query tweaks for setting/unsetting ts_started in invalidation table
  core/DataAccess/Model.php
Labels: Needs Review, not-in-changelog

#16738 Detect when both auto archiving and browser archiving is enabled
  plugins/Diagnostics/Diagnostic/CronArchivingCheck.php
  plugins/Diagnostics/lang/en.json
Labels: Needs Review

#16739 add check for dangling invalidations
  core/CronArchive.php
  tests/PHPUnit/Unit/DeprecatedMethodsTest.php
Labels: Needs Review, not-in-changelog

#16748 When no deactivation date found, then rearchive as much as allowed
  core/Plugin.php
  tests/PHPUnit/Integration/PluginTest.php
Labels: Needs Review, not-in-changelog

#16744 Ignore plugin timings when matomo is not installed yet
  core/Plugin/Manager.php
Labels: Needs Review, not-in-changelog

#16746 Prevent some archiving notes being printed for each site
  core/CronArchive.php
  plugins/CoreAdminHome/Tasks.php
Labels: Needs Review, not-in-changelog

#16752 handle "all" in removeInvalidationsFromDistributedList
  core/Archive/ArchiveInvalidator.php
  tests/PHPUnit/Integration/DataAccess/ArchiveInvalidatorTest.php
Labels: Needs Review, not-in-changelog

#16753 fix removal of invalidations for segments
  core/DataAccess/Model.php
  tests/PHPUnit/Integration/DataAccess/ArchiveInvalidatorTest.php
Labels: Needs Review, not-in-changelog

#16759 allow remove invalidations by report name
  core/Archive/ArchiveInvalidator.php
  tests/PHPUnit/Integration/DataAccess/ArchiveInvalidatorTest.php
Labels: Needs Review, not-in-changelog

#16764 Use new version of matomo-php-tracker instead of 4.x-dev branch.
  composer.json
  composer.lock
Labels: not-in-changelog

#16768 Add disablePerformanceTracking method to methods to apply first
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  tests/javascript/index.php
Labels: not-in-changelog

#16770 Tweak developer changelog re token
  CHANGELOG.md
Labels: not-in-changelog

#16772 Remove existing invalidations before scheduling new ones
  core/Archive/ArchiveInvalidator.php
  core/Version.php
  tests/PHPUnit/Integration/DataAccess/ArchiveInvalidatorTest.php
Labels: Needs Review

#16774 Update PHP requirement in README
  README.md
Labels: Needs Review, not-in-changelog

#16781 Fix Installer UI tests
  tests/UI/expected-screenshots/OneClickUpdate_latest_version_available.png
  tests/UI/expected-screenshots/OneClickUpdate_update_fail.png
  tests/UI/expected-screenshots/OneClickUpdate_update_screen.png
  tests/UI/specs/OneClickUpdate_spec.js
  tests/resources/install-matomo.php
Labels: Needs Review, c: Tests & QA, not-in-changelog

#16779 Fix seo widget
  plugins/SEO/Metric/Alexa.php
  plugins/SEO/Widgets/GetRank.php
  plugins/SEO/config/ui-test.php
  plugins/SEO/tests/UI/SeoWidget_spec.js
  plugins/SEO/tests/UI/expected-ui-screenshots/SeoWidgetTest_widget.png
  plugins/SEO/tests/resources/alexa_response.html
  plugins/SEO/tests/resources/bing_response.html
  plugins/SEO/tests/resources/google_response.html
  plugins/SEO/tests/resources/whois_response.html
  plugins/SEO/tests/resources/whoiscom_response.html
Labels: Needs Review, not-in-changelog

#16800 Fix notice value might not be defined in alexa
  plugins/SEO/Metric/Alexa.php
Labels: not-in-changelog

#16799 Add pluginjson for custom dimensions + fix build
  plugins/CustomDimensions/plugin.json
  tests/PHPUnit/Integration/DataAccess/ArchiveInvalidatorTest.php
  tests/PHPUnit/Integration/ReleaseCheckListTest.php
  tests/PHPUnit/Integration/Tracker/RequestTest.php
Labels: Needs Review, not-in-changelog

#16807 Remove ExampleTheme plugin on update
  core/Updates/4.0.1-b1.php
  core/Version.php
Labels: Needs Review, not-in-changelog

#16796 Invalidate everything once before a site is archived and do not inval…
  core/CronArchive/QueueConsumer.php
  core/DataAccess/Model.php
  plugins/CoreConsole/tests/System/ArchiveCronTest.php
  tests/PHPUnit/Integration/CronArchiveTest.php
Labels: Needs Review, not-in-changelog

#16809 Fixes seo widget ui test
  plugins/SEO/tests/UI/SeoWidget_spec.js
Labels: c: Tests & QA, not-in-changelog

#16814 Update session ids on update
  core/Updates/4.0.0-b1.php
Labels: Needs Review, not-in-changelog

#16816 Fix hash algo is missing during upgrade
  core/Updates/4.0.0-b1.php
  core/Updates/4.0.1-b1.php
Labels: Needs Review, not-in-changelog

#16820 WP optimize is not a Matomo plugin
  core/Plugin/Manager.php
Labels: not-in-changelog

#16823 PHP8 compatibility improvements
  plugins/Installation/ServerFilesGenerator.php
Labels: Needs Review

#16822 Improve token auth migration
  core/Updater/Migration/Custom.php
  core/Updates/4.0.0-b1.php
  plugins/CoreAdminHome/Commands/MigrateTokenAuths.php
Labels: Needs Review

#16829 Ignore errors while updating session ids
  core/Updates/4.0.0-b1.php
Labels: Needs Review, not-in-changelog

#16826 Adjust archive_invalidations index
  core/Db/Schema/Mysql.php
Labels: Needs Review, not-in-changelog

#16835 Change referrer url size to 1500
  plugins/Referrers/Columns/ReferrerUrl.php
Labels: Needs Review

#16836 Trim referrer url if needed
  plugins/Referrers/Columns/ReferrerUrl.php
  plugins/Referrers/tests/Integration/Columns/ReferrerUrlTest.php
Labels: Needs Review, not-in-changelog

#16838 Improve php8 compatibility
  core/DataTable/Filter/AddColumnsProcessedMetricsGoal.php
  plugins/API/RowEvolution.php
  plugins/MobileMessaging/MobileMessaging.php
  plugins/ScheduledReports/ScheduledReports.php
Labels: not-in-changelog

#16777 re-add missing condition for --skip-segments-today
  core/Archive.php
  core/CronArchive.php
  core/CronArchive/ArchiveFilter.php
  plugins/CoreConsole/Commands/CoreArchiver.php
  tests/PHPUnit/Integration/CronArchive/ArchiveFilterTest.php
  tests/PHPUnit/Integration/CronArchive/QueueConsumerTest.php
  tests/PHPUnit/Integration/CronArchiveTest.php
Labels: Needs Review, not-in-changelog

#16839 Bump version to 4.0.3
  core/Version.php
Labels: not-in-changelog
