Repository matomo-org/matomo, pull requests merged in 2020-04, with the labels that each got.

#15765 Fix realtime widget
  plugins/Live/angularjs/live-widget-refresh/live-widget-refresh.directive.js
Labels: Needs Review, not-in-changelog

#15746 Fix inconsistent usage of segment idSites
  core/ArchiveProcessor/Loader.php
  core/ArchiveProcessor/PluginsArchiver.php
Labels: Needs Review

#15737 Fix tests for tracker plugins no longer worked
  plugins/CustomPiwikJs/TrackingCode/JsTestPluginTrackerFiles.php
Labels: Needs Review, not-in-changelog

#15769 Revert detect page view bucket
  plugins/Marketplace/Api/Client.php
Labels: Needs Review

#15775 Fix error in InvalidateReportData command on PHP 7.4
  plugins/CoreAdminHome/Commands/InvalidateReportData.php
Labels: Bug

#15773 Notifications with the same id might not be shown at all
  plugins/CoreHome/angularjs/notification/notification.directive.js
Labels: Bug, Needs Review

#15785 Make sure to always set JSON_PIWIK to native JSON when possible
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: Needs Review

#15783 Fix console command missing in diagnostics check
  plugins/Diagnostics/Diagnostic/CronArchivingLastRunCheck.php
Labels: Needs Review

#15744 Adds option to disable referrer spam blacklist
  config/global.ini.php
  core/Tracker/VisitExcluded.php
  plugins/CoreAdminHome/Tasks.php
Labels: Needs Review

#15784 Force POST for bulk requests, fix alwaysUseSendBeacon not respected for bulk requests
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  tests/javascript/index.php
Labels: Needs Review

#15795 Make sure upgrading from a 3.X or pre- version to 4.X via oneclickupdate works
  plugins/CoreUpdater/ReleaseChannel/LatestCurrentBeta.php
  plugins/CoreUpdater/ReleaseChannel/LatestCurrentStable.php
  plugins/UserCountry/VisitorGeolocator.php
Labels: Needs Review

#15798 Make sure to clean up tracking failures before sending email notification
  plugins/CoreAdminHome/Tasks.php
Labels: Needs Review

#15805 Fix comparing segments doesn't work with condition startsWith
  plugins/CoreHome/javascripts/broadcast.js
Labels: Bug, Needs Review

#15786 Faster segmented suggested values when browser archiving is disabled
  core/Columns/Dimension.php
  core/Plugin/Segment.php
  plugins/API/API.php
  plugins/API/SegmentMetadata.php
  plugins/API/tests/System/AutoSuggestAPITest.php
  plugins/Actions/Columns/ClickedUrl.php
  plugins/Actions/Columns/DownloadUrl.php
  plugins/Actions/Columns/EntryPageTitle.php
  plugins/Actions/Columns/EntryPageUrl.php
  plugins/Actions/Columns/ExitPageTitle.php
  plugins/Actions/Columns/ExitPageUrl.php
  plugins/Actions/Columns/PageTitle.php
  plugins/Actions/Columns/PageUrl.php
  plugins/Actions/DataTable/Filter/Actions.php
  plugins/Contents/Columns/ContentName.php
  plugins/Contents/Columns/ContentPiece.php
  plugins/Events/Columns/EventAction.php
  plugins/Events/Columns/EventCategory.php
  plugins/Events/Columns/EventName.php
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getPageTitles_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getPageTitles_range.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_Actions.getPageTitles_firstSite_lastN__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_Actions.getPageUrls_firstSite_lastN__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__Actions.getPageTitles_day.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__Actions.getPageTitles_month.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__Actions.getPageTitles_week.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__Actions.getPageTitles_year.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__Actions.getPageUrls_day.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__Actions.getPageUrls_week.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__Actions.getPageUrls_year.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idSiteOne___Actions.getPageTitles_day.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idSiteOne___Actions.getPageTitles_month.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idSiteOne___Actions.getPageTitles_week.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idSiteOne___Actions.getPageTitles_year.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idSiteOne___Actions.getPageUrls_day.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idSiteOne___Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idSiteOne___Actions.getPageUrls_week.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idSiteOne___Actions.getPageUrls_year.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata_pageTitleZeroString__Actions.getPageTitles_day.xml
Labels: Needs Review

#15809 Fix problem when comparing segments or opening popovers
  plugins/CoreHome/javascripts/broadcast.js
Labels: Bug

#15810 split some files containing multiple classes
  core/API/NoDefaultValue.php
  core/API/Proxy.php
  core/Access.php
  core/Auth.php
  core/AuthResult.php
  core/NoAccessException.php
  core/Updater.php
  core/UpdaterErrorException.php
Labels: not-in-changelog

#15811 Use matomo require in plugin.json files
  plugins/ExampleLogTables/plugin.json
  plugins/ExamplePlugin/plugin.json
  plugins/ExampleTheme/plugin.json
  plugins/ExampleUI/plugin.json
  plugins/TestRunner/plugin.json
  tests/resources/custompluginsdir/CustomDirPlugin/plugin.json
Labels: Needs Review, not-in-changelog

#15800 purge all old archives regardless of done value
  core/Archive/ArchivePurger.php
  core/DataAccess/Model.php
  tests/PHPUnit/Fixtures/RawArchiveDataWithTempAndInvalidated.php
  tests/PHPUnit/Integration/Archive/ArchivePurgerTest.php
Labels: Needs Review

#15808 Add more parameters to the computeNbUnique event
  CHANGELOG.md
  core/ArchiveProcessor.php
Labels: Needs Review

#15813 Fix fatal error when trying to install Matomo when PHP version is too low
  core/testMinimumPhpVersion.php
Labels: Needs Review

#15814 Make sure to set cookie name before loading any cookie
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: Needs Review

#15815 Add test to ensure there are no plugin updates for core plugins
  tests/PHPUnit/Integration/ReleaseCheckListTest.php
Labels: Needs Review

#15796 Assume plugins that do not define a upper bound for Matomo version re…
  core/Plugin/Dependency.php
  plugins/Marketplace/tests/Integration/PluginsTest.php
  tests/PHPUnit/Integration/DependencyTest.php
Labels: Needs Review, not-in-changelog

#15770 One click update in two parts so new code is loaded for second.
  plugins/CoreUpdater/Controller.php
  plugins/CoreUpdater/Updater.php
Labels: Needs Review

#15821 merge 3.x to 4.x
  CHANGELOG.md
  core/Archive/ArchivePurger.php
  core/Archive/DataTableFactory.php
  core/ArchiveProcessor.php
  core/Columns/Dimension.php
  core/DataAccess/Model.php
  core/Plugin/Segment.php
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  plugins/API/API.php
  plugins/API/SegmentMetadata.php
  plugins/API/tests/System/AutoSuggestAPITest.php
  plugins/Actions/Columns/ClickedUrl.php
  plugins/Actions/Columns/DownloadUrl.php
  plugins/Actions/Columns/EntryPageTitle.php
  plugins/Actions/Columns/EntryPageUrl.php
  plugins/Actions/Columns/ExitPageTitle.php
  plugins/Actions/Columns/ExitPageUrl.php
  plugins/Actions/Columns/PageTitle.php
  plugins/Actions/Columns/PageUrl.php
  plugins/Actions/DataTable/Filter/Actions.php
  plugins/Contents/Columns/ContentName.php
  plugins/Contents/Columns/ContentPiece.php
  plugins/CoreAdminHome/Tasks.php
  plugins/CoreUpdater/Controller.php
  plugins/CoreUpdater/Updater.php
  plugins/Events/Columns/EventAction.php
  plugins/Events/Columns/EventCategory.php
  plugins/Events/Columns/EventName.php
  tests/PHPUnit/Fixtures/RawArchiveDataWithTempAndInvalidated.php
  tests/PHPUnit/Integration/Archive/ArchivePurgerTest.php
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getPageTitles_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getPageTitles_range.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_Actions.getPageTitles_firstSite_lastN__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_Actions.getPageUrls_firstSite_lastN__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__Actions.getPageTitles_day.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__Actions.getPageTitles_month.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__Actions.getPageTitles_week.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__Actions.getPageTitles_year.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__Actions.getPageUrls_day.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__Actions.getPageUrls_week.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__Actions.getPageUrls_year.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idSiteOne___Actions.getPageTitles_day.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idSiteOne___Actions.getPageTitles_month.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idSiteOne___Actions.getPageTitles_week.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idSiteOne___Actions.getPageTitles_year.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idSiteOne___Actions.getPageUrls_day.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idSiteOne___Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idSiteOne___Actions.getPageUrls_week.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idSiteOne___Actions.getPageUrls_year.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata_pageTitleZeroString__Actions.getPageTitles_day.xml
  tests/javascript/index.php
Labels: not-in-changelog

#15824 Use archive for userId segment suggested values
  plugins/CoreHome/Columns/UserId.php
  plugins/ExampleLogTables/tests/System/expected/test_ExampleLogTables_admin__UserId.getUsers_month.xml
  plugins/ExampleLogTables/tests/System/expected/test_ExampleLogTables_all__UserId.getUsers_month.xml
  plugins/ExampleLogTables/tests/System/expected/test_ExampleLogTables_men__UserId.getUsers_month.xml
  plugins/ExampleLogTables/tests/System/expected/test_ExampleLogTables_women__UserId.getUsers_month.xml
  plugins/UserId/API.php
  plugins/UserId/tests/System/expected/test___UserId.getUsers_day.xml
  plugins/UserId/tests/System/expected/test___UserId.getUsers_range.xml
  plugins/UserId/tests/System/expected/test_ascSortOrder__UserId.getUsers_day.xml
  plugins/UserId/tests/System/expected/test_ascSortOrder__UserId.getUsers_range.xml
  plugins/UserId/tests/System/expected/test_limit__UserId.getUsers_day.xml
  plugins/UserId/tests/System/expected/test_limit__UserId.getUsers_range.xml
  plugins/UserId/tests/System/expected/test_searchByUserId__UserId.getUsers_day.xml
  plugins/UserId/tests/System/expected/test_searchByUserId__UserId.getUsers_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs__UserId.getUsers_month.xml
  tests/PHPUnit/System/expected/test_reportLimiting__UserId.getUsers_day.xml
  tests/PHPUnit/System/expected/test_reportLimiting_flattened__UserId.getUsers_day.xml
  tests/PHPUnit/System/expected/test_reportLimiting_rankingQuery__UserId.getUsers_day.xml
Labels: Needs Review, not-in-changelog

#15818 Prevent possible notice and hiding actual error in debug trace
  plugins/Monolog/Formatter/LineMessageFormatter.php
Labels: Needs Review

#15825 Mark plugins in marketplace test responses as compatible with Matomo 4
  plugins/Marketplace/tests/Integration/PluginsTest.php
  plugins/Marketplace/tests/resources/v2.0_plugins-purchase_type-paid-access_token-consumer1_paid2_custom1.json
  plugins/Marketplace/tests/resources/v2.0_plugins-purchase_type-paid-access_token-consumer2_paid1.json
  plugins/Marketplace/tests/resources/v2.0_plugins-purchase_type-paid-access_token-notexistingtoken.json
  plugins/Marketplace/tests/resources/v2.0_plugins-purchase_type-paid-num_users-201-access_token-consumer1_paid2_custom1.json
  plugins/Marketplace/tests/resources/v2.0_plugins-purchase_type-paid-num_users-201-access_token-consumer2_paid1.json
  plugins/Marketplace/tests/resources/v2.0_plugins.json
  plugins/Marketplace/tests/resources/v2.0_plugins_Barometer_info.json
  plugins/Marketplace/tests/resources/v2.0_plugins_PaidPlugin1_info-access_token-consumer3_paid1_custom2.json
  plugins/Marketplace/tests/resources/v2.0_plugins_PaidPlugin1_info-purchase_type-paid-num_users-201-access_token-consumer2_paid1.json
  plugins/Marketplace/tests/resources/v2.0_plugins_PaidPlugin1_info.json
  plugins/Marketplace/tests/resources/v2.0_plugins_TreemapVisualization_info.json
  plugins/Marketplace/tests/resources/v2.0_themes.json
Labels: c: Tests & QA, not-in-changelog

#15755 try to fix two UI tests
  plugins/CoreUpdater/Updater.php
  plugins/UsersManager/tests/UI/UserSettings_spec.js
  plugins/UsersManager/tests/UI/expected-screenshots/UserSettings_load_security.png
  tests/PHPUnit/Fixtures/UITestFixture.php
  tests/UI/expected-screenshots/OneClickUpdate_login.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_realtime_visits.png
  tests/UI/specs/OneClickUpdate_spec.js
  tests/UI/specs/UIIntegration_spec.js
Labels: Needs Review

#15832 Always purge today & yesterday and add update for 3.13.5
  core/Updates/3.13.5-rc1.php
  core/Version.php
  plugins/CoreAdminHome/Tasks.php
Labels: Needs Review, not-in-changelog

#15835 Fix typo in error message
  plugins/Widgetize/Controller.php
Labels: Needs Review, not-in-changelog

#15839 makes DBStats.getArchiveTableYear private
  plugins/DBStats/API.php
Labels: Needs Review, not-in-changelog

#15838 removes VisitsSummary.getColumns
  plugins/VisitFrequency/API.php
  plugins/VisitsSummary/API.php
Labels: Needs Review, not-in-changelog

#15840 moves Annotations.getDateRangeForPeriod to plugin class
  plugins/Annotations/API.php
  plugins/Annotations/Annotations.php
  plugins/Annotations/Controller.php
Labels: Needs Review, not-in-changelog

#15848 Reactivates some skipped tests
  plugins/Contents/tests/System/ContentsTest.php
  plugins/Ecommerce/tests/System/EcommerceOrderWithItemsTest.php
  tests/PHPUnit/Framework/TestCase/SystemTestCase.php
  tests/PHPUnit/Integration/ArchiveWebTest.php
  tests/PHPUnit/Integration/JsProxyTest.php
  tests/PHPUnit/Integration/Tracker/RequestTest.php
  tests/PHPUnit/System/TwoVisitorsTwoWebsitesDifferentDaysTest.php
  tests/PHPUnit/System/UrlNormalizationTest.php
Labels: Needs Review, c: Tests & QA, not-in-changelog

#15853 Make sure to increase time limit when archiving
  core/SettingsServer.php
Labels: Needs Review

#15846 Ensure Referrers.get does return an empty result if there aren't any archives
  plugins/Referrers/API.php
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits_csv__API.get_month.csv
  tests/PHPUnit/System/expected/test_noVisit_PeriodIsLast__Referrers.get_day.xml
  tests/PHPUnit/System/expected/test_noVisit_PeriodIsLast__Referrers.get_week.xml
Labels: Needs Review, not-in-changelog

#15863 Improve generated docs on extending visitor log & profile
  plugins/Live/VisitorDetailsAbstract.php
Labels: c: Documentation

#15844 Run UI tests of submodules with core build if possible
  tests/lib/screenshot-testing/support/app.js
Labels: Needs Review, not-in-changelog

#15866 Removes deprecated event Live.getAllVisitorDetails
  CHANGELOG.md
  plugins/ExampleTracker/ExampleTracker.php
  plugins/ExampleTracker/VisitorDetails.php
  plugins/Live/Visitor.php
Labels: Needs Review

#15867 Fix plugins/Live/Controller.php(99): Notice - Undefined variable: visitors
  plugins/Live/Controller.php
Labels: Needs Review

#15877 Ensure oneClickUpdatePartTwo always returns json
  plugins/CoreUpdater/Controller.php
  plugins/CoreUpdater/Updater.php
Labels: Needs Review, not-in-changelog

#15854 Keep last 100 characters of archive error message when error is too long
  core/CronArchive.php
Labels: Needs Review

#15872 Queue content tracking requests
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  tests/javascript/index.php
Labels: Needs Review

#15874 put rexpiring delay logic in Lock class
  core/Concurrency/Lock.php
  core/DataAccess/ArchivingDbAdapter.php
  tests/PHPUnit/Integration/Concurrency/LockTest.php
  tests/PHPUnit/Integration/DataAccess/LogAggregatorTest.php
Labels: Needs Review, not-in-changelog

#15882 Fix iso code of Brandenburg
  plugins/UserCountryMap/svg/DEU.svg
Labels: Needs Review, not-in-changelog

#15883 Updates device detector to 3.12.5
  composer.lock
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_browserEngine__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_browserName__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_deviceType__API.getSuggestedValuesForSegment.xml
  plugins/DevicesDetection/functions.php
  plugins/DevicesDetection/lang/en.json
  plugins/DevicesDetection/tests/System/expected/test___DevicesDetection.getType_day.xml
  tests/PHPUnit/System/expected/test_ImportLogs__DevicesDetection.getType_month.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits__DevicesDetection.getType_day.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits_withCookieSupport__DevicesDetection.getType_day.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getSegmentsMetadata.xml
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard2.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_devices.png
Labels: Task

#15879 Minor performance improvement when invalidating archives
  core/DataAccess/Model.php
Labels: Needs Review
