Repository matomo-org/matomo, pull requests merged in 2020-08, with the labels that each got.

#16264 Require only view access for embedded widgets when using tokens
  CHANGELOG.md
  plugins/Widgetize/Controller.php
  plugins/Widgetize/lang/en.json
Labels: Needs Review

#16282 Fix default value of heart beat timer
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: Needs Review

#16281 Make sure confirmPassword uses the currently active login plugin, not always "Login".
  plugins/Login/Controller.php
  plugins/Login/templates/confirmPassword.twig
Labels: Needs Review

#16263 Only allow widgetize and token usage for view users
  core/API/Request.php
  core/FrontController.php
  core/Session/SessionAuth.php
  plugins/Dashboard/tests/UI/Dashboard_spec.js
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_removed.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_loaded_token_auth.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_removed.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_reset.png
  plugins/Widgetize/Controller.php
  tests/PHPUnit/Fixtures/UITestFixture.php
  tests/PHPUnit/Framework/Fixture.php
  tests/PHPUnit/Integration/FrontControllerTest.php
  tests/PHPUnit/System/CookieTest.php
  tests/UI/expected-screenshots/BarGraph_load_fail_when_token_used.png
  tests/UI/expected-screenshots/EmptySite_emptySiteDashboard_ignored.png
  tests/UI/expected-screenshots/Theme_home.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_home.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_home_admintoken_not_allowed.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_themes.png
  tests/UI/expected-screenshots/UIIntegrationTest_api_error.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard1.png
  tests/UI/specs/BarGraph_spec.js
  tests/UI/specs/Comparison_spec.js
  tests/UI/specs/UIIntegration_spec.js
Labels: Needs Review

#16292 avoid triggering automated (vacation) responses
  core/Mail/Transport.php
Labels: Needs Review

#16296 fix used translation keys
  plugins/PagePerformance/Columns/TimeDomCompletion.php
  plugins/PagePerformance/Columns/TimeDomProcessing.php
  plugins/PagePerformance/Columns/TimeNetwork.php
  plugins/PagePerformance/Columns/TimeOnLoad.php
  plugins/PagePerformance/Columns/TimeServer.php
  plugins/PagePerformance/Columns/TimeTransfer.php
Labels: not-in-changelog

#16284 Reorganise Matomo 4 updates for better performance
  core/Updater/Migration/Db/DropColumns.php
  core/Updater/Migration/Db/Factory.php
  core/Updater/Migration/Db/Sql.php
  core/Updates/4.0.0-b1.php
  plugins/CoreUpdater/Commands/Update.php
  tests/PHPUnit/Integration/Updater/Migration/Db/DropColumnsTest.php
  tests/PHPUnit/Integration/Updater/Migration/Db/MigrationsTest.php
  tests/PHPUnit/Integration/Updater/Migration/Db/SqlTest.php
Labels: Needs Review, not-in-changelog

#16303 Updates device detector to 3.13.0
  composer.lock
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_browserName__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_operatingSystemName__API.getSuggestedValuesForSegment.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getSegmentsMetadata.xml
Labels: Task, not-in-changelog

#16304 Use renamed composer package matomo/referrer-spam-list
  composer.json
  composer.lock
  core/Tracker/Visit/ReferrerSpamFilter.php
Labels: Task, not-in-changelog

#16312 remove optional parameter before required one
  plugins/Actions/ArchivingHelper.php
Labels: Needs Review, not-in-changelog

#16310 Fix possible notice when generating a sparkline
  plugins/CoreVisualizations/Visualizations/Sparkline.php
Labels: Needs Review, not-in-changelog

#16290 Fix error when primary key is required
  core/DataAccess/LogAggregator.php
  core/Updater/Migration/Db.php
  tests/PHPUnit/Integration/DataAccess/LogAggregatorTest.php
Labels: Needs Review, not-in-changelog

#16308 Adds missing rel attribute to external links
  plugins/Live/templates/_profileSummaryVisits.twig
Labels: Needs Review, not-in-changelog

#16309 Fix API example links
  core/API/DocumentationGenerator.php
Labels: Needs Review, Regression, not-in-changelog

#16295 Number formatting may be wrong when eg German language is used
  core/Plugin/ArchivedMetric.php
  core/Plugin/Report.php
Labels: Needs Review

#16313 don't log silenced errors in php8
  core/ErrorHandler.php
Labels: Needs Review

#16302 Add feature to exclude tracking requests via config file
  config/global.ini.php
  core/Tracker/Request.php
  core/Tracker/VisitExcluded.php
  tests/PHPUnit/Integration/Tracker/RequestTest.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: Needs Review

#16298 Fix UI tests using embedded widgets
  plugins/Overlay/tests/UI/Overlay_spec.js
  plugins/TwoFactorAuth/tests/Fixtures/TwoFactorFixture.php
  plugins/TwoFactorAuth/tests/UI/TwoFactorAuth_spec.js
  tests/PHPUnit/Fixtures/UITestFixture.php
  tests/UI/expected-screenshots/enable_framed_pages_embed_whole_app.png
  tests/UI/specs/UIIntegration_spec.js
Labels: Needs Review, c: Tests & QA, not-in-changelog

#16315 Add plugin.json files for some internal plugins
  plugins/CustomVariables/plugin.json
  plugins/Provider/plugin.json
Labels: Needs Review, not-in-changelog

#11115 Reporting API: showColumns and hideColumns are now applied recursively
  CHANGELOG.md
  core/API/DataTablePostProcessor.php
  core/API/DocumentationGenerator.php
  core/DataTable/Filter/ColumnDelete.php
  plugins/Live/tests/System/ApiTest.php
  plugins/Live/tests/System/expected/test_hideColumnsNonRecursive__Live.getLastVisitsDetails_day.xml
  plugins/Live/tests/System/expected/test_hideColumns__Live.getLastVisitsDetails_day.xml
  tests/PHPUnit/Unit/DataTable/Filter/ColumnDeleteTest.php
Labels: Enhancement, Needs Review

#16319 Add plugin.json files where needed
  plugins/CustomVariables/plugin.json
  plugins/Provider/plugin.json
Labels: not-in-changelog

#16301 url decode value in requestcommand
  core/CliMulti/RequestCommand.php
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment0_noOptions__Live.getLastVisitsDetails_day.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment0_noOptions__Live.getLastVisitsDetails_year.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment0_noOptions__VisitFrequency.get_day.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment0_noOptions__VisitFrequency.get_year.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment0_noOptions__VisitsSummary.get_day.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment0_noOptions__VisitsSummary.get_year.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment1_noOptions__Live.getLastVisitsDetails_day.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment1_noOptions__Live.getLastVisitsDetails_year.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment1_noOptions__VisitFrequency.get_day.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment1_noOptions__VisitFrequency.get_year.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment1_noOptions__VisitsSummary.get_day.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment1_noOptions__VisitsSummary.get_year.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_segmentPreArchivedWithUrlEncoding_noOptions__VisitsSummary.get_day.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_segmentPreArchivedWithUrlEncoding_noOptions__VisitsSummary.get_month.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_segmentPreArchivedWithUrlEncoding_noOptions__VisitsSummary.get_week.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_segmentPreArchivedWithUrlEncoding_noOptions__VisitsSummary.get_year.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_segmentPreArchived_noOptions__VisitsSummary.get_day.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_segmentPreArchived_noOptions__VisitsSummary.get_month.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_segmentPreArchived_noOptions__VisitsSummary.get_week.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_segmentPreArchived_noOptions__VisitsSummary.get_year.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_singleMetric__ExamplePlugin.getExampleArchivedMetric_day.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_singleMetric__ExamplePlugin.getExampleArchivedMetric_week.xml
  tests/PHPUnit/Fixtures/ManySitesImportedLogs.php
Labels: Needs Review

#16328 Fix background color for active and focused tab
  plugins/Morpheus/stylesheets/ui/_tabs.less
Labels: Regression, not-in-changelog

#16325 Fix formatting of metrics in milliseconds
  core/Columns/Dimension.php
Labels: Needs Review, not-in-changelog

#16326 add convenience method for handling partial archiving in Archiver.php
  core/Plugin/Archiver.php
  plugins/ExamplePlugin/Archiver.php
Labels: Needs Review, not-in-changelog

#16314 Tests no memory limit
  tests/PHPUnit/System/ConsoleTest.php
Labels: Needs Review, c: Tests & QA

#16287 By default select site creation date if site was created today or if select date is before site creation date
  core/Plugin/Menu.php
  tests/PHPUnit/Integration/MenuTest.php
Labels: Needs Review, not-in-changelog

#16337 Add Template.confirmPasswordContent event
  plugins/Login/templates/confirmPassword.twig
Labels: Needs Review

#16340 Adjustments for CustomReports plugin
  core/Columns/Dimension.php
  core/Plugin/ArchivedMetric.php
  plugins/PagePerformance/Columns/TimeDomCompletion.php
  plugins/PagePerformance/Columns/TimeDomProcessing.php
  plugins/PagePerformance/Columns/TimeNetwork.php
  plugins/PagePerformance/Columns/TimeOnLoad.php
  plugins/PagePerformance/Columns/TimeServer.php
  plugins/PagePerformance/Columns/TimeTransfer.php
Labels: Needs Review, not-in-changelog

#16343 Adjust example tracker to the breaking changes in Matomo 4
  plugins/ExampleTracker/tracker.js
Labels: Needs Review, not-in-changelog

#16341 Use relative URLs for svgBasePath so proxy url doesn't need to be configured to make real time map work
  plugins/UserCountryMap/Controller.php
Labels: Needs Review

#16346 Tweaks for archiving for enterprise demo.
  core/CronArchive.php
  core/DataAccess/Model.php
Labels: not-in-changelog

#16322 Fix plugins might not be updated when updating core
  core/FrontController.php
  plugins/CoreUpdater/Controller.php
  plugins/CoreUpdater/Updater.php
  plugins/CoreUpdater/lang/en.json
  plugins/CoreUpdater/templates/updateSuccess.twig
  tests/UI/expected-screenshots/OneClickUpdate_update_success.png
Labels: Needs Review

#16344 Disable some core updater actions if auto update is not enabled
  plugins/CoreUpdater/Controller.php
Labels: Needs Review

#15508 Fix: Archiving with console on SELinux
  core/CliMulti/Process.php
Labels: Needs Review

#16345 Allow execution of core and plugin specific JS tests only
  tests/javascript/README.md
  tests/javascript/index.php
Labels: Needs Review, not-in-changelog

#16276 Fix encoding of dashboard name when copying a dashboard
  plugins/Dashboard/javascripts/dashboard.js
  plugins/Dashboard/tests/UI/Dashboard_spec.js
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_copied.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_reset.png
Labels: Needs Review, not-in-changelog

#16247 Recalculate visit numbers dynamically in visitor profile when more visits are loaded
  plugins/Live/javascripts/visitorProfile.js
  plugins/Live/templates/getVisitList.twig
Labels: Needs Review

#16357 Make number fields look the same as text fields
  plugins/CorePluginsAdmin/angularjs/form-field/field-number.html
Labels: Needs Review, Regression, not-in-changelog

#12114 Prevent possible infinite loop when page is unloading
  js/piwik.js
Labels: Needs Review, Pull Request WIP

#16360 Fix build as minified JS version is missing
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: not-in-changelog
