Repository matomo-org/matomo, pull requests merged in 2020-12, with the labels that each got.

#16837 More rigorous checks for non-existant site so archiving wont fail if …
  core/Archive/ArchivePurger.php
  core/CronArchive.php
  core/CronArchive/QueueConsumer.php
  tests/PHPUnit/Integration/CronArchive/QueueConsumerTest.php
Labels: Needs Review

#16844 only select invalidations that were added before a sites archiving began
  core/CronArchive/QueueConsumer.php
  core/DataAccess/Model.php
  tests/PHPUnit/Integration/CronArchive/QueueConsumerTest.php
  tests/PHPUnit/Integration/DataAccess/ModelTest.php
Labels: Needs Review

#16858 Remove no longer shipped example plugins during update
  core/Updates/4.0.4-b1.php
  core/Version.php
Labels: Needs Review, not-in-changelog

#16860 Document setGenerationTime removal and add back the method
  CHANGELOG.md
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  tests/javascript/index.php
Labels: Needs Review, not-in-changelog

#16851 Fix ttl not being respected on existing invalidations
  core/CronArchive/QueueConsumer.php
  tests/PHPUnit/Integration/CronArchive/QueueConsumerTest.php
  tests/PHPUnit/Integration/CronArchiveTest.php
Labels: Needs Review

#16871 Use existing Request method w/ correct logic for limiting widgetize access.
  plugins/Widgetize/Controller.php
Labels: Needs Review, not-in-changelog

#16872 Set default ArchiveFilter instance.
  core/CronArchive.php
Labels: Needs Review, not-in-changelog

#16870 When forcing GET request method in JS tracker then disable send beacon
  CHANGELOG.md
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  tests/javascript/index.php
Labels: Needs Review, not-in-changelog

#16875 Do not force api session usage for widgetized views
  plugins/CoreHome/angularjs/common/services/piwik-api.js
  plugins/CoreHome/javascripts/broadcast.js
  plugins/Morpheus/javascripts/ajaxHelper.js
  plugins/UserCountryMap/javascripts/realtime-map.js
  plugins/UserCountryMap/javascripts/visitor-map.js
Labels: Needs Review, not-in-changelog

#16845 segment invalidations must be paired w/ normal invalidations
  core/CronArchive.php
  core/CronArchive/SegmentArchiving.php
  plugins/CoreConsole/tests/System/ArchiveCronTest.php
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_segmentForToday_noOptions__VisitsSummary.get_day.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_segmentForToday_noOptions__VisitsSummary.get_month.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_segmentForToday_noOptions__VisitsSummary.get_week.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_segmentForToday_noOptions__VisitsSummary.get_year.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_singleMetric__ExamplePlugin.getExampleArchivedMetric_day.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_singleMetric__ExamplePlugin.getExampleArchivedMetric_week.xml
  tests/PHPUnit/Integration/CronArchiveTest.php
Labels: Needs Review, not-in-changelog

#16881 Set version to 4.0.4-b1
  core/Version.php
Labels: not-in-changelog

#16882 Set version to 4.0.4
  core/Version.php
Labels: not-in-changelog

#16893 Fix ArgumentCountError: mysqli_stmt::bind_param() does not accept unknown named parameters
  core/Db/BatchInsert.php
Labels: Needs Review, not-in-changelog

#16895 Remove invalidations for segments that are not pre-processed if found.
  core/CronArchive/QueueConsumer.php
  tests/PHPUnit/Integration/CronArchive/QueueConsumerTest.php
Labels: Needs Review

#16902 Fixes a couple of test class names
  tests/PHPUnit/Unit/DataTable/Filter/AddSummaryRowTest.php
  tests/PHPUnit/Unit/DataTable/Filter/ExcludeLowPopulationTest.php
  tests/PHPUnit/Unit/DataTable/Filter/LimitTest.php
  tests/PHPUnit/Unit/DataTable/Filter/PatternRecursiveTest.php
  tests/PHPUnit/Unit/DataTable/Filter/RangeCheckTest.php
  tests/PHPUnit/Unit/DataTable/Filter/TruncateTest.php
  tests/PHPUnit/Unit/DataTable/MapTest.php
  tests/PHPUnit/Unit/DataTable/Renderer/CSVTest.php
  tests/PHPUnit/Unit/DataTable/Renderer/ConsoleTest.php
  tests/PHPUnit/Unit/DataTable/Renderer/JSONTest.php
  tests/PHPUnit/Unit/DataTable/Renderer/XMLTest.php
Labels: c: Tests & QA, not-in-changelog

#16899 Host detection: use HTTP_HOST as default, but provide a setting to use SERVER_NAME instead
  CHANGELOG.md
  config/global.ini.php
  core/Plugin/Controller.php
  core/Url.php
  plugins/ScheduledReports/config/tcpdf_config.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: Needs Review

#16903 Assume something is widgetized whenever a token_auth is set in url
  plugins/CoreHome/javascripts/broadcast.js
Labels: Needs Review, not-in-changelog

#16896 Only invalidate in past for segments that belong to the site …
  core/CronArchive/SegmentArchiving.php
  tests/PHPUnit/Integration/CronArchive/QueueConsumerTest.php
  tests/PHPUnit/Integration/CronArchive/SegmentArchivingTest.php
Labels: Needs Review, not-in-changelog

#16886 If archive_invalidations is in inconsistent state, fix as getting next archive to process.
  core/CronArchive.php
  core/CronArchive/QueueConsumer.php
  core/DataAccess/Model.php
  tests/PHPUnit/Integration/CronArchive/QueueConsumerTest.php
  tests/PHPUnit/Integration/CronArchiveTest.php
  tests/PHPUnit/Integration/DataAccess/ModelTest.php
Labels: Needs Review, not-in-changelog

#16843 Avoid inserting duplicates in invalidation table to reduce IO.
  core/DataAccess/Model.php
  core/Db/BatchInsert.php
  tests/PHPUnit/Integration/CronArchiveTest.php
  tests/PHPUnit/Integration/DataAccess/ArchiveInvalidatorTest.php
Labels: Needs Review

#16913 More efficient page performance request processor
  plugins/PagePerformance/Tracker/PerformanceDataProcessor.php
Labels: Needs Review, not-in-changelog

#16911 Harden check for db-ip urls
  plugins/GeoIp2/GeoIP2AutoUpdater.php
Labels: Needs Review, not-in-changelog

#16926 Rewrite Annotations tests to run correctly
  plugins/Annotations/tests/System/AnnotationsTest.php
Labels: Needs Review, c: Tests & QA, not-in-changelog

#16923 Improvements on prepending a plus sign to evolutions
  core/DataTable/Filter/CalculateEvolutionFilter.php
  plugins/API/Filter/DataComparisonFilter.php
  plugins/API/RowEvolution.php
  tests/PHPUnit/System/expected/test_RowEvolution_LabelReservedCharactersHierarchical__API.getRowEvolution_day.xml
  tests/PHPUnit/System/expected/test_RowEvolution_goals_visitsUntilConversion_WithoutLabels__API.getRowEvolution_day.xml
  tests/PHPUnit/System/expected/test_RowEvolution_goals_visitsUntilConversion__API.getRowEvolution_day.xml
  tests/PHPUnit/System/expected/test_RowEvolution_multiWithFilterLimit__API.getRowEvolution_day.xml
  tests/PHPUnit/System/expected/test_RowEvolution_pageTitlesMulti__API.getRowEvolution_week.xml
  tests/PHPUnit/System/expected/test_RowEvolution_pageTitles__API.getRowEvolution_week.xml
Labels: Needs Review, c: i18n

#16921 Use correct method to check row count
  plugins/Referrers/API.php
Labels: Needs Review, not-in-changelog

#16908 Harden check for numeric array indices
  core/DataTable.php
  tests/PHPUnit/Unit/DataTable/Renderer/CSVTest.php
  tests/PHPUnit/Unit/DataTable/Renderer/ConsoleTest.php
Labels: Needs Review

#16901 better Windows detection
  core/SettingsServer.php
Labels: Needs Review

#16890 New version available plugins will be updated confusing
  plugins/CoreUpdater/templates/newVersionAvailable.twig
Labels: Needs Review, not-in-changelog

#16883 Load correct url for multisites when clicked in site selector
  plugins/CoreHome/angularjs/siteselector/siteselector-model.service.js
Labels: Needs Review, not-in-changelog

#16846 Fix error message when fopen fails in Http class
  core/ErrorHandler.php
  core/Http.php
Labels: Needs Review, not-in-changelog

#16830 Allow using last (week|month|year) as date param
  core/Date.php
  core/Period/Factory.php
  core/Period/Range.php
  plugins/CoreHome/angularjs/common/services/periods.js
  tests/PHPUnit/Fixtures/VisitsInCurrentYear.php
  tests/PHPUnit/Framework/TestRequest/Collection.php
  tests/PHPUnit/System/SpecialDateParamsTest.php
  tests/PHPUnit/System/expected/test_specialDateParams_lastmonth__Actions.getPageTitles_day.xml
  tests/PHPUnit/System/expected/test_specialDateParams_lastmonth__VisitsSummary.getVisits_day.xml
  tests/PHPUnit/System/expected/test_specialDateParams_lastweek__Actions.getPageTitles_day.xml
  tests/PHPUnit/System/expected/test_specialDateParams_lastweek__VisitsSummary.getVisits_day.xml
  tests/PHPUnit/System/expected/test_specialDateParams_lastyear__Actions.getPageTitles_day.xml
  tests/PHPUnit/System/expected/test_specialDateParams_lastyear__VisitsSummary.getVisits_day.xml
  tests/PHPUnit/System/expected/test_specialDateParams_range__Actions.getPageTitles_range.xml
  tests/PHPUnit/System/expected/test_specialDateParams_range__VisitsSummary.getVisits_range.xml
  tests/PHPUnit/Unit/DateTest.php
Labels: Needs Review, not-in-changelog

#16813 Use wikimedia/less.php instead of leafo/lessphp
  composer.json
  composer.lock
  core/AssetManager/UIAssetMerger/StylesheetUIAssetMerger.php
  core/Plugin/ThemeStyles.php
  tests/PHPUnit/Unit/AssetManager/stylesheets/ExpectedMergeResult.css
  tests/UI/expected-screenshots/UIIntegrationTest_customdirplugin.png
Labels: Needs Review

#16808 Avoid warning while loading seo metrics
  plugins/SEO/Metric/Alexa.php
  plugins/SEO/Metric/Bing.php
  plugins/SEO/Metric/DomainAge.php
  plugins/SEO/Metric/Google.php
Labels: Needs Review

#16785 Add GTM install guide to "no data tracked yet" page
  plugins/SitesManager/templates/_trackingCodeEmail.twig
  plugins/SitesManager/templates/siteWithoutData.twig
  tests/UI/expected-screenshots/EmptySite_emptySiteDashboard.png
  tests/UI/expected-screenshots/OneClickUpdate_login.png
Labels: Needs Review

#16930 Make isChromeDataSaverUsed method public
  core/Tracker/VisitExcluded.php
Labels: not-in-changelog

#16704 Append a suffix to temporary downloaded geoip files
  plugins/GeoIp2/Controller.php
  plugins/GeoIp2/GeoIP2AutoUpdater.php
Labels: Needs Review

#16685 Fix overflow handling of datatables
  plugins/CoreHome/javascripts/dataTable.js
Labels: Needs Review, c: Design / UI

#16910 Adds possibility to configure protocols for allowed outgoing connections
  config/global.ini.php
  core/Http.php
  tests/PHPUnit/Integration/HttpTest.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: Needs Review, c: Security

#16841 Fix unknown keyword is not shown in transitions report in seach engines section
  plugins/Transitions/API.php
  plugins/Transitions/tests/System/expected/test_Transitions__Transitions.getTransitionsForPageUrl_day.xml
  plugins/Transitions/tests/System/expected/test_Transitions__Transitions.getTransitionsForPageUrl_month.xml
  plugins/Transitions/tests/System/expected/test_Transitions_noLimit__Transitions.getTransitionsForPageTitle_day.xml
  plugins/Transitions/tests/System/expected/test_Transitions_noLimit__Transitions.getTransitionsForPageTitle_month.xml
  plugins/Transitions/tests/System/expected/test_Transitions_noLimit__Transitions.getTransitionsForPageUrl_day.xml
  plugins/Transitions/tests/System/expected/test_Transitions_noLimit__Transitions.getTransitionsForPageUrl_month.xml
  plugins/Transitions/tests/System/expected/test_Transitions_withSegment__Transitions.getTransitionsForPageTitle_day.xml
  plugins/Transitions/tests/System/expected/test_Transitions_withSegment__Transitions.getTransitionsForPageUrl_day.xml
  tests/PHPUnit/Fixtures/SomeVisitsManyPageviewsWithTransitions.php
Labels: Needs Review

#16936 Better check for getmypid to potentially avoid warnings
  core/CliMulti/Process.php
Labels: Needs Review, not-in-changelog

#16943 Prevent memory error when using PHP8 and a session error happens
  libs/Zend/Session/Exception.php
Labels: Needs Review

#16782 Adds missing field for Campaign ID to campaign builder
  plugins/Referrers/Referrers.php
  plugins/Referrers/angularjs/campaign-builder/campaign-builder.controller.js
  plugins/Referrers/angularjs/campaign-builder/campaign-builder.directive.html
  plugins/Referrers/lang/en.json
Labels: Needs Review, not-in-changelog

#16932 fix some tests exception handling
  plugins/SegmentEditor/tests/Integration/SegmentEditorTest.php
  tests/PHPUnit/System/VisitsInPastInvalidateOldReportsTest.php
Labels: Needs Review, c: Tests & QA, not-in-changelog

#16765 add note message when continuing an existing queue
  core/CronArchive.php
  core/CronArchive/FixedSiteIds.php
  core/CronArchive/SharedSiteIds.php
Labels: Needs Review

#16769 Better detection for end of sharedSiteId queue
  core/CronArchive/SharedSiteIds.php
  tests/PHPUnit/Integration/CronArchive/SharedSiteIdsTest.php
Labels: Needs Review

#16780 Improves Geolocation diagnostics
  plugins/GeoIp2/LocationProvider/GeoIp2.php
  plugins/GeoIp2/LocationProvider/GeoIp2/ServerModule.php
  plugins/UserCountry/Controller.php
  plugins/UserCountry/Diagnostic/GeolocationDiagnostic.php
  plugins/UserCountry/LocationProvider.php
  plugins/UserCountry/LocationProvider/DefaultProvider.php
  plugins/UserCountry/lang/en.json
Labels: Needs Review, not-in-changelog

#16941 Improve handling of current user information for Filechecks
  core/Filechecks.php
Labels: Needs Review

#16783 Improve scrolling of dialogs
  plugins/CoreHome/javascripts/popover.js
  plugins/Overlay/tests/UI/expected-screenshots/Overlay_row_evolution.png
  plugins/Overlay/tests/UI/expected-screenshots/Overlay_transitions.png
  plugins/PagePerformance/tests/UI/expected-screenshots/PagePerformance_pagetitle_overlay.png
  plugins/PagePerformance/tests/UI/expected-screenshots/PagePerformance_pageurl_overlay.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_visits_showprofile.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitor_profile_not_segmented.png
  tests/UI/expected-screenshots/ViewDataTableTest_export_options.png
Labels: Needs Review, not-in-changelog

#16952 Only mark process as finished after fully sending the output
  core/CliMulti/RequestCommand.php
Labels: Needs Review

#16954 Avoid filesystem checks when process was set as finished
  core/CliMulti/Process.php
Labels: Needs Review

#16951 If one process' output is "abnormal", don't declare all other concurrently running processes as finished
  core/CliMulti.php
Labels: Needs Review

#16950 Remember if process ever started
  core/CliMulti/Process.php
  tests/PHPUnit/Integration/CliMulti/ProcessTest.php
Labels: Needs Review

#16760 multi_server_environment setting now disallows config edits from Web UI
  config/global.ini.php
  plugins/CoreAdminHome/Controller.php
  plugins/CoreAdminHome/templates/generalSettings.twig
  plugins/CoreUpdater/SystemSettings.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: Needs Review

#16957 Do not use Date class in Loader::getMinVisitTimesPerSite() to avoid using Dates w/ strange visit data.
  core/ArchiveProcessor/Loader.php
Labels: Needs Review, not-in-changelog

#16960 Fix ArchiveInvalidatorTests for PHP 8
  tests/PHPUnit/Integration/DataAccess/ArchiveInvalidatorTest.php
Labels: Needs Review, c: Tests & QA, not-in-changelog

#16958 Removes duplicate code
  core/Tracker/Visit.php
Labels: Needs Review, not-in-changelog

#16925 do not update token usage in tracking requests
  plugins/UsersManager/Model.php
  plugins/UsersManager/tests/Integration/ModelTest.php
Labels: Needs Review, not-in-changelog

#16797 use composer/ca-bundle for default CA bundle
  composer.json
  composer.lock
  core/DataFiles/cacert.pem
  core/Http.php
Labels: Needs Review, Task

#16946 Fix intersecting period logic so proper archives will archive in parallel.
  core/CronArchive/QueueConsumer.php
  tests/PHPUnit/Integration/CronArchiveTest.php
  tests/PHPUnit/Unit/CronArchive/QueueConsumerTest.php
Labels: Needs Review, Regression

#16947 Apparently the segment needs to be double encoded when sent in the climulti:request command.
  core/CronArchive.php
  plugins/CoreConsole/tests/System/ArchiveCronTest.php
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_segmentWithEncoding_noOptions__VisitsSummary.get_day.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_segmentWithEncoding_noOptions__VisitsSummary.get_month.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_segmentWithEncoding_noOptions__VisitsSummary.get_week.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_segmentWithEncoding_noOptions__VisitsSummary.get_year.xml
  tests/PHPUnit/Integration/CronArchiveTest.php
Labels: Needs Review, Regression

#16970 Use correct tracker filename in privacy settings
  plugins/PrivacyManager/Controller.php
Labels: Needs Review, not-in-changelog

#16968 Remove unneeded code
  core/ArchiveProcessor/Loader.php
  core/DataAccess/RawLogDao.php
Labels: Needs Review, not-in-changelog

#16974 Check for instanceIds when checking for currently running archive processes
  core/CliMulti/RequestParser.php
Labels: Needs Review, not-in-changelog

#16967 Invalidate archives after deleting a visit to prevent race conditions
  plugins/PrivacyManager/Model/DataSubjects.php
Labels: Needs Review

#16987 Detect running archivers correctly
  core/CronArchive.php
Labels: Needs Review, not-in-changelog

#16988 fix potential error in reports purge query
  plugins/PrivacyManager/ReportsPurger.php
  plugins/PrivacyManager/tests/System/PurgeDataTest.php
Labels: Needs Review, not-in-changelog

#16992 When looking for other climulti processes, also make sure idSite is same.
  core/CronArchive/QueueConsumer.php
Labels: Needs Review

#16976 Update wikimedia/less.php dependency
  composer.json
  composer.lock
  tests/PHPUnit/Integration/ReleaseCheckListTest.php
Labels: Needs Review, not-in-changelog

#16934 Ensure removed dimensions are not used even if they still exist
  core/Columns/Dimension.php
  plugins/DevicePlugins/DevicePlugins.php
  tests/PHPUnit/Integration/Columns/DimensionTest.php
Labels: Needs Review

#16997 Update en.json
  plugins/PagePerformance/lang/en.json
Labels: Needs Review, not-in-changelog

#16977 Improve action id lookup for segments
  core/Tracker/TableLogAction.php
  tests/UI/expected-screenshots/UIIntegrationTest_actions_outlinks_vlog.png
  tests/UI/specs/UIIntegration_spec.js
Labels: Needs Review, not-in-changelog

#17014 Force new visit after 10K actions
  config/global.ini.php
  core/Tracker/VisitorRecognizer.php
  tests/PHPUnit/Integration/Tracker/VisitorRecognizerTest.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: Needs Review, not-in-changelog

#17004 Better fix for climulti segment encoding bug
  config/environment/test.php
  core/CliMulti/Process.php
  core/CliMulti/RequestCommand.php
  core/CronArchive.php
  plugins/CoreConsole/tests/System/ArchiveCronTest.php
  tests/PHPUnit/Integration/CronArchiveTest.php
Labels: Needs Review, Regression

#17008 Fix report showing data of wrong date
  core/Period/Factory.php
  tests/PHPUnit/Integration/Period/FactoryTest.php
Labels: Needs Review, Regression, not-in-changelog

#16966 Add imprint URL to Template.pageFooter
  plugins/PrivacyManager/PrivacyManager.php
  plugins/PrivacyManager/SystemSettings.php
  plugins/PrivacyManager/lang/en.json
  plugins/PrivacyManager/templates/footerLinks.twig
  tests/PHPUnit/System/expected/test_ImportLogs__CorePluginsAdmin.getSystemSettings.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits__CorePluginsAdmin.getSystemSettings.xml
  tests/PHPUnit/System/expected/test_noVisit_PeriodIsLast__CorePluginsAdmin.getSystemSettings.xml
  tests/PHPUnit/System/expected/test_noVisit__CorePluginsAdmin.getSystemSettings.xml
Labels: Needs Review, not-in-changelog

#16747 Assume hidden keywords to be available by default
  plugins/Referrers/SearchEngine.php
  plugins/Referrers/tests/System/ApiTest.php
  tests/resources/extractSearchEngineInformationFromUrlTests.yml
Labels: Needs Review, not-in-changelog

#16971 Limit max execution time of archiving queries to 2 hours by default
  config/global.ini.php
  core/DataAccess/ArchivingDbAdapter.php
  tests/PHPUnit/Integration/DataAccess/LogAggregatorTest.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_settings_general.png
Labels: Needs Review, not-in-changelog

#17021 Make “Compare To” translatable
  lang/en.json
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/angularjs/period-selector/period-selector.directive.html
Labels: Needs Review
