Repository matomo-org/matomo, pull requests merged in 2020-03, with the labels that each got.

#15633 Fix session cookie expire
  core/Session.php
  tests/PHPUnit/Integration/SessionTest.php
Labels: Needs Review, not-in-changelog

#15662 Fix void return used and "improve" isLeap in Date
  core/Date.php
  libs/Zend/Mail.php
  plugins/DevicePlugins/Archiver.php
  plugins/Resolution/Archiver.php
Labels: Needs Review

#15650 Avoid warning from passing 2 args to ucwords() on older PHP versions
  core/Http.php
Labels: Needs Review, not-in-changelog

#15666 Try to prevent a deadlock when writing options
  core/Archive/ArchiveInvalidator.php
  plugins/PrivacyManager/tests/Integration/Model/DataSubjectsTest.php
  plugins/SitesManager/tests/Integration/SitesManagerTest.php
  tests/PHPUnit/Integration/CronArchiveTest.php
  tests/PHPUnit/Integration/DataAccess/ArchiveInvalidatorTest.php
  tests/PHPUnit/Integration/Tracker/VisitTest.php
  tests/PHPUnit/Integration/TrackerTest.php
Labels: Needs Review, not-in-changelog

#15665 Convert range date to date archive if needed
  core/Period/Factory.php
  tests/PHPUnit/Integration/Period/FactoryTest.php
Labels: Needs Review

#15668 Avoid formatting ecommerce conversion rate twice
  plugins/Goals/Controller.php
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard2.png
  tests/UI/expected-screenshots/UIIntegrationTest_goals_individual_goal.png
  tests/UI/expected-screenshots/UIIntegrationTest_goals_individual_goal_updated.png
Labels: Needs Review, not-in-changelog

#15669 Fix issue with HeatmapSessionRecording on IIS
  core/Updates/3.13.4-b1.php
  core/Version.php
  plugins/Installation/ServerFilesGenerator.php
Labels: Needs Review, not-in-changelog

#15671 try to update nonce in out out frame when using new window
  plugins/CoreAdminHome/templates/optOut.twig
  plugins/UsersManager/tests/UI/UsersManager_spec.js
  tests/UI/expected-screenshots/OptOutForm_clicked_once.png
  tests/UI/expected-screenshots/OptOutForm_clicked_twice.png
  tests/UI/expected-screenshots/OptOutForm_opted-out_reloaded.png
  tests/UI/specs/OptOutForm_spec.js
Labels: Needs Review, not-in-changelog

#15670 activate warning for php versions incompatible with next major release
  core/Plugin/ControllerAdmin.php
Labels: Needs Review, not-in-changelog

#15683 fix #15681 secure cookie flag is not set for referrer and custom dimensions
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: Needs Review, not-in-changelog

#15649 By default a segment should be visible to all users
  plugins/SegmentEditor/templates/_segmentSelector.twig
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_6_segment_editor_different.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_8_segment_editor_create.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_add_new_and_condition.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_add_new_or_condition.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_dimension_drag_drop.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_drag_and_condition.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_drag_or_condition.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_saved_details.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_suggested_values.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_updated_details.png
Labels: Needs Review

#15450 Process unique visitor metric for Roll-ups (set enable_processing_unique_visitors_multiple_sites = 1)
  config/global.ini.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: Needs Review

#15616 Move Archive.php archive invalidation to Loader…
  core/Archive.php
  core/Archive/ArchiveInvalidator.php
  core/ArchiveProcessor/Loader.php
  core/ArchiveProcessor/Parameters.php
  core/CronArchive.php
  core/DataAccess/ArchiveSelector.php
  core/DataAccess/Model.php
  core/Period.php
  core/Tracker/Visit.php
  core/Twig.php
  plugins/CoreAdminHome/Tasks.php
  plugins/CoreAdminHome/tests/Integration/TasksTest.php
  plugins/Monolog/Processor/ExceptionToTextProcessor.php
  plugins/PrivacyManager/tests/Integration/DataPurgingTest.php
  tests/PHPUnit/Integration/ArchiveProcessor/LoaderTest.php
  tests/PHPUnit/Integration/ArchiveTest.php
  tests/PHPUnit/Integration/CronArchiveTest.php
  tests/PHPUnit/Integration/DataAccess/ArchiveSelectorTest.php
  tests/PHPUnit/Integration/Tracker/VisitTest.php
  tests/PHPUnit/Integration/TrackerTest.php
  tests/PHPUnit/System/OneVisitorOneWebsiteSeveralDaysDateRangeArchivingTest.php
  tests/PHPUnit/System/OneVisitorTwoVisitsTest.php
  tests/PHPUnit/System/TwoVisitorsTwoWebsitesDifferentDaysConversionsTest.php
  tests/PHPUnit/System/TwoVisitsWithCustomVariablesSegmentMatchVisitorTypeTest.php
  tests/PHPUnit/Unit/PeriodTest.php
Labels: Needs Review, c: Performance

#15686 Prevent notice in PHP 7.4 Passing glue string after array is deprecated
  core/Tracker/Model.php
Labels: Needs Review

#15684 Retry compiling less file if it fails
  plugins/Proxy/Controller.php
Labels: Needs Review

#15676 Make sure to set secure flag when setting samesite none
  core/Tracker/Request.php
Labels: Needs Review, not-in-changelog

#15687 Make sure config cache is only used when there is a correct path
  core/Config/IniFileChain.php
Labels: Needs Review

#15673 Always send a referrer-policy header
  core/View.php
Labels: Needs Review

#15555 Trigger SafeMode if a plugin update is broken
  core/Updater.php
  plugins/CoreUpdater/CoreUpdater.php
Labels: Needs Review

#15664 Force using index index_idsite_idvisitor if available
  core/DbHelper.php
  core/Tracker/Model.php
  plugins/CoreHome/CoreHome.php
  plugins/ExampleLogTables/tests/Fixtures/VisitsWithUserIdAndCustomData.php
  plugins/ExampleLogTables/tests/System/expected/test_ExampleLogTables_admin__Actions.get_month.xml
  plugins/ExampleLogTables/tests/System/expected/test_ExampleLogTables_admin__UserId.getUsers_month.xml
  plugins/ExampleLogTables/tests/System/expected/test_ExampleLogTables_admin__VisitsSummary.get_month.xml
  plugins/ExampleLogTables/tests/System/expected/test_ExampleLogTables_all__Actions.get_month.xml
  plugins/ExampleLogTables/tests/System/expected/test_ExampleLogTables_all__UserId.getUsers_month.xml
  plugins/ExampleLogTables/tests/System/expected/test_ExampleLogTables_all__VisitsSummary.get_month.xml
  plugins/ExampleLogTables/tests/System/expected/test_ExampleLogTables_men__Actions.get_month.xml
  plugins/ExampleLogTables/tests/System/expected/test_ExampleLogTables_men__UserId.getUsers_month.xml
  plugins/ExampleLogTables/tests/System/expected/test_ExampleLogTables_men__VisitsSummary.get_month.xml
  plugins/ExampleLogTables/tests/System/expected/test_ExampleLogTables_women__Actions.get_month.xml
  plugins/ExampleLogTables/tests/System/expected/test_ExampleLogTables_women__UserId.getUsers_month.xml
  plugins/ExampleLogTables/tests/System/expected/test_ExampleLogTables_women__VisitsSummary.get_month.xml
  plugins/UserId/tests/Fixtures/TrackFewVisitsAndCreateUsers.php
Labels: Needs Review, not-in-changelog

#15652 respect max execution time limit for transitions plugin
  core/DataAccess/LogAggregator.php
  core/DbHelper.php
  core/RankingQuery.php
  plugins/Live/Model.php
  plugins/Live/tests/Integration/ModelTest.php
  plugins/Transitions/API.php
  tests/PHPUnit/Unit/DbHelperTest.php
Labels: Needs Review, not-in-changelog

#15694 Note dbip's poor city accuracy in UI
  plugins/UserCountry/lang/en.json
  plugins/UserCountry/templates/_updaterManage.twig
  plugins/UserCountry/templates/adminIndex.twig
Labels: Needs Review, not-in-changelog

#15704 readd provider plugin
  .gitmodules
Labels: not-in-changelog

#15705 fix template
  plugins/UsersManager/templates/userSettings.twig
Labels: Regression, not-in-changelog

#15701 Revert "Process unique visitor metric for Roll-ups (set enable_processing_unique_visitors_multiple_sites = 1)"
  config/global.ini.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: Needs Review

#15706 Avoid update problem if token_auth table does not yet exist
  core/DbHelper.php
  plugins/Login/Auth.php
Labels: Regression, not-in-changelog

#15707 Detect page view bucket
  plugins/Marketplace/Api/Client.php
Labels: Needs Review

#15713 Fix there might no permission to get multisites report
  plugins/Marketplace/Api/Client.php
Labels: Needs Review, not-in-changelog

#15636 Replace jscrollpane with native
  bower.json
  libs/bower_components/jScrollPane/.bower.json
  libs/bower_components/jScrollPane/.gitignore
  libs/bower_components/jScrollPane/.gitmodules
  libs/bower_components/jScrollPane/MIT-LICENSE.txt
  libs/bower_components/jScrollPane/README.md
  libs/bower_components/jScrollPane/bower.json
  libs/bower_components/jScrollPane/build/.gitignore
  libs/bower_components/jScrollPane/build/Gruntfile.js
  libs/bower_components/jScrollPane/build/package.json
  libs/bower_components/jScrollPane/image/logo.png
  libs/bower_components/jScrollPane/script/demo.js
  libs/bower_components/jScrollPane/script/jquery.jscrollpane.js
  libs/bower_components/jScrollPane/script/jquery.jscrollpane.min.js
  libs/bower_components/jScrollPane/script/jquery.mousewheel.js
  libs/bower_components/jScrollPane/script/mwheelIntent.js
  libs/bower_components/jScrollPane/style/demo.css
  libs/bower_components/jScrollPane/style/jquery.jscrollpane.css
  libs/bower_components/jquery-mousewheel/.bower.json
  libs/bower_components/jquery-mousewheel/ChangeLog.md
  libs/bower_components/jquery-mousewheel/LICENSE.txt
  libs/bower_components/jquery-mousewheel/README.md
  libs/bower_components/jquery-mousewheel/bower.json
  libs/bower_components/jquery-mousewheel/jquery.mousewheel.js
  libs/bower_components/jquery-mousewheel/jquery.mousewheel.min.js
  libs/jquery/mwheelIntent.js
  libs/jquery/stylesheets/jquery.jscrollpane.css
  libs/jquery/stylesheets/scroll.less
  plugins/CoreHome/CoreHome.php
  plugins/SegmentEditor/stylesheets/segmentation.less
Labels: Needs Review

#15558 Remove PHP serialization response format
  CHANGELOG.md
  core/CliMulti.php
  core/CronArchive.php
  core/DataTable/Renderer.php
  core/DataTable/Renderer/Json.php
  core/DataTable/Renderer/Php.php
  core/DataTable/Renderer/Xml.php
  plugins/API/API.php
  plugins/API/Renderer/Php.php
  plugins/API/tests/System/AutoSuggestAPITest.php
  plugins/API/tests/Unit/PhpRendererTest.php
  plugins/CoreHome/templates/_dataTableActions.twig
  plugins/CoreUpdater/tests/UI/CoreUpdaterDb_spec.js
  plugins/MultiSites/Dashboard.php
  plugins/SEO/Widgets/GetRank.php
  plugins/SEO/tests/Integration/SEOTest.php
  plugins/UserCountryMap/Controller.php
  tests/PHPUnit/Framework/TestRequest/Collection.php
  tests/PHPUnit/Integration/CronArchiveTest.php
  tests/PHPUnit/Integration/DataTable/Filter/PivotByDimensionTest.php
  tests/PHPUnit/System/ApiGetReportMetadataTest.php
  tests/PHPUnit/System/expected/test_apiGetReportMetadata_defaultFormatValue__Actions.getPageTitles_day.asldjkf
  tests/PHPUnit/System/expected/test_apiGetReportMetadata_phpRenderer__API.getDefaultMetricTranslations.php
  tests/PHPUnit/Unit/API/ApiRendererTest.php
  tests/PHPUnit/Unit/API/ResponseBuilderTest.php
  tests/PHPUnit/Unit/DataTable/Renderer/PHPTest.php
  tests/PHPUnit/Unit/FilesystemTest.php
  tests/UI/expected-screenshots/ReportExporting_Referrers.getWebsites_exported.php.txt
  tests/UI/expected-screenshots/ReportExporting_RowEvolution_exported.php.txt
  tests/UI/expected-screenshots/ReportExporting_VisitsSummary.get_exported.php.txt
  tests/UI/expected-screenshots/ViewDataTableTest_export_options.png
  tests/UI/specs/ReportExporting_spec.js
Labels: Needs Review, not-in-changelog

#15723 Improve sorting of action details
  plugins/Live/Visualizations/VisitorLog.php
Labels: Needs Review, c: Tests & QA, not-in-changelog

#15719 Fix segment editor scrolling
  plugins/SegmentEditor/javascripts/Segmentation.js
  plugins/SegmentEditor/stylesheets/segmentation.less
Labels: Needs Review, Regression, not-in-changelog

#15724 Add possibility to silently stop the archiver without an error
  core/CronArchive.php
  core/CronArchive/StopArchiverException.php
Labels: Enhancement

#15696 Better handling of processing uniques for multiple sites
  core/ArchiveProcessor.php
  core/DataAccess/LogAggregator.php
  tests/PHPUnit/System/MultipleSitesArchivingTest.php
Labels: Needs Review

#15688 Ensure stringify/parse is a function
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: Needs Review

#15728 Ensure to use correct date while archiving
  core/CronArchive.php
  tests/PHPUnit/Integration/CronArchiveTest.php
Labels: Needs Review, not-in-changelog

#15712 Show accurately the configured retention length
  plugins/PrivacyManager/Controller.php
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_overview.png
  plugins/UsersManager/tests/UI/expected-screenshots/UserSettings_load_security.png
Labels: Needs Review

#15750 Fix displaying of actions when loading additional visits in visitor profile
  plugins/Live/Controller.php
  plugins/Live/tests/UI/Live_spec.js
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_profile_action_details.png
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_profile_actions_hidden.png
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_profile_more_visits.png
  plugins/Live/tests/UI/expected-screenshots/Live_visitor_profile_visit_details.png
Labels: Needs Review, Regression

#15749 re-expire archiving lock less often
  core/DataAccess/ArchivingDbAdapter.php
Labels: Needs Review, not-in-changelog

#15757 Update device detector to latest 3.12.4
  composer.lock
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_browserName__API.getSuggestedValuesForSegment.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getSegmentsMetadata.xml
Labels: Task
