Repository matomo-org/matomo, pull requests merged in 2020-02, with the labels that each got.

#15223 Hide visitor map controls if no data is available
  plugins/CorePluginsAdmin/tests/UI/expected-screenshots/TagManagerTeaser_admin_page_disable.png
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuth_logme_verified.png
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuth_twofa_forced_step4.png
  plugins/UserCountryMap/javascripts/visitor-map.js
  plugins/UserCountryMap/stylesheets/visitor-map.less
  plugins/UserCountryMap/templates/visitorMap.twig
  plugins/UserCountryMap/tests/UI/expected-screenshots/VisitorMap_cities.png
  plugins/UserCountryMap/tests/UI/expected-screenshots/VisitorMap_regions.png
Labels: Needs Review, not-in-changelog

#15503 Removes deprecated console param --piwik-domain
  CHANGELOG.md
  core/CliMulti/RequestCommand.php
  core/Console.php
  core/CronArchive.php
  plugins/TestRunner/Commands/TestsRun.php
  plugins/TestRunner/Commands/TestsRunUI.php
  tests/lib/screenshot-testing/support/test-environment.js
Labels: Needs Review

#15502 Fix possible undefined index notice
  core/Plugin/Report.php
Labels: Needs Review, not-in-changelog

#15506 Ensure to only show enabled reports in "Goals By"-view
  plugins/Goals/Goals.php
Labels: Bug, Needs Review

#15504 Removes Piwik is now Matomo from update screen
  plugins/CoreUpdater/templates/updateSuccess.twig
  tests/UI/expected-screenshots/OneClickUpdate_update_success.png
Labels: Needs Review, not-in-changelog

#15465 Use latest davaxi/sparkline release
  composer.json
  composer.lock
Labels: Needs Review

#15464 Use latest davaxi/sparkline release
  composer.json
  composer.lock
Labels: Needs Review

#15275 Force using DB sessions once Matomo is installed
  config/global.ini.php
  core/Session.php
  plugins/TestRunner/Aws/config.ini.php
  tests/PHPUnit/Framework/Mock/TestConfig.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: Needs Review

#15530 Fix deprecation notice
  plugins/CoreVisualizations/Visualizations/HtmlTable.php
Labels: Needs Review

#15536 Update cache component
  composer.lock
Labels: Needs Review, not-in-changelog

#15539 Missing return
  core/Console.php
Labels: not-in-changelog

#15533 [automatic translation update] Updated 4 strings in 2 languages (de el)
  plugins/Annotations/lang/de.json
  plugins/Diagnostics/lang/el.json
  plugins/MultiSites/lang/de.json
Labels: c: i18n

#15535 Fix missing crossorigin attribute in manifest link
  plugins/Morpheus/templates/layout.twig
Labels: Needs Review, not-in-changelog

#15531 Add support for up to 4 fields to multipairfield
  plugins/CoreHome/angularjs/multipairfield/multipairfield.controller.js
  plugins/CoreHome/angularjs/multipairfield/multipairfield.directive.html
  plugins/CoreHome/angularjs/multipairfield/multipairfield.directive.js
  plugins/CoreHome/angularjs/multipairfield/multipairfield.directive.less
  plugins/CorePluginsAdmin/angularjs/form-field/field-multituple.html
  plugins/Morpheus/templates/demo.twig
  plugins/Morpheus/tests/UI/expected-screenshots/Morpheus_load.png
  tests/UI/expected-screenshots/Theme_demo.png
Labels: Needs Review

#15551 Trigger exception when idgoal does not exist
  core/Tracker/GoalManager.php
  tests/PHPUnit/System/TrackerResponseTest.php
Labels: Needs Review, not-in-changelog

#15542 Adds action for building tracker js files
  .github/workflows/buildtrackerjs.yml
Labels: Needs Review

#15556 Empty auto complete results in segment editor when changing the segment
  plugins/SegmentEditor/angularjs/segment-generator/segmentgenerator.controller.js
Labels: Needs Review, c: Usability

#15557 Makes "Ask for Consent" page translatable
  plugins/PrivacyManager/lang/en.json
  plugins/PrivacyManager/templates/askingForConsent.twig
Labels: Needs Review, not-in-changelog

#15560 Prevent possible notice curly braces on array - PHP 7.4 compatibility
  libs/HTML/QuickForm2/Element/Date.php
  libs/Zend/Validate/Isbn.php
Labels: Needs Review, not-in-changelog

#15544 Ensure the number of fraction digits is correct
  core/NumberFormatter.php
  plugins/CoreHome/DataTableRowAction/RowEvolution.php
  tests/PHPUnit/Integration/NumberFormatterTest.php
Labels: Needs Review

#15566 Don't link to UI Updater when multi server environment is enabled
  plugins/CoreHome/templates/_headerMessage.twig
Labels: Needs Review, not-in-changelog

#15568 Support tracker js files from custom plugin directories
  plugins/CustomPiwikJs/TrackingCode/PluginTrackerFiles.php
  plugins/CustomPiwikJs/tests/Integration/PluginTrackerFilesTest.php
Labels: Needs Review

#15569 Fix non-numeric value encountered in session recording
  plugins/CoreVisualizations/Visualizations/HtmlTable.php
Labels: Needs Review

#15577 During archive invalidation clear general cache less often
  core/Archive/ArchiveInvalidator.php
Labels: Needs Review

#15576 Do not record the stack trace for user input errors
  core/Exception/InvalidRequestParameterException.php
Labels: Needs Review

#15564 Fix some failing tests
  plugins/Dashboard/tests/UI/DashboardManager_spec.js
  plugins/Dashboard/tests/UI/Dashboard_spec.js
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_removed.png
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_html_row_evolution_graph__ScheduledReports.generateReport_week.original.html
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_html_row_evolution_overEach__ScheduledReports.generateReport_week.original.html
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_html_row_evolution_prevCustomN__ScheduledReports.generateReport_week.original.html
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_html_tables_and_graph__ScheduledReports.generateReport_week.original.html
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_in_pdf_tables_only__ScheduledReports.generateReport_week.original.pdf
  plugins/Feedback/tests/UI/FeedbackPopup_spec.js
  plugins/Feedback/tests/UI/expected-screenshots/FeedbackPopup_dashboard_no_popup.png
  plugins/TwoFactorAuth/tests/UI/TwoFactorAuth_spec.js
  plugins/UsersManager/tests/UI/UsersManager_spec.js
  tests/PHPUnit/Framework/Fixture.php
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_html_row_evolution_graph__ScheduledReports.generateReport_month.original.html
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_html_row_evolution_overEach__ScheduledReports.generateReport_month.original.html
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_html_row_evolution_prevCustomN__ScheduledReports.generateReport_month.original.html
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_html_tables_and_graph__ScheduledReports.generateReport_month.original.html
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_in_pdf_tables_only__ScheduledReports.generateReport_month.original.pdf
  tests/UI/expected-screenshots/OptOutForm_opted-out_reloaded.png
  tests/UI/expected-screenshots/ReportExporting_VisitsSummary.get_exported.php.txt
  tests/UI/specs/EmptySite_spec.js
  tests/UI/specs/OneClickUpdate_spec.js
  tests/UI/specs/OptOutForm_spec.js
Labels: Needs Review, c: Tests & QA, not-in-changelog

#15572 color background of custom logo preview
  plugins/CoreAdminHome/stylesheets/generalSettings.less
Labels: Needs Review, c: Design / UI, not-in-changelog

#15583 Fixes some comparison issues
  plugins/CoreHome/angularjs/common/services/periods.js
  plugins/CoreHome/angularjs/period-selector/period-selector.controller.js
Labels: Needs Review, not-in-changelog

#15578 Add movers and shakers widget to dashboard
  core/Period/Range.php
  plugins/CorePluginsAdmin/tests/UI/expected-screenshots/TagManagerTeaser_admin_page_disable.png
  plugins/Dashboard/Dashboard.php
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_create_new.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_reset.png
  plugins/Insights/tests/Integration/ApiTest.php
  plugins/Insights/tests/Integration/ModelTest.php
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuth_logme_verified.png
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuth_twofa_forced_step4.png
  tests/PHPUnit/System/expected/test_oneVisitor_oneWebsite_severalDays_DateRange__MultiSites.getAll_range.xml
  tests/PHPUnit/System/expected/test_oneVisitor_oneWebsite_severalDays_DateRange__MultiSites.getOne_range.xml
  tests/PHPUnit/Unit/Period/RangeTest.php
Labels: Needs Review, not-in-changelog

#15570 couple proxysite changes for comparison hopefully w/o side effects
  core/Plugin/ViewDataTable.php
  core/Plugin/Visualization.php
Labels: Needs Review

#15595 Improve / Fix UserID tests
  tests/PHPUnit/Fixtures/FewVisitsWithSetVisitorId.php
  tests/PHPUnit/System/expected/test_UserId_VisitorId__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_UserId_VisitorId__VisitsSummary.get_day.xml
  tests/PHPUnit/System/expected/test_UserId_VisitorId__VisitsSummary.get_month.xml
  tests/PHPUnit/System/expected/test_UserId_VisitorId__VisitsSummary.get_week.xml
  tests/PHPUnit/System/expected/test_UserId_VisitorId__VisitsSummary.get_year.xml
  tests/PHPUnit/System/expected/test_UserId_VisitorId_segmentUserId__Goals.get_day.xml
  tests/PHPUnit/System/expected/test_UserId_VisitorId_segmentUserId__VisitsSummary.get_day.xml
Labels: c: Tests & QA, not-in-changelog

#15541 Adds translation updates action
  .github/workflows/translations.yml
Labels: Needs Review

#15590 Fallback to JSON renderer if no valid format is given
  core/API/Request.php
  tests/PHPUnit/System/ApiGetReportMetadataTest.php
  tests/PHPUnit/System/expected/test_apiGetReportMetadata_defaultFormatValue__Actions.getPageTitles_day.asldjkf
Labels: Needs Review

#15561 Fix couple issues w/ samesite handling in session, make sure session …
  core/Cookie.php
  core/Session.php
  core/Tracker/IgnoreCookie.php
  js/piwik.js
  js/piwik.min.js
  libs/Zend/Session.php
  matomo.js
  piwik.js
  plugins/Overlay/Controller.php
  tests/PHPUnit/System/CookieTest.php
  tests/lib/screenshot-testing/package-lock.json
  tests/lib/screenshot-testing/package.json
Labels: Needs Review

#15587 Ensure a valid timestamp is set when recording a conversion
  core/Tracker/GoalManager.php
  core/Tracker/Model.php
  core/Tracker/Visit.php
  tests/PHPUnit/Integration/Tracker/ModelTest.php
Labels: Needs Review, not-in-changelog

#15603 Try to prevent possible deadlock in archive invalidator
  core/Archive/ArchiveInvalidator.php
Labels: Needs Review, not-in-changelog

#15567 Add UI test for JavaScript tracking.
  core/Tracker/Response.php
  plugins/ExampleTracker/Columns/ExampleVisitDimension.php
  plugins/ExampleTracker/ExampleTracker.php
  plugins/ExampleTracker/VisitorDetails.php
  plugins/ExampleTracker/templates/_visitorLogIcons.twig
  plugins/ExampleTracker/tracker.js
  tests/PHPUnit/Fixtures/JSTrackingUIFixture.php
  tests/PHPUnit/Fixtures/UITestFixture.php
  tests/UI/expected-screenshots/JSTracker_visitor_log.png
  tests/UI/specs/JSTracker_spec.js
  tests/resources/overlay-test-site/index.html
  tests/resources/overlay-test-site/page-1.html
  tests/resources/overlay-test-site/page-2.html
  tests/resources/overlay-test-site/page-3.html
  tests/resources/overlay-test-site/page-4.html
  tests/resources/overlay-test-site/page-5.html
  tests/resources/overlay-test-site/page-6.html
Labels: Needs Review

#15601 Fix VisitorFrequency.get API for idsites=all
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_noOptions__VisitFrequency.get_month.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment0_noOptions__VisitFrequency.get_day.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment0_noOptions__VisitFrequency.get_year.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment1_noOptions__VisitFrequency.get_day.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment1_noOptions__VisitFrequency.get_year.xml
  plugins/VisitFrequency/API.php
  tests/PHPUnit/System/expected/test_DataComparisonTest_multipleSites_multipleCompare__VisitFrequency.get_month.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__VisitFrequency.get_day.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__VisitFrequency.get_month.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__VisitFrequency.get_week.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__VisitFrequency.get_year.xml
Labels: Needs Review, Regression

#15605 Fix VisitorFrequency.get API for idsites=all
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_noOptions__VisitFrequency.get_month.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment0_noOptions__VisitFrequency.get_day.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment0_noOptions__VisitFrequency.get_year.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment1_noOptions__VisitFrequency.get_day.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment1_noOptions__VisitFrequency.get_year.xml
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_removed.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_loaded_token_auth.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_removed.png
  plugins/VisitFrequency/API.php
  tests/PHPUnit/System/ConsoleTest.php
  tests/PHPUnit/System/expected/test_DataComparisonTest_multipleSites_multipleCompare__VisitFrequency.get_month.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__VisitFrequency.get_day.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__VisitFrequency.get_month.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__VisitFrequency.get_week.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__VisitFrequency.get_year.xml
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: Regression

#15602 Fix session cookies for Matomo installed in subdirectory
  core/Session.php
Labels: Needs Review, Regression

#15592 Try to determine the region iso code based on it's name if not available
  plugins/GeoIp2/LocationProvider/GeoIp2/Php.php
  plugins/GeoIp2/tests/Integration/LocationProviderTest.php
  tests/lib/geoip-files/GeoIP2-City.json
  tests/lib/geoip-files/GeoIP2-City.mmdb
Labels: Needs Review

#15606 Allow using paid db-ip urls for auto update
  plugins/GeoIp2/GeoIP2AutoUpdater.php
  plugins/GeoIp2/tests/Unit/GeoIP2AutoUpdaterTest.php
Labels: Needs Review, not-in-changelog

#15615 Make sure "Event Category" is translated in Visits log API outputs
  plugins/API/tests/System/expected/test_AutoSuggestAPITest__Live.getLastVisitsDetails_range.xml
  plugins/Events/VisitorDetails.php
  plugins/PrivacyManager/tests/System/expected/test_allSites__Live.getLastVisitsDetails_year.xml
  tests/PHPUnit/System/expected/test_CustomEvents__Live.getLastVisitsDetails_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Live.getLastVisitsDetails_range.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_Live.getLastVisitsDetails_offsetAndLimit_1__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_Live.getLastVisitsDetails_offsetAndLimit_2__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_Live.getLastVisitsDetails_sortByIdVisit__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_Live.getLastVisitsDetails_sortDesc__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest__Live.getLastVisitsDetails_month.xml
Labels: Needs Review

#15408 Fix event value is truncated
  core/Db/Schema/Mysql.php
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_eventValue__VisitsSummary.get_range.xml
Labels: Needs Review, not-in-changelog

#15614 Remove donation widget from dashboard
  plugins/Dashboard/Dashboard.php
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_create_new.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_reset.png
  plugins/Marketplace/lang/en.json
  plugins/Marketplace/templates/getPremiumFeatures.twig
Labels: Needs Review

#15604 Set samesite lax instead of None if site is not on https
  core/Cookie.php
Labels: Needs Review, not-in-changelog

#15622 Temporarily skip some tests until we have a first release
  plugins/Marketplace/tests/System/Api/ClientTest.php
  tests/PHPUnit/Unit/DeprecatedMethodsTest.php
Labels: c: Tests & QA, not-in-changelog

#15621 Fix failing Live system test
  plugins/Live/tests/System/expected/test_actionSegment__Live.getLastVisitsDetails_day.xml
Labels: Needs Review, c: Tests & QA, not-in-changelog

#15585 Use transient cache for caching menus instead static array
  core/Menu/MenuAbstract.php
  core/Menu/MenuAdmin.php
  core/Menu/MenuTop.php
  tests/PHPUnit/Framework/TestCase/IntegrationTestCase.php
Labels: Needs Review

#15582 Makes remaining GDPR pages fully translatable
  plugins/PrivacyManager/PrivacyManager.php
  plugins/PrivacyManager/angularjs/anonymize-log-data/anonymize-log-data.directive.html
  plugins/PrivacyManager/angularjs/manage-gdpr/managegdpr.directive.html
  plugins/PrivacyManager/angularjs/opt-out-customizer/opt-out-customizer.directive.html
  plugins/PrivacyManager/lang/en.json
  plugins/PrivacyManager/templates/gdprOverview.twig
  plugins/PrivacyManager/templates/usersOptOut.twig
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_overview.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_overview_no_retention.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_delete_visit_cancelled.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_delete_visit_cancelled_verified_no_data_deleted.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_delete_visit_confirmed.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_enrich_segment_by_ip.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_uncheck_one_visit.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_visits_found.png
Labels: Needs Review, not-in-changelog

#15591 Do not initiate auth instance if a user is already logged in in FrontController::init()
  core/Access.php
  core/FrontController.php
Labels: Needs Review, not-in-changelog

#15619 Prevent server gone away error in CronArchive
  core/CronArchive.php
Labels: Bug, Needs Review

#15611 Only detect php type based on file name
  config/global.ini.php
  core/CliMulti/CliPhp.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: Needs Review

#15584 Fix CSV export for idSite=all
  plugins/API/Renderer/Csv.php
  plugins/Ecommerce/Reports/Base.php
  plugins/ImageGraph/ImageGraph.php
  tests/PHPUnit/Fixtures/ThreeSitesWithSharedVisitors.php
  tests/PHPUnit/System/AllWebsitesTest.php
  tests/PHPUnit/System/expected/test_AllWebsitesTest_superuser__VisitsSummary.get_.csv
  tests/PHPUnit/System/expected/test_AllWebsitesTest_user__VisitsSummary.get_.csv
Labels: Needs Review, not-in-changelog

#15521 Removes GeoIp Legacy support
  CHANGELOG.md
  core/Updates/4.0.0-b1.php
  libs/MaxMindGeoIP/geoip.inc
  libs/MaxMindGeoIP/geoipcity.inc
  plugins/GeoIp2/Columns/Region.php
  plugins/GeoIp2/Controller.php
  plugins/GeoIp2/GeoIP2AutoUpdater.php
  plugins/GeoIp2/GeoIp2.php
  plugins/GeoIp2/LocationProvider/GeoIp2/Php.php
  plugins/GeoIp2/LocationProvider/GeoIp2/ServerModule.php
  plugins/GeoIp2/angularjs/geoip2-updater/geoip2-updater.controller.js
  plugins/GeoIp2/angularjs/geoip2-updater/geoip2-updater.directive.js
  plugins/GeoIp2/lang/en.json
  plugins/GeoIp2/templates/_updaterManage.twig
  plugins/GeoIp2/templates/_updaterNextRunTime.twig
  plugins/GeoIp2/templates/configuration.twig
  plugins/GeoIp2/templates/setupguide.twig
  plugins/GeoIp2/tests/Unit/GeoIp2Test.php
  plugins/UserCountry/Archiver.php
  plugins/UserCountry/Columns/Region.php
  plugins/UserCountry/Controller.php
  plugins/UserCountry/Diagnostic/GeolocationDiagnostic.php
  plugins/UserCountry/GeoIPAutoUpdater.php
  plugins/UserCountry/LocationProvider.php
  plugins/UserCountry/LocationProvider/GeoIp.php
  plugins/UserCountry/LocationProvider/GeoIp/Pecl.php
  plugins/UserCountry/LocationProvider/GeoIp/Php.php
  plugins/UserCountry/LocationProvider/GeoIp/ServerBased.php
  plugins/UserCountry/Reports/Base.php
  plugins/UserCountry/Reports/GetContinent.php
  plugins/UserCountry/Tasks.php
  plugins/UserCountry/UserCountry.php
  plugins/UserCountry/functions.php
  plugins/UserCountry/lang/en.json
  plugins/UserCountry/templates/_updaterNextRunTime.twig
  plugins/UserCountry/templates/adminIndex.twig
  plugins/UserCountry/tests/Integration/APITest.php
  plugins/UserCountry/tests/UI/UserCountry_spec.js
  plugins/UserCountry/tests/UI/expected-screenshots/UserCountry_admin_geoip2.png
  plugins/UserCountry/tests/UI/expected-screenshots/UserCountry_admin_no_providers.png
  plugins/UserCountry/tests/Unit/UserCountryTest.php
  tests/PHPUnit/Framework/TestingEnvironmentManipulator.php
Labels: Needs Review, not-in-changelog

#15632 Remove jquery placeholder
  bower.json
  libs/bower_components/jquery-placeholder/.bower.json
  libs/bower_components/jquery-placeholder/bower.json
  libs/bower_components/jquery-placeholder/jquery.placeholder.js
  plugins/Login/templates/loginLayout.twig
Labels: Needs Review

#15643 UI test failure screenshots for plugins not uploaded
  tests/lib/screenshot-testing/support/app.js
Labels: Needs Review, c: Tests & QA, not-in-changelog
