Repository matomo-org/matomo, pull requests merged in 2021-07, with the labels that each got.

#17726 Add possiblity to open sites manager and directly edit a specific site using URL parameter
  plugins/SitesManager/angularjs/sites-manager/sites-manager-site.controller.js
  plugins/SitesManager/angularjs/sites-manager/sites-manager-type-model.js
  plugins/SitesManager/angularjs/sites-manager/sites-manager.controller.js
  plugins/SitesManager/tests/UI/SitesManager_spec.js
  plugins/SitesManager/tests/UI/expected-screenshots/SitesManager_site_edit_url.png
Labels: Needs Review

#17700 Adds some more tests for log importer
  tests/PHPUnit/Integration/LogImporterTest.php
  tests/resources/access-logs/different_hosts.log
  tests/resources/access-logs/windows-1252.log
Labels: Needs Review, c: Tests & QA

#17724 Added "aurora_readonly_read_committed" setting to global ini
  config/global.ini.php
Labels: Needs Review, not-in-changelog

#17735 Handle failed promise by silently ignoring it
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: Needs Review, not-in-changelog

#17742 Fix preselection in site selector form fields
  plugins/CoreHome/angularjs/siteselector/siteselector.directive.js
  plugins/CorePluginsAdmin/angularjs/form-field/field-site.html
Labels: Needs Review

#17758 Fix possible warning that session is not active for anonymous user
  core/FrontController.php
  tests/PHPUnit/Integration/FrontControllerTest.php
Labels: Needs Review, not-in-changelog

#17744 17417 cookie domain
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  tests/javascript/index.php
Labels: Needs Review, not-in-changelog

#17778 Throw a meaningful exception if a report does not support pivot feature
  core/DataTable/Filter/PivotByDimension.php
Labels: Needs Review, not-in-changelog

#17757 provide console command for version information (#17755)
  plugins/CoreAdminHome/Commands/VersionInfo.php
Labels: Needs Review

#17788 do not try and set mysqli ssl option through mysqli_options since it is set later via mysqli_ssl_set
  libs/Zend/Db/Adapter/Mysqli.php
Labels: Needs Review, not-in-changelog

#17772 check plugin exists in the filesystem on plugin activate command
  core/Plugin/Manager.php
  plugins/CorePluginsAdmin/Commands/ActivatePlugin.php
Labels: Needs Review, not-in-changelog

#17792 Updates device detector to 4.3.0
  composer.lock
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_browserName__API.getSuggestedValuesForSegment.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getSegmentsMetadata.xml
Labels: Task

#17779 Fix filter in UserCountry.getCountry for Map of Maps
  plugins/UserCountry/API.php
  plugins/UserCountry/tests/Fixtures/ManySitesManyVisitsWithGeoIp.php
  plugins/UserCountry/tests/System/ApiTest.php
  plugins/UserCountry/tests/System/expected/test___UserCountry.getCity_day.xml
  plugins/UserCountry/tests/System/expected/test___UserCountry.getContinent_day.xml
  plugins/UserCountry/tests/System/expected/test___UserCountry.getCountry_day.xml
  plugins/UserCountry/tests/System/expected/test___UserCountry.getRegion_day.xml
  plugins/UserCountry/tests/System/expected/test_multi_period__UserCountry.getCity_day.xml
  plugins/UserCountry/tests/System/expected/test_multi_period__UserCountry.getContinent_day.xml
  plugins/UserCountry/tests/System/expected/test_multi_period__UserCountry.getCountry_day.xml
  plugins/UserCountry/tests/System/expected/test_multi_period__UserCountry.getRegion_day.xml
  plugins/UserCountry/tests/System/expected/test_multi_periods_and_sites__UserCountry.getCity_day.xml
  plugins/UserCountry/tests/System/expected/test_multi_periods_and_sites__UserCountry.getContinent_day.xml
  plugins/UserCountry/tests/System/expected/test_multi_periods_and_sites__UserCountry.getCountry_day.xml
  plugins/UserCountry/tests/System/expected/test_multi_periods_and_sites__UserCountry.getRegion_day.xml
  plugins/UserCountry/tests/System/expected/test_multi_sites__UserCountry.getCity_month.xml
  plugins/UserCountry/tests/System/expected/test_multi_sites__UserCountry.getContinent_month.xml
  plugins/UserCountry/tests/System/expected/test_multi_sites__UserCountry.getCountry_month.xml
  plugins/UserCountry/tests/System/expected/test_multi_sites__UserCountry.getRegion_month.xml
  tests/PHPUnit/Fixtures/ManyVisitsWithGeoIP.php
Labels: Needs Review, not-in-changelog

#17793 Temporarily let update test fail directly to avoid aborted tests on PHP7.4 and above
  plugins/CoreUpdater/tests/Integration/Commands/UpdateTest.php
Labels: c: Tests & QA, not-in-changelog

#17795 Support filter_truncate parameter for MultiSites API
  plugins/MultiSites/API.php
  tests/PHPUnit/System/OneVisitorOneWebsiteSeveralDaysDateRangeTest.php
  tests/PHPUnit/System/expected/test_oneVisitor_oneWebsite_severalDays_DateRange_Truncated__MultiSites.getAll_range.xml
Labels: Needs Review, not-in-changelog

#17789 More helpful messages on db connection failures
  core/Db/Adapter.php
  lang/en.json
  plugins/Installation/tests/System/APITest.php
  tests/PHPUnit/Unit/Tracker/CacheTest.php
  tests/UI/expected-screenshots/UIIntegrationTest_db_connect_error.png
Labels: Needs Review

#17790 do not ignore remote_addr if reading the last ip in proxy header lists
  core/IP.php
  tests/PHPUnit/Unit/IPTest.php
Labels: Needs Review

#17442 Fix exporting main metrics with a period of weeks and export format CSV
  core/DataTable/Renderer/Csv.php
  tests/PHPUnit/System/CsvExportTest.php
  tests/PHPUnit/System/expected/test_csvExport_multi__Contents.getContentNames_week.csv
  tests/PHPUnit/System/expected/test_csvExport_multi__VisitsSummary.get_week.csv
Labels: not-in-changelog

#17800 do not introduce breaking change in Mail.send
  CHANGELOG.md
  core/Mail.php
Labels: Regression

#17806 Fix failing Mail test
  tests/PHPUnit/Integration/MailTest.php
Labels: c: Tests & QA, not-in-changelog

#17822 Archiving may fail when also using roll up reporting
  core/DataAccess/Model.php
Labels: Needs Review

#17826 Add minor entries to dev changelog
  CHANGELOG.md
Labels: Needs Review

#17830 Don't check cookie value if cookie was deleted
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  tests/javascript/index.php
Labels: Needs Review, not-in-changelog

#17832 Add command to generate a system check
  plugins/CoreConsole/Commands/GenerateSystemCheck.php
  plugins/ExamplePlugin/Diagnostic/ExampleCheck.php
Labels: Needs Review

#17831 make sure summary rows are serialized with their in-db subtable ID and not in memory one
  core/DataTable.php
  tests/PHPUnit/Unit/DataTableTest.php
Labels: Bug, Needs Review

#17840 better checks when shell_exec is disabled
  core/CliMulti/Process.php
Labels: Needs Review

#17842 Revert "more private Referrer-Policy: use strict-origin-when-cross-origin "
  core/View.php
Labels: Needs Review
