Repository matomo-org/matomo, pull requests merged in 2021-11, with the labels that each got.

#18233 Added code to filter response for API.getReportPagesMetadata and API.getWidgetMetadata
  plugins/CustomDimensions/tests/System/ApiTest.php
  plugins/CustomDimensions/tests/System/expected/test___API.getReportPagesMetadata.xml
  plugins/CustomDimensions/tests/System/expected/test___API.getWidgetMetadata.xml
  tests/PHPUnit/Framework/TestCase/SystemTestCase.php
Labels: c: Tests & QA, not-in-changelog

#18124 set table head sticky
  plugins/CoreHome/javascripts/dataTable.js
  plugins/CoreHome/stylesheets/dataTable/_dataTable.less
  plugins/PagePerformance/tests/UI/expected-screenshots/PagePerformance_rowactions.png
  plugins/PagePerformance/tests/UI/expected-screenshots/PagePerformance_rowactions_subtable.png
  tests/UI/expected-screenshots/UIIntegrationTest_actions_content_piece_name.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard3.png
  tests/UI/expected-screenshots/UIIntegrationTest_exampleui_tagClouds.png
  tests/UI/expected-screenshots/UIIntegrationTest_metric_tooltip.png
  tests/UI/expected-screenshots/ViewDataTableTest_subtables_loaded.png
  tests/UI/specs/UIIntegration_spec.js
Labels: not-in-changelog

#18260 Upgrade szymach/c-pchart from v2.0 to 3.0 to support PHP8.1
  composer.json
  composer.lock
  plugins/ImageGraph/StaticGraph.php
  plugins/ImageGraph/StaticGraph/Exception.php
  plugins/PrivacyManager/tests/Integration/PrivacyManagerTest.php
  tests/PHPUnit/Integration/ReleaseCheckListTest.php
Labels: not-in-changelog, Needs Review

#18259 Remove no longer needed version check for confirmPassword parameter in setSystemSettings API
  plugins/CorePluginsAdmin/API.php
Labels: not-in-changelog

#18265 [Vue] Make sure to use correct default params when building API requests in AjaxHelper.ts
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/AjaxHelper/AjaxHelper.ts
Labels: not-in-changelog

#18228 Show correct metrics in row evolution triggered from goal view tables
  plugins/API/API.php
  plugins/API/RowEvolution.php
  plugins/CoreHome/javascripts/dataTable_rowactions.js
  plugins/CoreHome/templates/getRowEvolutionPopover.twig
  plugins/Goals/tests/UI/GoalsPages_spec.js
  plugins/Goals/tests/UI/GoalsTable_spec.js
  plugins/Goals/tests/UI/expected-screenshots/GoalsPages_ecommerce.png
  plugins/Goals/tests/UI/expected-screenshots/GoalsPages_individual_goal.png
  plugins/Goals/tests/UI/expected-screenshots/GoalsPages_individual_goal_updated.png
  plugins/Goals/tests/UI/expected-screenshots/GoalsPages_individual_row_evolution.png
  plugins/Goals/tests/UI/expected-screenshots/GoalsPages_individual_row_evolution_reloaded.png
  plugins/Goals/tests/UI/expected-screenshots/GoalsPages_manage.png
  plugins/Goals/tests/UI/expected-screenshots/GoalsPages_overview.png
  plugins/Goals/tests/UI/expected-screenshots/GoalsPages_overview_row_evolution.png
  plugins/Goals/tests/UI/expected-screenshots/GoalsPages_overview_row_evolution_reloaded.png
  plugins/Goals/tests/UI/expected-screenshots/GoalsTable_goals_table_abandoned_carts.png
  plugins/Goals/tests/UI/expected-screenshots/GoalsTable_goals_table_ecommerce.png
  plugins/Goals/tests/UI/expected-screenshots/GoalsTable_goals_table_ecommerce_view.png
  plugins/Goals/tests/UI/expected-screenshots/GoalsTable_goals_table_full.png
  plugins/Goals/tests/UI/expected-screenshots/GoalsTable_goals_table_single.png
  plugins/Goals/tests/UI/expected-screenshots/GoalsTable_initial.png
  tests/UI/expected-screenshots/RowEvolution_row_evolution_goal_view.png
  tests/UI/expected-screenshots/RowEvolution_row_evolution_goal_view_reload.png
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
  tests/UI/expected-screenshots/UIIntegrationTest_goals_individual_row_evolution.png
  tests/UI/specs/RowEvolution_spec.js
  tests/UI/specs/UIIntegration_spec.js
Labels: not-in-changelog, Needs Review

#18269 Correct path for ignoring c-pchart docs
  tests/PHPUnit/Integration/ReleaseCheckListTest.php
Labels: not-in-changelog, Needs Review

#18263 Support downloading system tests from plugins
  plugins/CoreConsole/Commands/DevelopmentSyncProcessedSystemTests.php
Labels: Needs Review

#18271 [Vue] use jquery $destroy event instead of scope one
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/createAngularJsAdapter.ts
Labels: Needs Review

#18272 [Vue] add node version check to vue:build command
  plugins/CoreVue/Commands/Build.php
Labels: Needs Review

#18193 [Vue] migrate comparisons service + component
  .eslintrc.js
  jest.config.js
  package-lock.json
  package.json
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/angularjs/comparisons/comparisons.component.html
  plugins/CoreHome/angularjs/comparisons/comparisons.component.js
  plugins/CoreHome/angularjs/comparisons/comparisons.service.js
  plugins/CoreHome/angularjs/comparisons/comparisons.service.spec.js
  plugins/CoreHome/angularjs/reporting-menu/reportingmenu.controller.js
  plugins/CoreHome/javascripts/broadcast.js
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/AjaxHelper/AjaxHelper.ts
  plugins/CoreHome/vue/src/Comparisons/Comparisons.adapter.ts
  plugins/CoreHome/vue/src/Comparisons/Comparisons.less
  plugins/CoreHome/vue/src/Comparisons/Comparisons.store.instance.ts
  plugins/CoreHome/vue/src/Comparisons/Comparisons.store.spec.ts
  plugins/CoreHome/vue/src/Comparisons/Comparisons.store.ts
  plugins/CoreHome/vue/src/Comparisons/Comparisons.vue
  plugins/CoreHome/vue/src/ContentBlock/ContentBlock.vue
  plugins/CoreHome/vue/src/EnrichedHeadline/EnrichedHeadline.vue
  plugins/CoreHome/vue/src/Matomo/Matomo.adapter.ts
  plugins/CoreHome/vue/src/Matomo/Matomo.ts
  plugins/CoreHome/vue/src/MatomoDialog/MatomoDialog.vue
  plugins/CoreHome/vue/src/MatomoUrl/MatomoUrl.spec.ts
  plugins/CoreHome/vue/src/MatomoUrl/MatomoUrl.ts
  plugins/CoreHome/vue/src/Periods/Periods.adapter.ts
  plugins/CoreHome/vue/src/Periods/utilities.ts
  plugins/CoreHome/vue/src/Piwik/Piwik.adapter.ts
  plugins/CoreHome/vue/src/Piwik/Piwik.spec.ts
  plugins/CoreHome/vue/src/Piwik/Piwik.ts
  plugins/CoreHome/vue/src/PiwikUrl/PiwikUrl.adapter.ts
  plugins/CoreHome/vue/src/PiwikUrl/PiwikUrl.ts
  plugins/CoreHome/vue/src/Segmentation/Segments.store.ts
  plugins/CoreHome/vue/src/createAngularJsAdapter.ts
  plugins/CoreHome/vue/src/index.ts
  plugins/CoreVue/polyfills/src/index.ts
  plugins/CoreVue/types/index.d.ts
  plugins/SitesManager/tests/UI/SitesManager_spec.js
  tests/UI/expected-screenshots/Comparison_dashboard_last_period.png
  tests/UI/expected-screenshots/Comparison_dashboard_last_period_and_segment.png
  tests/UI/expected-screenshots/Comparison_visitors_overview.png
  tests/UI/expected-screenshots/Comparison_visitors_overview_segment_removed.png
  tests/UI/expected-screenshots/Comparison_visitors_overview_switched.png
  tests/UI/expected-screenshots/PeriodSelector_custom_comparison.png
  tests/UI/specs/Comparison_spec.js
  tests/angularjs/bootstrap.jest.js
  tsconfig.spec.json
Labels: Needs Review

#18278 Remove cache clearing from forget invalidations loop.
  core/Archive/ArchiveInvalidator.php
Labels: Needs Review

#18241 Take archive TTL time into consideration for today when browser archiving is enabled
  core/ArchiveProcessor/Loader.php
Labels: Needs Review

#18199 Mark IE11 as no longer supported browsers
  .browserslistrc
  core/SupportedBrowser.php
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/angularjs/iecheck.js
  plugins/CoreHome/lang/en.json
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreVue/polyfills/babel.config.js
  plugins/CoreVue/polyfills/dist/MatomoPolyfills.js
  plugins/CoreVue/polyfills/dist/MatomoPolyfills.min.js
  plugins/CoreVue/polyfills/dist/MatomoPolyfills.min.js.map
  plugins/ExampleVue/vue/dist/ExampleVue.umd.1.js
  plugins/ExampleVue/vue/dist/ExampleVue.umd.js
  plugins/ExampleVue/vue/dist/ExampleVue.umd.min.1.js
  plugins/ExampleVue/vue/dist/ExampleVue.umd.min.js
  plugins/Feedback/vue/dist/Feedback.umd.js
  plugins/Feedback/vue/dist/Feedback.umd.min.js
  tests/UI/specs/OptOutForm_spec.js
  tests/UI/specs/UIIntegration_spec.js
  tests/lib/screenshot-testing/run-tests.js
  tests/lib/screenshot-testing/support/globals.js
  tests/lib/screenshot-testing/support/page-renderer.js
Labels: Needs Review

#18213 [Vue] migrate date-picker and other period-selector related components
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/angularjs/date-picker/date-picker.directive.js
  plugins/CoreHome/angularjs/date-range-picker/date-range-picker.component.html
  plugins/CoreHome/angularjs/date-range-picker/date-range-picker.component.js
  plugins/CoreHome/angularjs/period-date-picker/period-date-picker.component.html
  plugins/CoreHome/angularjs/period-date-picker/period-date-picker.component.js
  plugins/CoreHome/angularjs/period-date-picker/period-date-picker.component.less
  plugins/CoreHome/angularjs/period-selector/period-selector.directive.html
  plugins/CoreHome/angularjs/selector/selector.directive.js
  plugins/CoreHome/stylesheets/selector.less
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/DatePicker/DatePicker.adapter.ts
  plugins/CoreHome/vue/src/DatePicker/DatePicker.vue
  plugins/CoreHome/vue/src/DateRangePicker/DateRangePicker.adapter.ts
  plugins/CoreHome/vue/src/DateRangePicker/DateRangePicker.less
  plugins/CoreHome/vue/src/DateRangePicker/DateRangePicker.vue
  plugins/CoreHome/vue/src/ExpandOnClick/ExpandOnClick.adapter.ts
  plugins/CoreHome/vue/src/ExpandOnClick/ExpandOnClick.ts
  plugins/CoreHome/vue/src/ExpandOnHover/ExpandOnHover.adapter.ts
  plugins/CoreHome/vue/src/ExpandOnHover/ExpandOnHover.ts
  plugins/CoreHome/vue/src/PeriodDatePicker/PeriodDatePicker.adapter.ts
  plugins/CoreHome/vue/src/PeriodDatePicker/PeriodDatePicker.vue
  plugins/CoreHome/vue/src/createAngularJsAdapter.ts
  plugins/CoreHome/vue/src/index.ts
  plugins/CoreVue/types/index.d.ts
Labels: Needs Review, Do not close

#18235 Changes to keep sorting order consistent across all PHP versions for Live.getLastVisitsDetails API
  plugins/Live/Visitor.php
Labels: Needs Review, Stale

#18257 Translations update from Weblate
  lang/pl.json
  lang/uk.json
  plugins/CoreAdminHome/lang/de.json
  plugins/CoreAdminHome/lang/pt.json
  plugins/CoreAdminHome/lang/tr.json
  plugins/CoreAdminHome/lang/uk.json
  plugins/CoreHome/lang/uk.json
  plugins/Ecommerce/lang/pt.json
  plugins/GeoIp2/lang/pt.json
  plugins/Goals/lang/pt.json
  plugins/Installation/lang/uk.json
  plugins/Login/lang/de.json
  plugins/MultiSites/lang/uk.json
  plugins/Referrers/lang/uk.json
  plugins/SegmentEditor/lang/uk.json
  plugins/SitesManager/lang/uk.json
  plugins/UserId/lang/de.json
  plugins/UsersManager/lang/uk.json
  plugins/VisitFrequency/lang/uk.json
Labels: c: i18n

#18284 [Vue] wait for angular to be initialized to post events to avoid loading race condition
  .github/workflows/buildvue.yml
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/Matomo/Matomo.ts
Labels: not-in-changelog

#18285 Ensure DNS records are only requested for IP allowlist when needed
  config/global.php
  plugins/CoreHome/tests/Integration/LoginAllowlistTest.php
Labels: not-in-changelog, Needs Review

#18288 Translations update from Hosted Weblate
  lang/eu.json
  plugins/CustomDimensions/lang/de.json
  plugins/Diagnostics/lang/de.json
  plugins/Installation/lang/de.json
  plugins/Login/lang/de.json
Labels: c: i18n

#18287 [Vue] Add support for scoped styles (though they will not be able to access theme variables).
  core/AssetManager/UIAssetFetcher/StylesheetUIAssetFetcher.php
  package-lock.json
  package.json
  plugins/ExampleVue/vue/dist/ExampleVue.umd.1.js
  plugins/ExampleVue/vue/dist/ExampleVue.umd.js
  plugins/ExampleVue/vue/dist/ExampleVue.umd.min.1.js
  plugins/ExampleVue/vue/dist/ExampleVue.umd.min.js
  plugins/ExampleVue/vue/dist/css/1.3373f545.css
  plugins/ExampleVue/vue/src/ExampleComponent/ExampleComponent.vue
Labels: Needs Review

#18286 [Vue] use .development suffix for watch files and gitignore them
  .gitignore
  core/AssetManager/UIAssetFetcher/JScriptUIAssetFetcher.php
  plugins/CoreVue/Commands/Build.php
Labels: Needs Review

#18293 Avoid further deprecation warnings on PHP 8.1
  plugins/GeoIp2/LocationProvider/GeoIp2/Php.php
Labels: not-in-changelog, Needs Review

#18296 [Vue] Cannot return IAngularEvent in $emit wrapper unfortunately.
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/Matomo/Matomo.adapter.ts
  plugins/CoreHome/vue/src/Matomo/Matomo.ts
  plugins/CoreVue/types/index.d.ts
Labels: Needs Review

#18289 Translations update from Hosted Weblate
  lang/fa.json
  lang/uk.json
  plugins/API/lang/uk.json
  plugins/Contents/lang/uk.json
  plugins/CoreAdminHome/lang/uk.json
  plugins/CoreHome/lang/uk.json
  plugins/CorePluginsAdmin/lang/uk.json
  plugins/CoreUpdater/lang/uk.json
  plugins/CustomDimensions/lang/uk.json
  plugins/CustomJsTracker/lang/uk.json
  plugins/DevicesDetection/lang/uk.json
  plugins/Events/lang/uk.json
  plugins/Feedback/lang/de.json
  plugins/Feedback/lang/el.json
  plugins/Feedback/lang/es-ar.json
  plugins/Feedback/lang/es.json
  plugins/Feedback/lang/fi.json
  plugins/Feedback/lang/fr.json
  plugins/Feedback/lang/it.json
  plugins/Feedback/lang/ja.json
  plugins/Feedback/lang/nl.json
  plugins/Feedback/lang/pt-br.json
  plugins/Feedback/lang/pt.json
  plugins/Feedback/lang/sq.json
  plugins/Feedback/lang/sv.json
  plugins/Feedback/lang/tr.json
  plugins/Feedback/lang/zh-cn.json
  plugins/Feedback/lang/zh-tw.json
  plugins/Goals/lang/uk.json
  plugins/Insights/lang/uk.json
  plugins/IntranetMeasurable/lang/uk.json
  plugins/Marketplace/lang/uk.json
  plugins/MobileAppMeasurable/lang/uk.json
  plugins/MultiSites/lang/uk.json
  plugins/Overlay/lang/uk.json
  plugins/ProfessionalServices/lang/uk.json
  plugins/Resolution/lang/uk.json
  plugins/Transitions/lang/uk.json
  plugins/UserCountryMap/lang/uk.json
  plugins/UserId/lang/uk.json
  plugins/UserLanguage/lang/uk.json
  plugins/VisitFrequency/lang/uk.json
  plugins/VisitTime/lang/uk.json
  plugins/Widgetize/lang/uk.json
Labels: c: i18n

#18243 fix concurrency archiving overview goals
  core/ArchiveProcessor/Loader.php
  core/ArchiveProcessor/LoaderLock.php
  core/Concurrency/Lock.php
  tests/PHPUnit/Integration/ArchiveProcessor/LoaderLockTest.php
  tests/PHPUnit/Integration/ArchiveTest.php
Labels: not-in-changelog, Needs Review

#18299 Updates device detector to new major version
  composer.json
  composer.lock
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_browserName__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_operatingSystemName__API.getSuggestedValuesForSegment.xml
  plugins/CustomDimensions/tests/System/expected/test___API.getSegmentsMetadata.xml
  plugins/CustomDimensions/tests/System/expected/test___Live.getLastVisitsDetails_year.xml
  plugins/DevicesDetection/tests/System/expected/test___DevicesDetection.getBrand_day.xml
  plugins/DevicesDetection/tests/System/expected/test___DevicesDetection.getModel_day.xml
  plugins/DevicesDetection/tests/System/expected/test___DevicesDetection.getType_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents__Live.getLastVisitsDetails_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Live.getLastVisitsDetails_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs_siteIdThree_TrackedUsingLogReplayWithFixedSiteId__Live.getLastVisitsDetails_range.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getReportPagesMetadata.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getSegmentsMetadata.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getWidgetMetadata.xml
Labels: Task, not-in-changelog, Needs Review

#18267 Decode goal top dimension values
  plugins/Goals/templates/_listTopDimension.twig
  plugins/Goals/tests/UI/expected-screenshots/GoalsPages_individual_goal.png
  plugins/Goals/tests/UI/expected-screenshots/GoalsPages_individual_goal_updated.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard2.png
Labels: Bug, Needs Review

#18302 Translations update from Hosted Weblate
  lang/de.json
  plugins/CoreAdminHome/lang/tr.json
  plugins/Feedback/lang/de.json
  plugins/Feedback/lang/el.json
  plugins/Feedback/lang/es-ar.json
  plugins/Feedback/lang/fr.json
  plugins/Feedback/lang/it.json
  plugins/Feedback/lang/ja.json
  plugins/Feedback/lang/pt-br.json
  plugins/Feedback/lang/pt.json
  plugins/Feedback/lang/sq.json
  plugins/Feedback/lang/tr.json
  plugins/Goals/lang/de.json
  plugins/SitesManager/lang/tr.json
Labels: c: i18n

#18225 [Vue] migrate notifications directive & service + UI.Notifications
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/angularjs/notification/notification.controller.js
  plugins/CoreHome/angularjs/notification/notification.directive.html
  plugins/CoreHome/angularjs/notification/notification.directive.js
  plugins/CoreHome/angularjs/notification/notification.service.js
  plugins/CoreHome/angularjs/reporting-menu/reportingmenu.controller.js
  plugins/CoreHome/javascripts/notification.js
  plugins/CoreHome/stylesheets/vue-transitions.less
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/AjaxHelper/AjaxHelper.ts
  plugins/CoreHome/vue/src/FocusIf/FocusIf.adapter.ts
  plugins/CoreHome/vue/src/FocusIf/FocusIf.ts
  plugins/CoreHome/vue/src/Menudropdown/Menudropdown.vue
  plugins/CoreHome/vue/src/Notification/Notification.adapter.ts
  plugins/CoreHome/vue/src/Notification/Notification.less
  plugins/CoreHome/vue/src/Notification/Notification.vue
  plugins/CoreHome/vue/src/Notification/NotificationGroup.vue
  plugins/CoreHome/vue/src/Notification/Notifications.store.adapter.ts
  plugins/CoreHome/vue/src/Notification/Notifications.store.ts
  plugins/CoreHome/vue/src/Notification/index.ts
  plugins/CoreHome/vue/src/createAngularJsAdapter.ts
  plugins/CoreHome/vue/src/index.ts
  plugins/CoreVue/types/index.d.ts
  plugins/Marketplace/tests/UI/Marketplace_spec.js
  plugins/UsersManager/angularjs/user-permissions-edit/user-permissions-edit.component.html
  plugins/UsersManager/tests/UI/UsersManager_spec.js
  tests/UI/specs/PeriodSelector_spec.js
  tests/UI/specs/UIIntegration_spec.js
Labels: Needs Review

#18308 Update Feedback Question banner
  plugins/CustomDimensions/tests/UI/CustomDimensions_spec.js
  plugins/Feedback/Feedback.php
  plugins/Feedback/tests/Integration/FeedbackTest.php
  plugins/Feedback/vue/src/FeedbackQuestion/FeedbackQuestion.less
  plugins/Installation/tests/UI/expected-screenshots/Installation_superuser_de.png
  plugins/Morpheus/fonts/selection.json
  tests/UI/expected-screenshots/UIIntegrationTest_actions_content_name_piece.png
  tests/UI/expected-screenshots/UIIntegrationTest_actions_content_piece.png
  tests/UI/specs/UIIntegration_spec.js
Labels: not-in-changelog, Needs Review

#18099 Proportional evolution comparison for incomplete periods
  core/API/DataTablePostProcessor.php
  core/Archive.php
  core/Archive/DataCollection.php
  core/Archive/DataTableFactory.php
  core/DataTable.php
  core/DataTable/DataTableInterface.php
  core/DataTable/Map.php
  plugins/CoreHome/Columns/Metrics/EvolutionMetric.php
  plugins/CoreHome/tests/Unit/EvolutionMetricTest.php
  plugins/MultiSites/API.php
  plugins/MultiSites/Columns/Metrics/EcommerceOnlyEvolutionMetric.php
  plugins/MultiSites/MultiSites.php
  plugins/MultiSites/angularjs/dashboard/dashboard-model.service.js
  plugins/MultiSites/angularjs/site/site.directive.html
  plugins/MultiSites/lang/en.json
  plugins/MultiSites/tests/Integration/ControllerTest.php
  plugins/MultiSites/tests/Integration/DashboardTest.php
  tests/PHPUnit/Integration/ArchiveTest.php
  tests/PHPUnit/System/TwoVisitorsTwoWebsitesDifferentDaysConversionsTest.php
  tests/PHPUnit/System/expected/test_BackwardsCompatibility1XTest__MultiSites.getAll_day.xml
  tests/PHPUnit/System/expected/test_ImportLogs__MultiSites.getAll_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__MultiSites.getOne_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs_withEnhancedAndLast7__MultiSites.getAll_month.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits__MultiSites.getAll_day.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits__MultiSites.getOne_day.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_Conversions_MultiSites.getAll_firstSite_lastN__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_Conversions__MultiSites.getAll_day.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_Conversions__MultiSites.getAll_month.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_Conversions__MultiSites.getAll_week.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_Conversions__MultiSites.getAll_year.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_Conversions_idSiteOne___MultiSites.getAll_day.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_Conversions_idSiteOne___MultiSites.getAll_month.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_Conversions_idSiteOne___MultiSites.getAll_week.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_Conversions_idSiteOne___MultiSites.getAll_year.xml
  tests/PHPUnit/System/expected/test_noVisit_PeriodIsLast__MultiSites.getOne_day.xml
  tests/PHPUnit/System/expected/test_noVisit_PeriodIsLast__MultiSites.getOne_week.xml
  tests/PHPUnit/System/expected/test_noVisit__MultiSites.getOne_day.xml
  tests/PHPUnit/System/expected/test_oneVisitor_oneWebsite_severalDays_DateRange_IndexedByDate__MultiSites.getAll_day.xml
  tests/PHPUnit/System/expected/test_oneVisitor_oneWebsite_severalDays_DateRange_MultipleDatesNotSupported__MultiSites.getAll_day.xml
  tests/PHPUnit/System/expected/test_oneVisitor_oneWebsite_severalDays_DateRange_Truncated__MultiSites.getAll_range.xml
  tests/PHPUnit/System/expected/test_oneVisitor_oneWebsite_severalDays_DateRange__MultiSites.getAll_range.xml
  tests/PHPUnit/System/expected/test_oneVisitor_oneWebsite_severalDays_DateRange__MultiSites.getOne_range.xml
  tests/PHPUnit/System/expected/test_oneVisitor_oneWebsite_severalDays_DateRange_showColumns__MultiSites.getAll_day.xml
Labels: not-in-changelog, Needs Review

#18315 Determine the first date to show feedback question banner more randomly
  core/Piwik.php
  plugins/Feedback/Feedback.php
Labels: not-in-changelog, Needs Review

#18280 Improvements to the in-app feature rating mechanism
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/MatomoDialog/MatomoDialog.vue
  plugins/Feedback/API.php
  plugins/Feedback/Feedback.php
  plugins/Feedback/lang/en.json
  plugins/Feedback/tests/UI/RateFeature_spec.js
  plugins/Feedback/tests/UI/expected-screenshots/RateFeature_rate_feature_dislike_questions.png
  plugins/Feedback/tests/UI/expected-screenshots/RateFeature_rate_feature_dislike_submit.png
  plugins/Feedback/tests/UI/expected-screenshots/RateFeature_rate_feature_like_questions.png
  plugins/Feedback/tests/UI/expected-screenshots/RateFeature_rate_feature_like_submit.png
  plugins/Feedback/vue/dist/Feedback.umd.js
  plugins/Feedback/vue/dist/Feedback.umd.min.js
  plugins/Feedback/vue/src/RateFeature/RateFeature.less
  plugins/Feedback/vue/src/RateFeature/RateFeature.vue
  plugins/Feedback/vue/src/ReviewLinks/ReviewLinks.less
  plugins/Feedback/vue/src/ReviewLinks/ReviewLinks.vue
  plugins/Feedback/vue/src/index.ts
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_2_segment_editor_update.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_3_segment_editor_edit_name.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_8_segment_editor_create.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_add_new_and_condition.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_add_new_or_condition.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_dimension_drag_drop.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_drag_and_condition.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_drag_or_condition.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_enabled_create_realtime_segments.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_saved_details.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_suggested_values.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_updated_details.png
  tests/UI/expected-screenshots/UIIntegrationTest_actions_pages_tooltip_help.png
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
Labels: not-in-changelog, Needs Review

#18309 Couple of fixes in QuickForm2 for PHP8.1 compatibility
  libs/HTML/QuickForm2/Container.php
  libs/HTML/QuickForm2/Controller.php
  libs/HTML/QuickForm2/Element/InputFile.php
  libs/HTML/QuickForm2/Element/Select.php
  libs/HTML/QuickForm2/Node.php
Labels: not-in-changelog, Needs Review

#18314 Fix some PHP8.1 deprecation warnings occurred while running tests
  core/API/Request.php
  core/Common.php
  core/DataArray.php
  core/DataTable/Renderer/Csv.php
  core/DataTable/Renderer/Xml.php
  core/Mail.php
  core/Metrics/Formatter.php
  core/Plugin.php
  core/Plugin/Dependency.php
  core/Tracker/Visit.php
  core/Url.php
  core/UrlHelper.php
  plugins/SitesManager/API.php
  plugins/UserCountry/Archiver.php
  tests/PHPUnit/System/expected/test_CustomEvents_Events.getCategory_flat__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_Events.getCategory_lastN__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_Events.getName_flat__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_Events.getName_lastN__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents__Events.getCategory_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents__Events.getCategory_month.xml
  tests/PHPUnit/System/expected/test_CustomEvents__Events.getName_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents__Events.getName_month.xml
  tests/PHPUnit/System/expected/test_CustomEvents_eventCategoryOrNameMatch__Events.getCategory_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_eventCategoryOrNameMatch__Events.getName_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_eventValueMatch__Events.getCategory_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_eventValueMatch__Events.getName_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_secondaryDimensionIsEventAction__Events.getCategory_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_secondaryDimensionIsEventAction__Events.getCategory_month.xml
  tests/PHPUnit/System/expected/test_CustomEvents_secondaryDimensionIsEventAction__Events.getName_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_secondaryDimensionIsEventAction__Events.getName_month.xml
  tests/PHPUnit/System/expected/test_CustomEvents_secondaryDimensionIsEventCategory__Events.getName_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_secondaryDimensionIsEventCategory__Events.getName_month.xml
  tests/PHPUnit/System/expected/test_CustomEvents_secondaryDimensionIsEventName__Events.getCategory_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_secondaryDimensionIsEventName__Events.getCategory_month.xml
  tests/PHPUnit/System/expected/test_CustomEvents_segmentMatchesEventActionPlay__Events.getCategory_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_segmentMatchesEventActionPlay__Events.getName_day.xml
Labels: not-in-changelog, Needs Review

#18319 Updated newsletter signup link
  plugins/UsersManager/lang/en.json
  plugins/UsersManager/tests/UI/expected-screenshots/UserSettings_load.png
  tests/UI/expected-screenshots/Menus_mobile_top.png
Labels: not-in-changelog, Needs Review

#18323 Fix for misaligned evolution trend icons
  plugins/MultiSites/angularjs/dashboard/dashboard.directive.less
  plugins/MultiSites/angularjs/site/site.directive.html
  plugins/MultiSites/lang/en.json
Labels: Bug, not-in-changelog, Needs Review

#18329 Hide feedback banner in zen mode
  plugins/CoreHome/stylesheets/zen-mode.less
Labels: not-in-changelog, Needs Review

#18334 [Vue] 4.6.0 fixes
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/EnrichedHeadline/EnrichedHeadline.vue
  plugins/Feedback/vue/dist/Feedback.umd.js
  plugins/Feedback/vue/dist/Feedback.umd.min.js
  plugins/Feedback/vue/src/FeedbackQuestion/FeedbackQuestion.adapter.ts
  plugins/Feedback/vue/src/FeedbackQuestion/FeedbackQuestion.vue
  plugins/Feedback/vue/src/RateFeature/RateFeature.vue
Labels: Needs Review

#18336 Fix random UI should change dashboard layout when new layout is selected
  plugins/Dashboard/tests/UI/Dashboard_spec.js
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_change_layout.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_rename.png
Labels: Needs Review

#18337 [Vue] detect dependent plugins in vue UMDs and order plugins appropriately
  .github/workflows/buildvue.yml
  core/AssetManager/UIAssetFetcher/JScriptUIAssetFetcher.php
  plugins/CoreHome/vue/dist/umd.metadata.json
  plugins/ExampleVue/vue/dist/umd.metadata.json
  plugins/Feedback/vue/dist/umd.metadata.json
  vue.config.js
Labels: Needs Review

#18341 [Vue] use jQuery click for expand on click
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/ExpandOnClick/ExpandOnClick.ts
Labels: Needs Review, Regression

#18342 [Vue] remove problematic pathspec in buildvue.yml
  .github/workflows/buildvue.yml
Labels: Needs Review

#18340 Fixes possible notice
  core/Http.php
Labels: not-in-changelog, Needs Review

#18348 Ensure password with special characters are working correctly when creating a token auth
  plugins/UsersManager/API.php
  plugins/UsersManager/tests/System/ApiTest.php
Labels: not-in-changelog, Needs Review

#18321 Sort segment static lists by usage
  core/Plugin/Dimension/VisitDimension.php
  core/Plugin/Segment.php
  plugins/API/API.php
  plugins/API/SegmentMetadata.php
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_browserName__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_countryName__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_operatingSystemName__API.getSuggestedValuesForSegment.xml
  plugins/DevicesDetection/Columns/BrowserName.php
  plugins/DevicesDetection/Columns/Os.php
  plugins/UserCountry/Columns/Country.php
Labels: not-in-changelog, Needs Review

#18345 Fix for incorrect multisite dashboard Urls behind reverse proxy
  plugins/MultiSites/angularjs/dashboard/dashboard.directive.html
  plugins/MultiSites/angularjs/site/site.controller.js
Labels: not-in-changelog, Needs Review

#18358 Allow console logging to file if configured
  plugins/Monolog/config/cli.php
Labels: not-in-changelog, Needs Review, Easier debugging

#18356 [Vue] do not decode model value of site name in site selector, so it is always matches the DB value
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/SiteSelector/SiteSelector.adapter.ts
  plugins/CoreHome/vue/src/SiteSelector/SiteSelector.vue
Labels: not-in-changelog

#18333 Cache API.getSegmentMetadata better in Segment
  core/ArchiveProcessor/LoaderLock.php
  core/Segment.php
Labels: not-in-changelog

#18364 Revert "[Vue] do not decode model value of site name in site selector, so it is always matches the DB value"
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/SiteSelector/SiteSelector.adapter.ts
  plugins/CoreHome/vue/src/SiteSelector/SiteSelector.vue
Labels: Needs Review

#18369 Improve Vue Build action
  .github/workflows/buildvue.yml
Labels: not-in-changelog, Needs Review, Better processes

#18357 Log archiving query timeouts
  core/DataAccess/ArchivingDbAdapter.php
Labels: not-in-changelog, Needs Review, Easier debugging

#18367 [Vue] in site selector execute search on searchTerm change rather than keydown
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/SiteSelector/SiteSelector.vue
  plugins/CoreHome/vue/src/SiteSelector/SitesStore.ts
Labels: Needs Review, Regression

#18252 Chrome isn't using WebKit anymore
  plugins/API/tests/System/expected/test_AutoSuggestAPITest__Live.getLastVisitsDetails_range.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment0_noOptions__Live.getLastVisitsDetails_day.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment0_noOptions__Live.getLastVisitsDetails_year.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment1_noOptions__Live.getLastVisitsDetails_day.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment1_noOptions__Live.getLastVisitsDetails_year.xml
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_removed.png
  plugins/DevicesDetection/functions.php
  plugins/PrivacyManager/tests/System/expected/anonymizeVisitInformation_allSitesAllDates.json
  plugins/PrivacyManager/tests/System/expected/anonymizeVisitInformation_anonymizeUserId.json
  plugins/PrivacyManager/tests/System/expected/anonymizeVisitInformation_restrictDate.json
  plugins/PrivacyManager/tests/System/expected/anonymizeVisitInformation_restrictSites.json
  plugins/PrivacyManager/tests/System/expected/exportDataSubject_allVisits.json
  plugins/PrivacyManager/tests/System/expected/exportDataSubject_oneVisitGiven.json
  plugins/PrivacyManager/tests/System/expected/test_allSites__Live.getLastVisitsDetails_year.xml
  plugins/PrivacyManager/tests/System/expected/test_allSites_noActions__Live.getLastVisitsDetails_year.xml
  tests/PHPUnit/System/expected/test_ImportLogs__DevicesDetection.getBrowserEngines_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Live.getLastVisitsDetails_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs_siteIdThree_TrackedUsingLogReplayWithFixedSiteId__Live.getLastVisitsDetails_range.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_Live.getLastVisitsDetails_sortAsc__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_Live.getLastVisitsDetails_sortByIdVisit__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_Live.getLastVisitsDetails_sortDesc__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_pageurlNotContainsSegment__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_siteSearchCategoryNotEqualsSegment__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_reportLimitingdimension_2_rankingQuery__CustomDimensions.getCustomDimension_day.xml
  tests/UI/expected-screenshots/Theme_home.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard1.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_software.png
Labels: c: Usability, Needs Review

#18330 Further improvements for PHP 8.1
  core/DataTable/Renderer/Xml.php
  core/NumberFormatter.php
  core/Tracker/PageUrl.php
  libs/Zend/Db/Adapter/Pdo/Abstract.php
  plugins/Actions/VisitorDetails.php
  plugins/Ecommerce/VisitorDetails.php
  plugins/Events/VisitorDetails.php
  plugins/Goals/Archiver.php
  tests/PHPUnit/Framework/TestRequest/ApiTestConfig.php
Labels: not-in-changelog, Needs Review

#18029 Fix System check widget shows wrong tooltip text
  core/Twig.php
  plugins/Installation/templates/getSystemCheckWidget.twig
Labels: not-in-changelog, Needs Review, Stale, Stale for long

#18326 Add option to specify the max number of websites to process by archiver.
  core/CronArchive.php
  core/CronArchive/QueueConsumer.php
  plugins/CoreConsole/Commands/CoreArchiver.php
  tests/PHPUnit/Integration/CronArchive/QueueConsumerTest.php
Labels: Needs Review

#18377 [Vue] fix modal notification placement
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/Notification/Notifications.store.ts
Labels: Needs Review, Regression

#18387 Improve password handling in SMTP configuration
  plugins/CoreAdminHome/Controller.php
  plugins/CoreAdminHome/templates/generalSettings.twig
Labels: c: Security, Needs Review

#18392 Include another local file if present in UI tests to allow extending the screenshot testing lib.
  tests/lib/screenshot-testing/.gitignore
  tests/lib/screenshot-testing/mocha-super-suite.js
Labels: not-in-changelog, Needs Review

#18391 Add option to allow skipping logic that exits w/ an error code if warnings are detected in the output
  core/Console.php
Labels: Needs Review

#18385 [Vue] date picker viewDate property is not kept up to date
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/PeriodDatePicker/PeriodDatePicker.vue
Labels: not-in-changelog, Needs Review, Regression

#18390 Use themed font family for input forms to override materialize.css styling
  plugins/Morpheus/stylesheets/general/_typography.less
Labels: c: Tests & QA

#18331 Translations update from Hosted Weblate
  lang/eu.json
  lang/fr.json
  lang/ja.json
  lang/nb.json
  plugins/API/lang/nb.json
  plugins/CoreAdminHome/lang/de.json
  plugins/CoreHome/lang/sr.json
  plugins/CustomJsTracker/lang/nb.json
  plugins/Dashboard/lang/eu.json
  plugins/Feedback/lang/de.json
  plugins/Feedback/lang/el.json
  plugins/Feedback/lang/fr.json
  plugins/Feedback/lang/tr.json
  plugins/MultiSites/lang/de.json
  plugins/MultiSites/lang/el.json
  plugins/MultiSites/lang/tr.json
  plugins/UserLanguage/lang/de.json
  plugins/UsersManager/lang/de.json
  plugins/UsersManager/lang/el.json
  plugins/UsersManager/lang/tr.json
Labels: c: i18n

#18406 Merge fixes made to latest release back
  core/Version.php
  plugins/CoreHome/stylesheets/zen-mode.less
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/EnrichedHeadline/EnrichedHeadline.vue
  plugins/CoreHome/vue/src/ExpandOnClick/ExpandOnClick.ts
  plugins/CoreHome/vue/src/Notification/Notifications.store.ts
  plugins/CoreHome/vue/src/PeriodDatePicker/PeriodDatePicker.vue
  plugins/Feedback/vue/dist/Feedback.umd.js
  plugins/Feedback/vue/dist/Feedback.umd.min.js
  plugins/Feedback/vue/src/FeedbackQuestion/FeedbackQuestion.adapter.ts
  plugins/Feedback/vue/src/FeedbackQuestion/FeedbackQuestion.vue
  plugins/Feedback/vue/src/RateFeature/RateFeature.vue
  plugins/MultiSites/angularjs/dashboard/dashboard.directive.less
  plugins/MultiSites/angularjs/site/site.directive.html
  plugins/MultiSites/lang/en.json
Labels: not-in-changelog, Needs Review

#18416 Fixed link to travis build in readme
  README.md
Labels: not-in-changelog

#18395 Move some code around to prevent possible error
  core/Plugin/Controller.php
Labels: not-in-changelog, Needs Review

#18355 Fix possible notice when comparing goal data
  plugins/Goals/API.php
Labels: not-in-changelog, Needs Review
