Repository matomo-org/matomo, pull requests merged in 2021-09, with the labels that each got.

#17936 fix mobile translation key
  lang/ar.json
  lang/cs.json
  lang/da.json
  lang/de.json
  lang/el.json
  lang/en.json
  lang/es-ar.json
  lang/es.json
  lang/fi.json
  lang/fr.json
  lang/id.json
  lang/it.json
  lang/ja.json
  lang/ko.json
  lang/nb.json
  lang/nl.json
  lang/pl.json
  lang/pt-br.json
  lang/pt.json
  lang/ro.json
  lang/ru.json
  lang/sl.json
  lang/sq.json
  lang/sr.json
  lang/sv.json
  lang/tr.json
  lang/uk.json
  lang/zh-cn.json
  lang/zh-tw.json
Labels: c: i18n

#17943 When processing a dependent archive for a range, then only process the requested plugin, not all plugins
  core/ArchiveProcessor/Rules.php
Labels: Needs Review

#17910 Expose methods to disable CSP or loosen it for embedded iframes
  core/View/SecurityPolicy.php
Labels: Needs Review, Stale

#17955 Provide SecurityPolicy method to allow embedded iframes to fetch their resources
  core/View/SecurityPolicy.php
  tests/PHPUnit/Unit/SecurityPolicyTest.php
Labels: Needs Review

#17949 try and reconnect database after running each scheduled task (at most once per two hours) during core:archive
  core/CronArchive.php
Labels: Needs Review

#17958 Allow more img sources when embedding page in an iframe
  core/View/SecurityPolicy.php
Labels: Needs Review

#17957 Fix auto completion in controller was not working for plugin for security policy
  core/Plugin/Controller.php
Labels: Needs Review

#17929 Simple fixes for PHP8.1
  core/ArchiveProcessor.php
  core/AssetManager/UIAssetCacheBuster.php
  core/Common.php
  core/DataTable/Filter/AddColumnsProcessedMetrics.php
  core/Translation/Translator.php
  core/Twig.php
Labels: Needs Review

#17879 Added config option for custom tracking image
  config/global.ini.php
  core/Tracker/Response.php
  tests/PHPUnit/Unit/Tracker/ResponseTest.php
Labels: not-in-changelog, Needs Review

#17900 show users more informative information on error
  core/Config.php
  core/View.php
  lang/en.json
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/angularjs/widget-loader/widgetloader.directive.html
  plugins/CoreHome/angularjs/widget-loader/widgetloader.directive.js
  plugins/CoreHome/templates/_indexContent.twig
  plugins/CoreHome/templates/getDefaultIndexView.twig
  plugins/Morpheus/templates/admin.twig
  plugins/Morpheus/templates/ajaxMacros.twig
Labels: not-in-changelog, Needs Review

#17928 Improve check for correctly set cookie by casting to string
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: not-in-changelog, Needs Review, Stale

#17967 Fix notice Undefined index in DataCollection
  core/Archive/DataCollection.php
Labels: Needs Review

#17963 Translations update from Weblate
  lang/bg.json
  lang/el.json
  lang/pt.json
  lang/ru.json
  lang/sq.json
  lang/tr.json
  plugins/API/lang/tr.json
  plugins/Contents/lang/tr.json
  plugins/CoreAdminHome/lang/it.json
  plugins/CoreAdminHome/lang/pt.json
  plugins/CorePluginsAdmin/lang/tr.json
  plugins/DBStats/lang/tr.json
  plugins/Dashboard/lang/tr.json
  plugins/DevicePlugins/lang/tr.json
  plugins/Events/lang/tr.json
  plugins/ImageGraph/lang/tr.json
  plugins/Insights/lang/tr.json
  plugins/IntranetMeasurable/lang/tr.json
  plugins/LanguagesManager/lang/tr.json
  plugins/Live/lang/tr.json
  plugins/Overlay/lang/tr.json
  plugins/PagePerformance/lang/tr.json
  plugins/Resolution/lang/tr.json
  plugins/SEO/lang/tr.json
  plugins/ScheduledReports/lang/tr.json
  plugins/UserId/lang/tr.json
  plugins/UserLanguage/lang/tr.json
  plugins/VisitFrequency/lang/tr.json
  plugins/VisitorInterest/lang/tr.json
  plugins/VisitsSummary/lang/tr.json
  plugins/WebsiteMeasurable/lang/tr.json
  plugins/Widgetize/lang/tr.json
Labels: c: i18n

#17974 Fix multiple conversion selection in edit goal form
  plugins/Goals/angularjs/manage-goals/manage-goals.controller.js
Labels: not-in-changelog, Needs Review

#17970 Fix failing UI tests
  plugins/Dashboard/tests/UI/DashboardManager_spec.js
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_create_new.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_users_opt_out_default.png
  plugins/SegmentEditor/tests/UI/SegmentSelectorEditor_spec.js
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard2.png
  tests/UI/specs/UIIntegration_spec.js
  tests/UI/specs/ViewDataTable_spec.js
  tests/lib/screenshot-testing/support/page-renderer.js
Labels: c: Tests & QA, not-in-changelog, Needs Review

#17983 Revert "Make password reset use a secure hash to create reset token"
  plugins/Login/PasswordResetter.php
  plugins/Login/tests/Integration/PasswordResetterTest.php
Labels: not-in-changelog

#17981 automatically wait for lazy images in UI tests
  tests/UI/specs/UIIntegration_spec.js
  tests/lib/screenshot-testing/support/page-renderer.js
Labels: c: Tests & QA, not-in-changelog, Needs Review

#17964 delete old log_* table data also without idvisit
  core/DataAccess/RawLogDao.php
  core/LogDeleter.php
  plugins/PrivacyManager/Model/DataSubjects.php
  plugins/PrivacyManager/tests/Integration/Model/DataSubjectsTest.php
Labels: not-in-changelog, Needs Review

#17979 add promotion for seo web vitals, add campaign for Heatmaps and Sessi…
  plugins/PagePerformance/Reports/Get.php
  plugins/PagePerformance/tests/UI/expected-screenshots/PagePerformance_load.png
  plugins/ProfessionalServices/ProfessionalServices.php
  plugins/ProfessionalServices/Promo.php
  plugins/ProfessionalServices/templates/promoSEOWebVitals.twig
  plugins/Referrers/Reports/GetSearchEngines.php
  tests/UI/expected-screenshots/Comparison_normal_table.png
  tests/UI/expected-screenshots/Comparison_normal_table_no_periods.png
  tests/UI/expected-screenshots/Comparison_normal_table_no_segments.png
  tests/UI/expected-screenshots/Comparison_subtables_loaded.png
  tests/UI/expected-screenshots/Comparison_subtables_paginate.png
  tests/UI/expected-screenshots/UIIntegrationTest_referrers_search_engines_keywords.png
Labels: not-in-changelog, Needs Review

#17992 Update doctrine cache to the right version
  composer.lock
Labels: Needs Review

#17985 Translations update from Weblate
  lang/de.json
  lang/fr.json
  lang/ku.json
  lang/pt.json
  plugins/CoreAdminHome/lang/pt.json
  plugins/CoreHome/lang/pt.json
  plugins/PrivacyManager/lang/de.json
Labels: c: i18n

#17915 #17812 Improve handling of NotSupportedBrowserException
  core/Exception/NotSupportedBrowserException.php
  core/ExceptionHandler.php
Labels: Needs Review

#17987 if not comparing, set show_limit_control to true for Evolution Report
  plugins/CoreVisualizations/Visualizations/JqplotGraph/Evolution.php
  tests/UI/expected-screenshots/Comparison_row_evolution.png
  tests/UI/expected-screenshots/UIIntegrationTest_goals_individual_row_evolution.png
Labels: not-in-changelog, Needs Review

#17956 Add CLI config:get and config:delete
  plugins/CoreAdminHome/Commands/ConfigDelete.php
  plugins/CoreAdminHome/Commands/ConfigGet.php
  plugins/CoreAdminHome/tests/Integration/Commands/ConfigDeleteTest.php
  plugins/CoreAdminHome/tests/Integration/Commands/ConfigGetTest.php
  plugins/CoreAdminHome/tests/Integration/Commands/SetConfigTest.php
Labels: Needs Review

#17901 Add piwik.js public api method setPagePerformanceTiming.
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  tests/javascript/index.php
Labels: not-in-changelog, Needs Review

#17934 add Kurdish language to Matomo
  config/global.ini.php
  tests/PHPUnit/System/expected/test_apiGetReportMetadata_year__LanguagesManager.getAvailableLanguageNames.xml
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: c: i18n

#18008 Translations update from Weblate
  lang/el.json
  lang/es.json
  lang/nb.json
  lang/tr.json
  plugins/API/lang/nb.json
  plugins/API/lang/nl.json
  plugins/API/lang/pt.json
  plugins/Actions/lang/nb.json
  plugins/Actions/lang/pt.json
  plugins/Actions/lang/zh-tw.json
  plugins/Annotations/lang/pt.json
  plugins/CoreAdminHome/lang/nb.json
  plugins/CoreAdminHome/lang/tr.json
  plugins/CoreHome/lang/nb.json
  plugins/CoreHome/lang/zh-tw.json
  plugins/CorePluginsAdmin/lang/pt.json
  plugins/CoreUpdater/lang/nb.json
  plugins/CoreUpdater/lang/pt.json
  plugins/Dashboard/lang/nb.json
  plugins/Dashboard/lang/pt.json
  plugins/DevicesDetection/lang/pt.json
  plugins/Installation/lang/nb.json
  plugins/Installation/lang/pt.json
  plugins/SitesManager/lang/nb.json
  plugins/SitesManager/lang/tr.json
  plugins/Transitions/lang/tr.json
  plugins/VisitTime/lang/nb.json
  plugins/VisitsSummary/lang/tr.json
Labels: c: i18n

#18016 cover $typeReferrer 'false' or '0' to filter
  js/piwik.min.js
  matomo.js
  piwik.js
  plugins/Referrers/API.php
Labels: not-in-changelog, Needs Review

#18015 Add option to pass phpunit filter directly when running tests using tests:run command
  plugins/TestRunner/Commands/TestsRun.php
Labels: not-in-changelog, Needs Review

#18018 Added note to config that MYSQLI isn't supported for max execution
  config/global.ini.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: not-in-changelog, Needs Review

#18017 only show_limit_control on Acquisition/Overview
  plugins/Referrers/Reports/GetReferrerType.php
  tests/UI/expected-screenshots/UIIntegrationTest_goals_individual_row_evolution.png
Labels: not-in-changelog, Needs Review

#18030 Always use secure randomness
  core/Common.php
  plugins/MobileMessaging/API.php
Labels: c: Security, Needs Review

#18033 Add ScheduledReportEmail class
  plugins/ScheduledReports/ReportEmailGenerator.php
  plugins/ScheduledReports/ScheduledReportEmail.php
Labels: Needs Review

#18021 Translations update from Weblate
  lang/el.json
  plugins/CoreAdminHome/lang/de.json
  plugins/CoreAdminHome/lang/nb.json
  plugins/MobileAppMeasurable/lang/zh-tw.json
  plugins/MultiSites/lang/zh-tw.json
  plugins/Overlay/lang/pt.json
  plugins/Referrers/lang/de.json
  plugins/ScheduledReports/lang/pt.json
  plugins/TwoFactorAuth/lang/pt.json
  plugins/UserCountry/lang/pt.json
  plugins/VisitFrequency/lang/pt.json
  plugins/VisitFrequency/lang/zh-tw.json
Labels: c: i18n

#18032 Optimise tables separately
  core/Db.php
Labels: Needs Review

#18023 Allow social & search definitions to be sourced locally
  config/global.ini.php
  plugins/Referrers/SearchEngine.php
  plugins/Referrers/Social.php
  plugins/Referrers/Tasks.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: Needs Review

#17920 Improves Overlay UI tests
  config/environment/ui-test.php
  plugins/Overlay/tests/UI/Overlay_spec.js
  plugins/Overlay/tests/UI/expected-screenshots/Overlay_framed_loaded.png
  plugins/Overlay/tests/UI/expected-screenshots/Overlay_loaded_from_actions.png
  plugins/Overlay/tests/UI/expected-screenshots/Overlay_loaded_with_segment.png
  plugins/Overlay/tests/UI/expected-screenshots/Overlay_page_link_clicks.png
  plugins/Overlay/tests/UI/expected-screenshots/Overlay_page_new_links.png
  plugins/Overlay/tests/UI/expected-screenshots/Overlay_row_evolution.png
  tests/PHPUnit/Fixtures/UITestFixture.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_settings_general.png
  tests/lib/screenshot-testing/support/page-renderer.js
Labels: c: Tests & QA, not-in-changelog, Needs Review

#18037 add warning about dropping support for users using IE
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/angularjs/iecheck.js
  plugins/CoreHome/lang/en.json
Labels: Needs Review

#18042 removed Mssql and pgsql
  config/global.ini.php
  core/Db/Adapter.php
  core/Db/Adapter/Pdo/Mssql.php
  core/Db/Adapter/Pdo/Pgsql.php
  core/Tracker/Db/Pdo/Pgsql.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: Needs Review

#18028 add heartbeat ping tab tracking
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: not-in-changelog, Needs Review

#18043 Update regex inline helper slashes can be escaped.
  plugins/CustomDimensions/lang/en.json
Labels: Needs Review

#18024 Check config file was written correctly
  core/Config.php
  tests/PHPUnit/Unit/ConfigTest.php
Labels: Needs Review

#18046 For login allow list add support for IPv6
  config/global.php
  plugins/CoreHome/tests/Integration/LoginAllowlistTest.php
Labels: Bug, Needs Review

#18040 Fix escaping of html attribute
  plugins/Diagnostics/Diagnostic/ForceSSLCheck.php
  plugins/Diagnostics/templates/force_ssl_link.twig
Labels: not-in-changelog, Needs Review

#18057 Remove travis secure variables
  .travis.yml
Labels: c: Tests & QA, not-in-changelog

#18002 add mysql row format dynamic option
  core/Db/Adapter/Mysqli.php
  core/Db/Adapter/Pdo/Mysql.php
  core/Db/AdapterInterface.php
  core/Db/Schema/Mysql.php
  core/Db/Settings.php
  core/DbHelper.php
  core/Updater/Migration/Db/CreateTable.php
  core/Updates/4.5.0-b1.php
  plugins/Installation/Controller.php
  tests/PHPUnit/Integration/Updater/Migration/Db/FactoryTest.php
Labels: not-in-changelog, Needs Review

#18047 Translations update from Weblate
  lang/el.json
  lang/ja.json
  lang/zh-cn.json
  lang/zh-tw.json
  plugins/Actions/lang/ja.json
  plugins/CoreAdminHome/lang/ja.json
  plugins/CoreHome/lang/de.json
  plugins/CoreHome/lang/el.json
  plugins/CoreHome/lang/ja.json
  plugins/CustomDimensions/lang/el.json
  plugins/CustomJsTracker/lang/ja.json
  plugins/CustomJsTracker/lang/nb.json
  plugins/DBStats/lang/ja.json
  plugins/Dashboard/lang/uk.json
  plugins/Ecommerce/lang/nb.json
  plugins/Events/lang/pt.json
  plugins/Insights/lang/nb.json
  plugins/Installation/lang/ja.json
  plugins/Login/lang/nb.json
  plugins/MobileAppMeasurable/lang/ja.json
  plugins/MobileMessaging/lang/nb.json
  plugins/PagePerformance/lang/nb.json
  plugins/PrivacyManager/lang/nb.json
  plugins/ProfessionalServices/lang/ja.json
  plugins/Referrers/lang/nb.json
  plugins/Resolution/lang/ja.json
  plugins/ScheduledReports/lang/ja.json
  plugins/SegmentEditor/lang/ja.json
  plugins/SegmentEditor/lang/nb.json
  plugins/Tour/lang/nb.json
  plugins/UserCountryMap/lang/ja.json
  plugins/UserCountryMap/lang/zh-cn.json
  plugins/UserCountryMap/lang/zh-tw.json
  plugins/UsersManager/lang/nb.json
  plugins/VisitFrequency/lang/ja.json
  plugins/VisitFrequency/lang/nb.json
  plugins/VisitsSummary/lang/ja.json
  plugins/VisitsSummary/lang/nb.json
  plugins/Widgetize/lang/ja.json
Labels: c: i18n

#18063 Disable http requests on config
  config/global.ini.php
  plugins/Diagnostics/Diagnostic/AbstractPrivateDirectories.php
  plugins/Diagnostics/lang/en.json
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: not-in-changelog, Needs Review

#18053 add last seen to the UserManager Api
  plugins/UsersManager/API.php
  plugins/UsersManager/UserAccessFilter.php
  plugins/UsersManager/tests/Integration/UsersManagerTest.php
  plugins/UsersManager/tests/System/ApiTest.php
Labels: not-in-changelog, Needs Review

#18050 update admin level, user manage text
  plugins/UsersManager/UsersManager.php
  plugins/UsersManager/angularjs/users-manager/users-manager.component.html
  plugins/UsersManager/lang/en.json
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_admin_view_admin_add_user_by_email.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_admin_view_admin_add_user_by_login.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_admin_view_admin_add_user_not_exists.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_admin_view_admin_load.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_permissions_bulk_access_set.png
Labels: not-in-changelog, Needs Review

#17989 A few more PHP8.1 fixes
  composer.lock
  core/DataTable.php
  core/DbHelper.php
  libs/Zend/Db/Statement/Pdo.php
  libs/Zend/Session/Namespace.php
  plugins/DevicePlugins/API.php
  plugins/MultiSites/API.php
  plugins/Referrers/VisitorDetails.php
  plugins/SEO/Metric/Alexa.php
  plugins/SEO/Metric/Bing.php
  plugins/SEO/Metric/DomainAge.php
  plugins/SEO/Metric/Google.php
  plugins/SEO/Metric/ProviderCache.php
  tests/PHPUnit/Integration/DbHelperTest.php
Labels: not-in-changelog, Needs Review

#18073 [Vue] fix generate vue component command (new subfolder organization was not updated there)
  plugins/CoreVue/Commands/GenerateVueComponent.php
Labels: not-in-changelog, Needs Review

#18078 When "average generation time" is zero, hide the sparkline and "Avg generation time" graphs metric from picker
  plugins/VisitsSummary/Reports/Get.php
Labels: not-in-changelog, Needs Review

#17998 Remove "add new segment" selector in segment editor
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_default.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_delete_visit_cancelled.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_delete_visit_cancelled_verified_no_data_deleted.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_delete_visit_confirmed.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_enrich_segment_by_ip.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_no_visits_found.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_uncheck_one_visit.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_visits_found.png
  plugins/SegmentEditor/angularjs/segment-generator/segmentgenerator.directive.less
  plugins/SegmentEditor/javascripts/Segmentation.js
  plugins/SegmentEditor/stylesheets/segmentation.less
  plugins/SegmentEditor/templates/_segmentSelector.twig
  plugins/SegmentEditor/tests/UI/SegmentSelectorEditor_spec.js
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_2_segment_editor_update.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_3_segment_editor_edit_name.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_6_segment_editor_different.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_6_segment_editor_droplist.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_8_segment_editor_create.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_add_new_and_condition.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_add_new_or_condition.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_dimension_drag_drop.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_drag_and_condition.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_drag_or_condition.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_enabled_create_realtime_segments.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_saved_details.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_suggested_values.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_updated_details.png
Labels: not-in-changelog, Needs Review

#18074 [Dev-2082] Update container factory to allow for sorting plugins
  core/Container/ContainerFactory.php
  tests/PHPUnit/Framework/TestingEnvironmentManipulator.php
  tests/PHPUnit/bootstrap.php
Labels: Needs Review

#18083 [Vue] add .eslintignore for IDEs that run the eslint CLI
  .eslintignore
  package.json
Labels: Needs Review

#18084 try to fix failing overlay ui test
  plugins/Overlay/tests/UI/Overlay_spec.js
Labels: c: Tests & QA, not-in-changelog
