Repository matomo-org/matomo, pull requests merged in 2021-04, with the labels that each got.

#17410 Fixes possible notice
  core/SupportedBrowser.php
Labels: Needs Review, not-in-changelog

#17409 Make profile export work in current session
  plugins/Live/javascripts/visitorProfile.js
Labels: Needs Review, not-in-changelog

#17416 better systemcheck error boxes
  plugins/Installation/stylesheets/systemCheckPage.less
Labels: Needs Review, c: Design / UI

#17413 Use exceptions to provide more context to warning logs in Row.php
  core/DataTable/Row.php
Labels: not-in-changelog

#17421 more markdown friendly system checks
  plugins/Diagnostics/tests/UI/expected-screenshots/Diagnostics_page.png
  plugins/Installation/templates/_systemCheckSection.twig
  plugins/Installation/tests/UI/expected-screenshots/Installation_system_check.png
Labels: Needs Review, Task

#17380 Show notification when there is raw data but no data
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/angularjs/common/services/periods.js
  plugins/CoreHome/angularjs/common/services/periods.spec.js
  plugins/CoreHome/angularjs/reporting-menu/reportingmenu-model.js
  plugins/CoreHome/angularjs/reporting-page/reportingpage.controller.js
  plugins/CoreHome/angularjs/reporting-page/reportingpage.directive.html
  plugins/CoreHome/lang/en.json
  tests/PHPUnit/Fixtures/OneVisit.php
  tests/UI/expected-screenshots/OnlyRawDataNotification_show_notification_when_only_raw_data_exists.png
  tests/UI/specs/OnlyRawDataNotification_spec.js
Labels: not-in-changelog

#17426 Display French Guiana as separate country on map
  plugins/UserCountryMap/svg/SA.svg
  plugins/UserCountryMap/svg/world.svg
Labels: not-in-changelog

#17348 Set width for calendar
  plugins/CoreHome/angularjs/period-selector/period-selector.directive.html
  plugins/CoreHome/angularjs/period-selector/period-selector.directive.less
  tests/UI/expected-screenshots/PeriodSelector_comparison_checked.png
  tests/UI/expected-screenshots/PeriodSelector_custom_comparison.png
  tests/UI/expected-screenshots/PeriodSelector_date_range_selected.png
  tests/UI/expected-screenshots/PeriodSelector_day_selected.png
  tests/UI/expected-screenshots/PeriodSelector_expanded.png
  tests/UI/expected-screenshots/PeriodSelector_month_changed.png
  tests/UI/expected-screenshots/PeriodSelector_month_selected.png
  tests/UI/expected-screenshots/PeriodSelector_range_picker_displayed.png
  tests/UI/expected-screenshots/PeriodSelector_week_selected.png
  tests/UI/expected-screenshots/PeriodSelector_year_changed.png
  tests/UI/expected-screenshots/PeriodSelector_year_selected.png
Labels: Needs Review, not-in-changelog

#17436 Escape URL in geolocation admin error message
  plugins/GeoIp2/GeoIP2AutoUpdater.php
Labels: c: Security

#17440 speed up integration tests by not using DbHelper::getTablesInstalled()
  tests/PHPUnit/Framework/TestCase/SystemTestCase.php
Labels: c: Tests & QA, not-in-changelog

#17437 Do not allow setting partial archives to DONE_INVALIDATED
  core/DataAccess/Model.php
  tests/PHPUnit/Integration/DataAccess/ArchiveInvalidatorTest.php
Labels: Needs Review

#17333 Add event tags to top and bottom of body
  plugins/Morpheus/templates/layout.twig
Labels: Needs Review

#17439 Fixes for specific case when partial archives have to initiate archiving for child archives
  core/ArchiveProcessor/Loader.php
  core/ArchiveProcessor/Rules.php
  core/DataAccess/ArchiveSelector.php
  core/DataAccess/ArchiveWriter.php
  plugins/CoreConsole/tests/System/ArchiveCronTest.php
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_singleMetric__ExamplePlugin.getExampleArchivedMetric_day.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_singleMetric__ExamplePlugin.getExampleArchivedMetric_week.xml
  plugins/ExamplePlugin/Archiver.php
  tests/PHPUnit/Framework/TestCase/IntegrationTestCase.php
  tests/PHPUnit/Framework/TestCase/SystemTestCase.php
  tests/PHPUnit/Integration/ArchiveProcessor/LoaderTest.php
  tests/PHPUnit/Integration/DataAccess/ArchiveSelectorTest.php
  tests/PHPUnit/Integration/DataAccess/ArchiveWriterTest.php
Labels: Needs Review, not-in-changelog

#17449 Fix some UI tests
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_create_new.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_reset.png
  plugins/Diagnostics/tests/UI/expected-screenshots/Diagnostics_page.png
  plugins/SEO/tests/Integration/SEOTest.php
  plugins/UserCountryMap/svg/world.svg
  plugins/UserCountryMap/tests/UI/expected-screenshots/VisitorMap_avg_time_on_site.png
  plugins/UserCountryMap/tests/UI/expected-screenshots/VisitorMap_bounce_rate.png
  plugins/UsersManager/tests/UI/UsersManager_spec.js
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard3.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitor_profile_popup.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_locations_provider.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_realtime_map.png
  tests/UI/expected-screenshots/enable_framed_pages_embed_whole_app.png
Labels: c: Tests & QA, not-in-changelog

#17448 fix typo in cache:clear
  plugins/CoreConsole/Commands/ClearCaches.php
Labels: not-in-changelog

#17446 Dont load unneeded images
  plugins/Feedback/angularjs/feedback-popup/review-links.directive.html
Labels: not-in-changelog

#17447 Allow processing segments X days before last edit day
  config/global.ini.php
  core/CronArchive/SegmentArchiving.php
  tests/PHPUnit/Integration/CronArchive/SegmentArchivingTest.php
Labels: Needs Review

#17453 fix random failure + update two screenshots
  tests/PHPUnit/System/BlobReportLimitingTest.php
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_realtime_visits.png
Labels: c: Tests & QA, not-in-changelog

#17455 update expected screenshots
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_settings_general.png
Labels: not-in-changelog

#17427 Performance timing API as default
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: not-in-changelog

#17445 Ensure correct no access message is shown
  core/Access.php
  plugins/IntranetMeasurable/tests/UI/IntranetMeasurable_spec.js
  plugins/Login/tests/UI/NoAccess_spec.js
  plugins/Login/tests/UI/expected-screenshots/NoAccess_login_noaccess.png
  plugins/Login/tests/UI/expected-screenshots/NoAccess_login_session_timeout.png
Labels: Bug

#17458 Rearchive segment only when definition changed
  plugins/SegmentEditor/API.php
Labels: Needs Review, not-in-changelog

#17460 add some assertions for segment rearchive so there is test coverage
  plugins/SegmentEditor/tests/Integration/SegmentEditorTest.php
Labels: Needs Review, c: Tests & QA, not-in-changelog

#17464 Allow generating reports in TSV format
  core/ReportRenderer.php
  core/ReportRenderer/Tsv.php
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_in_tsv__ScheduledReports.generateReport_week.original.tsv
  plugins/ScheduledReports/ScheduledReports.php
  plugins/ScheduledReports/config/config.php
  plugins/ScheduledReports/templates/_addReport.twig
  plugins/ScheduledReports/templates/_listReports.twig
  tests/PHPUnit/Framework/TestCase/SystemTestCase.php
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_in_tsv__ScheduledReports.generateReport_month.original.tsv
Labels: Needs Review, not-in-changelog

#17461 Add get-segment-sql development command for debugging
  plugins/CoreConsole/Commands/GetSegmentSql.php
  plugins/SitesManager/Model.php
Labels: Needs Review

#17467 Set online guide url for User Id reports
  plugins/CustomDimensions/tests/System/expected/test___API.getReportMetadata_day.xml
  plugins/UserId/Reports/Base.php
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getGlossaryReports.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getReportMetadata_day.xml
Labels: Needs Review, not-in-changelog

#17470 Avoid double encoding page titles
  plugins/Live/templates/getLastVisitsStart.twig
Labels: Needs Review, not-in-changelog

#17473 use rawSafeDecoded filter
  plugins/Live/templates/getLastVisitsStart.twig
Labels: Needs Review, not-in-changelog

#17477 Add comment about using shop@innocraft.com for premium features
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Needs Review

#17475 Remove urlencode for segment definitions
  core/Archive.php
  core/CronArchive.php
  core/CronArchive/QueueConsumer.php
  core/CronArchive/SegmentArchiving.php
  core/DataAccess/Model.php
  plugins/SegmentEditor/API.php
  tests/PHPUnit/Integration/Archive/ArchivePurgerTest.php
  tests/PHPUnit/Integration/CronArchiveTest.php
Labels: Needs Review, not-in-changelog

#17456 show period label on evo graph
  plugins/CoreHome/javascripts/dataTable.js
  plugins/CoreHome/stylesheets/dataTable/_dataTable.less
  plugins/CoreHome/templates/_dataTableActions.twig
  plugins/CustomDimensions/tests/UI/expected-ui-screenshots/CustomDimensions_report_action_subtable_rowevolution.png
  plugins/CustomDimensions/tests/UI/expected-ui-screenshots/CustomDimensions_report_actions_rowevolution.png
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_widget_preview.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_rowevolution.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_widget_maximise.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_widget_unmaximise.png
  plugins/Overlay/tests/UI/expected-screenshots/Overlay_row_evolution.png
  plugins/PagePerformance/tests/UI/expected-screenshots/PagePerformance_pagetitle_overlay.png
  plugins/PagePerformance/tests/UI/expected-screenshots/PagePerformance_pageurl_overlay.png
  tests/UI/expected-screenshots/Comparison_multi_row_evolution.png
  tests/UI/expected-screenshots/EvolutionGraph_annotation_edit_form.png
  tests/UI/expected-screenshots/EvolutionGraph_annotation_edit_submit.png
  tests/UI/expected-screenshots/EvolutionGraph_annotation_starred.png
  tests/UI/expected-screenshots/EvolutionGraph_annotations_all.png
  tests/UI/expected-screenshots/EvolutionGraph_annotations_none.png
  tests/UI/expected-screenshots/EvolutionGraph_annotations_single_period.png
  tests/UI/expected-screenshots/EvolutionGraph_bounce_rate.png
  tests/UI/expected-screenshots/EvolutionGraph_initial.png
  tests/UI/expected-screenshots/EvolutionGraph_label_ticks_cutout.png
  tests/UI/expected-screenshots/EvolutionGraph_limit_changed.png
  tests/UI/expected-screenshots/EvolutionGraph_metric_picker_shown.png
  tests/UI/expected-screenshots/EvolutionGraph_new_annotation_form.png
  tests/UI/expected-screenshots/EvolutionGraph_new_annotation_submit.png
  tests/UI/expected-screenshots/EvolutionGraph_one_series.png
  tests/UI/expected-screenshots/EvolutionGraph_periods_list.png
  tests/UI/expected-screenshots/EvolutionGraph_periods_selected.png
  tests/UI/expected-screenshots/EvolutionGraph_table_actions.png
  tests/UI/expected-screenshots/EvolutionGraph_two_metrics.png
  tests/UI/expected-screenshots/RowEvolution_multirow_evolution.png
  tests/UI/expected-screenshots/RowEvolution_multirow_evolution_other_metric.png
  tests/UI/expected-screenshots/RowEvolution_row_evolution.png
  tests/UI/expected-screenshots/RowEvolution_row_evolution_ecommerce_item.png
  tests/UI/expected-screenshots/RowEvolution_row_evolution_multiple_series.png
  tests/UI/expected-screenshots/RowEvolution_row_evolution_other_metric.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard5_mobile.png
  tests/UI/expected-screenshots/UIIntegrationTest_goals_individual_row_evolution.png
  tests/UI/expected-screenshots/UIIntegrationTest_widgets_listing.png
Labels: Needs Review, not-in-changelog

#17478 Use full segment data to rearchive segment
  plugins/SegmentEditor/API.php
  plugins/SegmentEditor/tests/Integration/SegmentEditorTest.php
Labels: Needs Review, Regression, not-in-changelog

#17480 Do not use DbHelper::getTablesInstalled() in integration test setup …
  tests/PHPUnit/Framework/TestCase/SystemTestCase.php
Labels: Needs Review, c: Tests & QA, not-in-changelog

#17483 Do not parse plugin details with angular in marketplace overlay
  plugins/Marketplace/templates/plugin-details.twig
Labels: Needs Review, not-in-changelog

#17492 Improve method to determine date to archive segments from
  core/CronArchive/SegmentArchiving.php
  tests/PHPUnit/Integration/CronArchive/SegmentArchivingTest.php
Labels: Needs Review, Regression, not-in-changelog

#17494 Fix OneClickUpdate UI test
  tests/UI/specs/OneClickUpdate_spec.js
Labels: c: Tests & QA, not-in-changelog

#17491 Updates library pear/archive_tar
  composer.lock
Labels: Needs Review, not-in-changelog

#17485 Add new update to make sure deleted segments also have a computed hash.
  core/Updates/4.3.0-b4.php
  core/Version.php
Labels: Needs Review, not-in-changelog

#17490 Add diagnostic that checks if server directories that should be private are accessible
  plugins/Diagnostics/Diagnostic/RequiredPrivateDirectories.php
  plugins/Diagnostics/config/config.php
  plugins/Diagnostics/lang/en.json
  plugins/Diagnostics/tests/UI/expected-screenshots/Diagnostics_page.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_home.png
  tests/UI/expected-screenshots/UIIntegrationTest_api_error.png
Labels: Needs Review

#17496 work around group_concat max len being too small in ArchiveSelector.getArchiveIds
  core/DataAccess/ArchiveSelector.php
  tests/PHPUnit/Integration/DataAccess/ArchiveSelectorTest.php
Labels: Bug, Needs Review

#17504 Link to the Matomo font guide
  plugins/Morpheus/fonts/README.md
Labels: Needs Review

#17505 Fix determine segment rearchive date
  core/CronArchive/SegmentArchiving.php
  tests/PHPUnit/Integration/CronArchive/SegmentArchivingTest.php
Labels: Needs Review, Regression, not-in-changelog
