Repository matomo-org/matomo, pull requests merged in 2021-08, with the labels that each got.

#17835 Fix sorting of Geolocation providers
  plugins/UserCountry/LocationProvider.php
  plugins/UserCountry/tests/Integration/LocationProviderTest.php
  tests/PHPUnit/Framework/Mock/LocationProvider.php
Labels: Bug, Needs Review, Regression

#17808 Ensure to use correct default value for segment in scheduled reports
  plugins/ScheduledReports/angularjs/manage-scheduled-report/manage-scheduled-report.controller.js
  tests/UI/expected-screenshots/UIIntegrationTest_email_reports_editor.png
Labels: not-in-changelog

#17689 [PHP 8.1 compatibility] don't pass null to PDOStatement::fetch()
  libs/Zend/Db/Statement/Pdo.php
Labels: Do not close, Task

#17849 Scheduled tasks: Always read timetable from the database and not from…
  core/Scheduler/Scheduler.php
  core/Scheduler/Timetable.php
Labels: Needs Review

#17848 Fix long failing UI tests
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_permissions_bulk_access_set.png
  tests/UI/expected-screenshots/UIIntegrationTest_invalid_idsite_superuser.png
Labels: Needs Review, not-in-changelog

#17854 Fix transition popover for page titles
  plugins/Transitions/javascripts/transitions.js
Labels: Needs Review, not-in-changelog

#17801 If visit local time is null do not fail in report fetch API method
  plugins/VisitTime/functions.php
Labels: not-in-changelog

#17828 updates composer dependencies
  composer.lock
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_in_pdf_tables_only__ScheduledReports.generateReport_week.original.pdf
  plugins/Referrers/tests/System/expected/test_phpSerialized__Referrers.getReferrerType_year.original
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_in_pdf_tables_only__ScheduledReports.generateReport_month.original.pdf
  tests/PHPUnit/System/expected/test_reportLimitingdimension_2__CustomDimensions.getCustomDimension_day.xml
  tests/PHPUnit/System/expected/test_reportLimitingdimension_2_flattened__CustomDimensions.getCustomDimension_day.xml
  tests/PHPUnit/System/expected/test_reportLimitingdimension_2_rankingQuery__CustomDimensions.getCustomDimension_day.xml
Labels: Task, not-in-changelog

#17809 Set proper permissions for github actions
  .github/workflows/buildtrackerjs.yml
  .github/workflows/follow-up-reviews.yml
  .github/workflows/inactive-prs-closing-message.yaml
  .github/workflows/inactive-prs.yaml
  .github/workflows/phpcs.yml
  .github/workflows/submodules.yml
  .github/workflows/translations.yml
Labels: Needs Review, c: Security, not-in-changelog

#17857 Action permissions can't be set on step level
  .github/workflows/buildtrackerjs.yml
  .github/workflows/submodules.yml
  .github/workflows/translations.yml
Labels: Regression, not-in-changelog

#17867 Do not log a failed login if a valid app token_auth is sent
  core/Access.php
Labels: Needs Review

#17869 Fix a couple a possible warnings in PHP 8.1
  core/Access.php
  core/AssetManager/UIAssetCacheBuster.php
  plugins/GeoIp2/LocationProvider/GeoIp2/Php.php
  plugins/Referrers/Columns/Base.php
  plugins/Referrers/SearchEngine.php
Labels: Needs Review

#17846 Remove checking for /proc existence
  core/CliMulti/Process.php
Labels: Needs Review

#17736 avoid large amounts of notifications being added to the session
  core/Db/Schema/Mysql.php
  core/Notification/Manager.php
  core/Session.php
  core/Session/SaveHandler/DbTable.php
  core/Session/SessionAuth.php
  core/Updates/4.5.0-b1.php
  core/Version.php
  plugins/Monolog/Handler/WebNotificationHandler.php
  tests/PHPUnit/Framework/Fixture.php
  tests/PHPUnit/Integration/Session/SaveHandler/DbTableTest.php
  tests/PHPUnit/Unit/Notification/ManagerTest.php
Labels: not-in-changelog

#17798 Set CSP header to prevent XSS
  config/global.ini.php
  core/Plugin/Controller.php
  core/View.php
  core/View/SecurityPolicy.php
  tests/PHPUnit/Unit/SecurityPolicyTest.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: Needs Review

#17874 before trying to invalidate parent period, make sure period is enabled in INI config
  config/global.ini.php
  core/Archive/ArchiveInvalidator.php
  core/CronArchive.php
  core/CronArchive/QueueConsumer.php
  core/Period/Factory.php
  tests/PHPUnit/Integration/CronArchive/QueueConsumerTest.php
  tests/PHPUnit/Integration/DataAccess/ArchiveInvalidatorTest.php
Labels: not-in-changelog, Needs Review

#17851 add token_auth to overlay requests where necessary
  core/View.php
  plugins/Annotations/javascripts/annotations.js
  plugins/CoreHome/angularjs/common/services/piwik-api.js
  plugins/CoreHome/angularjs/widget-loader/widgetloader.directive.js
  plugins/CoreHome/javascripts/broadcast.js
  plugins/CoreHome/javascripts/dataTable_rowactions.js
  plugins/Live/javascripts/SegmentedVisitorLog.js
  plugins/Live/javascripts/visitorProfile.js
  plugins/Overlay/javascripts/Overlay_Helper.js
  plugins/Overlay/javascripts/Piwik_Overlay.js
  plugins/Overlay/templates/index.twig
  plugins/Overlay/templates/index_noframe.twig
Labels: Needs Review

#17893 Skip max execution query hint test for Mysqli
  tests/PHPUnit/Integration/DataAccess/LogAggregatorTest.php
Labels: c: Tests & QA, not-in-changelog

#17886 Fix possible notices
  core/DataAccess/Model.php
  plugins/SegmentEditor/Model.php
Labels: not-in-changelog, Needs Review

#16897 Run AllTests on PHP8
  .travis.yml
  core/DataTable/Filter/RangeCheck.php
  plugins/CoreAdminHome/tests/Integration/APITest.php
  plugins/CustomDimensions/tests/Integration/Dimension/DimensionTest.php
  plugins/CustomDimensions/tests/Integration/Dimension/ExtractionTest.php
  plugins/CustomJsTracker/tests/Integration/FileTest.php
  plugins/CustomJsTracker/tests/Integration/TrackerUpdaterTest.php
  plugins/Goals/tests/Integration/APITest.php
  plugins/Login/tests/Integration/PasswordVerifierTest.php
  plugins/MobileMessaging/ReportRenderer/Sms.php
  plugins/Monolog/tests/Unit/Processor/ExceptionToTextProcessorTest.php
  plugins/Referrers/tests/System/ApiTest.php
  plugins/Referrers/tests/System/expected/test_phpSerialized8__Referrers.getReferrerType_year.original
  plugins/ScheduledReports/tests/Integration/ApiTest.php
  plugins/ScheduledReports/tests/Integration/ReportEmailGenerator/AttachedFileReportEmailGeneratorTest.php
  plugins/SitesManager/tests/Integration/SitesManagerTest.php
  plugins/TwoFactorAuth/tests/Integration/TwoFactorAuthTest.php
  plugins/UserCountry/tests/Integration/APITest.php
  plugins/UsersManager/UserAccessFilter.php
  plugins/UsersManager/tests/Integration/UsersManagerTest.php
  tests/PHPUnit/Fixtures/InvalidVisits.php
  tests/PHPUnit/Framework/TestCase/SystemTestCase.php
  tests/PHPUnit/Framework/TestRequest/Response.php
  tests/PHPUnit/Integration/DataAccess/LogAggregatorTest.php
  tests/PHPUnit/Integration/DbTest.php
  tests/PHPUnit/Integration/HttpTest.php
  tests/PHPUnit/Integration/ReleaseCheckListTest.php
  tests/PHPUnit/System/BackwardsCompatibility1XTest.php
  tests/PHPUnit/System/ConsoleTest.php
Labels: c: Tests & QA, Needs Review

#17865 Test Config::getBool() for clarity of configuration options
  tests/PHPUnit/Unit/Config/ConfigTest.php
  tests/PHPUnit/Unit/Config/test_files/boolean_settings_test.ini.php
Labels: Needs Review

#17817 When aggregating reports, inflate one expanded datatable at a time
  core/Archive.php
  core/Archive/DataCollection.php
  core/Archive/DataTableFactory.php
  core/ArchiveProcessor.php
  core/DataTable.php
  core/DataTable/Manager.php
  core/DataTable/Row.php
  plugins/Contents/tests/System/expected/test_Contents__Actions.getPageUrls_month.xml
  plugins/Diagnostics/tests/Integration/Commands/AnalyzeArchiveTableTest.php
  plugins/Transitions/tests/UI/expected-screenshots/Transitions_transitions_report_switch_url.png
  plugins/UserCountry/tests/System/expected/test_multi_sites__UserCountry.getCity_month.xml
  tests/PHPUnit/System/expected/test_CustomEvents__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_flat__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_invertCompare__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_multipleSites_multipleCompare__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_periods__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_rangePeriodAgainstSingle__Actions.getPageUrls_range.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_segmentsAndPeriods__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_segments__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_subtableActions__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getEntryPageTitles_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getEntryPageTitles_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getEntryPageUrls_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getEntryPageUrls_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getExitPageTitles_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getExitPageTitles_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getExitPageUrls_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getExitPageUrls_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getPageTitles_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getPageTitles_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getPageUrls_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs_siteIdThree_TrackedUsingLogReplayWithFixedSiteId__Actions.getEntryPageTitles_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs_siteIdThree_TrackedUsingLogReplayWithFixedSiteId__Actions.getEntryPageUrls_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs_siteIdThree_TrackedUsingLogReplayWithFixedSiteId__Actions.getExitPageTitles_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs_siteIdThree_TrackedUsingLogReplayWithFixedSiteId__Actions.getExitPageUrls_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs_siteIdThree_TrackedUsingLogReplayWithFixedSiteId__Actions.getPageTitles_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs_siteIdThree_TrackedUsingLogReplayWithFixedSiteId__Actions.getPageUrls_range.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest__UserCountry.getCity_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_segment_city__UserCountry.getCity_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_segment_region__UserCountry.getCity_month.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__Actions.getPageTitles_month.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__Actions.getPageTitles_week.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__Actions.getPageTitles_year.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__Actions.getPageUrls_week.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__Actions.getPageUrls_year.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idSiteOne___Actions.getPageTitles_month.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idSiteOne___Actions.getPageTitles_week.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idSiteOne___Actions.getPageTitles_year.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idSiteOne___Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idSiteOne___Actions.getPageUrls_week.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idSiteOne___Actions.getPageUrls_year.xml
  tests/PHPUnit/Unit/DeprecatedMethodsTest.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: Needs Review

#17891 Ignore overwrite subtable warning for summary rows for old data…
  core/Archive/DataTableFactory.php
  core/DataTable/Row.php
Labels: Needs Review

#17905 Update cache component
  composer.lock
Labels: Needs Review

#17895 remove acceptedValues from PageUrl
  plugins/Actions/Columns/PageUrl.php
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getSegmentsMetadata.xml
Labels: not-in-changelog

#17877 Only set requests in tracking request set when correct value is given
  core/Tracker/RequestSet.php
Labels: Needs Review

#17855 Use Monolog:SyslogHandler syslog default facility
  plugins/Monolog/config/config.php
Labels: Needs Review

#17918 If a usable archive exists and the invalidation is for a specific plugin, delete the invalidation
  core/CronArchive/QueueConsumer.php
  tests/PHPUnit/Integration/CronArchive/QueueConsumerTest.php
Labels: not-in-changelog, Needs Review

#17930 use list of supported languages from config
  config/global.ini.php
  plugins/LanguagesManager/API.php
Labels: c: i18n

#17933 Weblate contributions
  lang/fr.json
  lang/nb.json
  plugins/CoreUpdater/lang/nb.json
  plugins/DevicesDetection/lang/nb.json
  plugins/VisitTime/lang/nb.json
Labels: c: i18n

#17937 Load sparkline images only once they are near view port
  core/Twig.php
Labels: Needs Review

#17889 split private directories check into required and recommended
  plugins/Diagnostics/Diagnostic/AbstractPrivateDirectories.php
  plugins/Diagnostics/Diagnostic/RecommendedPrivateDirectories.php
  plugins/Diagnostics/Diagnostic/RequiredPrivateDirectories.php
  plugins/Diagnostics/config/config.php
  plugins/Diagnostics/lang/en.json
  plugins/Diagnostics/tests/UI/expected-screenshots/Diagnostics_page.png
Labels: not-in-changelog, Needs Review
