Repository matomo-org/matomo, pull requests merged in 2021-05, with the labels that each got.

#17515 no links in copy-paste system check
  plugins/Installation/templates/_systemCheckSection.twig
Labels: Needs Review

#17519 Allow invalidating empty site
  core/Archive/ArchiveInvalidator.php
  core/ArchiveProcessor/Loader.php
  tests/PHPUnit/Integration/CronArchive/QueueConsumerTest.php
Labels: Needs Review, Regression

#17524 Ensure redirects in HTTP class are only done to allowed protocols (for cURL)
  core/Http.php
  tests/PHPUnit/Integration/HttpTest.php
  tests/resources/redirector.php
Labels: Needs Review, c: Security

#17521 Improve tracker performance when using custom dimensions (one less update query per tracking request)
  core/Tracker/RequestProcessor.php
  core/Tracker/Visit.php
  plugins/CustomDimensions/Tracker/CustomDimensionsRequestProcessor.php
Labels: Needs Review

#17523 Updates phpmailer/phpmailer to 6.4.1
  composer.lock
Labels: Needs Review, Task, not-in-changelog

#17351 Make archiving process to respect process_new_segments_from settings
  core/ArchiveProcessor/Loader.php
  core/CronArchive.php
  core/DataAccess/Model.php
  plugins/CoreConsole/Commands/CoreArchiver.php
  plugins/CoreConsole/tests/System/ArchiveCronTest.php
  plugins/SegmentEditor/tests/System/UnprocessedSegmentsTest.php
  tests/PHPUnit/Fixtures/UITestFixture.php
  tests/PHPUnit/Integration/ArchiveProcessor/LoaderTest.php
  tests/PHPUnit/Integration/DataAccess/ModelTest.php
Labels: Needs Review, not-in-changelog

#17529 Clear all cache directly after an update instead of in oneClickResults().
  plugins/CoreUpdater/Controller.php
Labels: not-in-changelog

#17540 more neutral wording and other style improvements
  PRIVACY.md
  config/global.ini.php
  core/Tracker/ScheduledTasksRunner.php
  js/piwik.js
  plugins/UsersManager/Controller.php
  tests/README.md
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard2.png
Labels: Needs Review

#17517 Do not confuse normal rows with the label "-1" w/ the summary row
  core/DataTable.php
  core/DataTable/Filter/ReplaceSummaryRowLabel.php
  core/DataTable/Row.php
  plugins/Actions/ArchivingHelper.php
  plugins/Referrers/tests/System/expected/test_phpSerialized74__Referrers.getReferrerType_year.original
  plugins/Referrers/tests/System/expected/test_phpSerialized__Referrers.getReferrerType_year.original
  tests/PHPUnit/Fixtures/ManyVisitsWithMockLocationProvider.php
  tests/PHPUnit/Integration/ArchiveProcessingTest.php
  tests/PHPUnit/System/BlobReportLimitingTest.php
  tests/PHPUnit/System/expected/test_reportLimitingwithNegOneLabel___Events.getAction_day.xml
  tests/PHPUnit/System/expected/test_reportLimitingwithNegOneLabel___Events.getCategory_day.xml
  tests/PHPUnit/System/expected/test_reportLimitingwithNegOneLabel___Events.getName_day.xml
  tests/PHPUnit/System/expected/test_reportLimitingwithNegOneLabel__flattened__Events.getAction_day.xml
  tests/PHPUnit/System/expected/test_reportLimitingwithNegOneLabel__flattened__Events.getCategory_day.xml
  tests/PHPUnit/System/expected/test_reportLimitingwithNegOneLabel__flattened__Events.getName_day.xml
  tests/PHPUnit/System/expected/test_reportLimitingwithNegOneLabel__rankingQuery__Events.getAction_day.xml
  tests/PHPUnit/System/expected/test_reportLimitingwithNegOneLabel__rankingQuery__Events.getCategory_day.xml
  tests/PHPUnit/System/expected/test_reportLimitingwithNegOneLabel__rankingQuery__Events.getName_day.xml
  tests/PHPUnit/Unit/DataTableTest.php
Labels: Needs Review

#17538 Add option to skip log purging check when invalidating archives in the rare cases it is needed.
  core/Archive/ArchiveInvalidator.php
  plugins/CoreAdminHome/Commands/InvalidateReportData.php
  tests/PHPUnit/Integration/DataAccess/ArchiveInvalidatorTest.php
Labels: Needs Review

#17503 detect brute force login attempts from different ip addresses
  core/Db/Schema/Mysql.php
  core/Updates/4.3.0-b5.php
  plugins/CoreHome/CoreHome.php
  plugins/Login/Emails/SuspiciousLoginAttemptsInLastHourEmail.php
  plugins/Login/Login.php
  plugins/Login/Model.php
  plugins/Login/Security/BruteForceDetection.php
  plugins/Login/lang/en.json
  plugins/Login/templates/_suspiciousLoginAttemptsEmail.twig
  plugins/Login/tests/Integration/ModelTest.php
  plugins/Login/tests/Integration/Security/BruteForceDetectionTest.php
Labels: Needs Review, c: Security

#17543 make SuspiciousLoginAttemptsInLastHourEmail email from DI container
  plugins/Login/Security/BruteForceDetection.php
Labels: Needs Review, not-in-changelog

#17544 bump version and change update to new version
  core/Updates/4.3.0-rc2.php
  core/Version.php
Labels: Needs Review, not-in-changelog

#17520 Use token auth when widgetize
  core/FrontController.php
  tests/PHPUnit/Integration/FrontControllerTest.php
Labels: Needs Review, not-in-changelog

#17545 Ensure login is set for brute force log when 2fa code is invalid
  plugins/TwoFactorAuth/Controller.php
Labels: Needs Review, c: Security, not-in-changelog

#17546 do not use login detection bruteforcedetection code during oneClickResults action
  plugins/Login/Security/BruteForceDetection.php
Labels: Needs Review

#17539 Use Common::safe_unserialize for session data
  CHANGELOG.md
  libs/README.md
  libs/Zend/Session.php
Labels: Needs Review, c: Security

#17547 If no archives names are requested when querying archive data, do not initiate archiving.
  core/Archive.php
  tests/PHPUnit/Integration/ArchiveTest.php
Labels: Needs Review

#17552 Updates device detector to 4.2.3
  composer.lock
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getSegmentsMetadata.xml
Labels: Task, not-in-changelog

#17518 Update mark notification as read method
  plugins/CoreHome/Controller.php
  plugins/CoreHome/angularjs/notification/notification.controller.js
  plugins/CoreHome/angularjs/notification/notification.directive.html
  plugins/CoreHome/config/test.php
  plugins/CoreHome/tests/UI/Notifications_spec.js
  plugins/CoreHome/tests/UI/expected-screenshots/Notifications_close.png
  plugins/CoreHome/tests/UI/expected-screenshots/Notifications_close_reload.png
  plugins/CoreHome/tests/UI/expected-screenshots/Notifications_loaded.png
  plugins/CoreHome/tests/UI/expected-screenshots/Notifications_reloaded.png
Labels: Needs Review, not-in-changelog

#17553 Prevent error message in dev mode no date is defined in segment
  plugins/SegmentEditor/API.php
Labels: Needs Review

#17564 fix decoration: none
  plugins/CoreHome/stylesheets/layout.less
Labels: Needs Review, c: Design / UI, not-in-changelog

#17568 use status code instead of checking contents
  plugins/Diagnostics/Diagnostic/RequiredPrivateDirectories.php
Labels: not-in-changelog

#17570 Make more link work again in marketplace plugin list
  plugins/Marketplace/angularjs/marketplace/marketplace.directive.js
Labels: Needs Review

#17569 Make sure summary row subtables are included in the serialized representaion of a datatable tree.
  core/DataTable.php
  tests/PHPUnit/Unit/DataTableTest.php
Labels: Needs Review

#17462 Add testdox to phpunit.xml
  tests/PHPUnit/phpunit.xml.dist
Labels: Needs Review

#17573 Improves Geolocation diagnostics
  plugins/Diagnostics/tests/UI/expected-screenshots/Diagnostics_page.png
  plugins/UserCountry/Diagnostic/GeolocationDiagnostic.php
Labels: Needs Review

#17587 Upload logo form fix
  plugins/CoreAdminHome/templates/generalSettings.twig
Labels: not-in-changelog

#17579 Fix fetching Alexa rank
  plugins/SEO/Metric/Alexa.php
Labels: Needs Review, not-in-changelog

#17593 Adds missing iso attributes to Greece map
  plugins/UserCountryMap/svg/GRC.svg
Labels: Needs Review, not-in-changelog

#17588 Use html formatter for formating reported generated
  core/Plugin/Visualization.php
Labels: Needs Review, not-in-changelog

#17598 Modiy refer banner
  core/Plugin/Manager.php
  plugins/Feedback/Feedback.php
  plugins/Feedback/angularjs/refer-banner/refer-banner.controller.js
  plugins/Feedback/angularjs/refer-banner/refer-banner.directive.html
  plugins/Feedback/angularjs/refer-banner/refer-banner.directive.less
  plugins/Feedback/lang/en.json
  plugins/Feedback/tests/Integration/FeedbackTest.php
  plugins/Feedback/tests/Integration/ReferBannerTest.php
  plugins/Feedback/tests/UI/expected-screenshots/FeedbackForm_show.png
  plugins/Feedback/tests/UI/expected-screenshots/FeedbackPopup_feedback_popup.png
  plugins/Feedback/tests/UI/expected-screenshots/ReferBannerTest_feedback_popup.png
  tests/PHPUnit/Integration/Plugin/ManagerTest.php
Labels: Needs Review, not-in-changelog

#17574 Ignore performance metrics that are obviously too high
  plugins/PagePerformance/Columns/Base.php
  plugins/PagePerformance/tests/Integration/Tracker/PerformanceDataProcessorTest.php
Labels: Needs Review

#17610 Use originalString when returning the Segment definition string
  core/Archive.php
  core/Archive/ArchiveInvalidator.php
  core/Segment.php
  tests/PHPUnit/Integration/SegmentTest.php
Labels: Needs Review, not-in-changelog

#17606 Improve required private directories check
  CHANGELOG.md
  plugins/CoreUpdater/Commands/SecurityFiles.php
  plugins/Diagnostics/Diagnostic/RequiredPrivateDirectories.php
  plugins/Installation/ServerFilesGenerator.php
Labels: Needs Review

#17618 Fix uncaught exception when running system tests for plugins
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_browserName__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_operatingSystemName__API.getSuggestedValuesForSegment.xml
  plugins/CoreHome/Columns/VisitorId.php
Labels: Needs Review, c: Tests & QA, not-in-changelog

#17487 Use empty nonce if not md5
  plugins/CoreAdminHome/OptOutManager.php
Labels: not-in-changelog

#17620 clear EventDispatcher cache in tests
  core/EventDispatcher.php
  tests/PHPUnit/Framework/Fixture.php
  tests/PHPUnit/Framework/TestCase/IntegrationTestCase.php
  tests/PHPUnit/Unit/DataAccess/LogQueryBuilder/JoinTablesTest.php
Labels: Needs Review, c: Tests & QA, not-in-changelog

#17623 Update matomo/cache to new version w/ doctrine/cache fork.
  composer.lock
Labels: not-in-changelog

#17531 Email notifications for critical actions
  core/Mail.php
  plugins/CoreAdminHome/Emails/RecoveryCodesRegeneratedEmail.php
  plugins/CoreAdminHome/Emails/RecoveryCodesShowedEmail.php
  plugins/CoreAdminHome/Emails/SecurityNotificationEmail.php
  plugins/CoreAdminHome/Emails/SettingsChangedEmail.php
  plugins/CoreAdminHome/Emails/TokenAuthCreatedEmail.php
  plugins/CoreAdminHome/Emails/TokenAuthDeletedEmail.php
  plugins/CoreAdminHome/Emails/TwoFactorAuthDisabledEmail.php
  plugins/CoreAdminHome/Emails/TwoFactorAuthEnabledEmail.php
  plugins/CoreAdminHome/Emails/UserCreatedEmail.php
  plugins/CoreAdminHome/Emails/UserDeletedEmail.php
  plugins/CoreAdminHome/lang/en.json
  plugins/CoreAdminHome/templates/_securityNotificationEmail.twig
  plugins/CorePluginsAdmin/API.php
  plugins/TwoFactorAuth/Controller.php
  plugins/UsersManager/API.php
  plugins/UsersManager/Controller.php
  plugins/UsersManager/Model.php
Labels: Needs Review

#16754 Update PHP extension requirements & deprecate Common::mb_* methods
  composer.json
  composer.lock
  core/API/ApiRenderer.php
  core/CliMulti/Output.php
  core/Common.php
  core/Concurrency/Lock.php
  core/CronArchive.php
  core/DataAccess/LogAggregator.php
  core/Date.php
  core/DeviceDetector/DeviceDetectorFactory.php
  core/Tracker/Failures.php
  core/Tracker/GoalManager.php
  core/Tracker/PageUrl.php
  core/Tracker/Request.php
  core/Tracker/Visit.php
  core/Twig.php
  core/Updates/4.0.0-b1.php
  core/Url.php
  core/Validators/CharacterLength.php
  libs/upgradephp/upgrade.php
  plugins/API/Controller.php
  plugins/Actions/Actions/ActionSiteSearch.php
  plugins/Actions/DataTable/Filter/Actions.php
  plugins/Actions/VisitorDetails.php
  plugins/CoreHome/Columns/UserId.php
  plugins/CoreVisualizations/Visualizations/Cloud.php
  plugins/CustomDimensions/Tracker/CustomDimensionsRequestProcessor.php
  plugins/DevicesDetection/Columns/BrowserName.php
  plugins/DevicesDetection/Columns/Os.php
  plugins/Diagnostics/Diagnostic/PhpExtensionsCheck.php
  plugins/Diagnostics/tests/UI/expected-screenshots/Diagnostics_page.png
  plugins/GeoIp2/GeoIP2AutoUpdater.php
  plugins/GeoIp2/LocationProvider/GeoIp2/Php.php
  plugins/Installation/lang/en.json
  plugins/Installation/tests/UI/expected-screenshots/Installation_system_check.png
  plugins/Intl/Commands/GenerateIntl.php
  plugins/MobileMessaging/SMSProvider.php
  plugins/Referrers/Columns/Base.php
  plugins/Referrers/Columns/ReferrerUrl.php
  plugins/Referrers/SearchEngine.php
  plugins/ScheduledReports/Controller.php
  plugins/SegmentEditor/SegmentFormatter.php
  plugins/SegmentEditor/SegmentSelectorControl.php
  plugins/SitesManager/SiteUrls.php
  plugins/TwoFactorAuth/Dao/RecoveryCodeDao.php
  plugins/TwoFactorAuth/tests/Integration/Dao/RecoveryCodeRandomGeneratorTest.php
  plugins/TwoFactorAuth/tests/Integration/Dao/RecoveryCodeStaticGeneratorTest.php
  plugins/TwoFactorAuth/tests/Integration/Dao/TwoFaSecretRandomGeneratorTest.php
  plugins/TwoFactorAuth/tests/Integration/TwoFactorAuthenticationTest.php
  plugins/UsersManager/API.php
  plugins/UsersManager/UsersManager.php
  tests/PHPUnit/Integration/ReleaseCheckListTest.php
Labels: Needs Review

#17506 Show report generated time when date range includes today
  LEGALNOTICE
  core/ArchiveProcessor.php
  plugins/CoreHome/angularjs/enrichedheadline/enrichedheadline.directive.html
  plugins/CoreHome/angularjs/enrichedheadline/enrichedheadline.directive.js
  plugins/CoreHome/angularjs/enrichedheadline/enrichedheadline.directive.less
  plugins/CoreHome/templates/_dataTable.twig
  plugins/Morpheus/fonts/matomo.svg
  plugins/Morpheus/fonts/matomo.ttf
  plugins/Morpheus/fonts/matomo.woff
  plugins/Morpheus/fonts/matomo.woff2
  plugins/Morpheus/fonts/selection.json
  plugins/Morpheus/stylesheets/base/icons.css
  plugins/Morpheus/templates/demo.twig
  plugins/Morpheus/tests/UI/expected-screenshots/Morpheus_load.png
  tests/PHPUnit/System/TwoVisitorsTwoWebsitesDifferentDaysConversionsTest.php
  tests/UI/expected-screenshots/Theme_demo.png
Labels: Needs Review, not-in-changelog

#17522 Outlink tracking when DOM modified
  CHANGELOG.md
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  tests/javascript/index.php
Labels: Needs Review, not-in-changelog

#16880 in cache buster only look at activated plugins, not loaded plugins
  core/AssetManager/UIAssetCacheBuster.php
Labels: Needs Review, not-in-changelog

#17624 Fix possible notice when no user is set
  core/Piwik.php
Labels: Needs Review, c: Tests & QA

#17630 Fix position & visibility of icons in maximized widgets
  plugins/Dashboard/stylesheets/widget.less
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_widget_maximise.png
Labels: Needs Review, not-in-changelog

#17629 Ensure to close open tooltips when widget is maximized
  plugins/Dashboard/javascripts/dashboardWidget.js
Labels: Needs Review, not-in-changelog

#17633 Use logger when outputting invalidate-report-data so there will be a …
  plugins/CoreAdminHome/Commands/InvalidateReportData.php
  plugins/CoreAdminHome/tests/Integration/Commands/InvalidateReportDataTest.php
Labels: Needs Review

#17632 Improve purge log data logic
  core/LogDeleter.php
  plugins/PrivacyManager/LogDataPurger.php
Labels: Needs Review, c: Performance

#17635 Allow aborting sending mails via Mail.send event.
  CHANGELOG.md
  core/Mail.php
  tests/PHPUnit/Integration/MailTest.php
Labels: Needs Review

#17636 Allow overriding some Tracker config by idSite
  core/Tracker/Request.php
  core/Tracker/TrackerConfig.php
  core/Tracker/Visit.php
  core/Tracker/VisitorRecognizer.php
  plugins/CoreHome/Tracker/VisitRequestProcessor.php
  plugins/Referrers/Columns/Campaign.php
  plugins/Referrers/Columns/Website.php
  tests/PHPUnit/Unit/Tracker/RequestSetTest.php
  tests/PHPUnit/Unit/Tracker/TrackerConfigTest.php
Labels: Needs Review
