Repository matomo-org/matomo, pull requests merged in 2021-12, with the labels that each got.

#18366 Configuration option to disable transition periods
  core/Period/Range.php
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/Periods/Range.ts
  plugins/Transitions/API.php
  plugins/Transitions/Controller.php
  plugins/Transitions/Transitions.php
  plugins/Transitions/javascripts/transitions.js
  plugins/Transitions/lang/en.json
  plugins/Transitions/tests/Integration/TransitionsMaxAllowedPeriodTest.php
  plugins/Transitions/tests/UI/Transitions_spec.js
Labels: not-in-changelog, Needs Review

#18422 Update missing screenshots
  plugins/MultiSites/tests/UI/expected-screenshots/MultiSitesTest_all_websites.png
  plugins/MultiSites/tests/UI/expected-screenshots/MultiSitesTest_all_websites_changed_sort_order.png
  plugins/MultiSites/tests/UI/expected-screenshots/MultiSitesTest_all_websites_page_1.png
  plugins/MultiSites/tests/UI/expected-screenshots/MultiSitesTest_all_websites_search.png
  plugins/Transitions/tests/UI/expected-screenshots/Transitions_transitions_report_period_not_allowed.png
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
  tests/UI/expected-screenshots/UIIntegrationTest_widgetize_allwebsites.png
Labels: not-in-changelog, Needs Review

#18420 Update Version to 4.7.0-b1
  core/Version.php
Labels: not-in-changelog

#18407 do not use real mysql version in tests for running UI tests
  plugins/CoreHome/Widgets/GetSystemSummary.php
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_removed.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_removed.png
  tests/UI/expected-screenshots/EmptySite_emptySiteDashboard_ignored.png
  tests/UI/expected-screenshots/Theme_home.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_home.png
  tests/UI/expected-screenshots/UIIntegrationTest_api_error.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard1.png
Labels: c: Tests & QA, Needs Review

#18419 [Vue] emit/broadcast on scope the method was called on not rootScope
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/Matomo/Matomo.adapter.ts
Labels: Regression

#18384 Fixes HTML_QuickForm2_ContainerIterator for PHP8.1
  libs/HTML/QuickForm2/Container.php
  libs/HTML/QuickForm2/Element/Select.php
Labels: not-in-changelog, Needs Review

#18413 Fixes some UI issues in anonymise data
  plugins/PrivacyManager/angularjs/anonymize-log-data/anonymize-log-data.directive.less
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_anonymizelogdata_anonymizeip_and_visit_column_cancelled.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_anonymizelogdata_anonymizeip_and_visit_column_confirmed.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_anonymizelogdata_anonymizeip_and_visit_column_prefilled.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_anonymizelogdata_anonymizelocation_anduserid_and_action_column_confirmed.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_anonymizelogdata_anonymizelocation_anduserid_and_action_column_prefilled.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_anonymizelogdata_one_site_and_custom_date_confirmed.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_anonymizelogdata_one_site_and_custom_date_prefilled.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_privacy_settings_default.png
Labels: c: Design / UI, Needs Review

#18414 Translations update from Hosted Weblate
  lang/ja.json
  plugins/API/lang/nb.json
  plugins/CoreAdminHome/lang/fr.json
  plugins/CoreAdminHome/lang/ur.json
  plugins/CoreHome/lang/de.json
  plugins/CorePluginsAdmin/lang/de.json
  plugins/CoreUpdater/lang/it.json
  plugins/CustomJsTracker/lang/nb.json
  plugins/Dashboard/lang/nb.json
  plugins/Feedback/lang/fr.json
  plugins/ImageGraph/lang/ta.json
  plugins/Insights/lang/nb.json
  plugins/IntranetMeasurable/lang/nb.json
  plugins/MobileAppMeasurable/lang/nb.json
  plugins/MultiSites/lang/el.json
  plugins/MultiSites/lang/tr.json
  plugins/ProfessionalServices/lang/de.json
  plugins/ProfessionalServices/lang/nb.json
  plugins/Resolution/lang/nb.json
  plugins/Transitions/lang/el.json
  plugins/Transitions/lang/nb.json
  plugins/UserCountryMap/lang/nb.json
  plugins/UserId/lang/nb.json
  plugins/UserLanguage/lang/nb.json
  plugins/UsersManager/lang/es.json
  plugins/UsersManager/lang/nb.json
  plugins/Widgetize/lang/nb.json
Labels: not-in-changelog, c: i18n

#18382 [Vue] migrate piwik-period-selector angularjs component
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/angularjs/period-selector/period-selector.controller.js
  plugins/CoreHome/angularjs/period-selector/period-selector.directive.html
  plugins/CoreHome/angularjs/period-selector/period-selector.directive.js
  plugins/CoreHome/javascripts/corehome.js
  plugins/CoreHome/lang/en.json
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/Comparisons/Comparisons.store.ts
  plugins/CoreHome/vue/src/DateRangePicker/DateRangePicker.vue
  plugins/CoreHome/vue/src/ExpandOnClick/ExpandOnClick.ts
  plugins/CoreHome/vue/src/ExpandOnHover/ExpandOnHover.ts
  plugins/CoreHome/vue/src/MatomoUrl/MatomoUrl.ts
  plugins/CoreHome/vue/src/PeriodSelector/PeriodSelector.adapter.ts
  plugins/CoreHome/vue/src/PeriodSelector/PeriodSelector.less
  plugins/CoreHome/vue/src/PeriodSelector/PeriodSelector.vue
  plugins/CoreHome/vue/src/directiveUtilities.ts
  plugins/CoreHome/vue/src/index.ts
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_admin_view_admin_edit_permissions.png
  tests/UI/expected-screenshots/PeriodSelector_custom_comparison.png
Labels: Needs Review

#18447 Also try to remove hidden files on update
  core/Filesystem.php
Labels: Needs Review

#18425 Widgetize language reworked
  plugins/Widgetize/lang/en.json
Labels: Needs Review, c: i18n

#18452 Update expected screenshots to pass UI tests
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_settings_general.png
Labels: not-in-changelog, Needs Review

#18450 Translations update from Hosted Weblate
  plugins/Actions/lang/de.json
  plugins/CoreHome/lang/de.json
  plugins/CoreHome/lang/el.json
  plugins/CoreHome/lang/tr.json
  plugins/Dashboard/lang/de.json
  plugins/Goals/lang/de.json
  plugins/SitesManager/lang/de.json
Labels: c: i18n

#18421 [Vue] Remove plugin.json from CoreVue since it is unnecessary and
  plugins/CoreVue/plugin.json
Labels: Needs Review

#18449 [Vue] fix url location updating regression in MatomoUrl.updateLocation use
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/Comparisons/Comparisons.store.ts
  plugins/CoreHome/vue/src/PeriodSelector/PeriodSelector.vue
  plugins/PagePerformance/tests/UI/PagePerformance_spec.js
Labels: Regression

#18444 Ensure UTF8mb4 conversion command always enables tracking again
  plugins/CoreUpdater/Commands/ConvertToUtf8mb4.php
Labels: not-in-changelog, Needs Review

#18461 Fix 'Call to undefined function Piwik\piwik_fix_lbrace()'
  core/Common.php
  core/Twig.php
  plugins/Diagnostics/Diagnostic/DiagnosticResult.php
Labels: not-in-changelog, Needs Review

#18455 Ignore segment errors in update script
  core/Updates/4.6.0-b4.php
Labels: not-in-changelog, Needs Review

#18279 add disable archiving segment for plugins
  config/global.ini.php
  core/ArchiveProcessor/Loader.php
  core/ArchiveProcessor/Rules.php
  core/Config/GeneralConfig.php
  core/Plugin/Visualization.php
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/lang/en.json
  plugins/CoreHome/templates/_dataTable.twig
  tests/PHPUnit/Fixtures/DisablePluginArchive.php
  tests/PHPUnit/Integration/ArchiveProcessor/LoaderTest.php
  tests/PHPUnit/System/ArchiveInvalidationTest.php
  tests/PHPUnit/Unit/ConfigTest.php
  tests/UI/expected-screenshots/DisablePluginArchive_referrer_disabled.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
  tests/UI/specs/DisablePluginArchive_spec.js
Labels: not-in-changelog

#18462 Improve site without data page
  plugins/Live/stylesheets/live.less
  plugins/Live/stylesheets/visitor_profile.less
  plugins/Morpheus/stylesheets/base/mixins.less
  plugins/Morpheus/stylesheets/general/_jqueryUI.less
  plugins/Morpheus/stylesheets/main.less
  plugins/SitesManager/lang/en.json
  plugins/SitesManager/stylesheets/SitesManager.less
  plugins/SitesManager/templates/siteWithoutData.twig
  tests/UI/expected-screenshots/EmptySite_emptySiteDashboard.png
  tests/UI/expected-screenshots/OneClickUpdate_login.png
Labels: not-in-changelog, Needs Review

#18457 Translations update from Hosted Weblate
  lang/sv.json
  plugins/Actions/lang/fr.json
  plugins/CoreHome/lang/sl.json
  plugins/CoreUpdater/lang/de.json
  plugins/DevicesDetection/lang/de.json
  plugins/Events/lang/de.json
  plugins/GeoIp2/lang/de.json
  plugins/Live/lang/de.json
  plugins/MobileMessaging/lang/de.json
  plugins/PrivacyManager/lang/de.json
  plugins/Tour/lang/de.json
  plugins/Transitions/lang/tr.json
  plugins/TwoFactorAuth/lang/de.json
  plugins/Widgetize/lang/de.json
  plugins/Widgetize/lang/el.json
  plugins/Widgetize/lang/tr.json
Labels: c: i18n

#18423 [Vue] migrate piwik-reporting-menu directive to vue
  core/AssetManager/UIAssetFetcher/JScriptUIAssetFetcher.php
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/angularjs/common/directives/side-nav.js
  plugins/CoreHome/angularjs/reporting-menu/reportingmenu-model.js
  plugins/CoreHome/angularjs/reporting-menu/reportingmenu.controller.js
  plugins/CoreHome/angularjs/reporting-menu/reportingmenu.directive.html
  plugins/CoreHome/angularjs/reporting-menu/reportingmenu.directive.js
  plugins/CoreHome/angularjs/reporting-page/reportingpage.controller.js
  plugins/CoreHome/stylesheets/layout.less
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/AjaxHelper/AjaxHelper.ts
  plugins/CoreHome/vue/src/MatomoUrl/MatomoUrl.ts
  plugins/CoreHome/vue/src/Notification/Notifications.store.ts
  plugins/CoreHome/vue/src/QuickAccess/QuickAccess.vue
  plugins/CoreHome/vue/src/ReportingMenu/ReportingMenu.adapter.ts
  plugins/CoreHome/vue/src/ReportingMenu/ReportingMenu.store.adapter.ts
  plugins/CoreHome/vue/src/ReportingMenu/ReportingMenu.store.ts
  plugins/CoreHome/vue/src/ReportingMenu/ReportingMenu.vue
  plugins/CoreHome/vue/src/ReportingPages/ReportingPages.store.ts
  plugins/CoreHome/vue/src/SideNav/SideNav.adapter.ts
  plugins/CoreHome/vue/src/SideNav/SideNav.ts
  plugins/CoreHome/vue/src/SiteSelector/SiteSelector.adapter.ts
  plugins/CoreHome/vue/src/SiteSelector/SiteSelector.vue
  plugins/CoreHome/vue/src/createAngularJsAdapter.ts
  plugins/CoreHome/vue/src/index.ts
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/Field/Field.adapter.ts
  plugins/CoreVue/polyfills/dist/MatomoPolyfills.js
  plugins/CoreVue/polyfills/dist/MatomoPolyfills.min.js
  plugins/CoreVue/polyfills/src/jqueryNativeEventTrigger.ts
  plugins/CoreVue/types/index.d.ts
  plugins/Dashboard/tests/UI/DashboardManager_spec.js
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_removed.png
  plugins/PagePerformance/tests/UI/PagePerformance_spec.js
  plugins/SitesManager/tests/UI/SitesManager_spec.js
  plugins/TestRunner/Commands/SyncScreenshots.php
  plugins/UsersManager/tests/UI/UserSettings_spec.js
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_admin_view_admin_load.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_all_rows_deselected.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_all_rows_in_search.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_all_rows_selected.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_bulk_remove_access.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_bulk_set_access.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_bulk_set_access_confirm.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_delete_bulk_access.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_delete_single.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_manage_users_back.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_previous.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_role_for.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_rows_selected.png
  tests/UI/expected-screenshots/EmptySite_emptySiteDashboard_ignored.png
  tests/UI/expected-screenshots/Menus_admin_loaded.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_plugins.png
  tests/UI/specs/Comparison_spec.js
  tests/UI/specs/Menus_spec.js
  vue.config.js
Labels: Needs Review

#18473 Ensure update to 4.6.2 removes some files
  core/Updates/4.6.2-rc2.php
  core/Version.php
Labels: not-in-changelog, Needs Review

#18399 convert sparkline api to one request - fixes archive
  plugins/Goals/API.php
  plugins/Goals/Controller.php
  plugins/Goals/Pages.php
  plugins/Goals/Reports/GetMetrics.php
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getReportPagesMetadata.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getWidgetMetadata.xml
Labels: not-in-changelog, Needs Review

#18483 Revert "convert sparkline api to one request - fixes archive"
  plugins/Goals/API.php
  plugins/Goals/Controller.php
  plugins/Goals/Pages.php
  plugins/Goals/Reports/GetMetrics.php
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getReportPagesMetadata.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getWidgetMetadata.xml
Labels: not-in-changelog

#18428 [Vue] migrate widget-loader directive
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/angularjs/widget-loader/widgetloader.directive.html
  plugins/CoreHome/angularjs/widget-loader/widgetloader.directive.js
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/AjaxHelper/AjaxHelper.ts
  plugins/CoreHome/vue/src/EnrichedHeadline/EnrichedHeadline.vue
  plugins/CoreHome/vue/src/Matomo/Matomo.adapter.ts
  plugins/CoreHome/vue/src/WidgetLoader/WidgetLoader.adapter.ts
  plugins/CoreHome/vue/src/WidgetLoader/WidgetLoader.vue
  plugins/CoreHome/vue/src/index.ts
  plugins/CoreVue/types/index.d.ts
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_reset.png
  plugins/TwoFactorAuth/tests/UI/TwoFactorAuth_spec.js
  tests/UI/specs/UIIntegration_spec.js
  tests/lib/screenshot-testing/support/app.js
Labels: Needs Review

#18477 [Vue] two bug fixes: use correct base for site change + correct URL for launching new site
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/Comparisons/Comparisons.store.spec.ts
  plugins/CoreHome/vue/src/MatomoUrl/MatomoUrl.ts
  plugins/CoreHome/vue/src/SiteSelector/SitesStore.ts
Labels: Needs Review

#18429 [Vue] migrate piwik-widget and related directives
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/angularjs/widget-bydimension-container/widget-bydimension-container.directive.html
  plugins/CoreHome/angularjs/widget-bydimension-container/widget-bydimension-container.directive.js
  plugins/CoreHome/angularjs/widget-container/widgetcontainer.directive.html
  plugins/CoreHome/angularjs/widget-container/widgetcontainer.directive.js
  plugins/CoreHome/angularjs/widget/widget.directive.html
  plugins/CoreHome/angularjs/widget/widget.directive.js
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/AjaxHelper/AjaxHelper.ts
  plugins/CoreHome/vue/src/Comparisons/Comparisons.vue
  plugins/CoreHome/vue/src/ReportMetadata/ReportMetadata.store.ts
  plugins/CoreHome/vue/src/ReportingMenu/ReportingMenu.store.ts
  plugins/CoreHome/vue/src/ReportingMenu/ReportingMenu.vue
  plugins/CoreHome/vue/src/SiteSelector/SiteSelector.adapter.ts
  plugins/CoreHome/vue/src/Tooltips/Tooltips.ts
  plugins/CoreHome/vue/src/Widget/Widget.adapter.ts
  plugins/CoreHome/vue/src/Widget/Widget.vue
  plugins/CoreHome/vue/src/Widget/Widgets.store.ts
  plugins/CoreHome/vue/src/WidgetByDimensionContainer/WidgetByDimensionContainer.adapter.ts
  plugins/CoreHome/vue/src/WidgetByDimensionContainer/WidgetByDimensionContainer.less
  plugins/CoreHome/vue/src/WidgetByDimensionContainer/WidgetByDimensionContainer.vue
  plugins/CoreHome/vue/src/WidgetContainer/WidgetContainer.adapter.ts
  plugins/CoreHome/vue/src/WidgetContainer/WidgetContainer.vue
  plugins/CoreHome/vue/src/WidgetLoader/WidgetLoader.vue
  plugins/CoreHome/vue/src/index.ts
  plugins/CoreVue/polyfills/dist/MatomoPolyfills.js
  plugins/CoreVue/polyfills/dist/MatomoPolyfills.min.js
  plugins/CoreVue/polyfills/src/index.ts
  plugins/CoreVue/types/index.d.ts
  plugins/ScheduledReports/tests/UI/ScheduledReports_spec.js
  plugins/TwoFactorAuth/tests/UI/TwoFactorAuth_spec.js
  tests/UI/specs/Theme_spec.js
Labels: Needs Review

#18491 Fix possible undefined constant exception when using ssl_no_verify
  libs/Zend/Db/Adapter/Mysqli.php
Labels: not-in-changelog, Needs Review

#18498 [VUE] add report date
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/EnrichedHeadline/EnrichedHeadline.vue
  tests/UI/expected-screenshots/UIIntegrationTest_actions_pages_tooltip_help.png
  tests/UI/specs/UIIntegration_spec.js
Labels: not-in-changelog

#18497 fix two regressions in period selector comparison launching/detection
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/PeriodSelector/PeriodSelector.vue
Labels: not-in-changelog, Regression

#18398 Add system check warnings for php-fpm and nginx if config files are accessible
  plugins/Diagnostics/Diagnostic/PhpInformational.php
  plugins/Diagnostics/Diagnostic/RequiredPrivateDirectories.php
  plugins/Diagnostics/Diagnostic/ServerInformational.php
  plugins/Diagnostics/lang/en.json
  plugins/Installation/tests/UI/expected-screenshots/Installation_system_check.png
Labels: not-in-changelog, Needs Review

#18488 API language reworked
  plugins/API/lang/en.json
Labels: Needs Review, c: i18n

#18506 API Language updates
  plugins/API/lang/en.json
  plugins/Feedback/tests/UI/expected-screenshots/FeedbackForm_show.png
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getGlossaryReports.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getReportMetadata_day.xml
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
  tests/UI/expected-screenshots/UIIntegrationTest_glossary.png
  tests/UI/expected-screenshots/UIIntegrationTest_glossary_widgetized.png
Labels: Needs Review

#18501 Ensure 2FA is not loaded when safemode is triggered
  plugins/TwoFactorAuth/TwoFactorAuth.php
Labels: Bug, Needs Review

#18500 Fix for datatable row sum error
  core/DataTable/Row.php
Labels: not-in-changelog, Needs Review, Regression

#18430 [Vue] migrate reporting page directive
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/angularjs/reporting-page/reportingpage-model.js
  plugins/CoreHome/angularjs/reporting-page/reportingpage.controller.js
  plugins/CoreHome/angularjs/reporting-page/reportingpage.directive.html
  plugins/CoreHome/angularjs/reporting-page/reportingpage.directive.js
  plugins/CoreHome/angularjs/reporting-page/reportingpage.directive.less
  plugins/CoreHome/javascripts/dataTable.js
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/MatomoUrl/MatomoUrl.ts
  plugins/CoreHome/vue/src/Orderable.ts
  plugins/CoreHome/vue/src/ReportMetadata/ReportMetadata.store.ts
  plugins/CoreHome/vue/src/ReportingMenu/Category.ts
  plugins/CoreHome/vue/src/ReportingMenu/ReportingMenu.store.ts
  plugins/CoreHome/vue/src/ReportingMenu/ReportingMenu.vue
  plugins/CoreHome/vue/src/ReportingMenu/Subcategory.ts
  plugins/CoreHome/vue/src/ReportingPage/ReportingPage.adapter.ts
  plugins/CoreHome/vue/src/ReportingPage/ReportingPage.less
  plugins/CoreHome/vue/src/ReportingPage/ReportingPage.store.adapter.ts
  plugins/CoreHome/vue/src/ReportingPage/ReportingPage.store.ts
  plugins/CoreHome/vue/src/ReportingPage/ReportingPage.vue
  plugins/CoreHome/vue/src/ReportingPages/ReportingPages.store.ts
  plugins/CoreHome/vue/src/Widget/Widget.vue
  plugins/CoreHome/vue/src/Widget/Widgets.store.ts
  plugins/CoreHome/vue/src/WidgetByDimensionContainer/WidgetByDimensionContainer.vue
  plugins/CoreHome/vue/src/WidgetContainer/WidgetContainer.vue
  plugins/CoreHome/vue/src/index.ts
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/FormField/FormField.vue
  plugins/CoreVue/types/index.d.ts
  plugins/Live/tests/UI/DeactivatedFeatures_spec.js
  plugins/PagePerformance/tests/UI/PagePerformance_spec.js
  tests/UI/specs/UIIntegration_spec.js
  tests/angularjs/karma.conf.js
Labels: Needs Review

#18431 [Vue] add site selector model adapter and fix siteselector.vue bug
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/angularjs/siteselector/siteselector-model.service.js
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/SiteSelector/SitesStore.adapter.ts
  plugins/CoreHome/vue/src/index.ts
Labels: Do not close

#18507 [Vue] fix infinite loop when using custom field angularjs template
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/FormField/FieldAngularJsTemplate.vue
Labels: Needs Review

#18508 Merge 4.6.x patches back to main branch
  core/Updates/4.6.0-b4.php
  core/Updates/4.6.2-rc2.php
  plugins/CoreHome/vue/src/ExpandOnClick/ExpandOnClick.ts
  plugins/CoreHome/vue/src/Matomo/Matomo.adapter.ts
  plugins/CoreUpdater/Commands/ConvertToUtf8mb4.php
Labels: not-in-changelog

#18502 Translations update from Hosted Weblate
  lang/nb.json
  lang/sv.json
  plugins/API/lang/de.json
  plugins/API/lang/el.json
  plugins/Actions/lang/nb.json
  plugins/Contents/lang/nb.json
  plugins/CoreAdminHome/lang/nb.json
  plugins/CoreHome/lang/nb.json
  plugins/CorePluginsAdmin/lang/nb.json
  plugins/CoreUpdater/lang/it.json
  plugins/CoreUpdater/lang/nb.json
  plugins/CustomDimensions/lang/nb.json
  plugins/DevicesDetection/lang/nb.json
  plugins/Diagnostics/lang/de.json
  plugins/Diagnostics/lang/el.json
  plugins/Diagnostics/lang/nb.json
  plugins/Ecommerce/lang/nb.json
  plugins/Ecommerce/lang/sv.json
  plugins/Events/lang/nb.json
  plugins/Feedback/lang/nb.json
  plugins/Goals/lang/nb.json
  plugins/Goals/lang/sv.json
  plugins/Installation/lang/nb.json
  plugins/Installation/lang/sv.json
  plugins/Live/lang/nb.json
  plugins/Login/lang/nb.json
  plugins/Marketplace/lang/nb.json
  plugins/MobileMessaging/lang/nb.json
  plugins/PrivacyManager/lang/nb.json
  plugins/Referrers/lang/nb.json
  plugins/ScheduledReports/lang/nb.json
  plugins/SegmentEditor/lang/nb.json
  plugins/SitesManager/lang/nb.json
  plugins/SitesManager/lang/sv.json
  plugins/Tour/lang/nb.json
  plugins/Tour/lang/sv.json
  plugins/UserCountry/lang/nb.json
  plugins/UsersManager/lang/nb.json
  plugins/VisitFrequency/lang/nb.json
  plugins/VisitTime/lang/nb.json
  plugins/VisitsSummary/lang/nb.json
Labels: c: i18n

#18510 Filter metadata API response only when the test is executed for allowed metadata API
  tests/PHPUnit/Framework/TestCase/SystemTestCase.php
Labels: Needs Review

#18503 Ensure updates are always done with super user permission
  core/Updater.php
  plugins/CoreUpdater/Controller.php
Labels: Bug, Needs Review

#18519 Updates coding standard dependencies
  composer.json
  composer.lock
Labels: Task, c: Tests & QA, not-in-changelog

#18493 convert sparkline api to one request - fixes archive
  plugins/Goals/API.php
  plugins/Goals/Controller.php
  plugins/Goals/Pages.php
  plugins/Goals/Reports/Get.php
  plugins/Goals/Reports/GetMetrics.php
  plugins/Goals/tests/UI/expected-screenshots/GoalsPages_overview.png
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getReportPagesMetadata.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getWidgetMetadata.xml
Labels: not-in-changelog, Needs Review

#18515 Fixes: Saving plugin settings might not work with certain password managers enabled
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/PluginSettings/PluginSettings.vue
Labels: Needs Review

#18522 move tracking code below website selector
  plugins/CoreAdminHome/templates/trackingCodeGenerator.twig
  tests/UI/expected-screenshots/UIIntegrationTest_admin_manage_tracking_code.png
Labels: not-in-changelog, Needs Review

#18518 Updates matomo/ini composer dependency
  composer.json
  composer.lock
  plugins/CoreAdminHome/tests/Integration/Commands/SetConfigTest.php
Labels: not-in-changelog, Needs Review

#18514 Fixes more issues on PHP 8.1
  config/environment/ui-test.php
  core/SettingsPiwik.php
  plugins/API/Filter/DataComparisonFilter/ComparisonRowGenerator.php
  plugins/CoreVisualizations/Visualizations/Sparklines.php
  plugins/SitesManager/SitesManager.php
  tests/PHPUnit/Fixtures/DisablePluginArchive.php
Labels: Needs Review

#18513 Translations update from Hosted Weblate
  lang/fr.json
  plugins/API/lang/fr.json
  plugins/API/lang/ja.json
  plugins/API/lang/tr.json
  plugins/Actions/lang/fr.json
  plugins/CoreAdminHome/lang/fr.json
  plugins/CoreAdminHome/lang/ja.json
  plugins/CoreHome/lang/fr.json
  plugins/CoreHome/lang/ja.json
  plugins/CoreHome/lang/tr.json
  plugins/CorePluginsAdmin/lang/nb.json
  plugins/CustomDimensions/lang/nb.json
  plugins/Diagnostics/lang/fr.json
  plugins/Diagnostics/lang/tr.json
  plugins/Ecommerce/lang/nb.json
  plugins/Feedback/lang/fr.json
  plugins/Feedback/lang/ja.json
  plugins/Feedback/lang/nb.json
  plugins/Installation/lang/fr.json
  plugins/Installation/lang/ja.json
  plugins/Installation/lang/tr.json
  plugins/Live/lang/nb.json
  plugins/Login/lang/fr.json
  plugins/Login/lang/ja.json
  plugins/MobileMessaging/lang/nb.json
  plugins/MultiSites/lang/fr.json
  plugins/MultiSites/lang/nb.json
  plugins/Overlay/lang/nb.json
  plugins/PrivacyManager/lang/fr.json
  plugins/ProfessionalServices/lang/hr.json
  plugins/Referrers/lang/ja.json
  plugins/Referrers/lang/nb.json
  plugins/SegmentEditor/lang/nb.json
  plugins/SitesManager/lang/fr.json
  plugins/SitesManager/lang/ja.json
  plugins/SitesManager/lang/tr.json
  plugins/Transitions/lang/fr.json
  plugins/Transitions/lang/ja.json
  plugins/UserId/lang/ja.json
  plugins/UsersManager/lang/fr.json
  plugins/UsersManager/lang/ja.json
  plugins/VisitFrequency/lang/nb.json
  plugins/VisitTime/lang/nb.json
  plugins/Widgetize/lang/fr.json
Labels: c: i18n

#18433 [Vue] migrate remaining directives in CorePluginsAdmin
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/AjaxHelper/AjaxHelper.ts
  plugins/CoreHome/vue/src/createAngularJsAdapter.ts
  plugins/CorePluginsAdmin/angularjs/form/form.directive.js
  plugins/CorePluginsAdmin/angularjs/plugins/plugin-filter.directive.js
  plugins/CorePluginsAdmin/angularjs/plugins/plugin-management.directive.js
  plugins/CorePluginsAdmin/angularjs/plugins/plugin-upload.directive.js
  plugins/CorePluginsAdmin/angularjs/save-button/save-button.directive.html
  plugins/CorePluginsAdmin/angularjs/save-button/save-button.directive.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/Form/Form.adapter.ts
  plugins/CorePluginsAdmin/vue/src/Form/Form.ts
  plugins/CorePluginsAdmin/vue/src/Plugins/PluginFilter.adapter.ts
  plugins/CorePluginsAdmin/vue/src/Plugins/PluginFilter.ts
  plugins/CorePluginsAdmin/vue/src/Plugins/PluginManagement.adapter.ts
  plugins/CorePluginsAdmin/vue/src/Plugins/PluginManagement.ts
  plugins/CorePluginsAdmin/vue/src/Plugins/PluginUpload.adapter.ts
  plugins/CorePluginsAdmin/vue/src/Plugins/PluginUpload.ts
  plugins/CorePluginsAdmin/vue/src/SaveButton/SaveButton.adapter.ts
  plugins/CorePluginsAdmin/vue/src/SaveButton/SaveButton.vue
  plugins/CorePluginsAdmin/vue/src/index.ts
  plugins/Referrers/angularjs/campaign-builder/campaign-builder.controller.js
Labels: Needs Review, Do not close

#18065 Show a summary of new features
  core/Changes/Model.php
  core/Changes/UserChanges.php
  core/Db/Schema/Mysql.php
  core/Menu/MenuAbstract.php
  core/Plugin.php
  core/Updates/4.7.0-b2.php
  core/Version.php
  plugins/CoreAdminHome/Controller.php
  plugins/CoreAdminHome/CoreAdminHome.php
  plugins/CoreAdminHome/Menu.php
  plugins/CoreAdminHome/lang/en.json
  plugins/CoreAdminHome/stylesheets/whatIsNew.less
  plugins/CoreAdminHome/templates/whatIsNew.twig
  plugins/CoreAdminHome/tests/UI/expected-screenshots/CustomLogo_admin.png
  plugins/CoreAdminHome/tests/UI/expected-screenshots/CustomLogo_admin_svg.png
  plugins/CoreHome/Controller.php
  plugins/CoreHome/templates/_topBar.twig
  plugins/CoreHome/tests/Integration/ChangesTest.php
  plugins/CoreHome/tests/UI/Changes_spec.js
  plugins/CoreHome/tests/UI/expected-screenshots/Changes_show_popover.png
  plugins/CoreHome/tests/UI/expected-screenshots/ShowChanges_view.png
  plugins/CorePluginsAdmin/CorePluginsAdmin.php
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_create_new.png
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_removed.png
  plugins/ExamplePlugin/changes.json
  plugins/Login/tests/UI/expected-screenshots/Login_bruteforcelog_noentries.png
  plugins/Login/tests/UI/expected-screenshots/Login_bruteforcelog_withentries.png
  plugins/Morpheus/fonts/matomo.svg
  plugins/Morpheus/fonts/matomo.ttf
  plugins/Morpheus/fonts/matomo.woff
  plugins/Morpheus/fonts/matomo.woff2
  plugins/Morpheus/fonts/selection.json
  plugins/Morpheus/stylesheets/base/icons.css
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_complex_segment.png
  plugins/Transitions/Transitions.php
  plugins/UsersManager/API.php
  plugins/UsersManager/Model.php
  plugins/UsersManager/tests/Integration/UsersManagerTest.php
  plugins/UsersManager/tests/System/ApiTest.php
  tests/PHPUnit/Fixtures/CreateChanges.php
  tests/UI/expected-screenshots/Menus_mobile_top.png
  tests/UI/expected-screenshots/QuickAccess_search_1.png
  tests/UI/expected-screenshots/QuickAccess_search_category.png
  tests/UI/expected-screenshots/SupportedBrowser_page_loads_when_browser_supported.png
  tests/UI/expected-screenshots/Theme_home.png
  tests/UI/expected-screenshots/UIIntegrationTest_period_select_date_range_click.png
  tests/UI/expected-screenshots/enable_framed_pages_embed_whole_app.png
Labels: not-in-changelog, Needs Review, Do not close

#18529 Translations update from Hosted Weblate
  lang/fr.json
  lang/it.json
  lang/zh-cn.json
  plugins/CoreAdminHome/lang/el.json
  plugins/CoreAdminHome/lang/zh-cn.json
  plugins/CoreHome/lang/de.json
  plugins/MultiSites/lang/nb.json
  plugins/PrivacyManager/lang/nb.json
  plugins/Referrers/lang/nb.json
Labels: c: i18n

#18440 [Vue] migrate report export directive and popover
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/angularjs/common/directives/field-condition.js
  plugins/CoreHome/angularjs/common/directives/ignore-click.js
  plugins/CoreHome/angularjs/common/directives/onenter.js
  plugins/CoreHome/angularjs/common/directives/select-on-focus.js
  plugins/CoreHome/angularjs/content-intro/content-intro.directive.js
  plugins/CoreHome/angularjs/content-table/content-table.directive.js
  plugins/CoreHome/angularjs/report-export/reportexport.directive.js
  plugins/CoreHome/angularjs/report-export/reportexport.popover.html
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/Matomo/Matomo.adapter.ts
  plugins/CoreHome/vue/src/Notification/Notifications.store.ts
  plugins/CoreHome/vue/src/ReportExport/ReportExport.adapter.ts
  plugins/CoreHome/vue/src/ReportExport/ReportExport.less
  plugins/CoreHome/vue/src/ReportExport/ReportExport.ts
  plugins/CoreHome/vue/src/ReportExport/ReportExportPopover.vue
  plugins/CoreHome/vue/src/SelectOnFocus/SelectOnFocus.adapter.ts
  plugins/CoreHome/vue/src/SelectOnFocus/SelectOnFocus.ts
  plugins/CoreHome/vue/src/createAngularJsAdapter.ts
  plugins/CoreHome/vue/src/createVueApp.ts
  plugins/CoreHome/vue/src/index.ts
  plugins/CoreVue/types/index.d.ts
  tests/UI/expected-screenshots/ViewDataTableTest_export_options.png
  tests/UI/expected-screenshots/ViewDataTableTest_export_options_2.png
  tests/UI/specs/ReportExporting_spec.js
Labels: Needs Review, Do not close

#18542 [Vue] remove support in vue for FormField.allSettings
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/FormField/FieldTextareaArray.vue
  plugins/CorePluginsAdmin/vue/src/FormField/FormField.adapter.ts
  plugins/CorePluginsAdmin/vue/src/FormField/FormField.vue
Labels: not-in-changelog, Needs Review

#18442 [Vue] migrate some smaller components in CoreHome
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/angularjs/content-intro/content-intro.directive.js
  plugins/CoreHome/angularjs/content-table/content-table.directive.js
  plugins/CoreHome/angularjs/progressbar/progressbar.directive.html
  plugins/CoreHome/angularjs/progressbar/progressbar.directive.js
  plugins/CoreHome/angularjs/progressbar/progressbar.directive.less
  plugins/CoreHome/angularjs/sparkline/sparkline.component.js
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/AjaxHelper/AjaxHelper.ts
  plugins/CoreHome/vue/src/ContentIntro/ContentIntro.adapter.ts
  plugins/CoreHome/vue/src/ContentIntro/ContentIntro.ts
  plugins/CoreHome/vue/src/ContentTable/ContentTable.adapter.ts
  plugins/CoreHome/vue/src/ContentTable/ContentTable.ts
  plugins/CoreHome/vue/src/Progressbar/Progressbar.adapter.ts
  plugins/CoreHome/vue/src/Progressbar/Progressbar.less
  plugins/CoreHome/vue/src/Progressbar/Progressbar.vue
  plugins/CoreHome/vue/src/Sparkline/Sparkline.adapter.ts
  plugins/CoreHome/vue/src/Sparkline/Sparkline.less
  plugins/CoreHome/vue/src/Sparkline/Sparkline.vue
  plugins/CoreHome/vue/src/index.ts
  plugins/CoreVue/types/index.d.ts
  plugins/Diagnostics/tests/UI/expected-screenshots/Diagnostics_page.png
  plugins/Installation/templates/_systemCheckSection.twig
  plugins/Morpheus/stylesheets/uibase/_loading.less
  plugins/Morpheus/tests/UI/expected-screenshots/Morpheus_load.png
  tests/UI/expected-screenshots/Theme_demo.png
  tests/UI/expected-screenshots/ViewDataTableTest_export_options_2.png
Labels: Needs Review, Do not close

#18443 [Vue] migrate ajax-form directive to vue
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/angularjs/ajax-form/ajax-form.controller.js
  plugins/CoreHome/angularjs/ajax-form/ajax-form.directive.js
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/AjaxForm/AjaxForm.adapter.ts
  plugins/CoreHome/vue/src/AjaxForm/AjaxForm.vue
  plugins/CoreHome/vue/src/index.ts
Labels: Needs Review, Do not close
