Repository matomo-org/matomo, pull requests merged in 2021-06, with the labels that each got.

#17617 insert invalidations for segment archives that get invalidated when invalidating all visits archives
  core/DataAccess/Model.php
  tests/PHPUnit/Integration/DataAccess/ArchiveInvalidatorTest.php
Labels: Bug, Needs Review

#17576 Do not use which when determining if ps and awk are available
  core/CliMulti/Process.php
  lang/en.json
  plugins/Diagnostics/Diagnostic/CronArchivingCheck.php
Labels: Needs Review

#17548 turn on github actions
  .github/workflows/follow-up-reviews.yml
  .github/workflows/inactive-prs-closing-message.yaml
  .github/workflows/inactive-prs.yaml
Labels: Needs Review, not-in-changelog

#17645 fix usort() in SQL Profiler
  core/Profiler.php
Labels: not-in-changelog

#17382 use strict-origin-when-cross-origin Referrer-Policy
  core/View.php
Labels: Needs Review, Stale

#17656 fix regression
  core/DataTable.php
  plugins/Insights/DataTable/Filter/Insight.php
  tests/PHPUnit/Fixtures/ManyVisitsWithMockLocationProvider.php
  tests/PHPUnit/System/BlobReportLimitingTest.php
  tests/PHPUnit/System/expected/test_reportLimiting_rankingQueryDisabled__Insights.getInsightsOverview_day.xml
Labels: Needs Review, not-in-changelog

#17659 rebuild tracker javascript
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: not-in-changelog

#17663 Updates some npm dependencies for screenshot tests
  tests/lib/screenshot-testing/package-lock.json
  tests/lib/screenshot-testing/package.json
Labels: Needs Review, c: Tests & QA, not-in-changelog

#17526 Check if config loaded in getHostname()
  core/Config.php
  plugins/Diagnostics/Diagnostic/CronArchivingLastRunCheck.php
Labels: Needs Review

#17661 Ensure redirects from logme method are only done to trusted hosts
  CHANGELOG.md
  plugins/Login/Controller.php
  plugins/Login/tests/UI/Login_spec.js
  plugins/Login/tests/UI/expected-screenshots/Login_logme_redirect_invalid.png
Labels: Needs Review, c: Security

#17664 Add some extra information when two non-summable columns are added together for debugging purposes.
  core/DataTable/Row.php
Labels: Needs Review

#17666 use correct event handler in login plugin
  plugins/Login/Login.php
Labels: Bug

#17665 Disable logme functionality by default
  CHANGELOG.md
  config/global.ini.php
  core/Updates/4.4.0-b1.php
  core/Version.php
  plugins/Login/Controller.php
  plugins/Login/tests/UI/Login_spec.js
  plugins/Login/tests/UI/expected-screenshots/Login_logme_disabled.png
  plugins/TwoFactorAuth/tests/UI/TwoFactorAuth_spec.js
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: Needs Review, c: Security

#17668 Move tests documentation to developer website
  tests/README.md
  tests/README.testing-data.md
  tests/README.troubleshooting.md
  tests/javascript/README.md
Labels: Needs Review

#17660 Ignore invalid capabilities instead of throwing an exception
  plugins/UsersManager/API.php
Labels: Needs Review

#17670 Ensure DbException is thrown correctly
  core/Tracker.php
Labels: Bug, Needs Review

#17673 Removing hardcoded strings and adding new translation strings for "We…
  plugins/SitesManager/SitesManager.php
  plugins/SitesManager/angularjs/sites-manager/sites-manager-site.controller.js
  plugins/SitesManager/lang/en.json
Labels: Needs Review, not-in-changelog

#17674 Fix UI tests
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_create_new.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_reset.png
  plugins/Login/tests/UI/Login_spec.js
  plugins/SEO/tests/UI/SeoWidget_spec.js
  plugins/SEO/tests/UI/expected-ui-screenshots/SeoWidgetTest_widget.png
Labels: not-in-changelog

#17671 Improvements to site type detection (added Drupal and WebFlow)
  config/global.php
  core/Http.php
  plugins/SitesManager/Controller.php
  plugins/SitesManager/GtmSiteTypeGuesser.php
  plugins/SitesManager/SitesManager.php
  tests/PHPUnit/Integration/HttpTest.php
Labels: Needs Review

#17678 Fix parameters of UsersManager.addUser.end event
  plugins/UsersManager/API.php
Labels: Needs Review, Regression

#17676 check bound parameters for Date instances if in development mode
  core/Db.php
Labels: Needs Review, not-in-changelog

#17682 Remove PR template file as it's now global
  .github/pull_request_template.md
Labels: Needs Review

#17681 Improves detection of local hostnames
  core/Url.php
  plugins/SitesManager/Controller.php
Labels: Needs Review

#17684 Add check for setting max_execution_time = -1, see #17585
  plugins/Diagnostics/Diagnostic/PhpSettingsCheck.php
  plugins/Diagnostics/tests/UI/expected-screenshots/Diagnostics_page.png
  plugins/Installation/tests/UI/expected-screenshots/Installation_system_check.png
Labels: not-in-changelog

#17677 Ensure login is correctly detected for brute force detection when using logme feature
  plugins/Login/Login.php
Labels: Needs Review, c: Security

#17527 Add link to new FAQ how to make the diagnostic “Managing processes via CLI” show Ok
  plugins/Diagnostics/Diagnostic/CronArchivingCheck.php
  plugins/Diagnostics/Diagnostic/DiagnosticResult.php
  plugins/Installation/templates/_systemCheckSection.twig
Labels: Needs Review, c: Platform

#17675 Make sure overlay API requests send force_api_session as POST param
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  plugins/Overlay/javascripts/Piwik_Overlay.js
Labels: Bug, Needs Review

#17688 pass array to Db::fetchOne()
  core/Option.php
Labels: Needs Review, Task

#17687 don't pass null as a glob() flag
  core/Filesystem.php
  tests/PHPUnit/System/CliMultiTest.php
Labels: Needs Review, Task

#17693 allow empty site list
  core/Site.php
  plugins/CoreConsole/Commands/CoreArchiver.php
Labels: Needs Review, Task

#17702 Update notify list for github stale actions
  .github/workflows/follow-up-reviews.yml
  .github/workflows/inactive-prs-closing-message.yaml
Labels: not-in-changelog

#17694 Fix permission checks for siteWithoutData methods
  plugins/SitesManager/Controller.php
Labels: Bug, Needs Review

#17705 Use team mention for github stale actions
  .github/workflows/follow-up-reviews.yml
  .github/workflows/inactive-prs-closing-message.yaml
Labels: Needs Review, not-in-changelog

#17704 Allow changing row limit when hierarchy is expanded
  plugins/Actions/tests/UI/expected-screenshots/ActionsDataTable_auto_expand.png
  plugins/Actions/tests/UI/expected-screenshots/ActionsDataTable_subtables_loaded.png
  plugins/CoreHome/javascripts/dataTable.js
  plugins/PagePerformance/tests/UI/expected-screenshots/PagePerformance_rowactions_subtable.png
Labels: Needs Review, not-in-changelog

#17703 Web cron archive - allow POST'd token_auth
  misc/cron/archive.php
Labels: not-in-changelog

#17685 Remove type attribute from tracking code
  plugins/Installation/tests/UI/expected-screenshots/Installation_js_tracking.png
  plugins/Morpheus/templates/javascriptCode.twig
  plugins/SitesManager/tests/System/expected/test_SitesManager_after3_7_0__SitesManager.getJavascriptTag.xml
  plugins/SitesManager/tests/System/expected/test_SitesManager_prior3_7_0__SitesManager.getJavascriptTag.xml
  plugins/SitesManager/tests/System/expected/test_SitesManager_prior3_7_0_but_forced__SitesManager.getJavascriptTag.xml
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_permissions_bulk_access_set.png
  tests/PHPUnit/Integration/Tracker/TrackerCodeGeneratorTest.php
  tests/PHPUnit/System/expected/test_apiGetReportMetadata_year__SitesManager.getJavascriptTag.xml
  tests/UI/expected-screenshots/EmptySite_emptySiteDashboard.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_manage_tracking_code.png
Labels: Needs Review, not-in-changelog

#17698 Add info about custom segments in archiving setting
  lang/en.json
  plugins/CoreAdminHome/Controller.php
  plugins/CoreAdminHome/templates/generalSettings.twig
  tests/UI/expected-screenshots/UIIntegrationTest_admin_settings_general.png
Labels: Needs Review, not-in-changelog

#17472 Add some context to this error since logs will not have the host or instance or other information.
  core/Exception/NotYetInstalledException.php
  plugins/Monolog/Processor/ExceptionToTextProcessor.php
  plugins/Monolog/tests/Integration/LogTest.php
  plugins/Monolog/tests/Unit/Processor/ExceptionToTextProcessorTest.php
Labels: Do not close

#17695 Stronger condition to check NFS
  core/Filesystem.php
Labels: Needs Review

#17718 Allow enabling aurora read replica read committed
  core/Db.php
Labels: Needs Review

#17727 Make anchor links on Admin General Settings page work
  plugins/CoreHome/angularjs/anchorLinkFix.js
  plugins/CorePluginsAdmin/angularjs/plugin-settings/plugin-settings.controller.js
Labels: Needs Review

#17728 Fix few bugs in sparklines visualisation when there is no row
  plugins/CoreVisualizations/Visualizations/Sparklines.php
  tests/UI/expected-screenshots/UIIntegrationTest_exampleui_sparklines_no_matching_row.png
  tests/UI/specs/UIIntegration_spec.js
Labels: Bug, Needs Review

#17725 Multisite links to reports now pass token_auth
  plugins/MultiSites/angularjs/site/site.controller.js
  plugins/MultiSites/angularjs/site/site.directive.html
Labels: Needs Review, not-in-changelog
