Repository matomo-org/matomo, pull requests merged in 2021-10, with the labels that each got.

#18085 replace db error message
  core/Tracker/Db.php
Labels: not-in-changelog, Needs Review

#18093 [Vue] add missing file headers
  plugins/CoreHome/vue/src/ActivityIndicator/ActivityIndicator.adapter.ts
  plugins/CoreHome/vue/src/ActivityIndicator/ActivityIndicator.vue
  plugins/CoreHome/vue/src/Alert/Alert.adapter.ts
  plugins/CoreHome/vue/src/Alert/Alert.vue
  plugins/CoreHome/vue/src/index.ts
  plugins/CoreHome/vue/src/translate.ts
  plugins/CoreVue/polyfills/src/index.ts
  plugins/ExampleVue/vue/src/ExampleComponent/ExampleComponent.adapter.ts
  plugins/ExampleVue/vue/src/ExampleComponent/ExampleComponent.vue
  plugins/ExampleVue/vue/src/index.ts
Labels: not-in-changelog, Needs Review

#18095 Update CA bundle
  composer.lock
Labels: not-in-changelog, Needs Review

#18035 Icon for "Report generated X min ago" displayed for "Today" is too small
  lang/en.json
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/angularjs/enrichedheadline/enrichedheadline.directive.html
  plugins/CoreHome/angularjs/enrichedheadline/enrichedheadline.directive.js
  plugins/CoreHome/angularjs/enrichedheadline/enrichedheadline.directive.less
  plugins/Morpheus/tests/UI/expected-screenshots/Morpheus_load.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_permissions_bulk_access_set.png
  tests/UI/expected-screenshots/Theme_demo.png
  tests/UI/expected-screenshots/UIIntegrationTest_actions_pages_tooltip_help.png
Labels: not-in-changelog, Needs Review

#18060 add php binary format check
  plugins/Diagnostics/Diagnostic/PHPBinaryCheck.php
  plugins/Diagnostics/config/config.php
  plugins/Diagnostics/tests/UI/expected-screenshots/Diagnostics_page.png
  plugins/Installation/lang/en.json
  plugins/Installation/tests/UI/expected-screenshots/Installation_system_check.png
Labels: not-in-changelog, Needs Review

#18077 'Users' or 'UserId' tab no data: explain how to populate Users report data
  plugins/UserId/Categories/VisitorsUserSubcategory.php
  plugins/UserId/Reports/GetUsers.php
  plugins/UserId/lang/en.json
Labels: not-in-changelog, Needs Review

#18100 fix the xml on test
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getReportPagesMetadata.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getWidgetMetadata.xml
Labels: not-in-changelog

#18102 [Vue] fix error in tsconfig.json (include matching no files)
  plugins/ExampleVue/vue/dist/ExampleVue.umd.1.js
  plugins/ExampleVue/vue/dist/ExampleVue.umd.1.js.map
  plugins/ExampleVue/vue/dist/ExampleVue.umd.js
  plugins/ExampleVue/vue/dist/ExampleVue.umd.js.map
  plugins/ExampleVue/vue/dist/ExampleVue.umd.min.1.js.map
  plugins/ExampleVue/vue/dist/ExampleVue.umd.min.js
  plugins/ExampleVue/vue/dist/ExampleVue.umd.min.js.map
  tsconfig.json
  tsconfig.spec.json
Labels: not-in-changelog, Needs Review

#18242 [Vue] make sure transcluded content is processed before query selectors in EnrichedHeadline
  .github/workflows/buildvue.yml
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/EnrichedHeadline/EnrichedHeadline.vue
Labels: not-in-changelog, Needs Review

#18237 Translations update from Weblate
  plugins/CoreAdminHome/lang/el.json
  plugins/PrivacyManager/lang/pt-br.json
Labels: c: i18n
