Repository matomo-org/matomo, pull requests merged in 2022-01, with the labels that each got.

#18445 [Vue] migrate popover handler to popover service
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/angularjs/popover-handler/popover-handler.directive.js
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/PopoverHandler/PopoverHandler.ts
  plugins/CoreHome/vue/src/index.ts
  plugins/CoreVue/types/index.d.ts
  plugins/Overlay/javascripts/Piwik_Overlay.js
Labels: Needs Review, Do not close

#18446 [Vue] migrate smaller core home common directives and deprecate others
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/angularjs/common/directives/attributes.js
  plugins/CoreHome/angularjs/common/directives/autocomplete-matched.js
  plugins/CoreHome/angularjs/common/directives/dropdown-button.js
  plugins/CoreHome/angularjs/common/directives/show-sensitive-data.js
  plugins/CoreHome/angularjs/common/directives/translate.js
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/DropdownButton/DropdownButton.adapter.ts
  plugins/CoreHome/vue/src/DropdownButton/DropdownButton.ts
  plugins/CoreHome/vue/src/ShowSensitiveData/ShowSensitiveData.adapter.ts
  plugins/CoreHome/vue/src/ShowSensitiveData/ShowSensitiveData.ts
  plugins/CoreHome/vue/src/index.ts
  tests/UI/specs/EvolutionGraph_spec.js
Labels: Needs Review, Do not close

#18532 Change log entry for the new change notifications feature
  CHANGELOG.md
Labels: not-in-changelog, Needs Review, c: Documentation, Stale

#18543 Translations update from Hosted Weblate
  lang/id.json
  lang/it.json
  lang/sk.json
  plugins/API/lang/nb.json
  plugins/Annotations/lang/sk.json
  plugins/Contents/lang/nb.json
  plugins/CoreAdminHome/lang/id.json
  plugins/CoreAdminHome/lang/tr.json
  plugins/CoreHome/lang/id.json
  plugins/CoreHome/lang/nb.json
  plugins/CustomJsTracker/lang/id.json
  plugins/Ecommerce/lang/nb.json
  plugins/Events/lang/nb.json
  plugins/Feedback/lang/nb.json
  plugins/GeoIp2/lang/nb.json
  plugins/Goals/lang/id.json
  plugins/Installation/lang/hu.json
  plugins/Installation/lang/id.json
  plugins/Live/lang/nb.json
  plugins/Login/lang/nb.json
  plugins/Marketplace/lang/id.json
  plugins/Marketplace/lang/nb.json
  plugins/MobileMessaging/lang/nb.json
  plugins/MultiSites/lang/nb.json
  plugins/Overlay/lang/nb.json
  plugins/PagePerformance/lang/id.json
  plugins/PrivacyManager/lang/id.json
  plugins/Referrers/lang/id.json
  plugins/Referrers/lang/nb.json
  plugins/SegmentEditor/lang/nb.json
  plugins/SitesManager/lang/id.json
  plugins/UserCountry/lang/nb.json
  plugins/UserId/lang/it.json
  plugins/UsersManager/lang/hu.json
  plugins/UsersManager/lang/id.json
  plugins/UsersManager/lang/nb.json
  plugins/VisitFrequency/lang/id.json
  plugins/VisitFrequency/lang/nb.json
  plugins/VisitTime/lang/ja.json
  plugins/VisitTime/lang/nb.json
  plugins/Widgetize/lang/ja.json
Labels: c: i18n

#18547 remove strong type on SendFeedbackForFeature function
  plugins/Feedback/API.php
  plugins/Feedback/tests/Integration/FeedbackTest.php
  plugins/Feedback/vue/dist/Feedback.umd.js
  plugins/Feedback/vue/dist/Feedback.umd.min.js
  plugins/Feedback/vue/src/RateFeature/RateFeature.vue
Labels: not-in-changelog, Needs Review

#18525 Installation pages send API request to API.getPagesComparisonsDisabledFor
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/Comparisons/Comparisons.store.ts
  plugins/Feedback/vue/dist/Feedback.umd.js
  plugins/Feedback/vue/dist/Feedback.umd.min.js
  plugins/Feedback/vue/src/RateFeature/RateFeature.vue
  plugins/Installation/templates/layout.twig
Labels: not-in-changelog

#18540 fix error no data show on campaing
  plugins/SegmentEditor/SegmentEditor.php
Labels: Needs Review

#18535 remove compareDates with comparePeriods when adding new segment
  plugins/SegmentEditor/javascripts/Segmentation.js
Labels: Bug, Do not close

#18589 Fixes some smaller UI regressions
  plugins/CoreHome/vue/src/Progressbar/Progressbar.less
  plugins/Diagnostics/tests/UI/expected-screenshots/Diagnostics_page.png
  plugins/Installation/Controller.php
  plugins/Installation/templates/_systemCheckSection.twig
  plugins/Morpheus/tests/UI/expected-screenshots/Morpheus_load.png
  tests/UI/expected-screenshots/Theme_demo.png
Labels: not-in-changelog

#18526 update Performance Report Average Load Time query
  plugins/PagePerformance/Archiver.php
  tests/PHPUnit/System/expected/test_ImportLogs__PagePerformance.get_month.xml
Labels: not-in-changelog, Needs Review, Stale

#18581 [Vue] handle disabled options in fieldselect
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/FormField/FieldSelect.vue
  plugins/Morpheus/templates/demo.twig
Labels: Needs Review, Regression

#18592 [Vue] add vue ignores to template .gitignore
  plugins/ExamplePlugin/.gitignore
Labels: Needs Review

#18591 [Vue] fixes #18578 better defaulting of date/period/segment in hash
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/angularjs/common/directives/show-sensitive-data.js
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/MatomoUrl/MatomoUrl.ts
  plugins/Morpheus/tests/UI/expected-screenshots/Morpheus_load.png
  tests/UI/expected-screenshots/Theme_demo.png
Labels: not-in-changelog, Needs Review

#18580 [Vue] dropdownmenu directive should be aware of data-target parameter
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/DropdownMenu/DropdownMenu.ts
  plugins/CustomDimensions/tests/UI/CustomDimensions_spec.js
Labels: Bug, Needs Review

#18579 [Vue] workaround vue issue w/ directives that modify css classes on elements that also bind to :class
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/ContentIntro/ContentIntro.ts
  plugins/CoreHome/vue/src/ContentTable/ContentTable.ts
Labels: Bug, Needs Review

#18588 Fix possible error with sparkline colors
  core/Visualization/Sparkline.php
Labels: not-in-changelog, Needs Review

#18593 Refactor 'user info changed' emails away from the generic Mail class
  plugins/UsersManager/API.php
  plugins/UsersManager/Emails/UserInfoChangedEmail.php
Labels: c: Platform

#18577 unifont import, TCPDF use import fonts
  core/ReportRenderer/Pdf.php
Labels: not-in-changelog, Needs Review

#18600 Fix for datatable row sum warning message
  core/DataTable/Row.php
Labels: not-in-changelog

#18533 [Vue] migrate archiving controller and portion of twig template to vue
  plugins/CoreAdminHome/CoreAdminHome.php
  plugins/CoreAdminHome/angularjs/archiving/archiving.controller.js
  plugins/CoreAdminHome/templates/generalSettings.twig
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.js
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.min.js
  plugins/CoreAdminHome/vue/dist/umd.metadata.json
  plugins/CoreAdminHome/vue/src/ArchivingSettings/ArchivingSettings.adapter.ts
  plugins/CoreAdminHome/vue/src/ArchivingSettings/ArchivingSettings.vue
  plugins/CoreAdminHome/vue/src/index.ts
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/vue/src/SiteSelector/SiteRef.ts
  tests/UI/expected-screenshots/UIIntegrationTest_admin_settings_general.png
Labels: Needs Review

#18354 Avoid any archiving queries in Goals Archiver if no goals or ecommerce are active
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment0_noOptions__Live.getLastVisitsDetails_day.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment0_noOptions__Live.getLastVisitsDetails_year.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment1_noOptions__Live.getLastVisitsDetails_day.xml
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_preArchivedSegment1_noOptions__Live.getLastVisitsDetails_year.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_Website2__Goals.getItemsCategory_week.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_Website2__Goals.getItemsName_week.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_Website2__Goals.getItemsSku_week.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_Website2__Goals.get_week.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_html_tables_and_graph__ScheduledReports.generateReport_week.original.html
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_html_tables_only__ScheduledReports.generateReport_week.original.html
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_in_csv__ScheduledReports.generateReport_week.original.csv
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_in_pdf_tables_only__ScheduledReports.generateReport_week.original.pdf
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_in_tsv__ScheduledReports.generateReport_week.original.tsv
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_via_sms_all_sites__ScheduledReports.generateReport_week.original.sms.txt
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItemsmultipleDates_andMultipleWebsites__Goals.getItemsCategory_day.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItemsmultipleDates_andMultipleWebsites__Goals.getItemsName_day.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItemsmultipleDates_andMultipleWebsites__Goals.getItemsSku_day.xml
  plugins/Goals/Archiver.php
  plugins/MultiSites/tests/UI/expected-screenshots/MultiSitesTest_all_websites.png
  plugins/MultiSites/tests/UI/expected-screenshots/MultiSitesTest_all_websites_changed_sort_order.png
  plugins/MultiSites/tests/UI/expected-screenshots/MultiSitesTest_all_websites_page_1.png
  plugins/MultiSites/tests/UI/expected-screenshots/MultiSitesTest_all_websites_search.png
  tests/PHPUnit/Fixtures/FewVisitsWithSetVisitorId.php
  tests/PHPUnit/Fixtures/ManySitesImportedLogs.php
  tests/PHPUnit/Fixtures/ManyVisitsWithMockLocationProvider.php
  tests/PHPUnit/Integration/ArchiveProcessor/LoaderTest.php
  tests/PHPUnit/Integration/ArchiveTest.php
  tests/PHPUnit/System/expected/test_ImportLogs__Live.getLastVisitsDetails_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs_withEnhancedAndLast7__MultiSites.getAll_month.xml
  tests/UI/expected-screenshots/UIIntegrationTest_widgetize_allwebsites.png
Labels: not-in-changelog, Needs Review, Do not close

#18604 Hide commands that don't work on windows
  core/Filechecks.php
Labels: not-in-changelog, Needs Review

#18575 move unsupported Browser check before create session
  core/FrontController.php
  tests/PHPUnit/Integration/FrontControllerTest.php
Labels: not-in-changelog

#18549 [Vue] migrate smtp controller in coreadminhome
  plugins/CoreAdminHome/CoreAdminHome.php
  plugins/CoreAdminHome/angularjs/smtp/mail-smtp.controller.js
  plugins/CoreAdminHome/templates/generalSettings.twig
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.js
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.min.js
  plugins/CoreAdminHome/vue/src/SmtpSettings/SmtpSettings.adapter.ts
  plugins/CoreAdminHome/vue/src/SmtpSettings/SmtpSettings.vue
  plugins/CoreAdminHome/vue/src/index.ts
  plugins/CoreHome/CoreHome.php
Labels: Needs Review

#18597 fix notice when generating documentation
  plugins/CustomDimensions/CustomDimensions.php
Labels: not-in-changelog, Needs Review

#18523 Change rearchive end date from yesterday to today
  core/Archive/ArchiveInvalidator.php
  tests/PHPUnit/Integration/DataAccess/ArchiveInvalidatorTest.php
Labels: Bug, not-in-changelog

#18613 [Vue] use markRaw with FieldAngularJsTemplate to get rid of vue warning
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/FormField/FormField.adapter.ts
Labels: Needs Review

#18611 [Vue] expose notification type
  plugins/CoreHome/vue/src/Notification/Notification.ts
  plugins/CoreHome/vue/src/Notification/Notifications.store.ts
  plugins/CoreHome/vue/src/Notification/index.ts
Labels: Needs Review

#18590 Ignore duplicate entry error when creating a sequence
  core/DataAccess/Model.php
Labels: Bug, c: Tests & QA, Needs Review

#18610 Translations update from Hosted Weblate
  plugins/Actions/lang/nb.json
  plugins/Contents/lang/nb.json
  plugins/CoreAdminHome/lang/de.json
  plugins/CoreAdminHome/lang/nb.json
  plugins/CoreHome/lang/nb.json
  plugins/CorePluginsAdmin/lang/nb.json
  plugins/CoreUpdater/lang/nb.json
  plugins/DevicesDetection/lang/nb.json
  plugins/Events/lang/nb.json
  plugins/Feedback/lang/nb.json
  plugins/GeoIp2/lang/nb.json
  plugins/Goals/lang/nb.json
  plugins/Live/lang/nb.json
  plugins/Login/lang/nb.json
  plugins/Marketplace/lang/nb.json
  plugins/MobileMessaging/lang/nb.json
  plugins/PrivacyManager/lang/nb.json
  plugins/Referrers/lang/nb.json
  plugins/ScheduledReports/lang/nb.json
  plugins/SegmentEditor/lang/nb.json
  plugins/SitesManager/lang/nb.json
  plugins/UsersManager/lang/nb.json
  plugins/VisitTime/lang/nb.json
  plugins/VisitsSummary/lang/nb.json
Labels: c: i18n

#18552 [Vue] migrate tracking code generation controllers to Vue
  plugins/CoreAdminHome/Controller.php
  plugins/CoreAdminHome/CoreAdminHome.php
  plugins/CoreAdminHome/angularjs/trackingcode/imagetrackingcode.controller.js
  plugins/CoreAdminHome/angularjs/trackingcode/jstrackingcode.controller.js
  plugins/CoreAdminHome/templates/trackingCodeGenerator.twig
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.js
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.min.js
  plugins/CoreAdminHome/vue/src/ImageTrackingCodeGenerator/ImageTrackingCodeGenerator.adapter.ts
  plugins/CoreAdminHome/vue/src/ImageTrackingCodeGenerator/ImageTrackingCodeGenerator.vue
  plugins/CoreAdminHome/vue/src/JsTrackingCodeGenerator/JsTrackingCodeGenerator.adapter.ts
  plugins/CoreAdminHome/vue/src/JsTrackingCodeGenerator/JsTrackingCodeGenerator.vue
  plugins/CoreAdminHome/vue/src/index.ts
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/QuickAccess/QuickAccess.vue
  plugins/CoreHome/vue/src/SiteSelector/Site.ts
  plugins/CoreHome/vue/src/SiteSelector/SiteSelector.vue
  plugins/CoreHome/vue/src/SiteSelector/SitesStore.ts
  plugins/CoreHome/vue/src/index.ts
  tests/UI/expected-screenshots/UIIntegrationTest_admin_manage_tracking_code.png
Labels: Needs Review

#18616 Refactor emails about password reset into a Mail sub-class
  plugins/Login/Emails/PasswordResetEmail.php
  plugins/Login/PasswordResetter.php
Labels: Needs Review

#18621 Updated translation key for fingerprint metric which was not defined
  plugins/CoreHome/Columns/VisitorFingerprint.php
Labels: Needs Review

#18623 [Vue] expose clone/cloneThenApply in CoreHome vue UMD
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/index.ts
Labels: Needs Review

#18619 [Vue] do not use button element in piwikHelper.modalConfirm() if it belongs to another nested modal
  plugins/Morpheus/javascripts/piwikHelper.js
Labels: Needs Review

#18614 Fix possible error when generating reports for custom dimensions
  core/Archive.php
  plugins/CustomDimensions/API.php
  plugins/CustomDimensions/tests/Fixtures/TrackVisitsWithCustomDimensionsFixture.php
  plugins/CustomDimensions/tests/System/ApiTest.php
  plugins/CustomDimensions/tests/System/expected/test___ScheduledReports.generateReport_year.original.pdf
Labels: not-in-changelog, Needs Review

#18629 Force period type to 'range' if date is a range when checking chart incomplete periods
  plugins/CoreVisualizations/javascripts/jqplot.js
Labels: Bug

#18599 add disable finger print options
  .eslintignore
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: not-in-changelog, Needs Review, c: Documentation

#18630 [Vue] add fromEntries polyfill and fix spread operator compiling
  babel.config.js
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CoreVue/polyfills/dist/MatomoPolyfills.js
  plugins/CoreVue/polyfills/dist/MatomoPolyfills.min.js
  plugins/CoreVue/polyfills/src/index.ts
Labels: Bug, Needs Review

#18627 [Vue] add --plugin option to print plugin git repo information to compute js asset size command
  plugins/CoreConsole/Commands/ComputeJsAssetSize.php
Labels: Needs Review

#18635 Fix cli multi detection on Windows
  core/CliMulti/Process.php
Labels: not-in-changelog, Needs Review

#18628 [Vue] rename PluginSetting component to GroupedSetting component and refactor condition handling
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/FormField/FormField.vue
  plugins/CorePluginsAdmin/vue/src/GroupedSettings/GroupedSetting.vue
  plugins/CorePluginsAdmin/vue/src/GroupedSettings/GroupedSettings.vue
  plugins/CorePluginsAdmin/vue/src/PluginSettings/PluginSettings.vue
  plugins/CorePluginsAdmin/vue/src/index.ts
Labels: Needs Review

#18644 [Vue] chrome 49 does not support the node prepend method
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/ContentBlock/ContentBlock.vue
Labels: Bug, not-in-changelog

#18642 [Vue] use different abortcontroller polyfill since the previous one does not support firefix 52
  package-lock.json
  package.json
  plugins/CoreVue/polyfills/dist/MatomoPolyfills.js
  plugins/CoreVue/polyfills/dist/MatomoPolyfills.min.js
  plugins/CoreVue/polyfills/src/index.ts
Labels: Needs Review

#18553 [Vue] migrate trackingfailures directive to Vue
  plugins/CoreAdminHome/CoreAdminHome.php
  plugins/CoreAdminHome/angularjs/trackingfailures/trackingfailures.controller.js
  plugins/CoreAdminHome/angularjs/trackingfailures/trackingfailures.directive.html
  plugins/CoreAdminHome/angularjs/trackingfailures/trackingfailures.directive.js
  plugins/CoreAdminHome/tests/UI/TrackingFailures_spec.js
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.js
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.min.js
  plugins/CoreAdminHome/vue/src/TrackingFailures/FailureRow.vue
  plugins/CoreAdminHome/vue/src/TrackingFailures/TrackingFailures.adapter.ts
  plugins/CoreAdminHome/vue/src/TrackingFailures/TrackingFailures.less
  plugins/CoreAdminHome/vue/src/TrackingFailures/TrackingFailures.vue
  plugins/CoreAdminHome/vue/src/index.ts
  plugins/CoreHome/CoreHome.php
Labels: Needs Review

#18626 [Vue] support custom field component in multipair and array field config
  core/Settings/FieldConfig/ArrayField.php
  core/Settings/FieldConfig/MultiPair.php
Labels: Needs Review

#18655 Fix incorrect number of placeholders in translation
  core/Access/RolesProvider.php
Labels: not-in-changelog, Needs Review

#18670 [Vue] fix eager update on array text fields, do not update if values are basically the same
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/FormField/FieldTextArray.vue
  plugins/CorePluginsAdmin/vue/src/FormField/FieldTextareaArray.vue
Labels: Needs Review, Regression

#18383 disable cron task when segment is deleted
  core/CronArchive.php
  tests/PHPUnit/Integration/CronArchiveInvalidSegmentTest.php
Labels: not-in-changelog

#18672 [Vue] do not angularjs watcher in createAngularJsAdapter on first watch execution
  plugins/CoreHome/vue/src/createAngularJsAdapter.ts
Labels: Needs Review

#18671 [Vue] Fixes #18663, make sure $location is initialized early.
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/MatomoUrl/MatomoUrl.adapter.ts
Labels: Needs Review

#18653 add date, period params into common function
  core/Piwik.php
  core/Plugin/Controller.php
  plugins/MultiSites/Controller.php
  plugins/VisitsSummary/Reports/Get.php
Labels: not-in-changelog, Needs Review

#18683 Fixes #18663, make sure $location is initialized early. (#18671)
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/MatomoUrl/MatomoUrl.adapter.ts
Labels: Needs Review

#18680 copy of the other PR
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/createAngularJsAdapter.ts
Labels: not-in-changelog

#18664 Fix possible error when generating PDF reports containing multibyte chars
  core/ReportRenderer/Pdf.php
  tests/PHPUnit/Fixtures/TwoSitesTwoVisitorsDifferentDays.php
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_Actions.getPageTitles_firstSite_lastN__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__Actions.getPageTitles_day.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__Actions.getPageTitles_month.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__Actions.getPageTitles_week.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays__Actions.getPageTitles_year.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idSiteOne___Actions.getPageTitles_day.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idSiteOne___Actions.getPageTitles_month.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idSiteOne___Actions.getPageTitles_week.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idSiteOne___Actions.getPageTitles_year.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_html_row_evolution_graph__ScheduledReports.generateReport_month.original.html
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_html_row_evolution_overEach__ScheduledReports.generateReport_month.original.html
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_html_row_evolution_prevCustomN__ScheduledReports.generateReport_month.original.html
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_html_tables_and_graph__ScheduledReports.generateReport_month.original.html
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_html_tables_only__ScheduledReports.generateReport_month.original.html
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_in_csv__ScheduledReports.generateReport_month.original.csv
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_in_pdf_tables_only__ScheduledReports.generateReport_month.original.pdf
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_in_tsv__ScheduledReports.generateReport_month.original.tsv
Labels: not-in-changelog, Needs Review

#18634 Allow disabling the usage of the default geolocation provider as fallback
  CHANGELOG.md
  config/global.ini.php
  core/Common.php
  lang/en.json
  plugins/GeoIp2/GeoIp2.php
  plugins/GeoIp2/tests/Integration/LocationProviderTest.php
  plugins/UserCountry/Controller.php
  plugins/UserCountry/LocationProvider.php
  plugins/UserCountry/LocationProvider/DefaultProvider.php
  plugins/UserCountry/LocationProvider/DisabledProvider.php
  plugins/UserCountry/VisitorGeolocator.php
  plugins/UserCountry/lang/en.json
  plugins/UserCountry/templates/adminIndex.twig
  plugins/UserCountry/tests/Integration/LocationProviderTest.php
  plugins/UserCountry/tests/UI/expected-screenshots/UserCountry_admin_geoip2.png
  plugins/UserCountry/tests/UI/expected-screenshots/UserCountry_admin_geoip2_no_provider.png
  plugins/UserCountry/tests/UI/expected-screenshots/UserCountry_admin_no_providers.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: not-in-changelog, Needs Review

#18651 Translations update from Hosted Weblate
  lang/ca.json
  lang/da.json
  lang/el.json
  lang/pl.json
  lang/zh-cn.json
  plugins/API/lang/nb.json
  plugins/API/lang/zh-cn.json
  plugins/Contents/lang/ja.json
  plugins/CoreAdminHome/lang/fr.json
  plugins/CoreAdminHome/lang/ja.json
  plugins/CoreAdminHome/lang/pl.json
  plugins/CoreAdminHome/lang/zh-cn.json
  plugins/CoreAdminHome/lang/zh-tw.json
  plugins/CoreUpdater/lang/ta.json
  plugins/CustomDimensions/lang/ja.json
  plugins/Feedback/lang/pl.json
  plugins/GeoIp2/lang/ja.json
  plugins/Installation/lang/de.json
  plugins/Installation/lang/el.json
  plugins/Installation/lang/fr.json
  plugins/Installation/lang/ja.json
  plugins/Installation/lang/nb.json
  plugins/Installation/lang/pl.json
  plugins/Installation/lang/tr.json
  plugins/Installation/lang/zh-cn.json
  plugins/MobileMessaging/lang/ja.json
  plugins/MultiSites/lang/ja.json
  plugins/PrivacyManager/lang/pl.json
  plugins/ProfessionalServices/lang/zh-cn.json
  plugins/TwoFactorAuth/lang/zh-cn.json
  plugins/UserCountry/lang/el.json
  plugins/UsersManager/lang/zh-cn.json
  plugins/VisitFrequency/lang/da.json
  plugins/Widgetize/lang/nb.json
Labels: c: i18n

#18696 set default color value, when key not exist.
  core/Visualization/Sparkline.php
Labels: not-in-changelog, Needs Review

#18666 Run scheduled report tests on any PHP version
  tests/PHPUnit/Framework/Fixture.php
Labels: c: Tests & QA, Needs Review

#18594 add core updater with file access check
  plugins/CoreUpdater/Updater.php
  plugins/CoreUpdater/lang/en.json
  tests/PHPUnit/Fixtures/LatestStableInstall.php
  tests/UI/expected-screenshots/OneClickUpdate_update_fail_permission.png
  tests/UI/specs/OneClickUpdate_spec.js
Labels: not-in-changelog

#18674 [Vue] reference css class not attribute (since that is what is added in vue)
  plugins/CoreHome/vue/src/DropdownMenu/DropdownMenu.less
Labels: Bug, Needs Review, Do not close

#18676 Apply `disableAlwaysUseSendBeacon` first
  js/piwik.js
Labels: Needs Review

#18708 Apply disableAlwaysUseSendBeacon first
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: not-in-changelog
