Repository matomo-org/matomo, pull requests merged in 2022-10, with the labels that each got.

#19624 Deprecate auto sanitize of API parameters & Common::getRequestVar and introduce Request class
  CHANGELOG.md
  core/API/Proxy.php
  core/Common.php
  core/Plugin/API.php
  core/Request.php
  plugins/CoreAdminHome/Controller.php
  plugins/CoreAdminHome/OptOutManager.php
  plugins/CoreUpdater/Controller.php
  plugins/Dashboard/Controller.php
  plugins/Login/Controller.php
  tests/PHPUnit/Unit/DeprecatedMethodsTest.php
  tests/PHPUnit/Unit/RequestTest.php
Labels: Stale

#19798 Updated the text and links in the Matomo Help Centre.
  plugins/Feedback/config/config.php
  plugins/Feedback/lang/en.json
  plugins/Feedback/templates/index.twig
  plugins/Feedback/tests/UI/expected-screenshots/FeedbackForm_show.png
Labels: Needs Review

#19827 Return correct parameter divId for JS opt-out
  plugins/CoreAdminHome/OptOutManager.php
Labels: Bug

#19805 Typofixes
  config/global.ini.php
  core/Access/CapabilitiesProvider.php
  core/Archive/ArchiveInvalidator.php
  core/Auth/Password.php
  core/Columns/Dimension.php
  core/Common.php
  core/Concurrency/LockBackend/MySqlLockBackend.php
  core/CronArchive.php
  core/DataAccess/ArchiveSelector.php
  core/DataAccess/LogAggregator.php
  core/DataAccess/Model.php
  core/DataTable/Filter/Truncate.php
  core/DataTable/Map.php
  core/Plugin/Dimension/VisitDimension.php
  core/Plugin/Report.php
  core/Plugin/Segment.php
  core/Plugin/Tasks.php
  core/Settings/Measurable/MeasurableSettings.php
  core/Settings/Plugin/SystemSettings.php
  core/Settings/Plugin/UserSettings.php
  plugins/CoreAdminHome/API.php
  plugins/CoreAdminHome/tests/Framework/Mock/API.php
Labels: not-in-changelog, Needs Review

#19830 add convenience command to minify tracker JS during development
  js/README.md
  plugins/CoreConsole/Commands/BuildTracker.php
Labels: Needs Review

#19845 Check downloaded referrer spam list for validity
  plugins/CoreAdminHome/Tasks.php
Labels: not-in-changelog, Needs Review

#19853 Goal visits log query: No need to execute the query when there are no idVisits given
  plugins/Goals/VisitorDetails.php
Labels: Needs Review

#19823 Fix Referrers.getKeywordsFromSearchEngineId API for invalid subtable ids
  plugins/Referrers/API.php
  plugins/Referrers/tests/System/ApiTest.php
  plugins/Referrers/tests/System/expected/test_subtableid_invalid__Referrers.getKeywordsFromSearchEngineId_year.xml
  plugins/Referrers/tests/System/expected/test_subtableid_valid__Referrers.getKeywordsFromSearchEngineId_year.xml
Labels: not-in-changelog, Needs Review

#19847 Enable search for software configuration report
  plugins/Resolution/API.php
  plugins/Resolution/Reports/GetConfiguration.php
  tests/PHPUnit/System/expected/test_ImportLogs__Resolution.getConfiguration_month.xml
  tests/PHPUnit/System/expected/test_reportLimiting_flattened__Resolution.getConfiguration_day.xml
Labels: not-in-changelog, Needs Review

#19824 Add spellcheck=false to password inputs
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/FormField/FieldText.vue
  plugins/Feedback/tests/UI/expected-screenshots/FeedbackForm_show.png
  plugins/Login/templates/confirmPassword.twig
  plugins/Login/templates/confirmResetPassword.twig
  plugins/Login/templates/invitation.twig
  plugins/Login/templates/login.twig
  plugins/PrivacyManager/vue/dist/umd.metadata.json
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: Needs Review

#19808 Visits Overview: Remove redundant information for better a11y.
  plugins/CoreVisualizations/templates/macros.twig
Labels: c: Accessibility

#19809 TourEngagement: Remove redundant information for better a11y.
  plugins/Tour/templates/engagement.twig
Labels: Needs Review, c: Accessibility, Stale

#19855 Ensure client hints are always returned as array
  core/Tracker/Request.php
Labels: not-in-changelog, Needs Review

#19858 Fix array to string conversion warning in userOptOut
  plugins/PrivacyManager/Controller.php
Labels: not-in-changelog, Regression

#19834 allow empty excludedReferrers on the global setting
  core/UrlHelper.php
  plugins/SitesManager/API.php
  plugins/SitesManager/tests/Integration/ApiTest.php
Labels: not-in-changelog, Needs Review

#19861 Ensure password check can only throw wrong password error
  core/Plugin/API.php
Labels: Needs Review

#19863 Adds missing escaping
  core/Plugin/Controller.php
Labels: c: Security, Needs Review

#19838 Avoid loading goals data multiple times for goal metrics
  plugins/Goals/Columns/Metrics/GoalSpecificProcessedMetric.php
Labels: c: Performance, Needs Review

#19869 Data retention settings might not be respected on PHP 8
  plugins/PrivacyManager/PrivacyManager.php
Labels: Critical, Needs Review, Regression

#19822 Ensure empty tables also use max width
  plugins/CoreHome/javascripts/dataTable.js
Labels: not-in-changelog, Needs Review

#19870 Fix failures link to Learn More
  plugins/CoreAdminHome/vue/src/TrackingFailures/FailureRow.vue
Labels: Needs Review, Regression

#19875 Build vue.js
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.js
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.min.js
Labels: not-in-changelog

#19891 Revert "Added support to pass segment in Archiving.getIdSitesToMarkArchivesAsInvalidated event"
  CHANGELOG.md
  core/Archive/ArchiveInvalidator.php
Labels: Needs Review

#19890 Pg 820 pass segment
  CHANGELOG.md
  core/Archive/ArchiveInvalidator.php
Labels: Needs Review

#19820 hide parent div of period selector in Visits->`real-time` to improve alignment
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/PeriodSelector/PeriodSelector.vue
  plugins/PrivacyManager/vue/dist/umd.metadata.json
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_realtime_visits.png
  tests/UI/specs/UIIntegration_spec.js
Labels: c: Usability, not-in-changelog, Needs Review

#19795 Adding plugin name checks with 60 characters limit
  CHANGELOG.md
  core/Plugin/Manager.php
  plugins/CoreConsole/Commands/GeneratePlugin.php
  tests/PHPUnit/Integration/Plugin/ManagerTest.php
Labels: Needs Review

#19926 Fix param handling for Controller::getLastUnitGraphAcrossPlugins
  core/Plugin/Controller.php
Labels: not-in-changelog, Needs Review

#19917 Harden check for valid redirect urls in logme method
  plugins/Login/Controller.php
Labels: Needs Review
