Repository matomo-org/matomo, pull requests merged in 2022-07, with the labels that each got.

#19457 [Vue] do not propagate class & style vue entry
  plugins/Morpheus/javascripts/piwikHelper.js
Labels: not-in-changelog

#19444 WebsiteMeasurable plugin language reworked
  plugins/WebsiteMeasurable/lang/en.json
Labels: c: i18n

#19446 Fixes different height of selectors
  plugins/CoreHome/stylesheets/selector.less
Labels: c: Design / UI

#19456 Fixes icon-menu-hamburger size
  plugins/CoreHome/stylesheets/layout.less
Labels: c: Design / UI, Needs Review

#19459 Reworked translations (including test fixes)
  plugins/CustomDimensions/tests/System/expected/test___API.getReportPagesMetadata.xml
  plugins/CustomDimensions/tests/System/expected/test___API.getSegmentsMetadata.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_Metadata_VisitTime.getVisitInformationPerServerTime__API.getProcessedReport_day.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_html_tables_and_graph__ScheduledReports.generateReport_week.original.html
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_html_tables_only__ScheduledReports.generateReport_week.original.html
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_in_csv__ScheduledReports.generateReport_week.original.csv
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_in_pdf_tables_only__ScheduledReports.generateReport_week.original.pdf
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_in_tsv__ScheduledReports.generateReport_week.original.tsv
  plugins/VisitTime/lang/en.json
  plugins/VisitorInterest/lang/en.json
  plugins/WebsiteMeasurable/lang/en.json
  tests/PHPUnit/System/expected/test_ImportLogs__VisitorInterest.getNumberOfVisitsPerVisitDuration_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__VisitorInterest.getNumberOfVisitsPerVisitDuration_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs_siteIdThree_TrackedUsingLogReplayWithFixedSiteId__VisitorInterest.getNumberOfVisitsPerVisitDuration_range.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_sortByProcessedMetric_constantRowsCountShouldKeepEmptyRows__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits__VisitorInterest.getNumberOfVisitsPerVisitDuration_day.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits_bulk_json__API.getBulkRequest.json
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits_bulk_xml__API.getBulkRequest.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits_showColumnsWithProcessedMetrics___API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits_withCookieSupport__VisitorInterest.getNumberOfVisitsPerVisitDuration_day.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_VisitorInterest.getNumberOfVisitsByDaysSinceLast_firstSite_lastN__API.getProcessedReport_day.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_html_tables_and_graph__ScheduledReports.generateReport_month.original.html
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_html_tables_only__ScheduledReports.generateReport_month.original.html
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_in_csv__ScheduledReports.generateReport_month.original.csv
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_in_pdf_tables_only__ScheduledReports.generateReport_month.original.pdf
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_in_tsv__ScheduledReports.generateReport_month.original.tsv
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getAvailableMeasurableTypes.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getGlossaryReports.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getReportMetadata_day.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getReportPagesMetadata.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getSegmentsMetadata.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getWidgetMetadata.xml
  tests/UI/expected-screenshots/UIIntegrationTest_admin_plugins.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_plugins_no_internet.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_visitor_generator.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard4.png
  tests/UI/expected-screenshots/UIIntegrationTest_email_reports_editor.png
  tests/UI/expected-screenshots/UIIntegrationTest_period_select_date_range_click.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_engagement.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_times.png
Labels: c: i18n

#19468 Allow composer plugins for dev dependency codesniffer to fix travis builds.
  composer.json
Labels: c: Tests & QA, Needs Review

#19470 UserLanguage plugin language reworked
  plugins/UserLanguage/lang/en.json
Labels: c: i18n

#19477 UserCountryMap plugin language reworked
  plugins/UserCountryMap/lang/en.json
Labels: c: i18n

#19475 UserId plugin language reworked
  plugins/UserId/lang/en.json
Labels: c: i18n

#19483 [Vue] In SiteSelector adapter, initialize scope.value too so it does not end up changing modelValue to undefined.
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/SiteSelector/SiteSelector.adapter.ts
  plugins/CoreHome/vue/src/SiteSelector/SiteSelector.vue
Labels: Needs Review, Regression

#19472 Translation source string improvements
  plugins/CustomDimensions/tests/System/expected/test___API.getReportPagesMetadata.xml
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_create_new.png
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_small_screen.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_reset.png
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_html_tables_and_graph__ScheduledReports.generateReport_week.original.html
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_html_tables_only__ScheduledReports.generateReport_week.original.html
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_in_csv__ScheduledReports.generateReport_week.original.csv
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_in_pdf_tables_only__ScheduledReports.generateReport_week.original.pdf
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_in_tsv__ScheduledReports.generateReport_week.original.tsv
  plugins/UserCountryMap/lang/en.json
  plugins/UserCountryMap/tests/UI/expected-screenshots/VisitorMap_avg_time_on_site.png
  plugins/UserCountryMap/tests/UI/expected-screenshots/VisitorMap_bounce_rate.png
  plugins/UserId/lang/en.json
  plugins/UserLanguage/lang/en.json
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_html_tables_and_graph__ScheduledReports.generateReport_month.original.html
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_html_tables_only__ScheduledReports.generateReport_month.original.html
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_in_csv__ScheduledReports.generateReport_month.original.csv
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_in_pdf_tables_only__ScheduledReports.generateReport_month.original.pdf
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_in_tsv__ScheduledReports.generateReport_month.original.tsv
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getGlossaryReports.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getReportMetadata_day.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getReportPagesMetadata.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getWidgetMetadata.xml
  tests/PHPUnit/System/expected/test_reportLimitingdimension_2_rankingQuery__CustomDimensions.getCustomDimension_day.xml
  tests/UI/expected-screenshots/UIIntegrationTest_admin_plugins.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_plugins_no_internet.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard3.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard4.png
  tests/UI/expected-screenshots/UIIntegrationTest_email_reports_editor.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_locations_provider.png
  tests/UI/expected-screenshots/enable_framed_pages_embed_whole_app.png
Labels: not-in-changelog, c: i18n

#19491 Allow reading consent removed cookie even if cookies are disabled
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: Needs Review

#19421 Show notification if PHP version is EOL
  core/Plugin/ControllerAdmin.php
Labels: Needs Review

#19508 Fixed incorrect Cuban province names on visitor map
  plugins/UserCountryMap/svg/CUB.svg
Labels: not-in-changelog, Needs Review

#19395 Preserve date range when switching between periods in evolution graphs
  plugins/CoreHome/javascripts/dataTable.js
Labels: not-in-changelog

#19516 Exclude .paypal.com as referrer by default
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  tests/javascript/index.php
Labels: Needs Review

#19490 Fixes row evolution for rows containing encoded entities
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/EnrichedHeadline/EnrichedHeadline.vue
  plugins/CoreVisualizations/javascripts/jqplot.js
  plugins/Feedback/vue/dist/Feedback.umd.js
  plugins/Feedback/vue/dist/Feedback.umd.min.js
  plugins/Feedback/vue/src/RateFeature/RateFeature.vue
  plugins/Goals/API.php
  plugins/Goals/Columns/Metrics/GoalSpecificProcessedMetric.php
  plugins/Goals/Controller.php
  plugins/Goals/Pages.php
  plugins/Goals/Reports/Base.php
  plugins/Goals/Reports/Get.php
  plugins/Goals/VisitorDetails.php
  plugins/Goals/Visualizations/Goals.php
  plugins/Goals/tests/UI/Goals_spec.js
  plugins/Goals/tests/UI/expected-screenshots/Goals_action_goals_row_evolution.png
  plugins/Goals/tests/UI/expected-screenshots/Goals_action_goals_visualization_page_urls.png
  plugins/Goals/tests/UI/expected-screenshots/Goals_action_goals_visualization_page_urls_subtable.png
  plugins/Goals/tests/UI/expected-screenshots/Goals_goals_by_entry_page_titles.png
  plugins/Goals/tests/UI/expected-screenshots/Goals_goals_by_entry_pages.png
  plugins/Goals/tests/UI/expected-screenshots/Goals_goals_by_page_titles.png
  plugins/Goals/tests/UI/expected-screenshots/Goals_goals_by_pages.png
  plugins/Goals/tests/UI/expected-screenshots/Goals_overview.png
  plugins/PagePerformance/javascripts/jqplotStackedBarEvolutionGraph.js
  tests/PHPUnit/Fixtures/SomePageGoalVisitsWithConversions.php
Labels: not-in-changelog

#19529 Fix possible javascript error on marketplace
  plugins/Marketplace/vue/dist/Marketplace.umd.js
  plugins/Marketplace/vue/dist/Marketplace.umd.min.js
  plugins/Marketplace/vue/src/Marketplace/Marketplace.vue
Labels: not-in-changelog, Needs Review, Regression

#19535 update invite email space
  plugins/UsersManager/templates/_userInviteEmail.twig
Labels: Needs Review

#19433 Add 429 response Code UI
  lang/en.json
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/AjaxHelper/AjaxHelper.ts
  plugins/CoreHome/vue/src/ReportingMenu/ReportingMenu.vue
  plugins/CoreHome/vue/src/WidgetLoader/WidgetLoader.vue
  plugins/Dashboard/javascripts/dashboardWidget.js
  plugins/Morpheus/stylesheets/uibase/_loading.less
  plugins/Morpheus/templates/ajaxMacros.twig
Labels: not-in-changelog, Needs Review

#19527 Update HTTPs security check, when client is using HTTP just throw a warning on diagnostic
  config/global.ini.php
  plugins/CoreUpdater/Diagnostic/HttpsUpdateCheck.php
  plugins/CoreUpdater/Updater.php
  plugins/CoreUpdater/tests/Integration/ReleaseChannelTest.php
  plugins/Installation/lang/en.json
  plugins/Marketplace/Api/Client.php
  plugins/Marketplace/config/config.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: Needs Review

#19560 Adds unique index for user email
  core/Db/Schema/Mysql.php
  core/Updates/4.12.0-b2.php
  core/Version.php
Labels: Needs Review

#19552 Improve translation source string
  plugins/Marketplace/lang/en.json
  plugins/Marketplace/templates/overview.twig
Labels: Needs Review, c: i18n

#19548 Translations update from Hosted Weblate
  lang/ca.json
  lang/el.json
  lang/fr.json
  lang/pl.json
  lang/uk.json
  plugins/API/lang/fr.json
  plugins/API/lang/pl.json
  plugins/CoreAdminHome/lang/fr.json
  plugins/DevicesDetection/lang/fr.json
  plugins/DevicesDetection/lang/id.json
  plugins/ImageGraph/lang/fr.json
  plugins/ImageGraph/lang/pl.json
  plugins/Login/lang/fr.json
  plugins/SEO/lang/pl.json
  plugins/Transitions/lang/pl.json
  plugins/UserLanguage/lang/fr.json
  plugins/UsersManager/lang/ca.json
  plugins/UsersManager/lang/el.json
  plugins/UsersManager/lang/id.json
  plugins/VisitTime/lang/fr.json
  plugins/VisitorInterest/lang/fr.json
  plugins/WebsiteMeasurable/lang/id.json
  plugins/Widgetize/lang/fr.json
Labels: c: i18n

#19522 revert refresh button
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/javascripts/refresh-button.js
  plugins/CoreHome/javascripts/top_controls.js
  plugins/CoreHome/lang/de.json
  plugins/CoreHome/lang/en.json
  plugins/CoreHome/stylesheets/layout.less
  plugins/CoreHome/templates/_headerMessage.twig
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_create_new.png
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_expanded.png
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_removed.png
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_widget_list_shown.png
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_widget_preview.png
  plugins/Goals/tests/UI/expected-screenshots/Goals_action_goals_visualization_page_urls.png
  plugins/Goals/tests/UI/expected-screenshots/Goals_action_goals_visualization_page_urls_subtable.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_1_selector_open.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_2_segment_editor_update.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_3_segment_editor_edit_name.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_8_segment_editor_create.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_add_new_and_condition.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_add_new_or_condition.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_autocomplete_capitalized.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_autocomplete_lowercase.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_autocomplete_uppercase.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_complex_segment.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_deleted.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_dimension_drag_drop.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_drag_and_condition.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_drag_or_condition.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_enabled_create_realtime_segments.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_enabled_create_realtime_segments_saved.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_saved.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_saved_details.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_suggested_values.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_updated.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_updated_details.png
  tests/UI/expected-screenshots/PeriodSelector_comparison_checked.png
  tests/UI/expected-screenshots/PeriodSelector_custom_comparison.png
  tests/UI/expected-screenshots/PeriodSelector_date_range_selected.png
  tests/UI/expected-screenshots/PeriodSelector_day_selected.png
  tests/UI/expected-screenshots/PeriodSelector_expanded.png
  tests/UI/expected-screenshots/PeriodSelector_invalid.png
  tests/UI/expected-screenshots/PeriodSelector_month_changed.png
  tests/UI/expected-screenshots/PeriodSelector_month_selected.png
  tests/UI/expected-screenshots/PeriodSelector_range_picker_displayed.png
  tests/UI/expected-screenshots/PeriodSelector_year_changed.png
  tests/UI/expected-screenshots/PeriodSelector_year_selected.png
  tests/UI/expected-screenshots/SupportedBrowser_page_loads_when_browser_supported.png
  tests/UI/expected-screenshots/Theme_home.png
  tests/UI/expected-screenshots/UIIntegrationTest_period_select_date_range_click.png
  tests/UI/expected-screenshots/UIIntegrationTest_shortcuts.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_overview_segment.png
  tests/UI/expected-screenshots/enable_framed_pages_embed_whole_app.png
Labels: not-in-changelog

#19561 Fix possible notices / code improvements
  core/Plugin/Report.php
  core/SettingsPiwik.php
  plugins/Actions/DataTable/Filter/Actions.php
Labels: not-in-changelog, Needs Review

#19525 Refactor and improve password confirmation in UI & API
  CHANGELOG.md
  core/Piwik.php
  core/Plugin/API.php
  core/View.php
  plugins/CorePluginsAdmin/API.php
  plugins/CorePluginsAdmin/CorePluginsAdmin.php
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/PasswordConfirmation/PasswordConfirmation.less
  plugins/CorePluginsAdmin/vue/src/PasswordConfirmation/PasswordConfirmation.vue
  plugins/CorePluginsAdmin/vue/src/PluginSettings/PluginSettings.less
  plugins/CorePluginsAdmin/vue/src/PluginSettings/PluginSettings.vue
  plugins/CorePluginsAdmin/vue/src/index.ts
  plugins/CoreVue/types/index.d.ts
  plugins/Morpheus/templates/_jsGlobalVariables.twig
  plugins/PrivacyManager/API.php
  plugins/PrivacyManager/Controller.php
  plugins/PrivacyManager/PrivacyManager.php
  plugins/PrivacyManager/templates/privacySettings.twig
  plugins/PrivacyManager/tests/UI/PrivacyManager_spec.js
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_anonymizelogdata_anonymizeip_and_visit_column_confirmation_message.png
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.js
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.min.js
  plugins/PrivacyManager/vue/src/AnonymizeLogData/AnonymizeLogData.vue
  plugins/PrivacyManager/vue/src/DeleteOldLogs/DeleteOldLogs.vue
  plugins/PrivacyManager/vue/src/DeleteOldReports/DeleteOldReports.vue
  plugins/PrivacyManager/vue/src/ReportDeletionSettings/ReportDeletionSettings.store.ts
  plugins/PrivacyManager/vue/src/ScheduleReportDeletion/ScheduleReportDeletion.vue
  plugins/TwoFactorAuth/tests/UI/TwoFactorAuthUsersManager_spec.js
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuthUsersManager_edit_with_2fa.png
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuthUsersManager_edit_with_2fa_reset_confirm.png
  plugins/UsersManager/API.php
  plugins/UsersManager/tests/UI/UserSettings_spec.js
  plugins/UsersManager/tests/UI/UsersManager_spec.js
  plugins/UsersManager/tests/UI/expected-screenshots/UserSettings_asks_confirmation.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_edit_user_basic_asks_confirmation.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_superuser_confirm.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_superuser_set.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_superuser_tab.png
  plugins/UsersManager/vue/dist/UsersManager.umd.js
  plugins/UsersManager/vue/dist/UsersManager.umd.min.js
  plugins/UsersManager/vue/src/PersonalSettings/PersonalSettings.vue
  plugins/UsersManager/vue/src/UserEditForm/UserEditForm.less
  plugins/UsersManager/vue/src/UserEditForm/UserEditForm.vue
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
Labels: c: Security, c: Usability, Needs Review

#19563 Update change log, add force_matomo_http_request
  CHANGELOG.md
Labels: Needs Review

#19570 [Vue] add isReportingPage() method to replace isAngularRenderingThePage()
  plugins/CoreHome/vue/src/Comparisons/Comparisons.store.spec.ts
  plugins/Morpheus/javascripts/piwikHelper.js
Labels: not-in-changelog

#19376 [Vue] remove angularjs use (except ng-app directive) from Widgetize plugin
  plugins/Widgetize/templates/iframe.twig
  plugins/Widgetize/vue/src/WidgetPreview/WidgetPreview.adapter.ts
Labels: Needs Review, Stale

#19377 [Vue] remove use of enriched headline angularjs directive in VisitsSummary
  plugins/VisitsSummary/templates/index.twig
Labels: Stale

#19403 [Vue] remove use of angularjs from Referrers
  plugins/Referrers/vue/dist/Referrers.umd.js
  plugins/Referrers/vue/dist/Referrers.umd.min.js
  plugins/Referrers/vue/src/CampaignBuilder/CampaignBuilder.adapter.ts
  plugins/Referrers/vue/src/index.ts
Labels: Needs Review, Do not close

#19430 [Vue] remove use of angularjs from ExampleUI plugin
  plugins/ExampleUI/templates/notifications.twig
Labels: Needs Review, Do not close

#19427 [Vue] remove use of angularjs from GeoIp2 plugin
  plugins/GeoIp2/templates/_updaterManage.twig
  plugins/GeoIp2/templates/configuration.twig
  plugins/GeoIp2/vue/dist/GeoIp2.umd.js
  plugins/GeoIp2/vue/dist/GeoIp2.umd.min.js
  plugins/GeoIp2/vue/src/GeoIp2Updater/GeoIp2Updater.vue
  plugins/GeoIp2/vue/src/Geoip2Updater/Geoip2Updater.adapter.ts
  plugins/GeoIp2/vue/src/index.ts
Labels: Needs Review, Do not close

#19407 [Vue] remove use of angularjs from MultiSites
  plugins/MultiSites/Dashboard.php
  plugins/MultiSites/angularjs/dashboard/dashboard.controller.js
  plugins/MultiSites/angularjs/dashboard/dashboard.directive.html
  plugins/MultiSites/angularjs/dashboard/dashboard.directive.js
  plugins/MultiSites/templates/getSitesInfo.twig
  plugins/MultiSites/vue/dist/MultiSites.umd.js
  plugins/MultiSites/vue/dist/MultiSites.umd.min.js
  plugins/MultiSites/vue/src/Dashboard/Dashboard.adapter.ts
  plugins/MultiSites/vue/src/MultisitesSite/MultisitesSite.adapter.ts
  plugins/MultiSites/vue/src/index.ts
Labels: Needs Review, Do not close

#19405 [Vue] remove use of angularjs from PagePerformance plugin
  plugins/PagePerformance/javascripts/PagePerformance.js
  tests/UI/specs/Theme_spec.js
Labels: Needs Review, Do not close

#19567 Remove special handling for setAxisYValues in page performance charts
  plugins/PagePerformance/JqplotDataGenerator/Chart.php
  plugins/PagePerformance/JqplotDataGenerator/StackedBarEvolution.php
Labels: not-in-changelog, Needs Review

#19379 [Vue] remove use of piwik-enriched-headline in UserLanguage
  plugins/UserLanguage/UserLanguage.php
Labels: Needs Review, Do not close

#19406 [Vue] remove angularjs from Overlay plugin
  plugins/Overlay/javascripts/Piwik_Overlay.js
  tests/lib/screenshot-testing/support/page-renderer.js
Labels: Needs Review, Do not close

#19435 [Vue] remove angularjs use from the DevicesDetection plugin
  plugins/CoreVue/types/index.d.ts
  plugins/DevicesDetection/Controller.php
  plugins/DevicesDetection/DevicesDetection.php
  plugins/DevicesDetection/templates/detection.twig
  plugins/DevicesDetection/vue/dist/DevicesDetection.umd.js
  plugins/DevicesDetection/vue/dist/DevicesDetection.umd.min.js
  plugins/DevicesDetection/vue/dist/umd.metadata.json
  plugins/DevicesDetection/vue/src/DetectionPage/DetectionPage.less
  plugins/DevicesDetection/vue/src/DetectionPage/DetectionPage.vue
  plugins/DevicesDetection/vue/src/index.ts
Labels: Needs Review, Do not close

#19499 Tour plugin language reworked
  plugins/Tour/lang/en.json
Labels: c: i18n

#19378 [Vue] remove use of angularjs from UsersManager plugin
  plugins/TwoFactorAuth/templates/userSettings.twig
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuth_usersettings_twofa_enabled.png
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuth_usersettings_twofa_enabled_required.png
  plugins/UsersManager/UsersManager.php
  plugins/UsersManager/templates/addNewToken.twig
  plugins/UsersManager/templates/addNewTokenSuccess.twig
  plugins/UsersManager/templates/anonymousSettings.twig
  plugins/UsersManager/templates/index.twig
  plugins/UsersManager/templates/userSecurity.twig
  plugins/UsersManager/templates/userSettings.twig
  plugins/UsersManager/tests/UI/expected-screenshots/UserSettings_add_token.png
  plugins/UsersManager/tests/UI/expected-screenshots/UserSettings_load_security.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_rows_selected.png
  plugins/UsersManager/vue/dist/UsersManager.umd.js
  plugins/UsersManager/vue/dist/UsersManager.umd.min.js
  plugins/UsersManager/vue/src/AddNewToken/AddNewToken.vue
  plugins/UsersManager/vue/src/AddNewToken/AddNewTokenSuccess.vue
  plugins/UsersManager/vue/src/AnonymousSettings/AnonymousSettings.adapter.ts
  plugins/UsersManager/vue/src/CapabilitiesEdit/CapabilitiesEdit.adapter.ts
  plugins/UsersManager/vue/src/CapabilitiesStore/CapabilitiesStore.adapter.ts
  plugins/UsersManager/vue/src/NewsletterSettings/NewsletterSettings.adapter.ts
  plugins/UsersManager/vue/src/PagedUsersList/PagedUsersList.adapter.ts
  plugins/UsersManager/vue/src/PersonalSettings/PersonalSettings.adapter.ts
  plugins/UsersManager/vue/src/UserEditForm/UserEditForm.adapter.ts
  plugins/UsersManager/vue/src/UserPermissionsEdit/UserPermissionsEdit.adapter.ts
  plugins/UsersManager/vue/src/UserPermissionsEdit/UserPermissionsEdit.less
  plugins/UsersManager/vue/src/UserSecurity/UserSecurity.vue
  plugins/UsersManager/vue/src/UserSettings/UserSettings.vue
  plugins/UsersManager/vue/src/UsersManager/UsersManager.adapter.ts
  plugins/UsersManager/vue/src/index.ts
Labels: Needs Review, Stale

#19383 [Vue] remove use of angularjs from Transitions
  plugins/CoreHome/Controller.php
  plugins/CoreHome/javascripts/popover.js
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/ContentBlock/ContentBlock.vue
  plugins/CoreHome/vue/src/WidgetLoader/WidgetLoader.vue
  plugins/Transitions/Transitions.php
  plugins/Transitions/javascripts/transitions.js
  plugins/Transitions/templates/renderPopover.twig
  plugins/Transitions/templates/transitions.twig
  plugins/Transitions/vue/dist/Transitions.umd.js
  plugins/Transitions/vue/dist/Transitions.umd.min.js
  plugins/Transitions/vue/src/TransitionExporter/TransitionExporter.adapter.ts
  plugins/Transitions/vue/src/TransitionExporter/TransitionExporter.ts
  plugins/Transitions/vue/src/TransitionExporter/TransitionExporterLink.vue
  plugins/Transitions/vue/src/TransitionsPage/TransitionsPage.vue
  plugins/Transitions/vue/src/index.ts
Labels: Needs Review, Do not close

#19390 [Vue] Remove use of angularjs from SitesManager plugin
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/VueEntryContainer/VueEntryContainer.vue
  plugins/CoreHome/vue/src/index.ts
  plugins/PrivacyManager/vue/dist/umd.metadata.json
  plugins/SitesManager/SitesManager.php
  plugins/SitesManager/templates/_displayJavascriptCode.twig
  plugins/SitesManager/templates/_siteWithoutDataTabs.twig
  plugins/SitesManager/templates/globalSettings.twig
  plugins/SitesManager/templates/index.twig
  plugins/SitesManager/templates/siteWithoutData.twig
  plugins/SitesManager/vue/dist/SitesManager.umd.js
  plugins/SitesManager/vue/dist/SitesManager.umd.min.js
  plugins/SitesManager/vue/src/ManageGlobalSettings/ManageGlobalSettings.adapter.ts
  plugins/SitesManager/vue/src/SiteTypesStore/SiteTypesStore.adapter.ts
  plugins/SitesManager/vue/src/SiteWithoutData/SiteWithoutData.vue
  plugins/SitesManager/vue/src/SitesManagement/SitesManagement.adapter.ts
  plugins/SitesManager/vue/src/index.ts
  tests/UI/specs/EmptySite_spec.js
Labels: Needs Review, Do not close

#19497 Transitions plugin language reworked
  plugins/Transitions/lang/en.json
Labels: c: i18n

#19575 Params name not matching, caused first website granted not working
  plugins/Login/tests/Integration/PasswordResetterTest.php
  plugins/UsersManager/API.php
  plugins/UsersManager/Repository/UserRepository.php
  plugins/UsersManager/tests/Integration/APITest.php
  plugins/UsersManager/tests/Integration/UserInviteTest.php
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_permissions_all_rows_in_search.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_permissions_edit.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_user_created.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
Labels: not-in-changelog

#19381 [Vue] remove angularjs use from UserCountry
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/Sparkline/Sparkline.vue
  plugins/UserCountry/UserCountry.php
  plugins/UserCountry/templates/adminIndex.twig
  plugins/UserCountry/templates/getDistinctCountries.twig
  plugins/UserCountry/vue/dist/UserCountry.umd.js
  plugins/UserCountry/vue/dist/UserCountry.umd.min.js
  plugins/UserCountry/vue/src/AdminPage/AdminPage.vue
  plugins/UserCountry/vue/src/GetDistinctCountries/GetDistinctCountries.vue
  plugins/UserCountry/vue/src/index.ts
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_locations_provider.png
Labels: Do not close

#19517 Exclude paypal as referrer in javascript tracker
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: Stale

#19479 UserCountry plugin language reworked
  plugins/UserCountry/lang/en.json
Labels: c: i18n

#19482 TwoFactorAuth plugin language reworked
  plugins/TwoFactorAuth/lang/en.json
Labels: c: i18n
