Repository matomo-org/matomo, pull requests merged in 2022-12, with the labels that each got.

#20034 Ensure to use unsanitized parameters for API request
  plugins/PagePerformance/Controller.php
  plugins/PagePerformance/tests/Fixtures/VisitsWithPagePerformanceMetrics.php
  plugins/PagePerformance/tests/UI/PagePerformance_spec.js
Labels: not-in-changelog, Needs Review

#20033 Improve layout of measurable type selection
  plugins/IntranetMeasurable/tests/UI/expected-screenshots/IntranetMeasurable_add_new_dialog.png
  plugins/SitesManager/stylesheets/SitesManager.less
  plugins/SitesManager/vue/dist/SitesManager.umd.js
  plugins/SitesManager/vue/dist/SitesManager.umd.min.js
  plugins/SitesManager/vue/src/SitesManagement/SitesManagement.vue
  tests/UI/expected-screenshots/MeasurableManager_add_new_dialog.png
  tests/UI/specs/MeasurableManager_spec.js
Labels: not-in-changelog

#20016 Make it possible to use type hinted parameters for API methods
  CHANGELOG.md
  core/API/DocumentationGenerator.php
  core/API/Proxy.php
  plugins/API/stylesheets/listAllAPI.less
  plugins/ExampleAPI/API.php
  plugins/ExamplePlugin/API.php
  plugins/ExampleUI/API.php
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
Labels: Needs Review

#20074 Prevent error in OptOutManager when language is not a string
  plugins/CoreAdminHome/OptOutManager.php
Labels: Needs Review

#20078 Fix for Http class header parse error
  core/Http.php
Labels: Bug, not-in-changelog, Needs Review

#20046 Add allow self singed in mail setting
  CHANGELOG.md
  config/global.ini.php
  core/Mail/Transport.php
Labels: not-in-changelog

#20064 Translations update from Hosted Weblate
  plugins/CoreAdminHome/lang/de.json
  plugins/CoreAdminHome/lang/ro.json
  plugins/CoreHome/lang/id.json
  plugins/CorePluginsAdmin/lang/id.json
  plugins/CoreUpdater/lang/id.json
  plugins/Feedback/lang/fr.json
  plugins/Feedback/lang/id.json
  plugins/Installation/lang/id.json
  plugins/MobileAppMeasurable/lang/es.json
  plugins/PrivacyManager/lang/nb.json
  plugins/SitesManager/lang/nb.json
  plugins/Tour/lang/de.json
  plugins/UsersManager/lang/fr.json
Labels: c: i18n

#20090 Speed up sparklines when larger periods are selected and improve detection of trends as well as fix comparison of dates
  lang/en.json
  plugins/CoreVisualizations/Visualizations/Sparklines.php
  plugins/CoreVisualizations/Visualizations/Sparklines/Config.php
  plugins/CoreVisualizations/Visualizations/Sparklines/SparklinePeriodSelector.php
  plugins/CoreVisualizations/templates/macros.twig
  plugins/CoreVisualizations/tests/Integration/Sparklines/SparklinePeriodSelectorTest.php
  plugins/CoreVisualizations/tests/Integration/SparklinesConfigTest.php
Labels: Needs Review

#20076 Improve css for userid in realtime widget
  plugins/Live/stylesheets/live.less
Labels: not-in-changelog

#20081 Adds new action to build woff2 font file
  .github/workflows/buildwoff2.yml
  .travis.yml
  tests/PHPUnit/Integration/ReleaseCheckListTest.php
Labels: c: Tests & QA

#20104 remove catch in UI tests
  tests/lib/screenshot-testing/support/page-renderer.js
Labels: c: Tests & QA, not-in-changelog, Needs Review

#20123 Added missing notification twig in siteWithoutData.twig
  plugins/SitesManager/templates/siteWithoutData.twig
Labels: Needs Review

#20110 Retry establishing DB connection if it fails with MySQL Server Has Gone Away
  core/Db/Adapter/Pdo/Mysql.php
  core/Tracker/Db/Pdo/Mysql.php
  core/Updater/Migration/Db.php
Labels: Needs Review

#20118 Speed up evolution and sparkline graphs
  core/DataAccess/ArchiveSelector.php
  tests/PHPUnit/System/expected/test_DataComparisonTest_flat__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_invertCompare__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_labelFilter__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_multipleSites_multipleCompare__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_periods__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_rangePeriodAgainstSingle__Actions.getPageUrls_range.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_segmentsAndPeriods__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_segments__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_singleAgainstRange__Actions.getPageUrls_day.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_subtableActions__Actions.getPageUrls_month.xml
Labels: c: Performance

#20132 [Vue] make sure to use the correct submit button text when editing/adding a scheduled report
  plugins/ScheduledReports/vue/dist/ScheduledReports.umd.js
  plugins/ScheduledReports/vue/dist/ScheduledReports.umd.min.js
  plugins/ScheduledReports/vue/dist/umd.metadata.json
  plugins/ScheduledReports/vue/src/AddReport/AddReport.vue
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
  tests/UI/expected-screenshots/UIIntegrationTest_email_reports_editor.png
Labels: Regression
