Repository matomo-org/matomo, pull requests merged in 2022-06, with the labels that each got.

#19299 [Vue] make sure spaces are encoded as %20 in URLs since some parts of matomo do not decode + properly
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/MatomoUrl/MatomoUrl.ts
Labels: Needs Review

#19305 [Vue] unset isSaving after save request finishes for saving global settings
  plugins/SitesManager/vue/dist/SitesManager.umd.js
  plugins/SitesManager/vue/dist/SitesManager.umd.min.js
  plugins/SitesManager/vue/src/ManageGlobalSettings/ManageGlobalSettings.vue
Labels: not-in-changelog, Needs Review

#19309 Fixed error due to non-array values
  plugins/Goals/DataTable/Filter/CalculateConversionPageRate.php
Labels: not-in-changelog, Regression

#19258 Translations update from Hosted Weblate
  lang/cs.json
  lang/eu.json
  lang/id.json
  lang/ja.json
  lang/uk.json
  plugins/API/lang/cs.json
  plugins/API/lang/id.json
  plugins/Actions/lang/tr.json
  plugins/Annotations/lang/uk.json
  plugins/CoreAdminHome/lang/cs.json
  plugins/CoreAdminHome/lang/fi.json
  plugins/CoreAdminHome/lang/id.json
  plugins/CoreAdminHome/lang/tr.json
  plugins/CoreAdminHome/lang/uk.json
  plugins/CoreHome/lang/ca.json
  plugins/CoreHome/lang/el.json
  plugins/CoreHome/lang/id.json
  plugins/CoreHome/lang/nb.json
  plugins/CoreHome/lang/pt-br.json
  plugins/CorePluginsAdmin/lang/id.json
  plugins/CorePluginsAdmin/lang/tr.json
  plugins/CoreUpdater/lang/id.json
  plugins/CoreUpdater/lang/uk.json
  plugins/CustomJsTracker/lang/id.json
  plugins/DevicePlugins/lang/id.json
  plugins/Feedback/lang/pt-br.json
  plugins/GeoIp2/lang/id.json
  plugins/Installation/lang/cs.json
  plugins/Installation/lang/nb.json
  plugins/Installation/lang/pt-br.json
  plugins/Live/lang/id.json
  plugins/Login/lang/id.json
  plugins/Marketplace/lang/id.json
  plugins/MobileMessaging/lang/id.json
  plugins/Overlay/lang/id.json
  plugins/PrivacyManager/lang/cs.json
  plugins/PrivacyManager/lang/id.json
  plugins/Referrers/lang/id.json
  plugins/SEO/lang/de.json
  plugins/SEO/lang/id.json
  plugins/SEO/lang/pt-br.json
  plugins/SEO/lang/uk.json
  plugins/ScheduledReports/lang/uk.json
  plugins/SitesManager/lang/tr.json
  plugins/UserCountry/lang/id.json
  plugins/UserCountryMap/lang/id.json
  plugins/UserLanguage/lang/uk.json
  plugins/UsersManager/lang/id.json
  plugins/Widgetize/lang/pt-br.json
Labels: c: i18n

#19126 [UI]update invalid archive notification
  core/Archive/ArchiveInvalidator.php
  core/Piwik.php
  plugins/SegmentEditor/SegmentEditor.php
  plugins/SegmentEditor/lang/en.json
  plugins/SegmentEditor/templates/_unprocessedSegmentMessage.twig
  plugins/SegmentEditor/tests/UI/UnprocessedSegment_spec.js
  plugins/SegmentEditor/tests/UI/expected-screenshots/UnprocessedSegmentTest_custom_segment.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/UnprocessedSegmentTest_unprocessed_default_segment.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/UnprocessedSegmentTest_unprocessed_segment.png
Labels: not-in-changelog, Needs Review

#19315 Improves memory usage of CSV exporter
  core/DataTable/Renderer/Csv.php
Labels: Needs Review

#19273 [CSS] add scroll to live visits table
  plugins/Dashboard/tests/UI/DashboardManager_spec.js
  plugins/Dashboard/tests/UI/Dashboard_spec.js
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_small_screen.png
  plugins/Live/stylesheets/live.less
Labels: not-in-changelog, Needs Review

#19342 Make 'Need Help?' widget translatable
  plugins/CoreAdminHome/lang/en.json
  plugins/CoreAdminHome/templates/home.twig
Labels: Needs Review, c: i18n

#19347 Fix FAQ # links
  core/Nonce.php
  js/piwik.js
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.js
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.min.js
  plugins/CoreAdminHome/vue/src/JsTrackingCodeGenerator/JsTrackingCodeGenerator.vue
  plugins/CoreHome/templates/_warningInvalidHost.twig
  plugins/CoreUpdater/templates/runUpdaterAndExit_done.twig
  plugins/CoreUpdater/templates/runUpdaterAndExit_welcome.twig
  plugins/Diagnostics/Diagnostic/DatabaseAbilitiesCheck.php
  plugins/GeoIp2/LocationProvider/GeoIp2/Php.php
  plugins/Installation/templates/reuseTables.twig
  plugins/Login/Controller.php
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.js
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.min.js
  plugins/PrivacyManager/vue/src/DeleteOldLogs/DeleteOldLogs.vue
  plugins/Referrers/SearchEngine.php
  plugins/UserCountry/LocationProvider/DefaultProvider.php
  plugins/UserCountry/Reports/Base.php
Labels: not-in-changelog

#19344 remove deprecated dollar brace string interpolation
  core/testMinimumPhpVersion.php
Labels: Task, not-in-changelog

#19324 [UI] goal overview conversion rate not showing correct on the graph
  plugins/Goals/Columns/Metrics/GoalConversionRate.php
  plugins/Goals/tests/System/expected/test_trackGoals_oneConversionPerVisitshowAllGoalSpecificMetrics_requestedColumns__Goals.get_day.xml
Labels: not-in-changelog, Needs Review

#19349 [Graphic]reload table if the default date changes
  core/Plugin/Visualization.php
  plugins/CoreHome/DataTableRowAction/RowEvolution.php
Labels: not-in-changelog, Needs Review

#19353 Fix for zero average order value on charts
  core/API/Request.php
  plugins/CoreVisualizations/JqplotDataGenerator/Chart.php
  plugins/CoreVisualizations/JqplotDataGenerator/Evolution.php
  plugins/CoreVisualizations/Visualizations/Graph.php
  plugins/Goals/Controller.php
  plugins/Goals/Reports/Get.php
  tests/UI/expected-screenshots/RowEvolution_row_evolution_ecommerce_item.png
Labels: Bug, not-in-changelog, Needs Review

#19332 [Vue] make sure to check for string values when checking if boolean-like values from the matomo API are truthy
  plugins/Goals/vue/dist/Goals.umd.js
  plugins/Goals/vue/dist/Goals.umd.min.js
  plugins/Goals/vue/src/ManageGoals/ManageGoals.vue
Labels: Regression

#19361 Fix PHPCS by requiring specific dependency versions
  composer.json
  composer.lock
  phpcs.xml
Labels: c: Tests & QA, not-in-changelog

#19362 [Vue] when getting plugin path relative to webroot, try all possible webroots
  core/AssetManager/UIAssetFetcher/PluginUmdAssetFetcher.php
Labels: Needs Review

#19325 Fix problem with too long browser versions
  plugins/DevicesDetection/Columns/BrowserVersion.php
Labels: not-in-changelog, Needs Review, Stale

#19375 [Vue] rework input value reset that allows parent component to disallow change
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/FormField/FieldNumber.vue
  plugins/CorePluginsAdmin/vue/src/FormField/FieldText.vue
  plugins/CorePluginsAdmin/vue/src/FormField/FieldTextArray.vue
  plugins/CorePluginsAdmin/vue/src/FormField/FieldTextarea.vue
  plugins/CorePluginsAdmin/vue/src/FormField/FieldTextareaArray.vue
Labels: Needs Review

#19387 Fixes glossary navigation
  plugins/API/Controller.php
  plugins/API/stylesheets/glossary.less
  plugins/API/templates/glossary.twig
Labels: Bug, c: Design / UI

#19396 Fix failing tests
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_invalid_token_auth.png
  plugins/Login/lang/en.json
  plugins/Login/tests/Integration/PasswordResetterTest.php
  plugins/Login/tests/UI/Invite_spec.js
  plugins/Login/tests/UI/Login_spec.js
  plugins/Login/tests/UI/expected-screenshots/Decline_default.png
  plugins/Login/tests/UI/expected-screenshots/Invite_error.png
  plugins/Login/tests/UI/expected-screenshots/Invite_set_password.png
  plugins/Login/tests/UI/expected-screenshots/Invite_wrong_password.png
  plugins/Login/tests/UI/expected-screenshots/Login_bruteforcelog_blockedapi.png
  plugins/Login/tests/UI/expected-screenshots/Login_bruteforcelog_blockedlogin.png
  plugins/Login/tests/UI/expected-screenshots/Login_bruteforcelog_blockedlogme.png
  plugins/Login/tests/UI/expected-screenshots/Login_bruteforcelog_noentries.png
  plugins/Login/tests/UI/expected-screenshots/Login_bruteforcelog_withentries.png
  plugins/Login/tests/UI/expected-screenshots/Login_forgot_password.png
  plugins/Login/tests/UI/expected-screenshots/Login_login_fail.png
  plugins/Login/tests/UI/expected-screenshots/Login_login_form.png
  plugins/Login/tests/UI/expected-screenshots/Login_login_form_logout.png
  plugins/Login/tests/UI/expected-screenshots/Login_password_reset.png
  plugins/Login/tests/UI/expected-screenshots/Login_password_reset_complete.png
  plugins/Login/tests/UI/expected-screenshots/Login_password_reset_confirm.png
  plugins/Login/tests/UI/expected-screenshots/Login_password_reset_error.png
  plugins/Login/tests/UI/expected-screenshots/NoAccess_login_noaccess.png
  plugins/Login/tests/UI/expected-screenshots/NoAccess_login_session_timeout.png
  plugins/SegmentEditor/tests/UI/SegmentSelectorEditor_spec.js
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_autocomplete_capitalized.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_autocomplete_lowercase.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_autocomplete_uppercase.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_complex_segment.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_updated_details.png
  plugins/UserCountryMap/Controller.php
  plugins/UsersManager/tests/Integration/UserInviteTest.php
  plugins/UsersManager/tests/UI/UsersManager_spec.js
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_admin_view_admin_load.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_delete_bulk_access.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_delete_single.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_edit_user_basic_asks_confirmation.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_edit_user_basic_confirmed_wrong_password.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_edit_user_form.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_manage_users_back.png
  tests/PHPUnit/Fixtures/UITestFixture.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_plugins.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_plugins_no_internet.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_settings_general.png
  tests/UI/expected-screenshots/UIIntegrationTest_invalid_idsite.png
  tests/UI/expected-screenshots/UIIntegrationTest_not_logged_in.png
  tests/javascript/index.php
Labels: c: Tests & QA

#19412 [Vue] apply #19375 to next_release
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/FormField/FieldNumber.vue
  plugins/CorePluginsAdmin/vue/src/FormField/FieldText.vue
  plugins/CorePluginsAdmin/vue/src/FormField/FieldTextArray.vue
  plugins/CorePluginsAdmin/vue/src/FormField/FieldTextarea.vue
  plugins/CorePluginsAdmin/vue/src/FormField/FieldTextareaArray.vue
Labels: Needs Review, Regression

#19408 [Vue] Fix broken reset of FieldCheckboxArray checkbox state.
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/FormField/FieldCheckboxArray.vue
  plugins/CorePluginsAdmin/vue/src/FormField/FieldSelect.vue
Labels: Regression

#19360 Fix number formatting in additional Y axis in (evolution) charts
  plugins/CoreVisualizations/javascripts/jqplot.js
  tests/UI/expected-screenshots/EvolutionGraph_bounce_rate.png
Labels: Bug, Needs Review

#19327 Try to handle incorrectly prefixed region codes
  plugins/GeoIp2/LocationProvider/GeoIp2/Php.php
  plugins/GeoIp2/tests/Integration/LocationProviderTest.php
  tests/lib/geoip-files/GeoIP2-City.json
  tests/lib/geoip-files/GeoIP2-City.mmdb
Labels: not-in-changelog, Needs Review, Stale

#19436 ImageGraph plugin language reworked
  plugins/ImageGraph/lang/en.json
Labels: c: i18n

#19302 Provide possibility to configure referrer exclusion list
  CHANGELOG.md
  core/Db/Schema/Mysql.php
  core/Settings/Measurable/MeasurableProperty.php
  core/Settings/Storage/Backend/SitesTable.php
  core/Tracker/TrackerCodeGenerator.php
  core/Updates/4.12.0-b1.php
  core/Version.php
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.js
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.min.js
  plugins/CoreAdminHome/vue/src/JsTrackingCodeGenerator/JsTrackingCodeGenerator.vue
  plugins/IntranetMeasurable/tests/UI/expected-screenshots/IntranetMeasurable_intranet_create.png
  plugins/Referrers/Columns/Base.php
  plugins/Referrers/tests/Integration/Columns/ReferrerTypeTest.php
  plugins/Referrers/tests/System/expected/test_phpSerialized8__Referrers.getReferrerType_year.original
  plugins/Referrers/tests/System/expected/test_phpSerialized__Referrers.getReferrerType_year.original
  plugins/SitesManager/API.php
  plugins/SitesManager/Controller.php
  plugins/SitesManager/SiteUrls.php
  plugins/SitesManager/SitesManager.php
  plugins/SitesManager/lang/en.json
  plugins/SitesManager/tests/Fixtures/ManySites.php
  plugins/SitesManager/tests/Integration/ApiTest.php
  plugins/SitesManager/tests/Integration/ModelTest.php
  plugins/SitesManager/tests/Integration/SiteUrlsTest.php
  plugins/SitesManager/tests/Integration/SitesManagerTest.php
  plugins/SitesManager/tests/Integration/TrackingTest.php
  plugins/SitesManager/tests/System/ApiTest.php
  plugins/SitesManager/tests/System/expected/test_SitesManager__SitesManager.getPatternMatchSites.xml
  plugins/SitesManager/tests/System/expected/test_SitesManager__SitesManager.getSiteSettings.xml
  plugins/SitesManager/tests/System/expected/test_SitesManagerwithLimit__SitesManager.getPatternMatchSites.xml
  plugins/SitesManager/tests/UI/expected-screenshots/SitesManager_global_settings.png
  plugins/SitesManager/tests/UI/expected-screenshots/SitesManager_site_edit_url.png
  plugins/SitesManager/tests/Unit/APITest.php
  plugins/SitesManager/tests/Unit/GuessSiteTypeAndGtmTest.php
  plugins/SitesManager/vue/dist/SitesManager.umd.js
  plugins/SitesManager/vue/dist/SitesManager.umd.min.js
  plugins/SitesManager/vue/src/GlobalSettingsStore/GlobalSettings.ts
  plugins/SitesManager/vue/src/GlobalSettingsStore/GlobalSettingsStore.ts
  plugins/SitesManager/vue/src/ManageGlobalSettings/ManageGlobalSettings.vue
  plugins/WebsiteMeasurable/MeasurableSettings.php
  tests/PHPUnit/Fixtures/OmniFixture.php
  tests/PHPUnit/Framework/Fixture.php
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getAvailableMeasurableTypes.xml
  tests/UI/expected-screenshots/MeasurableManager_add_measurable_view.png
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
  tests/javascript/index.php
  tests/javascript/matomotest.js
Labels: Enhancement, Needs Review
