Repository matomo-org/matomo, pull requests merged in 2022-05, with the labels that each got.

#19150 Fix command to disable 2fa for a user
  plugins/TwoFactorAuth/Commands/Disable2FAForUser.php
Labels: not-in-changelog, Needs Review

#19155 Ensure top control elements are displayed above reports on embeded dashboard
  plugins/Dashboard/stylesheets/dashboard.less
Labels: not-in-changelog, Needs Review

#19156 Rename MenuDropdown component to MenuItemsDropdown to finally avoid any case mismatches
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/MenuItemsDropdown/MenuItemsDropdown.adapter.ts
  plugins/CoreHome/vue/src/MenuItemsDropdown/MenuItemsDropdown.less
  plugins/CoreHome/vue/src/MenuItemsDropdown/MenuItemsDropdown.vue
  plugins/CoreHome/vue/src/ReportingMenu/ReportingMenu.vue
  plugins/CoreHome/vue/src/index.ts
  plugins/Goals/vue/dist/Goals.umd.js
  plugins/Morpheus/stylesheets/base.less
  plugins/SitesManager/vue/dist/umd.metadata.json
  tests/PHPUnit/Unit/FilesystemTest.php
Labels: not-in-changelog, Needs Review

#19157 Make Widgetize page translatable
  plugins/Widgetize/Widgetize.php
  plugins/Widgetize/lang/en.json
  plugins/Widgetize/vue/dist/Widgetize.umd.js
  plugins/Widgetize/vue/dist/Widgetize.umd.min.js
  plugins/Widgetize/vue/src/ExportWidget/ExportWidget.vue
  plugins/Widgetize/vue/src/WidgetPreview/WidgetPreviewIframe.vue
Labels: Needs Review

#19141 Translations update from Hosted Weblate
  plugins/API/lang/fi.json
  plugins/CoreAdminHome/lang/fi.json
  plugins/CoreAdminHome/lang/zh-tw.json
  plugins/CoreHome/lang/fi.json
  plugins/CoreUpdater/lang/tr.json
  plugins/CoreUpdater/lang/zh-tw.json
  plugins/CustomDimensions/lang/tr.json
  plugins/Dashboard/lang/ko.json
  plugins/Ecommerce/lang/tr.json
  plugins/Events/lang/zh-tw.json
  plugins/Feedback/lang/pt-br.json
  plugins/Installation/lang/de.json
  plugins/Installation/lang/fi.json
  plugins/Installation/lang/zh-cn.json
  plugins/LanguagesManager/lang/ko.json
  plugins/PrivacyManager/lang/tr.json
  plugins/Resolution/lang/fi.json
  plugins/UserCountryMap/lang/tr.json
  plugins/UserId/lang/zh-cn.json
  plugins/UserLanguage/lang/fi.json
  plugins/UsersManager/lang/pt-br.json
  plugins/UsersManager/lang/tr.json
  plugins/VisitsSummary/lang/fi.json
  plugins/Widgetize/lang/fi.json
Labels: c: i18n

#19041 [JS]update beforeunload to visibilitychange
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  piwik.min.js
  tests/javascript/index.php
Labels: not-in-changelog, Needs Review

#19165 [Vue] Fix vue-directive selector, make sure to select root node if it has vue-directive, not vue-entry
  plugins/Morpheus/javascripts/piwikHelper.js
Labels: Bug, Needs Review

#19111 Replace deprecated String.prototype.substr()
  plugins/Actions/javascripts/actionsDataTable.js
  plugins/CoreHome/angularjs/anchorLinkFix.js
  plugins/CoreHome/angularjs/common/directives/autocomplete-matched.js
  plugins/CoreHome/angularjs/common/directives/field-condition.js
  plugins/CoreHome/angularjs/common/filters/ucfirst.js
  plugins/CoreHome/angularjs/http404check.js
  plugins/CoreHome/javascripts/broadcast.js
  plugins/CoreHome/javascripts/dataTable.js
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/src/Matomo/Matomo.ts
  plugins/CoreHome/vue/src/QuickAccess/QuickAccess.vue
  plugins/CoreHome/vue/src/ShowSensitiveData/ShowSensitiveData.ts
  plugins/CustomDimensions/javascripts/rowactions.js
  plugins/CustomDimensions/vue/src/utilities.ts
  plugins/Goals/vue/src/ManageGoals/ManageGoals.vue
  plugins/Marketplace/vue/src/PluginName/PluginName.ts
  plugins/Overlay/javascripts/Piwik_Overlay.js
  plugins/Overlay/templates/startOverlaySession.twig
  plugins/PrivacyManager/vue/src/OptOutCustomizer/OptOutCustomizer.vue
  plugins/Referrers/vue/src/CampaignBuilder/CampaignBuilder.vue
  plugins/SegmentEditor/vue/src/SegmentGenerator/SegmentGenerator.vue
  plugins/Transitions/javascripts/transitions.js
  plugins/UserCountryMap/javascripts/realtime-map.js
  plugins/UserCountryMap/javascripts/visitor-map.js
  tests/javascript/index.php
  tests/javascript/jash/Jash.js
  tests/javascript/jslint/jslint.js
  tests/lib/screenshot-testing/support/chai-extras.js
Labels: Needs Review, Stale

#19170 Ensure all sites are changed when granting access to all sites
  plugins/UsersManager/vue/dist/UsersManager.umd.js
  plugins/UsersManager/vue/dist/UsersManager.umd.min.js
  plugins/UsersManager/vue/src/UserPermissionsEdit/UserPermissionsEdit.vue
Labels: not-in-changelog, Needs Review

#19172 Improve performance of calculating evolution trend metric value
  plugins/CoreHome/Columns/Metrics/EvolutionMetric.php
Labels: c: Performance, Needs Review

#19171 Remove Alexa page rank from SEO plugin
  plugins/SEO/API.php
  plugins/SEO/Metric/Aggregator.php
  plugins/SEO/Metric/Alexa.php
  plugins/SEO/config/config.php
  plugins/SEO/config/tracker.php
  plugins/SEO/config/ui-test.php
  plugins/SEO/lang/en.json
  plugins/SEO/tests/Integration/SEOTest.php
  plugins/SEO/tests/UI/SeoWidget_spec.js
  plugins/SEO/tests/UI/expected-ui-screenshots/SeoWidgetTest_widget.png
  plugins/SEO/tests/resources/alexa_response.html
  tests/UI/expected-screenshots/UIIntegrationTest_admin_plugins.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_plugins_no_internet.png
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
Labels: not-in-changelog, Needs Review

#19182 Improve isObjectEmpty function in piwik.js
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: Needs Review

#19139 Add support to exclude hosts from proxy
  config/global.ini.php
  core/Http.php
  tests/PHPUnit/Unit/HttpTest.php
Labels: Enhancement

#19191 tweak QueryParameters type in index.d.ts to better match arbitrary object types
  .github/workflows/buildvue.yml
  plugins/CoreVue/types/index.d.ts
Labels: Needs Review

#19195 [Vue] add ability to use a deep watch in scope var watches in angularjs adapters
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/createAngularJsAdapter.ts
Labels: Needs Review

#19192 Upgrades and bugfixes.
  package-lock.json
Labels: Task

#19212 covert getPluginUmdChunks from private to protected
  core/AssetManager.php
Labels: not-in-changelog

#19216 [Vue] correctly destroy vue entry components in widgetloader
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/WidgetLoader/WidgetLoader.vue
Labels: Bug

#19223 Merge 4.10.0 changes back to development branch
  core/AssetManager.php
  core/Version.php
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/WidgetLoader/WidgetLoader.vue
Labels: not-in-changelog

#19227 [Vue] add currentSiteName property to PiwikGlobal type
  plugins/CoreVue/types/index.d.ts
Labels: Needs Review

#19226 Ensure goal sparklines show the correct goal
  plugins/CoreVisualizations/Visualizations/Sparklines.php
  plugins/CoreVisualizations/Visualizations/Sparklines/Config.php
  plugins/Goals/Controller.php
Labels: not-in-changelog, Needs Review

#19180 MultiSites: move getAllWithGroups method from Controller to API
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_revenueAbandonedCart__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_revenueOrder__API.getSuggestedValuesForSegment.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_SegmentCartRevenueOrder__Goals.get_day.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_SegmentRevenueOrder__Goals.get_day.xml
  plugins/MultiSites/API.php
  plugins/MultiSites/Controller.php
  plugins/MultiSites/Dashboard.php
  plugins/MultiSites/tests/Integration/ControllerTest.php
  plugins/MultiSites/tests/System/ApiTest.php
  plugins/MultiSites/tests/System/expected/test___MultiSites.getAllWithGroups_day.xml
  plugins/MultiSites/tests/System/expected/test_limitedWithOffset__MultiSites.getAllWithGroups_day.xml
  plugins/MultiSites/tests/System/expected/test_limitedWithPattern__MultiSites.getAllWithGroups_day.xml
  plugins/MultiSites/tests/System/expected/test_limited__MultiSites.getAllWithGroups_day.xml
  plugins/MultiSites/tests/System/expected/test_multiplePeriods__MultiSites.getAllWithGroups_day.xml
  plugins/MultiSites/vue/dist/MultiSites.umd.js
  plugins/MultiSites/vue/dist/MultiSites.umd.min.js
  plugins/MultiSites/vue/src/Dashboard/Dashboard.store.ts
  tests/PHPUnit/System/BackwardsCompatibility1XTest.php
  tests/PHPUnit/System/expected/test_ImportLogs__MultiSites.getAllWithGroups_month.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits__MultiSites.getAllWithGroups_day.xml
  tests/PHPUnit/System/expected/test_noVisit_PeriodIsLast__MultiSites.getAllWithGroups_day.xml
  tests/PHPUnit/System/expected/test_noVisit_PeriodIsLast__MultiSites.getAllWithGroups_week.xml
  tests/PHPUnit/System/expected/test_noVisit__MultiSites.getAllWithGroups_day.xml
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
Labels: c: Performance

#19143 Compatibility fixes for PHP 8.1
  .travis.yml
  core/Db/Adapter/Mysqli.php
  core/ProxyHttp.php
  core/ReportRenderer/Pdf.php
  core/Site.php
  core/Tracker/Db/Mysqli.php
  libs/Authenticator/TwoFactorAuthenticator.php
  plugins/CoreAdminHome/Commands/ConfigDelete.php
  plugins/CoreAdminHome/Commands/ConfigGet.php
  plugins/Login/PasswordResetter.php
  plugins/Marketplace/Api/Service.php
  plugins/PrivacyManager/tests/Fixtures/MultipleSitesMultipleVisitsFixture.php
  plugins/Referrers/Columns/Base.php
  plugins/UserLanguage/functions.php
  tests/PHPUnit/Fixtures/ManyVisitsWithMockLocationProvider.php
  tests/PHPUnit/Framework/Fixture.php
  tests/PHPUnit/Integration/FrontControllerTest.php
  tests/resources/trigger-fatal.php
Labels: not-in-changelog

#19098 [security] Force matomo.org related requests to use ssl as default
  config/global.ini.php
  core/Http.php
  plugins/CoreUpdater/Controller.php
  plugins/CoreUpdater/Diagnostic/HttpsUpdateCheck.php
  plugins/CoreUpdater/ReleaseChannel.php
  plugins/CoreUpdater/Updater.php
  plugins/CoreUpdater/tests/Integration/ReleaseChannelTest.php
  plugins/Installation/lang/en.json
  plugins/Marketplace/Api/Client.php
  plugins/Marketplace/Controller.php
  plugins/Marketplace/config/config.php
  plugins/Marketplace/config/test.php
  plugins/UsersManager/NewsletterSignup.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: not-in-changelog

#19239 [Vue] add utility function for pattern that issues a single AJAX request at a time
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/AjaxHelper/AjaxHelper.ts
Labels: Needs Review

#19238 [Vue] change modal callbacks option type to allow any key value
  plugins/CoreVue/types/index.d.ts
Labels: Needs Review

#19240 [Vue] idsite property in SegmentGenerator component must default to Matomo idSite
  plugins/SegmentEditor/vue/dist/SegmentEditor.umd.js
  plugins/SegmentEditor/vue/dist/SegmentEditor.umd.min.js
  plugins/SegmentEditor/vue/src/SegmentGenerator/SegmentGenerator.vue
Labels: not-in-changelog, Needs Review

#19255 [Vue] Allow other primitive types as arguments to translate.
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/translate.ts
  plugins/CoreVue/types/index.d.ts
Labels: Needs Review

#19241 [Vue] hasExtraPlugin in campaign builder component should default to true
  plugins/Referrers/vue/dist/Referrers.umd.js
  plugins/Referrers/vue/dist/Referrers.umd.min.js
  plugins/Referrers/vue/src/CampaignBuilder/CampaignBuilder.vue
Labels: Needs Review, Regression

#19236 [Vue] add manage goals store to share loaded idGoal with plugin components that extend goal management
  core/Version.php
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/FormField/FieldCheckbox.vue
  plugins/CorePluginsAdmin/vue/src/FormField/FieldCheckboxArray.vue
  plugins/CorePluginsAdmin/vue/src/FormField/FieldRadio.vue
  plugins/Goals/vue/dist/Goals.umd.js
  plugins/Goals/vue/dist/Goals.umd.min.js
  plugins/Goals/vue/src/ManageGoals/ManageGoals.store.ts
  plugins/Goals/vue/src/ManageGoals/ManageGoals.vue
  plugins/Goals/vue/src/index.ts
Labels: Needs Review

#19245 Add 429 response code & conditional setDefaultAdapter
  core/Common.php
Labels: Needs Review

#19262 [Vue] default null/falsey value in FieldNumber to 0 to match angularjs behavior
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/FormField/FieldNumber.vue
Labels: Needs Review, Regression

#19257 Allow to serve manifest.json file
  plugins/Installation/ServerFilesGenerator.php
Labels: not-in-changelog

#19260 [Vue] correct sparkline segment encoding
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/Sparkline/Sparkline.vue
Labels: Needs Review

#19199 Handle write permission correctly when checking for users with access to same site
  plugins/UsersManager/UserAccessFilter.php
  plugins/UsersManager/tests/Integration/UserAccessFilterTest.php
Labels: not-in-changelog

#19271 fix anchor links on API page
  plugins/API/Controller.php
Labels: not-in-changelog, Needs Review

#19280 [Vue] in AjaxHelper do not use a default parameter if value is 0
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/AjaxHelper/AjaxHelper.ts
Labels: Needs Review

#19264 [Vue] ignore linkSync errors in custom chai assertion to avoid error if expected file does not exist
  tests/lib/screenshot-testing/support/chai-extras.js
Labels: Needs Review

#19261 feat: adds a refresh button
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/javascripts/refresh-button.js
  plugins/CoreHome/lang/de.json
  plugins/CoreHome/lang/en.json
  plugins/CoreHome/stylesheets/layout.less
  plugins/CoreHome/templates/_headerMessage.twig
Labels: Needs Review

#19292 Ensure refresh button is only shown where needed
  plugins/CoreHome/javascripts/refresh-button.js
  plugins/CoreHome/stylesheets/layout.less
  plugins/CoreHome/templates/_headerMessage.twig
  plugins/Goals/tests/UI/expected-screenshots/GoalsPages_manage.png
  plugins/Login/tests/UI/expected-screenshots/Login_bruteforcelog_noentries.png
  plugins/Login/tests/UI/expected-screenshots/Login_bruteforcelog_withentries.png
  plugins/SegmentEditor/tests/UI/SegmentSelectorEditor_spec.js
  plugins/UsersManager/tests/UI/UsersManager_spec.js
  tests/UI/expected-screenshots/Menus_mobile_top.png
  tests/UI/specs/UIIntegration_spec.js
Labels: not-in-changelog, Regression

#19200 Try to set referrer attribution cookie when leaving the page if no tracking request was sent yet
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  tests/javascript/index.php
Labels: not-in-changelog

#19285 [UI] Fix the database tooltip hidden problem
  plugins/CoreHome/javascripts/dataTable.js
  tests/UI/specs/UIIntegration_spec.js
Labels: not-in-changelog

#19293 [Vue] add userLogin property to PiwikGlobal type
  plugins/CoreVue/types/index.d.ts
Labels: Needs Review

#19296 [Vue] remove some console.logs that got through
  plugins/CustomDimensions/vue/dist/CustomDimensions.umd.js
  plugins/CustomDimensions/vue/dist/CustomDimensions.umd.min.js
  plugins/CustomDimensions/vue/src/Edit/Edit.vue
  plugins/SitesManager/vue/dist/SitesManager.umd.js
  plugins/SitesManager/vue/dist/SitesManager.umd.min.js
  plugins/SitesManager/vue/src/SitesManagement/SitesManagement.vue
Labels: Needs Review

#19294 Fix for undefined array index error when rendering sparklines.
  plugins/CoreVisualizations/Visualizations/Sparklines.php
Labels: not-in-changelog, Needs Review

#19295 Fix for missing formatting of conversion rate on goals reports
  plugins/CoreVisualizations/Visualizations/Sparklines.php
  plugins/Goals/Reports/Get.php
  plugins/Goals/tests/UI/expected-screenshots/GoalsPages_individual_goal.png
  plugins/Goals/tests/UI/expected-screenshots/GoalsPages_individual_goal_updated.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard2.png
Labels: not-in-changelog, Needs Review
