Repository matomo-org/matomo, pull requests merged in 2022-09, with the labels that each got.

#19698 Added code to unsanitize user email on update
  plugins/UsersManager/API.php
Labels: Needs Review

#19492 [Vue] remove use of angularjs for expression parsing
  LEGALNOTICE
  package-lock.json
  package.json
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/GroupedSettings/GroupedSetting.vue
  plugins/CorePluginsAdmin/vue/src/expressions.ts
  plugins/CorePluginsAdmin/vue/src/index.ts
  plugins/PrivacyManager/vue/dist/umd.metadata.json
Labels: Needs Review, Do not close

#19628 show Development language again when development mode is enabled
  plugins/LanguagesManager/API.php
Labels: Easier debugging

#19699 Fix a couple of UI regressions / bugs
  plugins/CoreHome/stylesheets/dataTable/_entityTable.less
  plugins/UsersManager/stylesheets/usersManager.less
Labels: not-in-changelog, Needs Review

#19690 Fix couple of PHP8.2 deprecation warnings
  core/AssetManager/UIAssetMerger.php
  core/Cookie.php
  plugins/CustomDimensions/Dimension/CustomActionDimension.php
  plugins/CustomDimensions/GetCustomDimension.php
Labels: Needs Review, Stale

#19710 Rename javascript event piwikPageChange to matomoPageChange
  CHANGELOG.md
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/PeriodSelector/PeriodSelector.vue
  plugins/CoreHome/vue/src/ReportingMenu/ReportingMenu.vue
  plugins/CoreHome/vue/src/ReportingPage/ReportingPage.vue
  plugins/CoreVisualizations/javascripts/jqplot.js
Labels: Needs Review

#19694 Fix for long report titles overflowing on PDF reports
  core/ReportRenderer/Pdf.php
  plugins/CustomDimensions/tests/System/expected/test___ScheduledReports.generateReport_year.original.pdf
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_LiveEcommerceStatusOrdered__Live.getLastVisitsDetails_day.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_Metadata_Goals.Get_AbandonedCart__API.getProcessedReport_day.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_Metadata_Goals.Get_NormalGoal__API.getProcessedReport_day.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_Metadata_Goals.Get_Order__API.getProcessedReport_day.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_Metadata_ItemsCategory__API.getProcessedReport_day.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_Metadata_ItemsSku__API.getProcessedReport_day.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_Metadata_VisitTime.getVisitInformationPerServerTime__API.getProcessedReport_day.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_SegmentCartRevenueOrder__Live.getLastVisitsDetails_day.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_SegmentRevenueOrder__Live.getLastVisitsDetails_day.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems__API.getProcessedReport_day.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems__Live.getLastVisitsDetails_day.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_html_row_evolution_graph__ScheduledReports.generateReport_week.original.html
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_html_row_evolution_overEach__ScheduledReports.generateReport_week.original.html
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_html_row_evolution_prevCustomN__ScheduledReports.generateReport_week.original.html
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_html_tables_and_graph__ScheduledReports.generateReport_week.original.html
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_html_tables_only__ScheduledReports.generateReport_week.original.html
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_in_csv__ScheduledReports.generateReport_week.original.csv
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_in_pdf_tables_only__ScheduledReports.generateReport_week.original.pdf
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_in_tsv__ScheduledReports.generateReport_week.original.tsv
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_via_sms_all_sites__ScheduledReports.generateReport_week.original.sms.txt
  tests/PHPUnit/Fixtures/TwoSitesEcommerceOrderWithItems.php
  tests/PHPUnit/Framework/Fixture.php
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_html_tables_only__ScheduledReports.generateReport_month.original.html
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_in_pdf_tables_only__ScheduledReports.generateReport_month.original.pdf
Labels: not-in-changelog

#19528 Improved opt out
  CHANGELOG.md
  core/FrontController.php
  core/Session.php
  plugins/CoreAdminHome/API.php
  plugins/CoreAdminHome/Controller.php
  plugins/CoreAdminHome/OptOutManager.php
  plugins/CoreAdminHome/lang/en.json
  plugins/CoreAdminHome/templates/optOut.twig
  plugins/CoreHome/LoginAllowlist.php
  plugins/CoreHome/tests/Integration/ChangesTest.php
  plugins/CoreHome/tests/UI/expected-screenshots/Changes_show_popover.png
  plugins/PrivacyManager/Controller.php
  plugins/PrivacyManager/PrivacyManager.php
  plugins/PrivacyManager/changes.json
  plugins/PrivacyManager/lang/en.json
  plugins/PrivacyManager/templates/usersOptOut.twig
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_users_opt_out_default.png
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.js
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.min.js
  plugins/PrivacyManager/vue/src/OptOutCustomizer/OptOutCustomizer.less
  plugins/PrivacyManager/vue/src/OptOutCustomizer/OptOutCustomizer.vue
  tests/PHPUnit/Integration/ReleaseCheckListTest.php
Labels: Critical, c: Privacy, not-in-changelog

#19718 Use correct login plugin when generating invite link urls
  plugins/Login/Controller.php
  plugins/Login/templates/invitation.twig
  plugins/Login/templates/invitationDecline.twig
  plugins/UsersManager/Emails/UserInviteEmail.php
  plugins/UsersManager/templates/_userInviteEmail.twig
Labels: not-in-changelog, Needs Review

#19711 clean up Overlay::showErrorWrongDomain action
  plugins/Overlay/Controller.php
Labels: not-in-changelog, Needs Review

#19731 Font color for mobile to use pre defined text and background variables
  plugins/CoreHome/stylesheets/layout.less
Labels: Needs Review

#19730 Fix column type for id change column
  core/Db/Schema/Mysql.php
  core/Updates/4.12.0-b3.php
  core/Version.php
Labels: not-in-changelog, Needs Review

#19727 Fix number formatting for visit frequency sparklines
  plugins/VisitFrequency/Reports/Get.php
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard4.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_engagement.png
Labels: not-in-changelog, Needs Review

#19732 Link to changed blog link in what's new notice
  plugins/PrivacyManager/changes.json
Labels: not-in-changelog, Needs Review

#19746 fix build for 5.x-dev
  plugins/CorePluginsAdmin/tests/UI/expected-screenshots/TagManagerTeaser_super_user_activate_plugin.png
  plugins/Insights/tests/Integration/ApiTest.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_plugins.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_plugins_no_internet.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_themes.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_visitor_generator.png
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
  tests/resources/OmniFixture-dump.sql
Labels: Needs Review

#19724 hot fix give default period
  core/Plugin/Controller.php
Labels: not-in-changelog, Needs Review

#19749 Added config option to disable archiving for actions goals
  config/global.ini.php
  plugins/Actions/Archiver.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: Bug, Needs Review

#19740 Improve no data check in html visualization
  core/Plugin/Visualization.php
  plugins/CoreVisualizations/templates/_dataTableViz_htmlTable.twig
Labels: not-in-changelog, Needs Review

#19738 Adding the abililty to exclude specific sites from the site selector
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/SiteSelector/SiteSelector.vue
  plugins/CoreHome/vue/src/SiteSelector/SitesStore.ts
  plugins/SitesManager/API.php
  plugins/SitesManager/tests/Integration/ApiTest.php
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
  tests/UI/specs/SiteSelector_spec.js
Labels: not-in-changelog, Needs Review

#19756 PHP8.1 fix: we don't need to check for leaked tokens in an empty string
  plugins/TwoFactorAuth/TwoFactorAuth.php
Labels: Needs Review

#19787 [Vue] remove model value reset pattern in SegmentGenerator as it did not work in Field
  plugins/SegmentEditor/vue/dist/SegmentEditor.umd.js
  plugins/SegmentEditor/vue/dist/SegmentEditor.umd.min.js
  plugins/SegmentEditor/vue/src/SegmentGenerator/SegmentGenerator.vue
Labels: Needs Review

#19793 De-duplicate the plugin name in the what's new entry
  plugins/CoreHome/tests/UI/expected-screenshots/Changes_show_popover.png
  plugins/PrivacyManager/changes.json
Labels: not-in-changelog, Needs Review

#19794 Detect consent managers on the selected site and show a setup link
  plugins/Tour/API.php
  plugins/Tour/Engagement/Challenge.php
  plugins/Tour/Engagement/ChallengeSetupConsentManager.php
  plugins/Tour/Engagement/Challenges.php
  plugins/Tour/lang/en.json
  plugins/Tour/tests/System/ConsentManagerDetectionTest.php
Labels: Enhancement
