Repository matomo-org/matomo, pull requests merged in 2022-11, with the labels that each got.

#19938 Prevent some possible exceptions
  plugins/Ecommerce/Controller.php
  plugins/Goals/Reports/Get.php
  plugins/Referrers/Reports/Get.php
  plugins/VisitsSummary/Reports/Get.php
Labels: not-in-changelog, Needs Review

#19936 Fix value of delete_logs_enable not displayed correctly in UI
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.js
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.min.js
  plugins/PrivacyManager/vue/src/DeleteOldLogs/DeleteOldLogs.vue
Labels: not-in-changelog, Needs Review, Regression

#19873 update autocomplete on html to `on` and `off`
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.js
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.min.js
  plugins/CoreAdminHome/vue/src/SmtpSettings/SmtpSettings.vue
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/Field/Field.adapter.ts
  plugins/CorePluginsAdmin/vue/src/Field/Field.vue
  plugins/CorePluginsAdmin/vue/src/PasswordConfirmation/PasswordConfirmation.vue
Labels: not-in-changelog, Needs Review

#19835 add file:// protocal exclude option in tracker
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: not-in-changelog, Needs Review

#19881 Add exception for invalid limit before grouping
  core/RankingQuery.php
  plugins/Transitions/API.php
  plugins/Transitions/tests/Integration/TransitionsMaxAllowedPeriodTest.php
  plugins/Transitions/tests/System/TransitionsTest.php
  tests/PHPUnit/Unit/RankingQueryTest.php
Labels: not-in-changelog

#19934 Updates semver dependency
  composer.json
  composer.lock
Labels: not-in-changelog, Needs Review

#19915 Fix for opt-out toggling on page load and incorrect default state
  plugins/CoreAdminHome/OptOutManager.php
Labels: not-in-changelog, Regression

#19943 Prepare github actions for Matomo 5
  .github/workflows/composer-update.yml
  .github/workflows/release.yml
  .github/workflows/submodules.yml
  .github/workflows/update-intl.yml
  README.md
  libs/README.md
Labels: not-in-changelog, Needs Review

#19877 Adds test to prove purge settings are stored / returned as int
  plugins/PrivacyManager/tests/Integration/PrivacyManagerTest.php
Labels: c: Tests & QA, not-in-changelog, Needs Review, Stale

#19953 add global types for datatable row action classes/code
  plugins/CoreVue/types/index.d.ts
Labels: Needs Review

#19971 Provide correct date parameter for comparison sparklines
  plugins/CoreVisualizations/Visualizations/Sparklines.php
Labels: not-in-changelog, Needs Review

#19970 Avoid double formatting of conversion rate in comparison mode
  plugins/Goals/Reports/Get.php
Labels: Bug, Needs Review, Regression

#19918 Fix PHP8.2 deprecation messages
  core/ArchiveProcessor/Loader.php
  core/Concurrency/Lock.php
  core/Segment/SegmentExpression.php
  plugins/PrivacyManager/DoNotTrackHeaderChecker.php
Labels: not-in-changelog, Needs Review

#19925 Translations update from Hosted Weblate
  lang/bg.json
  lang/zh-cn.json
  plugins/Contents/lang/es.json
  plugins/CoreAdminHome/lang/fr.json
  plugins/CoreAdminHome/lang/sv.json
  plugins/CoreHome/lang/nl.json
  plugins/CustomDimensions/lang/es.json
  plugins/CustomJsTracker/lang/es.json
  plugins/DevicePlugins/lang/gl.json
  plugins/DevicePlugins/lang/ko.json
  plugins/Diagnostics/lang/sv.json
  plugins/ImageGraph/lang/ko.json
  plugins/Installation/lang/es.json
  plugins/Installation/lang/fr.json
  plugins/LanguagesManager/lang/sv.json
  plugins/Live/lang/fa.json
  plugins/Live/lang/id.json
  plugins/Login/lang/tr.json
  plugins/MobileMessaging/lang/sv.json
  plugins/ProfessionalServices/lang/bg.json
  plugins/SEO/lang/ko.json
  plugins/SitesManager/lang/bg.json
  plugins/SitesManager/lang/de.json
  plugins/Tour/lang/ko.json
  plugins/Transitions/lang/fr.json
  plugins/UserCountry/lang/fr.json
  plugins/UserLanguage/lang/ko.json
  plugins/UsersManager/lang/bg.json
  plugins/UsersManager/lang/tr.json
  plugins/WebsiteMeasurable/lang/ko.json
  plugins/Widgetize/lang/sv.json
Labels: c: i18n

#19958 Segment auto suggest capitalization
  plugins/Morpheus/stylesheets/ui/_components.less
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_suggested_values.png
Labels: not-in-changelog, Needs Review

#19959 Set default limit for concurrent archivers
  CHANGELOG.md
  core/CronArchive.php
  plugins/CoreConsole/Commands/CoreArchiver.php
Labels: not-in-changelog, Needs Review

#19983 add callBackQueue to process callBack, when clientHintsRequestQueue is used
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  tests/javascript/index.php
Labels: not-in-changelog, Needs Review

#19980 Translations update from Hosted Weblate
  lang/ms.json
  plugins/ImageGraph/lang/gl.json
  plugins/LanguagesManager/lang/gl.json
  plugins/ProfessionalServices/lang/gl.json
  plugins/Resolution/lang/gl.json
Labels: c: i18n

#19957 Detect GA3, GA4 or GTM during installation and suggest migration guides
  core/SiteContentDetector.php
  plugins/CoreAdminHome/CoreAdminHome.php
  plugins/CoreAdminHome/lang/en.json
  plugins/CoreAdminHome/stylesheets/jsTrackingGenerator.css
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.js
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.min.js
  plugins/CoreAdminHome/vue/src/JsTrackingCodeGenerator/JsTrackingCodeGenerator.vue
  plugins/Installation/Controller.php
  plugins/Installation/Installation.php
  plugins/Installation/tests/UI/Installation_spec.js
  plugins/PrivacyManager/Controller.php
  plugins/PrivacyManager/lang/en.json
  plugins/PrivacyManager/templates/askingForConsent.twig
  plugins/PrivacyManager/tests/UI/PrivacyManager_ConsentManager_spec.js
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_ConsentManager_consent_default.png
  plugins/SitesManager/Controller.php
  plugins/SitesManager/lang/en.json
  plugins/SitesManager/templates/_siteWithoutDataTabs.twig
  plugins/SitesManager/templates/_trackingCodeEmail.twig
  plugins/Tour/API.php
  plugins/Tour/Engagement/Challenge.php
  plugins/Tour/Engagement/ChallengeSetupConsentManager.php
  plugins/Tour/Engagement/Challenges.php
  plugins/Tour/lang/en.json
  plugins/Tour/tests/System/ConsentManagerDetectionTest.php
  plugins/Tour/tests/UI/Tour_ConsentManager_spec.js
  plugins/Tour/tests/UI/expected-screenshots/Tour_ConsentManager_widget_initial.png
  tests/PHPUnit/Fixtures/DisableSiteContentDetection.php
  tests/PHPUnit/Fixtures/EmptySiteWithSiteContentDetection.php
  tests/PHPUnit/Fixtures/EmptySiteWithSiteContentDetectionGA3.php
  tests/PHPUnit/Fixtures/EmptySiteWithSiteContentDetectionGA4.php
  tests/PHPUnit/Fixtures/EmptySiteWithSiteContentDetectionGTM.php
  tests/PHPUnit/Framework/Mock/FakeSiteContentDetector.php
  tests/PHPUnit/Unit/SiteContentDetectorTest.php
  tests/UI/expected-screenshots/EmptySite_ConsentManager_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_GA3_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_GA4_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_GTM_emptySiteDashboard.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_manage_tracking_code.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard3.png
  tests/UI/specs/EmptySite_ConsentManager_spec.js
  tests/UI/specs/EmptySite_GA3_spec.js
  tests/UI/specs/EmptySite_GA4_spec.js
  tests/UI/specs/EmptySite_GTM_spec.js
Labels: Enhancement, Needs Review

#20004 update FR translation
  tests/PHPUnit/System/expected/test_apiGetReportMetadata_year__API.getProcessedReport_year.xml
Labels: c: Tests & QA, Needs Review

#19992 Correctly escape email addresses in mailto links
  core/Plugin/Controller.php
Labels: Bug, Needs Review

#19996 compile vue entry components when replacing html in live widget
  plugins/Live/javascripts/live.js
Labels: Needs Review, Regression

#19994 fix incorrect parameter provided to deleteInvalidations
  core/CronArchive/QueueConsumer.php
Labels: not-in-changelog, Needs Review

#19975 Update issue creation template to apply "To Triage" label
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation_issue.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Needs Review

#19991 Avoid potential unneeded requests in Goals sparklines
  plugins/Goals/Reports/Get.php
Labels: not-in-changelog, Needs Review

#19821 Detect consent manager and suggest guide
  plugins/SitesManager/templates/_trackingCodeEmail.twig
  tests/PHPUnit/Fixtures/DisableSiteContentDetection.php
  tests/UI/expected-screenshots/EmptySite_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_emptySiteDashboard_ignored.png
  tests/UI/specs/EmptySite_spec.js
Labels: Enhancement, Needs Review

#19995 Translations update from Hosted Weblate
  lang/eu.json
  plugins/API/lang/gl.json
  plugins/CoreAdminHome/lang/el.json
  plugins/CoreAdminHome/lang/es.json
  plugins/CoreAdminHome/lang/uk.json
  plugins/PrivacyManager/lang/el.json
  plugins/SitesManager/lang/el.json
  plugins/Tour/lang/el.json
Labels: c: i18n

#19948 Allow calls to opcache_reset to be disabled in config
  CHANGELOG.md
  config/global.ini.php
  core/Config.php
  core/Filesystem.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: Needs Review

#20008 Improve GA/consent manager detection by not restricting to curl and caching result
  core/SiteContentDetector.php
  tests/PHPUnit/Framework/Mock/FakeSiteContentDetector.php
  tests/PHPUnit/Unit/SiteContentDetectorTest.php
Labels: c: Performance

#19942 add isFullRequest parameter to JS tracker queueRequest() …
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  tests/javascript/index.php
Labels: Needs Review

#20015 Some code improvements around consent manager checks
  core/SiteContentDetector.php
  plugins/PrivacyManager/lang/en.json
  plugins/PrivacyManager/templates/askingForConsent.twig
  plugins/SitesManager/templates/_siteWithoutDataTabs.twig
Labels: not-in-changelog, Needs Review

#19990 Use font for search icons
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/MenuItemsDropdown/MenuItemsDropdown.less
  plugins/CoreHome/vue/src/MenuItemsDropdown/MenuItemsDropdown.vue
  plugins/SitesManager/stylesheets/SitesManager.less
  plugins/SitesManager/tests/UI/expected-screenshots/SitesManager_loaded.png
  plugins/SitesManager/tests/UI/expected-screenshots/SitesManager_page_1.png
  plugins/SitesManager/tests/UI/expected-screenshots/SitesManager_page_1_again.png
  plugins/SitesManager/tests/UI/expected-screenshots/SitesManager_page_2.png
  plugins/SitesManager/tests/UI/expected-screenshots/SitesManager_search_page_1.png
  plugins/SitesManager/tests/UI/expected-screenshots/SitesManager_site_edit_url.png
  plugins/SitesManager/vue/dist/SitesManager.umd.js
  plugins/SitesManager/vue/dist/SitesManager.umd.min.js
  plugins/SitesManager/vue/src/SitesManagement/ButtonBar.vue
  tests/UI/expected-screenshots/MeasurableManager_add_measurable_view.png
  tests/UI/expected-screenshots/MeasurableManager_loaded.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_manage_websites.png
Labels: not-in-changelog, Needs Review

#20013 Translations update from Hosted Weblate
  plugins/CoreAdminHome/lang/id.json
  plugins/ProfessionalServices/lang/id.json
Labels: c: i18n

#20007 hide widget when not found
  plugins/Dashboard/javascripts/dashboardWidget.js
Labels: not-in-changelog, Needs Review

#20017 Try to fix archiving error
  plugins/PagePerformance/Archiver.php
Labels: Needs Review, Regression

#20029 Added code to sanitize getPiwikInstanceId()
  CHANGELOG.md
  config/global.ini.php
  core/SettingsPiwik.php
Labels: Needs Review

#20044 Fix for unhandled datatable maps in custom dimensions
  plugins/CustomDimensions/API.php
Labels: Bug

#20047 Translations update from Hosted Weblate
  lang/sq.json
  plugins/CoreAdminHome/lang/pl.json
  plugins/CoreAdminHome/lang/sq.json
  plugins/CoreHome/lang/sq.json
  plugins/CorePluginsAdmin/lang/sq.json
  plugins/CoreUpdater/lang/sq.json
  plugins/DBStats/lang/es.json
  plugins/DevicesDetection/lang/sq.json
  plugins/Feedback/lang/sq.json
  plugins/ImageGraph/lang/sq.json
  plugins/Installation/lang/pl.json
  plugins/Installation/lang/sq.json
  plugins/Login/lang/sq.json
  plugins/Referrers/lang/sq.json
  plugins/SEO/lang/sq.json
  plugins/SegmentEditor/lang/sq.json
  plugins/Transitions/lang/sq.json
  plugins/UserCountry/lang/sq.json
  plugins/UsersManager/lang/de.json
Labels: c: i18n

#20063 Updating changelog to reflect release schedule change
  CHANGELOG.md
Labels: not-in-changelog
