Repository matomo-org/matomo, pull requests merged in 2022-08, with the labels that each got.

#19576 Fix the password length checks on invite User
  plugins/Login/Controller.php
  plugins/UsersManager/UsersManager.php
Labels: Needs Review

#19580 Enable brute force detection for user invitation
  plugins/Login/Controller.php
  plugins/Login/Login.php
Labels: not-in-changelog

#19588 Fix placing series / series picker in charts
  plugins/CoreVisualizations/javascripts/jqplot.js
  plugins/Goals/tests/UI/GoalsPages_spec.js
  plugins/Goals/tests/UI/expected-screenshots/GoalsPages_individual_row_evolution_reloaded.png
Labels: Bug, c: Tests & QA, Needs Review

#19577 Improve the sanitization of request parameters
  core/DataTable/Renderer/Csv.php
Labels: not-in-changelog

#19584 Revert "Exclude paypal as referrer in javascript tracker (#19517)"
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: not-in-changelog

#19578 Config option to specify database error codes to ignore during updates
  config/global.ini.php
  core/Updater/Migration/Db/Sql.php
Labels: Enhancement

#19441 [Vue] remove use of angularjs from DBStats plugin
  plugins/CoreHome/vue/src/EnrichedHeadline/EnrichedHeadline.less
  plugins/DBStats/DBStats.php
  plugins/DBStats/templates/index.twig
  plugins/DBStats/vue/dist/DBStats.umd.js
  plugins/DBStats/vue/dist/DBStats.umd.min.js
  plugins/DBStats/vue/dist/umd.metadata.json
  plugins/DBStats/vue/src/DBStatsIntro/DBStatsIntro.vue
  plugins/DBStats/vue/src/index.ts
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuth_usersettings_twofa_enabled.png
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuth_usersettings_twofa_enabled_required.png
  plugins/UsersManager/tests/UI/expected-screenshots/UserSettings_load_security.png
Labels: Needs Review, Do not close

#19402 [Vue] remove use of angularjs from ScheduledReports plugin
  plugins/Morpheus/javascripts/piwikHelper.js
  plugins/ScheduledReports/ScheduledReports.php
  plugins/ScheduledReports/templates/index.twig
  plugins/ScheduledReports/templates/unsubscribe.twig
  plugins/ScheduledReports/vue/dist/ScheduledReports.umd.js
  plugins/ScheduledReports/vue/dist/ScheduledReports.umd.min.js
  plugins/ScheduledReports/vue/src/AddReport/AddReport.vue
Labels: Needs Review, Do not close

#19429 [Vue] remove use of angularjs from ExampleVue component
  plugins/CoreVue/Commands/GenerateVueComponent.php
  plugins/ExampleVue/Widgets/GetExampleVue.php
  plugins/ExampleVue/vue/dist/ExampleVue.css
  plugins/ExampleVue/vue/dist/ExampleVue.umd.1.js
  plugins/ExampleVue/vue/dist/ExampleVue.umd.js
  plugins/ExampleVue/vue/dist/ExampleVue.umd.min.1.js
  plugins/ExampleVue/vue/dist/ExampleVue.umd.min.js
  plugins/ExampleVue/vue/src/ExampleComponent/ExampleComponent.adapter.ts
  plugins/ExampleVue/vue/src/index.ts
Labels: Needs Review, Do not close

#19431 [Vue] remove use of angularjs from ExamplePlugin
  plugins/CoreConsole/Commands/GenerateAngularComponent.php
  plugins/CoreConsole/Commands/GenerateAngularDirective.php
  plugins/CoreConsole/Commands/GenerateVueConstructBase.php
  plugins/CoreVue/Commands/GenerateVueComponent.php
  plugins/ExamplePlugin/angularjs/directive-component/component.controller.js
  plugins/ExamplePlugin/angularjs/directive-component/component.directive.html
  plugins/ExamplePlugin/angularjs/directive-component/component.directive.js
  plugins/ExamplePlugin/angularjs/directive-component/component.directive.less
  plugins/ExamplePlugin/angularjs/example-component/example-component.component.html
  plugins/ExamplePlugin/angularjs/example-component/example-component.component.js
  plugins/ExamplePlugin/angularjs/example-component/example-component.component.less
  plugins/ExamplePlugin/plugin.json
  tests/UI/expected-screenshots/UIIntegrationTest_admin_plugins.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_plugins_no_internet.png
Labels: Needs Review, Do not close

#19432 [Vue] remove use of angularjs from Ecommerce plugin
  plugins/CoreVue/types/index.d.ts
  plugins/Ecommerce/Ecommerce.php
  plugins/Ecommerce/templates/conversionOverview.twig
  plugins/Ecommerce/templates/products.twig
  plugins/Ecommerce/templates/sales.twig
  plugins/Ecommerce/vue/dist/Ecommerce.umd.js
  plugins/Ecommerce/vue/dist/Ecommerce.umd.min.js
  plugins/Ecommerce/vue/dist/umd.metadata.json
  plugins/Ecommerce/vue/src/ConversionOverview/ConversionOverview.vue
  plugins/Ecommerce/vue/src/index.ts
  plugins/Goals/tests/UI/expected-screenshots/GoalsPages_ecommerce.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard2.png
  tests/UI/expected-screenshots/UIIntegrationTest_ecommerce_overview.png
Labels: Needs Review, Do not close

#19598 Use brute force detection for reset password action
  plugins/Login/Controller.php
Labels: c: Security

#19591 Require password confirmation when removing a site in UI
  CHANGELOG.md
  plugins/SitesManager/API.php
  plugins/SitesManager/vue/dist/SitesManager.umd.js
  plugins/SitesManager/vue/dist/SitesManager.umd.min.js
  plugins/SitesManager/vue/src/SiteFields/SiteFields.vue
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
Labels: c: Security

#19604 update szymach/c-pchart
  composer.json
  composer.lock
  core/DataTable/Renderer/Csv.php
Labels: Task, not-in-changelog

#19391 [Vue] remove use of angularjs from SegmentEditor plugin
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/index.ts
  plugins/CoreVue/types/index.d.ts
  plugins/Morpheus/javascripts/piwikHelper.js
  plugins/SegmentEditor/angularjs/segment-generator/segmentgenerator.controller.js
  plugins/SegmentEditor/angularjs/segment-generator/segmentgenerator.directive.html
  plugins/SegmentEditor/angularjs/segment-generator/segmentgenerator.directive.js
  plugins/SegmentEditor/angularjs/segment-generator/segmentgenerator.model.js
  plugins/SegmentEditor/javascripts/Segmentation.js
  plugins/SegmentEditor/lang/en.json
  plugins/SegmentEditor/templates/_segmentSelector.twig
  plugins/SegmentEditor/tests/UI/SegmentSelectorEditor_spec.js
  plugins/SegmentEditor/vue/dist/SegmentEditor.umd.js
  plugins/SegmentEditor/vue/dist/SegmentEditor.umd.min.js
  plugins/SegmentEditor/vue/src/SegmentGenerator/SegmentGenerator.adapter.ts
  plugins/SegmentEditor/vue/src/SegmentGenerator/SegmentGenerator.vue
  plugins/SegmentEditor/vue/src/index.ts
Labels: Needs Review, Do not close

#19569 Fix for current year not processed for new custom reports
  core/CronArchive.php
  tests/PHPUnit/Integration/CronArchiveTest.php
Labels: Bug, Needs Review

#19610 Removes unused method Proxy\Controller::isPiwikUrl()
  plugins/Proxy/Controller.php
  plugins/Proxy/tests/Unit/ProxyTest.php
Labels: not-in-changelog, Needs Review

#19404 [Vue] remove angularjs from PrivacyManager plugin
  plugins/PrivacyManager/PrivacyManager.php
  plugins/PrivacyManager/templates/askingForConsent.twig
  plugins/PrivacyManager/templates/gdprOverview.twig
  plugins/PrivacyManager/templates/privacySettings.twig
  plugins/PrivacyManager/templates/usersOptOut.twig
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_privacy_settings_default.png
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.js
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.min.js
  plugins/PrivacyManager/vue/src/AnonymizeLogData/AnonymizeLogData.adapter.ts
  plugins/PrivacyManager/vue/src/AnonymizeLogData/PreviousAnonymizations.vue
  plugins/PrivacyManager/vue/src/AskingForConsent/AskingForConsent.vue
  plugins/PrivacyManager/vue/src/GdprOverview/GdprOverview.vue
  plugins/PrivacyManager/vue/src/ManageGdpr/ManageGdpr.adapter.ts
  plugins/PrivacyManager/vue/src/OptOutCustomizer/OptOutCustomizer.adapter.ts
  plugins/PrivacyManager/vue/src/PrivacySettings/PrivacySettings.vue
  plugins/PrivacyManager/vue/src/UsersOptOut/UsersOptOut.vue
  plugins/PrivacyManager/vue/src/index.ts
Labels: Do not close

#19595 Improve url detection in mod pagespeed check
  plugins/Diagnostics/Diagnostic/PageSpeedCheck.php
Labels: not-in-changelog, Needs Review

#19426 [Vue] remove angularjs from Goals plugin
  plugins/Goals/Goals.php
  plugins/Goals/templates/_addEditGoal.twig
  plugins/Goals/templates/addNewGoal.twig
  plugins/Goals/templates/conversionOverview.twig
  plugins/Goals/vue/dist/Goals.umd.js
  plugins/Goals/vue/dist/Goals.umd.min.js
  plugins/Goals/vue/src/GoalPageLink/GoalPageLink.adapter.ts
  plugins/Goals/vue/src/GoalPageLink/GoalPageLink.ts
  plugins/Goals/vue/src/ManageGoals/ManageGoals.adapter.ts
  plugins/Goals/vue/src/ManageGoals/ManageGoals.vue
  plugins/Goals/vue/src/index.ts
Labels: Needs Review, Do not close

#19428 [Vue] remove use of angularjs from Feedback plugin
  plugins/Feedback/Feedback.php
  plugins/Feedback/stylesheets/feedback.less
  plugins/Feedback/templates/feedbackQuestionBanner.twig
  plugins/Feedback/templates/index.twig
  plugins/Feedback/tests/UI/FeedbackForm_spec.js
  plugins/Feedback/tests/UI/expected-screenshots/FeedbackForm_show.png
  plugins/Feedback/vue/dist/Feedback.umd.js
  plugins/Feedback/vue/dist/Feedback.umd.min.js
  plugins/Feedback/vue/src/FeedbackQuestion/FeedbackQuestion.adapter.ts
  plugins/Feedback/vue/src/FeedbackQuestion/FeedbackQuestion.vue
  plugins/Feedback/vue/src/RateFeature/RateFeature.adapter.ts
  plugins/Feedback/vue/src/index.ts
Labels: Needs Review, Do not close

#19449 [Vue] remove angularjs from CoreVisualizations plugin
  plugins/CoreVisualizations/Visualizations/Sparklines/Config.php
  plugins/CoreVisualizations/Widgets/SingleMetricView.php
  plugins/CoreVisualizations/javascripts/jqplot.js
  plugins/CoreVisualizations/javascripts/jqplotBarGraph.js
  plugins/CoreVisualizations/javascripts/jqplotEvolutionGraph.js
  plugins/CoreVisualizations/javascripts/seriesPicker.js
  plugins/CoreVisualizations/vue/dist/CoreVisualizations.umd.js
  plugins/CoreVisualizations/vue/dist/CoreVisualizations.umd.min.js
  plugins/CoreVisualizations/vue/src/SeriesPicker/SeriesPicker.adapter.ts
  plugins/CoreVisualizations/vue/src/SeriesPicker/SeriesPicker.less
  plugins/CoreVisualizations/vue/src/SingleMetricView/SingleMetricView.adapter.ts
  plugins/CoreVisualizations/vue/src/SingleMetricView/SingleMetricView.less
  plugins/CoreVisualizations/vue/src/index.ts
Labels: Needs Review, Do not close

#19450 [Vue] remove use of angularjs from CoreAdminHome
  plugins/CoreAdminHome/templates/generalSettings.twig
  plugins/CoreAdminHome/templates/home.twig
  plugins/CoreAdminHome/templates/trackingCodeGenerator.twig
  plugins/CoreAdminHome/templates/trackingFailures.twig
  plugins/CoreAdminHome/templates/whatIsNew.twig
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.js
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.min.js
  plugins/CoreAdminHome/vue/src/ArchivingSettings/ArchivingSettings.adapter.ts
  plugins/CoreAdminHome/vue/src/BrandingSettings/BrandingSettings.adapter.ts
  plugins/CoreAdminHome/vue/src/ImageTrackingCodeGenerator/ImageTrackingCodeGenerator.adapter.ts
  plugins/CoreAdminHome/vue/src/ImageTrackingCodeGenerator/ImageTrackingCodeGenerator.vue
  plugins/CoreAdminHome/vue/src/JsTrackingCodeGenerator/JsTrackingCodeGenerator.adapter.ts
  plugins/CoreAdminHome/vue/src/SmtpSettings/SmtpSettings.adapter.ts
  plugins/CoreAdminHome/vue/src/TrackingFailures/TrackingFailures.adapter.ts
  plugins/CoreAdminHome/vue/src/index.ts
Labels: Needs Review, Do not close

#19442 [Vue] remove angularjs from Dashboard plugin
  plugins/CoreHome/Controller.php
  plugins/CoreHome/templates/_indexContent.twig
  plugins/CoreHome/templates/getDefaultIndexView.twig
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/ExpandOnClick/ExpandOnClick.ts
  plugins/CoreHome/vue/src/ReportingMenu/ReportingMenu.store.ts
  plugins/CoreHome/vue/src/Tooltips/Tooltips.ts
  plugins/CoreVue/types/index.d.ts
  plugins/Dashboard/Controller.php
  plugins/Dashboard/Dashboard.php
  plugins/Dashboard/DashboardManagerControl.php
  plugins/Dashboard/DashboardSettingsControlBase.php
  plugins/Dashboard/javascripts/dashboard.js
  plugins/Dashboard/javascripts/dashboardObject.js
  plugins/Dashboard/javascripts/dashboardWidget.js
  plugins/Dashboard/javascripts/widgetMenu.js
  plugins/Dashboard/stylesheets/dashboard.less
  plugins/Dashboard/templates/_dashboardSettings.twig
  plugins/Dashboard/templates/_header.twig
  plugins/Dashboard/templates/embeddedIndex.twig
  plugins/Dashboard/templates/index.twig
  plugins/Dashboard/tests/UI/DashboardManager_spec.js
  plugins/Dashboard/tests/UI/Dashboard_spec.js
  plugins/Dashboard/vue/dist/Dashboard.umd.js
  plugins/Dashboard/vue/dist/Dashboard.umd.min.js
  plugins/Dashboard/vue/src/Dashboard/Dashboard.adapter.ts
  plugins/Dashboard/vue/src/Dashboard/Dashboard.store.adapter.ts
  plugins/Dashboard/vue/src/Dashboard/Dashboard.ts
  plugins/Dashboard/vue/src/DashboardSettings/DashboardSettings.vue
  plugins/Dashboard/vue/src/index.ts
  plugins/Morpheus/templates/_jsGlobalVariables.twig
Labels: Needs Review, Do not close

#19451 [Vue] remove use of angularjs from API plugin
  plugins/API/API.php
  plugins/API/stylesheets/glossary.less
  plugins/API/templates/glossary.twig
  plugins/API/templates/listAllAPI.twig
  plugins/API/vue/dist/API.umd.js
  plugins/API/vue/dist/API.umd.min.js
  plugins/API/vue/dist/umd.metadata.json
  plugins/API/vue/src/Glossary/Glossary.vue
  plugins/API/vue/src/index.ts
  tests/UI/expected-screenshots/UIIntegrationTest_glossary.png
  tests/UI/expected-screenshots/UIIntegrationTest_glossary_widgetized.png
Labels: Needs Review, Do not close

#19614 Improve check for provider plugin
  plugins/UserCountry/LocationProvider/DefaultProvider.php
Labels: not-in-changelog, Needs Review, Stability

#19618 Fix for page goals visualization showing hits instead of visits
  plugins/Goals/Visualizations/Goals.php
  plugins/Goals/tests/UI/expected-screenshots/Goals_action_goals_visualization_page_urls.png
  plugins/Goals/tests/UI/expected-screenshots/Goals_action_goals_visualization_page_urls_subtable.png
  plugins/Goals/tests/UI/expected-screenshots/Goals_goals_by_page_titles.png
  plugins/Goals/tests/UI/expected-screenshots/Goals_goals_by_pages.png
Labels: Bug

#19409 [Vue] remove angularjs from the Morpheus plugin
  plugins/Morpheus/Controller.php
  plugins/Morpheus/templates/admin.twig
  plugins/Morpheus/templates/contentBlock.twig
  plugins/Morpheus/templates/dashboard.twig
  plugins/Morpheus/templates/demo.twig
  plugins/Morpheus/templates/layout.twig
  plugins/Morpheus/tests/UI/expected-screenshots/Morpheus_load.png
  plugins/Morpheus/vue/dist/Morpheus.umd.js
  plugins/Morpheus/vue/dist/Morpheus.umd.min.js
  plugins/Morpheus/vue/dist/umd.metadata.json
  plugins/Morpheus/vue/src/Demo/Demo.vue
  plugins/Morpheus/vue/src/Demo/DemoCodePair.vue
  plugins/Morpheus/vue/src/index.ts
  tests/UI/expected-screenshots/Theme_demo.png
Labels: Do not close

#19471 [js]Update * to originHost
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: not-in-changelog

#19416 [Vue] remove angularjs from marketplace
  plugins/CorePluginsAdmin/Controller.php
  plugins/CorePluginsAdmin/CorePluginsAdmin.php
  plugins/CorePluginsAdmin/lang/en.json
  plugins/CorePluginsAdmin/stylesheets/plugins_admin.less
  plugins/CorePluginsAdmin/templates/macros.twig
  plugins/CorePluginsAdmin/templates/plugins.twig
  plugins/CorePluginsAdmin/templates/themes.twig
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/Plugins/PluginName.ts
  plugins/CorePluginsAdmin/vue/src/PluginsIntro/PluginsIntro.vue
  plugins/CorePluginsAdmin/vue/src/PluginsTable/PluginsTable.vue
  plugins/CorePluginsAdmin/vue/src/PluginsTable/PluginsTableWithUpdates.vue
  plugins/CorePluginsAdmin/vue/src/UploadPluginDialog/UploadPluginDialog.vue
  plugins/CorePluginsAdmin/vue/src/index.ts
  plugins/Marketplace/Marketplace.php
  plugins/Marketplace/templates/getNewPlugins.twig
  plugins/Marketplace/templates/getNewPluginsAdmin.twig
  plugins/Marketplace/templates/getPremiumFeatures.twig
  plugins/Marketplace/templates/licenseform.twig
  plugins/Marketplace/templates/macros.twig
  plugins/Marketplace/templates/overview.twig
  plugins/Marketplace/templates/plugin-list.twig
  plugins/Marketplace/templates/subscription-overview.twig
  plugins/Marketplace/templates/uploadPluginDialog.twig
  plugins/Marketplace/tests/UI/Marketplace_spec.js
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_no_license_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_no_license_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_with_exceeded_license_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_with_exceeded_license_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_with_license_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_with_license_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_superuser_enable_plugins_admin.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_superuser_enable_plugins_admin_with_multiserver_enabled.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_superuser_invalid_license_key_entered.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_superuser_remove_license_key_confirmed.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_superuser_valid_license_key_entered.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_themes_with_valid_license_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_themes_with_valid_license_superuser.png
  plugins/Marketplace/vue/dist/Marketplace.umd.js
  plugins/Marketplace/vue/dist/Marketplace.umd.min.js
  plugins/Marketplace/vue/src/GetNewPlugins/GetNewPlugins.vue
  plugins/Marketplace/vue/src/GetNewPluginsAdmin/GetNewPluginsAdmin.vue
  plugins/Marketplace/vue/src/GetPremiumFeatures/GetPremiumFeatures.vue
  plugins/Marketplace/vue/src/MissingReqsNotice/MissingReqsNotice.vue
  plugins/Marketplace/vue/src/OverviewIntro/OverviewIntro.vue
  plugins/Marketplace/vue/src/PluginName/PluginName.adapter.ts
  plugins/Marketplace/vue/src/SubscriptionOverview/SubscriptionOverview.vue
  plugins/Marketplace/vue/src/index.ts
  tests/UI/expected-screenshots/UIIntegrationTest_admin_plugins.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_plugins_no_internet.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_themes.png
  tests/UI/specs/UIIntegration_spec.js
Labels: Do not close

#19401 Adjust integration instruction for wordpress sites
  plugins/SitesManager/Controller.php
  plugins/SitesManager/SitesManager.php
  plugins/SitesManager/lang/en.json
  plugins/SitesManager/templates/_siteWithoutDataTabs.twig
  tests/UI/expected-screenshots/OneClickUpdate_login.png
Labels: not-in-changelog, Needs Review

#19631 [Vue] fix back button to dashboard
  plugins/Dashboard/vue/dist/Dashboard.umd.js
  plugins/Dashboard/vue/dist/Dashboard.umd.min.js
  plugins/Dashboard/vue/src/Dashboard/Dashboard.ts
Labels: Needs Review, Regression

#19611 Require password confirmation when inviting a user in UI
  CHANGELOG.md
  plugins/UsersManager/API.php
  plugins/UsersManager/UsersManager.php
  plugins/UsersManager/lang/en.json
  plugins/UsersManager/tests/UI/UsersManager_spec.js
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_invite_confirm.png
  plugins/UsersManager/vue/dist/UsersManager.umd.js
  plugins/UsersManager/vue/dist/UsersManager.umd.min.js
  plugins/UsersManager/vue/src/UserEditForm/UserEditForm.vue
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
Labels: c: Security, Needs Review

#19382 [Vue] remove use of angularjs from TwoFactorAuth plugin
  core/AssetManager/UIAssetFetcher/PluginUmdAssetFetcher.php
  plugins/Login/javascripts/login.js
  plugins/Login/templates/_formErrors.twig
  plugins/Login/vue/dist/Login.umd.js
  plugins/Login/vue/dist/Login.umd.min.js
  plugins/Login/vue/dist/umd.metadata.json
  plugins/Login/vue/src/FormErrors/FormErrors.vue
  plugins/Login/vue/src/index.ts
  plugins/PrivacyManager/vue/dist/umd.metadata.json
  plugins/TwoFactorAuth/TwoFactorAuth.php
  plugins/TwoFactorAuth/javascripts/twofactorauth.js
  plugins/TwoFactorAuth/templates/_setupTwoFactorAuth.twig
  plugins/TwoFactorAuth/templates/loginTwoFactorAuth.twig
  plugins/TwoFactorAuth/templates/setupFinished.twig
  plugins/TwoFactorAuth/templates/setupTwoFactorAuth.twig
  plugins/TwoFactorAuth/templates/setupTwoFactorAuthStandalone.twig
  plugins/TwoFactorAuth/templates/showRecoveryCodes.twig
  plugins/TwoFactorAuth/templates/userSettings.twig
  plugins/TwoFactorAuth/vue/dist/TwoFactorAuth.umd.js
  plugins/TwoFactorAuth/vue/dist/TwoFactorAuth.umd.min.js
  plugins/TwoFactorAuth/vue/dist/umd.metadata.json
  plugins/TwoFactorAuth/vue/src/LoginTwoFactorAuth/LoginTwoFactorAuth.vue
  plugins/TwoFactorAuth/vue/src/SetupFinished/SetupFinished.vue
  plugins/TwoFactorAuth/vue/src/SetupTwoFactorAuth/SetupTwoFactorAuth.vue
  plugins/TwoFactorAuth/vue/src/ShowRecoveryCodes/ShowRecoveryCodesPage.vue
  plugins/TwoFactorAuth/vue/src/UserSettings/UserSettings.vue
  plugins/TwoFactorAuth/vue/src/index.ts
  plugins/TwoFactorAuth/vue/src/types.ts
  plugins/UsersManager/UsersManager.php
  tests/PHPUnit/Integration/AssetManagerTest.php
Labels: Do not close

#19417 [Vue] remove angularjs from Login plugin
  plugins/Login/Controller.php
  plugins/Login/Login.php
  plugins/Login/javascripts/bruteforcelog.js
  plugins/Login/templates/bruteForceLog.twig
  plugins/Login/templates/confirmPassword.twig
  plugins/Login/templates/confirmResetPassword.twig
  plugins/Login/templates/invitation.twig
  plugins/Login/templates/login.twig
  plugins/Login/vue/dist/Login.umd.js
  plugins/Login/vue/dist/Login.umd.min.js
  plugins/Login/vue/src/BruteForceLog/BruteForceLog.vue
  plugins/Login/vue/src/index.ts
Labels: Needs Review, Do not close

#19640 fix randomly failing ui tests
  plugins/UsersManager/tests/UI/UsersManager_spec.js
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_resend_success.png
Labels: c: Tests & QA, not-in-changelog

#19632 Fix CSP header when viewing plugin details
  plugins/CorePluginsAdmin/Controller.php
Labels: Needs Review, Regression

#19594 Do not accept invalid SSL certificates for requests to ASPSMS and Clockwork
  CHANGELOG.md
  plugins/Diagnostics/tests/UI/expected-screenshots/Diagnostics_page.png
  plugins/MobileMessaging/Diagnostic/MobileMessagingInformational.php
  plugins/MobileMessaging/SMSProvider/ASPSMS.php
  plugins/MobileMessaging/SMSProvider/Clockwork.php
  plugins/MobileMessaging/config/config.php
Labels: Needs Review, Stale

#19641 Fix logging when invalidating reports
  core/Archive/ArchiveInvalidator/InvalidationResult.php
  plugins/CoreAdminHome/Commands/InvalidateReportData.php
Labels: not-in-changelog, Needs Review

#19621 Removes deprecated JSON2 API format
  CHANGELOG.md
  core/API/ApiRenderer.php
  tests/PHPUnit/Unit/API/ApiRendererTest.php
Labels: not-in-changelog, Needs Review, Stale

#19662 Ignore duplicate key errors when creating temporary tables
  core/DataAccess/LogAggregator.php
Labels: not-in-changelog, Needs Review

#19486 [Vue] remove angularjs from CustomDimensions plugin
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/MatomoUrl/MatomoUrl.ts
  plugins/CoreHome/vue/src/SiteSelector/SiteSelector.vue
  plugins/CustomDimensions/templates/manage.twig
  plugins/CustomDimensions/vue/dist/CustomDimensions.umd.js
  plugins/CustomDimensions/vue/dist/CustomDimensions.umd.min.js
  plugins/CustomDimensions/vue/src/Edit/Edit.adapter.ts
  plugins/CustomDimensions/vue/src/Edit/Edit.vue
  plugins/CustomDimensions/vue/src/List/List.adapter.ts
  plugins/CustomDimensions/vue/src/List/List.vue
  plugins/CustomDimensions/vue/src/Manage/Manage.adapter.ts
  plugins/CustomDimensions/vue/src/Manage/Manage.vue
  plugins/CustomDimensions/vue/src/index.ts
Labels: Do not close

#19670 Fix SiteSelector initially might show too many sites
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/SiteSelector/SiteSelector.vue
  plugins/CoreHome/vue/src/SiteSelector/SitesStore.ts
Labels: not-in-changelog, Needs Review, Regression

#19673 Added code to exclude Microsoft and Yandex click from query parameters
  config/global.ini.php
  tests/PHPUnit/Integration/Tracker/ActionTest.php
Labels: Needs Review

#19418 [Vue] remove angularjs from the Live plugin
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/Passthrough/Passthrough.vue
  plugins/CoreHome/vue/src/index.ts
  plugins/Live/Controller.php
  plugins/Live/Live.php
  plugins/Live/javascripts/SegmentedVisitorLog.js
  plugins/Live/javascripts/live.js
  plugins/Live/stylesheets/live.less
  plugins/Live/templates/_totalVisitors.twig
  plugins/Live/templates/getLastVisitsStart.twig
  plugins/Live/templates/index.twig
  plugins/Live/templates/indexVisitorLog.twig
  plugins/Live/vue/dist/Live.umd.js
  plugins/Live/vue/dist/Live.umd.min.js
  plugins/Live/vue/src/IndexHeader/IndexHeader.vue
  plugins/Live/vue/src/LastVisits/LastVisits.ts
  plugins/Live/vue/src/LivePage/LivePage.vue
  plugins/Live/vue/src/LiveWidget/LiveWidgetRefresh.adapter.ts
  plugins/Live/vue/src/LiveWidget/LiveWidgetRefresh.ts
  plugins/Live/vue/src/TotalVisitors/TotalVisitors.vue
  plugins/Live/vue/src/index.ts
  plugins/Morpheus/stylesheets/main.less
  plugins/ScheduledReports/vue/dist/umd.metadata.json
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_realtime_visits.png
  tests/UI/specs/UIIntegration_spec.js
Labels: Do not close

#19425 [Vue] remove angularjs from Installation plugin
  config/environment/ui-test.php
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/ContentTable/ContentTable.ts
  plugins/Diagnostics/Diagnostic/DiagnosticResult.php
  plugins/Diagnostics/Diagnostic/DiagnosticResultItem.php
  plugins/Diagnostics/Diagnostic/RequiredPhpSetting.php
  plugins/Diagnostics/tests/UI/expected-screenshots/Diagnostics_page.png
  plugins/Installation/Controller.php
  plugins/Installation/Installation.php
  plugins/Installation/View.php
  plugins/Installation/stylesheets/systemCheckPage.less
  plugins/Installation/templates/_systemCheckLegend.twig
  plugins/Installation/templates/_systemCheckSection.twig
  plugins/Installation/templates/getSystemCheckWidget.twig
  plugins/Installation/templates/layout.twig
  plugins/Installation/templates/systemCheck.twig
  plugins/Installation/templates/systemCheckPage.twig
  plugins/Installation/tests/UI/expected-screenshots/Installation_system_check.png
  plugins/Installation/vue/dist/Installation.umd.js
  plugins/Installation/vue/dist/Installation.umd.min.js
  plugins/Installation/vue/dist/umd.metadata.json
  plugins/Installation/vue/src/SystemCheck/DiagnosticTable.vue
  plugins/Installation/vue/src/SystemCheck/SystemCheck.vue
  plugins/Installation/vue/src/SystemCheck/SystemCheckLegend.vue
  plugins/Installation/vue/src/SystemCheck/SystemCheckPage.vue
  plugins/Installation/vue/src/SystemCheck/SystemCheckSection.vue
  plugins/Installation/vue/src/index.ts
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_invite_confirm.png
Labels: Needs Review, Do not close

#19680 filtering a user's permissions, capabilities fixes
  plugins/UsersManager/Model.php
  plugins/UsersManager/tests/Integration/APITest.php
  plugins/UsersManager/tests/UI/UsersManager_spec.js
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_admin_view_admin_filter_permissions.png
Labels: not-in-changelog

#19685 Ensure to properly escape widgetid attribute
  plugins/CoreHome/DataTableRowAction/RowEvolution.php
  plugins/Dashboard/javascripts/dashboardObject.js
Labels: c: Security, not-in-changelog, Needs Review

#19434 [Vue] remove angularjs from Diagnostics plugin
  plugins/Diagnostics/Diagnostics.php
  plugins/Diagnostics/templates/configfile.twig
  plugins/Diagnostics/vue/dist/Diagnostics.umd.js
  plugins/Diagnostics/vue/dist/Diagnostics.umd.min.js
  plugins/Diagnostics/vue/dist/umd.metadata.json
  plugins/Diagnostics/vue/src/ConfigFile/ConfigFile.vue
  plugins/Diagnostics/vue/src/index.ts
  plugins/Installation/templates/getSystemCheckWidget.twig
  plugins/Live/templates/_totalVisitors.twig
  plugins/PrivacyManager/vue/dist/umd.metadata.json
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
  tests/UI/specs/UIIntegration_spec.js
Labels: Needs Review, Do not close
