Repository matomo-org/matomo, pull requests merged in 2023-10, with the labels that each got.

#21330 Bump migration script to RC5
  core/Updates/5.0.0-rc5.php
Labels: Task, not-in-changelog, Needs Review

#21327 Translations update from Hosted Weblate
  lang/cs.json
  lang/el.json
  lang/uk.json
  plugins/API/lang/fi.json
  plugins/CoreAdminHome/lang/el.json
  plugins/CoreAdminHome/lang/uk.json
  plugins/Goals/lang/cs.json
  plugins/ScheduledReports/lang/fi.json
  plugins/SitesManager/lang/bg.json
  plugins/SitesManager/lang/ca.json
  plugins/SitesManager/lang/cs.json
  plugins/SitesManager/lang/da.json
  plugins/SitesManager/lang/de.json
  plugins/SitesManager/lang/el.json
  plugins/SitesManager/lang/es-ar.json
  plugins/SitesManager/lang/es.json
  plugins/SitesManager/lang/fi.json
  plugins/SitesManager/lang/fr.json
  plugins/SitesManager/lang/id.json
  plugins/SitesManager/lang/it.json
  plugins/SitesManager/lang/ja.json
  plugins/SitesManager/lang/ko.json
  plugins/SitesManager/lang/nb.json
  plugins/SitesManager/lang/nl.json
  plugins/SitesManager/lang/pl.json
  plugins/SitesManager/lang/pt-br.json
  plugins/SitesManager/lang/pt.json
  plugins/SitesManager/lang/ru.json
  plugins/SitesManager/lang/sq.json
  plugins/SitesManager/lang/sr.json
  plugins/SitesManager/lang/sv.json
  plugins/SitesManager/lang/tr.json
  plugins/SitesManager/lang/uk.json
  plugins/SitesManager/lang/zh-cn.json
  plugins/SitesManager/lang/zh-tw.json
  plugins/UsersManager/lang/el.json
  plugins/VisitFrequency/lang/de.json
Labels: not-in-changelog, c: i18n

#21234 Fix regression with subtable labels
  plugins/CoreHome/javascripts/dataTable_rowactions.js
Labels: Needs Review, Regression, Stale

#21335 Fix failing UI tests caused by update message partially shown
  plugins/CoreHome/tests/UI/VersionInfoHeaderMessage_spec.js
Labels: c: Tests & QA, not-in-changelog

#21336 Hide "what's new" popup from anonymous users
  core/Plugin/Controller.php
Labels: not-in-changelog, Needs Review

#21338 Use bound sql and backticks for table name
  core/Updates/5.0.0-rc2.php
Labels: Task, not-in-changelog, Needs Review

#21347 Translations update from Hosted Weblate
  plugins/JsTrackerInstallCheck/lang/es.json
  plugins/UserCountry/lang/it.json
Labels: Task, not-in-changelog, c: i18n

#21359 Use correct ISO code attribute for Italy regions on map
  plugins/UserCountryMap/javascripts/visitor-map.js
Labels: not-in-changelog, Needs Review

#21362 Ensure parameter is provided in correct type
  plugins/CustomDimensions/RecordBuilders/CustomDimension.php
  plugins/DevicesDetection/RecordBuilders/Base.php
  plugins/Referrers/RecordBuilders/Referrers.php
  plugins/UserCountry/RecordBuilders/Locations.php
  plugins/VisitTime/RecordBuilders/ServerTime.php
Labels: not-in-changelog, Needs Review

#21360 Fix possible call to undefined method
  plugins/API/Filter/DataComparisonFilter/ComparisonRowGenerator.php
Labels: not-in-changelog, Needs Review

#21343 add aggregation ops to new datatable instance as metadata in Row::sumRowWithLabelToSubtable()
  core/DataTable/Row.php
Labels: Needs Review, Regression

#21364 Fix segment SQL fetching for data comparison
  core/Segment.php
Labels: not-in-changelog, Needs Review

#21342 Fix last-n date lookup query for calculate-conversion-pages command
  plugins/Goals/Commands/CalculateConversionPages.php
  plugins/Goals/tests/System/CalculateConversionPagesCommandTest.php
Labels: Bug, not-in-changelog, Needs Review

#21341 Fix for "What's new" content visible when it shouldn't be
  core/Changes/Model.php
  plugins/CoreAdminHome/templates/whatIsNew.twig
  plugins/CorePluginsAdmin/CorePluginsAdmin.php
Labels: Bug, Needs Review

#21376 Improve email headers for feedback mails
  plugins/Feedback/API.php
Labels: not-in-changelog, Needs Review

#21385 Ensure segment generator fetches available segments when site is changed
  plugins/SegmentEditor/vue/dist/SegmentEditor.umd.js
  plugins/SegmentEditor/vue/dist/SegmentEditor.umd.min.js
  plugins/SegmentEditor/vue/src/SegmentGenerator/SegmentGenerator.store.ts
Labels: not-in-changelog, Needs Review

#21370 Fix problem with unprefixed group by columns in select queries
  core/DataAccess/LogAggregator.php
  plugins/Transitions/API.php
  tests/PHPUnit/Integration/DataAccess/LogAggregatorTest.php
Labels: not-in-changelog, Needs Review

#21383 Fix OTP code not visible
  plugins/TwoFactorAuth/tests/UI/TwoFactorAuth_spec.js
  plugins/TwoFactorAuth/vue/dist/TwoFactorAuth.umd.js
  plugins/TwoFactorAuth/vue/dist/TwoFactorAuth.umd.min.js
  plugins/TwoFactorAuth/vue/src/SetupTwoFactorAuth/SetupTwoFactorAuth.vue
Labels: not-in-changelog, Needs Review

#21393 Cast column label to string to stop magic casting issues. Version 5
  core/DataTable.php
Labels: not-in-changelog, Needs Review

#21366 Cast column label to string to stop magic casting issues.
  core/DataTable.php
Labels: not-in-changelog, Needs Review

#21390 Automatically set translation for label column based on dimension
  core/Plugin/ViewDataTable.php
  plugins/Actions/Reports/GetDownloads.php
  plugins/Actions/Reports/GetEntryPageTitles.php
  plugins/Actions/Reports/GetEntryPageUrls.php
  plugins/Actions/Reports/GetExitPageTitles.php
  plugins/Actions/Reports/GetExitPageUrls.php
  plugins/Actions/Reports/GetOutlinks.php
  plugins/Actions/Reports/GetPageTitles.php
  plugins/Actions/Reports/GetPageTitlesFollowingSiteSearch.php
  plugins/Actions/Reports/GetPageUrls.php
  plugins/Actions/Reports/GetSiteSearchCategories.php
  plugins/Actions/Reports/GetSiteSearchKeywords.php
  plugins/Actions/Reports/GetSiteSearchNoResultKeywords.php
  plugins/Contents/Reports/Base.php
  plugins/CustomDimensions/GetCustomDimension.php
  plugins/DevicePlugins/Reports/GetPlugin.php
  plugins/DevicesDetection/Reports/GetBrowserEngines.php
  plugins/DevicesDetection/Reports/GetBrowserVersions.php
  plugins/DevicesDetection/Reports/GetBrowsers.php
  plugins/DevicesDetection/Reports/GetOsFamilies.php
  plugins/ExampleReport/Reports/GetExampleReport.php
  plugins/Goals/Reports/GetDaysToConversion.php
  plugins/Goals/Reports/GetVisitsUntilConversion.php
  plugins/Referrers/Reports/GetAll.php
  plugins/Referrers/Reports/GetCampaigns.php
  plugins/Referrers/Reports/GetKeywordsFromCampaignId.php
  plugins/Referrers/Reports/GetKeywordsFromSearchEngineId.php
  plugins/Referrers/Reports/GetSearchEngines.php
  plugins/Referrers/Reports/GetSearchEnginesFromKeywordId.php
  plugins/Referrers/Reports/GetSocials.php
  plugins/Referrers/Reports/GetUrlsForSocial.php
  plugins/Referrers/Reports/GetUrlsFromWebsiteId.php
  plugins/Referrers/Reports/GetWebsites.php
  plugins/Resolution/Reports/GetConfiguration.php
  plugins/Resolution/Reports/GetResolution.php
  plugins/UserCountry/Reports/GetCity.php
  plugins/UserCountry/Reports/GetContinent.php
  plugins/UserCountry/Reports/GetCountry.php
  plugins/UserCountry/Reports/GetRegion.php
  plugins/UserLanguage/Reports/GetLanguage.php
  plugins/VisitTime/Reports/GetByDayOfWeek.php
  plugins/VisitorInterest/Reports/GetNumberOfVisitsPerVisitDuration.php
Labels: not-in-changelog, Needs Review, Technical debt

#21322 Fix problems with displayed encoded entities in javascript translations
  core/Translation/Translator.php
  plugins/CoreAdminHome/tests/UI/expected-screenshots/MobileMenu_mobileMenuPartial.png
Labels: not-in-changelog, Needs Review

#21401 Add premium plugin menu items to professional services (V5)
  plugins/ProfessionalServices/Categories/PromoAbTestingCategory.php
  plugins/ProfessionalServices/Categories/PromoCrashAnalytics.php
  plugins/ProfessionalServices/Categories/PromoCustomReportsCategory.php
  plugins/ProfessionalServices/Categories/PromoFormsCategory.php
  plugins/ProfessionalServices/Categories/PromoFunnelsCategory.php
  plugins/ProfessionalServices/Categories/PromoHeatmapCategory.php
  plugins/ProfessionalServices/Categories/PromoMediaCategory.php
  plugins/ProfessionalServices/Categories/PromoSessionRecordingCategory.php
  plugins/ProfessionalServices/PromoWidgetApplicable.php
  plugins/ProfessionalServices/Widgets/PromoAbTesting.php
  plugins/ProfessionalServices/Widgets/PromoCrashAnalytics.php
  plugins/ProfessionalServices/Widgets/PromoCustomReports.php
  plugins/ProfessionalServices/Widgets/PromoForms.php
  plugins/ProfessionalServices/Widgets/PromoFunnels.php
  plugins/ProfessionalServices/Widgets/PromoHeatmap.php
  plugins/ProfessionalServices/Widgets/PromoMedia.php
  plugins/ProfessionalServices/Widgets/PromoSessionRecording.php
  plugins/ProfessionalServices/lang/en.json
  plugins/ProfessionalServices/tests/Unit/PromoWidgetApplicableTest.php
  tests/PHPUnit/Integration/Category/CategoryListTest.php
Labels: not-in-changelog, Needs Review

#21395 Esnure only Datatable objects are used for rendering visualizations
  core/Plugin/Visualization.php
Labels: not-in-changelog, Needs Review

#21398 Ignore summary row when aggregating goal metrics for custom dimensions
  plugins/CustomDimensions/RecordBuilders/CustomDimension.php
Labels: not-in-changelog, Needs Review

#21384 Hide update/version info when auto-update disabled
  core/View.php
  plugins/CoreHome/templates/_headerMessage.twig
Labels: not-in-changelog, c: Design / UI, Needs Review

#21394 Add premium plugin menu items to professional services [4.x]
  plugins/ProfessionalServices/Categories/PromoAbTestingCategory.php
  plugins/ProfessionalServices/Categories/PromoCrashAnalytics.php
  plugins/ProfessionalServices/Categories/PromoCustomReportsCategory.php
  plugins/ProfessionalServices/Categories/PromoFormsCategory.php
  plugins/ProfessionalServices/Categories/PromoFunnelsCategory.php
  plugins/ProfessionalServices/Categories/PromoHeatmapCategory.php
  plugins/ProfessionalServices/Categories/PromoMediaCategory.php
  plugins/ProfessionalServices/Categories/PromoSessionRecordingCategory.php
  plugins/ProfessionalServices/PromoWidgetApplicable.php
  plugins/ProfessionalServices/Widgets/PromoAbTesting.php
  plugins/ProfessionalServices/Widgets/PromoCrashAnalytics.php
  plugins/ProfessionalServices/Widgets/PromoCustomReports.php
  plugins/ProfessionalServices/Widgets/PromoForms.php
  plugins/ProfessionalServices/Widgets/PromoFunnels.php
  plugins/ProfessionalServices/Widgets/PromoHeatmap.php
  plugins/ProfessionalServices/Widgets/PromoMedia.php
  plugins/ProfessionalServices/Widgets/PromoSessionRecording.php
  plugins/ProfessionalServices/lang/en.json
  plugins/ProfessionalServices/tests/Unit/PromoWidgetApplicableTest.php
  tests/PHPUnit/Integration/Category/CategoryListTest.php
Labels: not-in-changelog, Needs Review

#21408 Add common download file extensions
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: Enhancement, not-in-changelog, c: Tracking

#21412 Enable searching on the device type report
  plugins/DevicesDetection/Reports/GetType.php
Labels: Enhancement, not-in-changelog, Needs Review

#21420 Fix warning Trying to add two strings in DataTable\Row::sumRowArray
  plugins/CoreHome/Columns/Metrics/EvolutionMetric.php
  plugins/CoreHome/tests/Integration/Columns/Metrics/EvolutionMetricTest.php
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_Conversions_MultiSites.getAll_firstSite_lastN__API.getProcessedReport_day.xml
Labels: Needs Review

#21430 Add MK and MC to the list of people allowed to release a version
  .github/workflows/release.yml
Labels: Task, not-in-changelog

#21433 Fix undefined index if forced archiving is configured
  core/ArchiveProcessor/Loader.php
  tests/PHPUnit/Integration/ArchiveProcessor/LoaderLockTest.php
  tests/PHPUnit/Integration/ArchiveProcessor/LoaderTest.php
  tests/PHPUnit/Integration/ArchiveProcessor/ParametersTest.php
Labels: not-in-changelog, Needs Review

#21429 Fix error in template
  plugins/SitesManager/templates/_wordpressTabInstructions.twig
Labels: Bug, not-in-changelog, Regression

#21435 Fix for e.externalRawLink is not a function error
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/createVueApp.ts
Labels: Bug, not-in-changelog, Regression

#21445 Fix for card formatting on what's new popup
  plugins/CoreHome/stylesheets/layout.less
  plugins/CoreHome/tests/UI/expected-screenshots/WhatIsNew_what_is_new.png
Labels: Bug, not-in-changelog, Regression

#21436 Added code to not add MaxExecutionTimeHintToQuery if already present
  core/DbHelper.php
  tests/PHPUnit/Unit/DbHelperTest.php
Labels: not-in-changelog, Needs Review

#21454 Fix for truncated link in error message
  core/API/Request.php
Labels: Bug, not-in-changelog, Regression

#21447 Fix incorrect URL parameter in update notification
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.js
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.min.js
  plugins/CoreAdminHome/vue/src/JsTrackingCodeGenerator/JsTrackingCodeGenerator.vue
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/VersionInfoHeaderMessage/VersionInfoHeaderMessage.vue
  plugins/Morpheus/javascripts/piwikHelper.js
Labels: Bug, not-in-changelog, Regression

#21434 Run Matomo in PHP 8.3
  .github/workflows/matomo-tests.yml
  plugins/Marketplace/tests/Integration/EnvironmentTest.php
  plugins/TwoFactorAuth/TwoFactorAuth.php
  tests/resources/DataTables-archived-different-formats.php
Labels: not-in-changelog, Needs Review, Technical debt

#21455 Display the Widgetize ViewAccessRequired exception as an HTML message
  core/API/Request.php
Labels: Bug

#21452 Exclude twclid URL parameter by default
  config/global.ini.php
  tests/PHPUnit/Integration/Tracker/ActionTest.php
Labels: Needs Review

#21451 Fix possible action data loss in segmentation due to signed int32 overflow
  core/DataAccess/RawLogDao.php
Labels: Bug
