Repository matomo-org/matomo, pull requests merged in 2023-12, with the labels that each got.

#21605 Move plugin related sub menu items to new Plugins menu item
  core/Menu/MenuAdmin.php
  lang/en.json
  plugins/CoreAdminHome/Menu.php
  plugins/CoreAdminHome/tests/UI/expected-screenshots/MobileMenu_mobileMenuPartial.png
  plugins/CoreAdminHome/tests/UI/expected-screenshots/TrackingCodeGenerator_initial.png
  plugins/CorePluginsAdmin/Menu.php
  plugins/Marketplace/Menu.php
  plugins/Morpheus/Controller.php
  plugins/Morpheus/Menu.php
  plugins/Morpheus/fonts/matomo.eot
  plugins/Morpheus/fonts/matomo.svg
  plugins/Morpheus/fonts/matomo.ttf
  plugins/Morpheus/fonts/matomo.woff
  plugins/Morpheus/fonts/matomo.woff2
  plugins/Morpheus/fonts/selection.json
  plugins/Morpheus/fonts/svgs/icon-plugin.svg
  plugins/Morpheus/stylesheets/base/icons.css
  plugins/Morpheus/tests/UI/expected-screenshots/Morpheus_load.png
  plugins/PrivacyManager/Menu.php
  plugins/UsersManager/tests/UI/expected-screenshots/UserSettings_signup_success.png
  tests/UI/expected-screenshots/Menus_admin_changed.png
  tests/UI/expected-screenshots/Menus_admin_loaded.png
  tests/UI/expected-screenshots/Menus_admin_websites.png
  tests/UI/expected-screenshots/Menus_mobile_left.png
  tests/UI/expected-screenshots/Theme_demo.png
  tests/UI/expected-screenshots/UIIntegrationTest_actions_outlinks_vlog.png
Labels: c: Usability, Needs Review

#21623 Log reason when archiving stops
  core/CronArchive.php
Labels: Needs Review

#21639 Remove useless method call
  plugins/CoreUpdater/Controller.php
Labels: not-in-changelog, Needs Review

#21644 Remove misplaced curly closing brackets
  plugins/Annotations/templates/getEvolutionIcons.twig
  plugins/CoreHome/templates/_dataTableFooter.twig
  plugins/UserCountryMap/templates/visitorMap.twig
Labels: Bug, not-in-changelog, Needs Review, Technical debt

#21597 Translations update from Hosted Weblate
  lang/ca.json
  lang/el.json
  lang/es.json
  lang/eu.json
  lang/pt-br.json
  lang/sv.json
  lang/tr.json
  plugins/CoreAdminHome/lang/eu.json
  plugins/Diagnostics/lang/el.json
  plugins/Diagnostics/lang/es.json
  plugins/JsTrackerInstallCheck/lang/eu.json
  plugins/Marketplace/lang/de.json
  plugins/PrivacyManager/lang/eu.json
  plugins/PrivacyManager/lang/uk.json
  plugins/ProfessionalServices/lang/el.json
  plugins/Referrers/lang/eu.json
  plugins/SegmentEditor/lang/eu.json
  plugins/SitesManager/lang/eu.json
  plugins/Tour/lang/eu.json
  plugins/UsersManager/lang/eu.json
  plugins/VisitorInterest/lang/eu.json
Labels: not-in-changelog, c: i18n

#21642 [Coding Style] Prepare migration to PSR 12 compatibility
  composer.json
  composer.lock
  phpcs.xml
Labels: c: Tests & QA, not-in-changelog, Technical debt

#21634 Improve tests around (complex) action segments
  tests/PHPUnit/System/ComplicatedSegmentTest.php
  tests/PHPUnit/System/ImportLogsTest.php
  tests/PHPUnit/System/expected/test_ComplicatedSegment_SegmentWithManyActions__Live.getLastVisitsDetails_day.xml
  tests/PHPUnit/System/expected/test_ComplicatedSegment_SegmentWithManyActions__VisitsSummary.get_day.xml
  tests/PHPUnit/System/expected/test_ImportLogs_complexActionSegment__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs_complexActionSegment__VisitsSummary.get_month.xml
Labels: c: Tests & QA, not-in-changelog, Needs Review

#21541 respect MATOMO_PLUGIN_DIRS global in vue:build
  core/AssetManager/UIAssetFetcher/PluginUmdAssetFetcher.php
  core/Plugin/Manager.php
  plugins/CoreVue/Commands/Build.php
  vue.config.js
Labels: not-in-changelog

#21649 [Coding Style] Enable rule PSR12.Files.OpenTag.NotAlone
  phpcs.xml
  plugins/SitesManager/SiteContentDetection/BugSnag.php
  plugins/SitesManager/SiteContentDetection/RaygunCrashReporting.php
  plugins/SitesManager/SiteContentDetection/Rollbar.php
  plugins/SitesManager/SiteContentDetection/Sentry.php
  plugins/SitesManager/SiteContentDetection/TrackJs.php
  plugins/SitesManager/tests/Unit/SiteContentDetection/BugSnagTest.php
  plugins/SitesManager/tests/Unit/SiteContentDetection/RaygunCrashReportingTest.php
  plugins/SitesManager/tests/Unit/SiteContentDetection/RollbarTest.php
  plugins/SitesManager/tests/Unit/SiteContentDetection/SentryTest.php
  plugins/SitesManager/tests/Unit/SiteContentDetection/TrackJsTest.php
  tests/PHPUnit/Unit/UpdateCheckTest.php
Labels: not-in-changelog, Technical debt

#21617 Adds new license key section to plugin menu
  plugins/CoreAdminHome/tests/UI/expected-screenshots/MobileMenu_mobileMenuPartial.png
  plugins/Marketplace/Controller.php
  plugins/Marketplace/Marketplace.php
  plugins/Marketplace/Menu.php
  plugins/Marketplace/lang/en.json
  plugins/Marketplace/stylesheets/marketplace.less
  plugins/Marketplace/templates/manageLicenseKey.twig
  plugins/Marketplace/tests/UI/ManageLicense_spec.js
  plugins/Marketplace/tests/UI/expected-screenshots/ManageLicense_invalid.png
  plugins/Marketplace/tests/UI/expected-screenshots/ManageLicense_loaded.png
  plugins/Marketplace/tests/UI/expected-screenshots/ManageLicense_remove_dialog.png
  plugins/Marketplace/tests/UI/expected-screenshots/ManageLicense_removed.png
  plugins/Marketplace/tests/UI/expected-screenshots/ManageLicense_valid.png
  plugins/Marketplace/vue/dist/Marketplace.umd.js
  plugins/Marketplace/vue/dist/Marketplace.umd.min.js
  plugins/Marketplace/vue/src/ManageLicenseKey/ManageLicenseKey.vue
  plugins/Marketplace/vue/src/index.ts
Labels: Enhancement, Needs Review

#21656 [Coding Style] Enable rule Squiz.WhiteSpace.ScopeKeywordSpacing.Incorrect
  phpcs.xml
  plugins/Actions/Segment.php
  plugins/CoreHome/Segment.php
Labels: c: Tests & QA, not-in-changelog, Needs Review, Technical debt

#21626 [4.x] Adds new license key section to plugin menu
  plugins/Marketplace/Controller.php
  plugins/Marketplace/Marketplace.php
  plugins/Marketplace/Menu.php
  plugins/Marketplace/lang/en.json
  plugins/Marketplace/stylesheets/marketplace.less
  plugins/Marketplace/templates/manageLicenseKey.twig
  plugins/Marketplace/tests/UI/ManageLicense_spec.js
  plugins/Marketplace/tests/UI/expected-screenshots/ManageLicense_invalid.png
  plugins/Marketplace/tests/UI/expected-screenshots/ManageLicense_loaded.png
  plugins/Marketplace/tests/UI/expected-screenshots/ManageLicense_remove_dialog.png
  plugins/Marketplace/tests/UI/expected-screenshots/ManageLicense_removed.png
  plugins/Marketplace/tests/UI/expected-screenshots/ManageLicense_valid.png
  plugins/Marketplace/vue/dist/Marketplace.umd.js
  plugins/Marketplace/vue/dist/Marketplace.umd.min.js
  plugins/Marketplace/vue/src/ManageLicenseKey/ManageLicenseKey.vue
  plugins/Marketplace/vue/src/index.ts
  tests/UI/expected-screenshots/UIIntegrationTest_admin_plugins.png
Labels: c: Usability, Needs Review

#21658 Fix transition popover for page titles with percent signs
  plugins/Transitions/javascripts/transitions.js
Labels: Bug, not-in-changelog, c: Design / UI, Needs Review

#21653 Improve performance of queries for complex custom reports using segments
  core/DataAccess/LogAggregator.php
  tests/PHPUnit/Integration/DataAccess/LogAggregatorTest.php
Labels: c: Performance, Needs Review

#21665 PG-17501 Updates to Github bug template for better UX
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: Task, not-in-changelog

#21671 [Coding style] Enable rule Generic.WhiteSpace.ScopeIndent.Incorrect(Exact)
  core/API/Request.php
  core/AssetManager/UIAssetFetcher/PluginUmdAssetFetcher.php
  core/CliMulti/Process.php
  core/CliMulti/RequestCommand.php
  core/CronArchive/QueueConsumer.php
  core/DataAccess/RawLogDao.php
  core/DataTable/Filter/AddColumnsProcessedMetricsGoal.php
  core/Date.php
  core/Db/BatchInsert.php
  core/FrontController.php
  core/Http.php
  core/Plugin.php
  core/Plugin/Visualization.php
  core/SiteContentDetector.php
  core/Tracker/Db.php
  phpcs.xml
  plugins/Actions/ArchivingHelper.php
  plugins/CoreAdminHome/OptOutManager.php
  plugins/Diagnostics/Commands/UnexpectedFiles.php
  plugins/Ecommerce/Columns/Revenue.php
  plugins/Goals/Commands/CalculateConversionPages.php
  plugins/Goals/tests/System/CalculateConversionPagesCommandTest.php
  plugins/Goals/tests/System/ProcessDependentArchiveTest.php
  plugins/Intl/Commands/GenerateIntl.php
  plugins/Login/Login.php
  plugins/Login/Security/BruteForceDetection.php
  plugins/Marketplace/tests/Integration/PluginsTest.php
  plugins/MobileMessaging/ReportRenderer/Sms.php
  plugins/MultiSites/API.php
  plugins/MultiSites/tests/Integration/DashboardTest.php
  plugins/Tour/Engagement/Levels.php
  plugins/Transitions/API.php
  plugins/TwoFactorAuth/Controller.php
  plugins/TwoFactorAuth/Dao/RecoveryCodeRandomGenerator.php
  plugins/TwoFactorAuth/Dao/TwoFaSecretStaticGenerator.php
  plugins/UsersManager/API.php
  plugins/VisitorInterest/VisitorInterest.php
  tests/PHPUnit/Framework/TestCase/SystemTestCase.php
  tests/PHPUnit/Framework/TestingEnvironmentManipulator.php
  tests/PHPUnit/System/TimezonesTest.php
  tests/PHPUnit/Unit/Period/RangeTest.php
  tests/PHPUnit/Unit/Tracker/CacheTest.php
  tests/PHPUnit/bootstrap.php
Labels: c: Tests & QA, not-in-changelog, Needs Review, Technical debt

#21655 Translations update from Hosted Weblate
  lang/fr.json
  lang/ru.json
  lang/uk.json
  plugins/Contents/lang/eu.json
  plugins/CustomDimensions/lang/eu.json
  plugins/Diagnostics/lang/ca.json
  plugins/Diagnostics/lang/eu.json
  plugins/Ecommerce/lang/eu.json
  plugins/Marketplace/lang/ca.json
  plugins/Marketplace/lang/el.json
  plugins/MobileMessaging/lang/eu.json
  plugins/ProfessionalServices/lang/eu.json
  plugins/ProfessionalServices/lang/fr.json
  plugins/ProfessionalServices/lang/sv.json
Labels: not-in-changelog, c: i18n

#21680 [Coding Style] Enable rule PSR12.Classes.AnonClassDeclaration.SpaceAfterKeyword
  phpcs.xml
  plugins/ScheduledReports/tests/Integration/ApiTest.php
  tests/PHPUnit/Integration/ArchiveProcessingTest.php
  tests/PHPUnit/Integration/MailTest.php
  tests/PHPUnit/Integration/SegmentTest.php
  tests/PHPUnit/Unit/ArchiveProcessor/RecordBuilderTest.php
  tests/PHPUnit/Unit/CliMulti/RequestParserTest.php
Labels: c: Tests & QA, not-in-changelog, Needs Review

#21681 [Coding Style] Enable rule PSR12.Classes.ClassInstantiation.MissingParentheses
  core/ArchiveProcessor.php
  core/BaseFactory.php
  core/Columns/MetricsList.php
  core/Console.php
  core/CronArchive.php
  core/DataTable.php
  core/DataTable/Map.php
  core/Option.php
  core/Plugin/Manager.php
  core/Plugin/ReportsProvider.php
  core/Segment/SegmentsList.php
  core/Singleton.php
  core/Tracker/Db.php
  core/View.php
  core/Widget/WidgetsList.php
  phpcs.xml
  plugins/Overlay/API.php
  plugins/Transitions/API.php
  tests/PHPUnit/Framework/TestRequest/Collection.php
  tests/PHPUnit/Integration/Tracker/Visit/ReferrerSpamFilterTest.php
  tests/PHPUnit/Unit/DataTable/Filter/AddSummaryRowTest.php
  tests/PHPUnit/Unit/DataTable/Filter/ExcludeLowPopulationTest.php
  tests/PHPUnit/Unit/DataTable/Filter/LimitTest.php
  tests/PHPUnit/Unit/DataTable/Filter/PatternRecursiveTest.php
  tests/PHPUnit/Unit/DataTable/Filter/PatternTest.php
  tests/PHPUnit/Unit/DataTable/Filter/TruncateTest.php
  tests/PHPUnit/Unit/DataTable/Renderer/CSVTest.php
  tests/PHPUnit/Unit/DataTable/Renderer/ConsoleTest.php
  tests/PHPUnit/Unit/DataTable/Renderer/JSONTest.php
  tests/PHPUnit/Unit/DataTable/Renderer/XMLTest.php
  tests/PHPUnit/Unit/DataTableTest.php
Labels: c: Tests & QA, not-in-changelog, Needs Review

#21679 Fix possible fatal error in VisitTime report
  plugins/VisitTime/functions.php
Labels: not-in-changelog, Needs Review

#21674 Fix segment invalidation for custom dimensions
  plugins/CoreAdminHome/Commands/InvalidateReportData.php
  plugins/CoreAdminHome/tests/Integration/Commands/InvalidateReportDataTest.php
  plugins/SegmentEditor/API.php
Labels: Bug, not-in-changelog, Regression, c: Custom Dimensions, c: Segments

#21692 [Coding Style] Enable rule PSR12.Files.ImportStatement.LeadingSlash
  .git-blame-ignore-revs
  core/Plugin/SettingsProvider.php
  phpcs.xml
  plugins/CoreAdminHome/config/test.php
  plugins/CustomDimensions/Dimension/Active.php
  plugins/CustomDimensions/Dimension/CaseSensitive.php
  plugins/CustomDimensions/Dimension/Dimension.php
  plugins/CustomDimensions/Dimension/Index.php
  plugins/CustomDimensions/Dimension/Name.php
  plugins/Login/tests/Integration/APITest.php
  plugins/Marketplace/tests/Framework/Mock/Consumer.php
  tests/PHPUnit/Framework/TestRequest/ApiTestConfig.php
  tests/PHPUnit/Framework/TestRequest/Collection.php
Labels: c: Tests & QA, not-in-changelog, Needs Review, Technical debt

#21693 [Coding Style] Enable rule PSR12.Functions.ReturnTypeDeclaration.SpaceBeforeColon
  core/DataTable.php
  core/Filesystem.php
  core/Plugin/Dimension/VisitDimension.php
  core/Scheduler/Timetable.php
  phpcs.xml
  plugins/CoreAdminHome/OptOutManager.php
  plugins/Ecommerce/Controller.php
  plugins/Login/Emails/PasswordResetEmail.php
  plugins/Transitions/API.php
  plugins/Transitions/Transitions.php
  plugins/UsersManager/tests/System/ApiTest.php
  tests/PHPUnit/Integration/Segment/SegmentUnavailableTest.php
Labels: c: Tests & QA, not-in-changelog, Needs Review, Technical debt

#21699 [Coding Style] Enable rule PSR2.Methods.FunctionCallSignature.EmptyLine
  core/DataAccess/LogAggregator.php
  phpcs.xml
  plugins/SitesManager/Model.php
Labels: c: Tests & QA, not-in-changelog, Needs Review, Technical debt

#21700 [Coding Style] Enable rule Generic.Formatting.DisallowMultipleStatements.SameLine
  core/ArchiveProcessor/RecordBuilder.php
  core/DataAccess/RawLogDao.php
  core/DataTable/Filter/PivotByDimension.php
  core/LogDeleter.php
  core/Measurable/Type.php
  core/Plugin/Report.php
  phpcs.xml
  plugins/CoreAdminHome/tests/Fixture/DuplicateActions.php
  plugins/CoreAdminHome/tests/Integration/TasksTest.php
  plugins/CoreConsole/Commands/ComputeJsAssetSize.php
  plugins/CoreVisualizations/JqplotDataGenerator/Evolution.php
  plugins/CoreVisualizations/Visualizations/Graph.php
  plugins/CoreVisualizations/Visualizations/HtmlTable.php
  plugins/CustomDimensions/API.php
  plugins/DBStats/API.php
  plugins/Ecommerce/Controller.php
  plugins/Live/tests/Integration/ModelTest.php
  plugins/PagePerformance/API.php
  plugins/PagePerformance/JqplotDataGenerator/StackedBarEvolution.php
  plugins/Referrers/API.php
  plugins/Referrers/Categories/AllReferrersSubcategory.php
  plugins/Referrers/DataTable/Filter/KeywordsFromSearchEngineId.php
  plugins/Referrers/DataTable/Filter/SearchEnginesFromKeywordId.php
  plugins/SegmentEditor/tests/Integration/SegmentEditorTest.php
  plugins/UserCountry/API.php
  tests/PHPUnit/Framework/TestRequest/Response.php
  tests/PHPUnit/Integration/CacheTest.php
  tests/PHPUnit/Integration/CronArchiveTest.php
  tests/PHPUnit/Integration/MailTest.php
  tests/PHPUnit/Integration/ReleaseCheckListTest.php
  tests/PHPUnit/Unit/DataTable/Filter/SortTest.php
  tests/PHPUnit/Unit/DataTableTest.php
  tests/PHPUnit/Unit/Translation/FilesTest.php
Labels: c: Tests & QA, not-in-changelog, Needs Review, Technical debt

#21702 [Coding Style] Enable rule PSR2.ControlStructures.SwitchDeclaration.BodyOnNextLineCASE
  .git-blame-ignore-revs
  core/Cache.php
  phpcs.xml
  plugins/ImageGraph/API.php
Labels: c: Tests & QA, not-in-changelog, Needs Review, Technical debt

#21707 [Coding Style] Enable rule Generic.Functions.FunctionCallArgumentSpacing.TooMuchSpaceAfterComma
  phpcs.xml
  plugins/CustomDimensions/tests/Fixtures/TrackVisitsWithCustomDimensionsFixture.php
  plugins/Diagnostics/Diagnostic/ConfigInformational.php
  plugins/Goals/Commands/CalculateConversionPages.php
  plugins/PrivacyManager/tests/Fixtures/MultipleSitesMultipleVisitsFixture.php
  plugins/UsersManager/Controller.php
  plugins/UsersManager/tests/Integration/ModelTest.php
  tests/PHPUnit/Fixtures/ManyVisitsWithMockLocationProvider.php
  tests/PHPUnit/Fixtures/SomePageGoalVisitsWithConversions.php
  tests/PHPUnit/System/CliMultiTest.php
  tests/PHPUnit/Unit/Tracker/ResponseTest.php
Labels: c: Tests & QA, not-in-changelog, Needs Review, Technical debt

#21708 Hide all sites item in site selector for custom dimension management
  plugins/CustomDimensions/templates/manage.twig
Labels: c: Usability, Needs Review

#21687 Translations update from Hosted Weblate
  lang/de.json
  lang/gu.json
  lang/pt-br.json
  plugins/Actions/lang/gu.json
  plugins/CoreAdminHome/lang/fr.json
  plugins/CoreAdminHome/lang/pt-br.json
  plugins/Diagnostics/lang/pt-br.json
  plugins/Diagnostics/lang/sv.json
  plugins/JsTrackerInstallCheck/lang/pt-br.json
  plugins/Live/lang/fr.json
  plugins/Marketplace/lang/pt-br.json
  plugins/Marketplace/lang/sv.json
  plugins/PrivacyManager/lang/fr.json
  plugins/ProfessionalServices/lang/de.json
  plugins/ProfessionalServices/lang/fr.json
  plugins/ProfessionalServices/lang/pt-br.json
  plugins/ScheduledReports/lang/fr.json
  plugins/SitesManager/lang/pt-br.json
  plugins/UsersManager/lang/pt-br.json
Labels: not-in-changelog, c: i18n

#21710 [Coding Style] Enable rules Generic.Functions.FunctionCallArgumentSpacing.*
  core/CliMulti.php
  core/DataAccess/Model.php
  core/DataAccess/RawLogDao.php
  core/Plugin/ConsoleCommand.php
  core/ReportRenderer/Pdf.php
  core/Tracker/Model.php
  core/Updates/5.0.0-rc5.php
  phpcs.xml
  plugins/API/API.php
  plugins/API/ProcessedReport.php
  plugins/API/tests/Unit/WidgetMetadataTest.php
  plugins/Actions/Columns/VisitTotalInteractions.php
  plugins/CoreAdminHome/OptOutManager.php
  plugins/CoreConsole/Commands/GenerateSystemCheck.php
  plugins/CustomDimensions/Tracker/CustomDimensionsRequestProcessor.php
  plugins/CustomDimensions/tests/Integration/Dao/LogTableTest.php
  plugins/CustomDimensions/tests/Integration/Dimension/IndexTest.php
  plugins/CustomDimensions/tests/Integration/Tracker/CustomDimensionsRequestProcessorTest.php
  plugins/Diagnostics/Diagnostic/ConfigInformational.php
  plugins/Ecommerce/Columns/Revenue.php
  plugins/Ecommerce/VisitorDetails.php
  plugins/GeoIp2/tests/System/ConvertRegionCodesToIsoTest.php
  plugins/Goals/Commands/CalculateConversionPages.php
  plugins/Goals/tests/System/ProcessDependentArchiveTest.php
  plugins/Insights/DataTable/Filter/Insight.php
  plugins/Live/VisitorDetails.php
  plugins/Login/tests/Integration/Security/BruteForceDetectionTest.php
  plugins/Marketplace/tests/Integration/EnvironmentTest.php
  plugins/PagePerformance/Visualizations/PerformanceColumns.php
  plugins/TestRunner/Commands/TestsRunUI.php
  plugins/Transitions/tests/Integration/TransitionsMaxAllowedPeriodTest.php
  plugins/UsersManager/tests/Integration/APITest.php
  plugins/UsersManager/tests/Integration/Validators/AllowedEmailDomainTest.php
  plugins/VisitsSummary/Reports/Get.php
  tests/PHPUnit/Fixtures/DisablePluginArchive.php
  tests/PHPUnit/Fixtures/ManyVisitsWithGeoIP.php
  tests/PHPUnit/Fixtures/SomePageGoalVisitsWithConversions.php
  tests/PHPUnit/Integration/ArchiveProcessor/LoaderLockTest.php
  tests/PHPUnit/Integration/ArchiveProcessor/LoaderTest.php
  tests/PHPUnit/Integration/CliMulti/ProcessTest.php
  tests/PHPUnit/Integration/DataAccess/LogAggregatorTest.php
  tests/PHPUnit/Integration/NumberFormatterTest.php
  tests/PHPUnit/Integration/ProfessionalSupport/AdvertisingTest.php
  tests/PHPUnit/Integration/ReleaseCheckListTest.php
  tests/PHPUnit/Integration/Settings/Storage/Backend/ConfigTest.php
  tests/PHPUnit/Integration/Settings/Storage/Backend/MeasurableSettingsTableTest.php
  tests/PHPUnit/Integration/Settings/Storage/Backend/PluginSettingsTableTest.php
  tests/PHPUnit/Integration/Tracker/FingerprintSaltTest.php
  tests/PHPUnit/Integration/Tracker/RequestSetTest.php
  tests/PHPUnit/Integration/Tracker/RequestTest.php
  tests/PHPUnit/Unit/Period/RangeTest.php
Labels: c: Tests & QA, not-in-changelog, Needs Review, Technical debt

#21714 On PHPCS failure in GH action, also show the report before adding code annotations
  .github/workflows/phpcs.yml
Labels: c: Tests & QA, not-in-changelog, Needs Review, Technical debt

#21716 [Coding Style] Enable rule Squiz.Functions.MultiLineFunctionDeclaration.ContentAfterBrace
  core/Segment/SegmentExpression.php
  phpcs.xml
  tests/PHPUnit/Unit/DataTableTest.php
Labels: c: Tests & QA, not-in-changelog, Needs Review, Technical debt

#21717 Enable rule Squiz.Functions.MultiLineFunctionDeclaration.SpaceBeforeBrace
  core/ArchiveProcessor/Rules.php
  core/Tracker/Request.php
  phpcs.xml
  plugins/CustomDimensions/tests/System/ApiTest.php
  plugins/LanguagesManager/Commands/PluginsWithTranslations.php
  plugins/UsersManager/Controller.php
Labels: c: Tests & QA, not-in-changelog, Needs Review, Technical debt

#21720 [Coding Style] Enable rule PSR2.Classes.ClassDeclaration.SpaceAfterKeyword
  core/ViewDataTable/Config.php
  phpcs.xml
Labels: c: Tests & QA, not-in-changelog, Needs Review, Technical debt

#21719 Improve escaping of values in CSV exports
  core/DataTable/Renderer/Csv.php
  tests/PHPUnit/Unit/DataTable/Renderer/CSVTest.php
Labels: Needs Review

#21669 Use regular expressions to parse segment string into segment logical tree
  core/Segment/SegmentExpression.php
Labels: not-in-changelog, Needs Review

#21728 [Coding Style] Enable rule PSR12.Keywords.ShortFormTypeKeywords.LongFound
  core/Http.php
  phpcs.xml
Labels: c: Tests & QA, not-in-changelog, Needs Review, Technical debt

#21731 [Coding Style] Enable rule PSR2.ControlStructures.SwitchDeclaration.WrongOpenercase
  core/Columns/DimensionMetricFactory.php
  phpcs.xml
  plugins/CoreHome/Columns/VisitGoalBuyer.php
Labels: c: Tests & QA, not-in-changelog, Needs Review, Technical debt

#21730 [Coding Style] Enable rule PSR12.ControlStructures.BooleanOperatorPlacement.FoundMixed
  core/CronArchive.php
  core/Nonce.php
  core/Period/Range.php
  core/Plugin/Visualization.php
  core/ReportRenderer/Pdf.php
  core/Updates/4.0.0-b1.php
  phpcs.xml
Labels: c: Tests & QA, not-in-changelog, Needs Review, Technical debt

#21713 Add archiving diagnostic commands
  core/DataAccess/ArchiveTableDao.php
  core/Plugin/ConsoleCommand.php
  core/Plugin/ConsoleCommand/ConsoleCommandBufferedOutput.php
  core/Plugin/ConsoleCommand/ConsoleCommandConsoleOutput.php
  plugins/Diagnostics/Commands/ArchivingConfig.php
  plugins/Diagnostics/Commands/ArchivingInstanceStatistics.php
  plugins/Diagnostics/Commands/ArchivingMetrics.php
  plugins/Diagnostics/Commands/ArchivingQueue.php
  plugins/Diagnostics/Commands/ArchivingStatus.php
  plugins/Diagnostics/tests/Integration/Commands/ArchivingConfigTest.php
  plugins/Diagnostics/tests/Integration/Commands/ArchivingInstanceStatisticsTest.php
  plugins/Diagnostics/tests/Integration/Commands/ArchivingMetricsTest.php
  plugins/Diagnostics/tests/Integration/Commands/ArchivingQueueTest.php
  plugins/Diagnostics/tests/Integration/Commands/ArchivingStatusTest.php
Labels: Enhancement, Needs Review, Easier debugging
