Repository matomo-org/matomo, pull requests merged in 2023-03, with the labels that each got.

#20404 OptOut: Remove extra twig markings
  plugins/CoreAdminHome/templates/optOut.twig
Labels: Needs Review, Regression

#20416 Add referrerpolicy="no-referrer-when-downgrade" to noscript tracking code
  plugins/Morpheus/templates/javascriptCode.twig
Labels: Bug, not-in-changelog

#20414 PHP 8.2 deprecation warning fixes
  core/Tracker/TableLogAction/Cache.php
  plugins/CoreVisualizations/Visualizations/HtmlTable/Config.php
  plugins/Live/VisitorProfile.php
Labels: Bug, not-in-changelog, Needs Review

#20427 Fix PHP 8.2 deprecation
  plugins/Events/Actions/ActionEvent.php
Labels: not-in-changelog, Needs Review

#20435 Ensure empty widgets are loaded correctly
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/WidgetLoader/WidgetLoader.vue
Labels: not-in-changelog, Needs Review

#20372 Translations update from Hosted Weblate
  lang/bs.json
  lang/eu.json
  lang/id.json
  lang/ja.json
  lang/pt-br.json
  lang/sv.json
  lang/tr.json
  lang/zh-tw.json
  plugins/CoreHome/lang/zh-cn.json
  plugins/CoreHome/lang/zh-tw.json
  plugins/CorePluginsAdmin/lang/zh-tw.json
  plugins/CoreUpdater/lang/pl.json
  plugins/CoreUpdater/lang/pt-br.json
  plugins/CoreUpdater/lang/zh-tw.json
  plugins/DevicesDetection/lang/pt-br.json
  plugins/Events/lang/pl.json
  plugins/Feedback/lang/zh-tw.json
  plugins/GeoIp2/lang/zh-tw.json
  plugins/Goals/lang/pt-br.json
  plugins/Installation/lang/zh-tw.json
  plugins/PrivacyManager/lang/pt-br.json
  plugins/ProfessionalServices/lang/zh-tw.json
  plugins/Referrers/lang/sq.json
  plugins/ScheduledReports/lang/zh-tw.json
  plugins/SitesManager/lang/el.json
  plugins/SitesManager/lang/ja.json
  plugins/Tour/lang/ja.json
  plugins/VisitsSummary/lang/zh-tw.json
  plugins/WebsiteMeasurable/lang/zh-tw.json
Labels: c: i18n

#20437 Fixed PHP 8.2 deprecation error
  plugins/CustomDimensions/Dimension/Name.php
  plugins/CustomDimensions/tests/System/ApiTest.php
Labels: Needs Review

#20336 Fix to allow campaign switching during a session
  CHANGELOG.md
  plugins/Referrers/Columns/Base.php
  plugins/Referrers/tests/Integration/ReferrerAttributionTest.php
  plugins/Referrers/tests/System/ApiTest.php
  plugins/Referrers/tests/System/expected/test_phpSerialized8__Referrers.getReferrerType_year.original
  plugins/Referrers/tests/System/expected/test_phpSerialized__Referrers.getReferrerType_year.original
  tests/PHPUnit/Fixtures/SomeVisitsCustomVariablesCampaignsNotHeuristics.php
  tests/PHPUnit/Fixtures/TwoSitesManyVisitsOverSeveralDaysWithSearchEngineReferrers.php
  tests/PHPUnit/Fixtures/TwoVisitsWithCustomVariables.php
  tests/PHPUnit/System/expected/test_PiwikTracker_trackForceUsingVisitId_insteadOfHeuristics_alsoTestsCampaignTracking__Referrers.getCampaigns_day.xml
  tests/PHPUnit/System/expected/test_PiwikTracker_trackForceUsingVisitId_insteadOfHeuristics_alsoTestsCampaignTracking__Referrers.getWebsites_day.xml
  tests/PHPUnit/System/expected/test_PiwikTracker_trackForceUsingVisitId_insteadOfHeuristics_alsoTestsCampaignTracking__VisitsSummary.get_day.xml
  tests/PHPUnit/System/expected/test_periodIsRange_dateIsLastN_MetadataAndNormalAPI__Live.getFirstVisitForVisitorId.xml
  tests/PHPUnit/System/expected/test_periodIsRange_dateIsLastN_MetadataAndNormalAPI__Live.getLastVisitsDetails_range.xml
  tests/PHPUnit/System/expected/test_periodIsRange_dateIsLastN_MetadataAndNormalAPI__Live.getVisitorProfile.xml
  tests/PHPUnit/System/expected/test_periodIsRange_dateIsLastN_MetadataAndNormalAPI__Referrers.getCampaigns_range.xml
  tests/PHPUnit/System/expected/test_periodIsRange_dateIsLastN_MetadataAndNormalAPI_pagesegment__Live.getFirstVisitForVisitorId.xml
  tests/PHPUnit/System/expected/test_periodIsRange_dateIsLastN_MetadataAndNormalAPI_pagesegment__Live.getLastVisitsDetails_range.xml
  tests/PHPUnit/System/expected/test_periodIsRange_dateIsLastN_MetadataAndNormalAPI_pagesegment__Live.getVisitorProfile.xml
  tests/PHPUnit/System/expected/test_periodIsRange_dateIsLastN_MetadataAndNormalAPI_pagesegment__Referrers.getCampaigns_range.xml
Labels: Bug, Needs Review

#20455 allow xmlFieldsToRemove API test config to remove multi-line xml nodes
  tests/PHPUnit/Framework/TestRequest/Response.php
Labels: Needs Review

#20445 Addressing PHP deprecation error in test class
  core/Mail.php
  tests/PHPUnit/Framework/Mock/Tracker/Db.php
  tests/PHPUnit/Unit/MailTest.php
Labels: c: Tests & QA, not-in-changelog, Needs Review

#20465 Do not throw no archive exception for API requests triggered by the UI
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/AjaxHelper/AjaxHelper.ts
  plugins/CoreHome/vue/src/WidgetLoader/WidgetLoader.vue
  plugins/SegmentEditor/SegmentEditor.php
Labels: Needs Review

#20456 Ensure archiving for segments uses correct date ranges
  core/ArchiveProcessor.php
  core/CronArchive.php
  plugins/CoreAdminHome/API.php
  plugins/CoreAdminHome/Controller.php
  plugins/SegmentEditor/SegmentEditor.php
  plugins/Transitions/API.php
  tests/PHPUnit/Fixtures/VisitsInDifferentTimezones.php
  tests/PHPUnit/Framework/TestCase/SystemTestCase.php
  tests/PHPUnit/Framework/TestRequest/Collection.php
  tests/PHPUnit/Integration/Archive/ChunksTest.php
  tests/PHPUnit/Integration/ArchiveProcessingTest.php
  tests/PHPUnit/System/TimezonesTest.php
  tests/PHPUnit/System/expected/test_TimezonesTest__Live.getLastVisitsDetails_range.xml
  tests/PHPUnit/System/expected/test_TimezonesTest_range_ast__Live.getLastVisitsDetails_range.xml
  tests/PHPUnit/System/expected/test_TimezonesTest_range_nomatch_ast__Live.getLastVisitsDetails_range.xml
  tests/PHPUnit/System/expected/test_TimezonesTest_range_nomatch_utc__Live.getLastVisitsDetails_range.xml
  tests/PHPUnit/System/expected/test_TimezonesTest_range_utc__Live.getLastVisitsDetails_range.xml
  tests/PHPUnit/System/expected/test_TimezonesTest_today__VisitsSummary.get_day.xml
  tests/PHPUnit/System/expected/test_TimezonesTest_today_ast__Live.getLastVisitsDetails_day.xml
  tests/PHPUnit/System/expected/test_TimezonesTest_today_ast__Transitions.getTransitionsForAction_day.xml
  tests/PHPUnit/System/expected/test_TimezonesTest_today_ast__VisitsSummary.get_day.xml
  tests/PHPUnit/System/expected/test_TimezonesTest_today_nomatch__VisitsSummary.get_day.xml
  tests/PHPUnit/System/expected/test_TimezonesTest_today_nomatch_ast__Transitions.getTransitionsForAction_day.xml
  tests/PHPUnit/System/expected/test_TimezonesTest_today_nomatch_ast__VisitsSummary.get_day.xml
  tests/PHPUnit/System/expected/test_TimezonesTest_today_nomatch_utc__Transitions.getTransitionsForAction_day.xml
  tests/PHPUnit/System/expected/test_TimezonesTest_today_nomatch_utc__VisitsSummary.get_day.xml
  tests/PHPUnit/System/expected/test_TimezonesTest_today_utc__Live.getLastVisitsDetails_day.xml
  tests/PHPUnit/System/expected/test_TimezonesTest_today_utc__Transitions.getTransitionsForAction_day.xml
  tests/PHPUnit/System/expected/test_TimezonesTest_today_utc__VisitsSummary.get_day.xml
  tests/PHPUnit/System/expected/test_TimezonesTest_yesterday__VisitsSummary.get_day.xml
  tests/PHPUnit/System/expected/test_TimezonesTest_yesterday_ast__Live.getLastVisitsDetails_day.xml
  tests/PHPUnit/System/expected/test_TimezonesTest_yesterday_ast__VisitsSummary.get_day.xml
  tests/PHPUnit/System/expected/test_TimezonesTest_yesterday_nomatch__VisitsSummary.get_day.xml
  tests/PHPUnit/System/expected/test_TimezonesTest_yesterday_nomatch_ast__VisitsSummary.get_day.xml
  tests/PHPUnit/System/expected/test_TimezonesTest_yesterday_nomatch_utc__VisitsSummary.get_day.xml
  tests/PHPUnit/System/expected/test_TimezonesTest_yesterday_utc__Live.getLastVisitsDetails_day.xml
  tests/PHPUnit/System/expected/test_TimezonesTest_yesterday_utc__VisitsSummary.get_day.xml
Labels: Needs Review

#20471 add semantic types for date/datetime
  core/Plugin/Metric.php
Labels: Needs Review

#20392 use local build script for tests
  .github/scripts/build-package.sh
  .github/workflows/release.yml
  plugins/CoreUpdater/ReleaseChannel/LatestStable.php
  tests/PHPUnit/Fixtures/LatestStableInstall.php
Labels: c: Tests & QA, not-in-changelog, Stale

#20476 Add a new column to the log conversion table in preparation for 5.x
  core/Db/Schema/Mysql.php
Labels: Task, not-in-changelog, Needs Review

#20474 Implement custom console formatter to allow logging request id
  plugins/Monolog/Formatter/ConsoleFormatter.php
  plugins/Monolog/config/cli.php
Labels: not-in-changelog, Needs Review, Regression

#20450 Translations update from Hosted Weblate
  plugins/CoreAdminHome/lang/zh-cn.json
  plugins/CoreHome/lang/nl.json
Labels: c: i18n

#20479 Allow no referrer with expected referrer
  core/Nonce.php
  tests/PHPUnit/Integration/NonceTest.php
  tests/PHPUnit/System/TimezonesTest.php
  tests/PHPUnit/System/expected/test_TimezonesTest_today_ast__Transitions.getTransitionsForAction_day.xml
  tests/PHPUnit/System/expected/test_TimezonesTest_today_utc__Transitions.getTransitionsForAction_day.xml
Labels: not-in-changelog

#20096 Attach browser features to tracking requests when they are send
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  tests/javascript/index.php
  tests/javascript/matomo.php
Labels: Needs Review

#20351 Add option to only allow tokens to be POSTed
  CHANGELOG.md
  config/global.ini.php
  core/API/Request.php
  core/Db/Schema/Mysql.php
  core/Updates/5.0.0-b1.php
  plugins/Login/Login.php
  plugins/PrivacyManager/vue/dist/umd.metadata.json
  plugins/UsersManager/Controller.php
  plugins/UsersManager/Model.php
  plugins/UsersManager/UsersManager.php
  plugins/UsersManager/lang/en.json
  plugins/UsersManager/templates/addNewToken.twig
  plugins/UsersManager/tests/Integration/ModelTest.php
  plugins/UsersManager/tests/Integration/TokenPostOnlyTest.php
  plugins/UsersManager/tests/UI/UserSettings_spec.js
  plugins/UsersManager/tests/UI/expected-screenshots/UserSettings_add_token.png
  plugins/UsersManager/tests/UI/expected-screenshots/UserSettings_load_security.png
  plugins/UsersManager/tests/UI/expected-screenshots/UserSettings_load_security_new_token.png
  plugins/UsersManager/vue/dist/UsersManager.umd.js
  plugins/UsersManager/vue/dist/UsersManager.umd.min.js
  plugins/UsersManager/vue/src/AddNewToken/AddNewToken.vue
  plugins/UsersManager/vue/src/UserSecurity/UserSecurity.vue
Labels: Enhancement, c: Security, not-in-changelog

#20488 Add missing annotation delete translation
  plugins/Annotations/templates/_annotation.twig
Labels: Bug, not-in-changelog, Needs Review

#20491 Enable segmented log feature for more referrer reports
  core/DataTable/Filter/AddSegmentByLabel.php
  plugins/PrivacyManager/tests/System/expected/test_userIdAnonymized__Referrers.getAll_year.xml
  plugins/Referrers/API.php
  tests/PHPUnit/System/expected/test_DataComparisonTest_invertCompare__Referrers.getAll_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_periods__Referrers.getAll_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_rangePeriodAgainstSingle__Referrers.getAll_range.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_segmentsAndPeriods__Referrers.getAll_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_segments__Referrers.getAll_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Referrers.getAll_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Referrers.getReferrerType_month.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits__Referrers.getAll_day.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits__Referrers.getReferrerType_day.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits_withCookieSupport__Referrers.getAll_day.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits_withCookieSupport__Referrers.getReferrerType_day.xml
  tests/PHPUnit/System/expected/test_oneVisitor_oneWebsite_severalDays_DateRange_Flattened__Referrers.getSocials_range.xml
  tests/PHPUnit/System/expected/test_oneVisitor_oneWebsite_severalDays_DateRange_IndexedByDate__Referrers.getSocials_day.xml
  tests/PHPUnit/System/expected/test_oneVisitor_oneWebsite_severalDays_DateRange__Referrers.getSocials_range.xml
  tests/PHPUnit/System/expected/test_reportLimiting__Referrers.getAll_day.xml
  tests/PHPUnit/System/expected/test_reportLimiting__Referrers.getAll_month.xml
  tests/PHPUnit/System/expected/test_reportLimiting__Referrers.getReferrerType_day.xml
  tests/PHPUnit/System/expected/test_reportLimiting__Referrers.getReferrerType_month.xml
  tests/PHPUnit/System/expected/test_reportLimiting_flattened__Referrers.getAll_day.xml
  tests/PHPUnit/System/expected/test_reportLimiting_rankingQuery__Referrers.getAll_day.xml
  tests/PHPUnit/System/expected/test_reportLimiting_rankingQuery__Referrers.getReferrerType_day.xml
Labels: Enhancement, not-in-changelog

#20332 when aggregating non-day periods, only store one datatable and blob row in memory at a time
  core/Archive.php
  core/Archive/DataCollection.php
  core/ArchiveProcessor.php
  core/DataAccess/ArchiveSelector.php
  core/Segment.php
  tests/PHPUnit/Integration/DataAccess/ArchiveSelectorTest.php
  tests/PHPUnit/System/expected/test_DataComparisonTest_flat__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_invertCompare__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_labelFilter__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_multipleSites_multipleCompare__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_periods__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_rangePeriodAgainstSingle__Actions.getPageUrls_range.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_segmentsAndPeriods__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_segments__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_singleAgainstRange__Actions.getPageUrls_day.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_subtableActions__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_reportLimiting__Resolution.getConfiguration_month.xml
Labels: Needs Review

#20499 fix: default semanticType to null
  plugins/CoreHome/Columns/Metrics/CallableProcessedMetric.php
Labels: Regression

#20502 Fix mysql and php versions are swapped in summary widget
  plugins/CoreHome/Widgets/GetSystemSummary.php
Labels: not-in-changelog

#20495 Ensure to unsanitize goal pattern correctly
  plugins/Goals/API.php
Labels: Needs Review, Regression

#20413 Support ranges with two dates for invalidateArchivedReports API call
  plugins/CoreAdminHome/API.php
  tests/PHPUnit/System/ArchiveInvalidationTest.php
Labels: Bug, not-in-changelog, Needs Review, Stale, 5.0.0

#20379 join log_action in segment sql queries instead of using idaction IN (...)
  CHANGELOG.md
  config/global.ini.php
  core/Columns/Dimension.php
  core/Columns/DimensionSegmentFactory.php
  core/Plugin/Segment.php
  core/Segment.php
  core/Segment/SegmentExpression.php
  core/Tracker/TableLogAction.php
  core/Tracker/TableLogAction/Cache.php
  lang/en.json
  plugins/API/API.php
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_visitConvertedGoalName__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_visitConvertedGoalName__VisitsSummary.get_range.xml
  plugins/Actions/Columns/ActionUrl.php
  plugins/Actions/Columns/ClickedUrl.php
  plugins/Actions/Columns/DownloadUrl.php
  plugins/Actions/Columns/EntryPageTitle.php
  plugins/Actions/Columns/EntryPageUrl.php
  plugins/Actions/Columns/ExitPageTitle.php
  plugins/Actions/Columns/ExitPageUrl.php
  plugins/Actions/Columns/PageTitle.php
  plugins/Actions/Columns/PageUrl.php
  plugins/Actions/Columns/SearchKeyword.php
  plugins/Actions/tests/System/ApiTest.php
  plugins/Contents/Columns/ContentInteraction.php
  plugins/Contents/Columns/ContentName.php
  plugins/Contents/Columns/ContentPiece.php
  plugins/Contents/Columns/ContentTarget.php
  plugins/CustomDimensions/tests/System/expected/test___API.getSegmentsMetadata.xml
  plugins/Ecommerce/Columns/ProductCategory.php
  plugins/Ecommerce/Columns/ProductName.php
  plugins/Ecommerce/Columns/ProductSku.php
  plugins/Ecommerce/Columns/ProductViewCategory.php
  plugins/Ecommerce/Columns/ProductViewName.php
  plugins/Ecommerce/Columns/ProductViewSku.php
  plugins/Events/Columns/EventAction.php
  plugins/Events/Columns/EventCategory.php
  plugins/Events/Columns/EventName.php
  plugins/Events/Columns/EventUrl.php
  plugins/Goals/Columns/GoalName.php
  plugins/Goals/Columns/IdGoal.php
  tests/PHPUnit/Integration/SegmentTest.php
  tests/PHPUnit/System/ComplicatedSegmentTest.php
  tests/PHPUnit/System/expected/test_ComplicatedSegment_SegmentWithManyActions__Live.getLastVisitsDetails_day.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getSegmentsMetadata.xml
  tests/PHPUnit/Unit/Archive/DataCollectionTest.php
  tests/PHPUnit/Unit/Segment/SegmentExpressionTest.php
Labels: 5.0.0
