Repository matomo-org/matomo, pull requests merged in 2023-05, with the labels that each got.

#20593 Translations update from Hosted Weblate
  lang/es.json
  plugins/API/lang/ta.json
  plugins/Annotations/lang/et.json
  plugins/Annotations/lang/zh-tw.json
  plugins/CoreAdminHome/lang/ca.json
  plugins/CoreAdminHome/lang/el.json
  plugins/CoreAdminHome/lang/nl.json
  plugins/CoreAdminHome/lang/tr.json
  plugins/CoreAdminHome/lang/uk.json
  plugins/CoreAdminHome/lang/zh-tw.json
  plugins/CoreHome/lang/ar.json
  plugins/CoreHome/lang/ru.json
  plugins/Diagnostics/lang/es.json
  plugins/GeoIp2/lang/es.json
  plugins/Live/lang/es.json
  plugins/Login/lang/es.json
  plugins/PagePerformance/lang/es.json
  plugins/PrivacyManager/lang/es.json
  plugins/PrivacyManager/lang/nl.json
  plugins/PrivacyManager/lang/zh-tw.json
  plugins/SitesManager/lang/ca.json
  plugins/SitesManager/lang/el.json
  plugins/SitesManager/lang/es.json
  plugins/SitesManager/lang/nl.json
  plugins/SitesManager/lang/tr.json
  plugins/SitesManager/lang/zh-tw.json
  plugins/Tour/lang/es.json
  plugins/VisitTime/lang/es.json
Labels: c: i18n

#20621 If custom logo feature is disabled, assume it's not enabled even if one is already uploaded
  plugins/CoreAdminHome/CustomLogo.php
Labels: Needs Review, Stale

#20648 Fix use of CoreHome.ShowHelpLink component
  plugins/CoreHome/templates/_menu.twig
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/ShowHelpLink/ShowHelpLink.adapter.ts
  plugins/CoreHome/vue/src/index.ts
Labels: Needs Review, Regression

#20638 Fix array access issue for a single goal ID only
  plugins/Goals/DataTable/Filter/CalculateConversionPageRate.php
Labels: not-in-changelog, Needs Review

#20628 Add return type to satisfy interface implementation and fix deprecation warning
  plugins/Diagnostics/Diagnostic/RequiredPhpSetting.php
Labels: not-in-changelog, Needs Review

#20653 Check request method is set before using it
  plugins/PrivacyManager/PrivacyManager.php
Labels: Needs Review

#20660 Fixed width of no-data screen tabs and FAQ link update for WordPress image tracking.
  plugins/SitesManager/stylesheets/SitesManager.less
  plugins/SitesManager/templates/_siteWithoutDataTabs.twig
  plugins/SitesManager/templates/_wordpressTabInstructions.twig
  tests/UI/expected-screenshots/EmptySite_Cloudflare_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_ConsentManager_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_GA3_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_GA4_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_GTM_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_Wordpress_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_emptySiteDashboard.png
  tests/UI/expected-screenshots/OneClickUpdate_login.png
Labels: Needs Review, BHAG-Tracking-OKR-Q2

#20661 Ensure IP is passed as string
  core/Url.php
Labels: not-in-changelog, Needs Review

#20578 Avoid API request for API.getPagesComparisonsDisabledFor on Login pages
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/Comparisons/Comparisons.store.ts
Labels: Needs Review, Stale

#20663 if no subwidgets are defined for a category, do not display the category
  plugins/Dashboard/javascripts/widgetMenu.js
Labels: Needs Review

#20650 Translations update from Hosted Weblate
  plugins/CoreAdminHome/lang/tr.json
  plugins/CoreAdminHome/lang/uk.json
  plugins/CoreHome/lang/cs.json
  plugins/Live/lang/es.json
  plugins/SitesManager/lang/el.json
  plugins/SitesManager/lang/tr.json
Labels: c: i18n

#20643 Allow reports to override the min/max label width values
  plugins/CoreHome/javascripts/dataTable.js
  plugins/CoreVisualizations/Visualizations/HtmlTable/Config.php
Labels: Needs Review

#20665 Fixed width of no-data screen tabs and FAQ link update for WordPress image tracking
  plugins/SitesManager/stylesheets/SitesManager.less
  plugins/SitesManager/templates/_siteWithoutDataTabs.twig
  tests/UI/expected-screenshots/EmptySite_Cloudflare_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_ConsentManager_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_GA3_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_GA4_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_GTM_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_Wordpress_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_emptySiteDashboard.png
  tests/UI/expected-screenshots/OneClickUpdate_login.png
Labels: Needs Review, BHAG-Tracking-OKR-Q2

#20600 Add immutable visitor property functions to the VisitProperties class
  core/Tracker/Visit/VisitProperties.php
  core/Tracker/Visitor.php
  core/Tracker/VisitorRecognizer.php
  plugins/Referrers/Columns/Base.php
  plugins/Referrers/tests/Integration/Columns/ReferrerKeywordTest.php
  plugins/Referrers/tests/Integration/Columns/ReferrerNameTest.php
  plugins/Referrers/tests/Integration/Columns/ReferrerTypeTest.php
  plugins/Referrers/tests/Integration/ReferrerAttributionTest.php
Labels: Bug, not-in-changelog, Needs Review

#20674 Ensure IP is passed as string (#20661)
  core/Url.php
Labels: not-in-changelog

#20682 Apply #20643 to 4.x-dev - Allow reports to override the min/max label width values
  plugins/CoreHome/javascripts/dataTable.js
  plugins/CoreVisualizations/Visualizations/HtmlTable/Config.php
Labels: Needs Review

#20680 Apply #20638 to 4.x-dev - Fix array access issue for a single goal ID only
  plugins/Goals/DataTable/Filter/CalculateConversionPageRate.php
Labels: Needs Review

#20681 Apply #20663 to 4.x-dev - if no subwidgets are defined for a category, do not display the category
  plugins/Dashboard/javascripts/widgetMenu.js
Labels: Needs Review

#20683 Apply #19952 to 4.x-dev - add Live.initializeVisitorActions event to allow plugins to collapse actions in visitor log if they need to
  plugins/Live/javascripts/visitorActions.js
Labels: Needs Review

#20678 Add merge icon to icon font.
  LEGALNOTICE
  plugins/Morpheus/Controller.php
  plugins/Morpheus/fonts/matomo.svg
  plugins/Morpheus/fonts/matomo.ttf
  plugins/Morpheus/fonts/matomo.woff
  plugins/Morpheus/fonts/matomo.woff2
  plugins/Morpheus/fonts/selection.json
  plugins/Morpheus/stylesheets/base/icons.css
  tests/UI/expected-screenshots/Theme_demo.png
Labels: Needs Review

#20666 Added contact support option on No-data screen
  plugins/Morpheus/stylesheets/base/colors.less
  plugins/SitesManager/Controller.php
  plugins/SitesManager/SitesManager.php
  plugins/SitesManager/config/config.php
  plugins/SitesManager/lang/en.json
  plugins/SitesManager/stylesheets/SitesManager.less
  plugins/SitesManager/templates/_siteWithoutDataTabs.twig
  plugins/SitesManager/templates/siteWithoutData.twig
  plugins/SitesManager/vue/dist/SitesManager.umd.js
  plugins/SitesManager/vue/dist/SitesManager.umd.min.js
  plugins/SitesManager/vue/src/SiteWithoutData/SiteWithoutData.vue
  tests/UI/expected-screenshots/EmptySite_Cloudflare_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_ConsentManager_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_GA3_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_GA4_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_GTM_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_Wordpress_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_emptySiteDashboard.png
  tests/UI/expected-screenshots/OneClickUpdate_login.png
Labels: Needs Review, BHAG-Tracking-OKR-Q2

#20667 Improves "Ask for consent" page
  core/SiteContentDetector.php
  plugins/PrivacyManager/Controller.php
  plugins/PrivacyManager/PrivacyManager.php
  plugins/PrivacyManager/lang/en.json
  plugins/PrivacyManager/templates/askingForConsent.twig
  plugins/PrivacyManager/tests/UI/PrivacyManager_ConsentManager_spec.js
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_ConsentManager_consent_default.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_consent_default.png
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.js
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.min.js
  plugins/PrivacyManager/vue/dist/umd.metadata.json
  plugins/PrivacyManager/vue/src/AskingForConsent/AskingForConsent.vue
Labels: not-in-changelog, Needs Review

#20693 Use matomo brand in less color names
  CHANGELOG.md
  plugins/API/stylesheets/glossary.less
  plugins/CoreHome/stylesheets/layout.less
  plugins/CoreHome/vue/src/Alert/alert.less
  plugins/CoreHome/vue/src/DropdownMenu/DropdownMenu.less
  plugins/CoreHome/vue/src/Notification/Notification.less
  plugins/CoreHome/vue/src/ReportExport/ReportExport.less
  plugins/Dashboard/stylesheets/dashboard.less
  plugins/Installation/stylesheets/systemCheckPage.less
  plugins/Live/stylesheets/visitor_profile.less
  plugins/Marketplace/stylesheets/marketplace.less
  plugins/Morpheus/stylesheets/base/colors.less
  plugins/PrivacyManager/vue/src/ManageGdpr/ManageGdpr.less
  plugins/ScheduledReports/stylesheets/scheduledreports.less
  plugins/SitesManager/stylesheets/SitesManager.less
  plugins/Transitions/vue/src/TransitionExporter/TransitionExporterPopover.less
  plugins/UserCountry/stylesheets/userCountry.less
Labels: Needs Review

#20009 Allow reports to specify a column/metadata other than "label" that uniquely identifies a row
  config/global.php
  core/API/DataTableManipulator.php
  core/API/DataTableManipulator/LabelFilter.php
  core/API/DataTablePostProcessor.php
  core/API/DocumentationGenerator.php
  core/API/Proxy.php
  core/DataTable.php
  core/Plugin/Report.php
  core/Plugin/Visualization.php
  plugins/API/RowEvolution.php
  plugins/CoreHome/DataTableRowAction/RowEvolution.php
  plugins/CoreHome/javascripts/dataTable_rowactions.js
  plugins/CoreVisualizations/Visualizations/HtmlTable/Config.php
  plugins/CoreVisualizations/templates/_dataTableViz_htmlTable.twig
  plugins/CoreVisualizations/templates/_dataTableViz_htmlTable_comparisons.twig
  tests/PHPUnit/System/LabelFilterTest.php
  tests/PHPUnit/System/expected/test_LabelFilter_urlsWithCustomRowId__Actions.getPageUrls_day.xml
  tests/UI/specs/UIIntegration_spec.js
Labels: Needs Review, 5.0.0

#20555 fix two issues with handling of processing dependent archives
  core/ArchiveProcessor.php
  core/ArchiveProcessor/Loader.php
  core/ArchiveProcessor/Parameters.php
  core/DataAccess/LogAggregator.php
  plugins/Goals/Archiver.php
  tests/PHPUnit/Integration/ArchiveProcessor/LoaderTest.php
  tests/PHPUnit/Integration/ArchiveTest.php
Labels: Needs Review

#20700 UI changes for contact support on no data page
  plugins/Morpheus/stylesheets/base/colors.less
  plugins/SitesManager/Controller.php
  plugins/SitesManager/SitesManager.php
  plugins/SitesManager/config/config.php
  plugins/SitesManager/lang/en.json
  plugins/SitesManager/stylesheets/SitesManager.less
  plugins/SitesManager/templates/_siteWithoutDataTabs.twig
  plugins/SitesManager/templates/siteWithoutData.twig
  tests/UI/expected-screenshots/EmptySite_Cloudflare_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_ConsentManager_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_GA3_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_GA4_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_GTM_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_Wordpress_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_emptySiteDashboard_ignored.png
  tests/UI/expected-screenshots/OneClickUpdate_login.png
  tests/UI/specs/EmptySite_spec.js
Labels: Needs Review, BHAG-Tracking-OKR-Q2

#20675 Translations update from Hosted Weblate
  lang/lv.json
  plugins/CoreAdminHome/lang/ca.json
  plugins/Ecommerce/lang/uk.json
  plugins/PrivacyManager/lang/bg.json
  plugins/PrivacyManager/lang/ca.json
  plugins/PrivacyManager/lang/da.json
  plugins/PrivacyManager/lang/de.json
  plugins/PrivacyManager/lang/el.json
  plugins/PrivacyManager/lang/fr.json
  plugins/PrivacyManager/lang/id.json
  plugins/PrivacyManager/lang/it.json
  plugins/PrivacyManager/lang/ja.json
  plugins/PrivacyManager/lang/nb.json
  plugins/PrivacyManager/lang/nl.json
  plugins/PrivacyManager/lang/pl.json
  plugins/PrivacyManager/lang/pt.json
  plugins/PrivacyManager/lang/sq.json
  plugins/PrivacyManager/lang/sv.json
  plugins/PrivacyManager/lang/tr.json
  plugins/PrivacyManager/lang/zh-cn.json
  plugins/PrivacyManager/lang/zh-tw.json
  plugins/SitesManager/lang/bg.json
  plugins/SitesManager/lang/ca.json
  plugins/SitesManager/lang/cs.json
  plugins/SitesManager/lang/de.json
  plugins/SitesManager/lang/el.json
  plugins/SitesManager/lang/es-ar.json
  plugins/SitesManager/lang/es.json
  plugins/SitesManager/lang/fi.json
  plugins/SitesManager/lang/fr.json
  plugins/SitesManager/lang/id.json
  plugins/SitesManager/lang/it.json
  plugins/SitesManager/lang/ja.json
  plugins/SitesManager/lang/nb.json
  plugins/SitesManager/lang/nl.json
  plugins/SitesManager/lang/pl.json
  plugins/SitesManager/lang/pt-br.json
  plugins/SitesManager/lang/pt.json
  plugins/SitesManager/lang/ru.json
  plugins/SitesManager/lang/sq.json
  plugins/SitesManager/lang/sv.json
  plugins/SitesManager/lang/tr.json
  plugins/SitesManager/lang/zh-cn.json
  plugins/SitesManager/lang/zh-tw.json
Labels: c: i18n

#20699 Prevent duplicate dates for the purge old archive data command
  plugins/CoreAdminHome/Commands/PurgeOldArchiveData.php
Labels: Bug, not-in-changelog, Needs Review, 5.0.0

#20711 Remove steps relating to GTM container preview and adjust wording of other steps
  plugins/SitesManager/lang/en.json
  plugins/SitesManager/templates/_gtmTabInstructions.twig
  tests/UI/expected-screenshots/EmptySite_GTM_emptySiteDashboard.png
Labels: Needs Review

#20710 [4.x] Remove steps relating to GTM container preview and adjust wording of other steps
  plugins/SitesManager/lang/en.json
  plugins/SitesManager/templates/_gtmTabInstructions.twig
  tests/UI/expected-screenshots/EmptySite_GTM_emptySiteDashboard.png
Labels: Needs Review

#20679 Apply #20555 to 4.x-dev - fix two issues with handling of processing dependent archives
  core/ArchiveProcessor.php
  core/ArchiveProcessor/Loader.php
  core/ArchiveProcessor/Parameters.php
  core/DataAccess/LogAggregator.php
  plugins/Goals/Archiver.php
  tests/PHPUnit/Integration/ArchiveProcessor/LoaderTest.php
  tests/PHPUnit/Integration/ArchiveTest.php
Labels: Needs Review

#20721 Ignore misc/user/*.js
  .gitignore
Labels: not-in-changelog, Needs Review

#20725 Restore mobile menu html structure
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/ReportingMenu/ReportingMenu.vue
  tests/UI/expected-screenshots/Menus_mobile_left.png
  tests/UI/specs/Menus_spec.js
Labels: not-in-changelog, Needs Review

#20712 Translations update from Hosted Weblate
  plugins/CoreAdminHome/lang/uk.json
  plugins/CorePluginsAdmin/lang/uk.json
  plugins/Ecommerce/lang/ru.json
  plugins/Feedback/lang/uk.json
  plugins/ImageGraph/lang/ru.json
  plugins/Live/lang/ru.json
  plugins/PrivacyManager/lang/ca.json
  plugins/Referrers/lang/uk.json
  plugins/SitesManager/lang/ca.json
  plugins/SitesManager/lang/el.json
  plugins/SitesManager/lang/nl.json
  plugins/SitesManager/lang/tr.json
  plugins/Tour/lang/ru.json
  plugins/Tour/lang/uk.json
  plugins/VisitFrequency/lang/ru.json
Labels: not-in-changelog, c: i18n

#20733 Improved no data screen steps and UI for WordPress
  plugins/SitesManager/lang/en.json
  plugins/SitesManager/stylesheets/SitesManager.less
  plugins/SitesManager/templates/_siteWithoutDataTabs.twig
  plugins/SitesManager/templates/_wordpressTabInstructions.twig
  tests/UI/expected-screenshots/EmptySite_Wordpress_emptySiteDashboard.png
  tests/UI/expected-screenshots/OneClickUpdate_login.png
Labels: not-in-changelog

#20754 [PHP8.2 deprecations] Ensure string conversion is applied to truthy values only when validating email domains
  plugins/UsersManager/Validators/AllowedEmailDomain.php
Labels: not-in-changelog, Needs Review

#20743 Translations update from Hosted Weblate
  lang/eu.json
  plugins/SitesManager/lang/ca.json
  plugins/SitesManager/lang/el.json
  plugins/SitesManager/lang/tr.json
Labels: not-in-changelog, c: i18n

#20637 No-data GTM screen translations
  plugins/SitesManager/lang/de.json
  plugins/SitesManager/lang/en.json
  plugins/SitesManager/lang/es.json
  plugins/SitesManager/lang/fr.json
  plugins/SitesManager/lang/it.json
  plugins/SitesManager/lang/nl.json
  plugins/SitesManager/lang/tr.json
  plugins/SitesManager/templates/_gtmTabInstructions.twig
  plugins/SitesManager/templates/_siteWithoutDataTabs.twig
  tests/UI/expected-screenshots/EmptySite_GTM_emptySiteDashboard.png
Labels: Needs Review, BHAG-Tracking-OKR-Q2

#20758 Improve changelog wording related to `file://` and `enableFileTracking`
  CHANGELOG.md
Labels: not-in-changelog, Needs Review

#20704 [4.x] Add German, Spanish, French, Italian and Dutch translation for no-data GTM page
  plugins/SitesManager/lang/de.json
  plugins/SitesManager/lang/en.json
  plugins/SitesManager/lang/es.json
  plugins/SitesManager/lang/fr.json
  plugins/SitesManager/lang/it.json
  plugins/SitesManager/lang/nl.json
  plugins/SitesManager/templates/_gtmTabInstructions.twig
  plugins/SitesManager/templates/_siteWithoutDataTabs.twig
  tests/PHPUnit/Unit/Period/RangeTest.php
  tests/UI/expected-screenshots/EmptySite_GTM_emptySiteDashboard.png
Labels: BHAG-Tracking-OKR-Q2

#20748 Improved no data screen steps and UI for WordPress
  plugins/SitesManager/lang/en.json
  plugins/SitesManager/stylesheets/SitesManager.less
  plugins/SitesManager/templates/_siteWithoutDataTabs.twig
  plugins/SitesManager/templates/_wordpressTabInstructions.twig
  tests/UI/expected-screenshots/EmptySite_Wordpress_emptySiteDashboard.png
  tests/UI/expected-screenshots/OneClickUpdate_login.png
Labels: Needs Review, BHAG-Tracking-OKR-Q2

#20775 Fix overfloating element in goals widget
  plugins/Goals/stylesheets/goals.less
Labels: not-in-changelog, Needs Review

#20782 Correctly escape report name in CSV exports
  core/DataTable/Renderer/Csv.php
  core/ReportRenderer/Csv.php
Labels: c: Security, Needs Review

#20776 Correctly decode values in movers & shakers widget
  plugins/Insights/templates/table_row.twig
Labels: not-in-changelog, Needs Review

#20785 Correctly escape report name in CSV exports
  core/DataTable/Renderer/Csv.php
  core/ReportRenderer/Csv.php
Labels: c: Security

#20786 Remove display:flex from list of actions in live visits entry
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_reset.png
  plugins/Insights/tests/UI/expected-screenshots/Insights_initial.png
  plugins/Live/stylesheets/live.less
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard2.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_realtime_visits.png
Labels: not-in-changelog, Needs Review

#20526 Improve page conversion attribution performance with pre-calculated field
  core/DataAccess/LogAggregator.php
  core/Tracker/GoalManager.php
  core/Tracker/Model.php
  core/Updates/5.0.0-b1.php
  plugins/Actions/ArchivingHelper.php
  plugins/CoreUpdater/tests/UI/expected-screenshots/CoreUpdaterDb_main.png
  plugins/CoreUpdater/tests/UI/expected-screenshots/CoreUpdaterDb_main_instance.png
  plugins/Goals/Columns/PageviewsBefore.php
  plugins/Goals/Commands/CalculateConversionPages.php
  plugins/Goals/Model.php
  plugins/Goals/lang/en.json
  plugins/Goals/tests/System/CalculateConversionPagesCommandTest.php
  plugins/Goals/tests/System/TrackGoalsPagesTest.php
  plugins/PrivacyManager/tests/System/expected/anonymizeVisitInformation_allSitesAllDates.json
  plugins/PrivacyManager/tests/System/expected/anonymizeVisitInformation_anonymizeUserId.json
  plugins/PrivacyManager/tests/System/expected/anonymizeVisitInformation_restrictDate.json
  plugins/PrivacyManager/tests/System/expected/anonymizeVisitInformation_restrictSites.json
  plugins/PrivacyManager/tests/System/expected/exportDataSubject_allVisits.json
  plugins/PrivacyManager/tests/System/expected/exportDataSubject_oneVisitGiven.json
  tests/PHPUnit/Integration/Columns/DimensionTest.php
  tests/PHPUnit/System/expected/test_CustomEvents__Actions.getPageUrls_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_CustomEvents_eventCategoryOrNameMatch__Actions.getPageUrls_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_eventValueMatch__Actions.getPageUrls_day.xml
  tests/PHPUnit/System/expected/test_CustomEvents_segmentMatchesEventActionPlay__Actions.getPageUrls_day.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_flat__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_invertCompare__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_labelFilter__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_multipleMultiPeriods__Actions.getPageUrls_day.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_multipleSites_multipleCompare__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_periods__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_rangePeriodAgainstSingle__Actions.getPageUrls_range.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_segmentsAndPeriods__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_segments__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_singleAgainstRange__Actions.getPageUrls_day.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_subtableActions__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getEntryPageUrls_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getEntryPageUrls_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getExitPageUrls_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getExitPageUrls_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Actions.getPageUrls_range.xml
Labels: c: Performance, not-in-changelog, Needs Review

#20781 Added site detection for Vue and added relevant tab and info
  core/SiteContentDetector.php
  plugins/CoreAdminHome/CoreAdminHome.php
  plugins/CoreAdminHome/lang/en.json
  plugins/CoreAdminHome/templates/trackingCodeGenerator.twig
  plugins/Installation/Controller.php
  plugins/Installation/tests/UI/expected-screenshots/Installation_js_tracking.png
  plugins/SitesManager/Controller.php
  plugins/SitesManager/GtmSiteTypeGuesser.php
  plugins/SitesManager/SitesManager.php
  plugins/SitesManager/config/config.php
  plugins/SitesManager/images/vue-icon.png
  plugins/SitesManager/lang/en.json
  plugins/SitesManager/stylesheets/SitesManager.less
  plugins/SitesManager/templates/_displayJavascriptCode.twig
  plugins/SitesManager/templates/_siteWithoutDataTabs.twig
  plugins/SitesManager/templates/_trackingCodeEmail.twig
  plugins/SitesManager/templates/_vueTabInstructions.twig
  tests/PHPUnit/Fixtures/EmptySiteWithSiteContentDetectionVue.php
  tests/PHPUnit/Unit/SiteContentDetectorTest.php
  tests/UI/expected-screenshots/EmptySite_ConsentManager_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_GA3_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_GA4_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_Vue_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_emptySiteDashboard.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_manage_tracking_code.png
  tests/UI/specs/EmptySite_Vue_spec.js
Labels: not-in-changelog, Needs Review, BHAG-Tracking-OKR-Q2

#20790 Added site detection for Vue and added relevant tab and info
  core/SiteContentDetector.php
  plugins/CoreAdminHome/CoreAdminHome.php
  plugins/CoreAdminHome/lang/en.json
  plugins/CoreAdminHome/templates/trackingCodeGenerator.twig
  plugins/Installation/Controller.php
  plugins/Installation/tests/UI/expected-screenshots/Installation_js_tracking.png
  plugins/SitesManager/Controller.php
  plugins/SitesManager/GtmSiteTypeGuesser.php
  plugins/SitesManager/SitesManager.php
  plugins/SitesManager/config/config.php
  plugins/SitesManager/images/vue-icon.png
  plugins/SitesManager/lang/en.json
  plugins/SitesManager/stylesheets/SitesManager.less
  plugins/SitesManager/templates/_displayJavascriptCode.twig
  plugins/SitesManager/templates/_siteWithoutDataTabs.twig
  plugins/SitesManager/templates/_trackingCodeEmail.twig
  plugins/SitesManager/templates/_vueTabInstructions.twig
  tests/PHPUnit/Fixtures/EmptySiteWithSiteContentDetectionVue.php
  tests/PHPUnit/Unit/SiteContentDetectorTest.php
  tests/UI/expected-screenshots/EmptySite_ConsentManager_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_GA3_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_GA4_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_Vue_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_emptySiteDashboard.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_manage_tracking_code.png
  tests/UI/specs/EmptySite_Vue_spec.js
Labels: Needs Review

#20795 Ensure to show sparkline evolution correctly if lower value should be treated as better
  plugins/CoreVisualizations/Visualizations/Sparklines/Config.php
  plugins/CoreVisualizations/templates/macros.twig
  plugins/CoreVisualizations/tests/Integration/SparklinesConfigTest.php
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_create_new.png
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_small_screen.png
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_reset.png
  plugins/Diagnostics/tests/UI/expected-screenshots/Diagnostics_page.png
  plugins/Goals/Reports/Get.php
  plugins/Referrers/Reports/Get.php
  plugins/VisitsSummary/Reports/Get.php
  tests/UI/expected-screenshots/Comparison_visitors_overview_no_compare.png
  tests/UI/expected-screenshots/Menus_mobile_left.png
  tests/UI/expected-screenshots/SupportedBrowser_widget_loads_when_browser_supported.png
  tests/UI/expected-screenshots/UIIntegrationTest_category_help.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard4.png
  tests/UI/expected-screenshots/UIIntegrationTest_metric_tooltip.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_overview.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_overview_columns.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_overview_limit.png
Labels: not-in-changelog, Needs Review

#20806 Ensure series label isn't set to null
  plugins/ImageGraph/API.php
  plugins/ImageGraph/StaticGraph.php
Labels: not-in-changelog, Needs Review
