Repository matomo-org/matomo, pull requests merged in 2023-06, with the labels that each got.

#20828 in AutoSuggestAPITest make sure static var overrides are undone after the test finishes
  plugins/API/tests/System/AutoSuggestAPITest.php
Labels: c: Tests & QA

#20394 introduce RecordBuilder concept to split up Archiver code and use in Goals
  core/Archive.php
  core/ArchiveProcessor.php
  core/ArchiveProcessor/Loader.php
  core/ArchiveProcessor/Parameters.php
  core/ArchiveProcessor/PluginsArchiver.php
  core/ArchiveProcessor/Record.php
  core/ArchiveProcessor/RecordBuilder.php
  core/ArchiveProcessor/Rules.php
  core/CronArchive.php
  core/CronArchive/QueueConsumer.php
  core/DataAccess/ArchiveSelector.php
  core/DataAccess/LogAggregator.php
  core/DataAccess/Model.php
  core/Piwik.php
  core/Plugin/Archiver.php
  plugins/Goals/Archiver.php
  plugins/Goals/Goals.php
  plugins/Goals/RecordBuilders/Base.php
  plugins/Goals/RecordBuilders/GeneralGoalsRecords.php
  plugins/Goals/RecordBuilders/ProductRecord.php
  plugins/Goals/Reports/GetVisitsUntilConversion.php
  plugins/SegmentEditor/SegmentEditor.php
  tests/PHPUnit/Integration/Archive/PartialArchiveTest.php
  tests/PHPUnit/Integration/ArchiveProcessor/LoaderTest.php
  tests/PHPUnit/Integration/DataAccess/ArchiveSelectorTest.php
  tests/PHPUnit/System/OneVisitorOneWebsiteSeveralDaysDateRangeArchivingTest.php
Labels: Needs Review, Do not close, 5.0.0

#20744 Provide json output of console command `plugin:list`
  core/Plugin/ConsoleCommand.php
  plugins/CoreAdminHome/Commands/ConfigDelete.php
  plugins/CoreAdminHome/Commands/ConfigGet.php
  plugins/CorePluginsAdmin/Commands/ListPlugins.php
Labels: Enhancement

#20827 convert ignoreClearAllViewDataTableParameters to test vars instead of paramter
  plugins/Installation/tests/UI/Installation_spec.js
  tests/PHPUnit/Framework/TestingEnvironmentManipulator.php
  tests/UI/specs/UIIntegration_spec.js
Labels: c: Tests & QA, Needs Review

#20831 cannot move Archiver consts/static vars to GeneralGoalsRecords/ProductRecord
  plugins/Goals/Archiver.php
  plugins/Goals/RecordBuilders/GeneralGoalsRecords.php
  plugins/Goals/Reports/GetVisitsUntilConversion.php
Labels: Needs Review, Regression

#20759 Translations update from Hosted Weblate
  lang/id.json
  lang/it.json
  plugins/CoreAdminHome/lang/ca.json
  plugins/CoreAdminHome/lang/el.json
  plugins/CoreAdminHome/lang/id.json
  plugins/CoreAdminHome/lang/it.json
  plugins/CoreAdminHome/lang/nl.json
  plugins/CoreAdminHome/lang/pt-br.json
  plugins/CoreAdminHome/lang/tr.json
  plugins/CoreAdminHome/lang/uk.json
  plugins/CorePluginsAdmin/lang/id.json
  plugins/CorePluginsAdmin/lang/it.json
  plugins/CoreUpdater/lang/it.json
  plugins/Feedback/lang/it.json
  plugins/Goals/lang/ca.json
  plugins/Goals/lang/el.json
  plugins/Goals/lang/it.json
  plugins/Goals/lang/nl.json
  plugins/Goals/lang/pt-br.json
  plugins/Goals/lang/tr.json
  plugins/Installation/lang/de.json
  plugins/Installation/lang/id.json
  plugins/Installation/lang/it.json
  plugins/Login/lang/it.json
  plugins/Marketplace/lang/pt-br.json
  plugins/MobileMessaging/lang/it.json
  plugins/PrivacyManager/lang/nl.json
  plugins/PrivacyManager/lang/tr.json
  plugins/SegmentEditor/lang/it.json
  plugins/SegmentEditor/lang/pt-br.json
  plugins/SitesManager/lang/ca.json
  plugins/SitesManager/lang/de.json
  plugins/SitesManager/lang/el.json
  plugins/SitesManager/lang/es.json
  plugins/SitesManager/lang/fr.json
  plugins/SitesManager/lang/it.json
  plugins/SitesManager/lang/nl.json
  plugins/SitesManager/lang/tr.json
  plugins/UserId/lang/pt-br.json
  plugins/UserLanguage/lang/pt-br.json
  plugins/VisitTime/lang/it.json
  plugins/VisitorInterest/lang/it.json
  plugins/VisitorInterest/lang/pt-br.json
  plugins/WebsiteMeasurable/lang/pt-br.json
Labels: not-in-changelog, c: i18n

#20420 Improve handling and detection of region codes and names
  plugins/GeoIp2/Commands/UpdateRegionCodes.php
  plugins/GeoIp2/LocationProvider/GeoIp2.php
  plugins/GeoIp2/LocationProvider/GeoIp2/Php.php
  plugins/GeoIp2/data/isoRegionNames.php
  plugins/GeoIp2/tests/System/expected/test_ConvertRegionCodesToIsoTest_testExecute_ShouldConvertRegionCodes__UserCountry.getRegion_month.xml
  tests/PHPUnit/Integration/ReleaseCheckListTest.php
  tests/PHPUnit/System/expected/test_ImportLogs__Live.getLastVisitsDetails_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs__UserCountry.getCity_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__UserCountry.getRegion_month.xml
Labels: Stale, 5.0.0

#20836 Fix/improve some randomly failing tests
  plugins/Annotations/tests/System/AnnotationsTest.php
  plugins/BulkTracking/tests/Integration/HandlerTest.php
  plugins/BulkTracking/tests/Integration/RequestsTest.php
  plugins/CoreAdminHome/tests/Integration/TasksTest.php
  plugins/CoreHome/tests/Integration/LoginAllowlistTest.php
  plugins/CustomDimensions/tests/Unit/Dimension/ActiveTest.php
  plugins/CustomDimensions/tests/Unit/Dimension/CaseSensitiveTest.php
  plugins/CustomDimensions/tests/Unit/Dimension/NameTest.php
  plugins/CustomDimensions/tests/Unit/Dimension/ScopeTest.php
  plugins/CustomJsTracker/tests/Integration/FileTest.php
  plugins/CustomJsTracker/tests/Integration/TrackerUpdaterTest.php
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_create_new.png
  plugins/ExampleLogTables/tests/System/CustomLogTablesTest.php
  plugins/LanguagesManager/tests/Integration/LanguagesManagerTest.php
  plugins/Live/tests/Integration/ModelTest.php
  plugins/Login/tests/Integration/APITest.php
  plugins/Referrers/tests/Unit/SearchEngineTest.php
  tests/PHPUnit/Integration/AccessTest.php
  tests/PHPUnit/Integration/ArchiveProcessor/PluginsArchiverTest.php
  tests/PHPUnit/Integration/FilesystemTest.php
  tests/PHPUnit/Integration/HttpTest.php
  tests/PHPUnit/Integration/Measurable/MeasurableSettingsTest.php
  tests/PHPUnit/Integration/ReleaseCheckListTest.php
  tests/PHPUnit/Integration/SegmentTest.php
  tests/PHPUnit/Integration/Settings/BaseSettingsTestCase.php
  tests/PHPUnit/Integration/Tracker/HandlerTest.php
  tests/PHPUnit/Integration/Updater/Migration/Db/MigrationsTest.php
  tests/PHPUnit/Integration/UpdaterTest.php
  tests/PHPUnit/Integration/Validator/IdSiteTest.php
  tests/PHPUnit/Unit/FilesystemTest.php
  tests/PHPUnit/Unit/PeriodTest.php
  tests/PHPUnit/Unit/Report/ReportWidgetConfigTest.php
  tests/PHPUnit/Unit/Validator/CharacterLengthTest.php
  tests/PHPUnit/Unit/Validator/DateTimeTest.php
  tests/PHPUnit/Unit/Validator/EmailTest.php
  tests/PHPUnit/Unit/Validator/IpRangesTest.php
  tests/PHPUnit/Unit/Validator/NotEmptyTest.php
  tests/PHPUnit/Unit/Validator/NumberRangeTest.php
  tests/PHPUnit/Unit/Validator/UrlLikeTest.php
  tests/PHPUnit/Unit/Validator/WhiteListedValueTest.php
  tests/PHPUnit/Unit/Widget/WidgetConfigTest.php
  tests/PHPUnit/Unit/Widget/WidgetContainerConfigTest.php
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard3.png
  tests/UI/specs/UIIntegration_spec.js
Labels: c: Tests & QA, not-in-changelog

#20847 Prevent possible DI errors during update
  core/AssetManager/UIAssetFetcher/PluginUmdAssetFetcher.php
Labels: Regression

#20843 Configure linguist to exclude `node_modules` in statistics
  .gitattributes
Labels: not-in-changelog

#20851 Remove reference to Divezone from translation text
  plugins/UsersManager/lang/en.json
Labels: not-in-changelog

#20850 remove setting a revised property
  plugins/UserId/Reports/GetUsers.php
Labels: not-in-changelog, Needs Review

#20849 Improve handling of updating/creating a new index on log_visit table in Matomo 5
  core/Db/Schema/Mysql.php
  core/Tracker/Model.php
  core/Updates/5.0.0-b1.php
  plugins/CoreHome/CoreHome.php
Labels: not-in-changelog, Regression

#20862 Merged multiple notifications under tracking code into one
  plugins/SitesManager/Controller.php
  plugins/SitesManager/lang/en.json
  plugins/SitesManager/stylesheets/SitesManager.less
  plugins/SitesManager/templates/_siteWithoutDataTabs.twig
  tests/PHPUnit/Fixtures/EmptySiteWithSiteContentDetectionMergeNotification.php
  tests/PHPUnit/Fixtures/EmptySiteWithSiteContentDetectionMergeNotificationOnlyGA.php
  tests/UI/expected-screenshots/EmptySite_ConsentManager_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_GA3_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_GA4_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_MergedNotificationGA_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_MergedNotification_emptySiteDashboard.png
  tests/UI/specs/EmptySite_MergedNotificationGA_spec.js
  tests/UI/specs/EmptySite_MergedNotification_spec.js
Labels: Needs Review

#20687 Remove use of DataArray from Goals plugin
  core/API/DataTablePostProcessor.php
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_SegmentPageUrlContains__Goals.getItemsName_day.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_SegmentPageUrlContains__Goals.getItemsName_week.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems__Goals.getItemsName_day.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems__Goals.getItemsName_week.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_productPrice__Goals.getItemsName_week.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_productSkuSegment__Goals.getItemsName_week.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_html_tables_only__ScheduledReports.generateReport_week.original.html
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_in_csv__ScheduledReports.generateReport_week.original.csv
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_in_tsv__ScheduledReports.generateReport_week.original.tsv
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItemsmultipleDates__Goals.getItemsName_day.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItemsmultipleDates_andMultipleWebsites__Goals.getItemsName_day.xml
  plugins/Goals/RecordBuilders/GeneralGoalsRecords.php
  plugins/Goals/RecordBuilders/ProductRecord.php
Labels: Needs Review

#20881 Fixes some failing tests
  plugins/Diagnostics/tests/UI/expected-screenshots/Diagnostics_page.png
  plugins/Marketplace/Api/Client.php
  plugins/Marketplace/tests/Integration/PluginsTest.php
Labels: c: Tests & QA, not-in-changelog

#20883 Remove unintended blank target from link
  plugins/SitesManager/templates/siteWithoutData.twig
Labels: Needs Review

#20885 Improve handling of deactivating incompatible plugins during update
  plugins/CoreUpdater/Updater.php
Labels: not-in-changelog, Needs Review

#20880 No-data translations for Vue.js, Cloudflare and WordPress
  plugins/SitesManager/Controller.php
  plugins/SitesManager/lang/de.json
  plugins/SitesManager/lang/en.json
  plugins/SitesManager/lang/es.json
  plugins/SitesManager/lang/fr.json
  plugins/SitesManager/lang/it.json
  plugins/SitesManager/lang/nl.json
  plugins/SitesManager/templates/_siteWithoutDataTabs.twig
  plugins/SitesManager/templates/_wordpressTabInstructions.twig
  tests/UI/expected-screenshots/EmptySite_Cloudflare_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_Vue_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_Wordpress_emptySiteDashboard.png
  tests/UI/expected-screenshots/OneClickUpdate_login.png
Labels: c: Design / UI, Needs Review, c: Tracking, BHAG-Tracking-OKR-Q2

#20897 Remove translations for product or library names
  plugins/CoreAdminHome/templates/trackingCodeGenerator.twig
  plugins/SitesManager/SitesManager.php
  plugins/SitesManager/lang/en.json
  plugins/SitesManager/templates/_displayJavascriptCode.twig
  plugins/SitesManager/templates/_siteWithoutDataTabs.twig
  plugins/SitesManager/templates/_trackingCodeEmail.twig
Labels: not-in-changelog, Needs Review

#20873 4.x Check if report exists prior to getting its row identifier
  core/Plugin/Visualization.php
Labels: not-in-changelog, Needs Review

#20807 Ensure Installation sets trusted host including port number if available
  plugins/Installation/Controller.php
Labels: not-in-changelog, Needs Review, Stale

#20884 Correctly handle rename index on older mysql servers
  core/Updater/Migration/Db.php
  core/Updates/5.0.0-b1.php
Labels: not-in-changelog, Needs Review

#20878 React steps updated for history change step, #PG-2779
  plugins/SitesManager/lang/en.json
  plugins/SitesManager/stylesheets/SitesManager.less
  plugins/SitesManager/templates/_reactTabInstructions.twig
  plugins/SitesManager/templates/_siteWithoutDataTabs.twig
Labels: not-in-changelog, Needs Review

#20898 Check if report exists prior to getting its row identifier
  core/Plugin/Visualization.php
Labels: not-in-changelog, Needs Review

#20895 Translations update from Hosted Weblate
  plugins/CoreAdminHome/lang/ca.json
  plugins/CoreAdminHome/lang/uk.json
  plugins/Marketplace/lang/el.json
  plugins/SitesManager/lang/ca.json
  plugins/SitesManager/lang/de.json
  plugins/SitesManager/lang/el.json
  plugins/SitesManager/lang/es.json
  plugins/SitesManager/lang/fr.json
  plugins/SitesManager/lang/it.json
  plugins/SitesManager/lang/nl.json
  plugins/SitesManager/lang/pt-br.json
  plugins/SitesManager/lang/tr.json
  plugins/UserCountry/lang/pt-br.json
Labels: not-in-changelog, c: i18n

#20899 Translations update from Hosted Weblate
  plugins/SitesManager/lang/ca.json
  plugins/SitesManager/lang/el.json
  plugins/SitesManager/lang/pt-br.json
Labels: not-in-changelog, c: i18n

#20879 Disable save button, while a site is being saved
  plugins/SitesManager/vue/dist/SitesManager.umd.js
  plugins/SitesManager/vue/dist/SitesManager.umd.min.js
  plugins/SitesManager/vue/src/SiteFields/SiteFields.vue
Labels: not-in-changelog, Needs Review

#20705 use RecordBuilders in Actions plugin
  core/ArchiveProcessor/Record.php
  core/ArchiveProcessor/RecordBuilder.php
  plugins/Actions/Archiver.php
  plugins/Actions/ArchivingHelper.php
  plugins/Actions/RecordBuilders/ActionReports.php
  plugins/Actions/RecordBuilders/SearchCategories.php
  plugins/Diagnostics/tests/Integration/Commands/AnalyzeArchiveTableTest.php
  tests/PHPUnit/System/OneVisitorOneWebsiteSeveralDaysDateRangeArchivingTest.php
  tests/PHPUnit/System/expected/test_SiteSearch_Actions.getSiteSearchCategories_firstSite_lastN__API.getProcessedReport_day.xml
  tests/PHPUnit/Unit/ArchiveProcessor/RecordBuilderTest.php
Labels: Needs Review

#20905 Fix drag&drop in datatable search bar
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/DataTable/DataTableActions.vue
Labels: not-in-changelog, Needs Review

#20909 Fix dropdowns in segment editor
  plugins/SegmentEditor/stylesheets/segmentation.less
  plugins/SegmentEditor/tests/UI/SegmentSelectorEditor_spec.js
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_add_new_and_condition.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_add_new_or_condition.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_dimension_drag_drop.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_drag_and_condition.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_drag_or_condition.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_saved_details.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_suggested_values.png
Labels: not-in-changelog, Needs Review

#20719 use RecordBuilders in Contents plugin
  core/ArchiveProcessor/Record.php
  core/DataTable.php
  core/DataTable/Row.php
  plugins/Contents/Archiver.php
  plugins/Contents/DataArray.php
  plugins/Contents/RecordBuilders/ContentRecords.php
  plugins/Diagnostics/tests/Integration/Commands/AnalyzeArchiveTableTest.php
  plugins/Goals/Reports/GetVisitsUntilConversion.php
Labels: Needs Review

#20764 align allowed characters for option `--value` on console command `config:delete` to `config:set`
  plugins/CoreAdminHome/Commands/ConfigDelete.php
  plugins/CoreAdminHome/tests/Integration/Commands/ConfigDeleteTest.php
Labels: Needs Review

#20811 Ignore "code style" commits in the blame view
  .git-blame-ignore-revs
  .gitattributes
  .github/scripts/clean-build.sh
  config/global.php
  tests/PHPUnit/Integration/ReleaseCheckListTest.php
Labels: not-in-changelog

#20762 use RecordBuilders in UserLanguage plugin
  plugins/UserLanguage/Archiver.php
  plugins/UserLanguage/RecordBuilders/Languages.php
Labels: Needs Review, Stale

#20747 use RecordBuilders in the Resolution plugin
  plugins/Resolution/Archiver.php
  plugins/Resolution/RecordBuilders/Configuration.php
  plugins/Resolution/RecordBuilders/Resolution.php
  tests/PHPUnit/System/OneVisitorOneWebsiteSeveralDaysDateRangeArchivingTest.php
Labels: Needs Review, Stale

#20755 use RecordBuilders in UserId plugin
  plugins/UserId/Archiver.php
  plugins/UserId/RecordBuilders/Users.php
Labels: Needs Review

#20739 use RecordBuilders in the PagePerformance plugin
  plugins/PagePerformance/Archiver.php
  plugins/PagePerformance/RecordBuilders/PerformanceTotals.php
Labels: Needs Review, Stale

#20765 use RecordBuilders in VisitorInterest plugin
  plugins/VisitorInterest/Archiver.php
  plugins/VisitorInterest/RecordBuilders/Engagement.php
Labels: Needs Review, Stale

#20731 use RecordBuilders in Events plugin
  plugins/Events/Archiver.php
  plugins/Events/RecordBuilders/EventReports.php
Labels: Needs Review

#20917 Fixing Order metric so that the plural name is used correctly
  plugins/Ecommerce/Columns/Order.php
Labels: Needs Review

#20915 Single click copy button for code snippets
  LEGALNOTICE
  lang/en.json
  plugins/CoreAdminHome/lang/en.json
  plugins/CoreAdminHome/stylesheets/generalSettings.less
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.js
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.min.js
  plugins/CoreAdminHome/vue/src/ImageTrackingCodeGenerator/ImageTrackingCodeGenerator.vue
  plugins/CoreAdminHome/vue/src/JsTrackingCodeGenerator/JsTrackingCodeAdvancedOptions.vue
  plugins/CoreAdminHome/vue/src/JsTrackingCodeGenerator/JsTrackingCodeGenerator.vue
  plugins/CoreAdminHome/vue/src/JsTrackingCodeGenerator/JsTrackingCodeGeneratorSitesWithoutData.vue
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/stylesheets/coreHome.less
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/CopyToClipboard/CopyToClipboard.adapter.ts
  plugins/CoreHome/vue/src/CopyToClipboard/CopyToClipboard.ts
  plugins/CoreHome/vue/src/index.ts
  plugins/CustomDimensions/vue/dist/CustomDimensions.umd.js
  plugins/CustomDimensions/vue/dist/CustomDimensions.umd.min.js
  plugins/CustomDimensions/vue/src/Edit/Edit.vue
  plugins/CustomDimensions/vue/src/Manage/Manage.vue
  plugins/Installation/stylesheets/installation.css
  plugins/Installation/tests/UI/expected-screenshots/Installation_js_tracking.png
  plugins/Morpheus/fonts/matomo.eot
  plugins/Morpheus/fonts/matomo.svg
  plugins/Morpheus/fonts/matomo.ttf
  plugins/Morpheus/fonts/matomo.woff
  plugins/Morpheus/fonts/matomo.woff2
  plugins/Morpheus/fonts/selection.json
  plugins/Morpheus/stylesheets/base/icons.css
  plugins/Morpheus/templates/demo.twig
  plugins/Morpheus/tests/UI/expected-screenshots/Morpheus_load.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_users_opt_out_default.png
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.js
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.min.js
  plugins/PrivacyManager/vue/src/OptOutCustomizer/OptOutCustomizer.vue
  plugins/Referrers/tests/UI/expected-screenshots/CampaignBuilder_generate_url_nokeyword.png
  plugins/Referrers/tests/UI/expected-screenshots/CampaignBuilder_generate_url_withkeyword.png
  plugins/Referrers/vue/dist/Referrers.umd.js
  plugins/Referrers/vue/dist/Referrers.umd.min.js
  plugins/Referrers/vue/src/CampaignBuilder/CampaignBuilder.vue
  plugins/SitesManager/templates/_displayJavascriptCode.twig
  plugins/SitesManager/templates/_gtmTabInstructions.twig
  plugins/SitesManager/templates/_vueTabInstructions.twig
  plugins/SitesManager/templates/_wordpressTabInstructions.twig
  plugins/UsersManager/templates/addNewTokenSuccess.twig
  plugins/UsersManager/tests/UI/expected-screenshots/UserSettings_add_token_success.png
  tests/UI/expected-screenshots/EmptySite_ConsentManager_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_GA3_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_GA4_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_GTM_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_MergedNotificationGA_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_MergedNotification_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_React_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_Wordpress_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_emptySiteDashboard.png
  tests/UI/expected-screenshots/EmptySite_hideAdvancedTrackingOptions.png
  tests/UI/expected-screenshots/EmptySite_showAdvancedTrackingOptions.png
  tests/UI/expected-screenshots/OneClickUpdate_login.png
  tests/UI/expected-screenshots/Theme_demo.png
Labels: Enhancement, BHAG-Tracking-OKR-Q2

#20809 Allow to optionally defer JS from custom layout templates
  core/AssetManager.php
  core/Twig.php
  core/View.php
  plugins/CoreHome/templates/_uiControl.twig
  plugins/Login/templates/loginLayout.twig
  plugins/Morpheus/javascripts/piwikHelper.js
  plugins/Morpheus/templates/_iframeBuster.twig
  plugins/Morpheus/templates/_jsCssIncludes.twig
Labels: c: Performance, Needs Review

#20914 Clean up some link styling css
  plugins/Annotations/stylesheets/annotations.less
  plugins/Annotations/templates/_annotation.twig
  plugins/Annotations/templates/_annotationList.twig
  plugins/CoreHome/stylesheets/cloud.less
  plugins/CoreHome/stylesheets/coreHome.less
  plugins/CoreHome/stylesheets/dataTable/_dataTable.less
  plugins/CoreHome/stylesheets/dataTable/_entityTable.less
  plugins/CoreHome/stylesheets/dataTable/_rowActions.less
  plugins/CoreHome/stylesheets/dataTable/_tableConfiguration.less
  plugins/CoreUpdater/tests/UI/expected-screenshots/CoreUpdaterDb_main.png
  plugins/CoreUpdater/tests/UI/expected-screenshots/CoreUpdaterDb_main_instance.png
  plugins/CoreUpdater/tests/UI/expected-screenshots/CoreUpdaterDb_updated.png
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_widget_list_shown.png
  plugins/Dashboard/tests/UI/expected-screenshots/DashboardManager_widget_preview.png
  plugins/Feedback/stylesheets/feedback.less
  plugins/Installation/tests/UI/expected-screenshots/Installation_congrats.png
  plugins/Installation/tests/UI/expected-screenshots/Installation_js_tracking.png
  plugins/Installation/tests/UI/expected-screenshots/Installation_superuser.png
  plugins/Installation/tests/UI/expected-screenshots/Installation_superuser_de.png
  plugins/Installation/tests/UI/expected-screenshots/Installation_superuser_fail.png
  plugins/Morpheus/stylesheets/general/_default.less
  plugins/Morpheus/stylesheets/general/_typography.less
  plugins/Morpheus/stylesheets/main.less
  plugins/SegmentEditor/images/segment-move.png
  plugins/SegmentEditor/javascripts/Segmentation.js
  plugins/SegmentEditor/stylesheets/segmentation.less
  plugins/SitesManager/tests/UI/expected-screenshots/SitesManager_page_1.png
  plugins/SitesManager/tests/UI/expected-screenshots/SitesManager_page_1_again.png
  plugins/SitesManager/tests/UI/expected-screenshots/SitesManager_page_2.png
  plugins/SitesManager/tests/UI/expected-screenshots/SitesManager_search_page_1.png
  tests/UI/expected-screenshots/UIIntegrationTest_widgets_listing.png
Labels: not-in-changelog, Needs Review

#20930 Fix SEO plugin test
  plugins/SEO/tests/Integration/SEOTest.php
Labels: Bug

#20720 use RecordBuilders in CustomDimensions plugin
  core/DataArray.php
  core/DataTable/Filter/EnrichRecordWithGoalMetricSums.php
  core/Metrics.php
  plugins/CustomDimensions/Archiver.php
  plugins/CustomDimensions/CustomDimensions.php
  plugins/CustomDimensions/DataArray.php
  plugins/CustomDimensions/RecordBuilders/CustomDimension.php
Labels: Needs Review, Stale

#20934 Use variadics/splat instead of call_user_func_array()/func_get_args()
  DIObject.php
  core/Common.php
  core/DataAccess/ArchivingDbAdapter.php
  core/Log.php
  core/Visualization/Sparkline.php
  plugins/SitesManager/tests/Integration/SiteUrlsTest.php
Labels: Needs Review

#20935 Update Scheduled reports first page description text
  plugins/ScheduledReports/lang/en.json
  tests/UI/expected-screenshots/UIIntegrationTest_email_reports_editor.png
Labels: Needs Review

#20737 use RecordBuilders in ExamplePlugin
  core/ArchiveProcessor/PluginsArchiver.php
  core/Plugin/Archiver.php
  plugins/ExamplePlugin/API.php
  plugins/ExamplePlugin/Archiver.php
  plugins/ExamplePlugin/RecordBuilders/ExampleBlob.php
  plugins/ExamplePlugin/RecordBuilders/ExampleMetric.php
  plugins/ExamplePlugin/RecordBuilders/ExampleMetric2.php
  tests/PHPUnit/Integration/ArchiveProcessor/LoaderTest.php
Labels: not-in-changelog

#20931 [CSS Stylelint] Forbid irregular whitespaces
  .stylelintrc.json
Labels: not-in-changelog, Needs Review

#20932 [CSS Stylelint] Disallow appending unit to zero values
  .stylelintrc.json
  plugins/API/css/styles.css
  plugins/Annotations/stylesheets/annotations.less
  plugins/CoreHome/stylesheets/layout.less
  plugins/CoreHome/vue/src/MenuItemsDropdown/MenuItemsDropdown.less
  plugins/Feedback/stylesheets/feedback.less
  plugins/SegmentEditor/stylesheets/segmentation.less
  plugins/Transitions/stylesheets/transitions.less
  plugins/UsersManager/stylesheets/usersManager.less
Labels: not-in-changelog, Needs Review

#20933 [CSS Stylelint] Disallow empty blocks, comments and sources
  .stylelintrc.json
  plugins/Morpheus/stylesheets/base/font.css
Labels: not-in-changelog, Needs Review

#20939 [CSS Stylelint] Avoid duplications
  .stylelintrc.json
  plugins/Annotations/stylesheets/annotations.less
  plugins/CoreHome/stylesheets/dataTable/_dataTable.less
  plugins/CoreHome/stylesheets/dataTable/_subDataTable.less
  plugins/CoreHome/stylesheets/jquery.ui.autocomplete.css
  plugins/CoreHome/stylesheets/layout.less
  plugins/CoreHome/vue/src/PeriodSelector/PeriodSelector.less
  plugins/CoreHome/vue/src/SiteSelector/SiteSelector.less
  plugins/Dashboard/stylesheets/dashboard.less
  plugins/Dashboard/stylesheets/standalone.css
  plugins/Dashboard/stylesheets/widget.less
  plugins/Live/stylesheets/live.less
  plugins/Live/stylesheets/visitor_profile.less
  plugins/Marketplace/stylesheets/marketplace.less
  plugins/Morpheus/stylesheets/base/bootstrap.css
  plugins/Morpheus/stylesheets/general/_default.less
  plugins/Morpheus/stylesheets/general/_forms.less
  plugins/Morpheus/stylesheets/general/_jqueryUI.less
  plugins/Morpheus/stylesheets/main.less
  plugins/Morpheus/stylesheets/ui/_charts.less
  plugins/Morpheus/stylesheets/ui/_components.less
  plugins/Morpheus/stylesheets/ui/_list-group.less
  plugins/Morpheus/stylesheets/uibase/_periodSelect.less
  plugins/MultiSites/vue/src/Dashboard/Dashboard.less
  plugins/PrivacyManager/vue/src/AnonymizeLogData/AnonymizeLogData.less
  plugins/SegmentEditor/stylesheets/segmentation.less
  plugins/SegmentEditor/vue/src/SegmentGenerator/SegmentGenerator.less
  plugins/Transitions/stylesheets/transitions.less
Labels: not-in-changelog, Needs Review
