Repository matomo-org/matomo, pull requests merged in 2023-08, with the labels that each got.

#21094 fix issue in javascript test runner when JS tests finish before test runner setup code
  tests/javascript/testrunnerNode.js
Labels: Needs Review

#21090 Fix possible errors in sparklines when there is no data
  core/Visualization/Sparkline.php
  plugins/API/API.php
Labels: not-in-changelog, Needs Review

#21103 Added code to trigger Archiving.getIdSitesToMarkArchivesAsInvalidated on PrivacyManager.deleteDataSubjects
  core/Archive/ArchiveInvalidator.php
  plugins/PrivacyManager/Model/DataSubjects.php
Labels: not-in-changelog

#21098 Removes PhantomJS runner for JS tests
  plugins/TestRunner/Commands/TestsRunJS.php
  plugins/TestRunner/Commands/TestsRunUI.php
  plugins/TestRunner/Commands/TestsSetupFixture.php
  tests/javascript/testrunnerPhantom.js
  tests/lib/screenshot-testing/support/app.js
  tests/lib/screenshot-testing/support/test-environment.js
Labels: not-in-changelog, Needs Review

#20924 Redesign accept invitation screen
  lang/en.json
  plugins/Login/images/invitation-image.png
  plugins/Login/lang/en.json
  plugins/Login/stylesheets/login.less
  plugins/Login/templates/invitation.twig
  plugins/Login/templates/loginLayout.twig
  plugins/Login/tests/UI/expected-screenshots/Invite_set_password.png
  plugins/Login/tests/UI/expected-screenshots/Invite_wrong_password.png
  plugins/UsersManager/tests/Integration/UserInviteTest.php
Labels: Needs Review, Do not close

#21097 Improve Onborading flow
  lang/en.json
  plugins/Login/images/invitation-image.png
  plugins/Login/lang/en.json
  plugins/Login/stylesheets/login.less
  plugins/Login/templates/invitation.twig
  plugins/Login/templates/loginLayout.twig
  plugins/Login/tests/UI/expected-screenshots/Invite_set_password.png
  plugins/Login/tests/UI/expected-screenshots/Invite_wrong_password.png
  plugins/UsersManager/tests/Integration/UserInviteTest.php
Labels: not-in-changelog

#21122 fix row actions for action table with goal metrics
  plugins/CoreHome/javascripts/dataTable_rowactions.js
  plugins/Goals/tests/UI/Goals_spec.js
  plugins/Goals/tests/UI/expected-screenshots/Goals_goals_by_pages_row_evolution.png
Labels: not-in-changelog, Needs Review

#21093 Allow passing campaign parameters directly as tracking parameters
  plugins/Referrers/Columns/Base.php
  plugins/Referrers/tests/Integration/Columns/ReferrerTypeTest.php
Labels: not-in-changelog, Needs Review

#21101 Translations update from Hosted Weblate
  lang/el.json
  lang/pl.json
  lang/tr.json
  lang/uk.json
  plugins/CoreAdminHome/lang/ru.json
  plugins/CoreAdminHome/lang/tr.json
  plugins/CoreHome/lang/ru.json
  plugins/Login/lang/el.json
  plugins/Login/lang/tr.json
  plugins/SitesManager/lang/tr.json
  plugins/VisitTime/lang/it.json
Labels: not-in-changelog, c: i18n

#21131 Updated Morpheus example for array of checkbox
  plugins/Morpheus/Controller.php
  plugins/Morpheus/tests/UI/expected-screenshots/Morpheus_load.png
  tests/UI/expected-screenshots/Theme_demo.png
Labels: not-in-changelog

#21132 Make API method VisitFrequency.get working with multiple sites
  plugins/VisitFrequency/API.php
  tests/PHPUnit/System/TwoVisitorsTwoWebsitesDifferentDaysTest.php
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_NotLastNPeriods__VisitFrequency.get_day.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_NotLastNPeriods__VisitFrequency.get_month.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idsites__Goals.get_month.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idsites__VisitFrequency.get_month.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_idsites__VisitsSummary.get_month.xml
Labels: Needs Review

#21136 Translations update from Hosted Weblate
  lang/cs.json
  lang/eu.json
  lang/nl.json
  lang/sk.json
  lang/zh-tw.json
  plugins/Annotations/lang/cs.json
  plugins/CoreAdminHome/lang/zh-tw.json
  plugins/Events/lang/cs.json
  plugins/Login/lang/zh-tw.json
Labels: not-in-changelog, c: i18n

#21152 Fix qTip library to work without jquery browser
  plugins/UserCountryMap/javascripts/vendor/jquery.qtip.min.js
Labels: not-in-changelog, Regression

#21151 Fix possible php warning in Plugin class
  core/Plugin.php
Labels: not-in-changelog, Needs Review

#21157 Translations update from Hosted Weblate
  plugins/CoreAdminHome/lang/es.json
  plugins/CoreAdminHome/lang/fr.json
  plugins/ImageGraph/lang/cs.json
  plugins/SitesManager/lang/es.json
  plugins/SitesManager/lang/fr.json
  plugins/SitesManager/lang/it.json
  plugins/SitesManager/lang/nl.json
Labels: Task, not-in-changelog, c: i18n

#21146 [DEV-17076] Change translation key for Tour_AddWebsite and also the english translation
  plugins/Tour/Engagement/ChallengeAddedWebsite.php
  plugins/Tour/lang/en.json
  plugins/Tour/tests/System/expected/test___Tour.getChallenges.xml
  plugins/Tour/tests/UI/expected-screenshots/Tour_widget_complete_some_challenges.png
  plugins/Tour/tests/UI/expected-screenshots/Tour_widget_initial.png
  plugins/Tour/tests/UI/expected-screenshots/Tour_widget_none_completed.png
  plugins/Tour/tests/UI/expected-screenshots/Tour_widget_skipped_goal.png
  tests/PHPUnit/System/expected/test_BackwardsCompatibility1XTest__Tour.getChallenges.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Tour.getChallenges.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits__Tour.getChallenges.xml
  tests/PHPUnit/System/expected/test_noVisit_PeriodIsLast__Tour.getChallenges.xml
  tests/PHPUnit/System/expected/test_noVisit__Tour.getChallenges.xml
  tests/UI/expected-screenshots/Menus_mobile_left.png
  tests/UI/expected-screenshots/UIIntegrationTest_dashboard3.png
Labels: not-in-changelog, Needs Review

#21158 Backport translations update from Hosted Weblate (#21157)
  plugins/CoreAdminHome/lang/es.json
  plugins/CoreAdminHome/lang/fr.json
  plugins/ImageGraph/lang/cs.json
  plugins/SitesManager/lang/es.json
  plugins/SitesManager/lang/fr.json
  plugins/SitesManager/lang/it.json
  plugins/SitesManager/lang/nl.json
Labels: Task, not-in-changelog, c: i18n

#21167 In segment editor segment value input, bind to the actual value and not or condition object
  plugins/SegmentEditor/vue/dist/SegmentEditor.umd.js
  plugins/SegmentEditor/vue/dist/SegmentEditor.umd.min.js
  plugins/SegmentEditor/vue/src/SegmentGenerator/SegmentGenerator.vue
  plugins/SegmentEditor/vue/src/SegmentGenerator/ValueInput.vue
Labels: not-in-changelog, Regression

#21145 FIX Ensure visitor profile country name doesn't overflow
  plugins/Live/stylesheets/visitor_profile.less
Labels: not-in-changelog

#21178 Prefer using ellipsis char (…) over three dots (...) in translations
  lang/en.json
  plugins/Annotations/lang/en.json
  plugins/CorePluginsAdmin/lang/en.json
  plugins/CorePluginsAdmin/tests/UI/expected-screenshots/TagManagerTeaser_admin_page.png
  plugins/CorePluginsAdmin/tests/UI/expected-screenshots/TagManagerTeaser_superuser_page.png
  plugins/Dashboard/lang/en.json
  plugins/GeoIp2/lang/en.json
  plugins/PrivacyManager/lang/en.json
  plugins/SegmentEditor/lang/en.json
  tests/UI/expected-screenshots/EmptySite_Wordpress_emptySiteDashboard.png
  tests/UI/expected-screenshots/EvolutionGraph_annotation_edit_form.png
  tests/UI/expected-screenshots/EvolutionGraph_annotation_edit_submit.png
  tests/UI/expected-screenshots/EvolutionGraph_annotation_starred.png
  tests/UI/expected-screenshots/EvolutionGraph_annotations_all.png
  tests/UI/expected-screenshots/EvolutionGraph_annotations_none.png
  tests/UI/expected-screenshots/EvolutionGraph_annotations_single_period.png
  tests/UI/expected-screenshots/EvolutionGraph_export_image.png
  tests/UI/expected-screenshots/EvolutionGraph_new_annotation_form.png
  tests/UI/expected-screenshots/EvolutionGraph_new_annotation_submit.png
  tests/UI/expected-screenshots/OneClickLastForcedUpdate_login.png
  tests/UI/expected-screenshots/OneClickUpdate_login.png
Labels: not-in-changelog, c: i18n

#21176 Avoid checking for raw data if visits log is disabled
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/ReportingPage/ReportingPage.vue
  plugins/CoreVue/types/index.d.ts
Labels: not-in-changelog, Needs Review

#21192 In segment editor segment value input, bind to the actual value and not or condition object
  plugins/SegmentEditor/vue/dist/SegmentEditor.umd.js
  plugins/SegmentEditor/vue/dist/SegmentEditor.umd.min.js
  plugins/SegmentEditor/vue/src/SegmentGenerator/SegmentGenerator.vue
  plugins/SegmentEditor/vue/src/SegmentGenerator/ValueInput.vue
Labels: not-in-changelog, Regression

#21194 Fix (button) title when creating/updating a scheduled report
  plugins/ScheduledReports/vue/dist/ScheduledReports.umd.js
  plugins/ScheduledReports/vue/dist/ScheduledReports.umd.min.js
  plugins/ScheduledReports/vue/src/AddReport/AddReport.vue
  tests/UI/expected-screenshots/UIIntegrationTest_email_reports_editor.png
Labels: not-in-changelog, Needs Review

#21169 Disable API.getPagesComparisonsDisabledFor check in glossary widget
  plugins/API/API.php
Labels: not-in-changelog, Needs Review

#21189 Fix for unexpected zero value last edit dates in segment archiving
  core/CronArchive/SegmentArchiving.php
  tests/PHPUnit/Integration/CronArchive/SegmentArchivingTest.php
Labels: Bug, Needs Review

#21203 Fix for 'Label column not found in the table' error in archiving
  core/DataTable.php
  tests/PHPUnit/Unit/DataTableTest.php
Labels: Bug

#21190 Fix for unexpected zero value last edit dates in segment archiving 4.x
  core/CronArchive/SegmentArchiving.php
  tests/PHPUnit/Integration/CronArchive/SegmentArchivingTest.php
Labels: Bug, Needs Review
