Repository matomo-org/matomo, pull requests merged in 2023-04, with the labels that each got.

#20547 Declare Site Content Detector as API
  core/SiteContentDetector.php
Labels: Needs Review

#20541 Translations update from Hosted Weblate
  lang/nb.json
  lang/pl.json
  lang/sv.json
  lang/zh-tw.json
  plugins/API/lang/zh-tw.json
  plugins/Actions/lang/zh-tw.json
  plugins/Contents/lang/zh-tw.json
  plugins/CoreAdminHome/lang/sv.json
  plugins/CoreAdminHome/lang/zh-tw.json
  plugins/CoreHome/lang/pl.json
  plugins/CorePluginsAdmin/lang/pl.json
  plugins/CorePluginsAdmin/lang/sv.json
  plugins/CorePluginsAdmin/lang/zh-tw.json
  plugins/CoreUpdater/lang/sv.json
  plugins/CustomDimensions/lang/sv.json
  plugins/CustomJsTracker/lang/zh-tw.json
  plugins/DBStats/lang/zh-tw.json
  plugins/Dashboard/lang/zh-tw.json
  plugins/DevicesDetection/lang/zh-tw.json
  plugins/Diagnostics/lang/sv.json
  plugins/Ecommerce/lang/sv.json
  plugins/Goals/lang/sv.json
  plugins/Insights/lang/zh-tw.json
  plugins/Installation/lang/sv.json
  plugins/Installation/lang/zh-tw.json
  plugins/Live/lang/sv.json
  plugins/Live/lang/zh-tw.json
  plugins/Login/lang/sv.json
  plugins/Login/lang/zh-tw.json
  plugins/Marketplace/lang/sv.json
  plugins/Marketplace/lang/zh-tw.json
  plugins/MobileAppMeasurable/lang/zh-tw.json
  plugins/MobileMessaging/lang/sv.json
  plugins/MultiSites/lang/sv.json
  plugins/Overlay/lang/zh-tw.json
  plugins/PagePerformance/lang/zh-tw.json
  plugins/PrivacyManager/lang/sv.json
  plugins/PrivacyManager/lang/zh-tw.json
  plugins/Referrers/lang/zh-tw.json
  plugins/SEO/lang/sv.json
  plugins/SegmentEditor/lang/sv.json
  plugins/SegmentEditor/lang/zh-tw.json
  plugins/SitesManager/lang/sv.json
  plugins/Tour/lang/zh-tw.json
  plugins/Transitions/lang/sv.json
  plugins/TwoFactorAuth/lang/zh-tw.json
  plugins/UserCountry/lang/sv.json
  plugins/UserCountry/lang/zh-tw.json
  plugins/UserCountryMap/lang/zh-tw.json
  plugins/UserId/lang/sv.json
  plugins/UserId/lang/zh-tw.json
  plugins/UsersManager/lang/sv.json
  plugins/VisitFrequency/lang/zh-tw.json
  plugins/VisitTime/lang/zh-tw.json
  plugins/VisitorInterest/lang/fa.json
  plugins/VisitorInterest/lang/zh-tw.json
  plugins/Widgetize/lang/zh-tw.json
Labels: c: i18n

#20552 Run tests on PHP 8.2 instead of 8.1
  .github/workflows/matomo-tests.yml
  core/API/Proxy.php
  plugins/API/tests/Unit/HtmlRendererTest.php
  plugins/CoreAdminHome/tests/Unit/SetConfig/ConfigSettingManipulationTest.php
  plugins/PrivacyManager/tests/Framework/Mock/Config.php
  tests/PHPUnit/Unit/CliMulti/RequestParserTest.php
  tests/PHPUnit/Unit/TrackerTest.php
Labels: c: Tests & QA

#20560 Fix error message when UI asset can't be written
  core/AssetManager/UIAsset/OnDiskUIAsset.php
Labels: Bug, Needs Review

#20535 Ensure to reset role input when change confirmation is declined
  plugins/UsersManager/vue/dist/UsersManager.umd.js
  plugins/UsersManager/vue/dist/UsersManager.umd.min.js
  plugins/UsersManager/vue/src/UserPermissionsEdit/UserPermissionsEdit.vue
Labels: not-in-changelog, Needs Review, Stale

#20542 Improve method to generate segment test url
  plugins/SegmentEditor/javascripts/Segmentation.js
Labels: Needs Review, Stale

#20564 Fix PHP 8.2 deprecation warnings
  plugins/CoreHome/DataTableRowAction/RowEvolution.php
Labels: not-in-changelog, Needs Review

#20556 in SegmentGenerator convert autocomplete values to strings
  plugins/SegmentEditor/vue/dist/SegmentEditor.umd.js
  plugins/SegmentEditor/vue/dist/SegmentEditor.umd.min.js
  plugins/SegmentEditor/vue/src/SegmentGenerator/SegmentGenerator.vue
Labels: Needs Review, Stale

#20566 Added site detection for cloudflare and updated noData page to mention cloudflare
  core/SiteContentDetector.php
  plugins/CoreAdminHome/CoreAdminHome.php
  plugins/CoreAdminHome/lang/en.json
  plugins/CoreAdminHome/templates/trackingCodeGenerator.twig
  plugins/Installation/Controller.php
  plugins/Installation/tests/UI/expected-screenshots/Installation_js_tracking.png
  plugins/SitesManager/Controller.php
  plugins/SitesManager/SitesManager.php
  plugins/SitesManager/images/cloudflare-icon.png
  plugins/SitesManager/lang/en.json
  plugins/SitesManager/templates/_displayJavascriptCode.twig
  plugins/SitesManager/templates/_siteWithoutDataTabs.twig
  plugins/SitesManager/templates/_trackingCodeEmail.twig
  tests/PHPUnit/Fixtures/EmptySiteWithSiteContentDetectionCloudflare.php
  tests/PHPUnit/Unit/SiteContentDetectorTest.php
  tests/UI/expected-screenshots/EmptySite_Cloudflare_emptySiteDashboard.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_manage_tracking_code.png
  tests/UI/specs/EmptySite_Cloudflare_spec.js
Labels: Needs Review, BHAG-Tracking-OKR-Q2

#20573 Added site detection for cloudflare and updated noData page to mention cloudflare
  core/SiteContentDetector.php
  plugins/CoreAdminHome/CoreAdminHome.php
  plugins/CoreAdminHome/lang/en.json
  plugins/CoreAdminHome/templates/trackingCodeGenerator.twig
  plugins/Installation/Controller.php
  plugins/Installation/tests/UI/expected-screenshots/Installation_js_tracking.png
  plugins/SitesManager/Controller.php
  plugins/SitesManager/SitesManager.php
  plugins/SitesManager/images/cloudflare-icon.png
  plugins/SitesManager/lang/en.json
  plugins/SitesManager/templates/_displayJavascriptCode.twig
  plugins/SitesManager/templates/_siteWithoutDataTabs.twig
  plugins/SitesManager/templates/_trackingCodeEmail.twig
  tests/PHPUnit/Fixtures/EmptySiteWithSiteContentDetectionCloudflare.php
  tests/PHPUnit/Unit/SiteContentDetectorTest.php
  tests/UI/expected-screenshots/EmptySite_Cloudflare_emptySiteDashboard.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_manage_tracking_code.png
  tests/UI/specs/EmptySite_Cloudflare_spec.js
Labels: Needs Review

#20548 Custom Dimensions: Allow non-capturing groups in extraction regex
  plugins/CustomDimensions/Dimension/Extraction.php
  plugins/CustomDimensions/tests/Integration/Dimension/ExtractionTest.php
Labels: Enhancement, c: Custom Dimensions

#20565 when checking if a field is available in a segment's "from", check the field unaltered
  core/Segment/SegmentExpression.php
  tests/PHPUnit/Integration/SegmentTest.php
Labels: Needs Review

#20536 Ensure parameters expected to be provided as json are handled correctly
  core/Common.php
Labels: Needs Review, Stale

#20512 When aggregating non-day periods, only store one datatable and blob row in memory at a time
  core/Archive.php
  core/Archive/DataCollection.php
  core/ArchiveProcessor.php
  core/DataAccess/ArchiveSelector.php
  core/Segment.php
  tests/PHPUnit/Integration/DataAccess/ArchiveSelectorTest.php
  tests/PHPUnit/System/expected/test_DataComparisonTest_flat__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_invertCompare__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_labelFilter__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_multipleSites_multipleCompare__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_periods__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_rangePeriodAgainstSingle__Actions.getPageUrls_range.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_segmentsAndPeriods__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_segments__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_singleAgainstRange__Actions.getPageUrls_day.xml
  tests/PHPUnit/System/expected/test_DataComparisonTest_subtableActions__Actions.getPageUrls_month.xml
  tests/PHPUnit/System/expected/test_reportLimiting__Resolution.getConfiguration_month.xml
Labels: Needs Review, Stale

#20579 Improve brute force protection checks (#20543)
  plugins/Login/Login.php
Labels: c: Security

#20594 Ensure to populate log_action cache when archiving using DB Reader, not using the Writer
  core/Tracker/TableLogAction/Cache.php
Labels: Needs Review

#20595 support record names that end in ints (ie entity IDs) when aggregating one blob at a time
  core/ArchiveProcessor.php
  tests/PHPUnit/Integration/DataAccess/ArchiveSelectorTest.php
Labels: Needs Review, Regression

#20597 support record names that end in ints (ie entity IDs) when aggregating one blob at a time
  core/ArchiveProcessor.php
  tests/PHPUnit/Integration/DataAccess/ArchiveSelectorTest.php
Labels: not-in-changelog

#20606 Added GTM installation guide in no-data and tracking code pages
  plugins/CoreAdminHome/CoreAdminHome.php
  plugins/CoreAdminHome/lang/en.json
  plugins/CoreAdminHome/templates/trackingCodeGenerator.twig
  plugins/Installation/tests/UI/expected-screenshots/Installation_js_tracking.png
  plugins/SitesManager/Controller.php
  plugins/SitesManager/SitesManager.php
  plugins/SitesManager/images/google-tag-manager-icon.png
  plugins/SitesManager/lang/en.json
  plugins/SitesManager/templates/_displayJavascriptCode.twig
  plugins/SitesManager/templates/_gtmTabInstructions.twig
  plugins/SitesManager/templates/_siteWithoutDataTabs.twig
  tests/PHPUnit/Fixtures/EmptySiteWithSiteContentDetectionGTM.php
  tests/UI/expected-screenshots/EmptySite_GTM_emptySiteDashboard.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_manage_tracking_code.png
Labels: Needs Review

#20610 Removes deprecated javascript methods broadcast.init, broadcast.propagateAjax and broadcast.pageLoad
  CHANGELOG.md
  plugins/CoreHome/javascripts/broadcast.js
  plugins/Overlay/templates/index.twig
Labels: Needs Review

#20599 Improve type checking for the transitions getTransitionsForAction method
  plugins/Transitions/API.php
Labels: Bug, Needs Review, 5.0.0

#20631 Fix typo in bug report issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: not-in-changelog, Needs Review
