Repository matomo-org/matomo, pull requests merged in 2024-12, with the labels that each got.

#22804 Introduce javascript event to manipulate multisites dashboard KPIs
  plugins/MultiSites/Controller.php
  plugins/MultiSites/templates/allWebsitesDashboard.twig
  plugins/MultiSites/tests/UI/AllWebsitesDashboard_spec.js
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_dashboard.png
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_dashboard_all_badges.png
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_dashboard_kpi_badge.png
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_error.png
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_evolution_change.png
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_no_revenue.png
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_no_sparklines.png
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_widgetized.png
  plugins/MultiSites/vue/dist/MultiSites.umd.js
  plugins/MultiSites/vue/dist/MultiSites.umd.min.js
  plugins/MultiSites/vue/src/AllWebsitesDashboard/AllWebsitesDashboard.store.ts
  plugins/MultiSites/vue/src/AllWebsitesDashboard/AllWebsitesDashboard.vue
Labels: Needs Review

#22811 Sticky headers might break when resizing
  plugins/CoreHome/javascripts/dataTable.js
  tests/UI/specs/UIIntegration_spec.js
Labels: Bug

#22812 Translations update from Hosted Weblate
  plugins/Installation/lang/fi.json
  plugins/Marketplace/lang/el.json
  plugins/Marketplace/lang/ga.json
  plugins/Marketplace/lang/sq.json
Labels: not-in-changelog, c: i18n

#22824 Set table overflow only for the actual overflowing table
  plugins/CoreHome/javascripts/dataTable.js
Labels: not-in-changelog, Needs Review, Regression

#22822 prepare 5.2.0 RC1
  core/Version.php
Labels: not-in-changelog

#22826 Optimise dispatcher when list of plugins provided
  core/EventDispatcher.php
Labels: Needs Review

#22818 Prevent recomputing of metric metadata in EvolutionMetrics
  plugins/CoreHome/Columns/Metrics/EvolutionMetric.php
Labels: Needs Review

#22815 Improve performance of archive state detection
  core/Archive/ArchiveState.php
  tests/PHPUnit/Unit/Archive/ArchiveStateTest.php
Labels: c: Performance, Needs Review

#22825 Add IPv6 support for Matomo Installation
  plugins/Installation/FormDatabaseSetup.php
  plugins/Installation/HostPortExtractor.php
  plugins/Installation/tests/Unit/HostPortExtractorTest.php
Labels: Bug, Needs Review

#22835 Use terminal width independent "ps" command
  core/CliMulti/RequestParser.php
Labels: Bug, Needs Review, Stability

#22828 Translations update from Hosted Weblate
  lang/fi.json
  plugins/API/lang/sq.json
  plugins/CoreAdminHome/lang/fi.json
  plugins/CoreHome/lang/fi.json
  plugins/CorePluginsAdmin/lang/fi.json
  plugins/CorePluginsAdmin/lang/sq.json
  plugins/CoreUpdater/lang/fi.json
  plugins/CustomDimensions/lang/fi.json
  plugins/Dashboard/lang/fi.json
  plugins/DevicesDetection/lang/sq.json
  plugins/Diagnostics/lang/sq.json
  plugins/Feedback/lang/fi.json
  plugins/Feedback/lang/sq.json
  plugins/GeoIp2/lang/sq.json
  plugins/Goals/lang/fi.json
  plugins/Installation/lang/fi.json
  plugins/Live/lang/fi.json
  plugins/Login/lang/el.json
  plugins/Login/lang/fi.json
  plugins/Login/lang/ga.json
  plugins/Login/lang/sq.json
  plugins/Marketplace/lang/sq.json
  plugins/MobileMessaging/lang/fi.json
  plugins/PrivacyManager/lang/sq.json
  plugins/ProfessionalServices/lang/sq.json
  plugins/Referrers/lang/fi.json
  plugins/Resolution/lang/sq.json
  plugins/ScheduledReports/lang/fi.json
  plugins/SegmentEditor/lang/fi.json
  plugins/SitesManager/lang/fi.json
  plugins/SitesManager/lang/sq.json
  plugins/Tour/lang/fi.json
  plugins/Tour/lang/sq.json
  plugins/TwoFactorAuth/lang/fi.json
  plugins/UserCountry/lang/sq.json
  plugins/UserId/lang/sq.json
  plugins/UsersManager/lang/fi.json
  plugins/VisitFrequency/lang/fi.json
  plugins/VisitTime/lang/fi.json
  plugins/VisitorInterest/lang/sq.json
  plugins/VisitsSummary/lang/fi.json
  plugins/Widgetize/lang/sq.json
Labels: c: i18n

#22843 Update Version to 5.2.0
  core/Version.php
Labels: not-in-changelog

#22842 Show remove user icon only to admin users for pending users they invited
  plugins/UsersManager/vue/dist/UsersManager.umd.js
  plugins/UsersManager/vue/dist/UsersManager.umd.min.js
  plugins/UsersManager/vue/src/PagedUsersList/PagedUsersList.vue
Labels: Bug, Needs Review

#22844 Activate automated preview releases at 1am daily
  .github/workflows/release-preview.yml
  core/Version.php
Labels: not-in-changelog, Needs Review, Better processes

#22865 Allow to pass in secrets to test action
  .github/workflows/matomo-tests.yml
Labels: not-in-changelog, Needs Review

#22866 Ensure only translation keys are added to client side translations for menu entries
  plugins/CoreHome/CoreHome.php
Labels: not-in-changelog, Needs Review

#22862 Upgrade composer/semver
  composer.json
  composer.lock
Labels: dependencies

#22857 Translations update from Hosted Weblate
  lang/cs.json
  plugins/API/lang/de.json
  plugins/Insights/lang/fr.json
  plugins/Installation/lang/de.json
  plugins/Login/lang/de.json
  plugins/Marketplace/lang/de.json
  plugins/PrivacyManager/lang/fr.json
  plugins/Referrers/lang/fr.json
  plugins/SitesManager/lang/de.json
Labels: c: i18n

#22849 Use segment length to make dropdown responsive
  plugins/Morpheus/stylesheets/main.less
  plugins/SegmentEditor/stylesheets/segmentation.less
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_1_selector_open.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_deleted.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_enabled_create_realtime_segments_saved.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_saved.png
  plugins/SegmentEditor/tests/UI/expected-screenshots/SegmentSelectorEditorTest_updated.png
Labels: c: Design / UI, Needs Review

#22861 Allow newer versions of jshrink
  composer.json
  composer.lock
Labels: dependencies

#22874 Do not check password or user for scheduled preview releases
  .github/workflows/release-preview.yml
Labels: not-in-changelog, Needs Review, Better processes

#22837 Improves responsiveness of KPI widgets on new all websites dashboard
  plugins/MultiSites/images/kpi_divider_horizontal.svg
  plugins/MultiSites/tests/UI/AllWebsitesDashboard_spec.js
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_dashboard.png
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_dashboard_all_badges.png
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_dashboard_kpi_badge.png
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_dashboard_mobile.png
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_dashboard_mobile_no_revenue.png
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_dashboard_tablet.png
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_dashboard_tablet_no_revenue.png
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_error.png
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_evolution_change.png
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_no_revenue.png
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_no_sparklines.png
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_widgetized.png
  plugins/MultiSites/vue/dist/MultiSites.umd.js
  plugins/MultiSites/vue/dist/MultiSites.umd.min.js
  plugins/MultiSites/vue/src/AllWebsitesDashboard/AllWebsitesDashboard.less
  plugins/MultiSites/vue/src/AllWebsitesDashboard/KPICard.vue
Labels: not-in-changelog, c: Design / UI, Needs Review

#22872 Improve error visuals for All Websites Dashboard
  plugins/MultiSites/MultiSites.php
  plugins/MultiSites/lang/en.json
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_error.png
  plugins/MultiSites/vue/dist/MultiSites.umd.js
  plugins/MultiSites/vue/dist/MultiSites.umd.min.js
  plugins/MultiSites/vue/src/AllWebsitesDashboard/AllWebsitesDashboard.store.ts
  plugins/MultiSites/vue/src/AllWebsitesDashboard/AllWebsitesDashboard.vue
  plugins/MultiSites/vue/src/AllWebsitesDashboard/SitesTable.vue
Labels: c: Design / UI, Needs Review

#22885 Ensure empty plugin settings are saved correctly
  plugins/CorePluginsAdmin/SettingsMetadata.php
  plugins/CorePluginsAdmin/tests/Integration/ApiTest.php
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/PluginSettings/PluginSettings.vue
Labels: c: Usability, c: Design / UI, Needs Review, c: APIs, javascript

#22776 Integration tests for visitor id vs user id scenarios
  tests/PHPUnit/Fixtures/UITestFixture.php
  tests/PHPUnit/Integration/Tracker/UserIdVisitorIdTest.php
  tests/UI/specs/UserIdVisitorId_spec.js
  tests/resources/overlay-test-site/user-id-visitor-id.php
Labels: c: Tests & QA, not-in-changelog

#22892 Limit invalidations for hits metric to current month
  core/Updates/5.2.0-b6.php
Labels: Needs Review

#22894 Update Version to 5.2.1
  core/Version.php
Labels: not-in-changelog

#22891 Ensure empty plugin settings are saved correctly [5.x]
  plugins/CorePluginsAdmin/SettingsMetadata.php
  plugins/CorePluginsAdmin/tests/Integration/ApiTest.php
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/PluginSettings/PluginSettings.vue
Labels: not-in-changelog, Needs Review

#22893 Limit invalidations for hits metric to current month
  core/Updates/5.2.0-b6.php
Labels: not-in-changelog, Needs Review

#22723 Remove the calls to realpath in FileIntegrity checks
  core/FileIntegrity.php
Labels: Needs Review, Stale
