Repository matomo-org/matomo, pull requests merged in 2024-11, with the labels that each got.

#22740 Prevent unusable location provider from breaking the login process
  plugins/Login/Security/LoginFromDifferentCountryDetection.php
  plugins/Login/tests/Integration/Security/LoginFromAnotherCountryTest.php
Labels: Bug, not-in-changelog, Needs Review

#22733 [automatic composer updates]
  composer.lock
  plugins/CustomDimensions/tests/System/expected/test___ScheduledReports.generateReport_year.original.pdf
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_in_pdf_tables_only__ScheduledReports.generateReport_week.original.pdf
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_in_pdf_tables_only__ScheduledReports.generateReport_month.original.pdf
Labels: not-in-changelog, Needs Review

#22738 Move AWD date picker from the component to the top controls and adjust layout
  plugins/Morpheus/templates/dashboard.twig
  plugins/MultiSites/templates/allWebsitesDashboard.twig
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_dashboard.png
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_error.png
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_evolution_change.png
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_no_revenue.png
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_no_sparklines.png
  plugins/MultiSites/vue/dist/MultiSites.umd.js
  plugins/MultiSites/vue/dist/MultiSites.umd.min.js
  plugins/MultiSites/vue/src/AllWebsitesDashboard/AllWebsitesDashboard.less
  plugins/MultiSites/vue/src/AllWebsitesDashboard/AllWebsitesDashboard.vue
Labels: Enhancement, not-in-changelog, c: Design / UI, Needs Review

#22745 [automatic composer updates]
  composer.lock
Labels: Task, not-in-changelog

#22757 Fix typo in displayed migration command
  core/Updates/5.2.0-b6.php
Labels: Bug, not-in-changelog, Needs Review

#22729 Add more options for global URL parameter exclusions
  CHANGELOG.md
  config/global.ini.php
  plugins/IntranetMeasurable/tests/UI/expected-screenshots/IntranetMeasurable_intranet_create.png
  plugins/SitesManager/API.php
  plugins/SitesManager/Controller.php
  plugins/SitesManager/SitesManager.php
  plugins/SitesManager/lang/en.json
  plugins/SitesManager/stylesheets/SitesManager.less
  plugins/SitesManager/templates/globalSettings.twig
  plugins/SitesManager/tests/Integration/ApiTest.php
  plugins/SitesManager/tests/System/expected/test_SitesManager__SitesManager.getSiteSettings.xml
  plugins/SitesManager/tests/UI/SitesManager_spec.js
  plugins/SitesManager/tests/UI/expected-screenshots/SitesManager_global_settings.png
  plugins/SitesManager/tests/UI/expected-screenshots/SitesManager_global_url_param_exclusion_add_common.png
  plugins/SitesManager/tests/UI/expected-screenshots/SitesManager_global_url_param_exclusion_common_exclusions.png
  plugins/SitesManager/tests/UI/expected-screenshots/SitesManager_global_url_param_exclusion_custom.png
  plugins/SitesManager/tests/UI/expected-screenshots/SitesManager_global_url_param_exclusion_default.png
  plugins/SitesManager/tests/UI/expected-screenshots/SitesManager_site_edit_url.png
  plugins/SitesManager/vue/dist/SitesManager.umd.js
  plugins/SitesManager/vue/dist/SitesManager.umd.min.js
  plugins/SitesManager/vue/src/GlobalSettingsStore/GlobalSettings.ts
  plugins/SitesManager/vue/src/GlobalSettingsStore/GlobalSettingsStore.ts
  plugins/SitesManager/vue/src/ManageGlobalSettings/ExcludeQueryParameterSettings.vue
  plugins/SitesManager/vue/src/ManageGlobalSettings/ManageGlobalSettings.vue
  plugins/SitesManager/vue/src/index.ts
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getAvailableMeasurableTypes.xml
  tests/PHPUnit/Unit/DeprecatedMethodsTest.php
  tests/UI/expected-screenshots/MeasurableManager_add_measurable_view.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
Labels: Needs Review

#22759 [automatic composer updates]
  composer.lock
Labels: Task, not-in-changelog, dependencies

#22771 Move changelog record to correct version
  CHANGELOG.md
Labels: not-in-changelog, Needs Review

#22758 Translations update from Hosted Weblate
  lang/ca.json
  lang/fi.json
  lang/tr.json
  plugins/CoreAdminHome/lang/tr.json
  plugins/MobileMessaging/lang/tr.json
  plugins/SitesManager/lang/ar.json
  plugins/SitesManager/lang/el.json
  plugins/SitesManager/lang/ga.json
  plugins/SitesManager/lang/sq.json
  plugins/TwoFactorAuth/lang/tr.json
  plugins/UsersManager/lang/fi.json
  plugins/UsersManager/lang/tr.json
Labels: not-in-changelog, c: i18n

#22774 Changing a user visible text which had the name Piwik instead of Matomo
  plugins/MobileMessaging/SMSProvider/ASPSMS.php
Labels: not-in-changelog

#22781 Example code for setCustomRequestProcessing is not working anymore with encodedURI
  js/piwik.js
Labels: Needs Review

#22789 [automatic composer updates]
  composer.lock
Labels: not-in-changelog, dependencies

#22780 Fix overlay test that fails on the first day of the month / Fix overlay
  plugins/Overlay/tests/UI/Overlay_spec.js
  plugins/Overlay/tests/UI/expected-screenshots/Overlay_loaded_from_actions.png
Labels: c: Tests & QA, not-in-changelog, Needs Review

#22615 Show install all plugins button on Manage Plugins and License key section
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/InstallAllPaidPluginsButton/InstallAllPaidPluginsButton.vue
  plugins/CorePluginsAdmin/vue/src/PluginsIntro/PluginsIntro.vue
  plugins/CorePluginsAdmin/vue/src/index.ts
  plugins/Marketplace/Controller.php
  plugins/Marketplace/templates/overview.twig
  plugins/Marketplace/tests/UI/Marketplace_spec.js
  plugins/Marketplace/tests/UI/expected-screenshots/ManageLicense_valid.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_install_purchased_plugins_modal_manageLicenseKeyUrl_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_install_purchased_plugins_modal_managePluginsUrl_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_install_purchased_plugins_modal_paidPluginsUrl_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_with_license_manageLicenseKeyUrl_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_with_license_managePluginsUrl_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_with_license_paidPluginsUrl_superuser.png
  plugins/Marketplace/vue/dist/Marketplace.umd.js
  plugins/Marketplace/vue/dist/Marketplace.umd.min.js
  plugins/Marketplace/vue/src/InstallAllPaidPluginsButton/InstallAllPaidPluginsButton.vue
  plugins/Marketplace/vue/src/ManageLicenseKey/ManageLicenseKey.vue
  plugins/Marketplace/vue/src/OverviewIntro/OverviewIntro.vue
  plugins/Marketplace/vue/src/index.ts
Labels: Needs Review

#22797 Translations update from Hosted Weblate
  plugins/CoreAdminHome/lang/pl.json
  plugins/CoreAdminHome/lang/tr.json
  plugins/PrivacyManager/lang/fr.json
  plugins/SitesManager/lang/el.json
  plugins/SitesManager/lang/fr.json
  plugins/SitesManager/lang/tr.json
Labels: not-in-changelog, c: i18n

#22795 Ensure time strings are parsed relative to now time
  core/Tracker/Request.php
Labels: c: Tests & QA, Needs Review

#22750 Block installation if installation is older than 3 days
  core/Application/Kernel/EnvironmentValidator.php
  plugins/Diagnostics/Diagnostic/DatabaseAbilitiesCheck.php
  plugins/Diagnostics/Diagnostic/DbReaderCheck.php
  plugins/Diagnostics/Diagnostic/ForceSSLCheck.php
  plugins/Diagnostics/Diagnostic/NfsDiskCheck.php
  plugins/Installation/Controller.php
  plugins/Installation/lang/en.json
  plugins/Installation/tests/UI/Installation_spec.js
  plugins/Installation/tests/UI/expected-screenshots/Installation_already_installed.png
  plugins/Installation/tests/UI/expected-screenshots/Installation_db_existing.png
  plugins/Installation/tests/UI/expected-screenshots/Installation_expired.png
  plugins/UserCountry/Diagnostic/GeolocationDiagnostic.php
  tests/lib/screenshot-testing/support/page-renderer.js
  tests/lib/screenshot-testing/support/test-environment.js
Labels: Enhancement, c: Security, Needs Review

#22775 Adjust 2FA step 2 behaviour to move QR code into a modal
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/MatomoDialog/MatomoDialog.vue
  plugins/Morpheus/javascripts/piwikHelper.js
  plugins/TwoFactorAuth/TwoFactorAuth.php
  plugins/TwoFactorAuth/lang/en.json
  plugins/TwoFactorAuth/stylesheets/twofactorauth.less
  plugins/TwoFactorAuth/tests/UI/TwoFactorAuth_spec.js
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuth_twofa_forced_step2.png
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuth_twofa_forced_step2_showcodes.png
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuth_twofa_forced_step3.png
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuth_twofa_setup_step2.png
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuth_twofa_setup_step2_showcodes.png
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuth_twofa_setup_step3.png
  plugins/TwoFactorAuth/vue/dist/TwoFactorAuth.umd.js
  plugins/TwoFactorAuth/vue/dist/TwoFactorAuth.umd.min.js
  plugins/TwoFactorAuth/vue/src/SetupTwoFactorAuth/InstallOTPApp.vue
  plugins/TwoFactorAuth/vue/src/SetupTwoFactorAuth/SetupTwoFactorAuth.vue
Labels: Enhancement, c: Security, Needs Review

#22802 Fix CoreHome global property typing
  plugins/CoreVue/types/index.d.ts
Labels: Task, not-in-changelog, Needs Review

#22803 Correct EOL dates of PHP versions
  core/Plugin/ControllerAdmin.php
Labels: Needs Review

#22806 Manage subscription text updated to link to correct pages, #PG-3716
  plugins/Marketplace/Marketplace.php
  plugins/Marketplace/lang/en.json
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_subscription_overview_noLicense.png
  plugins/Marketplace/vue/dist/Marketplace.umd.js
  plugins/Marketplace/vue/dist/Marketplace.umd.min.js
  plugins/Marketplace/vue/src/SubscriptionOverview/SubscriptionOverview.vue
Labels: Needs Review
