Repository matomo-org/matomo, pull requests merged in 2024-05, with the labels that each got.

#22175 Fix incorrect number formatting in prettifyNumberOfDownloads function
  plugins/Marketplace/Plugins.php
  plugins/Marketplace/tests/Unit/PluginsTest.php
Labels: Bug, not-in-changelog, Needs Review

#22183 Add role attribute to parent unordered lists
  plugins/CoreHome/templates/_topBar.twig
Labels: c: Design / UI, Needs Review

#22171 DEV-17995 design review tweaks
  plugins/Marketplace/config/test.php
  plugins/Marketplace/stylesheets/plugin-details.less
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_free_plugin_details_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_free_plugin_details_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_free_plugin_details_user.png
  plugins/Marketplace/tests/resources/images/plugins/TreemapVisualization/images/1.0.1/Treemap.png
  plugins/Marketplace/tests/resources/images/plugins/TreemapVisualization/images/1.0.1/screen-resolution-treemap.png
  plugins/Marketplace/tests/resources/images/plugins/TreemapVisualization/images/1.0.1/social-network-treemap.png
  plugins/Marketplace/vue/dist/Marketplace.umd.js
  plugins/Marketplace/vue/dist/Marketplace.umd.min.js
  plugins/Marketplace/vue/src/PluginDetailsModal/PluginDetailsModal.vue
Labels: c: Marketplace, not-in-changelog, c: Design / UI, Needs Review

#22192 Fix bad JS imports
  plugins/Marketplace/vue/dist/Marketplace.umd.js
  plugins/Marketplace/vue/dist/Marketplace.umd.min.js
  plugins/Marketplace/vue/src/RequestTrial/RequestTrial.vue
  plugins/Marketplace/vue/src/StartFreeTrial/StartFreeTrial.vue
Labels: Bug, not-in-changelog, c: Design / UI, Regression

#22193 Increase version to b2
  core/Version.php
Labels: not-in-changelog, Needs Review

#22178 Display notification about not yet processed data also when visits log is disabled
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/lang/en.json
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/ReportingPage/ReportingPage.vue
  plugins/Live/API.php
  plugins/Live/Model.php
  plugins/Live/tests/System/ApiTest.php
  plugins/Live/tests/System/expected/test___Live.getMostRecentVisitsDateTime_day.xml
  plugins/Live/tests/System/expected/test___Live.getMostRecentVisitsDateTime_week.xml
  plugins/SitesManager/vue/dist/SitesManager.umd.js
  plugins/SitesManager/vue/dist/SitesManager.umd.min.js
  plugins/SitesManager/vue/src/SiteWithoutData/SiteWithoutData.vue
  tests/PHPUnit/System/PeriodIsRangeDateIsLastNMetadataAndNormalAPITest.php
  tests/UI/expected-screenshots/OnlyRawDataNotification_show_notification_when_only_raw_data_exists_no_visits_log.png
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
  tests/UI/specs/OnlyRawDataNotification_spec.js
Labels: Enhancement, Needs Review, Regression

#22202 Adjust preview channel condition
  .github/scripts/build-package.sh
  core/Version.php
  tests/PHPUnit/Unit/VersionTest.php
Labels: Task, Enhancement, not-in-changelog, Needs Review, Better processes

#22177 Translations update from Hosted Weblate
  plugins/CoreAdminHome/lang/de.json
  plugins/CoreAdminHome/lang/gu.json
  plugins/CoreAdminHome/lang/pt-br.json
  plugins/CoreAdminHome/lang/sv.json
  plugins/CorePluginsAdmin/lang/de.json
  plugins/CorePluginsAdmin/lang/gu.json
  plugins/CorePluginsAdmin/lang/pt-br.json
  plugins/CorePluginsAdmin/lang/sv.json
  plugins/Feedback/lang/gu.json
  plugins/Feedback/lang/tr.json
  plugins/Goals/lang/gu.json
  plugins/Installation/lang/es.json
  plugins/Login/lang/fr.json
  plugins/Marketplace/lang/ca.json
  plugins/Marketplace/lang/de.json
  plugins/Marketplace/lang/el.json
  plugins/Marketplace/lang/gu.json
  plugins/Marketplace/lang/pt-br.json
  plugins/Marketplace/lang/sv.json
  plugins/Marketplace/lang/tr.json
  plugins/PrivacyManager/lang/gu.json
  plugins/PrivacyManager/lang/sv.json
  plugins/ProfessionalServices/lang/de.json
  plugins/Referrers/lang/gu.json
  plugins/Referrers/lang/zh-tw.json
  plugins/SitesManager/lang/de.json
  plugins/SitesManager/lang/gu.json
  plugins/UsersManager/lang/de.json
  plugins/UsersManager/lang/gu.json
  plugins/UsersManager/lang/pt-br.json
  plugins/Widgetize/lang/bg.json
  plugins/Widgetize/lang/ca.json
  plugins/Widgetize/lang/el.json
  plugins/Widgetize/lang/gu.json
  plugins/Widgetize/lang/pt-br.json
  plugins/Widgetize/lang/sq.json
  plugins/Widgetize/lang/tr.json
Labels: not-in-changelog, c: i18n

#22200 [Test stability] Improve stability of Tracker\RequestSetTest
  tests/PHPUnit/Unit/Tracker/RequestSetTest.php
Labels: c: Tests & QA, not-in-changelog, Needs Review

#22217 Improve opt out compatibility with older browsers
  plugins/CoreAdminHome/OptOutManager.php
Labels: Needs Review

#22218 Adjust version compares for new preview release syntax
  .github/scripts/build-package.sh
  core/Version.php
  tests/PHPUnit/Unit/VersionTest.php
Labels: not-in-changelog, Needs Review

#22216 Translations update from Hosted Weblate
  plugins/CoreHome/lang/ca.json
  plugins/CoreHome/lang/pt-br.json
  plugins/Marketplace/lang/pt-br.json
Labels: not-in-changelog, c: i18n

#22214 Ignore "report_to_invalidate" for archive state detection
  core/Archive/ArchiveState.php
  tests/PHPUnit/Integration/Archive/ArchiveStateMetadataTest.php
  tests/PHPUnit/Unit/Archive/ArchiveStateTest.php
Labels: Bug, c: Performance, not-in-changelog, Needs Review, Regression

#22223 Ensure to correctly encode segment title for tooltips
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/Comparisons/Comparisons.vue
  plugins/SegmentEditor/javascripts/Segmentation.js
Labels: c: Security, Needs Review

#22229 Translations update from Hosted Weblate
  plugins/CoreHome/lang/gu.json
  plugins/PrivacyManager/lang/gu.json
Labels: not-in-changelog, c: i18n

#22231 Fix: skipping a Tour challenge shows an error message
  plugins/Tour/javascripts/engagement.js
Labels: Needs Review

#22225 Replace usage of SQL_CALC_FOUND_ROWS with separate queries
  core/Common.php
  plugins/UsersManager/Model.php
  plugins/UsersManager/tests/Integration/APITest.php
  tests/PHPUnit/Framework/Fixture.php
Labels: Needs Review

#22240 Add pure CSS Matomo loader
  plugins/CoreHome/CoreHome.php
  plugins/CoreHome/stylesheets/matomo-loader.less
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/ActivityIndicator/ActivityIndicator.vue
  plugins/CoreHome/vue/src/MatomoLoader/MatomoLoader.vue
  plugins/CoreHome/vue/src/index.ts
  plugins/Morpheus/stylesheets/uibase/_loading.less
Labels: Enhancement, c: Design / UI, Needs Review, Technical debt

#22239 Fix row evolution for reports where visits metric is not available
  plugins/API/RowEvolution.php
  plugins/Goals/tests/UI/Goals_spec.js
  plugins/Goals/tests/UI/expected-screenshots/Goals_goals_by_entry_page_titles_row_evolution.png
Labels: not-in-changelog, Needs Review

#22247 Improve WidgetizedDashboard UI tests to take less screenshots
  plugins/Dashboard/tests/UI/WidgetizedDashboard_spec.js
  plugins/Dashboard/tests/UI/expected-screenshots/WidgetizedDashboard_copied.png
  plugins/Dashboard/tests/UI/expected-screenshots/WidgetizedDashboard_create_new.png
  plugins/Dashboard/tests/UI/expected-screenshots/WidgetizedDashboard_invalid_token_auth.png
  plugins/Dashboard/tests/UI/expected-screenshots/WidgetizedDashboard_loaded_token_auth.png
  plugins/Dashboard/tests/UI/expected-screenshots/WidgetizedDashboard_removed.png
  plugins/Dashboard/tests/UI/expected-screenshots/WidgetizedDashboard_rename.png
  plugins/Dashboard/tests/UI/expected-screenshots/WidgetizedDashboard_reset.png
  plugins/Dashboard/tests/UI/expected-screenshots/WidgetizedDashboard_widget_move_removed.png
Labels: c: Tests & QA, not-in-changelog

#22228 Move Goal actions into single actions column
  plugins/Goals/tests/UI/expected-screenshots/GoalsPages_manage.png
  plugins/Goals/vue/dist/Goals.umd.js
  plugins/Goals/vue/dist/Goals.umd.min.js
  plugins/Goals/vue/src/ManageGoals/ManageGoals.vue
Labels: Needs Review

#22254 fix possible notice: `$optionalUserInfo` variable can be undefined in some cases
  core/Filechecks.php
Labels: Needs Review

#22251 Add entry to market new changes in funnel, #PG-3459
  plugins/ProfessionalServices/changes.json
Labels: Enhancement, c: Marketplace, c: Platform, not-in-changelog

#22234 Translations update from Hosted Weblate
  lang/pl.json
  plugins/CoreHome/lang/tr.json
  plugins/CoreHome/lang/zh-cn.json
  plugins/CorePluginsAdmin/lang/pl.json
  plugins/DevicesDetection/lang/pl.json
  plugins/Diagnostics/lang/ca.json
  plugins/Diagnostics/lang/el.json
  plugins/Installation/lang/ca.json
  plugins/Installation/lang/el.json
  plugins/Installation/lang/pl.json
  plugins/Installation/lang/tr.json
  plugins/Marketplace/lang/bg.json
  plugins/Marketplace/lang/ca.json
  plugins/Marketplace/lang/cs.json
  plugins/Marketplace/lang/da.json
  plugins/Marketplace/lang/de.json
  plugins/Marketplace/lang/el.json
  plugins/Marketplace/lang/es.json
  plugins/Marketplace/lang/eu.json
  plugins/Marketplace/lang/fa.json
  plugins/Marketplace/lang/fi.json
  plugins/Marketplace/lang/fr.json
  plugins/Marketplace/lang/gu.json
  plugins/Marketplace/lang/id.json
  plugins/Marketplace/lang/it.json
  plugins/Marketplace/lang/ja.json
  plugins/Marketplace/lang/nb.json
  plugins/Marketplace/lang/nl.json
  plugins/Marketplace/lang/pl.json
  plugins/Marketplace/lang/pt-br.json
  plugins/Marketplace/lang/pt.json
  plugins/Marketplace/lang/ro.json
  plugins/Marketplace/lang/ru.json
  plugins/Marketplace/lang/sk.json
  plugins/Marketplace/lang/sq.json
  plugins/Marketplace/lang/sr.json
  plugins/Marketplace/lang/sv.json
  plugins/Marketplace/lang/tl.json
  plugins/Marketplace/lang/tr.json
  plugins/Marketplace/lang/uk.json
  plugins/Marketplace/lang/zh-cn.json
  plugins/Marketplace/lang/zh-tw.json
  plugins/SitesManager/lang/pl.json
  plugins/TwoFactorAuth/lang/pl.json
  plugins/UserCountryMap/lang/pl.json
  plugins/UsersManager/lang/pl.json
  plugins/VisitorInterest/lang/pl.json
Labels: not-in-changelog, c: i18n

#22243 Added code to escape hover text in SiteSelector, AS-301
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/SiteSelector/SiteSelector.vue
Labels: Needs Review

#22208 Check privilege sql has been successful on install script
  plugins/Installation/FormDatabaseSetup.php
Labels: Needs Review

#22252 Improve handling of database port during installation process
  core/Db/Adapter.php
  core/Db/Adapter/Mysqli.php
  core/Db/Adapter/Pdo/Mysql.php
  core/Db/AdapterInterface.php
  core/Db/Schema.php
  core/Db/Schema/Mysql.php
  core/Db/Schema/Tidb.php
  core/Db/SchemaInterface.php
  plugins/Diagnostics/Diagnostic/DbAdapterCheck.php
  plugins/Installation/FormDatabaseSetup.php
Labels: not-in-changelog, Needs Review

#22256 Fix possible PHP deprecation notice
  core/Tracker/VisitExcluded.php
  core/UrlHelper.php
Labels: not-in-changelog, Needs Review

#22257 Improve marketplace UI tests
  plugins/Marketplace/tests/UI/Marketplace_spec.js
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_subscription_overview_exceededLicense.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_subscription_overview_expiredLicense.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_subscription_overview_noLicense.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_subscription_overview_validLicense.png
Labels: c: Marketplace, c: Tests & QA, not-in-changelog, Needs Review

#22258 Translations update from Hosted Weblate
  plugins/CoreHome/lang/de.json
  plugins/Diagnostics/lang/pt-br.json
  plugins/Installation/lang/de.json
  plugins/Installation/lang/pt-br.json
  plugins/Marketplace/lang/ca.json
  plugins/Marketplace/lang/de.json
  plugins/Marketplace/lang/pt-br.json
  plugins/Widgetize/lang/de.json
Labels: not-in-changelog, c: i18n

#22261 Update feature gate image for funnels
  plugins/ProfessionalServices/images/ad-funnels.png
  plugins/ProfessionalServices/tests/UI/expected-screenshots/ProfessionalServices_PluginPromo_promo_funnels.png
Labels: Needs Review
