Repository matomo-org/matomo, pull requests merged in 2024-02, with the labels that each got.

#21863 Fix sorting for ecommerce item reports
  plugins/Ecommerce/tests/System/EcommerceOrderWithItemsTest.php
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_productSkuSegmentSorted__Goals.getItemsCategory_week.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_productSkuSegmentSorted__Goals.getItemsName_week.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_productSkuSegmentSorted__Goals.getItemsSku_week.xml
  plugins/Goals/API.php
Labels: Bug, Needs Review

#21861 SystemTestsCore: fix ImportLogsTest race condition on visits with identical date/time
  tests/PHPUnit/System/expected/test_ImportLogs__Live.getLastVisitsDetails_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs_complexActionSegment__Live.getLastVisitsDetails_month.xml
  tests/resources/access-logs/fake_logs_enable_all.log
Labels: c: Tests & QA, not-in-changelog, Needs Review, Technical debt

#21864 Check parameters for scheduled report sending early
  plugins/ScheduledReports/API.php
  plugins/ScheduledReports/tests/Integration/ApiTest.php
Labels: Needs Review, Technical debt

#21865 Check parameters for scheduled report sending early (4.x)
  plugins/ScheduledReports/API.php
  plugins/ScheduledReports/tests/Integration/ApiTest.php
Labels: Needs Review, Technical debt

#21850 [Coding Style] Enable rules PSR2.Methods.FunctionCallSignature.Space*
  core/API/DataTablePostProcessor.php
  core/Access.php
  core/Archive/DataTableFactory.php
  core/Concurrency/Lock.php
  core/CronArchive.php
  core/DataTable/Renderer/Console.php
  core/Http.php
  core/Option.php
  core/Period/Year.php
  core/Plugin/ConsoleCommand.php
  core/SettingsServer.php
  core/Twig.php
  core/Updater.php
  core/Updates/2.0.4-b5.php
  phpcs.xml
  plugins/API/Glossary.php
  plugins/CoreAdminHome/Commands/DeleteLogsData.php
  plugins/CoreHome/DataTableRowAction/RowEvolution.php
  plugins/CustomDimensions/Controller.php
  plugins/Diagnostics/Diagnostic/PhpInformational.php
  plugins/Events/API.php
  plugins/Installation/Widgets/GetSystemCheck.php
  plugins/LanguagesManager/tests/Integration/LanguagesManagerTest.php
  plugins/LanguagesManager/tests/Unit/TranslationWriter/Validate/CoreTranslationsTest.php
  plugins/Live/tests/System/ApiCounterTest.php
  plugins/PrivacyManager/tests/Integration/DataPurgingTest.php
  plugins/PrivacyManager/tests/Unit/DoNotTrackHeaderCheckerTest.php
  plugins/Referrers/tests/System/ApiTest.php
  plugins/ScheduledReports/tests/Integration/ApiTest.php
  plugins/SitesManager/Model.php
  plugins/Transitions/API.php
  plugins/UsersManager/tests/System/ApiTest.php
  plugins/VisitorInterest/Reports/GetNumberOfVisitsByVisitCount.php
  tests/PHPUnit/Fixtures/ManyVisitsWithGeoIP.php
  tests/PHPUnit/Fixtures/SomeVisitsCustomVariablesCampaignsNotHeuristics.php
  tests/PHPUnit/Fixtures/TwoSitesTwoVisitorsDifferentDays.php
  tests/PHPUnit/Framework/TestRequest/Collection.php
  tests/PHPUnit/Integration/EmailValidatorTest.php
  tests/PHPUnit/Integration/ReleaseCheckListTest.php
  tests/PHPUnit/Integration/UpdaterTest.php
  tests/PHPUnit/System/CliMultiTest.php
  tests/PHPUnit/Unit/DataTable/Filter/ColumnDeleteTest.php
  tests/PHPUnit/Unit/DataTable/Renderer/ConsoleTest.php
  tests/PHPUnit/Unit/DataTableTest.php
Labels: c: Tests & QA, not-in-changelog, Needs Review, Technical debt

#21870 Ensure old ecommerce item data is handled correctly
  plugins/Goals/API.php
Labels: not-in-changelog, Needs Review

#21835 Translations update from Hosted Weblate
  lang/ca.json
  lang/el.json
  lang/eu.json
  lang/pt-br.json
  lang/pt.json
  lang/sv.json
  lang/tr.json
  plugins/Actions/lang/gu.json
  plugins/Marketplace/lang/ca.json
  plugins/Marketplace/lang/el.json
  plugins/Marketplace/lang/pt-br.json
  plugins/Marketplace/lang/sv.json
  plugins/Marketplace/lang/tr.json
  plugins/ProfessionalServices/lang/de.json
  plugins/ProfessionalServices/lang/sv.json
  plugins/SitesManager/lang/pt.json
Labels: not-in-changelog, c: i18n

#21880 Fix annotation icon placement for "lastX"/"previousX" ranges (4.x)
  plugins/Annotations/Annotations.php
  plugins/Annotations/tests/System/AnnotationsTest.php
  plugins/Annotations/tests/System/expected/test_annotations_last30__Annotations.getAll_range.xml
  plugins/Annotations/tests/System/expected/test_annotations_last30__Annotations.getAnnotationCountForDates_range.xml
Labels: Bug

#21872 Update workflow with actions/checkout@v3 to actions/checkout@v4
  .github/workflows/buildtrackerjs.yml
  .github/workflows/buildvue.yml
  .github/workflows/buildwoff2.yml
  .github/workflows/composer-update.yml
  .github/workflows/matomo-tests.yml
  .github/workflows/phpcs.yml
  .github/workflows/release.yml
  .github/workflows/stylelinter.yml
  .github/workflows/submodules.yml
  .github/workflows/update-font.yml
  .github/workflows/update-intl.yml
Labels: Task, c: Tests & QA, Needs Review, Technical debt

#21887 Ensure to only abort the loading request for a popover when closing it
  plugins/CoreHome/javascripts/popover.js
Labels: Bug, Needs Review

#21900 Making some changes to help plugins that extend the Goals view
  plugins/Goals/vue/dist/Goals.umd.js
  plugins/Goals/vue/dist/Goals.umd.min.js
  plugins/Goals/vue/src/ManageGoals/ManageGoals.vue
Labels: Task, c: Platform, not-in-changelog

#21896 Decouple Tracking Code Generator from Overlay plugin
  CHANGELOG.md
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.js
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.min.js
  plugins/CoreAdminHome/vue/src/JsTrackingCodeGenerator/JsTrackingCodeAdvancedOptions.vue
  plugins/Overlay/API.php
  plugins/Overlay/javascripts/Piwik_Overlay.js
  plugins/SitesManager/API.php
  tests/PHPUnit/Unit/DeprecatedMethodsTest.php
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
Labels: Bug, Needs Review

#21913 Added code to allow empty passwordConfirmation value by default for skipPasswordConfiirmation action to work without password
  plugins/TwoFactorAuth/API.php
  plugins/TwoFactorAuth/tests/Integration/APITest.php
Labels: Needs Review

#21876 Send a notification mail to all super users when anonymous access is enabled
  plugins/CoreAdminHome/Emails/AnonymousAccessEnabledEmail.php
  plugins/CoreAdminHome/lang/en.json
  plugins/UsersManager/API.php
Labels: c: Security, Needs Review

#21897 Filter special whitespace when rendering ImageGraphs without unifont
  plugins/ImageGraph/StaticGraph.php
  plugins/ImageGraph/tests/UI/ImageGraph_spec.js
  plugins/ImageGraph/tests/UI/expected-screenshots/ImageGraph_evolution_graph_week.png
Labels: Bug, not-in-changelog, c: Design / UI, Needs Review

#21871 Require password confirmation for giving anonymous user view access
  plugins/UsersManager/API.php
  plugins/UsersManager/tests/Integration/APITest.php
  plugins/UsersManager/vue/dist/UsersManager.umd.js
  plugins/UsersManager/vue/dist/UsersManager.umd.min.js
  plugins/UsersManager/vue/src/PagedUsersList/PagedUsersList.vue
  plugins/UsersManager/vue/src/UsersManager/UsersManager.vue
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
Labels: Enhancement, c: Security, Needs Review

#21918 Fix failing API request in Overlay
  plugins/Overlay/client/client.js
  plugins/Overlay/client/followingpages.js
  plugins/Overlay/client/translations.js
Labels: not-in-changelog, Needs Review, Regression

#21917 Never show changes older than 6 months in What's new popover
  core/Changes/Model.php
  plugins/CoreHome/tests/Integration/ChangesTest.php
  tests/PHPUnit/Fixtures/CreateChanges.php
Labels: Enhancement, not-in-changelog, Needs Review

#21886 Show search engine names in Transitions instead of keywords
  plugins/Transitions/API.php
  plugins/Transitions/tests/System/expected/test_Transitions__Transitions.getTransitionsForPageUrl_day.xml
  plugins/Transitions/tests/System/expected/test_Transitions__Transitions.getTransitionsForPageUrl_month.xml
  plugins/Transitions/tests/System/expected/test_Transitions_noLimit__Transitions.getTransitionsForPageTitle_day.xml
  plugins/Transitions/tests/System/expected/test_Transitions_noLimit__Transitions.getTransitionsForPageTitle_month.xml
  plugins/Transitions/tests/System/expected/test_Transitions_noLimit__Transitions.getTransitionsForPageUrl_day.xml
  plugins/Transitions/tests/System/expected/test_Transitions_noLimit__Transitions.getTransitionsForPageUrl_month.xml
  plugins/Transitions/tests/System/expected/test_Transitions_withSegment__Transitions.getTransitionsForPageTitle_day.xml
  plugins/Transitions/tests/System/expected/test_Transitions_withSegment__Transitions.getTransitionsForPageUrl_day.xml
  plugins/Transitions/tests/UI/Transitions_spec.js
  plugins/Transitions/tests/UI/expected-screenshots/Transitions_transitions_report_search_engines.png
Labels: Enhancement, Needs Review

#21916 Improve password confirmation for passwordless authentication
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/PasswordConfirmation/PasswordConfirmation.vue
  plugins/CorePluginsAdmin/vue/src/PluginSettings/PluginSettings.vue
  plugins/PrivacyManager/tests/UI/PrivacyManager_spec.js
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_anonymizelogdata_anonymizeip_and_visit_column_confirmation_message.png
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.js
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.min.js
  plugins/PrivacyManager/vue/src/AnonymizeLogData/AnonymizeLogData.vue
  plugins/PrivacyManager/vue/src/DeleteOldLogs/DeleteOldLogs.vue
  plugins/PrivacyManager/vue/src/DeleteOldReports/DeleteOldReports.vue
  plugins/PrivacyManager/vue/src/ScheduleReportDeletion/ScheduleReportDeletion.vue
  plugins/SitesManager/vue/dist/SitesManager.umd.js
  plugins/SitesManager/vue/dist/SitesManager.umd.min.js
  plugins/SitesManager/vue/src/SiteFields/SiteFields.vue
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuthUsersManager_edit_with_2fa_reset_confirm.png
  plugins/UsersManager/UsersManager.php
  plugins/UsersManager/lang/en.json
  plugins/UsersManager/tests/UI/expected-screenshots/UserSettings_asks_confirmation.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_delete_bulk_confirm.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_delete_single_confirm.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_edit_user_basic_asks_confirmation.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_invite_confirm.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_superuser_confirm.png
  plugins/UsersManager/vue/dist/UsersManager.umd.js
  plugins/UsersManager/vue/dist/UsersManager.umd.min.js
  plugins/UsersManager/vue/src/PagedUsersList/PagedUsersList.vue
  plugins/UsersManager/vue/src/PersonalSettings/PersonalSettings.vue
  plugins/UsersManager/vue/src/UserEditForm/UserEditForm.vue
  plugins/UsersManager/vue/src/UsersManager/UsersManager.vue
Labels: Enhancement, c: Usability, Needs Review

#21938 Update expected ecommerce scheduled reports
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_html_row_evolution_graph__ScheduledReports.generateReport_week.original.html
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_html_row_evolution_prevCustomN__ScheduledReports.generateReport_week.original.html
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_html_tables_and_graph__ScheduledReports.generateReport_week.original.html
Labels: c: Tests & QA, not-in-changelog, Needs Review, Regression

#21879 Allow for marketplace provided plugin cover images
  plugins/Marketplace/Plugins.php
  plugins/Marketplace/config/test.php
  plugins/Marketplace/images/categories/matomo.png
  plugins/Marketplace/images/categories/uncategorised.png
  plugins/Marketplace/stylesheets/marketplace.less
  plugins/Marketplace/templates/plugin-list.twig
  plugins/Marketplace/tests/Integration/PluginsTest.php
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_no_license_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_no_license_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_no_license_user.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_with_exceeded_license_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_with_exceeded_license_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_with_exceeded_license_user.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_with_license_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_with_license_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_with_license_user.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_superuser_enable_plugins_admin.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_superuser_enable_plugins_admin_with_multiserver_enabled.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_superuser_invalid_license_key_entered.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_superuser_remove_license_key_confirmed.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_superuser_valid_license_key_entered.png
  plugins/Marketplace/tests/resources/images/categories/customisation.png
  plugins/Marketplace/tests/resources/images/categories/matomo.png
  plugins/Marketplace/tests/resources/images/categories/uncategorised.png
  plugins/Marketplace/tests/resources/images/plugins/TreemapVisualization/images/1.0.1/_cover.png
  plugins/Marketplace/tests/resources/v2.0_consumer-access_token-consumer1_paid2_custom1.json
  plugins/Marketplace/tests/resources/v2.0_consumer-access_token-consumer2_paid1.json
  plugins/Marketplace/tests/resources/v2.0_consumer-access_token-consumer3_paid1_custom2.json
  plugins/Marketplace/tests/resources/v2.0_consumer-access_token-notexistingtoken.json
  plugins/Marketplace/tests/resources/v2.0_consumer-access_token-validbutnolicense.json
  plugins/Marketplace/tests/resources/v2.0_consumer-num_users-201-access_token-consumer1_paid2_custom1.json
  plugins/Marketplace/tests/resources/v2.0_consumer_validate-access_token-consumer1_paid2_custom1.json
  plugins/Marketplace/tests/resources/v2.0_consumer_validate-access_token-consumer2_paid1.json
  plugins/Marketplace/tests/resources/v2.0_consumer_validate-access_token-consumer3_paid1_custom2.json
  plugins/Marketplace/tests/resources/v2.0_consumer_validate-access_token-notexistingtoken.json
  plugins/Marketplace/tests/resources/v2.0_consumer_validate-access_token-validbutnolicense.json
  plugins/Marketplace/tests/resources/v2.0_consumer_validate.json
  plugins/Marketplace/tests/resources/v2.0_info.json
  plugins/Marketplace/tests/resources/v2.0_plugins-purchase_type-paid-access_token-consumer1_paid2_custom1.json
  plugins/Marketplace/tests/resources/v2.0_plugins-purchase_type-paid-access_token-consumer2_paid1.json
  plugins/Marketplace/tests/resources/v2.0_plugins-purchase_type-paid-access_token-notexistingtoken.json
  plugins/Marketplace/tests/resources/v2.0_plugins-purchase_type-paid-num_users-201-access_token-consumer1_paid2_custom1.json
  plugins/Marketplace/tests/resources/v2.0_plugins-purchase_type-paid-num_users-201-access_token-consumer2_paid1.json
  plugins/Marketplace/tests/resources/v2.0_plugins-query-nomatchforthisquery.json
  plugins/Marketplace/tests/resources/v2.0_plugins.json
  plugins/Marketplace/tests/resources/v2.0_plugins_Barometer_info.json
  plugins/Marketplace/tests/resources/v2.0_plugins_CustomPlugin1_info-access_token-notexistingtoken.json
  plugins/Marketplace/tests/resources/v2.0_plugins_PaidPlugin1_info-access_token-consumer3_paid1_custom2.json
  plugins/Marketplace/tests/resources/v2.0_plugins_PaidPlugin1_info-purchase_type-paid-num_users-201-access_token-consumer2_paid1.json
  plugins/Marketplace/tests/resources/v2.0_plugins_PaidPlugin1_info.json
  plugins/Marketplace/tests/resources/v2.0_plugins_TreemapVisualization_info.json
  plugins/Marketplace/tests/resources/v2.0_plugins_checkUpdates-pluginspluginsnameAnonymousPi.json
  plugins/Marketplace/tests/resources/v2.0_themes.json
Labels: Enhancement, Needs Review

#21940 Include date in CLI logging
  plugins/Monolog/config/cli.php
Labels: not-in-changelog, Needs Review

#21813 Determine incomplete/invalidated periods for evolution graphs
  core/API/DataTablePostProcessor.php
  core/Archive.php
  core/Archive/ArchiveInvalidator.php
  core/Archive/ArchiveState.php
  core/DataAccess/ArchiveSelector.php
  core/DataTable.php
  core/DataTable/Row.php
  plugins/CoreVisualizations/JqplotDataGenerator/Evolution.php
  plugins/CoreVisualizations/Visualizations/JqplotGraph/Evolution.php
  plugins/MultiSites/API.php
  tests/PHPUnit/Integration/Archive/ArchiveStateMetadataTest.php
  tests/PHPUnit/Integration/DataAccess/ArchiveInvalidatorTest.php
  tests/PHPUnit/Integration/DataAccess/ArchiveSelectorTest.php
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_Conversions_MultiSites.getAll_firstSite_lastN__API.getProcessedReport_day.xml
  tests/PHPUnit/Unit/Archive/ArchiveStateTest.php
Labels: c: Design / UI, Needs Review, c: Better Graphs

#21920 Connect marketplace and "Start Free Trial" CTA
  plugins/CorePluginsAdmin/CorePluginsAdmin.php
  plugins/CorePluginsAdmin/lang/en.json
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/Plugins/PluginStartFreeTrial.ts
  plugins/CorePluginsAdmin/vue/src/index.ts
  plugins/CoreVue/types/index.d.ts
  plugins/Marketplace/API.php
  plugins/Marketplace/Api/Service.php
  plugins/Marketplace/Plugins.php
  plugins/Marketplace/config/test.php
  plugins/Marketplace/templates/macros.twig
  plugins/Marketplace/templates/plugin-list.twig
  plugins/Marketplace/tests/Framework/Mock/Service.php
  plugins/Marketplace/tests/Integration/ApiTest.php
  plugins/Marketplace/tests/Integration/PluginsTest.php
  plugins/Marketplace/tests/UI/Marketplace_StartFreeTrial_spec.js
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_no_license_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_no_license_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_no_license_user.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_with_exceeded_license_user.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_with_license_user.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_superuser_enable_plugins_admin.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_superuser_enable_plugins_admin_with_multiserver_enabled.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_superuser_invalid_license_key_entered.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_superuser_remove_license_key_confirmed.png
Labels: Enhancement, c: Marketplace, Needs Review

#21954 Add class wrappers to use Syslog dependency instead of using directly
  plugins/Monolog/Handler/ErrorLogHandler.php
  plugins/Monolog/Handler/SyslogHandler.php
  plugins/Monolog/config/config.php
Labels: c: Platform, not-in-changelog

#21958 Prevent role change password confirmation if anonymous user is not involved
  plugins/UsersManager/tests/Fixtures/AnonymousUser.php
  plugins/UsersManager/tests/UI/UsersManager_AnonymousUser_spec.js
  plugins/UsersManager/vue/dist/UsersManager.umd.js
  plugins/UsersManager/vue/dist/UsersManager.umd.min.js
  plugins/UsersManager/vue/src/PagedUsersList/PagedUsersList.vue
Labels: Bug, c: Security, not-in-changelog, Needs Review, Regression

#21892 Translations update from Hosted Weblate
  lang/fr.json
  lang/nb.json
  lang/sq.json
  lang/zh-tw.json
  plugins/Actions/lang/gu.json
  plugins/CoreAdminHome/lang/ca.json
  plugins/CoreAdminHome/lang/el.json
  plugins/CoreAdminHome/lang/nb.json
  plugins/CoreAdminHome/lang/sq.json
  plugins/CoreAdminHome/lang/sv.json
  plugins/CoreAdminHome/lang/tr.json
  plugins/CoreAdminHome/lang/zh-tw.json
  plugins/CorePluginsAdmin/lang/ca.json
  plugins/CorePluginsAdmin/lang/el.json
  plugins/CorePluginsAdmin/lang/gu.json
  plugins/CorePluginsAdmin/lang/sq.json
  plugins/CorePluginsAdmin/lang/sv.json
  plugins/CorePluginsAdmin/lang/tr.json
  plugins/CoreUpdater/lang/gu.json
  plugins/CustomDimensions/lang/gu.json
  plugins/CustomDimensions/lang/sq.json
  plugins/Dashboard/lang/sq.json
  plugins/Diagnostics/lang/gu.json
  plugins/Diagnostics/lang/sq.json
  plugins/Diagnostics/lang/zh-tw.json
  plugins/Feedback/lang/zh-cn.json
  plugins/Goals/lang/sq.json
  plugins/Installation/lang/sq.json
  plugins/JsTrackerInstallCheck/lang/sq.json
  plugins/Live/lang/gu.json
  plugins/Login/lang/fr.json
  plugins/Login/lang/sq.json
  plugins/Marketplace/lang/gu.json
  plugins/Marketplace/lang/sq.json
  plugins/Marketplace/lang/zh-tw.json
  plugins/MobileMessaging/lang/gu.json
  plugins/PagePerformance/lang/gu.json
  plugins/PrivacyManager/lang/sq.json
  plugins/ProfessionalServices/lang/gu.json
  plugins/ScheduledReports/lang/sq.json
  plugins/SegmentEditor/lang/sq.json
  plugins/SitesManager/lang/sq.json
  plugins/Tour/lang/fr.json
  plugins/Tour/lang/sq.json
  plugins/UsersManager/lang/ca.json
  plugins/UsersManager/lang/el.json
  plugins/UsersManager/lang/sq.json
  plugins/UsersManager/lang/sv.json
  plugins/UsersManager/lang/tr.json
Labels: Task, not-in-changelog, c: i18n

#21951 Migrates Marketplace to vue.js & adds modal when trialing a plugin without license
  plugins/CorePluginsAdmin/templates/macros.twig
  plugins/CorePluginsAdmin/templates/plugins.twig
  plugins/CorePluginsAdmin/templates/themes.twig
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/Plugins/PluginStartFreeTrial.ts
  plugins/CorePluginsAdmin/vue/src/index.ts
  plugins/CoreUpdater/templates/newVersionAvailable.twig
  plugins/Marketplace/API.php
  plugins/Marketplace/Controller.php
  plugins/Marketplace/Input/Mode.php
  plugins/Marketplace/Input/PurchaseType.php
  plugins/Marketplace/Input/Sort.php
  plugins/Marketplace/Marketplace.php
  plugins/Marketplace/stylesheets/marketplace.less
  plugins/Marketplace/templates/macros.twig
  plugins/Marketplace/templates/overview.twig
  plugins/Marketplace/templates/plugin-list.twig
  plugins/Marketplace/tests/UI/Marketplace_StartFreeTrial_spec.js
  plugins/Marketplace/tests/UI/Marketplace_spec.js
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_no_license_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_no_license_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_superuser_enable_plugins_admin.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_superuser_enable_plugins_admin_with_multiserver_enabled.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_superuser_invalid_license_key_entered.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_superuser_remove_license_key_confirmed.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_superuser_valid_license_key_entered.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_themes_with_valid_license_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_themes_with_valid_license_superuser.png
  plugins/Marketplace/vue/dist/Marketplace.umd.js
  plugins/Marketplace/vue/dist/Marketplace.umd.min.js
  plugins/Marketplace/vue/src/Marketplace/Marketplace.vue
  plugins/Marketplace/vue/src/OverviewIntro/OverviewIntro.vue
  plugins/Marketplace/vue/src/PluginList/CTAContainer.vue
  plugins/Marketplace/vue/src/PluginList/DownloadButton.vue
  plugins/Marketplace/vue/src/PluginList/HelpLink.vue
  plugins/Marketplace/vue/src/PluginList/MoreDetailsButton.vue
  plugins/Marketplace/vue/src/PluginList/PluginList.vue
  plugins/Marketplace/vue/src/StartFreeTrial/StartFreeTrial.vue
  plugins/Marketplace/vue/src/index.ts
Labels: Enhancement, c: Marketplace, c: Usability, c: Design / UI, Needs Review, Technical debt

#21977 Update test expectations
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_browserName__API.getSuggestedValuesForSegment.xml
  plugins/Marketplace/tests/UI/Marketplace_StartFreeTrial_spec.js
  tests/PHPUnit/Integration/Tracker/VisitTest.php
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getSegmentsMetadata.xml
Labels: c: Tests & QA, not-in-changelog

#21925 Improve handling of float request values
  core/Common.php
  core/Request.php
  tests/PHPUnit/Unit/CommonTest.php
  tests/PHPUnit/Unit/RequestTest.php
Labels: Bug, Needs Review, c: Data Integrity & Accuracy
