Repository matomo-org/matomo, pull requests merged in 2024-08, with the labels that each got.

#22421 Use Matomo coding standard repo
  composer.json
  composer.lock
  phpcs.xml
Labels: c: Tests & QA, Needs Review

#22469 Sort list of plugins in archive invalidation information
  plugins/Diagnostics/Diagnostic/ArchiveInvalidationsInformational.php
Labels: c: Tests & QA, not-in-changelog, Needs Review

#22464 Ensure a static sorting of referrers in transitions
  plugins/Transitions/API.php
Labels: not-in-changelog, Needs Review

#22462 Sort email reports by description in API & UI
  config/environment/ui-test-tidb.php
  core/Container/ContainerFactory.php
  plugins/ScheduledReports/API.php
  plugins/ScheduledReports/Controller.php
  tests/UI/expected-screenshots/UIIntegrationTest_email_reports.png
  tests/UI/specs/UIIntegration_spec.js
Labels: Needs Review

#22465 Sort visits also by idvisit to ensure a static result if the time is exactly the same
  plugins/Live/Model.php
  plugins/Live/tests/Integration/ModelTest.php
  plugins/Live/tests/System/expected/test_allSites__Live.getLastVisitsDetails_day.xml
  plugins/Live/tests/System/expected/test_multiSites__Live.getLastVisitsDetails_day.xml
  plugins/PrivacyManager/tests/System/expected/test_allSites__Live.getLastVisitsDetails_year.xml
  plugins/PrivacyManager/tests/System/expected/test_allSites_noActions__Live.getLastVisitsDetails_year.xml
  plugins/PrivacyManager/tests/System/expected/test_userIdAnonymized__Live.getLastVisitsDetails_year.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Live.getLastVisitsDetails_range.xml
  tests/UI/expected-screenshots/UIIntegrationTest_segmented_visitorlog.png
Labels: not-in-changelog, Needs Review

#22472 Prepare 5.1.1-rc1
  core/Version.php
Labels: not-in-changelog

#22473 Sort goals by id in API response
  core/DataTable/Filter/ReplaceColumnNames.php
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_Metadata_VisitTime.getVisitInformationPerServerTime__API.getProcessedReport_day.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems__API.getProcessedReport_day.xml
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems__UserCountry.getContinent_day.xml
  plugins/Goals/tests/System/expected/test_goals_ecommerceshowSalesByPages__Actions.getPageUrls_day.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits_hideColumns___API.getProcessedReport_day.xml
Labels: c: Tests & QA, Needs Review

#22451 Update 1-click trial process to go via Markeplace e-shop
  plugins/Marketplace/Controller.php
  plugins/Marketplace/Marketplace.php
  plugins/Marketplace/stylesheets/plugin-details.less
  plugins/Marketplace/templates/overview.twig
  plugins/Marketplace/tests/UI/Marketplace_StartFreeTrial_spec.js
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_free_plugin_details_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_free_plugin_details_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_free_plugin_details_user.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugin_details_exceeded_license_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugin_details_exceeded_license_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugin_details_exceeded_license_user.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugin_details_no_license_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugin_details_no_license_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugin_details_no_license_user.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugin_details_valid_license_multiUserEnvironment_installed.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugin_details_valid_license_superuser_installed.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugin_details_valid_license_user_installed.png
  plugins/Marketplace/vue/dist/Marketplace.umd.js
  plugins/Marketplace/vue/dist/Marketplace.umd.min.js
  plugins/Marketplace/vue/src/Marketplace/Marketplace.vue
  plugins/Marketplace/vue/src/OverviewIntro/OverviewIntro.vue
  plugins/Marketplace/vue/src/PluginDetailsModal/PluginDetailsModal.vue
  plugins/Marketplace/vue/src/PluginList/CTAContainer.vue
  plugins/Marketplace/vue/src/PluginList/PluginList.vue
Labels: Enhancement, c: Marketplace, Needs Review, Better processes

#22474 Improvements around validity checks for redirect urls
  core/UrlHelper.php
  plugins/Login/Controller.php
  plugins/Login/tests/UI/Login_spec.js
Labels: c: Security

#22453 Translations update from Hosted Weblate
  plugins/Diagnostics/lang/de.json
  plugins/GeoIp2/lang/ga.json
  plugins/Installation/lang/es.json
  plugins/Live/lang/fr.json
  plugins/Referrers/lang/de.json
  plugins/Referrers/lang/sv.json
  plugins/SegmentEditor/lang/ga.json
  plugins/Widgetize/lang/es.json
  plugins/Widgetize/lang/eu.json
  plugins/Widgetize/lang/fr.json
  plugins/Widgetize/lang/id.json
  plugins/Widgetize/lang/it.json
  plugins/Widgetize/lang/ja.json
  plugins/Widgetize/lang/nb.json
  plugins/Widgetize/lang/nl.json
  plugins/Widgetize/lang/pt.json
  plugins/Widgetize/lang/sv.json
  plugins/Widgetize/lang/uk.json
Labels: not-in-changelog, c: i18n

#22476 Use custom token when creating automated PRs
  .github/workflows/composer-update.yml
  .github/workflows/submodules.yml
Labels: not-in-changelog, Needs Review

#22478 Update 1-click trial process to go via Markeplace e-shop (#22451)
  plugins/Marketplace/Controller.php
  plugins/Marketplace/Marketplace.php
  plugins/Marketplace/stylesheets/plugin-details.less
  plugins/Marketplace/templates/overview.twig
  plugins/Marketplace/tests/UI/Marketplace_StartFreeTrial_spec.js
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_free_plugin_details_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_free_plugin_details_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_free_plugin_details_user.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugin_details_exceeded_license_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugin_details_exceeded_license_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugin_details_exceeded_license_user.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugin_details_no_license_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugin_details_no_license_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugin_details_no_license_user.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugin_details_valid_license_multiUserEnvironment_installed.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugin_details_valid_license_superuser_installed.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugin_details_valid_license_user_installed.png
  plugins/Marketplace/vue/dist/Marketplace.umd.js
  plugins/Marketplace/vue/dist/Marketplace.umd.min.js
  plugins/Marketplace/vue/src/Marketplace/Marketplace.vue
  plugins/Marketplace/vue/src/OverviewIntro/OverviewIntro.vue
  plugins/Marketplace/vue/src/PluginDetailsModal/PluginDetailsModal.vue
  plugins/Marketplace/vue/src/PluginList/CTAContainer.vue
  plugins/Marketplace/vue/src/PluginList/PluginList.vue
Labels: not-in-changelog

#22448 Add names to GH build steps for discoverability
  .github/workflows/buildvue.yml
  .github/workflows/buildwoff2.yml
Labels: not-in-changelog, Needs Review

#22481 Improves a couple of tests to succeed on TiDb
  plugins/CoreAdminHome/tests/Integration/Model/DuplicateActionRemoverTest.php
  plugins/SitesManager/tests/Integration/ApiTest.php
  plugins/SitesManager/tests/Integration/ModelTest.php
  tests/PHPUnit/Integration/Archive/ChunksTest.php
  tests/PHPUnit/Integration/CronArchiveTest.php
  tests/PHPUnit/Integration/DataAccess/LogAggregatorTest.php
Labels: c: Tests & QA, not-in-changelog

#22470 Sort result of archive table analyze command
  core/DataAccess/ArchiveTableDao.php
  plugins/Diagnostics/tests/Integration/Commands/AnalyzeArchiveTableTest.php
Labels: c: Tests & QA, not-in-changelog, Needs Review

#22486 Ensure UI tests use the correct charset / collation on TiDb
  tests/PHPUnit/Fixtures/SqlDump.php
Labels: c: Tests & QA, not-in-changelog, Needs Review

#22485 Always use utf8 for load data infile on tidb
  core/Config/DatabaseConfig.php
  core/Db/BatchInsert.php
  tests/PHPUnit/Fixtures/SqlDump.php
  tests/PHPUnit/Integration/Db/Schema/TidbTest.php
Labels: Needs Review

#22488 Test fixes for TiDb
  core/DataAccess/Model.php
  tests/PHPUnit/Integration/DataAccess/ArchiveInvalidatorTest.php
  tests/PHPUnit/Integration/DataAccess/ModelTest.php
Labels: c: Tests & QA, Needs Review

#22492 Fix diagnostics:analyze-archive-table table output
  core/DataAccess/ArchiveTableDao.php
  plugins/Diagnostics/Commands/AnalyzeArchiveTable.php
  tests/PHPUnit/Integration/DataAccess/ArchiveTableDaoTest.php
Labels: Bug, not-in-changelog, Needs Review

#22489 Add visual test for add to cart button
  plugins/Marketplace/stylesheets/plugin-details.less
  plugins/Marketplace/tests/UI/Marketplace_spec.js
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugin_details_add_to_cart_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugin_details_add_to_cart_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugin_details_add_to_cart_user.png
  plugins/Marketplace/vue/dist/Marketplace.umd.js
  plugins/Marketplace/vue/dist/Marketplace.umd.min.js
  plugins/Marketplace/vue/src/PluginDetailsModal/PluginDetailsModal.vue
Labels: not-in-changelog

#22367 Add Github workflow to allow for automatic preview releases
  .github/workflows/matomo-tests.yml
  .github/workflows/release-preview.yml
  .github/workflows/release.yml
  core/Version.php
  tests/PHPUnit/Unit/VersionTest.php
Labels: c: Platform, c: Tests & QA, Needs Review, Better processes, Stale

#22498 Removing getting started menu from MTM
  plugins/CorePluginsAdmin/Controller.php
  plugins/CorePluginsAdmin/tests/UI/TagManagerTeaser_spec.js
  plugins/CorePluginsAdmin/tests/UI/expected-screenshots/TagManagerTeaser_super_user_activate_plugin.png
Labels: Needs Review

#22501 Explicitly pass secrets to release workflow
  .github/workflows/release-preview.yml
  .github/workflows/release.yml
Labels: not-in-changelog, Needs Review

#22494 [automatic composer updates]
  composer.lock
Labels: Task, not-in-changelog

#22512 Pass correct ref to release action
  .github/workflows/matomo-tests.yml
  .github/workflows/release-preview.yml
  .github/workflows/release.yml
Labels: not-in-changelog

#22503 Ensure requests for inexistent records are handled correctly
  core/DataAccess/ArchiveWriter.php
  core/Plugin/Archiver.php
  tests/PHPUnit/Integration/ArchiveProcessingTest.php
  tests/PHPUnit/Integration/ArchiveProcessor/LoaderTest.php
  tests/PHPUnit/Integration/ArchiveTest.php
Labels: Bug, Needs Review, Stability, c: Data Integrity & Accuracy

#22515 Ensure process list isn't cut of when looking for running processes
  core/CliMulti/Process.php
Labels: Needs Review

#22505 Make the alert more stern for UninstallConfirm in en.json
  plugins/CorePluginsAdmin/lang/en.json
Labels: not-in-changelog, c: i18n

#22517 Fixes translation error in mobile menu, #PG-3768
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/MobileLeftMenu/MobileLeftMenu.vue
Labels: Bug

#22507 Add supported read isolation level to schema interface
  CHANGELOG.md
  core/DataAccess/LogAggregator.php
  core/Db/Schema.php
  core/Db/Schema/Mysql.php
  core/Db/Schema/Tidb.php
  core/Db/SchemaInterface.php
  core/Db/TransactionLevel.php
  plugins/Diagnostics/Diagnostic/DatabaseAbilitiesCheck.php
  plugins/PrivacyManager/LogDataPurger.php
  tests/PHPUnit/Integration/DataAccess/LogAggregatorTest.php
  tests/PHPUnit/Integration/Db/TransactionLevelTest.php
  tests/PHPUnit/Unit/DeprecatedMethodsTest.php
Labels: not-in-changelog, Needs Review

#22521 Adds code to hide install and update button when enable_plugins_admin=0 is set, #PG-3693
  plugins/Marketplace/tests/UI/Marketplace_spec.js
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_themes_with_valid_license_disabled_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_themes_with_valid_license_disabled_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_themes_with_valid_license_disabled_user.png
  plugins/Marketplace/vue/dist/Marketplace.umd.js
  plugins/Marketplace/vue/dist/Marketplace.umd.min.js
  plugins/Marketplace/vue/src/PluginList/CTAContainer.vue
Labels: Bug, c: Usability

#22538 Ensure plugin updates are not offered in UI if plugin admin is disabled in config
  config/environment/ui-test.php
  config/global.php
  plugins/CorePluginsAdmin/Menu.php
  plugins/CorePluginsAdmin/templates/plugins.twig
  plugins/CorePluginsAdmin/tests/Fixtures/PluginUpdatesFixture.php
  plugins/CorePluginsAdmin/tests/UI/PluginsAdmin_spec.js
  plugins/CorePluginsAdmin/tests/UI/expected-screenshots/PluginsAdmin_plugins.png
  plugins/CorePluginsAdmin/tests/UI/expected-screenshots/PluginsAdmin_plugins_admin_disabled.png
  plugins/CorePluginsAdmin/tests/UI/expected-screenshots/PluginsAdmin_plugins_no_internet.png
  plugins/CorePluginsAdmin/tests/UI/expected-screenshots/PluginsAdmin_themes.png
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/PluginsTable/PluginsTableWithUpdates.vue
  plugins/Marketplace/Plugins.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_plugins.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_plugins_no_internet.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_themes.png
  tests/UI/specs/UIIntegration_spec.js
Labels: Bug, c: Usability, Needs Review

#22522 Translations update from Hosted Weblate
  lang/lv.json
  lang/tr.json
  plugins/CoreAdminHome/lang/lv.json
  plugins/CoreHome/lang/cs.json
  plugins/CoreHome/lang/id.json
  plugins/CoreHome/lang/lv.json
  plugins/CoreHome/lang/tr.json
  plugins/CorePluginsAdmin/lang/tr.json
  plugins/Dashboard/lang/lv.json
  plugins/Diagnostics/lang/tr.json
  plugins/Goals/lang/tr.json
  plugins/Installation/lang/id.json
  plugins/Installation/lang/tr.json
  plugins/JsTrackerInstallCheck/lang/cs.json
  plugins/JsTrackerInstallCheck/lang/el.json
  plugins/JsTrackerInstallCheck/lang/ga.json
  plugins/JsTrackerInstallCheck/lang/tr.json
  plugins/Marketplace/lang/tr.json
  plugins/MultiSites/lang/tr.json
  plugins/PrivacyManager/lang/cs.json
  plugins/ProfessionalServices/lang/tr.json
  plugins/Referrers/lang/tr.json
  plugins/UserCountryMap/lang/cs.json
  plugins/VisitorInterest/lang/zh-cn.json
  plugins/Widgetize/lang/tr.json
Labels: not-in-changelog, c: i18n
