Repository matomo-org/matomo, pull requests merged in 2024-03, with the labels that each got.

#21969 Added common command to check direct use of dependencies, #PG-3272
  .github/workflows/matomo-tests.yml
  plugins/TestRunner/Commands/CheckDirectDependencyUse.php
  plugins/TestRunner/tests/System/CheckDirectDependencyUseCommandTest.php
Labels: c: Tests & QA, not-in-changelog, Needs Review, Stability

#21982 Pass number of users and sites along when starting a free trial
  plugins/Marketplace/API.php
Labels: Bug, not-in-changelog, Needs Review

#21980 Write archive records with writer reconnection attempt
  core/DataAccess/ArchiveWriter.php
  core/Db.php
  tests/PHPUnit/Integration/DbTest.php
Labels: c: Performance, not-in-changelog, Needs Review, Stability

#22003 Prevent exception if gd extension is missing
  core/Visualization/Sparkline.php
Labels: Bug, not-in-changelog, c: Design / UI, Needs Review, Regression

#22005 Update allowed releasers
  .github/workflows/release.yml
Labels: not-in-changelog, Needs Review

#21992 Cache additional site urls in live visitor details
  plugins/Live/VisitorDetails.php
Labels: c: Performance, not-in-changelog, Needs Review

#22012 Fix tests:check-direct-dependency-use command not working with plugins when test running on Github
  plugins/TestRunner/Commands/CheckDirectDependencyUse.php
  plugins/TestRunner/tests/System/CheckDirectDependencyUseCommandTest.php
Labels: Needs Review

#21984 Translations update from Hosted Weblate
  plugins/CustomDimensions/lang/pt.json
  plugins/Diagnostics/lang/pt.json
  plugins/GeoIp2/lang/gu.json
  plugins/Installation/lang/pt.json
  plugins/Live/lang/pt.json
  plugins/Login/lang/pt.json
  plugins/MobileMessaging/lang/gu.json
  plugins/MobileMessaging/lang/pt.json
  plugins/PagePerformance/lang/pt.json
  plugins/PrivacyManager/lang/pt.json
  plugins/Referrers/lang/pt.json
  plugins/SegmentEditor/lang/pt.json
  plugins/Tour/lang/pt.json
  plugins/TwoFactorAuth/lang/pt.json
  plugins/UserId/lang/pt.json
  plugins/UsersManager/lang/pt.json
  plugins/UsersManager/lang/ru.json
  plugins/VisitFrequency/lang/pt.json
  plugins/Widgetize/lang/pt.json
Labels: Task, not-in-changelog, c: i18n

#22017 Updated matomo-tests.yml.twig template to install ripgrep and testomat key
  plugins/TestRunner/templates/matomo-tests.yml.twig
Labels: Task, c: Tests & QA, not-in-changelog

#22016 Translations update from Hosted Weblate
  lang/it.json
  plugins/CoreAdminHome/lang/eu.json
  plugins/CoreAdminHome/lang/it.json
  plugins/CorePluginsAdmin/lang/eu.json
  plugins/CorePluginsAdmin/lang/it.json
  plugins/CustomDimensions/lang/it.json
  plugins/Diagnostics/lang/it.json
  plugins/GeoIp2/lang/it.json
  plugins/Installation/lang/gu.json
  plugins/Login/lang/it.json
  plugins/Marketplace/lang/eu.json
  plugins/Marketplace/lang/it.json
  plugins/PrivacyManager/lang/it.json
  plugins/ProfessionalServices/lang/it.json
  plugins/ScheduledReports/lang/it.json
  plugins/SegmentEditor/lang/it.json
  plugins/SitesManager/lang/it.json
  plugins/Transitions/lang/it.json
  plugins/TwoFactorAuth/lang/it.json
  plugins/UserCountry/lang/it.json
  plugins/UsersManager/lang/eu.json
  plugins/UsersManager/lang/it.json
  plugins/VisitTime/lang/it.json
Labels: Task, not-in-changelog, c: i18n

#21999 Update JS tracker to support feature consent
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  tests/javascript/index.php
Labels: Needs Review, c: Tracking, javascript

#22030 Fix scheduled report generation for custom periods
  plugins/ScheduledReports/API.php
  plugins/ScheduledReports/tests/Integration/ApiTest.php
Labels: Bug, not-in-changelog, Needs Review, Regression

#22033 Fix scheduled report generation for custom periods (4.x)
  plugins/ScheduledReports/API.php
  plugins/ScheduledReports/tests/Integration/ApiTest.php
Labels: Bug, not-in-changelog, Needs Review, Regression

#22041 Translations update from Hosted Weblate
  lang/gu.json
  lang/pt.json
  lang/zh-cn.json
  plugins/Actions/lang/pt.json
  plugins/CoreAdminHome/lang/gu.json
  plugins/CoreAdminHome/lang/tr.json
  plugins/CoreAdminHome/lang/zh-cn.json
  plugins/CoreHome/lang/pt.json
  plugins/CorePluginsAdmin/lang/pt.json
  plugins/CoreUpdater/lang/pt.json
  plugins/CustomDimensions/lang/pt.json
  plugins/Dashboard/lang/zh-cn.json
  plugins/GeoIp2/lang/pt.json
  plugins/Goals/lang/pt.json
  plugins/Installation/lang/pt.json
  plugins/Login/lang/gu.json
  plugins/Marketplace/lang/pt.json
  plugins/MobileMessaging/lang/pt.json
  plugins/PagePerformance/lang/pt.json
  plugins/SitesManager/lang/gu.json
  plugins/Transitions/lang/pt.json
  plugins/TwoFactorAuth/lang/pt.json
  plugins/UserCountry/lang/pt.json
  plugins/VisitsSummary/lang/pt.json
Labels: not-in-changelog, c: i18n

#22035 Remove the symfony polyfill exclusions to allow roave/security-advisories to run
  composer.json
  composer.lock
Labels: Task, c: Platform, not-in-changelog, Needs Review

#22044 Ignore anonymous user when checking for allowed domains
  plugins/UsersManager/Validators/AllowedEmailDomain.php
  plugins/UsersManager/tests/Integration/SystemSettingsTest.php
  plugins/UsersManager/tests/Integration/Validators/AllowedEmailDomainTest.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_settings_general.png
Labels: Needs Review

#22052 Removed ripgrep installation code and moved to matomo-org/github-action-tests
  .github/workflows/matomo-tests.yml
  plugins/TestRunner/templates/matomo-tests.yml.twig
Labels: not-in-changelog, Needs Review

#22047 Ensure segmentation form is correctly reset
  plugins/SegmentEditor/javascripts/Segmentation.js
Labels: Needs Review
