Repository matomo-org/matomo, pull requests merged in 2024-10, with the labels that each got.

#22630 Enable segmented visits log for all referrers report
  plugins/Referrers/Reports/GetAll.php
Labels: c: Usability, Needs Review

#22646 Adds some tests around correct handling of formulas in CSV export
  core/DataTable/Renderer/Csv.php
  tests/PHPUnit/Unit/DataTable/Renderer/CSVTest.php
Labels: c: Tests & QA, Needs Review

#22648 Allow to pass a single string to write as a console message
  core/Plugin/ConsoleCommand.php
  plugins/CoreAdminHome/Commands/DeleteLogsData.php
  plugins/CoreAdminHome/Commands/RunScheduledTasks.php
  plugins/CoreConsole/Commands/ClearCaches.php
  plugins/CoreConsole/Commands/DevelopmentEnable.php
  plugins/CoreConsole/Commands/GenerateCommand.php
  plugins/CoreUpdater/Commands/ConvertToUtf8mb4.php
  plugins/CoreUpdater/Commands/Update.php
  plugins/CustomDimensions/Commands/AddCustomDimension.php
  plugins/CustomDimensions/Commands/RemoveCustomDimension.php
  plugins/Goals/Commands/CalculateConversionPages.php
  plugins/TestRunner/Commands/TestsSetupFixture.php
Labels: Task, Enhancement, Needs Review, Technical debt

#22649 Fix detection of current transaction isolation level
  core/Db/TransactionalDatabaseDynamicTrait.php
  core/Db/TransactionalDatabaseStaticTrait.php
Labels: Bug, Needs Review, Regression

#22641 Detect plugin display name through marketplace instead of passing it to API
  plugins/Marketplace/API.php
  plugins/Marketplace/tests/Integration/ApiTest.php
  plugins/Marketplace/vue/dist/Marketplace.umd.js
  plugins/Marketplace/vue/dist/Marketplace.umd.min.js
  plugins/Marketplace/vue/src/RequestTrial/RequestTrial.vue
Labels: not-in-changelog, Needs Review

#22656 Ensure LatestStable release channel uses the version provided from API
  plugins/CoreUpdater/ReleaseChannel.php
  plugins/CoreUpdater/ReleaseChannel/LatestStable.php
  plugins/CoreUpdater/tests/Integration/ReleaseChannelTest.php
Labels: Needs Review

#22655 Fix HTML markup of HTTP warning notification
  core/Plugin/ControllerAdmin.php
Labels: Needs Review, Regression

#22654 Adds some tests around correct handling of formulas in CSV export
  core/DataTable/Renderer/Csv.php
  tests/PHPUnit/Unit/DataTable/Renderer/CSVTest.php
Labels: Needs Review

#22657 Limit date ranges that end far in the future
  core/Period/Range.php
  tests/PHPUnit/Unit/DateTest.php
  tests/PHPUnit/Unit/Period/RangeTest.php
Labels: Needs Review

#22659 Detect plugin display name through marketplace instead of passing it to API
  plugins/Marketplace/API.php
  plugins/Marketplace/tests/Integration/ApiTest.php
  plugins/Marketplace/vue/dist/Marketplace.umd.js
  plugins/Marketplace/vue/dist/Marketplace.umd.min.js
  plugins/Marketplace/vue/src/RequestTrial/RequestTrial.vue
Labels: Needs Review

#22643 Configure Dependabot to update GitHub Actions and Submodules
  .github/dependabot.yml
  .github/workflows/submodules.yml
  .gitmodules
Labels: dependencies, Technical debt

#22675 Improve title of ecommerce overview widget in Dashboard
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_dashboard3.png
  plugins/Goals/Pages.php
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getReportPagesMetadata.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getWidgetMetadata.xml
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getWidgetMetadata_day.xml
Labels: Enhancement, c: Design / UI, Needs Review

#22658 Adds some tests around correct handling of formulas in CSV export
  core/DataTable/Renderer/Csv.php
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_in_tsv__ScheduledReports.generateReport_week.original.tsv
  plugins/Marketplace/tests/System/Api/ClientTest.php
  tests/PHPUnit/Unit/DataTable/Renderer/CSVTest.php
Labels: Needs Review

#22671 Fix issue with widgets store not reloading when expected
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/Widget/Widgets.store.ts
  plugins/CoreVue/types/index.d.ts
  plugins/Dashboard/javascripts/widgetMenu.js
Labels: Needs Review

#22549 Evaluate formFactors client hints for device detecion
  composer.lock
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  plugins/DevicesDetection/tests/Fixtures/MultiDeviceGoalConversions.php
  plugins/DevicesDetection/tests/System/expected/test___DevicesDetection.getBrand_day.xml
  plugins/DevicesDetection/tests/System/expected/test___DevicesDetection.getModel_day.xml
  plugins/DevicesDetection/tests/System/expected/test___DevicesDetection.getOsVersions_day.xml
  plugins/DevicesDetection/tests/System/expected/test___DevicesDetection.getType_day.xml
Labels: Enhancement, Needs Review, c: Data Integrity & Accuracy

#22681 Enable NPM updates for UI Tests using dependabot
  .github/dependabot.yml
Labels: not-in-changelog, Needs Review

#22670 Fix Unique visitors and Users metric shown in Users report
  plugins/UserId/Reports/GetUsers.php
  plugins/UserId/tests/UI/UserId_spec.js
  plugins/UserId/tests/UI/expected-screenshots/UserId_report.png
  plugins/UserId/tests/UI/expected-screenshots/UserId_report_engagement.png
Labels: Enhancement, c: Usability

#22678 Update core:convert-to-utf8mb4 to write db collaction to config
  core/DataAccess/ArchiveTableCreator.php
  core/Plugin/ConsoleCommand.php
  core/Updates/5.2.0-b2.php
  plugins/CoreUpdater/Commands/ConvertToUtf8mb4.php
  tests/PHPUnit/Unit/DataAccess/ArchiveTableCreatorTest.php
Labels: Enhancement, c: Platform, Needs Review

#22668 Various improvements to number verification workflow in MobileMessaging
  plugins/MobileMessaging/API.php
  plugins/MobileMessaging/Controller.php
  plugins/MobileMessaging/MobileMessaging.php
  plugins/MobileMessaging/Model.php
  plugins/MobileMessaging/SMSProvider/Development.php
  plugins/MobileMessaging/lang/en.json
  plugins/MobileMessaging/tests/Integration/MobileMessagingTest.php
  plugins/MobileMessaging/tests/UI/MobileMessaging_spec.js
  plugins/MobileMessaging/tests/UI/expected-screenshots/MobileMessaging_admin.png
  plugins/MobileMessaging/tests/UI/expected-screenshots/MobileMessaging_admin_numbers_added.png
  plugins/MobileMessaging/tests/UI/expected-screenshots/MobileMessaging_admin_numbers_initial.png
  plugins/MobileMessaging/tests/UI/expected-screenshots/MobileMessaging_admin_provider.png
  plugins/MobileMessaging/vue/dist/MobileMessaging.umd.js
  plugins/MobileMessaging/vue/dist/MobileMessaging.umd.min.js
  plugins/MobileMessaging/vue/dist/umd.metadata.json
  plugins/MobileMessaging/vue/src/ManageMobilePhoneNumbers/ManageMobilePhoneNumbers.vue
  plugins/ScheduledReports/tests/Integration/ApiTest.php
  tests/UI/expected-screenshots/UIIntegrationTest_api_listing.png
  tests/UI/specs/UIIntegration_spec.js
Labels: Enhancement, Needs Review

#22644 Improve handling for changing email of invited users
  plugins/UsersManager/API.php
  plugins/UsersManager/Model.php
  plugins/UsersManager/Repository/UserRepository.php
  plugins/UsersManager/UsersManager.php
  plugins/UsersManager/lang/en.json
  plugins/UsersManager/stylesheets/usersManager.less
  plugins/UsersManager/tests/Integration/APITest.php
  plugins/UsersManager/tests/UI/UsersManager_spec.js
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_user_invited_change.png
  plugins/UsersManager/vue/dist/UsersManager.umd.js
  plugins/UsersManager/vue/dist/UsersManager.umd.min.js
  plugins/UsersManager/vue/src/UserEditForm/UserEditForm.vue
Labels: Enhancement, Needs Review

#22679 Enable automatic NPM updates using dependabot
  .github/dependabot.yml
  .github/workflows/dependabot_prs.yml
  package.json
Labels: Task, Needs Review

#22685 Improve handling for changing email of invited users
  plugins/UsersManager/API.php
  plugins/UsersManager/Model.php
  plugins/UsersManager/Repository/UserRepository.php
  plugins/UsersManager/UsersManager.php
  plugins/UsersManager/lang/en.json
  plugins/UsersManager/stylesheets/usersManager.less
  plugins/UsersManager/tests/Integration/APITest.php
  plugins/UsersManager/tests/UI/UsersManager_spec.js
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_user_invited_change.png
  plugins/UsersManager/vue/dist/UsersManager.umd.js
  plugins/UsersManager/vue/dist/UsersManager.umd.min.js
  plugins/UsersManager/vue/src/UserEditForm/UserEditForm.vue
Labels: Needs Review

#22691 Fix typos in comments
  plugins/LanguagesManager/Model.php
Labels: Task, not-in-changelog, Needs Review

#22688 Update Dashboard when widget list is reloaded
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/Widget/Widgets.store.ts
  plugins/Dashboard/vue/dist/Dashboard.umd.js
  plugins/Dashboard/vue/dist/Dashboard.umd.min.js
  plugins/Dashboard/vue/src/DashboardSettings/DashboardSettings.vue
Labels: Bug, c: Design / UI, Needs Review

#22692 Improve style for AdBlock warning
  plugins/CoreHome/templates/_adblockDetect.twig
Labels: c: Design / UI

#22689 Translations update from Hosted Weblate
  plugins/Marketplace/lang/tr.json
  plugins/MobileMessaging/lang/ca.json
  plugins/MobileMessaging/lang/el.json
  plugins/MobileMessaging/lang/tr.json
  plugins/UsersManager/lang/ca.json
  plugins/UsersManager/lang/el.json
  plugins/UsersManager/lang/tr.json
Labels: not-in-changelog, c: i18n

#22694 Show owner name in marketplace card for each plugin
  plugins/Marketplace/Marketplace.php
  plugins/Marketplace/lang/en.json
  plugins/Marketplace/stylesheets/marketplace.less
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_no_license_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_no_license_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_no_license_user.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_with_exceeded_license_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_with_exceeded_license_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_with_exceeded_license_user.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_with_license_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_with_license_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_paid_plugins_with_license_user.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_themes_with_valid_license_disabled_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_themes_with_valid_license_disabled_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_themes_with_valid_license_disabled_user.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_themes_with_valid_license_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_themes_with_valid_license_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_themes_with_valid_license_user.png
  plugins/Marketplace/vue/dist/Marketplace.umd.js
  plugins/Marketplace/vue/dist/Marketplace.umd.min.js
  plugins/Marketplace/vue/src/PluginList/PluginList.vue
Labels: Needs Review

#22698 Show owner name UI adjusted as per product feedback, #PG-3773
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_themes_with_valid_license_disabled_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_themes_with_valid_license_disabled_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_themes_with_valid_license_disabled_user.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_themes_with_valid_license_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_themes_with_valid_license_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_themes_with_valid_license_user.png
  plugins/Marketplace/vue/dist/Marketplace.umd.js
  plugins/Marketplace/vue/dist/Marketplace.umd.min.js
  plugins/Marketplace/vue/src/PluginList/PluginList.vue
Labels: not-in-changelog, Needs Review

#22699 Updates marketplace icons with higher contrast version, #PG-3668
  plugins/Marketplace/images/categories/uncategorised.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_themes_with_valid_license_disabled_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_themes_with_valid_license_disabled_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_themes_with_valid_license_disabled_user.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_themes_with_valid_license_multiUserEnvironment.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_themes_with_valid_license_superuser.png
  plugins/Marketplace/tests/UI/expected-screenshots/Marketplace_themes_with_valid_license_user.png
  plugins/Marketplace/tests/resources/images/categories/customisation.png
  plugins/Marketplace/tests/resources/images/categories/uncategorised.png
Labels: Task, not-in-changelog

#22690 [PHP 8.4] Use SessionHandlerInterface instead of Zend_Session_SaveHandler_Interface
  core/Session/SaveHandler/DbTable.php
  libs/Zend/Session.php
  libs/Zend/Session/SaveHandler/DbTable.php
  libs/Zend/Session/SaveHandler/Exception.php
  libs/Zend/Session/SaveHandler/Interface.php
Labels: Needs Review

#22701 Fix some regressions in mobile messaging
  plugins/MobileMessaging/API.php
  plugins/MobileMessaging/Model.php
  plugins/MobileMessaging/lang/en.json
Labels: not-in-changelog, Needs Review

#22703 Fix some regressions in mobile messaging
  plugins/MobileMessaging/API.php
  plugins/MobileMessaging/Model.php
  plugins/MobileMessaging/lang/en.json
Labels: not-in-changelog, Needs Review, Regression

#22700 Translations update from Hosted Weblate
  plugins/Marketplace/lang/ca.json
  plugins/Marketplace/lang/el.json
  plugins/Marketplace/lang/et.json
  plugins/Marketplace/lang/fr.json
  plugins/Marketplace/lang/ga.json
  plugins/Marketplace/lang/sq.json
  plugins/Marketplace/lang/tr.json
  plugins/MobileMessaging/lang/ga.json
  plugins/UsersManager/lang/ga.json
Labels: not-in-changelog, c: i18n

#22559 Added the ability to force the use of an index
  core/DataAccess/LogAggregator.php
  core/DataAccess/LogQueryBuilder/JoinGenerator.php
  core/DataAccess/LogQueryBuilder/JoinTables.php
  tests/PHPUnit/Unit/DataAccess/LogAggregatorTest.php
  tests/PHPUnit/Unit/DataAccess/LogQueryBuilder/JoinGeneratorTest.php
  tests/PHPUnit/Unit/DataAccess/LogQueryBuilder/JoinTablesTest.php
Labels: Needs Review

#22674 Fix type error when idSites isn't an array
  core/Archive/ArchiveInvalidator.php
  tests/PHPUnit/Integration/DataAccess/ArchiveInvalidatorTest.php
Labels: Bug, c: Platform, Needs Review

#22667 Run tests on PHP 8.4 instead of PHP 8.3
  .github/workflows/matomo-tests.yml
  core/ErrorHandler.php
  core/bootstrap.php
  js/tracker.php
  tests/PHPUnit/Integration/DocumentationGeneratorTest.php
  tests/PHPUnit/Integration/FrontControllerTest.php
  tests/PHPUnit/System/EnvironmentValidationTest.php
Labels: c: Tests & QA

#22696 [automatic composer updates]
  composer.lock
  plugins/CustomDimensions/tests/System/expected/test___ScheduledReports.generateReport_year.original.pdf
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_in_pdf_tables_only__ScheduledReports.generateReport_week.original.pdf
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_in_pdf_tables_only__ScheduledReports.generateReport_month.original.pdf
Labels: Task, not-in-changelog

#22711 Use automation user to commit built vue files to ensure other actions are triggered
  .github/workflows/buildvue.yml
Labels: Needs Review

#22716 Adds missing description for 2FA plugin
  plugins/CorePluginsAdmin/tests/UI/expected-screenshots/PluginsAdmin_plugins.png
  plugins/CorePluginsAdmin/tests/UI/expected-screenshots/PluginsAdmin_plugins_admin_disabled.png
  plugins/CorePluginsAdmin/tests/UI/expected-screenshots/PluginsAdmin_plugins_no_internet.png
  plugins/TwoFactorAuth/lang/en.json
Labels: Bug, Needs Review, c: i18n

#22726 Ensure integer value is passed to database for secure_only flag
  plugins/UsersManager/Model.php
Labels: not-in-changelog, Needs Review
