Repository matomo-org/matomo, pull requests merged in 2024-07, with the labels that each got.

#22334 Send response code 400 when requesting a non existing method
  core/API/Proxy.php
  core/Http/BadRequestException.php
Labels: Needs Review

#22356 Adjust some database statement related tests
  tests/PHPUnit/Integration/Updater/Migration/Db/FactoryTest.php
Labels: c: Tests & QA, not-in-changelog, Needs Review

#22366 Fixes copy code not working for modal due to no focus in Modal
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/CopyToClipboard/CopyToClipboard.ts
Labels: Needs Review

#22351 Round conversion attribution before summing up the value in database query
  core/DataAccess/LogAggregator.php
Labels: c: Tests & QA, not-in-changelog, Needs Review

#22374 Use alternative domain for IPv6 tests of allowed IPs
  plugins/CoreHome/tests/Integration/LoginAllowlistTest.php
Labels: Task, c: Tests & QA, not-in-changelog, Needs Review

#22355 Move methods related to optimizing database tables to schema classes
  CHANGELOG.md
  core/Db.php
  core/Db/Schema.php
  core/Db/Schema/Mariadb.php
  core/Db/Schema/Mysql.php
  core/Db/Schema/Tidb.php
  core/Db/SchemaInterface.php
  plugins/CoreAdminHome/Commands/DeleteLogsData.php
  plugins/CoreAdminHome/Commands/OptimizeArchiveTables.php
  plugins/CoreAdminHome/Commands/PurgeOldArchiveData.php
  plugins/CoreAdminHome/Tasks.php
  plugins/PrivacyManager/LogDataPurger.php
  plugins/PrivacyManager/ReportsPurger.php
  tests/PHPUnit/Integration/Db/Schema/MariadbTest.php
  tests/PHPUnit/Integration/Db/Schema/MysqlTest.php
  tests/PHPUnit/Integration/Db/Schema/TidbTest.php
  tests/PHPUnit/Integration/DbTest.php
  tests/PHPUnit/Integration/SqlTest.php
  tests/PHPUnit/Unit/DeprecatedMethodsTest.php
Labels: c: Platform, Needs Review

#22382 Fixed issue with allowClipboard function not working in tests
  tests/lib/screenshot-testing/support/page-renderer.js
Labels: Needs Review

#22368 Translations update from Hosted Weblate
  lang/ko.json
  plugins/CustomJsTracker/lang/ga.json
  plugins/DevicePlugins/lang/ga.json
  plugins/ImageGraph/lang/ga.json
  plugins/Installation/lang/nb.json
  plugins/IntranetMeasurable/lang/ga.json
  plugins/JsTrackerInstallCheck/lang/ga.json
  plugins/LanguagesManager/lang/ga.json
  plugins/MobileAppMeasurable/lang/ga.json
  plugins/Referrers/lang/ca.json
  plugins/Referrers/lang/el.json
  plugins/Referrers/lang/tr.json
  plugins/Resolution/lang/ga.json
  plugins/SEO/lang/ga.json
  plugins/UserId/lang/ga.json
  plugins/UserLanguage/lang/ga.json
  plugins/WebsiteMeasurable/lang/ga.json
Labels: not-in-changelog, c: i18n

#22296 Add mechanism to invalidate dependent segment archives
  core/Archive/ArchiveInvalidator.php
  core/ArchiveProcessor.php
  core/DataAccess/Model.php
  plugins/CoreAdminHome/tests/Integration/InvalidateReportDataTest.php
  plugins/CoreConsole/tests/System/expected/test_ArchiveCronTest_noOptions__Goals.get_month.xml
  tests/PHPUnit/Integration/ArchiveProcessor/LoaderTest.php
Labels: Needs Review, c: Data Integrity & Accuracy

#22312 Improved All Websites Dashboard
  LEGALNOTICE
  plugins/Morpheus/Controller.php
  plugins/Morpheus/fonts/matomo.eot
  plugins/Morpheus/fonts/matomo.svg
  plugins/Morpheus/fonts/matomo.ttf
  plugins/Morpheus/fonts/matomo.woff
  plugins/Morpheus/fonts/matomo.woff2
  plugins/Morpheus/fonts/selection.json
  plugins/Morpheus/fonts/svgs/icon-dollar-sign.svg
  plugins/Morpheus/fonts/svgs/icon-hits.svg
  plugins/Morpheus/stylesheets/base/icons.css
  plugins/Morpheus/templates/dashboard.twig
  plugins/Morpheus/tests/UI/expected-screenshots/Morpheus_load.png
  plugins/MultiSites/API.php
  plugins/MultiSites/Controller.php
  plugins/MultiSites/FeatureFlags/ImprovedAllWebsitesDashboard.php
  plugins/MultiSites/MultiSites.php
  plugins/MultiSites/config/ui-test.php
  plugins/MultiSites/images/kpi_divider.svg
  plugins/MultiSites/lang/en.json
  plugins/MultiSites/templates/allWebsitesDashboard.twig
  plugins/MultiSites/tests/UI/AllWebsitesDashboard_spec.js
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_dashboard.png
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_error.png
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_evolution_change.png
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_no_revenue.png
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_no_sparklines.png
  plugins/MultiSites/tests/UI/expected-screenshots/AllWebsitesDashboard_widgetized.png
  plugins/MultiSites/vue/dist/MultiSites.umd.js
  plugins/MultiSites/vue/dist/MultiSites.umd.min.js
  plugins/MultiSites/vue/src/AllWebsitesDashboard/AllWebsitesDashboard.less
  plugins/MultiSites/vue/src/AllWebsitesDashboard/AllWebsitesDashboard.store.ts
  plugins/MultiSites/vue/src/AllWebsitesDashboard/AllWebsitesDashboard.vue
  plugins/MultiSites/vue/src/AllWebsitesDashboard/KPICard.vue
  plugins/MultiSites/vue/src/AllWebsitesDashboard/KPICardContainer.vue
  plugins/MultiSites/vue/src/AllWebsitesDashboard/SitesTable.vue
  plugins/MultiSites/vue/src/AllWebsitesDashboard/SitesTableSite.vue
  plugins/MultiSites/vue/src/index.ts
  plugins/MultiSites/vue/src/types.ts
  tests/UI/expected-screenshots/Theme_demo.png
Labels: Enhancement, c: Usability, c: Design / UI, Needs Review

#22386 Translations update from Hosted Weblate
  plugins/API/lang/ga.json
  plugins/Annotations/lang/ga.json
  plugins/Contents/lang/ga.json
  plugins/DBStats/lang/ga.json
  plugins/MultiSites/lang/ga.json
  plugins/Overlay/lang/ga.json
  plugins/UserCountryMap/lang/ga.json
  plugins/VisitorInterest/lang/ga.json
  plugins/VisitsSummary/lang/ga.json
  plugins/Widgetize/lang/ga.json
Labels: not-in-changelog, c: i18n

#22402 Improve URL check for logme redirect
  core/UrlHelper.php
  plugins/Login/Controller.php
  plugins/Login/tests/UI/Login_spec.js
Labels: Needs Review

#22392 Handle invalidation of currently processed archives correctly
  core/DataAccess/ArchiveTableDao.php
  core/DataAccess/ArchiveWriter.php
  core/DataAccess/Model.php
  tests/PHPUnit/Integration/DataAccess/ArchiveInvalidatorTest.php
  tests/PHPUnit/Integration/DataAccess/ModelTest.php
Labels: Bug, Major, Needs Review

#22399 Translations update from Hosted Weblate
  lang/zh-cn.json
  plugins/API/lang/zh-cn.json
  plugins/Actions/lang/zh-cn.json
  plugins/Annotations/lang/zh-cn.json
  plugins/CoreAdminHome/lang/zh-cn.json
  plugins/CoreHome/lang/es.json
  plugins/CoreHome/lang/zh-cn.json
  plugins/CorePluginsAdmin/lang/es.json
  plugins/CorePluginsAdmin/lang/zh-cn.json
  plugins/CoreUpdater/lang/zh-cn.json
  plugins/Ecommerce/lang/ga.json
  plugins/Events/lang/zh-cn.json
  plugins/Feedback/lang/zh-cn.json
  plugins/Goals/lang/zh-cn.json
  plugins/ImageGraph/lang/zh-cn.json
  plugins/Insights/lang/ga.json
  plugins/Insights/lang/zh-cn.json
  plugins/Installation/lang/es.json
  plugins/Installation/lang/zh-cn.json
  plugins/Live/lang/zh-cn.json
  plugins/Login/lang/zh-cn.json
  plugins/Marketplace/lang/zh-cn.json
  plugins/MultiSites/lang/el.json
  plugins/MultiSites/lang/es.json
  plugins/MultiSites/lang/tr.json
  plugins/Overlay/lang/zh-cn.json
  plugins/PrivacyManager/lang/zh-cn.json
  plugins/Referrers/lang/es.json
  plugins/Referrers/lang/zh-cn.json
  plugins/Referrers/lang/zh-tw.json
  plugins/Resolution/lang/zh-cn.json
  plugins/SEO/lang/zh-cn.json
  plugins/ScheduledReports/lang/zh-cn.json
  plugins/SegmentEditor/lang/zh-cn.json
  plugins/SitesManager/lang/zh-cn.json
  plugins/Transitions/lang/zh-cn.json
  plugins/TwoFactorAuth/lang/zh-cn.json
  plugins/UserCountry/lang/zh-cn.json
Labels: not-in-changelog, c: i18n

#22423 Translations update from Hosted Weblate
  plugins/CustomDimensions/lang/ga.json
  plugins/Dashboard/lang/ga.json
  plugins/Diagnostics/lang/ga.json
  plugins/Events/lang/ga.json
  plugins/MobileMessaging/lang/ga.json
  plugins/PagePerformance/lang/ga.json
  plugins/ProfessionalServices/lang/ga.json
  plugins/Transitions/lang/ga.json
  plugins/TwoFactorAuth/lang/ga.json
  plugins/UserCountry/lang/ga.json
  plugins/VisitFrequency/lang/ga.json
  plugins/VisitTime/lang/ga.json
Labels: not-in-changelog, c: i18n

#22400 Skip invalidating yesterday if a proper archive is already in progress
  core/CronArchive.php
  tests/PHPUnit/Integration/CronArchiveTest.php
Labels: Enhancement, Needs Review, Stability

#22412 Improve validity check for redirect urls
  plugins/Login/Controller.php
  plugins/Login/tests/UI/Login_spec.js
Labels: Needs Review

#22430 Track PrivacyManager\\MultipleSitesMultipleVisitsFixture visits without overlapping times
  plugins/PrivacyManager/tests/Fixtures/MultipleSitesMultipleVisitsFixture.php
  plugins/PrivacyManager/tests/Integration/Dao/LogDataAnonymizerTest.php
  plugins/PrivacyManager/tests/System/expected/anonymizeVisitInformation_allSitesAllDates.json
  plugins/PrivacyManager/tests/System/expected/anonymizeVisitInformation_anonymizeUserId.json
  plugins/PrivacyManager/tests/System/expected/anonymizeVisitInformation_restrictDate.json
  plugins/PrivacyManager/tests/System/expected/anonymizeVisitInformation_restrictSites.json
  plugins/PrivacyManager/tests/System/expected/exportDataSubject_allVisits.json
  plugins/PrivacyManager/tests/System/expected/exportDataSubject_oneVisitGiven.json
  plugins/PrivacyManager/tests/System/expected/test___PrivacyManager.findDataSubjects_allSites.xml
  plugins/PrivacyManager/tests/System/expected/test___PrivacyManager.findDataSubjects_specificSite.xml
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_visits_showprofile.png
Labels: c: Tests & QA, not-in-changelog, Needs Review

#22365 Update MTM no data tab translation
  plugins/JsTrackerInstallCheck/JsTrackerInstallCheck.php
  plugins/JsTrackerInstallCheck/lang/en.json
  plugins/JsTrackerInstallCheck/vue/dist/JsTrackerInstallCheck.umd.js
  plugins/JsTrackerInstallCheck/vue/dist/JsTrackerInstallCheck.umd.min.js
  plugins/JsTrackerInstallCheck/vue/src/JsTrackerInstallCheck/JsTrackerInstallCheck.vue
  tests/UI/expected-screenshots/EmptySite_detected_osano.png
  tests/UI/expected-screenshots/EmptySite_showAdvancedTrackingOptions.png
  tests/UI/expected-screenshots/EmptySite_trackingCode.png
  tests/UI/expected-screenshots/EmptySite_wordpress.png
Labels: Needs Review

#22435 Allow configuring archive failure recovery timeout
  config/global.ini.php
  core/DataAccess/Model.php
  tests/PHPUnit/Integration/DataAccess/ModelTest.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: Enhancement, Needs Review

#22429 Fix handling of ranking query for TiDb
  core/Db/Schema.php
  core/Db/Schema/Mysql.php
  core/Db/Schema/Tidb.php
  core/Db/SchemaInterface.php
  core/RankingQuery.php
  tests/PHPUnit/Unit/RankingQueryTest.php
Labels: Bug, Needs Review

#22434 Translations update from Hosted Weblate
  plugins/CoreUpdater/lang/zh-tw.json
  plugins/JsTrackerInstallCheck/lang/ca.json
  plugins/JsTrackerInstallCheck/lang/de.json
  plugins/JsTrackerInstallCheck/lang/el.json
  plugins/JsTrackerInstallCheck/lang/es.json
  plugins/JsTrackerInstallCheck/lang/eu.json
  plugins/JsTrackerInstallCheck/lang/fr.json
  plugins/JsTrackerInstallCheck/lang/ga.json
  plugins/JsTrackerInstallCheck/lang/gu.json
  plugins/JsTrackerInstallCheck/lang/hi.json
  plugins/JsTrackerInstallCheck/lang/it.json
  plugins/JsTrackerInstallCheck/lang/nb.json
  plugins/JsTrackerInstallCheck/lang/nl.json
  plugins/JsTrackerInstallCheck/lang/pt-br.json
  plugins/JsTrackerInstallCheck/lang/sq.json
  plugins/JsTrackerInstallCheck/lang/sv.json
  plugins/JsTrackerInstallCheck/lang/tr.json
  plugins/JsTrackerInstallCheck/lang/uk.json
  plugins/JsTrackerInstallCheck/lang/zh-tw.json
  plugins/Live/lang/fr.json
  plugins/Login/lang/zh-tw.json
  plugins/MultiSites/lang/ca.json
  plugins/Tour/lang/ga.json
  plugins/TwoFactorAuth/lang/fr.json
  plugins/UserCountryMap/lang/fr.json
Labels: not-in-changelog, c: i18n

#22449 Improve test stability of UsersManager UI tests
  plugins/UsersManager/tests/Fixtures/ManyUsers.php
  plugins/UsersManager/tests/UI/UsersManager_spec.js
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_admin_view_admin_add_user_by_email.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_admin_view_admin_add_user_by_login.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_admin_view_admin_edit_permissions.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_admin_view_admin_filter_permissions.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_admin_view_admin_load.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_admin_view_edit_user_basic_info.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_all_rows_deselected.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_all_rows_in_search.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_all_rows_selected.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_bulk_remove_access.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_bulk_set_access.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_copied_success.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_delete_bulk_access.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_delete_single.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_edit_user_basic_asks_confirmation.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_edit_user_basic_confirmed_wrong_password.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_edit_user_form.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_load.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_manage_users_back.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_next_click.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_previous.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_role_for.png
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_rows_selected.png
Labels: c: Tests & QA, not-in-changelog, Needs Review

#22439 Change Do -> Select for Mysqli Tidb Compat
  core/ArchiveProcessor/LoaderLock.php
Labels: not-in-changelog, Needs Review
