Repository matomo-org/matomo, pull requests merged in 2025-01, with the labels that each got.

#22902 Fix ok button text in privacy settings
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.js
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.min.js
  plugins/PrivacyManager/vue/src/ScheduleReportDeletion/ScheduleReportDeletion.vue
Labels: Needs Review

#22909 fix generation of visit dimension so you could set column type
  plugins/CoreConsole/Commands/GenerateDimension.php
Labels: Bug

#22876 Translations update from Hosted Weblate
  lang/de.json
  lang/fi.json
  lang/pt.json
  lang/ru.json
  plugins/CoreAdminHome/lang/pt.json
  plugins/CoreAdminHome/lang/ru.json
  plugins/CoreHome/lang/fi.json
  plugins/CoreHome/lang/ko.json
  plugins/CoreHome/lang/pt.json
  plugins/CoreHome/lang/ru.json
  plugins/CorePluginsAdmin/lang/de.json
  plugins/CorePluginsAdmin/lang/fr.json
  plugins/CorePluginsAdmin/lang/ko.json
  plugins/CorePluginsAdmin/lang/pt.json
  plugins/CorePluginsAdmin/lang/ru.json
  plugins/CoreUpdater/lang/ko.json
  plugins/CoreUpdater/lang/ru.json
  plugins/Feedback/lang/fi.json
  plugins/Feedback/lang/ru.json
  plugins/Goals/lang/ru.json
  plugins/Insights/lang/fi.json
  plugins/Insights/lang/ru.json
  plugins/Installation/lang/pt.json
  plugins/Installation/lang/ru.json
  plugins/Live/lang/ru.json
  plugins/Login/lang/pt.json
  plugins/Marketplace/lang/fr.json
  plugins/MobileMessaging/lang/de.json
  plugins/MobileMessaging/lang/pt.json
  plugins/MultiSites/lang/de.json
  plugins/MultiSites/lang/el.json
  plugins/MultiSites/lang/ga.json
  plugins/MultiSites/lang/sq.json
  plugins/ProfessionalServices/lang/de.json
  plugins/ProfessionalServices/lang/fr.json
  plugins/Referrers/lang/pt.json
  plugins/Referrers/lang/ru.json
  plugins/Resolution/lang/ru.json
  plugins/ScheduledReports/lang/ru.json
  plugins/SegmentEditor/lang/ru.json
  plugins/SitesManager/lang/de.json
  plugins/Tour/lang/pt.json
  plugins/UserLanguage/lang/ru.json
  plugins/UsersManager/lang/de.json
  plugins/VisitFrequency/lang/ru.json
  plugins/Widgetize/lang/pt.json
Labels: c: i18n

#22906 [automatic composer updates]
  composer.lock
  plugins/CustomDimensions/tests/System/expected/test___ScheduledReports.generateReport_year.original.pdf
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_in_pdf_tables_only__ScheduledReports.generateReport_week.original.pdf
  plugins/Live/tests/Integration/ModelTest.php
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_in_pdf_tables_only__ScheduledReports.generateReport_month.original.pdf
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getSegmentsMetadata.xml
  tests/UI/expected-screenshots/Comparison_multi_row_evolution.png
  tests/UI/expected-screenshots/IncompletePeriodVisualisation_visitors_overview.png
Labels: dependencies

#22914 Fix check for API.getBulkRequest
  plugins/API/API.php
Labels: Bug, Needs Review

#22916 Fix check for API.getBulkRequest
  plugins/API/API.php
Labels: Needs Review

#22919 #22918 fix typo
  plugins/Marketplace/Plugins.php
Labels: Bug

#22934 Fix possible array access error
  plugins/UserCountryMap/Controller.php
Labels: Bug, Needs Review

#22936 Validate Matomo URL in OptOutManager
  plugins/CoreAdminHome/OptOutManager.php
Labels: Needs Review

#22943 Validate Matomo URL in OptOutManager
  plugins/CoreAdminHome/OptOutManager.php
Labels: Needs Review

#22937 Escape control characters in log messages
  plugins/Monolog/Formatter/LineMessageFormatter.php
  plugins/Monolog/tests/Unit/Formatter/LineMessageFormatterTest.php
Labels: Needs Review

#22870 Using Intl extension to anglicisation
  plugins/GeoIp2/LocationProvider/GeoIp2/Php.php
Labels: Enhancement, Needs Review, c: i18n

#22944 Escape control characters in log messages
  plugins/Monolog/Formatter/LineMessageFormatter.php
  plugins/Monolog/tests/Unit/Formatter/LineMessageFormatterTest.php
Labels: Needs Review

#22945 Fix handling of color parameter
  core/Visualization/Sparkline.php
Labels: Bug, not-in-changelog, Needs Review

#22955 Escape segment name in comparison tooltip
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/Comparisons/Comparisons.vue
  plugins/MobileMessaging/vue/dist/umd.metadata.json
Labels: Bug, c: Design / UI, Needs Review

#22954 Escape referrer url in visits log tooltip
  plugins/Referrers/templates/_visitorDetails.twig
Labels: Bug, c: Design / UI, Needs Review

#22946 Translations update from Hosted Weblate
  plugins/CoreHome/lang/fi.json
  plugins/Installation/lang/ca.json
  plugins/Login/lang/ca.json
  plugins/Login/lang/tr.json
  plugins/Marketplace/lang/ca.json
  plugins/Marketplace/lang/tr.json
  plugins/MultiSites/lang/ca.json
  plugins/MultiSites/lang/tr.json
  plugins/SitesManager/lang/ca.json
  plugins/TwoFactorAuth/lang/ca.json
  plugins/UserCountryMap/lang/fi.json
  plugins/Widgetize/lang/fi.json
Labels: c: i18n

#22963 Fixes undefined variable error due to variable being placed in try block, but being used in finally section
  plugins/ScheduledReports/API.php
Labels: Needs Review

#22959 Prevent concurrent changes on user permissions
  plugins/UsersManager/API.php
Labels: Needs Review

#22966 Prevent concurrent changes on user permissions
  plugins/UsersManager/API.php
Labels: Needs Review

#22958 Add protocol check in handling of Overlay.startOverlaySession
  plugins/Overlay/templates/startOverlaySession.twig
Labels: not-in-changelog, Needs Review

#22950 Resolve UI issues with new top of datatable controls
  plugins/Actions/tests/UI/expected-screenshots/ActionsDataTable_auto_expand.png
  plugins/Actions/tests/UI/expected-screenshots/ActionsDataTable_column_sorted.png
  plugins/Actions/tests/UI/expected-screenshots/ActionsDataTable_exclude_low_population.png
  plugins/Actions/tests/UI/expected-screenshots/ActionsDataTable_flattened.png
  plugins/Actions/tests/UI/expected-screenshots/ActionsDataTable_initial.png
  plugins/Actions/tests/UI/expected-screenshots/ActionsDataTable_pageview_percentages.png
  plugins/Actions/tests/UI/expected-screenshots/ActionsDataTable_search.png
  plugins/Actions/tests/UI/expected-screenshots/ActionsDataTable_search_closed.png
  plugins/Actions/tests/UI/expected-screenshots/ActionsDataTable_search_visible.png
  plugins/Actions/tests/UI/expected-screenshots/ActionsDataTable_segmented_visitor_log_hover.png
  plugins/Actions/tests/UI/expected-screenshots/ActionsDataTable_subtables_loaded.png
  plugins/Actions/tests/UI/expected-screenshots/ActionsDataTable_unflattened.png
  plugins/Actions/tests/UI/expected-screenshots/ActionsDataTable_unique_pageview_percentages.png
  plugins/CoreHome/javascripts/dataTable.js
  plugins/CoreHome/stylesheets/dataTable/_dataTable.less
  plugins/CoreVisualizations/javascripts/jqplotBarGraph.js
  plugins/Goals/tests/UI/expected-screenshots/GoalsTable_goals_table_abandoned_carts.png
  plugins/Goals/tests/UI/expected-screenshots/GoalsTable_goals_table_ecommerce_view.png
  plugins/PagePerformance/tests/UI/expected-screenshots/PagePerformance_visualizations.png
  tests/UI/expected-screenshots/Comparison_bar_graph.png
  tests/UI/expected-screenshots/Comparison_normal_table.png
  tests/UI/expected-screenshots/Comparison_normal_table_no_periods.png
  tests/UI/expected-screenshots/Comparison_normal_table_no_segments.png
  tests/UI/expected-screenshots/Comparison_subtables_loaded.png
  tests/UI/expected-screenshots/Comparison_subtables_paginate.png
  tests/UI/expected-screenshots/ViewDataTableTest_0_initial.png
  tests/UI/expected-screenshots/ViewDataTableTest_10_change_limit.png
  tests/UI/expected-screenshots/ViewDataTableTest_11_flattened.png
  tests/UI/expected-screenshots/ViewDataTableTest_12_aggregate_shown.png
  tests/UI/expected-screenshots/ViewDataTableTest_13_make_hierarchical.png
  tests/UI/expected-screenshots/ViewDataTableTest_14_visits_percent.png
  tests/UI/expected-screenshots/ViewDataTableTest_15_search.png
  tests/UI/expected-screenshots/ViewDataTableTest_9_normal_table.png
  tests/UI/expected-screenshots/ViewDataTableTest_dimension_columns.png
  tests/UI/expected-screenshots/ViewDataTableTest_dimension_search.png
  tests/UI/expected-screenshots/ViewDataTableTest_exclude_low_population.png
  tests/UI/expected-screenshots/ViewDataTableTest_flatten_search.png
  tests/UI/expected-screenshots/ViewDataTableTest_limit_selector_open.png
  tests/UI/expected-screenshots/ViewDataTableTest_related_report_click.png
  tests/UI/expected-screenshots/ViewDataTableTest_subtables_loaded.png
  tests/UI/expected-screenshots/ViewDataTableTest_totals_row.png
Labels: c: Design / UI, Needs Review

#22967 Add protocol check in handling of Overlay.startOverlaySession
  plugins/Overlay/templates/startOverlaySession.twig
Labels: Needs Review

#22980 Update version to 5.2.2
  core/Version.php
Labels: not-in-changelog

#22969 Clean up export filenames for Excel compatibility
  core/DataTable/Renderer/Csv.php
  core/Filesystem.php
  plugins/ScheduledReports/ReportEmailGenerator/AttachedFileReportEmailGenerator.php
  tests/PHPUnit/Unit/FilesystemTest.php
Labels: Bug, Needs Review

#22979 Limit the processing time of archiving jobs
  core/CronArchive.php
  plugins/CoreConsole/Commands/CoreArchiver.php
  plugins/CoreConsole/tests/System/ArchiveCronTest.php
Labels: Needs Review, Stability

#22986 Translations update from Hosted Weblate
  lang/tr.json
  plugins/CoreAdminHome/lang/tr.json
  plugins/Feedback/lang/fi.json
  plugins/Login/lang/tr.json
  plugins/PrivacyManager/lang/tr.json
  plugins/UsersManager/lang/tr.json
Labels: c: i18n

#23004 Ensure to remove table prefix only from the beginning
  core/Common.php
  tests/PHPUnit/Unit/CommonTest.php
Labels: Needs Review
