Repository matomo-org/matomo, pull requests merged in 2025-04, with the labels that each got.

#23195 Improve test restoreDbTables for negative numerics
  tests/PHPUnit/Framework/TestCase/SystemTestCase.php
Labels: c: Tests & QA, not-in-changelog, Needs Review

#23202 [automatic composer updates]
  composer.lock
  plugins/API/tests/System/expected/test_AutoSuggestAPITest__Live.getLastVisitsDetails_range.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_latitude__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_longitude__API.getSuggestedValuesForSegment.xml
  plugins/CustomDimensions/tests/System/expected/test___ScheduledReports.generateReport_year.original.pdf
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_in_pdf_tables_only__ScheduledReports.generateReport_week.original.pdf
  plugins/UserCountry/tests/System/expected/test_AttributeHistoricalDataWithLocationsTest_testExecuteShouldReturnLogAfterWorkingWithSomeData__UserCountry.getCity_month.xml
  plugins/UserCountry/tests/System/expected/test___UserCountry.getCity_day.xml
  plugins/UserCountry/tests/System/expected/test_multi_period__UserCountry.getCity_day.xml
  plugins/UserCountry/tests/System/expected/test_multi_periods_and_sites__UserCountry.getCity_day.xml
  plugins/UserCountry/tests/System/expected/test_multi_sites__UserCountry.getCity_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs__Live.getLastVisitsDetails_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs__UserCountry.getCity_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs_complexActionSegment__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs_siteIdThree_TrackedUsingLogReplayWithFixedSiteId__Live.getLastVisitsDetails_range.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_Live.getLastVisitsDetails_sortAsc__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest__UserCountry.getCity_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest__UserCountry.getLocationFromIP.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_pageurlNotContainsSegment__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_segment_city__UserCountry.getCity_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_segment_lat_long__UserCountry.getCity_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_segment_region__UserCountry.getCity_month.xml
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_in_pdf_tables_only__ScheduledReports.generateReport_month.original.pdf
Labels: dependencies

#23180 Adjust email template to add scrollable table
  plugins/CoreHome/templates/ReportRenderer/_htmlReportBody.twig
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_html_tables_and_graph__ScheduledReports.generateReport_week.original.html
  plugins/Ecommerce/tests/System/expected/test_ecommerceOrderWithItems_schedrep_html_tables_only__ScheduledReports.generateReport_week.original.html
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_html_tables_and_graph__ScheduledReports.generateReport_month.original.html
  tests/PHPUnit/System/expected/test_TwoVisitors_twoWebsites_differentDays_schedrep_html_tables_only__ScheduledReports.generateReport_month.original.html
Labels: Needs Review

#23192 Deprecate Clockwork API for SMS
  plugins/MobileMessaging/SMSProvider/Clockwork.php
  plugins/MobileMessaging/tests/UI/MobileMessaging_spec.js
  plugins/MobileMessaging/tests/UI/expected-screenshots/MobileMessaging_admin_provider.png
Labels: Needs Review

#23172 Add a mechanism to remind users to rotate personal auth tokens
  config/global.ini.php
  core/Db/Schema/Mysql.php
  core/Plugin/Tasks.php
  core/Updates/5.4.0-b1.php
  core/Version.php
  plugins/UsersManager/AuthTokenEmailNotification.php
  plugins/UsersManager/Emails/AuthTokenNotificationEmail.php
  plugins/UsersManager/Model.php
  plugins/UsersManager/Tasks.php
  plugins/UsersManager/TokenNotificationProvider.php
  plugins/UsersManager/TokenNotifications/TokenEmailNotification.php
  plugins/UsersManager/TokenNotifications/TokenNotification.php
  plugins/UsersManager/TokenNotifications/TokenNotificationInterface.php
  plugins/UsersManager/TokenNotifications/TokenNotificationProviderInterface.php
  plugins/UsersManager/TokenNotifications/TokenNotifierTask.php
  plugins/UsersManager/lang/en.json
  plugins/UsersManager/templates/_authTokenNotificationHtmlEmail.twig
  plugins/UsersManager/templates/_authTokenNotificationTextEmail.twig
  plugins/UsersManager/tests/Fixtures/Tokens.php
  plugins/UsersManager/tests/Integration/AuthTokenNotificationEmailTest.php
  plugins/UsersManager/tests/Integration/ModelTest.php
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
Labels: Enhancement, c: Security

#23228 Prevent warning when no email is set for current user
  plugins/UsersManager/Controller.php
Labels: Bug

#23234 Improve memory usage of Live.getLastVisitDetails
  plugins/Live/API.php
Labels: Stability

#23235 Improve region name fetching
  plugins/GeoIp2/LocationProvider/GeoIp2.php
Labels: Stability

#23237 Translations update from Hosted Weblate
  lang/be.json
  lang/bg.json
  lang/bs.json
  lang/cy.json
  lang/da.json
  lang/eo.json
  lang/es-ar.json
  lang/eu.json
  lang/fa.json
  lang/gu.json
  lang/he.json
  lang/hi.json
  lang/hr.json
  lang/hu.json
  lang/id.json
  lang/it.json
  lang/ja.json
  lang/ko.json
  lang/lv.json
  lang/nb.json
  lang/pl.json
  lang/pt-br.json
  lang/ro.json
  lang/sk.json
  lang/sl.json
  lang/sr.json
  lang/th.json
  lang/vi.json
  lang/zh-tw.json
  plugins/Goals/lang/be.json
  plugins/Goals/lang/da.json
  plugins/Goals/lang/es-ar.json
  plugins/Goals/lang/hi.json
  plugins/Goals/lang/ko.json
  plugins/Goals/lang/pl.json
  plugins/Goals/lang/sk.json
  plugins/Goals/lang/sl.json
  plugins/Goals/lang/sr.json
  plugins/Goals/lang/vi.json
Labels: c: i18n

#23213 Introduce new API parameter showMetadata
  CHANGELOG.md
  core/API/ApiRenderer.php
  core/DataTable/Renderer.php
  core/DataTable/Renderer/Console.php
  core/DataTable/Renderer/Csv.php
  core/DataTable/Renderer/Html.php
  core/DataTable/Renderer/Json.php
  core/DataTable/Renderer/Rss.php
  core/DataTable/Renderer/Tsv.php
  core/DataTable/Renderer/Xml.php
  plugins/API/Renderer/Csv.php
  plugins/API/Renderer/Html.php
  plugins/API/Renderer/Json.php
  plugins/API/Renderer/Original.php
  plugins/API/Renderer/Rss.php
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/ReportExport/ReportExportPopover.vue
  tests/PHPUnit/Unit/DataTable/Renderer/CSVTest.php
  tests/PHPUnit/Unit/DataTable/Renderer/ConsoleTest.php
  tests/PHPUnit/Unit/DataTable/Renderer/CsvTest.php
  tests/PHPUnit/Unit/DataTable/Renderer/JSONTest.php
  tests/PHPUnit/Unit/DataTable/Renderer/JsonTest.php
  tests/PHPUnit/Unit/DataTable/Renderer/RendererTestCase.php
  tests/PHPUnit/Unit/DataTable/Renderer/TsvTest.php
  tests/PHPUnit/Unit/DataTable/Renderer/XMLTest.php
  tests/PHPUnit/Unit/DataTable/Renderer/XmlTest.php
  tests/UI/expected-screenshots/ReportExporting_Referrers.getWebsites_exported.csv.txt
  tests/UI/expected-screenshots/ReportExporting_Referrers.getWebsites_exported.json.txt
  tests/UI/expected-screenshots/ReportExporting_Referrers.getWebsites_exported.tsv.txt
  tests/UI/expected-screenshots/ReportExporting_Referrers.getWebsites_exported.xml.txt
  tests/UI/expected-screenshots/ReportExporting_RowEvolution_exported.csv.txt
  tests/UI/expected-screenshots/ReportExporting_RowEvolution_exported.json.txt
  tests/UI/expected-screenshots/ReportExporting_RowEvolution_exported.tsv.txt
  tests/UI/expected-screenshots/ReportExporting_RowEvolution_exported.xml.txt
  tests/UI/expected-screenshots/ViewDataTableTest_export_options_2.png
Labels: c: APIs

#23244 Translations update from Hosted Weblate
  lang/el.json
  lang/sq.json
  lang/uk.json
  plugins/CustomDimensions/lang/el.json
  plugins/DevicePlugins/lang/el.json
  plugins/Events/lang/el.json
  plugins/Goals/lang/el.json
  plugins/UsersManager/lang/el.json
  plugins/VisitorInterest/lang/el.json
Labels: c: i18n

#23245 Fix escaping in realtime report
  plugins/Live/templates/index.twig
Labels: Bug

#23248 Prevent automated linking in emails
  core/Twig.php
  plugins/CoreHome/templates/ReportRenderer/_htmlReportBody.twig
  plugins/CoreHome/templates/ReportRenderer/_htmlReportHeader.twig
  plugins/ScheduledReports/API.php
  plugins/ScheduledReports/Controller.php
  tests/PHPUnit/Unit/TwigTest.php
Labels: c: Security, c: Usability

#23257 Make blob archive compression level configurable
  config/global.ini.php
  core/DataAccess/ArchiveWriter.php
  tests/PHPUnit/Integration/DataAccess/ArchiveWriterTest.php
Labels: Enhancement, c: Platform, Needs Review

#23216 Add caching to two Archive loader methods
  core/ArchiveProcessor/Loader.php
  tests/PHPUnit/Fixtures/OmniFixture.php
  tests/PHPUnit/Framework/Fixture.php
  tests/PHPUnit/Integration/Archive/PartialArchiveTest.php
  tests/PHPUnit/Integration/ArchiveProcessor/LoaderTest.php
Labels: Enhancement, c: Performance, Needs Review
