Repository matomo-org/matomo, pull requests merged in 2025-09, with the labels that each got.

#23554 Translations update from Hosted Weblate
  lang/ca.json
  plugins/CoreHome/lang/ca.json
  plugins/IntranetMeasurable/lang/pt-br.json
  plugins/Login/lang/pt-br.json
  plugins/MobileAppMeasurable/lang/pt-br.json
  plugins/PrivacyManager/lang/ca.json
  plugins/UsersManager/lang/ca.json
  plugins/WebsiteMeasurable/lang/pt-br.json
Labels: c: i18n

#23574 [automatic composer updates]
  composer.lock
Labels: dependencies

#23569 Make segment help texts translatable
  core/Columns/Dimension.php
  core/Columns/DimensionSegmentFactory.php
  lang/en.json
  phpstan-baseline.neon
  plugins/Actions/Columns/ActionType.php
  plugins/Actions/Columns/VisitTotalInteractions.php
  plugins/Actions/Columns/VisitTotalSearches.php
  plugins/Actions/lang/en.json
  plugins/Contents/Columns/ContentInteraction.php
  plugins/Contents/Columns/ContentName.php
  plugins/Contents/Columns/ContentPiece.php
  plugins/Contents/Columns/ContentTarget.php
  plugins/Contents/lang/en.json
  plugins/CoreHome/Columns/LinkVisitActionId.php
  plugins/CoreHome/Columns/Profilable.php
  plugins/CoreHome/Columns/UserId.php
  plugins/CoreHome/Columns/VisitId.php
  plugins/CoreHome/Columns/VisitIp.php
  plugins/CoreHome/Columns/VisitorFingerprint.php
  plugins/CoreHome/Columns/VisitorId.php
  plugins/CoreHome/lang/en.json
  plugins/Events/Columns/EventUrl.php
  plugins/Events/Columns/TotalEvents.php
  plugins/Events/lang/en.json
  plugins/UserCountry/Columns/Country.php
  plugins/UserCountry/Columns/Latitude.php
  plugins/UserCountry/Columns/Region.php
  plugins/UserCountry/lang/en.json
  plugins/UserId/lang/en.json
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getSegmentsMetadata.xml
Labels: c: i18n

#23575 Fix edge-case with superuser access revocation
  plugins/UsersManager/UsersManager.php
  plugins/UsersManager/lang/en.json
  plugins/UsersManager/tests/UI/UsersManager_spec.js
  plugins/UsersManager/tests/UI/expected-screenshots/UsersManager_000newuser_view_superuser_tab_current_user.png
  plugins/UsersManager/vue/dist/UsersManager.umd.js
  plugins/UsersManager/vue/dist/UsersManager.umd.min.js
  plugins/UsersManager/vue/src/UserEditForm/UserEditForm.less
  plugins/UsersManager/vue/src/UserEditForm/UserEditForm.vue
Labels: Needs Review

#23581 Don't escape translations in token email, as they might contain encoded entities
  plugins/UsersManager/templates/_authTokenRotationNotificationHtmlEmail.twig
Labels: Regression

#23526 Update CNIL demo to use a new settings architecture
  core/Plugin/Manager.php
  core/Policy/CnilPolicy.php
  core/Policy/CompliancePolicy.php
  core/Policy/PolicyManager.php
  core/Settings/Interfaces/ConfigSettingInterface.php
  core/Settings/Interfaces/MeasurableSettingInterface.php
  core/Settings/Interfaces/OptionSettingInterface.php
  core/Settings/Interfaces/PolicyComparisonInterface.php
  core/Settings/Interfaces/SettingValueInterface.php
  core/Settings/Interfaces/SystemSettingInterface.php
  core/Settings/Interfaces/Traits/Getters/ConfigGetterTrait.php
  core/Settings/Interfaces/Traits/Getters/MeasurableGetterTrait.php
  core/Settings/Interfaces/Traits/Getters/OptionGetterTrait.php
  core/Settings/Interfaces/Traits/Getters/SystemGetterTrait.php
  core/Settings/Interfaces/Traits/PolicyComparisonTrait.php
  core/Settings/Interfaces/Traits/Setters/MeasurableSetterTrait.php
  core/Settings/Interfaces/Traits/Setters/SystemSetterTrait.php
  lang/en.json
  plugins/Live/Live.php
  plugins/Live/Settings/VisitorLog.php
  plugins/Live/lang/en.json
  plugins/PrivacyManager/API.php
  plugins/PrivacyManager/Settings/IPAnonymisation.php
  plugins/PrivacyManager/Settings/IpAddressMaskLength.php
  plugins/PrivacyManager/Settings/ReportRetention.php
  plugins/PrivacyManager/lang/en.json
  plugins/PrivacyManager/tests/Integration/ApiTest.php
  plugins/PrivacyManager/tests/System/APITest.php
  plugins/PrivacyManager/tests/System/expected/test___PrivacyManager.getComplianceStatus.xml
  plugins/PrivacyManager/tests/UI/PrivacyManager_spec.js
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_compliance.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_compliance_different_site.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_compliance_enforced.png
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.js
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.min.js
  plugins/PrivacyManager/vue/dist/umd.metadata.json
  plugins/PrivacyManager/vue/src/Compliance/Compliance.store.ts
  plugins/PrivacyManager/vue/src/Compliance/Compliance.vue
  plugins/PrivacyManager/vue/src/Compliance/ComplianceOverview.vue
  plugins/TwoFactorAuth/vue/dist/umd.metadata.json
  plugins/WebsiteMeasurable/Settings/Ecommerce.php
  plugins/WebsiteMeasurable/lang/en.json
  tests/PHPUnit/Framework/Mock/Policy/PolicyManager.php
  tests/PHPUnit/Framework/Mock/Policy/TestPolicy.php
  tests/PHPUnit/Framework/Mock/Settings/FakePolicySetting.php
  tests/PHPUnit/Framework/Mock/Settings/TraitImpls/PolicyComparisonTraitImpl.php
  tests/PHPUnit/System/expected/test_ImportLogs__PrivacyManager.getCompliancePolicies.xml
  tests/PHPUnit/System/expected/test_OneVisitorTwoVisits__PrivacyManager.getCompliancePolicies.xml
  tests/PHPUnit/System/expected/test_noVisit_PeriodIsLast__PrivacyManager.getCompliancePolicies.xml
  tests/PHPUnit/System/expected/test_noVisit__PrivacyManager.getCompliancePolicies.xml
  tests/PHPUnit/Unit/Policy/CompliancePolicyTest.php
  tests/PHPUnit/Unit/Policy/PolicyManagerTest.php
  tests/PHPUnit/Unit/Settings/PolicyComparisonTraitTest.php
Labels: Needs Review

#23612 Update German translations for Opt-Out messages
  plugins/CoreAdminHome/lang/de.json
Labels: not-in-changelog, c: i18n

#23605 Add "setReferralUrlMaxLength()" to JS Tracker to allow to limit referral cookie size
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
  tests/javascript/index.php
Labels: c: Tracking

#23622 Refactor token notification to only send one email per user with information for multiple tokens
  plugins/UsersManager/Emails/AuthTokenExpirationWarningNotificationEmail.php
  plugins/UsersManager/Emails/AuthTokenRotationNotificationEmail.php
  plugins/UsersManager/Model.php
  plugins/UsersManager/TokenNotifications/AuthTokenExpirationWarningEmailNotification.php
  plugins/UsersManager/TokenNotifications/AuthTokenRotationEmailNotification.php
  plugins/UsersManager/TokenNotifications/TokenEmailNotification.php
  plugins/UsersManager/TokenNotifications/TokenExpirationWarningNotificationProvider.php
  plugins/UsersManager/TokenNotifications/TokenNotification.php
  plugins/UsersManager/TokenNotifications/TokenNotificationInterface.php
  plugins/UsersManager/TokenNotifications/TokenNotificationProvider.php
  plugins/UsersManager/TokenNotifications/TokenNotifierTask.php
  plugins/UsersManager/TokenNotifications/TokenRotationNotificationProvider.php
  plugins/UsersManager/lang/en.json
  plugins/UsersManager/templates/_authTokenExpirationWarningNotificationHtmlEmail.twig
  plugins/UsersManager/templates/_authTokenExpirationWarningNotificationTextEmail.twig
  plugins/UsersManager/templates/_authTokenRotationNotificationHtmlEmail.twig
  plugins/UsersManager/templates/_authTokenRotationNotificationTextEmail.twig
  plugins/UsersManager/tests/Integration/AuthTokenExpirationWarningNotificationEmailTest.php
  plugins/UsersManager/tests/Integration/AuthTokenRotationNotificationEmailTest.php
Labels: Enhancement, c: Usability, Needs Review

#23628 Translations update from Hosted Weblate
  lang/de.json
  lang/el.json
  plugins/Contents/lang/de.json
  plugins/CoreHome/lang/de.json
  plugins/Dashboard/lang/de.json
  plugins/DevicePlugins/lang/de.json
  plugins/Events/lang/de.json
  plugins/Goals/lang/de.json
  plugins/Live/lang/el.json
  plugins/PrivacyManager/lang/de.json
  plugins/PrivacyManager/lang/el.json
  plugins/ScheduledReports/lang/de.json
  plugins/Transitions/lang/de.json
  plugins/UserCountry/lang/de.json
  plugins/UserId/lang/de.json
  plugins/UsersManager/lang/de.json
  plugins/UsersManager/lang/el.json
  plugins/UsersManager/lang/tr.json
  plugins/WebsiteMeasurable/lang/de.json
  plugins/WebsiteMeasurable/lang/el.json
Labels: c: i18n

#23630 Prepare 5.5.0-rc1
  core/Version.php
Labels: not-in-changelog
