Repository matomo-org/matomo, pull requests merged in 2025-06, with the labels that each got.

#23330 Add autofocus attribute to the password field, fix autocomplete attribute
  plugins/Login/templates/confirmPassword.twig
  plugins/Login/templates/confirmResetPassword.twig
  plugins/Login/tests/UI/expected-screenshots/ResetPassword_password_reset_confirm.png
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuth_show_recovery_codes_step1.png
  plugins/TwoFactorAuth/tests/UI/expected-screenshots/TwoFactorAuth_usersettings_twofa_disable_step2.png
  plugins/UsersManager/tests/UI/expected-screenshots/UserSettings_add_token_check_password.png
  plugins/UsersManager/vue/dist/UsersManager.umd.js
  plugins/UsersManager/vue/dist/UsersManager.umd.min.js
  plugins/UsersManager/vue/src/UserSecurity/UserSecurity.vue
Labels: Enhancement, c: Design / UI

#23337 Remove ng-non-bindable unused attribute
  plugins/Login/templates/confirmPassword.twig
  plugins/Login/templates/confirmResetPassword.twig
  plugins/Login/templates/initiateCancelResetPassword.twig
  plugins/Login/templates/login.twig
  plugins/Marketplace/templates/plugin-details.twig
  plugins/ScheduledReports/templates/unsubscribe.twig
Labels: Task, Technical debt

#23348 [automatic composer updates]
  composer.lock
Labels: dependencies

#23356 Automatically clear password input fields after 10 minutes
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.js
  plugins/CoreAdminHome/vue/dist/CoreAdminHome.umd.min.js
  plugins/CoreAdminHome/vue/src/SmtpSettings/SmtpSettings.vue
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/AutoClearPassword/AutoClearPassword.ts
  plugins/CoreHome/vue/src/index.ts
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/PasswordConfirmation/PasswordConfirmation.vue
  plugins/CorePluginsAdmin/vue/src/UploadPluginDialog/UploadPluginDialog.vue
  plugins/Login/templates/confirmPassword.twig
  plugins/Login/templates/confirmResetPassword.twig
  plugins/Login/templates/invitation.twig
  plugins/Login/templates/login.twig
  plugins/Login/tests/UI/Login_spec.js
  plugins/Morpheus/Controller.php
  plugins/Morpheus/tests/UI/Morpheus_spec.js
  plugins/Morpheus/tests/UI/expected-screenshots/Morpheus_load.png
  plugins/Morpheus/tests/UI/expected-screenshots/Morpheus_passwordAutoClear_cleared.png
  plugins/Morpheus/tests/UI/expected-screenshots/Morpheus_passwordAutoClear_filled.png
  plugins/Morpheus/vue/dist/Morpheus.umd.js
  plugins/Morpheus/vue/dist/Morpheus.umd.min.js
  plugins/Morpheus/vue/src/Demo/DemoCodePair.vue
  plugins/UsersManager/vue/dist/UsersManager.umd.js
  plugins/UsersManager/vue/dist/UsersManager.umd.min.js
  plugins/UsersManager/vue/src/UserEditForm/UserEditForm.vue
  plugins/UsersManager/vue/src/UserSecurity/UserSecurity.vue
  tests/UI/expected-screenshots/Theme_demo.png
Labels: Enhancement, c: Security, c: Design / UI

#23358 Add new class for managing password strength
  core/Auth/PasswordStrength.php
  lang/en.json
  tests/PHPUnit/Unit/Auth/PasswordStrengthTest.php
Labels: Needs Review

#23362 Add new System setting for enabling password strength check
  plugins/CoreAdminHome/tests/UI/expected-screenshots/CustomLogoUpload_branding_settings_reloaded_first.png
  plugins/CoreAdminHome/tests/UI/expected-screenshots/CustomLogoUpload_branding_settings_reloaded_second.png
  plugins/CoreAdminHome/tests/UI/expected-screenshots/CustomLogoUpload_custom_favicon_uploaded.png
  plugins/CoreAdminHome/tests/UI/expected-screenshots/CustomLogoUpload_custom_logo_uploaded.png
  plugins/CoreAdminHome/tests/UI/expected-screenshots/CustomLogoUpload_disable_logo_upload.png
  plugins/CoreAdminHome/tests/UI/expected-screenshots/CustomLogoUpload_enable_logo_upload.png
  plugins/Login/SystemSettings.php
  plugins/Login/lang/en.json
  tests/UI/expected-screenshots/UIIntegrationTest_admin_diagnostics_configfile.png
  tests/UI/expected-screenshots/UIIntegrationTest_admin_settings_general.png
  tests/UI/expected-screenshots/UIIntegrationTest_visitors_realtime_visits.png
Labels: Needs Review

#23366 [automatic composer updates]
  composer.lock
  tests/PHPUnit/System/expected/test_apiGetReportMetadata__API.getSegmentsMetadata.xml
Labels: dependencies

#23363 Normalize Script Path in Url::getCurrentScriptName()
  core/Url.php
  tests/PHPUnit/Unit/UrlTest.php
Labels: Task, c: Security, Needs Review

#23370 Update dashboard UI test screenshot after RSS feed change
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_dashboard4.png
Labels: Task, not-in-changelog

#23328 Update codebase to satisfy PHPStan level 1
  core/API/Request.php
  core/ArchiveProcessor.php
  core/AssetManager/UIAssetCacheBuster.php
  core/CliMulti.php
  core/Common.php
  core/Config/IniFileChain.php
  core/CronArchive/SegmentArchiving.php
  core/DataTable/Filter/PivotByDimension.php
  core/DataTable/Map.php
  core/DataTable/Renderer/Csv.php
  core/Http.php
  core/Metrics/Sorter.php
  core/Period/Range.php
  core/Plugin/Manager.php
  core/Plugin/Metric.php
  core/Plugin/Report.php
  core/Segment/SegmentExpression.php
  core/Tracker/Db/Mysqli.php
  plugins/API/ProcessedReport.php
  plugins/CoreAdminHome/Commands/InvalidateReportData.php
  plugins/Referrers/SearchEngine.php
  plugins/SEO/API.php
  plugins/SEO/Metric/Aggregator.php
  plugins/SEO/Metric/Bing.php
  plugins/SEO/Metric/DomainAge.php
  plugins/SEO/Metric/MetricsProvider.php
  plugins/SEO/Metric/ProviderCache.php
  plugins/TestRunner/Commands/CheckDirectDependencyUse.php
Labels: c: Tests & QA, Needs Review, Technical debt

#23382 [automatic composer updates]
  composer.lock
Labels: dependencies

#23378 Add backend password strength checks to password set forms
  core/Auth/PasswordStrength.php
  lang/en.json
  plugins/Login/Controller.php
  plugins/Login/tests/Integration/ControllerTest.php
  plugins/UsersManager/Controller.php
  plugins/UsersManager/tests/Integration/ControllerTest.php
Labels: Needs Review

#23391 Removed Piwik reference from code where possible, #PG-4266
  plugins/Contents/README.md
  plugins/CoreHome/javascripts/broadcast.js
  plugins/CoreHome/javascripts/dataTable.js
  plugins/CoreHome/javascripts/uiControl.js
  plugins/CustomDimensions/docs/faq.md
  plugins/Overlay/client/client.js
  plugins/Overlay/client/urlnormalizer.js
  plugins/UserCountryMap/templates/visitorMap.twig
Labels: Needs Review
