Repository matomo-org/matomo, pull requests merged in 2025-03, with the labels that each got.

#23050 Introduce PHPStan
  .github/scripts/clean-build.sh
  .github/workflows/phpstan.yml
  bootstrap-phpstan.php
  composer.json
  composer.lock
  core/Profiler.php
  phpstan.neon
  plugins/CoreAdminHome/CustomLogo.php
  plugins/DBStats/MySQLMetadataDataAccess.php
Labels: c: Tests & QA, Technical debt

#23074 Fix skip-to-content link
  plugins/CoreHome/templates/_topScreen.twig
Labels: c: Accessibility

#23091 Translations update from Hosted Weblate
  plugins/Diagnostics/lang/fr.json
  plugins/Login/lang/fr.json
  plugins/Marketplace/lang/fr.json
  plugins/MobileMessaging/lang/fr.json
  plugins/MultiSites/lang/de.json
  plugins/MultiSites/lang/fr.json
  plugins/PrivacyManager/lang/de.json
  plugins/PrivacyManager/lang/fr.json
  plugins/ProfessionalServices/lang/fr.json
  plugins/SegmentEditor/lang/de.json
  plugins/SegmentEditor/lang/fr.json
  plugins/SitesManager/lang/fr.json
  plugins/TwoFactorAuth/lang/de.json
  plugins/UsersManager/lang/fr.json
Labels: c: i18n

#23093 Persist search terms and filters when changing dates, date periods or segments
  plugins/CoreHome/javascripts/dataTable.js
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/SearchFiltersPersistence/SearchFiltersPersistence.store.ts
  plugins/CoreHome/vue/src/Widget/Widget.vue
  plugins/CoreHome/vue/src/WidgetLoader/WidgetLoader.vue
  plugins/CoreHome/vue/src/index.ts
  plugins/Dashboard/javascripts/dashboardWidget.js
  plugins/MobileMessaging/vue/dist/umd.metadata.json
  tests/UI/expected-screenshots/SearchFilterPersistenceTest_load_ok.png
  tests/UI/expected-screenshots/SearchFilterPersistenceTest_persisted_date.png
  tests/UI/expected-screenshots/SearchFilterPersistenceTest_persisted_segment.png
  tests/UI/expected-screenshots/SearchFilterPersistenceTest_persisted_sorting.png
  tests/UI/expected-screenshots/SearchFilterPersistenceTest_search_results.png
  tests/UI/specs/SearchFiltersPersistence_spec.js
Labels: c: Usability, c: Design / UI, Needs Review

#23092 Add log message for when sub-processing occurs
  core/ArchiveProcessor/Loader.php
  tests/PHPUnit/Integration/ArchiveProcessor/LoaderTest.php
Labels: Enhancement, c: Platform

#23117 Ensure login username is provided as string value
  plugins/Login/Login.php
Labels: Bug

#23118 Add notification that auth tokens are not revoked when changing passwords
  plugins/UsersManager/UsersManager.php
  plugins/UsersManager/lang/en.json
  plugins/UsersManager/tests/UI/UserSettings_spec.js
  plugins/UsersManager/tests/UI/expected-screenshots/UserSettings_load_security.png
  plugins/UsersManager/tests/UI/expected-screenshots/UserSettings_load_security_new_token.png
  plugins/UsersManager/tests/UI/expected-screenshots/UserSettings_load_security_no_tokens.png
  plugins/UsersManager/vue/dist/UsersManager.umd.js
  plugins/UsersManager/vue/dist/UsersManager.umd.min.js
  plugins/UsersManager/vue/src/UserSecurity/UserSecurity.vue
Labels: Enhancement, c: Usability

#23121 Update columns used for ecommerce goal pages
  plugins/Dashboard/tests/UI/expected-screenshots/Dashboard_dashboard2.png
  plugins/Goals/Visualizations/Goals.php
Labels: Needs Review

#23112 Translations update from Hosted Weblate
  plugins/Goals/lang/uk.json
  plugins/Installation/lang/cs.json
  plugins/JsTrackerInstallCheck/lang/uk.json
  plugins/Live/lang/uk.json
  plugins/Login/lang/el.json
  plugins/Login/lang/ga.json
  plugins/Login/lang/sq.json
  plugins/Login/lang/uk.json
  plugins/MultiSites/lang/ga.json
  plugins/PrivacyManager/lang/ga.json
  plugins/SegmentEditor/lang/ga.json
  plugins/SitesManager/lang/cs.json
  plugins/TwoFactorAuth/lang/uk.json
  plugins/UsersManager/lang/el.json
Labels: c: i18n

#23134 Update disabled site message to include link to site settings
  plugins/PrivacyManager/lang/ca.json
  plugins/PrivacyManager/lang/de.json
  plugins/PrivacyManager/lang/el.json
  plugins/PrivacyManager/lang/en.json
  plugins/PrivacyManager/lang/fr.json
  plugins/PrivacyManager/lang/nl.json
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_delete_visit_cancelled.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_delete_visit_cancelled_verified_no_data_deleted.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_delete_visit_confirmed.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_disabled_site.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_enrich_segment_by_ip.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_no_visits_found.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_uncheck_one_visit.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_gdpr_tools_visits_found.png
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.js
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.min.js
  plugins/PrivacyManager/vue/src/ManageGdpr/ManageGdpr.vue
  plugins/ScheduledReports/vue/dist/umd.metadata.json
  plugins/TwoFactorAuth/vue/dist/umd.metadata.json
Labels: Needs Review

#23136 Ensure parameters are encoded properly
  plugins/SitesManager/SiteContentDetection/WordPress.php
Labels: Needs Review

#23145 Prepare 5.3.1
  core/Version.php
Labels: not-in-changelog

#23154 Update site settings URL in GDPR tool disabled site text
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.js
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.min.js
  plugins/PrivacyManager/vue/src/ManageGdpr/ManageGdpr.vue
  plugins/TwoFactorAuth/vue/dist/umd.metadata.json
Labels: Needs Review

#23157 Ignore all DDEV-generated certs as they may change based on project name
  .ddev/.gitignore
Labels: Task, not-in-changelog

#23141 Translations update from Hosted Weblate
  lang/fi.json
  plugins/CoreAdminHome/lang/fi.json
  plugins/DevicesDetection/lang/fr.json
  plugins/PrivacyManager/lang/ga.json
  plugins/PrivacyManager/lang/sq.json
  plugins/UsersManager/lang/ga.json
Labels: c: i18n

#23138 Improve fault-tolerance of SEOTest integration test
  plugins/SEO/Metric/DomainAge.php
  plugins/SEO/tests/Integration/SEOTest.php
Labels: c: Platform, c: Tests & QA, Needs Review

#23162 Improve ResetPassword UI tests
  plugins/Login/tests/UI/ResetPassword_spec.js
Labels: c: Tests & QA

#23155 Update Lat Long storage to 2dp to meet privacy requirements
  plugins/API/tests/System/expected/test_AutoSuggestAPITest__Live.getLastVisitsDetails_range.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_latitude__API.getSuggestedValuesForSegment.xml
  plugins/API/tests/System/expected/test_AutoSuggestAPITest_longitude__API.getSuggestedValuesForSegment.xml
  plugins/GeoIp2/tests/Integration/LocationProviderTest.php
  plugins/PrivacyManager/tests/System/expected/anonymizeVisitInformation_allSitesAllDates.json
  plugins/PrivacyManager/tests/System/expected/anonymizeVisitInformation_restrictDate.json
  plugins/PrivacyManager/tests/System/expected/anonymizeVisitInformation_restrictSites.json
  plugins/UserCountry/LocationProvider.php
  plugins/UserCountry/tests/System/expected/test_AttributeHistoricalDataWithLocationsTest_testExecuteShouldReturnLogAfterWorkingWithSomeData__UserCountry.getCity_month.xml
  plugins/UserCountry/tests/System/expected/test___UserCountry.getCity_day.xml
  plugins/UserCountry/tests/System/expected/test_multi_period__UserCountry.getCity_day.xml
  plugins/UserCountry/tests/System/expected/test_multi_periods_and_sites__UserCountry.getCity_day.xml
  plugins/UserCountry/tests/System/expected/test_multi_sites__UserCountry.getCity_month.xml
  plugins/UserCountryMap/tests/UI/expected-screenshots/VisitorMap_cities.png
  tests/PHPUnit/System/expected/test_ImportLogs__Live.getLastVisitsDetails_range.xml
  tests/PHPUnit/System/expected/test_ImportLogs__UserCountry.getCity_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs_complexActionSegment__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_ImportLogs_siteIdThree_TrackedUsingLogReplayWithFixedSiteId__Live.getLastVisitsDetails_range.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_Live.getLastVisitsDetails_sortAsc__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest__UserCountry.getCity_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest__UserCountry.getLocationFromIP.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_pageurlNotContainsSegment__Live.getLastVisitsDetails_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_segment_city__UserCountry.getCity_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_segment_lat_long__UserCountry.getCity_month.xml
  tests/PHPUnit/System/expected/test_ManyVisitorsOneWebsiteTest_segment_region__UserCountry.getCity_month.xml
Labels: Needs Review

#23161 Suppress errors when trying to access javaEnabled property
  js/piwik.js
  js/piwik.min.js
  matomo.js
  piwik.js
Labels: Bug

#23182 [automatic composer updates]
  composer.lock
Labels: dependencies

#23184 Improve release check list tests
  .github/scripts/clean-build.sh
  tests/PHPUnit/Integration/ReleaseCheckListTest.php
Labels: c: Tests & QA
