Repository matomo-org/matomo, pull requests merged in 2025-08, with the labels that each got.

#23473 Fix site filters not initially being applied
  plugins/CoreHome/vue/dist/CoreHome.umd.js
  plugins/CoreHome/vue/dist/CoreHome.umd.min.js
  plugins/CoreHome/vue/src/SiteSelector/SiteSelector.vue
  plugins/CoreHome/vue/src/SiteSelector/SitesStore.spec.ts
  plugins/CoreHome/vue/src/SiteSelector/SitesStore.ts
Labels: Needs Review

#23466 Create skeleton CNIL compliance page behind feature flag
  plugins/PrivacyManager/Controller.php
  plugins/PrivacyManager/FeatureFlags/PrivacyCompliance.php
  plugins/PrivacyManager/Menu.php
  plugins/PrivacyManager/PrivacyManager.php
  plugins/PrivacyManager/lang/en.json
  plugins/PrivacyManager/templates/compliance.twig
  plugins/PrivacyManager/tests/UI/PrivacyManager_spec.js
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_compliance.png
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.js
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.min.js
  plugins/PrivacyManager/vue/src/Compliance/Compliance.vue
  plugins/PrivacyManager/vue/src/index.ts
Labels: Needs Review

#23485 Ignore dynamically created local static sites for tracking testing
  .ddev/.gitignore
  .gitignore
Labels: Task, not-in-changelog

#23413 Ensure partial archives are marked correctly
  core/ArchiveProcessor/Loader.php
  core/ArchiveProcessor/Parameters.php
  core/Plugin/Archiver.php
  plugins/Goals/tests/System/ProcessDependentArchiveTest.php
  tests/PHPUnit/Integration/Archive/PartialArchiveTest.php
  tests/PHPUnit/Integration/ArchiveProcessingTest.php
  tests/PHPUnit/Integration/ArchiveTest.php
  tests/PHPUnit/Integration/DataAccess/ArchiveWriterTest.php
Labels: Needs Review, Stability

#23508 Add rule to prevent imports from vue/src that cause hard-to-debug build issues
  .eslintrc.js
Labels: Task, not-in-changelog

#23502 Create CNIL demo page
  plugins/PrivacyManager/PrivacyManager.php
  plugins/PrivacyManager/lang/en.json
  plugins/PrivacyManager/stylesheets/compliance.less
  plugins/PrivacyManager/tests/UI/PrivacyManager_spec.js
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_compliance.png
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.js
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.min.js
  plugins/PrivacyManager/vue/dist/umd.metadata.json
  plugins/PrivacyManager/vue/src/Compliance/Compliance.store.ts
  plugins/PrivacyManager/vue/src/Compliance/Compliance.vue
  plugins/PrivacyManager/vue/src/Compliance/ComplianceOverview.vue
  plugins/PrivacyManager/vue/src/Compliance/ComplianceTable.vue
  plugins/TwoFactorAuth/vue/dist/umd.metadata.json
Labels: Needs Review

#23509 update CNIL demo to use placeholder APIs to retrieve data
  plugins/PrivacyManager/API.php
  plugins/PrivacyManager/PrivacyManager.php
  plugins/PrivacyManager/lang/en.json
  plugins/PrivacyManager/tests/System/expected/test___PrivacyManager.getComplianceStatus.xml
  plugins/PrivacyManager/tests/UI/PrivacyManager_spec.js
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_compliance.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_compliance_different_site.png
  plugins/PrivacyManager/tests/UI/expected-screenshots/PrivacyManager_compliance_enforced.png
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.js
  plugins/PrivacyManager/vue/dist/PrivacyManager.umd.min.js
  plugins/PrivacyManager/vue/src/Compliance/Compliance.store.ts
  plugins/PrivacyManager/vue/src/Compliance/Compliance.vue
  plugins/PrivacyManager/vue/src/Compliance/ComplianceOverview.vue
  plugins/TwoFactorAuth/vue/dist/umd.metadata.json
Labels: Needs Review

#23522 Change version to next alpha
  core/Version.php
Labels: not-in-changelog

#23527 Fix PHPStan issues in plugins/SitesManager/SiteContentDetection
  phpstan-baseline.neon
  plugins/SitesManager/SiteContentDetection/ConsentManagerDetectionAbstract.php
  plugins/SitesManager/SiteContentDetection/Matomo.php
  plugins/SitesManager/SiteContentDetection/SiteContentDetectionAbstract.php
  plugins/SitesManager/SiteContentDetection/VueJs.php
  plugins/SitesManager/SiteContentDetection/WordPress.php
Labels: not-in-changelog, Technical debt

#23525 [automatic composer updates]
  composer.lock
Labels: dependencies

#23530 Don't show install all plugins button if marketplace is disabled
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.js
  plugins/CorePluginsAdmin/vue/dist/CorePluginsAdmin.umd.min.js
  plugins/CorePluginsAdmin/vue/src/PluginsIntro/PluginsIntro.vue
Labels: Bug, c: Usability

#23536 Avoid sending notifications to empty recipients
  plugins/UsersManager/TokenNotifications/TokenEmailNotification.php
  plugins/UsersManager/TokenNotifications/TokenExpirationWarningNotificationProvider.php
  plugins/UsersManager/TokenNotifications/TokenRotationNotificationProvider.php
  plugins/UsersManager/UserNotifications/UserEmailNotification.php
Labels: not-in-changelog, Regression

#23543 Fix Bing SEO metric test skip
  plugins/SEO/tests/Integration/SEOTest.php
Labels: c: Tests & QA

#23520 Send user invite acceptance notification in inviter's language
  core/Http.php
  plugins/Login/Controller.php
  plugins/UsersManager/tests/Integration/UserInviteAcceptanceTest.php
Labels: Enhancement, Needs Review
